<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">3 . 1 - 24 Este capítulo, en torno a la caída de la humanidad, introduce dos temas dominantes en la teología del AT: 1) Dios es una persona y es un Dios salvador; 2) el ser humano es pecador. El lector no podrá comprender plenamente la Biblia si no hace suyas estas dos grandes verdades.
3 . 1 La serpiente es identificada en Rev 12:9 como el mismo Satanás, aquí en una forma corpórea. No está claro por qué escogió a la serpiente entre todos los animales . . . que Jehová Dios había hecho. Más adelante, el relato del AT menciona a la serpiente entre los animales inmundos (Lv 11). Es astuta , fuerte y escurridiza. Conque Dios os ha dicho : «Todo esto no es suficiente», sugiere el tentador. «¡Puedes tener más!» La pregunta fue hábilmente reformulada: ¿ De todo árbol ?
3 . 2 , 3 La respuesta de la mujer revela su inocencia original, pero la serpiente la hizo reconsiderar el asunto.
3 . 4 Esta descarada mentira puede ser traducida: «¿Morir? ¡No moriréis!». Es decir, «Dios os ha amenazado falsamente con la muerte».
3 . 5 Seréis como Dios : La tentadora sed de poder puede ser inagotable, aun cuando la gente tenga cubiertas todas sus necesidades. Sabiendo encierra el significado de «experimentando»; lo cual hacía que el reto fuese ahora mayor: «Dios los está privando de algo bueno (la autonomía) para mantenerlos dependientes de él».
3 . 6 El deseo de alcanzar la sabiduría le pareció razonable a la mujer. Desafortunadamente, su definición de la sabiduría era la autonomía humana, no la dependencia de Dios, como se enseña en Pro 1:7.
3 . 7 Estaban desnudos : La «sabiduría» recién obtenida por Adán y Eva no les trajo el prometido conocimiento del bien y el mal, sino la vergüenza de descubrir que estaban desnudos.
3 . 8 Los pecadores siempre se han escondido de la presencia de Jehová Dios , y lo continuarán haciendo: «Escondednos del rostro de aquel que está sentado en el trono» (Rev 6:16).
3 . 9 Jehová Dios no preguntaba porque ignorara, sino como un padre que se dirige a un hijo desobediente para decirle: «¿Qué has estado haciendo?»
3 . 12 , 13 Aparece por primera vez otra debilidad humana: el hombre culpa a la mujer y a Dios. La mujer también trata de evadir la culpa.
3 . 14 , 15 Maldita serás encierra la idea de estar bajo el juicio de Dios. Aunque el significado exacto de que la serpiente haya sido maldecida entre todas las bestias no está claro, Pablo confirma más tarde la idea de que toda la creación fue afectada por la caída de Adán (Rom 8:20-22). Sobre tu pecho andarás no significa que la serpiente haya tenido patas antes; más bien parece una forma poética de decir que el mundo animal no podría recuperar por sí solo su condición anterior a la caída. Polvo comerás también es símbolo de extrema humillación.
Las alusiones del NT al v. 15 (Rom 16:20; Heb 2:14; Ap 12) parecen indicar que la maldición a la serpiente tiene una más amplia aplicación. Interpretada mesiánicamente, la enemistad representa el conflicto entre Satanás (tu simiente) y el pueblo de Dios, especialmente Jesucristo (la simiente suya). Esta te herirá en la cabeza , y tú le herirás en el calcañar alude a la larga lucha entre el bien y el mal, que Dios gana al fin por medio de Jesucristo, el segundo Adán. A menudo se cita el v. 15 como la primera profecía mesiánica del AT, el «Protoevangelio».
3 . 15 cabeza, rosh (rohsh ; Strong #7218: Cabeza, la cabeza (del cuerpo humano); la cabeza de una fila; lo que es principal o supremo; primero, tope, príncipe, la parte más alta, cúspide, comienzo, líder, primordial y jefe. Así como la «cabeza» de una compañía se referiría a su ejecutivo principal, rosh se usa para mostrar liderazgo. En 3.15, la promesa es que la «simiente de la mujer» algún día aplastaría la «cabeza de la serpiente», esa mujer en particular tendría parte en el acto de deshacer los efectos de la caída. En su sentido más específico, el Señor Jesús aplastó a Satanás en la cruz. En su sentido más amplio, la raza humana llegará a triunfar completamente sobre el Maligno (Rom 16:20).
3 . 15 La primera proclamación del evangelio , LA VENIDA DEL MESíAS. Este versículo contiene la primera proclamación del evangelio. Aquí encontramos, en forma resumida, toda la riqueza, misericordia, dolor y gloria de la obra redentora de Dios para con la humanidad. Dios promete traer un Redentor de la «simiente de la mujer»; será completamente humano, pero concebido divinamente. «La serpiente antigua, que se llama diablo y Satanás», hará guerra a la «simiente» (véase Ap 12) y la morderá. Pero mientras la serpiente muerde su calcañar, su pie desciende aplastando la cabeza de la serpiente. En la vida y la muerte de Cristo se cumplió esta Escritura. Concebido divinamente, pero completamente humano, derrotó y exhibió públicamente a los poderes del infierno mediante su vida, muerte y resurrección (Col 2:15). Esta primera promesa mesiánica es una de las aseveraciones más sucintas del evangelio que podamos hallar.(*/Deu 18:18-19) J.H.
3 . 16 La mujer no es directamente objeto de maldición, aunque resulta obvio que se halla bajo la condena general a causa del pecado. Por otro lado, se destaca su papel como esposa y madre. La maternidad traerá consigo grandes sufrimientos, algo especialmente desalentador para las mujeres del AT, quienes veían las familias numerosas como señal de bendición. Tu deseo será para tu marido es algo difícil de traducir del hebreo. La expresión parece referirse a que, en oposición a la armonía que existía en el Edén, de ahí en adelante la mujer intentaría dominar a su compañero. él se enseñoreará de ti establece el papel asignado por Dios al esposo como siervo y cabeza de la familia. No existe evidencia alguna de que la intención haya sido disminuir la persona o atribuciones de la mujer, sino asignar al marido la responsabilidad de cuidar de ella como una vía para restablecer la antigua armonía entre ambos. Nota: el pasaje no reconoce al hombre derecho alguno sobre la mujer, sino que asigna al esposo la responsabilidad de guiar la relación matrimonial (véase Eph 5:22-33).
3 . 17 - 19 Adán tampoco es maldecido directamente. Su peor error fue obedecer a la voz de su mujer , en lugar de a la voz de Dios. Como tenía la máxima responsabilidad, su condena es la más amplia y comprensiva. Con dolor comerás de ella : Destaca el papel fundamental del hombre como trabajador y proveedor; el trabajo estará lleno de dificultades y decepciones (Espinos y cardos te producirá . . . con el sudor de tu rostro). Esta lucha de toda la vida terminará con la muerte.
3 . 17 El importante rol de la humanidad en los asuntos terrenales , VALOR HUMANO. Desde la perspectiva de su papel estratégico, debemos asumir que la humanidad es más valiosa que cualquier otra cosa en la tierra. Ninguna otra forma de vida terrenal desempeña un papel cósmico tan importante como la humanidad. Literalmente, el mundo se sostiene o se cae por las acciones humanas. Sólo los humanos tienen el poder de agotar los recursos de la tierra y de contaminar la atmósfera. El pecado de un ser humano, Adán, corrompió el mundo. La continua pecaminosidad de la humanidad causó el diluvio (6.12, 13). En contraste con esto, la obediencia de Jesucristo trajo justificación y justicia a muchos (Rom 5:18-19). Si los hombres y las mujeres redimidos anduvieran en esa justificación y justicia, ¿no podrían hacer florecer al mundo? Dios desea revelar su verdad y belleza al mundo sólo por medio de la humanidad redimida. Cada creyente tiene un significado estratégico en su propia esfera; todos debemos tratar de aumentar la contribución del bien y animar a otros a hacer lo mismo.(Psa 8:4-8/Gen 9:5-6) C.B.
3 . 22 - 24 La maldición es reforzada por la expulsión de Adán y Eva del huerto , lugar donde mantuvieron íntima comunión con Dios. Querubines y una espada encendida que se revolvía por todos lados impedían su regreso a aquel lugar. La lección está clara: no habrá comunión con Dios si éste no toma la iniciativa.
3 . 21 La sangre cubre, LA SANGRE. El pacto de amor de Dios requería que se sacrificaran animales inocentes para proveer vestidos de piel a Eva y Adán. Esta figura temprana de la propiciación sustitutiva señala la necesidad del juicio sobre el inocente, a fin de proveer cobertura al culpable. Adán y Eva hicieron un vano intento de cubrirse a sí mismos mediante sus propios esfuerzos, al fabricar vestidos de hojas de higuera. Sin embargo, el orden de Dios proveyó cobertura por medio del sacrificio. Bajo el nuevo pacto, se requiere que nos revistamos de Cristo más bien que de nuestras buenas obras (Gal 3:27).(Heb 9:12/Mat 26:28) C.S..
3 . 21 La restauración «En el principio», RESTAU-RACIóN. Génesis 1-3 revela las formas restauradoras de Dios «en el principio». El concepto del «Espíritu Santo y la restauración» se desarrolla en el artículo del mismo nombre que comienza en la página 1758.(Job 42:10-12/Gen 6:5) J.R.
3 . 24 Los querubines , áNGELES. Los querubines son seres creados, a los cuales se les ha asignado la protección del trono de Dios (Psa 99:1), así como la protección del arca del pacto y el propiciatorio (Exo 25:18-22; Exo 37:7-9). Los querubines resguardaban el árbol de la Vida, para que los seres humanos no comieran de él, y vivieran así para siempre en sus pecados. Por lo tanto, en contradicción con la opinión popular, más de un ángel protegía la entrada al Edén. La descripción más detallada de los querubines se encuentra en Ezequiel 10, donde se les relaciona estrechamente con la gloria de Dios y forman parte de la hueste celestial.(Is 6.2/Jud 1:9) M.H.</p>
<br/>




</div>
