<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">1 . 1 creó, bara Strong #1254: Formar, hacer, producir, crear. Originalmente este verbo encerraba la idea de «tallar» o «suprimir»; ese concepto aún se expresa mediante la forma verbal que encontramos en Jos 17:18, que significa «derribar» árboles para «preparar la tierra para la labranza». Esto sugiere que crear es similar a esculpir. Por lo tanto, baraes la palabra apropiada para describir tanto el proceso de crear algo de la nada como el de moldear lo existente para crear algo nuevo, tal cual hizo Dios al crear al hombre (Gen 1:27) del polvo de la tierra. Dios es siempre el sujeto del verbo baraen su forma común; el crear es, por lo tanto, un atributo divino.
1 . 1 En el principio creó Dios : Traducción tradicional de lo que hasta cierto punto es una compleja y debatida fórmula gramatical hebrea. Otras traducciones posibles han aparecido durante el último siglo, pero presuponen la existencia de un caos material, o hasta de una raza preadámica, antes que comenzara la creación descrita en el cap. 1. Nada en lo que resta de Génesis, ni en la Biblia como un todo, requiere o recomienda necesariamente esa interpretación, aunque tales opiniones son bíblicamente tolerables. De todos modos, la traducción más directa y aceptable es la que aquí se utiliza.
1 . 2 Se nos informa aquí de las consecuencias del primer acto creador de Dios: la tierra estaba desordenada (carente del orden que reinaría en ella cuando se completara el mandato de Dios) y las tinieblas estaban sobre la faz del abismo (una referencia adicional a la ausencia del orden y la belleza que aparecerían dentro de seis días). Ambas afirmaciones revelan que la creación constituyó un reflejo del proceso normal utilizado por Dios para introducir el orden en el caos. El abismo es el océano primitivo que se hallaba bajo la tierra (véase 7.11). Se movía connota algo que no permanece estacionario. El Espíritu Santo es el «brazo ejecutivo» de la Trinidad, por lo que se mantenía activo mientras Dios pronunciaba cada una de sus palabras. Una interpretación alterna, que señala la posibilidad de que la creación inicial descrita en Gen 1:1 haya sido alterada (posiblemente a causa de la caída de Lucifer), no es bíblicamente objetable, pero tampoco es verificable.
1 . 3 El primer mandato divino da inicio al proceso de transformar el caos. Dijo Dios se repetirá diez veces en el cap. 1 como medio de hacer surgir el orden y la vida. La forma exacta como se relacionan las tres personas de la Trinidad es un proceso que no se define con claridad en la Biblia (véase Col 1:16). La luz alude al efecto luminoso en general, porque los cuerpos celestes son creados en el cuarto día (vv. 14-19).
1 . 3 - 5 Dios , el hacedor de pactos, LA SANGRE. Desde el principio, Dios se revela como autor de pactos. Jeremías se refirió a esa actividad de Dios en la creación (Jer 33:20), al hablar del «pacto con el día y la noche». Así se destaca el inalterable carácter de la naturaleza divina y representa su relación con lo creado como una unión inmutable bajo el soberano gobierno de Dios.(*/Gen 8:20) C.S..
1 . 4 Era buena : Fórmula de aprobación divina que se repetirá siete veces para enfatizar la calidad y lo idóneo de la creación. Contrasta con la descripción del estado de la creación después de la caída (cap. 3).
1 . 5 Y fue la tarde y la mañana : Para los hebreos cada nuevo día comenzaba con el crepúsculo. Esta forma de calcular el tiempo, junto con el recuento de los días y el descanso sabatino en el séptimo día, muestra que el autor ve la creación como algo que ocurre en el transcurso de seis períodos consecutivos de 24 horas, seguido de un séptimo período de descanso divino.
1 . 6 , 7 Y separe las aguas de las aguas : La tierra cubierta por las aguas parece que estaba rodeada de vapor. Dios usó la expansión , el espacio entre la superficie y las nubes, para separar las dos «aguas», creando una acumulación masiva de vapor en las alturas (mabbul en hebreo). Estas aguas que estaban sobre la expansión creaban un protector «efecto de invernadero» sobre la tierra de ese período.
1 . 8 Cielos : Véase la definición del firmamento en la nota al v. 6.
1 . 9 , 10 El tercer día marcó la aparición de la tierra al definirse el límite (Júntense las aguas que están debajo de los cielos en un lugar) de los Mares.
1 . 11 , 12 Dios mandó que la tierra , con su potencial productivo, diera vida al reino de las plantas. Según su género : Las leyes de la genética divina se impusieron al mundo vegetal.
1 . 21 Grandes monstruos marinos : Las más extraordinarias criaturas del océano, tales como ballenas y delfines. Según su especie : Otra vez, las leyes de la genética que imposibilita cualquiera evolución de un género en otro; un gorrión jamás podrá producir un buitre.
1 . 24 Bestias : Término genérico que designa todo tipo de animales domésticos; serpientes alude a los reptiles, insectos, y así por el estilo; animales de la tierra se refiere a las especies de animales salvajes. Junto con los mencionados en el v. 21 representan la totalidad del mundo animal.
1 . 26 Hagamos : Dios estaba hablando no sólo en nombre de lo que se revela como la Trinidad en el NT, sino de toda la hueste celestial, incluyendo los ángeles. Nuestra imagen parece referirse a tales cualidades como la razón, la personalidad y el intelecto, y a las capacidades de relacionar, escuchar, ver y hablar. Todas estas son aptitudes que Dios decidió otorgar a los seres humanos. Y señoree . . . en toda la tierra : Dios creó al hombre para ser el agente de su reino, para gobernar y someter al resto de la creación, incluyendo las agresivas fuerzas satánicas, que pronto la invadirían.
1 . 26 hombre, adam Strong #120: Hombre, humanidad, Adán el primer hombre o la humanidad en general. Adam se traduce en el Antiguo Testamento como «Adán» (el nombre propio) unas 20 veces y como «hombre», en más de 500. Frecuentemente, cuando la Biblia se refiere a toda la raza humana, se usa la frase bnay adam los «hijos de los hombres». La palabra hebrea adam en su sentido general, no tiene nada que ver con masculinidad, sino más bien con humanidad. Por ejemplo, en un caso específico, adam se refiere exclusivamente a la mujer (Num 31:35) Adam probablemente se relaciona con el verbo adom el ser rojo, que se refiere a la hermosura del ser humano. Adamah «tierra» o «terreno», también podría derivarse de este verbo. De ahí que Gen 2:7 diga: «Entonces Jehová Dios formó adam del polvo de adamah . En 1Co 15:47 Pablo ve a Adán como hombre terrenal. Adam es una de las cuatro principales palabras hebreas para «hombre» que se usan en la Biblia. Véanse también enosh ish y geber
1 . 26 - 28 Dios creó al hombre ( varón y hembra ) a su propia imagen, ORDEN FAMILIAR. Estos versículos contienen una frase que es la piedra angular del entendimiento bíblico de la humanidad: imagen de Dios. La imagen de Dios se presenta principal y primordialmente en relación con un singular concepto social o comunitario de Dios. «Entonces dijo Dios [singular]: “ Hagamos [plural] al hombre a nuestra [plural] imagen». Muchos estudiosos interpretan el uso, tanto del singular como del plural, como una alusión a la Trinidad: un Dios en una comunidad de personas.
Dios procede entonces a crear al hombre a su imagen. En ese trascendental momento, la Escritura señala un aspecto particular de la naturaleza humana; es decir, aquello que corresponde al aspecto social o comunitario de la naturaleza divina: Dios crea al ser humano como hombre y mujer; no como un individuo solitario, sino como dos personas. Sin embargo, al continuar nuestra lectura, descubrimos que los dos son, no obstante, «uno» (véase 2.24).
La «comunidad»
que refleja la imagen de Dios es especial: la comunidad de una mujer y un hombre. Cuando Dios eligió crear a la humanidad a su imagen, creó el matrimonio, una familia. La comunidad de la familia constituye un reflejo de la comunidad de la divinidad. Su identidad, vida y poder provienen de Dios. (*/Eph 3:14-15) L.C.
1 . 26 - 28; 2 . 16 , 17 El dominio «delegado» a la humanidad, LOS FUNDAMENTOS DEL REINO. Al crear al ser humano, el Soberano del universo decidió delegar a la humanidad el señorío sobre la tierra (v. 28). El poder y la autoridad humana para el ejercicio de este señorío se originan en el deseo divino de hacer a los seres humanos a su propia imagen y semejanza. La habilidad humana para regir la tierra descansará en su continua obediencia a la autoridad de Dios como Señor de la creación. Su poder para reinar en la vida dependerá de su fidelidad a la hora de obedecer la ley divina. Véase también 1Ch 29:10-16.
(Gen 1:1/Gen 1:31)
L.W.H.</p>
<br/>




</div>
