<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 2</h2>
<p class="text-justify">2 . 1 La obra de la semana de la creación ha finalizado: la tierra es habitable, ha sido creada la vida, el hombre ejerce su dominio sobre lo creado, hay alimentos para todos. Sin embargo, el papel de Dios no ha concluido; el poder que sostiene la creación obra hasta hoy día.
2 . 2 , 3 Reposó significa que Dios se abstuvo de seguir creando al haber terminado toda la obra que hizo . El día séptimo : Creado para bien del ser humano, el día de reposo fue ordenado por Dios y lo santificó en el sentido de que quienes lo observaran se harían acreedores a las bendiciones divinas. Así, Dios estableció la semana de siete días como parte del orden universal.
2 . 4 Orígenes : Literalmente «generaciones», que significa «linaje», una palabra que aparece 11 veces en Génesis; término usualmente utilizado para introducir una nueva genealogía o narración. Este capítulo presenta la creación desde una perspectiva diferente, más localizada y centrada en el ser humano.
2 . 5 , 6 Dejando a un lado gran cantidad de detalles contenidos en el cap. 1, estos versículos corresponden a 1.2. Un vapor : Probablemente «un manantial» o «agua fresca del océano»; el agua de las profundidades estaba surgiendo aparentemente en la todavía indefinida tierra (continentes).
2 . 7 Formó : Seis de los términos hebreos utilizados en estos primeros capítulos para describir el proceso de la creación son muy similares, así que los traductores modernos emplean en cada ocasión palabras diferentes para que el lector sepa que está ante un término hebreo distinto. Todos ellos se aplican a la actividad creadora de Dios: bara (1.1), «crear»; asah (1.7), «hacer»; nathan (1.17), «poner»; yatsar (2.7) «formar»; banah (2.22), «hacer» o «edificar»; y qanah (4.1; 14.19), «crear», «poseer» o «adquirir». Un momento muy especial fue aquel cuando el Creador sopló en su nariz aliento de vida . «En él estaba la vida» (Joh 1:4), y le dio a la humanidad esa vida preciosa que sólo Dios puede dar.
2 . 8 Un huerto alude a un lugar real; no es una simple alegoría. En Edén , al oriente : Indica una región que se halla al este del actual Israel, en algún lugar de Mesopotamia o Arabia.
2 . 9 En esa fértil reserva natural se encontraban los dos árboles alrededor de los cuales giraría toda la historia humana de ahí en adelante. Eran los medios materiales utilizados por Dios para comunicar realidades espirituales. El árbol de vida se asocia con la vida de Dios, incluyendo la inmortalidad. El árbol de la ciencia del bien y del mal representa la autonomía humana, esto es, el gobernarse a sí mismo y asumir una postura independiente frente a Dios en todas las esferas de la vida.
2 . 10 - 14 Dos de los cuatro ríos han sido identificados: Hidekel (el Tigris) y el éufrates . Bedelio es una resina aromática amarillenta.
2 . 17 La tragedia de la autonomía humana se evidencia en la advertencia divina: ciertamente morirás . La autonomía humana incluye la muerte, que se extiende al ser espiritual, moral, social, relacional y, en última instancia, al físico.
2 . 18 Ayuda : Indica que Adán no era capaz de alcanzar por sí solo todo lo que estaba llamado a ser y a hacer. Idónea para él denota complementariedad. La ayuda es necesaria para el trabajo diario, la procreación, y el apoyo y compañía mutuos.
2 . 19 Ese es su nombre : Confirma lo que Dios había dicho al hombre en el cap. 1: «Y señoread» sobre la tierra y sus criaturas. Aquel que detenta la autoridad está llamado a nombrar a los miembros de la comunidad de la cual es responsable.
2 . 21 Una de sus costillas : Como en otros milagros de la Escritura, Dios comienza con una «pieza», como el plato de comida del cual Elías se alimentó durante dos años y medio, y los panes y peces con que Jesús dio de comer a las cinco mil personas. La costilla fue probablemente seleccionada como parte simbólica de lo más íntimo de la anatomía de Adán.
2 . 24 Dejará : Connota un cambio de prioridades por parte de quien contrae matrimonio. Y se unirá encierra la idea de pasión amorosa y a la vez permanencia. Una sola carne supone cierto número de implicaciones, que incluyen la unión sexual, la concepción de los hijos, la intimidad espiritual y emocional, y el mostrarse el mismo respeto que se guarda a los padres o parientes cercanos. Esto se complementa en el NT, donde se aclara que los esposos cristianos son además hermano y hermana entre sí.</p>
<br/>




</div>
