<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 49</h2>
<p class="text-justify">49 . 1 - 28 Esta no es solamente una profecía, sino también una bendición (véase v. 28); es también una maldición para algunos de los hijos de Jacob. Este habló con autoridad, desde la perspectiva de la fe; por lo tanto, sus palabras estuvieron llenas de vigor, y tendrían un efecto significativo sobre las futuras generaciones. Jacob reservó sus mejores bendiciones para Judá y José; sus descendientes se convirtieron en las tribus dominantes de Israel; Judá en el sur, y Efraín y Manasés en el norte. Típica de una antigua bendición semita en los umbrales de la muerte, hay implicaciones colectivas en algunas de estas afirmaciones, como si Jacob estuviese algunas veces hablando no solamente de sus hijos como individuos, sino también de sus descendientes.
49 . 3 , 4 Rubén debía haber recibido la bendición preeminente porque era el primogénito. Pero se envileció al subir al lecho de su padre , esto es, cuando «durmió con Bilha» (35.22), la concubina de Jacob. De ahí que perdiera la posición principal y sus descendientes se convirtieron en un pueblo de pastores al este del Jordán (Num 32:1-33).
49 . 5 - 7 Jacob temía a sus dos hijos siguientes, los hermanos Simeón y Leví, «¡tal para cual!» Un ejemplo de su iniquidad (o violencia) fue la matanza de Siquem (34.25-31). Simeón fue pasado por alto en la futura bendición de Moisés (Dt 33); aparentemente fueron absorbidos por Judá (Jos 15:20-63; Jos 19:1-9). Como los levitas fueron los primeros en retornar a Dios después del incidente del becerro de oro, se alzaron como la tribu encargada de ofrecer servicios sacerdotales especiales (Num 3:12-13, Num 3:41). Su historia en el AT fue de devoción vacilante.
49 . 8 - 12 Judá era el siguiente por orden de nacimiento, así que Jacob le concedió la bendición del primogénito. Gobernaría sobre Israel y sobre todas las naciones. Las predicciones de Jacob se cumplieron porque Siloh (el Mesías) vendría de la tribu de Judá.
49 . 11 , 12 Utilizando un lenguaje altamente simbólico, Jacob profetiza la era del Mesías como paradisíaca. Habrá abundancia de comida, vitalidad y salud. La gente se llenará de vino y leche .
49 . 10 Siloh, shiloh Strong #7886: Siloh era una de las ciudades donde se colocó el tabernáculo (Jos 18:1). Aquí, en el libro del Génesis, parece ser un nombre propio o título, el cual los creyentes generalmente aceptan como una designación mesiánica de Jesús. Su etimología es incierta. Para algunos shiloh significa «el pacífico». Según otro punto de vista, shiloh es un sustantivo con un sufijo pronominal que debe entenderse como «su hijo»; por lo tanto, los príncipes y los legisladores no se apartarían de Judá hasta que viniera su hijo. Otra posibilidad sería dividir shiloh en dos palabras shay y loh lo cual indicaría «aquél a quien se le brinda tributo». El significado más probable de shiloh es el aceptado por la mayoría de las autoridades judías antiguas, para las cuales se trataba de una palabra compuesta de shel y loh, que significaba «al que pertenece». En español Shelloh podría entenderse como: «a quien pertenece el dominio», «de quien es el reino», «aquel que tiene el derecho a reinar». Véase particularmente Eze 21:27.
49 . 13 Zabulón iba a detentar una posición mediocre junto al mar; sus descendientes servirían de instrumento para derrotar a Sísara (Jdg 4:6-10).
49 . 14 , 15 Isacar iba a ser bastante dócil, aceptando una vida feliz y tranquila en Canaán (véase Deu 33:18). Sus descendientes carecieron de visión política, concertando alianzas unas veces con Saúl y otras con David (1Ch 12:32).
49 . 16 - 18 Dan era una pequeña tribu, pero una pequeña serpiente junto al camino puede destruir a un guerrero poderoso. Desafortunadamente, Dan no estuvo a la altura de la bendición que le auguró se convertiría en un valiente (Jdg 1:34) y parece haber tenido pocas relaciones con las otras tribus en los años siguientes (Jdg 5:17). Sansón fue un danita.
49 . 19 Ejército . . . acometerá es un juego de palabras en lengua hebrea con el nombre de Gad . Esta tribu se asentó más tarde al este del Jordán, donde tuvo que enfrentar los ataques de amonitas, moabitas y amalecitas.
49 . 20 La tribu de Aser heredó un área escogida sobre la costa al norte del monte Carmelo. Estaba cerca de las ciudades de los mercaderes fenicios y se hizo rica, aunque no expulsó a los fenicios (Jdg 1:31-32).
49 . 21 Neftalí era también una tribu próspera, localizada en una fértil área montañosa al norte (Jos 20:7). Nunca sacaron de allí a los cananeos, pero recibieron tributo de ellos.
49 . 22 - 26 José recibió la más larga bendición. Se le presenta como una rama fructífera (v. 22), odiada (v. 23), fuerte (v. 24), y como un líder entre sus hermanos (v. 26). Sus descendientes dirigieron las tribus del norte (1Ki 12:25-33), pero también fueron idólatras y participaron en alianzas impías (2Ch 25:5-8; Hos 4:17). Algunos se asentaron al este del Jordán; Gedeón fue uno de ellos.
49 . 24 Estos títulos para Jehová son raros en el AT.
49 . 25 , 26 Las bendiciones son muy similares a la bendición que Moisés pronunció sobre José en Deu 33:13-16. Dios Omnipotente : Véase la nota a 17.1, 2.
49 . 27 La bendición de Benjamín tiene un carácter positivo; sería la inspirada tribu que Moisés llamó «el amado de Jehová» (Deu 33:12). Estuvieron algo intranquilos bajo el reinado de David (2Sa 20:1), pero se unieron al reino meridional cuando Israel se dividió (1Ki 12:21). El rey Saúl y el apóstol Pablo eran benjamitas.
49 . 29 - 32 Véase la nota a 23.4-20.
49 . 33 Encogió sus pies en la cama significa que se acostó en su lecho de muerte. Fue reunido con sus padres destaca la cohesión de la familia patriarcal, aun después de la muerte.</p>
<br/>




</div>
