<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Corintios 2</h2>
<p class="text-justify">Vv. 1-5.En su Persona, oficios y sufrimientos, Cristo es la suma y la sustancia del evangelio, y debe ser el gran tema de la predicación de un ministro del evangelio, pero no tanto como para dejar fuera otras partes de la verdad y de la voluntad revelada de Dios. Pablo predicaba todo el consejo de Dios.
Pocos saben el temor y el temblor de los ministros fieles por el profundo sentido de su propia debilidad. Ellos saben cuán insuficientes son, y temen por sí mismos. Cuando nada sino Cristo crucificado es predicado con claridad, el éxito debe ser enteramente del poder divino que acompaña a la palabra, y de esta manera, los hombres son llevados a creer, a la salvación de sus almas.</p>
<br/>
<p class="text-justify">Vv. 6-9.Los que reciben la doctrina de Cristo como divina, y habiendo sido iluminados por el Espíritu Santo, han mirado bien en ella, no sólo ven la clara historia de Cristo, y a éste crucificado, sino los profundos y admirables designios de la sabiduría divina. Es el misterio hecho manifiesto a los santos, Colosenses i, 26, aunque anteriormente escondido del mundo pagano; sólo se le mostró en tipos oscuros y profecías distantes, pero ahora es revelado y dado a conocer por el Espíritu de Dios.
Jesucristo es el Señor de gloria, título demasiado grande para toda criatura. Hay muchas cosas que la gente no haría si conociera la sabiduría de Dios en la gran obra de la redención. Hay cosas que Dios ha preparado para los que le aman, y le esperan, cosas que los sentidos no pueden descubrir, que ninguna enseñanza puede transmitir a nuestros oídos, ni pueden aún entrar a nuestros corazones. Debemos tomarlas como están en las Escrituras, como quiso Dios revelárnoslas.</p>
<br/>
<p class="text-justify">Vv. 10-16.Dios nos ha revelado sabiduría verdadera por su Espíritu. Esta es una prueba de la autoridad divina de las Sagradas Escrituras, 2 Pedro i, 21.
21. Véase, como prueba de la divinidad del Espíritu Santo, que conoce todas las cosas y escudriña todas las cosas, aun las cosas profundas de Dios. Nadie puede saber las cosas de Dios, sino su Espíritu Santo, que es uno con el Padre y el Hijo, y que da a conocer los misterios divinos a su Iglesia. Este es un testimonio muy claro de la verdadera divinidad y de la personalidad del Espíritu Santo.
Los apóstoles no fueron guiados por principios mundanos. Recibieron del Espíritu de Dios la revelación de estas cosas, y del mismo Espíritu recibieron su impresión salvadora. Estas cosas son las que declararon con un lenguaje claro y sencillo, enseñado por el Espíritu Santo, totalmente diferente de la afectada oratoria o palabras seductoras de la humana sabiduría. El hombre natural, el hombre sabio del mundo, no recibe las cosas del Espíritu de Dios. La soberbia del razonamiento carnal es tan opuesta a la espiritualidad como la sensualidad más baja. La mente santa discierne las bellezas verdaderas de la santidad, pero no pierde el poder de discernir y juzgar las cosas comunes y naturales. El hombre carnal es extraño a los principios, goces y actos de la vida divina. Sólo el hombre espiritual es una persona a quien Dios da el conocimiento de su voluntad. ¡Qué poco han conocido la mente de Dios por el poder natural! El Espíritu capacitó a los apóstoles para dar a conocer su mente. La mente de Cristo y la mente de Dios en Cristo nos son dadas a conocer plenamente en las Sagradas Escrituras. El gran privilegio de los cristianos es que tienen la mente de Cristo, revelada a ellos por su Espíritu. Ellos experimentan su poder santificador en sus corazones y dan buen fruto en sus vidas.</p>
<br/>




</div>
