<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Corintios 11</h2>
<p class="text-justify">V. 1.El primer versículo de este capítulo parece apropiado para concluir el capítulo anterior. El apóstol no sólo predica la doctrina que ellos debían creer, pero llevó tal clase de vida como la que ellos debieran vivir. Dado que Cristo es nuestro ejemplo perfecto, las acciones y la conducta de los hombres, acerca de las Escrituras, debieran seguirse sólo en la medida que sean como las de Él.</p>
<br/>
<p class="text-justify">Vv. 2-16.Aquí empiezan los detalles acerca de las asambleas públicas, capítulo xiv. Algunos abusos se habían introducido en la abundancia de dones espirituales concedidos a los corintios, pero como Cristo hizo la voluntad de Dios cuyo honra procuró, así el cristiano debe confesar su sumisión a Cristo, haciendo su voluntad y procurando su gloria. Nosotros debemos, aun en nuestra vestimenta y hábitos, evitar toda cosa que pueda deshonrar a Cristo.
La mujer fue sometida al hombre porque fue creada como su ayuda y consuelo. Ella nada debe hacer en las asambleas cristianas que parezca una pretensión de ser su igual. Ella debe tener una “potestad”sobre su cabeza esto es, un velo, debido a los ángeles. La presencia de ellos debe resguardar a los cristianos de todo lo que es malo mientras adoren a Dios. Sin embargo, el hombre y la mujer fueron hechos uno para el otro. Iban a ser de consolación y bendición mutua, no una la esclava y el otro el tirano. Dios ha establecido las cosas, en el reino de la providencia y en el de la gracia, de modo que la autoridad y el sometimiento de cada parte sean para ayuda y provecho mutuo. Era costumbre en las iglesias que las mujeres se presentaran veladas en las asambleas públicas, y así ingresaran a la adoración en público; y estaba bien que debieran hacerlo así. La religión cristiana sanciona las costumbres nacionales dondequiera que estas no sean contrarias a los grandes principios de la verdad y la santidad; las peculiaridades afectadas no reciben consentimiento de nada en la Biblia.</p>
<br/>
<p class="text-justify">Vv. 17-22.El apóstol reprende los desórdenes en la celebración de la cena del Señor. Las ordenanzas de Cristo, si no nos hacen mejor, tenderán a empeorarnos. Si el uso de ellas no enmienda, endurecerá. Al reunirse, ellos cayeron en divisiones y partidismos. Los cristianos pueden separarse de la comunión de unos con otros, pero aún ser caritativos unos con otros; se puede continuar en la misma comunión, pero sin ser caritativos. Esto último es división, más que lo primero.
Hay una comida descuidada e irregular de la cena del Señor que se suma a la culpa. Parece que muchos corintios ricos actuaron muy mal en la mesa del Señor, o en las fiestas de amor, que tenían lugar al mismo tiempo que la cena del Señor. El rico despreciaba al pobre, comía y bebía de las provisiones que traían, antes de permitir la participación del pobre; así, algunos quedaban sin nada, mientras que otros tenían más que suficiente. Lo que hubiera debido ser un vínculo de amor y afecto mutuo fue hecho instrumento de discordia y desunión. Debemos ser cuidadosos para que nada de nuestra conducta en la mesa del Señor parezca tomar a la ligera esa institución sagrada. La cena del Señor no es, ahora, hecha ocasión para la glotonería o el festejo, pero ¿no suele convertirse en un apoyo para la soberbia de la justicia propia o un manto para la hipocresía? No descansemos en las formas externas de la adoración, pero examinemos nuestros corazones.</p>
<br/>
<p class="text-justify">Vv. 23-34.El apóstol describe la ordenanza sagrada, de la cual tenía conocimiento por revelación de Cristo. En cuanto a los signos visibles, estos son el pan y el vino. Lo que se come se llama pan, aunque al mismo tiempo se dice que es el cuerpo del Señor, mostrando claramente que el apóstol no quería significar que el pan fuese cambiado en carne. San Mateo nos dice que nuestro Señor les invitó a todos a beber de la copa, capítulo xxvi, 27, como si hubiera previsto, con esta expresión, que un creyente fuese privado de la copa. Las cosas significadas por estos signos externos, son el cuerpo y la sangre de Cristo, su cuerpo partido, su sangre derramada, junto con todos los beneficios que fluyen de su muerte y sacrificio.
Las acciones de nuestro Señor fueron, al tomar el pan y la copa, dar gracias, partir el pan y dar el uno y la otra. Las acciones de los comulgantes fueron, tomar el pan y comer, tomar la copa y beber, haciendo ambas cosas en memoria de Cristo. Pero los actos externos no son el todo ni la parte principal de lo que debe hacerse en esta santa ordenanza. Los que participan de ella tienen que tomarlo a Él como su Señor y su Vida, rendirse a Él y vivir para Él.
En ella tenemos un relato de las finalidades de esta ordenanza. Tiene que hacerse en memoria de Cristo, para mantener fresca en nuestras mentes su muerte por nosotros, y también, para recordar a Cristo que intercede por nosotros a la diestra de Dios en virtud de su muerte. No es tan sólo en memoria de Cristo, de lo que Él hizo y sufrió, sino para celebrar su gracia en nuestra redención. Declaramos que su muerte es nuestra vida, la fuente de todos nuestros consuelos y esperanzas. Nos gloriamos en tal declaración; mostramos su muerte y la reclamamos como nuestro sacrificio y nuestro rescate aceptado. La cena del Señor no es una ordenanza que se observe sólo por un tiempo, pero debe ser perpetua.
El apóstol expone a los corintios el peligro de recibirla con un estado mental inapropiado o conservando el pacto con el pecado y la muerte mientras se profesa renovar y confirmar el pacto con Dios. Sin duda, ellos incurren en gran culpa y así se vuelven materia obligada de juicios espirituales. Pero los creyentes temerosos no deben descorazonarse de asistir a esta santa ordenanza. El Espíritu Santo nunca hubiera hecho que esta Escritura se hubiese puesto por escrito para disuadir de su deber a los cristianos serios, aunque el diablo la ha usado a menudo. El apóstol estaba dirigiéndose a los cristianos y les advierte que estén alerta ante los juicios temporales con que Dios corrige a sus siervos que le ofenden. En medio de la ira, Dios se acuerda de la misericordia: muchas veces castiga a los que ama. Mejor es soportar problemas en este mundo que ser miserable para siempre.
El apóstol señala el deber de los que van a la mesa del Señor. El examen de uno mismo es necesario para participar correctamente en esta ordenanza sagrada. Si nos examináramos cabalmente para condenar y enderezar lo que hallemos malo, podríamos detener los juicios divinos.
El apóstol termina todo con una advertencia contra las irregularidades en la mesa del Señor, de las cuales eran culpables los corintios. Cuidemos todos de esto para que ellos no se unan a la adoración de Dios como para provocarle y acarrearse venganza sobre sí.</p>
<br/>




</div>
