<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Corintios 16</h2>
<p class="text-justify">Vv. 1-9.Los buenos ejemplos de otros cristianos e iglesias deben estimularnos. Bueno es almacenar para buenos usos. Los que son ricos en este mundo deben ser ricos en buenas obras, 1 Timoteo vi, 17, 18. La mano diligente no se enriquecerá sin la bendición divina, Proverbios x, 4, 22. ¿Qué más adecuado para estimularnos a la caridad con el pueblo e hijos de Dios que mirar todo lo que tenemos como dádiva suya? Las obras de misericordia son frutos reales del amor verdadero a Dios, y por tanto son servicios apropiados para el día del Señor. Los ministros hacen la actividad que les corresponde cuando promueven, o ayudan, las obras de caridad.
El corazón de un ministro cristiano debe estar orientado hacia la gente entre quienes haya trabajado mucho tiempo, y con éxito. Debemos hacernos todos nuestros propósitos con sumisión a la providencia divina, Santiago, iv, 15. Los adversarios y la oposición no quiebran los espíritus de los ministros fieles y exitosos, pero enardecen su celo y les inspiran un nuevo valor. El ministro fiel se descorazona más con la dureza de los corazones de sus oyentes y el extravío de los profesantes que con los atentados de los enemigos.</p>
<br/>
<p class="text-justify">Vv. 10-12.Timoteo vino a hacer la obra del Señor. Por tanto, afligir su espíritu es contristar al Espíritu Santo; despreciarlo es despreciar a Aquel que lo envió. Los que trabajan en la obra del Señor deben ser tratados con ternura y respeto. Los ministros fieles no tendrán celo unos de otros. Corresponde a los ministros del evangelio demostrar interés por la reputación y la utilidad de unos y otros.</p>
<br/>
<p class="text-justify">Vv. 13-18.El cristiano siempre corre peligro, por tanto, siempre debe estar alerta. Debe estar firme en la fe del evangelio sin abandonarla, ni renunciar jamas a ella. Por esta sola fe será capaz de resistir en la hora de la tentación. Los cristianos deben cuidar que la caridad no sólo reine en sus corazones, sino brille en sus vidas. Hay una gran diferencia entre la firmeza cristiana y el activismo febril. El apóstol da instrucciones particulares para algunos que sirven la causa de Cristo entre ellos. Los que sirven a los santos, los que desean el honor de las iglesias, y quitar los reproches de ellas, tienen que ser muy considerados y amados. Deben reconocer voluntariamente el valor de los tales y de todos los que trabajaron con el apóstol o le ayudaron.</p>
<br/>
<p class="text-justify">Vv. 19-24.El cristianismo no destruye en absoluto el civismo. La religión debe fomentar un temperamento cortés y amable hacia todos. Dan una falsa idea de la religión, y le causan reproche, los que encuentran ánimo en ella para ser irritables y tercos. Los saludos cristianos no son simples cumplidos vacíos, sino expresiones reales de buena voluntad para el prójimo, y los encomiendan a la gracia y a la bendición divinas. Toda familia cristiana debe ser como una iglesia cristiana. Dondequiera que se reúnan dos o tres en el nombre de Cristo, y Él esté entre ellos, ahí hay una iglesia.
Aquí hay una advertencia solemne: muchas personas que tienen muy a menudo el nombre de Cristo en sus bocas, no tienen un amor verdadero por Él en sus corazones. No le ama de verdad quien no ame sus leyes ni obedezca sus mandamientos. Muchos son cristianos de nombre, porque no aman a Cristo Jesús, el Señor, con sinceridad. Los tales están separados del pueblo de Dios y del favor de Dios. Los que no aman al Señor Jesucristo deben perecer sin remedio. No descansemos en ninguna profesión religiosa donde no hay el amor de Cristo, los sinceros deseos por su salvación, la gratitud por sus misericordias, y la obediencia a sus mandamientos.
La gracia de nuestro Señor Jesucristo tiene en ella todo lo que es bueno para el tiempo y la eternidad. Desear que nuestros amigos puedan tener esta gracia consigo, es desearles el sumo bien. Esto debemos desear a todos nuestros amigos y hermanos en Cristo. No podemos desearles nada más grande, y no debemos desearle nada menos. El cristianismo verdadero hace que deseemos las bendiciones de ambos mundos para los que amamos; esto significa desearles que la gracia de Cristo esté con ellos. El apóstol había tratado claramente con los corintios, y les habló de sus faltas con justa severidad, pero se despide con amor y con una solemne profesión de su amor por ellos por amor a Cristo. Que nuestro amor sea con todos los que están en Cristo Jesús. Probemos si todas las cosas nos parecen sin valor cuando las comparamos con Cristo y su justicia. ¿Nos permitimos algún pecado conocido o la negligencia de un deber conocido? Con tales preguntas, fielmente hechas, podemos juzgar el estado de nuestras almas.</p>
<br/>




</div>
