<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Corintios 6</h2>
<p class="text-justify">Vv. 1-8.Los cristianos no deben contender unos contra otros, porque son hermanos. Eso evitaría muchos juicios legales, y terminaría con muchas peleas y disputas, si se atendiera debidamente. En los asuntos que nos perjudican mucho a nosotros o a nuestra familia, podríamos recurrir a los medios legales para hacer justicia, pero los cristianos deben tener una actitud perdonadora. Juzgad vosotros los asuntos en disputa antes de ir a las cortes por ellos. Son fruslerías y pueden arreglarse fácilmente si uno vence primero su propio espíritu. Soportad y tolerad y los hombres de más sencillos entre vosotros pueden terminar la disputa. Da vergüenza que entre los cristianos, peleas de poca monta crezcan de tal manera, que los hermanos no puedan resolverlas. La paz mental del hombre y la tranquilidad de su prójimo valen más que la victoria. Los juicios legales no pueden tener cabida entre hermanos a menos que haya faltas en ellos.</p>
<br/>
<p class="text-justify">Vv. 9-11.Se advierte a los corintios de muchos males grandes, de los cuales habían sido culpables anteriormente. Hay mucha fuerza en estas preguntas cuando consideramos que se dirigen a un pueblo envanecido con la ilusión de ser superior a los demás en sabiduría y conocimiento. Toda injusticia es pecado; todo pecado reinante, sí, todo pecado actual, cometido con intención, y del cual no se ha arrepentido, excluye del reino del cielo. No os engañéis. Los hombres se inclinan mucho a halagarse a sí mismos con que pueden vivir en pecado, pero morir en Cristo e irse al cielo. Sin embargo, no podemos esperar que sembrando en la carne cosechemos vida eterna.
Se les recuerda el cambio hecho en ellos por el evangelio y la gracia de Dios. La sangre de Cristo y el lavamiento de la regeneración pueden quitar toda culpa. Nuestra justificación se debe a los sufrimientos y los méritos de Cristo; nuestra santificación a la obra del Espíritu Santo, pero ambas van juntas. Todos los que son hechos justos a ojos de Dios, son hechos santos por la gracia de Dios.</p>
<br/>
<p class="text-justify">Vv. 12-20.Algunos de los corintios parecen haber estado prontos para decir: “Todas las cosas me son lícitas”. Pablo se opone a este peligroso engaño. Hay una libertad con que Cristo nos ha hecho libres, en la cual debemos afirmarnos, pero con toda seguridad, el cristiano no debe ponerse nunca bajo el poder de un apetito carnal cualquiera. El cuerpo es para el Señor; debe ser instrumento de justicia para santidad, por tanto, no debe ser instrumento de pecado. Honra para el cuerpo es que Jesucristo fuera levantado de entre los muertos; y será honra para nuestros cuerpos que sean resucitados. La esperanza de la resurrección en gloria debe guardar a los cristianos de deshonrar sus cuerpos con lujurias carnales.
Si el alma se une a Cristo por fe, todo el hombre es hecho miembro de su cuerpo espiritual. Otros vicios pueden derrotarse con lucha ; pero contra el que aquí se nos advierte, sólo es con huida. Enormes multitudes son cortadas por estos vicios en sus formas y consecuencias variadas. Sus efectos no sólo caen directamente sobre el cuerpo, sino con frecuencia en la mente. Nuestros cuerpos fueron redimidos de la merecida condenación y de la mísera esclavitud por el sacrificio expiatorio de Cristo. Tenemos que ser limpios, como vasos dignos para el uso de nuestro Maestro. Estando unidos a Cristo como un solo espíritu, y comprados a precio de indecible valor, el creyente debe considerarse como totalmente del Señor, por los lazos más fuertes. Que glorificar a Dios sea nuestra actividad hasta el último día y hora de nuestra vida, con nuestros cuerpos y con nuestros espíritus, que son de Él.</p>
<br/>




</div>
