<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Corintios 1</h2>
<p class="text-justify">Vv. 1-9.Todos los cristianos son dedicados y consagrados a Cristo por el bautismo, y tienen la obligación estricta de ser santos, porque en la Iglesia verdadera de Dios están todos los santificados en Cristo Jesús, llamados a ser santos, y que le invocan como el Dios manifestado en carne, para todas las bendiciones de la salvación; los cuales le reconocen y obedecen como Señor de ellos, y Señor de todo; no incluye a otras personas. El cristiano se distingue del profano y del ateo, porque no osa vivir sin oración; y se puede distinguir de los judíos y paganos en que invoca el nombre de Cristo.
Nótese con cuánta frecuencia repite el apóstol en estos versículos las palabras, nuestro Señor Jesucristo. Temía no mencionarlo con bastante honra y frecuencia. El apóstol da su saludo habitual a todos los que invocan a Cristo, deseando de Dios, para ellos, la misericordia que perdona, la gracia que santifica, y la paz que consuela, a través de Jesucristo.
Los pecadores no pueden tener paz de Dios, ni nada de Él, sino por medio de Cristo.
Da gracias por la conversión de ellos a la fe de Cristo; esa gracia les fue dada por Jesucristo. Ellos habían sido enriquecidos por Él con todos los dones espirituales. Habla de palabras y conocimiento. Donde Dios ha dado estos dos dones, ha dado gran poder para el servicio. Estos eran dones del Espíritu Santo, por los cuales, Dios daba testimonio de los apóstoles.
Los que esperan la venida de nuestro Señor Jesucristo, serán sostenidos por Él hasta el final; éstos serán sin culpa en el día de Cristo, hechos así por la rica y libre gracia. ¡Qué gloriosas son las esperanzas de tal privilegio: estar resguardados por el poder de Cristo del poder de nuestras corrupciones y de las tentaciones de Satanás!</p>
<br/>
<p class="text-justify">Vv. 10-16.Sed unánimes en las grandes cosas de la religión; donde no hay unidad de sentimiento, que haya al menos unión del afecto. El acuerdo en las cosas grandes debiera hacer menguar las divisiones sobre las menores. Habrá unión perfecta en el cielo y, mientras más nos acerquemos a ella en la tierra, más cerca llegaremos de la perfección.
Pablo y Apolos eran ambos fieles ministros de Jesucristo, y ayudantes de su fe y gozo; pero los que estaban dispuestos a ser beligerantes, se dividieron en bandos. Tan sujetas están las mejores cosas a corromperse, que el evangelio y sus instituciones son hechos motores de discordia y contención. Satanás siempre se ha propuesto estimular la discordia entre los cristianos, como uno de sus principales ingenios contra el evangelio.
El apóstol le dejó a los otros ministros el bautismo, mientras que él predicaba el evangelio, como obra más útil.</p>
<br/>
<p class="text-justify">Vv. 17-25.Pablo había sido criado en el saber judío; pero la clara predicación de Jesús crucificado era más poderosa que toda la oratoria y filosofía del mundo pagano. Esta es la suma y la sustancia del evangelio. Cristo crucificado es el fundamento de todas nuestras esperanzas, la fuente de todo nuestro gozo. Nosotros vivimos por su muerte. La predicación de la salvación de los pecadores perdidos por los sufrimientos y la muerte del Hijo de Dios, si se explica y aplica fielmente, parece locura para los que van por el camino de la destrucción. El sensual, el codicioso, el ambicioso, el orgulloso, por igual, ven que el evangelio se opone a sus empresas preferidas. Pero los que reciben el evangelio, y son iluminados por el Espíritu de Dios, ven más de la sabiduría y el poder de Dios en la doctrina de Cristo crucificado, que en todas sus otras obras.
Dios dejó a una gran parte de la humanidad librada a seguir los dictados de la razón jactanciosa del hombre, y el hecho ha demostrado que la sabiduría humana es necedad, e incapaz de encontrar o retener el conocimiento de Dios como Creador. Agradó a Dios salvar a los creyentes por la locura de la predicación. Por la locura de la predicación, no por lo que justamente podría llamarse predicación loca, sino que la cosa predicada era locura para los hombres sabios según el mundo. El evangelio siempre fue, y será, necedad para todos los que van por el camino de la destrucción. El mensaje de Cristo, entregado con sencillez, ha sido siempre una piedra de toque por la cual los hombres pueden saber por qué camino viajan. Pero la despreciada doctrina de la salvación por fe en el Salvador crucificado, Dios en naturaleza humana que compra a la Iglesia con su sangre, para salvar a multitudes, a todos los que creen, de la ignorancia, el engaño y el vicio, ha sido bendecida en toda época. Los instrumentos más débiles que Dios usa, son más fuertes en sus efectos que los hombres más fuertes. No se trata que haya necedad o debilidad en Dios, sino que lo que los hombres consideran tales, superan toda su admirada sabiduría y poder.</p>
<br/>
<p class="text-justify">Vv. 26-31.Dios no eligió filósofos, oradores, estadistas ni hombres ricos, poderosos e interesados en el mundo para publicar el evangelio de gracia y paz. Juzga mejor cuáles hombres y qué medidas sirven los propósitos de su gloria.
Aunque no son muchos los nobles habitualmente llamados por la gracia divina, ha habido algunos de ellos en toda época, que no se han avergonzado del evangelio de Cristo; porque las personas de todo rango necesitan la gracia que perdona. A menudo, el cristiano humilde, aunque pobre según el mundo, tiene más conocimiento verdadero del evangelio que los que han hecho del estudio de la letra de la Escritura el objeto de sus vidas, pero que la estudian como testigos de hombres más que como palabra de Dios. Hasta los niños pequeños logran tal conocimiento de la verdad divina como para silenciar a los infieles. La razón es que Dios les enseña; la intención es que ninguna carne se gloríe en su presencia. Esa distinción, la única en la cual podrían gloriarse no es de ellos mismos. Fue por la opción soberana y la gracia regeneradora de Dios que ellos estaban en Jesucristo por fe. Él nos es hecho por Dios sabiduría, justicia, santificación y redención: todo lo que necesitamos o podemos desear. Nos es hecho sabiduría para que por su palabra y su Espíritu, y de su plenitud y tesoros de sabiduría y conocimiento, podamos recibir todo lo que nos hará sabios para salvación, y aptos para todo servicio al que seamos llamados. Somos culpables, destinados al justo castigo; pero, es hecho justicia, nuestra gran expiación y sacrificio. Somos depravados y corruptos; Él es hecho santificación, la fuente de nuestra vida espiritual: de Él, la Cabeza, es dada a su cuerpo por su Espíritu Santo. Estamos esclavizados, y nos es hecho redención, nuestro Salvador y Libertador. Donde Cristo sea hecho justicia para un alma, también es hecho santificación. Nunca absuelve de la culpa del pecado sin liberar de su poder; es hecho justicia y santificación, para que, al final, sea hecho redención completa; pueda liberar al alma del ser de pecado, y librar el cuerpo de las cadenas del sepulcro. Esto es para que toda carne, conforme a la profecía de Jeremías, capítulo ix, 23, pueda gloriarse en el favor especial, en la gracia absolutamente suficiente, y la preciosa salvación de Jehová.</p>
<br/>




</div>
