<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Juan 2</h2>
<p class="text-justify">Vv. 1, 2.Tenemos un Abogado para con el Padre; uno que ha prometido, y es plenamente capaz de defender a cada uno que solicite perdón y salvación en su nombre, dependiendo de que Él abogue por ellos. Él es “Jesús”, el Salvador, y “Cristo”, el Mesías, el Ungido. Él solo es “el Justo”, que recibió su naturaleza libre de pecado, y como fiador nuestro obedeció perfectamente la ley de Dios, y así cumplió toda justicia. Todos los hombres de todo país, y a través de sucesivas generaciones, están invitados a ir a Dios a través de esta expiación absolutamente suficiente y por este camino nuevo y vivo. El evangelio, cuando se comprende y recibe correctamente, pone el corazón en contra de todo pecado y contra su práctica permitida; y al mismo tiempo, da un bendito alivio a las conciencias heridas de los que han pecado.</p>
<br/>
<p class="text-justify">Vv. 3-11.¿Qué conocimiento de Cristo puede ser aquel que no ve que Él es digno de toda nuestra obediencia? La vida de desobediencia muestra que no hay religión ni honestidad en el profesante.
El amor de Dios es perfeccionado en aquel que obedece sus mandamientos. La gracia de Dios en Él obtiene su marca verdadera, y produce su efecto soberano tanto como puede ser en este mundo, y esta es la regeneración del hombre, aunque aquí nunca sea absolutamente perfecta. Sin embargo, esta observancia de los mandamientos de Cristo tiene santidad y excelencia, que si fuesen universales, harían que la tierra se pareciera al cielo mismo.
El mandamiento de amarse los unos a los otros ha tenido vigencia desde el comienzo del mundo, pero podría considerarse como mandamiento nuevo al darlo a los cristianos. Era nuevo para ellos, como era nueva su situación respecto de sus motivos, reglas y obligaciones. Siguen en estado de tinieblas los que andan con odio y enemistad contra los creyentes. El amor cristiano nos enseña a valorar el alma de nuestro hermano y a temer todo lo que dañe su pureza y su paz. Donde haya tinieblas espirituales, estarán entenebrecidos la mente, el juicio y la conciencia, y erraremos el camino a la vida celestial. Estas cosas exigen un serio examen de sí; y la oración ferviente para que Dios nos muestre qué somos y dónde vamos.</p>
<br/>
<p class="text-justify">Vv. 12-14.Como los cristianos tienen sus estados propios, tienen sus deberes peculiares; pero hay preceptos y obediencia que afectan a todos, particularmente el amor mutuo y el desprecio al mundo. El discípulo sincero más joven es perdonado; la comunión de los santos va acompañada del perdón de pecados. Los que tienen la permanencia más prolongada en la escuela de Cristo necesitan aun más consejo e instrucción. Se debe escribir a los padres, y predicarles; nadie es demasiado viejo para aprender. Pero esto vale especialmente para los jóvenes en Cristo Jesús, aunque hayan alcanzado fortaleza de espíritu y sano sentido, hayan resistido exitosamente las primeras pruebas y tentaciones, hayan roto con las malas costumbres y relaciones, y hayan entrado por la puerta estrecha de la conversión verdadera.
Se vuelve a dirigir a los diferentes grupos de cristianos. Los niños en Cristo saben que Dios es su Padre: esa es su sabiduría. Los creyentes avanzados que conocen a Aquel que fue desde el comienzo, antes que este mundo fuese hecho, muy bien pueden ser guiados por eso a renunciar a este mundo.
La gloria de las personas jóvenes será la fortaleza en Cristo y en su gracia. Ellos vencen al maligno por la palabra de Dios.</p>
<br/>
<p class="text-justify">Vv. 15-17.Las cosas del mundo pueden desearse y poseerse para los usos y propósitos que Dios concibió, y hay que usarlas por su gracia y para su gloria; pero los creyentes no deben buscarlas ni valorarlas para propósitos en que el pecado abusa de ellas. El mundo aparta de Dios el corazón y mientras más prevalezca el amor al mundo, más decae el amor a Dios. Las cosas del mundo se clasifican conforme a las tres inclinaciones reinantes de la naturaleza depravada: -1. La concupiscencia de la carne, del cuerpo: los malos deseos del corazón, el apetito de darse el gusto con todas las cosas que excitan e inflaman los placeres sensuales.
2. La concupiscencia de los ojos: los ojos se deleitan con las riquezas y las posesiones ricas; esta es la concupiscencia de la codicia.
3. La soberbia de la vida: el hombre vano ansía la grandeza y la pompa de una vida de vanagloria, lo cual comprende una sed de honores y aplausos. Las cosas del mundo se desvanecen rápidamente y mueren; el mismo deseo desfallecerá y cesará dentro de poco tiempo, pero el santo afecto no es como la lujuria pasajera. El amor de Dios nunca desfallecerá.
Muchos vanos esfuerzos se han hecho para eludir la fuerza de este pasaje con limitaciones, distinciones o excepciones. Muchos han tratado de mostrar cuán lejos podemos ir estando orientados carnalmente y amando al mundo; pero no resulta fácil equivocarse respecto al significado evidente de estos versículos. A menos que esta victoria sobre el mundo empiece en el corazón, el hombre no tiene raíces en sí mismo y caerá o, en el mejor de los casos, será un profesante estéril. De todos modos, estas vanidades son tan seductoras para la corrupción de nuestros corazones, que, sin velar y orar sin cesar, no podemos escapar del mundo ni lograr la victoria sobre su dios y príncipe.</p>
<br/>
<p class="text-justify">Vv. 18-23.Todo hombre que niega la Persona o alguno de los oficios de Cristo es anticristo; y al negar al Hijo, niega también al Padre, y no tiene parte en su favor porque rechaza su gran salvación. Que esta profecía la aparición de seductores en el mundo cristiano nos resguarde de ser seducidos. La Iglesia no sabe bien quiénes son sus miembros verdaderos, ni quienes no lo son, pero así se prueba a los verdaderos cristianos que se hacen más vigilantes y humildes. Los verdaderos cristianos son los ungidos, como su nombre lo expresa: son los ungidos por el Espíritu Santo con gracia, con dones y privilegios espirituales. Las mentiras más grandes y perjudiciales que difunde el padre de mentira en el mundo suelen ser falsedades y errores relativos a la persona de Cristo. Sólo la unción del Santo puede guardarnos de los engaños. Mientras juzgamos favorablemente a todos los que confían en Cristo como el Salvador Divino, y obedecen su palabra y procuran vivir unidos con ellos, tengamos lástima y oremos por los que niegan la deidad de Cristo o su expiación y la obra de nueva creación que hace el Espíritu Santo. Protestemos contra la doctrina anticristiana y guardémonos de ellos lo más que podamos.</p>
<br/>
<p class="text-justify">Vv. 24-29.La verdad de Cristo que permanece en nosotros es el medio de separarse del pecado y unirse al Hijo de Dios, Juan xv, 3, 4. ¡Cuánto valor debemos dar a la verdad del evangelio! Por él se asegura la promesa de la vida eterna. La promesa que hace Dios es adecuada a su propia grandeza, poder y bondad; es la vida eterna.
El Espíritu de verdad no mentirá; y enseña todas las cosas de la presente dispensación, todas las cosas necesarias para nuestro conocimiento de Dios en Cristo, y su gloria en el evangelio.
El apóstol repite la amable palabra, “hijitos”que denota su afecto. Él persuade por amor. Los privilegios del evangelio obligan a los deberes del evangelio; y los ungidos por el Señor Jesús permanecen con Él. La nueva naturaleza espiritual es del Señor Cristo. El que es constante en la práctica de la religión en las épocas de prueba, demuestra que es nacido de lo alto, del Señor Cristo. Entonces, cuidémonos de sostener con injusticia la verdad, recordando que sólo son nacidos de Dios los que llevan su santa imagen y andan en sus caminos más justos.</p>
<br/>




</div>
