<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Juan 4</h2>
<p class="text-justify">Vv. 1-6.Los cristianos que están bien familiarizados con las Escrituras pueden discernir, en humilde dependencia de la enseñanza divina, a los que establecen doctrinas conforme a los apóstoles y aquellos que les contradicen. La suma de la religión revelada está en la doctrina referida a Cristo, Su persona y oficio. Los falsos maestros hablan al mundo conforme a sus máximas y gustos, como para no ofender a los hombres carnales. El mundo los aprueba, progresan rápido y tienen muchos seguidores como ellos; el mundo amará a los suyos y los suyos le amarán.
La doctrina verdadera de la persona del Salvador, que saca a los hombres desde el mundo a Dios, es marca del espíritu de verdad que se opone al espíritu de error. Mientras más pura y santa sea una doctrina, más probable que sea de Dios; tampoco podemos probar los espíritus por ninguna otra regla, para saber si son o no de Dios. Y ¿qué maravilla es que la gente de espíritu mundano se aferre a ésos que son como ellos, y que adecuan sus estratagemas y discursos a su gusto corrupto?</p>
<br/>
<p class="text-justify">Vv. 7-13.El Espíritu de Dios es el Espíritu de amor. El que no ama la imagen de Dios en Su pueblo, no tiene conocimiento salvador de Dios. Pues ser bueno y dar felicidad es la naturaleza de Dios. La ley de Dios es amor; y todos serán perfectamente felices si todos la hubiesen obedecido. La provisión del evangelio, para el perdón de pecado, y la salvación de los pecadores, consistente con la gloria y la justicia de Dios, demuestra que Dios es amor. El misterio y las tinieblas aún penden sobre muchas cosas. Dios se ha demostrado siendo amor para que no podamos dejar de alcanzar la felicidad eterna, a menos que sea por la incredulidad y la impenitencia, aunque la justicia estricta nos condenara a la miseria desesperanzada por romper las leyes de nuestro Creador.
Ninguna palabra ni pensamiento de nosotros puede hacer justicia al amor gratuito y asombroso del santo Dios para con los pecadores, que no podrían beneficiarse de Él ni dañarle, a los que Él podría aplastar justicieramente en un momento, y a los que, siendo merecedores de Su venganza, Él muestra el método por el cual fueron salvados aunque Él podía haber creado, por Su Palabra todopoderosa, otros mundos con seres más perfectos si lo hubiera considerado bien. ¿Investigamos todo el universo buscando al amor en sus despliegues más gloriosos? Se halla en la persona y la cruz de Cristo. ¿Existe el amor entre Dios y los pecadores? Aquí estaba el origen, no que nosotros amáramos a Dios sino que Él nos amó libremente. Su amor no podía estar concebido para ser infructuoso en nosotros, y cuando su fin y tema apropiados se ganen y produzcan, puede decirse que está perfeccionado. Así es perfeccionada la fe por sus obras. Así se manifestará que Dios habita en nosotros por Su Espíritu que crea de nuevo.
El cristiano que ama es el cristiano perfecto; póngalo en cualquier deber bueno y es perfecto para eso, es experto en eso. El amor aceita las ruedas de sus afectos y lo pone en eso que es útil para sus hermanos. El hombre que se ocupa de algo con mala voluntad, siempre lo hace mal. Que Dios habite en nosotros y nosotros en Él, eran palabras demasiado elevadas para que las usaran los mortales si Dios no las hubiera puesto delante de nosotros. Pero, ¿cómo puede saberse si el testimonio de esto procede del Espíritu Santo? Aquellos que están verdaderamente persuadidos de ser los hijos de Dios no pueden sino llamarlo Abba, Padre. Por amor a Él, odian el pecado y todo lo que no concuerde con Su voluntad, y tienen el deseo sano de todo corazón de hacer Su voluntad. Tal testimonio es el testimonio del Espíritu Santo.</p>
<br/>
<p class="text-justify">Vv. 14-21.El Padre envió al Hijo, Él deseó Su venida a este mundo. El apóstol atestigua esto. Y cualquiera que confiese que Jesús es el Hijo de Dios, en ése habita Dios y ése en Dios. Esta confesión abarca la fe en el corazón como fundamento; reconoce con la boca la gloria de Dios y Cristo, y confiesa en la vida y conducta contra los halagos y ceños fruncidos del mundo.
Debe haber un día de juicio universal. ¡Dichosos aquellos que tendrán osadía santa ante el Juez en aquel día sabiendo que Él es su Amigo y Abogado! Dichosos aquellos que tendrán osadía santa en la perspectiva de aquel día, que miran y esperan por eso y por la manifestación del Juez. El verdadero amor a Dios asegura a los creyentes del amor de Dios por ellos. El amor nos enseña a sufrir por Él y con Él; por tanto, podemos confiar que también seremos glorificados con Él, 2 Timoteo ii, 12.
Debemos distinguir entre el temor de Dios y tenerle miedo; el temor de Dios comprende alta consideración y veneración por Dios. La obediencia y las buenas obras hechas a partir del principio del amor, no son como el esfuerzo servil de uno que trabaja sin voluntad por miedo a la ira del amo. Son como las de un hijo obediente que sirve a un padre amado que beneficia a sus hermanos y las hace voluntariamente. Señal de que nuestro amor dista mucho de ser perfecto si son muchas nuestras dudas, temores y aprensiones de Dios. Que el cielo y la tierra se asombren por Su amor. Él envió Su palabra a invitar a los pecadores a participar de esta gran salvación. Que ellos tengan el consuelo del cambio feliz obrado en ellos mientras le dan a Él la gloria.
El amor de Dios en Cristo, en los corazones de los cristianos por el Espíritu de adopción, es la prueba grande de la conversión. Esta debe ser probada por sus efectos en sus temperamentos, y en sus conductas para con sus hermanos. Si un hombre dice amar a Dios y, sin embargo, se permite ira o venganza, o muestra una disposición egoísta, desmiente a su confesión. Pero si es evidente que nuestra enemistad natural está cambiada en afecto y gratitud, bendigamos el nombre de nuestro Dios por este sello y primicia de dicha eterna. Entonces nos diferenciamos de los profesos falsos que pretenden amar a Dios a quien no han visto pero odian a sus hermanos a los que han visto.</p>
<br/>




</div>
