<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Juan 1</h2>
<p class="text-justify">Vv. 1-4.El Dios esencial, la excelencia no creada que había sido desde el principio, desde la eternidad, igual con el Padre y que, finalmente, se manifestó con naturaleza humana para la salvación de los pecadores, es gran tema sobre el cual escribe el apóstol a sus hermanos. Los apóstoles le vieron durante algunos años, en los cuales presenciaron su sabiduría y santidad, sus milagros, y su amor y misericordia, hasta que le vieron crucificado por los pecadores, y después resucitado de entre los muertos. Ellos le tocaron para tener plena prueba de su resurrección.
Esta Persona divina, el Verbo de vida, el Verbo de Dios se manifestó en naturaleza humana para ser Autor y Dador de la vida eterna a la humanidad por medio de la redención por su sangre y el poder de su Espíritu regenerador.
Los apóstoles declaran lo que han visto y oído para que los creyentes compartieran sus bendiciones y ventajas eternas. Tenían libre acceso a Dios Padre. Tuvieron una feliz experiencia de la verdad en sus almas, y mostraron su excelencia en sus vidas. Esta comunión de los creyentes con el Padre y el Hijo empieza y es sustentada por el poder del Espíritu Santo. Los beneficios que Cristo concede, no son las mezquinas posesiones del mundo que causan envidia en los demás, sino el gozo y la felicidad de la comunión con Dios son absolutamente suficientes, de modo que cualquier cantidad de personas puede participar de ellos; y todos los autorizados para decir que en verdad su comunión es con el Padre, desearán guiar a otros a participar de la misma bienaventuranza.</p>
<br/>
<p class="text-justify">Vv. 5-10.Todos debiéramos recibir jubilosos un mensaje del Señor Jesús, el Verbo de vida, el Verbo eterno. El gran Dios debe ser representado a este mundo oscuro como luz pura y perfecta. Como esta es la naturaleza de Dios, sus doctrinas y preceptos deben ser tales. Como su perfecta felicidad no puede separarse de su perfecta santidad, así nuestra felicidad será proporcional a la santidad de nuestro ser. Andar en tinieblas es vivir y actuar contra la religión. Dios no mantiene comunión o relación celestial con las almas impías. No hay verdad en la confesión de ellas; su práctica muestra su necedad y falsedad. La vida eterna, el Hijo eterno, se vistió de carne y sangre, y murió para lavarnos de nuestros pecados en su sangre, y procura para nosotros las influencias sagradas por las cuales el pecado tiene que ser sometido más y más hasta que sea completamente acabado. Mientras se insiste en la necesidad de un andar santo, como efecto y prueba de conocer a Dios en Cristo Jesús, se advierte con igual cuidado en contra del error opuesto del orgullo de la justicia propia. Todos los que andan cerca de Dios, en santidad y justicia, están conscientes de que sus mejores días y sus mejores deberes están contaminados con el pecado. Dios ha dado testimonio de la pecaminosidad del mundo proveyendo un Sacrificio eficaz y suficiente por el pecado, necesario en todas las épocas; y se muestra la pecaminosidad de los mismos creyentes al pedirles que confiesen continuamente sus pecados y recurran por fe a la sangre del Sacrificio. Declarémonos culpables ante Dios, humillémonos y dispongámonos a conocer lo peor de nuestro caso. Confesemos honestamente todos nuestros pecados en su plena magnitud, confiando totalmente en su misericordia y verdad por medio de la justicia de Cristo, para un perdón libre y completo y por nuestra liberación del poder y la práctica del pecado.</p>
<br/>




</div>
