<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Juan 5</h2>
<p class="text-justify">Vv. 1-5.El verdadero amor por el pueblo de Dios se puede distinguir de la amabilidad natural o los afectos partidistas por estar unido con el amor de Dios, y la obediencia a sus mandamientos. El mismo Espíritu Santo que enseñó el amor, tendrá que enseñar también la obediencia; el hombre que peca por costumbre o descuida el deber que conoce, no puede amar de verdad a los hijos de Dios.
Como los mandamientos de Dios son reglas santas, justas y buenas de libertad y felicidad, así los que son nacidos de Dios y le aman, no los consideran gravosos, y lamentan no poder servirle en forma más perfecta. Se requiere abnegación, pero los cristianos verdaderos tienen un principio que los hace superar todos los obstáculos. Aunque el conflicto suele ser agudo, y el regenerado se ve derribado, de todos modos se levantará y renovará con denuedo su batalla. Pero todos, salvo los creyentes en Cristo, son esclavos en uno u otro aspecto de las costumbres, opiniones o intereses del mundo. La fe es la causa de la victoria, el medio, el instrumento, la armadura espiritual por la cual vencemos. En fe y por fe nos aferramos de Cristo, despreciamos el mundo y nos oponemos a él. La fe santifica el corazón y lo purifica de las concupiscencias sensuales por las cuales el mundo obtiene ventaja y dominio de las almas. Tiene el Espíritu de gracia que le habita, el cual es mayor que el que está en el mundo. El cristiano verdadero vence al mundo por fe; ve en la vida y conducta del Señor Jesús en la tierra y medio de ella, que debe renunciar y vencer a este mundo. No puede estar satisfecho con este mundo y mira más allá de él y continua inclinado, esforzándose y extendiéndose hacia el cielo. Todos debemos, por el ejemplo de Cristo, vencer al mundo o nos vencerá para nuestra ruina.</p>
<br/>
<p class="text-justify">Vv. 6-8.Estamos corrompidos por dentro y por fuera; por dentro, por el poder y la contaminación del pecado en nuestra naturaleza. Porque nuestra limpieza interior está en Cristo Jesús y por medio de Él, el lavado de la regeneración y la renovación por el Espíritu Santo. Algunos piensan que aquí se representan los dos sacramentos: el bautismo con agua, como señal externa de regeneración y purificación por el Espíritu Santo de la contaminación del pecado; y la cena del Señor, como señal externa del derramamiento de la sangre de Cristo, y de recibirle por fe para perdón y justificación. Estas dos maneras de limpiarse estaban representadas en los antiguos sacrificios y lavados ceremoniales. El agua y la sangre incluyen todo lo que es necesario para nuestra salvación. Nuestras almas son lavadas y purificadas, por el agua, para el cielo y la habitación de los santos en luz. Somos justificados, reconciliados y presentados como justos, por la sangre, a Dios. El Espíritu purificador para el lavado interior de nuestra naturaleza se obtiene por la sangre, habiendo sido satisfecha la maldición de la ley. El agua y la sangre fluyeron del costado del Redentor sacrificado. Él amaba a la Iglesia y se dio por ella para santificarla y limpiarla con el lavamiento del agua por la palabra; para presentársela para sí una Iglesia gloriosa, Efesios v, 25-27. Esto fue hecho en Espíritu de Dios y por Él, conforme a la declaración del Salvador. Él es el Espíritu de Dios y no puede mentir.
Tres dieron testimonio de las doctrinas de la persona de Cristo y su salvación. El Padre, repetidamente, por una voz desde el cielo declaró que Jesús era su Hijo amado. La Palabra declara que Él y el Padre eran Uno, y que quien lo ha visto a Él, ha visto al Padre. También el Espíritu Santo descendió del cielo y se posó en Cristo en su bautismo; Él había dado testimonio de Cristo por medio de todos los profetas, y dio testimonio de su resurrección y oficio de mediador por el don de poderes milagrosos a los apóstoles. Pero se cite o no este pasaje, la doctrina de la trinidad en unidad sigue igualmente firme y cierta.
Hubo tres testimonios para la doctrina enseñada por los apóstoles, respecto de la persona y salvación de Cristo.
1. El Espíritu Santo. Venimos al mundo con una disposición carnal corrupta que es enemistad contra Dios. Que esto sea eliminado por la regeneración y la nueva creación de almas por el Espíritu Santo, es testimonio del Salvador.
2. El agua: establece la pureza y el poder purificador del Salvador. La pureza y la santidad actual y activa de sus discípulos están representadas por el bautismo.
3. La sangre que Él derramó: este fue nuestro rescate, esto testifica de Jesucristo; selló y terminó los sacrificios del Antiguo Testamento. Los beneficios procurados por su sangre, prueban que Él es el Salvador del mundo. No es de extrañarse que quien rechace esta evidencia sea juzgado por blasfemar del Espíritu de Dios. Los tres testigos son para uno e idéntico propósito; concuerdan en una y la misma cosa.</p>
<br/>
<p class="text-justify">Vv. 9-12.Nada puede ser más absurdo que la conducta de los que dudan de la verdad del cristianismo, mientras en los asuntos corrientes de la vida no vacilan en proceder basados en el testimonio humano, y considerarían desquiciado a quien declinara hacerlo así. El cristiano verdadero ha visto su culpa y miseria, y su necesidad de un Salvador así. Ha visto lo adecuado de tal Salvador para todas sus necesidades y circunstancias espirituales. Ha encontrado y sentido el poder de la palabra y la doctrina de Cristo, humillando, sanando, vivificando y consolando su alma. Tiene una nueva disposición y nuevos deleites, y no es el hombre que fue anteriormente. Pero aún halla un conflicto consigo mismo, con el pecado, con la carne, el mundo y las potestades malignas. Pero halla tal fuerza de la fe en Cristo, que puede vencer al mundo y seguir viaje hacia uno mejor. Tal seguridad tiene el creyente del evangelio: tiene un testigo en sí mismo que acaba con toda duda del tema, salvo en las horas de tinieblas o conflicto; pero no pueden sacarlo de su fe en las verdades principales del evangelio.
Aquí está lo que hace tan espantoso el pecado del incrédulo: el pecado de la incredulidad. Él trata de mentiroso a Dios; porque no cree el testimonio que Dios dio de su Hijo. En vano es que un hombre alegue que cree el testimonio de Dios en otras cosas, mientras lo rechaza en esto. El que rehúsa confiar y honrar a Cristo como Hijo de Dios, el que desdeña someterse a su enseñanza como Profeta, a confiar en su expiación e intercesión como gran Sumo Sacerdote u obedecerle como Rey, está muerto en pecado, bajo condenación; una moral externa, conocimiento, formas, nociones o confianzas de nada le servirán.</p>
<br/>
<p class="text-justify">Vv. 13-17.Basados en todas estas pruebas sólo es justo que creamos en el nombre del Hijo de Dios. Los creyentes tienen vida eterna en el pacto del evangelio. Entonces, recibamos agradecidos el registro de la Escritura. Siempre abundando en la obra del Señor, sabiendo que nuestro trabajo en el Señor no es en vano. El Señor Cristo nos invita a ir a Él en todas las circunstancias, con nuestras súplicas y peticiones, a pesar del pecado que nos asedia. Nuestras oraciones deben ser ofrecidas siempre sometidas a la voluntad de Dios. En algunas cosas son contestadas rápidamente, en otras son otorgadas de la mejor manera, aunque no como se pidió. Debemos orar por el prójimo y por nosotros mismos. Hay pecados que batallan contra la vida espiritual en el alma y contra la vida de lo alto. No podemos orar que sean perdonados los pecados de los impenitentes e incrédulos mientras sigan así; ni que les sea otorgada misericordia, la cual supone el perdón de pecado, mientras sigan voluntariamente así. Pero podemos orar por su arrepentimiento, por el enriquecimiento de ellos con la fe en Cristo, y sobre la base de ella, por todas las demás misericordias salvadoras.
Debemos orar por el prójimo y por nosotros rogando al Señor que perdone y recupere al caído y alivie al tentado y afligido. Seamos agradecidos de verdad porque no hay pecado para muerte del cual uno se arrepienta verdaderamente.</p>
<br/>
<p class="text-justify">Vv. 18-21.Toda la humanidad está dividida en dos partes o esferas: el que pertenece a Dios y el que pertenece al maligno. Los creyentes verdaderos pertenecen a Dios; son de Dios y vienen de Él, para Él y por Él; mientras el resto, de lejos la gran mayoría, está en el poder del maligno; hacen sus obras y apoyan su causa. Esta declaración general comprende a todos los incrédulos, cualquiera sea su profesión, situación o posición o cualquiera sea el nombre por el que se llamen. El Hijo guía a los creyentes al Padre y ellos están en el amor y el favor de ambos; en unión con ambos, por la morada y obra del Espíritu Santo. ¡Dichosos aquellos a los que es dado saber que el Hijo de Dios ha venido, y tienen un corazón que confía y descansa en el que es verdadero! Que este sea nuestro privilegio: que seamos guardados de todos los ídolos y las falsas doctrinas, y del amor idólatra a los objetos mundanos, y que seamos mantenidos por el poder de Dios, por medio de la fe, para salvación eterna. A este verdadero Dios vivo sea la gloria y el dominio por siempre jamás. Amén.</p>
<br/>




</div>
