<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Pedro 3</h2>
<p class="text-justify">Vv. 1-7.La esposa debe cumplir su deber con su esposo, aunque él no obedezca la palabra. Diariamente vemos cuán de cerca observan los hombres malos los caminos y la vida de los que profesan la religión. No se prohibe vestirse bien, sino la vanidad y lo costoso del atavío. La gente religiosa debe cuidar que toda su conducta responda a su profesión, pero ¡cuán pocos saben cuál es la medida correcta y los límites de las dos necesidades de la vida: comida y vestido! A menos que la pobreza sea nuestro cuchillo y no nos permita, escasamente habrá uno que no desee algo más allá de lo que es bueno para nosotros. Muchos más son contemplados en la bajeza de su situación que en la humildad de su mente; y muchos no están así de limitados, pero desperdician su tiempo y dinero en trivialidades.
El apóstol manda a las mujeres cristianas a ponerse algo que no es corruptible, que embellece el alma, las virtudes del Espíritu Santo de Dios. La principal preocupación de la cristiana verdadera está en ordenar rectamente su propio espíritu. Esto hará más por estabilizar los afectos y estimular la estima del marido que los adornos estudiados o la ropa de moda, acompañada por un temperamento agresivo y perverso. Las cristianas deben cumplir su deber unas con otras con una mente dispuesta y por obediencia al mandamiento de Dios. Las esposas deben someterse a sus maridos, no por miedo ni terror, sino por el deseo de portarse bien y complacer a Dios. El deber del marido hacia su mujer implica respetarla debidamente, mantener su autoridad, protegerla y depositar su confianza en ella. Ellas son coherederas de todas las bendiciones de esta vida y de la venidera, y deben vivir pacíficamente los unos con las otras. La oración endulza su conducta. No basta que oren con la familia; marido y mujer deben orar juntos a solas y con sus hijos. Los que están familiarizados con la oración, encuentran una dulzura indecible en ella, tal que no serán estorbados en ella. Vive santamente para que ores mucho; y ora mucho para que vivas santamente.</p>
<br/>
<p class="text-justify">Vv. 8-13.Aunque los cristianos no siempre estén exactamente en unanimidad pueden, sin embargo, compadecerse unos a otros, y amarse como hermanos.
Si un hombre desea vivir cómodamente en la tierra o poseer la vida eterna en el cielo debe frenar su lengua de las palabras malas, abusivas o engañosas. Debe abandonar las malas acciones y abstenerse de ellas, hacer todo el bien que pueda, y buscar la paz con todos los hombres. Porque Dios, omnisciente y presente en todo lugar, vela sobre los justos y se encarga de cuidarlos. Nadie puede ni debe dañar a los que imitan el ejemplo de Cristo que es la bondad perfecta y que hizo el bien a los demás y a sus seguidores.</p>
<br/>
<p class="text-justify">Vv. 14-22.Santificamos a Dios ante los demás cuando nuestra conducta les invita y estimula a glorificarle y honrarle. ¿Cuál era la base y la razón de la esperanza de ellos? Seamos capaces de defender nuestra religión con mansedumbre en el temor de Dios. No hay lugar para otros temores donde hay este gran temor: no perturba.
La conciencia es buena cuando hace bien su oficio. En triste condición está la persona en quien el pecado y el sufrimiento se encuentran; el pecado hace que el sufrimiento sea extremado, desconsolador y destructor. Seguramente es mejor sufrir por hacer el bien que por hacer el mal que nuestra natural impaciencia sugiera en ocasiones.
El ejemplo de Cristo es un argumento en pro de la paciencia cuando se sufre. En el caso del sufrimiento de nuestro Señor, Él no conoció pecado, pero sufrió en lugar de los que no conocían justicia. La intención y la finalidad bendita de nuestro Señor fue reconciliarnos a Dios y llevarnos a la gloria eterna. Fue llevado a la muerte en su naturaleza humana, pero fue resucitado por el poder del Espíritu Santo. Si Cristo no pudo ser librado de los sufrimientos, ¿por qué piensan los cristianos que ellos sí debieran? -Dios toma nota exacta de los medios y las ventajas que tiene la gente de toda época. En cuanto al mundo antiguo, Cristo envió su Espíritu advirtiendo a Noé. Pero aunque la paciencia de Dios espera por mucho tiempo, cesará al final. Los espíritus de los pecadores desobedientes, tan pronto como están fuera de sus cuerpos, son entregados a la prisión del infierno, donde están ahora los que despreciaron la advertencia de Noé, y desde la cual no hay redención.
La salvación de Noé en el arca, flotando sobre el agua, que le llevó sobre el diluvio, logró la salvación de todos los creyentes verdaderos. Esa salvación temporal por el arca fue un tipo de la salvación eterna de los creyentes por el bautismo del Espíritu Santo. Para evitar errores, el apóstol declara qué quiere decir por bautismo que salva; no la ceremonia externa del lavado con agua que, en sí misma, no hace más que quitar la inmundicia de la carne, sino el bautismo del cual el agua bautismal es un signo. No es la ordenanza externa, pero el hombre, por la regeneración del Espíritu, es capacitado para arrepentirse y profesar la fe, y proponerse la vida nueva, rectamente, y como en presencia de Dios. Cuidémonos de no apoyarnos en las formas externas. Aprendamos a mirar espiritualmente las ordenanzas de Dios y a inquirir por el efecto espiritual y la obra de ellos en nuestras conciencias. Nosotros desearíamos que toda la religión se redujera a cosas externas, pero muchos de los que fueron bautizados y participaron constantemente a las ordenanzas, han seguido sin Cristo, murieron en sus pecados y ahora están más allá del rescate. Entonces no descanséis hasta estar limpiados por el Espíritu de Cristo y la sangre de Cristo. Su resurrección de entre los muertos es lo que nos asegura la purificación y de la paz.</p>
<br/>




</div>
