<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Pedro 5</h2>
<p class="text-justify">Vv. 1-4.El apóstol Pedro no ordena, exhorta. No reclama poder de gobierno sobre todos los pastores e iglesias. Era honra particular de Pedro y de otros pocos, el ser testigo de los sufrimientos de Cristo; pero es privilegio de todo verdadero creyente participar de la gloria que ha de ser revelada. Estos cristianos pobres, dispersos y sufridos, eran la grey de Dios, redimida para Dios por el gran Pastor, y viven en santo amor y comunión, conforme a la voluntad de Dios. También son dignificados con el título de heredad de Dios o sacerdocio de Dios. La porción peculiar, escogida para su pueblo es disfrutar de su especial favor, y darle un servicio especial. Cristo es el Príncipe de los pastores de toda la grey y heredad de Dios. Todos los ministros fieles recibirán una corona inmarcesible de gloria, infinitamente mejor y más honrosa que toda la autoridad, riqueza y placer del mundo.</p>
<br/>
<p class="text-justify">Vv. 5-9.La humildad preserva la paz y el orden en todas las iglesias y sociedades cristianas; el orgullo la perturba. Cuando Dios da gracia para ser humilde, también da sabiduría, fe y santidad. Ser humilde y someterse a nuestro Dios reconciliado, trae más consuelo al alma que los deleites de la soberbia y la ambición. Pero es a su debido tiempo ; no en el tiempo que tú imaginas, sino en el tiempo que Dios ha establecido sabiamente. Él espera, y ¿no esperarás tú? ¡Cuántas dificultades superará la firme creencia en su sabiduría, poder y bondad! Entonces, humillaos bajo su mano. -“Echad toda vuestra ansiedad”, preocupaciones personales, angustias familiares, ansiedad por el presente, cuidados por el futuro, por vosotros mismos, por otros, por la iglesia, echadlo todo sobre Dios. Son cargas onerosas, y suelen ser muy pecaminosas cuando tienen sus raíces en la desconfianza y la incredulidad, cuando torturan y distraen la mente, nos anulan para el servicio e impiden que nos sintamos contentos en el servicio de Dios. El remedio es echar nuestra solicitud sobre Dios, y dejar todo suceso a disposición de su gracia y su sabiduría. La creencia firme en que la voluntad y los consejos divinos son correctos calma el espíritu del hombre. En verdad el piadoso suele olvidar esto, y se angustia sin necesidad. Remítelo todo a la buena disposición de Dios. Las minas de oro de todas las consolaciones y bienes espirituales son suyas y del Espíritu mismo. Entonces, ¿no nos dará lo que es bueno para nosotros, si humildemente esperamos en Él, y echamos sobre su sabiduría y amor la carga de proveernos? -Todo el plan de Satanás es devorar y destruir almas. Él siempre está maquinando a quien cazar para llevarlo a la ruina eterna. Nuestro deber claro es ser sobrios; esto es, gobernar al hombre exterior y al interior con las reglas de la temperancia. Velad: sospechar del peligro constante de este enemigo espiritual, evitar con atención y diligencia sus designios. Sed firmes, sólidos, por fe. El hombre no puede luchar en un cenagal, donde no hay un punto firme donde apoyar el pie; sólo la fe suministra un apoyo. Eleva el alma al sólido terreno de avanzada de las promesas, y allí se asegura. La consideración de lo que otros sufren es buena para animarnos a soportar nuestra parte en toda aflicción; en cualquier forma o por cualquier medio que Satanás nos ataque, podemos saber que nuestros hermanos han pasado por lo mismo.</p>
<br/>
<p class="text-justify">Vv. 10-14.En conclusión, el apóstol ora a Dios por ellos, como el Dios de toda gracia. Perfeccione quiere decir su progreso hacia la perfección. Afirme se refiere a la cura de nuestra natural ligereza e inconstancia. Fortalezca tiene que ver con el crecimiento de las virtudes, especialmente en las que estamos más bajos y débiles. Establezca significa fijarse sobre un fundamento firme, y puede referirse a aquel que es el fundamento y fuerza del creyente. El poder de estas doctrinas en el corazón y sus frutos en la vida, muestra quiénes son partícipes de la gracia de Dios. La conservación y el crecimiento en el amor cristiano, y en el afecto mutuo, no es cuestión de un saludo vacío, sino la marca y signo de Jesús sobre sus seguidores. Otros pueden tener una falsa paz por un tiempo, y los malvados pueden desearla para sí mismos y para sus iguales; pero la de ellos es una vana esperanza, y llegará a nada. En Cristo se encuentra una paz sólida, la cual fluye de Él.</p>
<br/>




</div>
