<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Pedro 4</h2>
<p class="text-justify">Vv. 1-6.Los mejores y más firmes argumentos contra el pecado se toman de los sufrimientos de Cristo. Él murió para destruir el pecado; y aunque se sometió jubilosamente a los peores sufrimientos, nunca dio lugar al menor pecado. Las tentaciones no podrían dominar si no fuera por la propia corrupción del hombre; pero los cristianos verdaderos hacen de la voluntad de Dios, no de sus propios deseos ni lujuria, la regla de su vida y de sus acciones. La conversión verdadera hace un cambio maravilloso en el corazón y en la vida. Altera la mente, el juicio, los afectos y la conducta. Cuando el hombre se convierte verdaderamente, le resulta muy triste pensar cómo pasó el tiempo pasado de su vida.
Un pecado trae a otro. Aquí se mencionan seis pecados que dependen unos de otros. Deber del cristiano es no sólo guardarse de la maldad crasa, sino también de las cosas que conducen al pecado o que tienen apariencia de mal. El evangelio había sido predicado a los que desde entonces estaban muertos, que por el juicio carnal y orgulloso de los hombres impíos fueron condenados como malhechores, sufriendo algunos hasta la muerte. Pero siendo vivificados para la vida divina por el Espíritu Santo, vivieron para Dios como sus siervos devotos. Los creyentes no deben temer aunque el mundo se burle de ellos y les haga reproches.</p>
<br/>
<p class="text-justify">Vv. 7-11.Muy cercana estaba la destrucción de la iglesia y la nación judía, anunciada por nuestro Salvador. El rápido acercamiento de la muerte y el juicio nos concierne a todos, a lo cual nuestras mentes son llevadas naturalmente por estas palabras. Nuestro próximo fin es un argumento poderoso para hacernos sobrios en todos los asuntos mundanos, y fervientes en la religión.
Hay tantas cosas malas en todos, que Satanás prevalecerá para incitar divisiones y discordias, si el amor no cubre, excusa y perdona los errores y las faltas de los demás, por las cuales cada uno necesita la tolerancia del prójimo. Pero no tenemos que suponer que el amor cubrirá o enmendará los pecados de los que los practican, como para inducir a Dios a perdonarlos.
La naturaleza de la obra cristiana, que es obra elevada y difícil, la bondad del Amo, y la excelencia de la recompensa, todo requiere que nuestros esfuerzos sean serios y fervientes. En todos los deberes y los servicios de la vida, debemos apuntar a la gloria de Dios como nuestro fin principal. Miserable e inestable es el que se aferra a sí mismo y se olvida de Dios; sólo está confundido por su mérito, ganancia y bajos fines, que a menudo se frustran y que, cuando los alcanza, él y ellos deben perecer juntos en poco tiempo. Pero el que se ha dado totalmente a Dios puede decir confiadamente que el Señor es su porción y que nada sino la gloria por Jesucristo es sólido y duradero: eso dura para siempre.</p>
<br/>
<p class="text-justify">Vv. 12-19.El Espíritu Santo es glorificado con la paciencia y la fortaleza en el sufrimiento, con la dependencia de las promesas de Dios y por guardar la palabra que el Espíritu Santo ha revelado; pero es insultado y blasfemado por el desprecio y los reproches a los creyentes. Uno pensaría que las precauciones son innecesarias para los cristianos, pero sus enemigos los acusan falsamente de crímenes horribles. Hasta el mejor de los hombres necesita ser precavido contra el peso de los pecados. No hay consuelo en los sufrimientos cuando nos los acarreamos por nuestro propio pecado y necedad. Una época de calamidad universal se acerca, como lo predijo nuestro Salvador, Mateo xxiv, 9, 10. Si tales cosas acontecen en esta vida, ¡qué horrible será el día del juicio! -Verdad es que los justos apenas se salvan aun los que se proponen andar rectamente en los caminos de Dios. Esto no significa que el propósito y la obra de Dios sean inciertos; pero sólo alude a las grandes dificultades y encuentros duros del camino; que ellos pasan por tantas tentaciones y tribulaciones, por tantas luchas de fuera y tantos temores de dentro. Pero todas las dificultades externas serían como nada si no fuera por la lujuria y la corrupción interna. Estos son los peores impedimentos y dificultades. Si el camino del justo es tan duro, entonces, ¡cuán duro será el final del pecador impío que se complace en el pecado, y piensa que el justo es necio por todos sus dolores! -La única manera de mantener bien el alma es encomendarla a Dios por la oración y la perseverancia paciente en el bien hacer. Él vencerá todo para la ventaja definitiva del creyente.</p>
<br/>




</div>
