<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Pedro 2</h2>
<p class="text-justify">Vv. 1-10.Hablar mal es señal de maldad y engaño en el corazón y estorba nuestro provecho por la palabra de Dios. La vida nueva necesita un alimento idóneo. Los infantes desean leche y hacen por ella lo mejor que pueden conforme a su capacidad; así deben ser los deseos del cristiano por la palabra de Dios. Nuestro Señor Jesucristo es muy misericordioso con nosotros, miserables pecadores y tiene plenitud de gracia. Pero hasta el mejor de los siervos de Dios en esta vida tiene sólo un anticipo de las consolaciones de Dios.
Cristo es llamado Piedra para enseñar a sus siervos que Él es la protección y la seguridad de ellos, el fundamento sobre el cual son edificados. Él es precioso en la excelencia de su naturaleza, la dignidad de su oficio, y la gloria de sus servicios. Todos los creyentes verdaderos son un sacerdocio santo; sagrado para Dios, servicial para los demás, dotados de dones y gracias celestiales. Pero los sacrificios más espirituales de lo mejor en oración y alabanza, no son aceptables sino por medio de Jesucristo. -Él es la piedra del ángulo que une a todo el número de creyentes en un templo eterno, y soporta el peso de toda la construcción. Elegido o escogido para un fundamento que es eterno. Precioso más allá de toda comparación por todo lo que pueda tener valor. Ser edificado en Cristo significa creer en Él; pero en esto se engañan muchos a sí mismos, no consideran lo que es, ni la necesidad de participar de la salvación que Él ha obrado. Aunque la estructura del mundo se estuviera cayendo a pedazos, el hombre que está edificado sobre este fundamento puede oírlo sin temer. Él no será confundido . El alma creyente se apresura a ir a Cristo, pero nunca encuentra causa para apresurarse a huir de Él.
Todos los cristianos verdaderos son linaje escogido; constituyen una familia, un pueblo distinto del mundo: de otro espíritu, principio y costumbre; que nunca podrían ser si no fueran escogidos en Cristo para ser tales y ser santificados por su Espíritu. El primer estado de ellos es de grandes tinieblas, pero son sacados de las tinieblas a un estado de gozo, placer y prosperidad, para que muestren las alabanzas del Señor por la profesión de Su verdad y su buena conducta. -¡Qué enormes son sus obligaciones con Él, que los ha hecho su pueblo, y les ha mostrado misericordia! -Estar sin esta misericordia es un estado espantoso, aunque el hombre tenga todos los placeres mundanales. Nada hay que obre el arrepentimiento tan bien como el pensamientos correcto acerca de la misericordia y el amor de Dios. No nos atrevamos a abusar ni a afrentar la libre gracia de Dios si queremos ser salvados por ella; pero todos los que quieran ser contados entre los que obtienen misericordia anden como su pueblo.</p>
<br/>
<p class="text-justify">Vv. 11, 12.Hasta el mejor de los hombres, el linaje escogido, el pueblo de Dios tiene que ser exhortado a guardarse de los peores pecados. Las concupiscencias carnales son las más destructivas para el alma del hombre. Es un juicio doloroso ser entregado a ellas.
Hay un día de visitación que viene, en el cual Dios puede llamar al arrepentimiento por su palabra y su gracia; entonces, muchos glorificarán a Dios y las santas vidas de su pueblo habrán promovido el feliz cambio.</p>
<br/>
<p class="text-justify">Vv. 13-17.La conducta del cristiano debe ser honesta; lo cual no puede ser, si no se cumplen justa y cuidadosamente todos los deberes relacionados; el apóstol los trata aquí con claridad. Considerar esos deberes es la voluntad de Dios; en consecuencia, es deber del cristiano y el modo de silenciar las calumnias viles de hombres ignorantes y necios. Los cristianos deben proponerse, en todas sus relaciones, conducirse rectamente para que no hagan de su libertad un manto o cubierta de alguna maldad, o descuido del deber, pero deben recordar que son siervos de Dios.</p>
<br/>
<p class="text-justify">Vv. 18-25.Los criados de aquellos tiempos por lo general eran esclavos, y tenían amos paganos, que solían utilizarlos con crueldad; pero el apóstol les instruye que se sometan a sus amos puestos sobre ellos por la providencia, con el temor de deshonrar u ofender a Dios. No sólo a los agradados con el servicio razonable, sino con los severos y con los que se enojan sin causa. La mala conducta pecaminosa de una persona no justifica la conducta pecaminosa de la otra; el siervo tiene que cumplir su deber aunque el amo sea pecaminosamente perverso y malo. Pero los amos debieran ser mansos y buenos con sus siervos e inferiores. -¿Qué gloria o distinción habría en que los cristianos profesos sean pacientes cuando se les corrigen sus faltas? Pero si cuando se comportan bien y son maltratados por los amos paganos, soberbios y apasionados, lo soportan sin quejas sin ira y sin propósitos de venganza, y perseveran en su deber, esto será aceptable para Dios como efecto distintivo de su gracia y será recompensado por Él.
La muerte de Cristo tenía el propósito no sólo de ser ejemplo de paciencia en los sufrimientos, sino de llevar nuestros pecados; soportó el castigo de ellos, y con ello satisfizo la justicia divina. Por ello, nos los quita. Los frutos de los sufrimientos de Cristo son la muerte del pecado, y una nueva vida santa de justicia; de ellas tenemos ejemplo, motivaciones poderosas, y capacidad para cumplirlos, por la muerte y resurrección de Cristo. Nuestra justificación: Cristo fue molido y crucificado como sacrificio por nuestros pecados, y por sus llagas fueron curadas las enfermedades de nuestra alma.
Aquí está el pecado del hombre: él se descarría y esto es su propio acto. Su desgracia: él se aleja del redil, del Pastor y del rebaño, y, así, se expone a peligros sin cuenta. Aquí está la recuperación por la conversión; ahora vuelven como efecto de la gracia divina. De todos sus errores y descarríos regresan a Cristo. Los pecadores siempre están descarriados antes de su conversión; la vida de ellos es un error continuo.</p>
<br/>




</div>
