<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Pedro 1</h2>
<p class="text-justify">Vv. 1-9.Esta epístola está dirigida a los creyentes en general, que son extranjeros en toda ciudad o país donde vivan y están diseminados por todas las naciones. Ellos tienen que atribuir su salvación al amor electivo del Padre, la redención del Hijo y la santificación del Espíritu Santo; y, así, dar gloria al Dios único en tres Personas en cuyo nombre han sido bautizados.
La esperanza en el vocabulario mundano se refiere sólo a un bien incierto, porque todas las esperanzas mundanas son inestables, edificadas sobre arena, y las esperanzas del cielo que tiene el mundano son conjeturas ciegas y sin fundamento. Pero la esperanza de los hijos del Dios vivo es una esperanza viva; no sólo acerca de su objeto, sino también en su efecto. Vivifica y consuela en todas las angustias, capacita para enfrentar y superar todas las dificultades. La misericordia es la fuente de todo esto; sí, gran misericordia y misericordia múltiple. Esta bien cimentada esperanza de salvación es un principio activo y vivo de obediencia en el alma del creyente.
El tema del gozo cristiano es la memoria de la felicidad puesta por delante. Es incorruptible no puede acabarse; es una fortuna que no se puede gastar. También es incontaminada lo que significa su pureza y perfección. Inmarcesible porque no es más o menos placentera a veces, sino siempre la misma, no cambia. Todas las posesiones de aquí están manchadas con defectos y fallas; aún falta algo: casas lindas que tienen preocupaciones tristes revoloteando en torno a sus techos dorados y bien pintados; camas blandas y mesas llenas, a menudo con cuerpos enfermos y estómagos revueltos. Todas las posesiones están manchadas de pecado, sea al obtenerlas o al usarlas. ¡Cuán prontos estamos para hacer de las cosas que tenemos ocasión e instrumento de pecado, y pensar que no hay libertad ni deleite en su uso, sin abusar de ellas! Las posesiones mundanas son inciertas y pronto pasan como las flores y las plantas del campo. Eso debe ser del más alto valor, ya que se pone en el lugar mejor y más elevado: el cielo. Dichosos aquellos cuyos corazones pone el Espíritu Santo en esta herencia. Dios no sólo da gracia a su pueblo, pero lo preserva para gloria.
Cada creyente siempre tiene algo en que puede regocijarse grandemente; esto debe demostrarse en el semblante y la conducta. El Señor no aflige por gusto aunque su sabio amor suele asignar pruebas agudas para mostrar el corazón de su pueblo y para hacerles el bien al final. El oro no aumenta por ser probado en el fuego, se vuelve menos; pero la fe se afirma y multiplica por las tribulaciones y aflicciones. El oro debe perecer al final y sólo puede comprar cosas perecederas, mientras la prueba de fe será hallada para alabanza, honra y gloria. Esto debe reconciliarnos con las aflicciones presentes. Busquemos entonces creer en la excelencia de Cristo en sí y de su amor por nosotros; esto encenderá un fuego tal en el corazón que lo elevará en un sacrificio de amor hacia Él. La gloria de Dios y nuestra propia felicidad están tan unidas que si ahora buscamos sinceramente una, obtendremos la otra, cuando el alma ya no esté más sujeta al mal. La certeza de esta esperanza es como si los creyentes ya la hubieran recibido.</p>
<br/>
<p class="text-justify">Vv. 10-12.Jesucristo fue el tema principal de los estudios de los profetas. La indagatoria de ellos en los sufrimientos de Cristo y las glorias que seguirían, condujeron a una visión de todo el evangelio, cuyo resumen es, que Cristo Jesús fue entregado por nuestras ofensas y levantado de nuevo para nuestra justificación.
Dios se agradó en contestar nuestras necesidades más que nuestros pedidos. La doctrina de los profetas y la de los apóstoles concuerda exactamente, porque viene del mismo Espíritu de Dios. El evangelio es la ministración del Espíritu; su éxito depende de su operación y bendición. Entonces, busquemos con diligencia las Escrituras que contienen la doctrina de la salvación.</p>
<br/>
<p class="text-justify">Vv. 13-16.Como el viajero, el atleta, el guerrero y el trabajador, recogen sus vestiduras largas y sueltas, para estar preparados para sus actividades, así hagan los cristianos con sus mentes y afectos. Sed sobrios, velad contra todos los peligros y enemigos espirituales y sed templados en toda conducta. Sed sobrios en la opinión y en la conducta y humildes en vuestros juicios sobre vosotros mismos. Una confianza firme y perfecta en la gracia de Dios armoniza con los mejores esfuerzos en nuestro deber.
La santidad es el deseo y el deber de todo cristiano. Debe estar en todos los asuntos, en cada condición, y para toda la gente. Debemos velar y orar especialmente en contra de los pecados a que nos inclinamos. La palabra escrita de Dios es la regla más segura de la vida del cristiano y por esta regla se nos manda ser santos en todo. Dios hace santos a quienes salva.</p>
<br/>
<p class="text-justify">Vv. 17-25.La santa confianza en Dios como Padre y el temor que se le debe como Juez, armonizan; y considerar siempre a Dios como Juez le hace querido como Padre para nosotros. Si los creyentes hacen el mal, Dios los visitará con correctivos. Entonces, los cristianos no deben dudar de la fidelidad de Dios a sus promesas, ni den lugar al temor esclavizante por su ira, pero reverencien su santidad. El profeso que no teme está indefenso y Satanás lo cautiva a su voluntad; el profeso desalentado no tiene corazón que le valga para servirse de sus ventajas y es llevado fácilmente a rendirse.
El precio pagado por la redención del hombre fue la preciosa sangre de Cristo.
No sólo la conversación francamente mala, sino la que no aprovecha es altamente peligrosa, aunque se diga que es por costumbre. Necio es resolver: Yo viviré y moriré en tal forma, porque así hicieron mis antepasados.
Dios tenía propósitos de favor especial para su pueblo mucho antes que manifestara tal gracia a ellos. Pero la claridad de la luz, los soportes de la fe, el poder de las ordenanzas, son todos mucho más grandes que lo que antes fueron, desde que Cristo vino a la tierra. El consuelo de esto es que habiendo sido hechos uno con Cristo por fe, su gloria presente es una garantía de que donde Él esté, también estaremos nosotros, Juan xiv, 3. El alma debe ser purificada antes que pueda abandonar sus propios deseos e indulgencias. La palabra de Dios implantada en el corazón por el Espíritu Santo, es un medio de vida espiritual, que nos estimula al deber, obrando un cambio total en las disposiciones y afectos del alma, hasta que la lleva a la vida eterna.
En contraste con la excelencia del hombre espiritual renovado, como nacido de nuevo, nótese la vanidad del hombre natural. En su vida y en su caída, es como el pasto, la flor de la hierba, que pronto se marchita y muere. Debemos oír, y recibir y amar la santa palabra viva, y más bien arriesgar todo que perderla; hay que quitar todas las demás cosas del lugar debido a ella. Debemos alojarla en nuestro corazón como nuestro único tesoro y prenda segura del tesoro de gloria que hay para los creyentes en el cielo.</p>
<br/>




</div>
