<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Reyes 19</h2>
<p class="text-justify">Vv. 1-8.Jezabel envió un mensaje amenazador a Elías. Los corazones carnales son endurecidos y enfurecidos contra Dios, por aquello que debe convencerlos de pecado y vencerlos. La mucha fe no siempre es sinónimo de fe firme o fuerte. Elías podía ser útil a Israel en este momento y tenía toda la razón para depender de la protección de Dios mientras hacía la obra de Dios, pero huye. El suyo no era el deseo deliberado de la gracia, como el de Pablo, de irse y estar con Cristo. Así, Dios dejó solo a Elías para mostrar que cuando era osado y fuerte, era en el Señor y en el poder de su fuerza; pero solo no era mejor que sus padres. Aunque nosotros no sabemos, Dios sabe qué designio tiene para nosotros, qué servicios, qué pruebas, y Él se encargará de darnos gracia suficiente.</p>
<br/>
<p class="text-justify">Vv. 9-13.La pregunta que hace Dios, ¿qué haces aquí, Elías? Es un reproche. A menudo nos correspnde preguntar si estamos en nuestro lugar, y en la senda del deber: ¿estoy dónde debo estar? ¿A dónde me llama Dios, dónde está mi obra, y dónde puedo ser útil? Elías se queja de la gente y de su obstinación para pecar; yo soy el único que queda. Desesperar del éxito puede estorbar muchas buenas empresas. -¿Fue hasta allí Elías para encontrarse con Dios? Él descubrirá que Dios le saldrá al encuentro. El viento, el terremoto, el fuego no le hicieron taparse la cara, pero sí el silbo suave y apacible. Las almas bondadosas son más afectadas por las tiernas misericordias del Señor que por sus terrores. La suave voz de Aquel que habla desde la cruz, o del trono de la gracia, va acompañada de un poder peculiar para tomar posesión del corazón.</p>
<br/>
<p class="text-justify">Vv. 14-18.Dios repite la pregunta: ¿Qué haces aquí? Entonces él se lamenta de su desazón, y ¿a dónde irán los profetas de Dios con esa clase de quejas sino a su Señor? -El Señor le dio una respuesta. Declara que la malvada casa de Acab será desarraigada, que el pueblo de Israel será castigado por sus pecados; y muestra que Elías no había quedado solo, como él suponía, y que, además se le daría un ayudante. De esta manera fueron contestadas y satisfechas todas sus quejas.
Los fieles de Dios suelen ser a menudo sus protegidos, Salmo lxxxiii, 3, y la iglesia visible apenas se puede ver: el trigo se pierde entre la cizaña, y el oro en el oropel, hasta que llegue el día de separar, refinar y cernir. Conoce el Señor a los que son suyos, aunque nosotros no; Él ve en lo secreto. Cuando lleguemos al cielo echaremos de menos a muchos que pensamos, íbamos a encontrar allá; encontraremos a muchos que no pensamos encontrar allá. El amor de Dios frecuentemente resulta ser más grande que la caridad del hombre, y mucho más amplio.</p>
<br/>
<p class="text-justify">Vv. 19-21.Elías encontró a Eliseo por orden divina, no en la escuela de los profetas sino en el campo; no leyendo, orando ni sacrificando, sino arando. La ociosidad no honra al hombre, ni la agricultura es desgracia para ningún hombre. Un llamado honesto en el mundo no nos saca del camino de nuestro llamamiento celestial, más de lo que afectó a Eliseo. Su corazón fue tocado por el Espíritu Santo y él estuvo listo para dejarlo todo para ayudar a Elías. Es en el día de su poder que su pueblo se ofrecerá voluntario; ni tampoco irá nadie a Cristo a menos que sean llevados a Él. Era una época desalentadora para que los profetas salieran. Un hombre que consultara con carne y sangre no hubiera querido el manto de Elías, pero Eliseo deja todo alegremente para acompañarlo. Cuando el Salvador dijo: Sígueme, fueron abandonados alegremente los amigos más queridos y las ocupaciones más provechosas, y se cumplieron los deberes más arduos por amor a su nombre. Que nosotros, en forma similar, sintamos la energía de su gracia obrando poderosamente en nosotros, y que, por una sumisión sin reservas, podamos de inmediato asegurar nuestro llamamiento y elección.</p>
<br/>




</div>
