<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Samuel 17</h2>
<p class="text-justify">Vv. 1-11.Los hombres dependen tan completamente de Dios en todas las cosas, que cuando Él retira su ayuda, el más valeroso y decidido no encuentra corazón ni brazos como lo demuestra la experiencia diaria.</p>
<br/>
<p class="text-justify">Vv. 12-30.Isaí no pensó en mandar su hijo al ejército en esa situación crítica, pero el sabio Dios ordena las acciones y los asuntos para que sirvan a su designio.
En épocas de formalismo e indiferencia general, todo grado de celo que implique disposición para ir adelante o para aventurarse en la causa de Dios más que los demás, será tildado de orgullo y ambición, y nada menos que por los parientes cercanos como Eliab, o por los superiores negligentes. Fue una prueba de la mansedumbre, paciencia y constancia de David. Tenía el derecho y la razón de su lado, pero no devolvió golpe por golpe; con una respuesta blanda calmó la ira de su hermano. La derrota de su propia pasión fue más honrosa que la de Goliat. Quienes emprenden grandes servicios públicos, no deben encontrar raro que hablen mal de ellos y que se les opongan personas de quienes debían esperan apoyo y ayuda. Deben proseguir humildemente con su obra haciendo frente no sólo a las amenazas del enemigo sino a los dardos y sospechas de los amigos.</p>
<br/>
<p class="text-justify">Vv. 31-39.Un pastorcillo, llegado esa misma mañana directamente de su tarea de cuidar ovejas, tuvo más valor que todos los hombres poderosos de Israel. De esta manera, Dios a menudo envía buenas palabras a su Israel y hace grandes cosas por ellos por medio de lo necio y débil del mundo. De la manera que había respondido con mansedumbre a la pasión de su hermano, David respondió con fe al temor de Saúl.
Cuando David cuidaba ovejas, demostró que era muy cuidadoso y atento con su rebaño. Esto nos recuerda a Cristo, el buen Pastor, que no sólo se aventuró, sino que entregó su vida por las ovejas. Nuestra experiencia debiera animarnos a confiar en Dios y a ser valientes en el camino del deber. El Dios que ha liberado, libera y seguirá liberando.
David tuvo la autorización para pelear con el filisteo. Al no estar acostumbrado a una armadura, como la que Saúl le puso, no estaba satisfecho de ir de esa manera; esto era del Señor, para que se viera con toda claridad que él luchó y venció por fe y que la victoria era de Aquel que obra a través de los medios e instrumentos más débiles y despreciados. No debe preguntarse cuán excelente es una cosa, sino si es apropiada. Sea la cota de Saúl tan rica, y su armadura tan fuerte, pero ¿en qué mejoran a David, si no le acomoda? Pero la fe, la oración, la verdad y la justicia, toda la armadura de Dios, y el sentir que había en Cristo, son igualmente necesarios para todos los siervos del Señor, cualquiera sea la obra de ellos.</p>
<br/>
<p class="text-justify">Vv. 40-47.La seguridad y presunción de los necios los destruye. Nada puede superar la humildad, fe y piedad que hay en las palabras de David. Expresó su segura esperanza de éxito; se glorió en su pobre apariencia y en sus armas de que la victoria sería atribuida solo al Señor.</p>
<br/>
<p class="text-justify">Vv. 48-58.Véase lo frágil e incierta que es la vida, aunque el hombre se considere excelentemente fortificado; ¡cuán rápida y fácilmente y por qué pequeñas maneras, puede abrirse un pasaje para que salga la vida y entre la muerte! El fuerte no se gloríe en su fuerza ni el hombre armado en su armadura. Dios resiste al soberbio y desprecia a los que le desafían a Él y a su pueblo. Nadie que haya endurecido su corazón contra Dios ha prosperado. La historia quedó escrita para que todos se atrevan a entrar en acción en defensa de la honra de Dios, y en apoyo de su causa, con valiente e inconmovible confianza en Él. Hay un conflicto en que están comprometidos todos los seguidores del Cordero, y ¡deben estarlo!: un enemigo más formidable que Goliat, que se atreve a desafíar a los ejércitos de Israel; pero “resistid al diablo y de vosotros huirá”. Vé a la batalla con la fe de David, y las potestades de las tinieblas no te resistirán. ¡Pero con cuánta frecuencia el cristiano es entorpecido por un corazón malo e incrédulo!</p>
<br/>




</div>
