<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Samuel 25</h2>
<p class="text-justify">V. 1.Todo Israel lamentó a Samuel y tenían razón. Él oraba diariamente por ellos. Tienen corazones duros quienes pueden enterrar a los ministros fieles sin pena, los que no sienten como pérdida suya a quienes han orado por ellos, y les han enseñado el camino del Señor.</p>
<br/>
<p class="text-justify">Vv. 2-11.No hubiéramos sabido de Nabal si nada hubiera pasado entre él y David. Obsérvese su nombre, Nabal, “necio”, porque eso significa. Las riquezas hacen que los hombres se vean grandes ante los ojos del mundo, pero para quien ve correctamente, Nabal se veía muy bajo. No tenía honor ni honestidad; era vulgar, de mal temperamento e irritable; malo en sus hechos, duro y opresor; hombre que no le importaba qué fraude o violencia usaba para ganar y atesorar. ¡Qué poca razón tenemos para anhelar la riqueza de este mundo, cuando un vulgar como Nabal tiene abundancia, y hombres tan buenos como David sufren necesidad! -David puso como argumento los bondadosos servicios dispensados a los pastores de Nabal. Considerando que los hombres de David estaban en angustia y en deuda, inquietos y con escasez de provisiones, fue la buena administración de David lo que les impidió saquear. Nabal se dejó llevar por el apasionamiento, como tienden a hacerlo los hombres codiciosos, cuando se le pidió algo, pensando así cubrir un pecado con otro; y, maltratando al pobre, se excusan para no socorrerlos. Pero Dios no puede ser burlado. Que esto nos ayude a soportar los reproches y los malentendidos con paciencia y buen ánimo, y nos haga flexibles; con frecuencia ha sido la suerte de los excelentes de la tierra.
Nabal insiste mucho en la propiedad de las provisiones de su mesa. ¿No puede hacer con lo suyo como le plazca? Erramos si pensamos que somos señores absolutos de lo que tenemos y que podemos hacer lo que nos plazca con ello. No; no somos sino mayordomos, y debemos usarlo como se nos manda, recordando que no es nuestro sino de Aquel que nos lo encomendó.</p>
<br/>
<p class="text-justify">Vv. 12-17.Dios es bueno con el malo e ingrato, ¿por qué nosotros no podemos ser como Él? David decidió destruir a Nabal y todo lo que le pertenecía. ¿Es esta tu voz, oh David? ¿Había estado tanto tiempo en la escuela de la aflicción, donde debió aprender la paciencia y, sin embargo, sigue tan apasionado? En otros momentos, era sereno y considerado, pero se enardece tanto por unas pocas palabras duras, que procura destruir una familia entera. ¿Qué es de los mejores hombres, cuando Dios los deja librados a sí mismos, para que puedan saber lo que hay en sus corazones? ¡Qué necesario es orar, Señor, no nos metas en tentación!</p>
<br/>
<p class="text-justify">Vv. 18-31.Abigail expió con un regalo la negativa de Nabal al pedido de David. La conducta de ella fue muy sumisa. La sumisión pacifica grandes ofensas. Ella se pone en el lugar de un penitente, y de alguien que ruega. No podía excusar la conducta de su marido. Ella no depende de sus razonamientos, sino de la gracia de Dios para ablandar a David y espera que la gracia obre poderosamente. Le dice que estaba por debajo de él vengarse de un enemigo tan débil y despreciable como Nabal, que así como no le haría ningún bien, tampoco podía hacerle mal alguno.
Ella predice el final glorioso de los problemas presentes de David. Dios preservará tu vida; por tanto, no te conviene quitarle la vida a nadie, injusta e innecesariamente, en especial del pueblo de tu Dios y Salvador. Abigail guarda este argumento para el final por ser poderoso ante un hombre tan bueno; que mientras menos ceda a su pasión, más contribuirá a la paz y tranquilidad de su propia conciencia. Muchos han hecho en el ardor de su ira lo que desearán mil veces deshacer. La dulzura de la venganza pronto se vuelve amargura. Cuando somos tentados a pecar, debemos considerar cómo lo veremos cuando lo pensemos después.</p>
<br/>
<p class="text-justify">Vv. 32-39.David da gracias a Dios por enviarle esta feliz interferencia en un camino de pecado. Quien sea que nos salga al encuentro con un consejo, orientación, consuelo, advertencia o reproche oportuno, debemos ver que Dios lo envía. Debemos estar muy agradecidos por esas felices providencias que son medios para impedirnos pecar. La mayoría piensa bastante si tomarán el reproche con paciencia, pero pocos lo toman con gratitud y elogian a quienes lo dan y lo aceptan como un favor. Mientras más cerca estemos de cometer pecado, mayor es la misericordia de una llamada oportuna de atención. Los pecadores suelen estar muy seguros cuando más peligran.
Estaba muy ebrio. Señal de que era Nabal, un necio, que no podía disfrutar de algo sin abusar de ello; que no podía ser afable con sus amigos sin convertirse en bestia. No hay señal más segura de que un hombre tiene poca sabiduría ni forma más segura de destruir lo poco que tenga, que beber en exceso. A la mañana siguiente, ¡cómo ha cambiado! Su corazón que anoche estaba alegre con el vino, a la mañana siguiente estaba pesado como piedra; tan engañosos son los placeres carnales, que pronto pasa la risa del necio; el final de ese alborozo es angustia. Los ebrios se entristecen cuando reflexionan en su propia necedad.
Unos diez días después el Señor atacó a Nabal para que muriera. David bendijo a Dios por haberle impedido matar a Nabal. La tristeza del mundo, el orgullo avergonzado y la conciencia aterrada pone fin al gozo del lujurioso y apartan al codicioso de su riqueza; pero, cualquiera sea el arma, el Señor golpea a los hombres con la muertes cuando le place.</p>
<br/>
<p class="text-justify">Vv. 39-44.Abigail creía que David sería rey de Israel y apreciaba mucho su carácter piadoso y excelente. Consideró honorable su propuesta de matrimonio y ventajosa para ella, a pesar de sus dificultades actuales. Con gran humildad e indudablemente de acuerdo con las costumbres de la época, ella consintió, dispuesta a compartir sus tribulaciones. De esta manera, quienes se unen a Cristo deben estar dispuestos a sufrir con Él creyendo que después reinarán con Él.</p>
<br/>




</div>
