<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Tesalonicenses 5</h2>
<p class="text-justify">Vv. 1-5.Innecesario e inútil es preguntar la fecha específica de la venida de Cristo. No lo reveló a los apóstoles. Hay tiempos y sazones para que nosotros trabajemos, y es nuestro deber y preocupación conocerlos y observarlos, pero en cuanto al tiempo en que debamos rendir cuentas, no lo sabemos ni es necesario que lo sepamos.
La venida de Cristo será una gran sorpresa para los hombres. Nuestro mismo Señor lo dijo así. Como la hora de la muerte de cada persona, así será el juicio para la humanidad en general, así que el mismo comentario responde para ambas. La venida de Cristo será terrible para los impíos. Su destrucción les sobrevendrá mientras sueñan con la felicidad y se complacen con vanas entretenciones. No habrá medio para eludir el terror del castigo de ese día.
Ese día será de dicha para el justo. Ellos no están en tinieblas; son hijos de la luz. Esta es la feliz condición de todos los cristianos verdaderos. ¡Pero cuántos dicen paz y seguridad, mientras sobre sus cabezas pende la destrucción eterna! Despertémonos a nosotros mismos y unos a otros y cuidémonos de nuestros enemigos espirituales.</p>
<br/>
<p class="text-justify">Vv. 6-11.La mayor parte de la humanidad no considera las cosas del otro mundo porque están dormidos; o no las consideran porque duermen y sueñan. Nuestra moderación en cuanto a todas las cosas terrenales debiera ser conocida de todos los hombres. Los cristianos que tienen la luz del evangelio bendito brillando en sus rostros, ¿pueden despreocuparse de sus almas y ser indolentes con el otro mundo? Necesitamos la armadura espiritual o las tres gracias cristianas: fe, amor y esperanza. Fe si creemos que el ojo de Dios siempre está sobre nosotros, que hay otro mundo para el cual prepararse, vemos razón de estar alertas y ser sobrios. El amor verdadero y fervoroso a Dios y a las cosas de Dios, nos mantendrá alertas y sobrios. Si tenemos esperanza de salvación, cuidémonos de toda cosa que haga vacilar nuestra confianza en el Señor. Tenemos la base sobre la cual construir una esperanza inconmovible cuando consideramos que la salvación es por nuestro Señor Jesucristo que murió por nosotros para expiar nuestros pecados y para rescatar nuestras almas. Debemos unirnos en oración y alabanza unos con otros. Debemos darnos buen ejemplo unos a otros y este es el mejor medio para responder a la finalidad de la sociedad. Así aprenderemos a vivir para Aquel con quien esperamos vivir para siempre.</p>
<br/>
<p class="text-justify">Vv. 12-15.Los ministros del evangelio están descritos por la obra de su oficio que es servir y honrar al Señor. Deber de ellos no sólo es dar buen consejo, sino también advertir al rebaño los peligros y reprobar lo que estuviera mal. La gente debe honrar y amar a sus ministros porque su actividad es el bienestar de las almas de los hombres.
La gente debe estar en paz consigo misma haciendo todo lo que pueda para guardarse contra toda diferencia, aunque el amor a la paz no debe permitir que hagamos la vista gorda ante el pecado. Los espíritus temerosos y pesarosos deben ser animados, y una palabra amable puede hacer mucho bien. Debemos tolerar y soportar. Debemos ser pacientes y controlar el enojo, y esto con todos los hombres. Sean cuales sean las cosas que nos hagan los hombres, nosotros tenemos que hacer el bien al prójimo.</p>
<br/>
<p class="text-justify">Vv. 16-22.Tenemos que regocijarnos en las bendiciones de la criatura, como si no nos regocijáramos, sin esperar vivir muchos años y gozándonos durante todos ellos, pero si nos regocijamos en Dios podemos hacerlo para siempre jamás. Una vida verdaderamente religiosa es una vida de gozo constante. Podemos regocijarnos más si oramos más. La oración ayudará a llevar adelante todo asunto lícito y toda buena obra. Si oramos sin cesar no nos faltará tema para dar gracias en todo. Veremos razones para dar gracias por perdonar y prevenir, por las misericordias comunes y las excepcionales, las pasadas y las presentes, las espirituales y las temporales. No sólo por las cosas prósperas y agradables, sino también por las providencias aflictivas, por los castigos y las correcciones, porque Dios designa todo para nuestro bien, aunque, en la actualidad, no veamos en qué nos ayuda.
No apaguéis al Espíritu. Se dice que los cristianos son bautizados con el Espíritu Santo y con fuego. Él obró como fuego, iluminando, avivando y purificando las almas de los hombres. Como el fuego se apaga quitándole el combustible, y se sofoca echándole agua, o poniéndole mucha tierra encima, así debemos tener cuidado de no apagar al Espíritu Santo consintiendo los afectos y concupiscencias carnales, preocupándonos sólo de las cosas terrenales. Los creyentes suelen impedir su crecimiento en la gracia al no darse a los afectos espirituales producidos en sus corazones por el Espíritu Santo.
Por profecía entiéndase aquí la predicación de la palabra, la interpretación y la aplicación de las Escrituras. No debemos despreciar la predicación aunque sea simple, y no nos diga más de lo que sabíamos antes. Debemos escudriñar las Escrituras. Si probamos todas las cosas, debemos retener lo que es bueno. Debemos abstenernos de pecar, y de todo lo que tenga apariencia de pecado, que conduzca o se aproxime al pecado. El que no se refrena de las apariencias del pecado, el que no elimina las ocasiones de pecar, y no evita las tentaciones ni el acercamiento al pecado, no se mantendrá por mucho tiempo sin pecar.</p>
<br/>
<p class="text-justify">Vv. 23-28.El apóstol ora que ellos puedan ser santificados con más perfección, porque los mejores están santificados, pero en parte mientras estén en este mundo; por tanto, debemos orar por la santidad completa mientras seguimos adelante hacia ella. Y como vamos a caer si Dios no sigue haciendo su buena obra en el alma, debemos orar a Dios que perfeccione su obra hasta que seamos presentados sin falta ante el trono de su gloria.
Debemos orar unos por otros, y los hermanos deben expresar así su amor fraternal.
Esta epístola iba a ser leída a todos los hermanos. No sólo se permite a la gente corriente que lea las Escrituras, pero es su deber y se les debe exhortar a que lo hagan. La palabra de Dios no debe mantenerse en idioma desconocido, sino traducirse, puesto que a todos los hombres corresponde conocer las Escrituras, y para que todos los hombres puedan leerlas. Las Escrituras deben ser leídas en todas las congregaciones públicas, especialmente, para el beneficio de los indoctos.
No necesitamos más que conocer la gracia de nuestro Señor Jesucristo para hacernos dichosos. Él es una fuente de gracia que siempre fluye y rebasa para suplir todas nuestras carencias.</p>
<br/>




</div>
