<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Timoteo 6</h2>
<p class="text-justify">Vv. 1-5.Los cristianos no tenían que suponer que el conocimiento religioso o los privilegios cristianos les daban derecho a despreciar a los amos paganos o a desobedecer las órdenes lícitas o a exponer sus faltas a los demás. Los que disfrutaban el privilegio de vivir con amos creyentes, no debían dejar el respeto y la reverencia debidos porque fuesen iguales en los privilegios religiosos; más bien debían servir con doble diligencia y alegría por su fe en Cristo y como participes de su salvación gratuita.
No tenemos que reconocer como íntegras otras palabras sino las de nuestro Señor Jesucristo; a estas debemos dar consentimiento sincero. Habitualmente los que menos saben son los más orgullosos, porque no se conocen a sí mismos. De ahí vienen la envidia, la discordia, los improperios, las malas sospechas, las disputas sobre sutilezas y cosas nada claras, entre los hombres de mentes carnales corruptas, ignorantes de la verdad y de su poder santificador, y que procuran una ventaja mundana.</p>
<br/>
<p class="text-justify">Vv. 6-10.Aquellos que hacen del cristianismo un comercio para servir sus intereses en este mundo, se desengañarán pero los que lo consideran como su vocación, hallarán que tiene la promesa de la vida presente, y de la venidera. El piadoso ciertamente será feliz en el otro mundo; y tiene suficiente si está contento con su condición en este mundo; toda la gente verdaderamente piadosa está contenta. Cuando estemos en los apremios más grandes, no podemos estar más pobres que cuando vinimos a este mundo; un sudario, un ataúd, y una tumba, es todo lo que puede tener el hombre más rico del mundo con toda su riqueza. Si la naturaleza se contenta con poco, la gracia debe contentarse con menos. Las cosas necesarias de la vida limitan los deseos del cristiano verdadero, y con ellas debe contentarse.
Aquí vemos el mal de la codicia. No se dice que son ricos, sino los que quieren enriquecerse, los que depositan su felicidad en la riqueza y están ansiosos y decididos a obtenerla. Los que son así dan a Satanás la oportunidad para tentarlos, guiándolos a usar medios deshonestos y malas costumbres para aumentar sus ganancias. Además, los guía a tantas ocupaciones y a tal prisa de los negocios que no dejan tiempo ni inclinación para la religión espiritual; los guía a conexiones que los llevan al pecado y la necedad. ¡A qué pecados son llevados los hombres por amor al dinero! La gente puede tener dinero y no amarlo, pero si lo aman esto los empujará a todo mal. Toda clase de iniquidad y vicio, de una u otra forma, nacen del amor al dinero. No podemos mirar alrededor sin notar muchas pruebas de esto, especialmente en una época de prosperidad material, grandes gastos y profesión relajada.</p>
<br/>
<p class="text-justify">Vv. 11-16.No conviene a los hombres, en especial a los hombres de Dios, poner el corazón en las cosas de este mundo; los hombres de Dios deben sentirse transportados con las cosas de Dios. Debe tener un conflicto con la corrupción, con las tentaciones y con las potestades de las tinieblas. La vida eterna es la corona propuesta para estimularnos. Somos llamados a aferrarnos a eso.
Debe señalarse especialmente al rico cuáles son los peligros y deberes relacionados con el uso apropiado de la riqueza, pero ¿quién puede tener esta clase de encargo sin estar, él mismo, por encima del amor a las cosas que puede comprar la riqueza? -La manifestación de Cristo es segura pero no nos corresponde saber la fecha. Los ojos mortales no toleran el resplandor de la gloria divina. Nadie puede acercarse a Él a menos que se dé a conocer a los pecadores en Cristo y por medio de Cristo. La Deidad es adorada aquí sin distinción de Personas, porque todas las cosas se dicen apropiadamente del Padre, del Hijo o del Espíritu Santo. Dios nos es revelado sólo en la naturaleza humana de Cristo y a través de ella, como el Unigénito Hijo del Padre.</p>
<br/>
<p class="text-justify">Vv. 17-21.Ser rico en este mundo es totalmente diferente de ser rico para con Dios. Nada es más incierto que la riqueza mundanal. Los ricos deben entender que Dios les da sus riquezas y que Él puede darlas sólo para disfrutarlas ricamente; porque muchos tienen riquezas pero las disfrutan malamente, por no tener corazón para usarlas. ¿Cuál es el mejor valor de la fortuna aparte de dar la oportunidad de hacer el bien mayor? Mostrando fe en Cristo por los frutos del amor, echemos mano de la vida eterna, cuando el descuidado, el codicioso y el impío alzan sus ojos en los tormentos. El conocimiento que se opone a la verdad del evangelio no es ciencia verdadera ni conocimiento real, o de serlo, aprobaría el evangelio y le daría su asentimiento. Los que ponen la razón por encima de la fe, corren el peligro de dejar la fe. La gracia incluye todo lo que es bueno, y la gracia es una primicia, un comienzo de la gloria; dondequiera que Dios dé gracia, dará gloria.</p>
<br/>




</div>
