<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">1 Timoteo 2</h2>
<p class="text-justify">Vv. 1-7.Los discípulos de Cristo deben ser gente que ora; todos, sin distinguir nación, secta, rango o partido. Nuestro deber de cristianos está resumido en dos palabras: piedad, esto es, la adoración justa de Dios; y honestidad, esto es, buena conducta para con todos los hombres. Estas deben ir unidas; no somos verdaderamente honestos si no somos piadosos y no rendimos a Dios lo que le es debido; no somos verdaderamente piadosos si no somos honestos. Debemos abundar en lo que es aceptable ante los ojos de Dios nuestro Salvador.
Hay un solo Mediador y ese Mediador se dio como rescate por todos. Esta designación fue hecha para beneficio de los judíos y los gentiles de toda nación; para que todos los que lo quieran puedan ir por este camino al trono de la misericordia del Dios que perdona, a buscar reconciliación con Él.
El pecado había puesto enemistad entre Dios y nosotros; Jesucristo es el Mediador que hace la paz. Él es el rescate que iba a ser conocido en el tiempo establecido. En la época del Antiguo Testamento se habló de sus sufrimientos y de la gloria que seguiría, como de cosas que serían reveladas en los últimos tiempos. Los que son salvados deben llegar al conocimiento de la verdad, porque ese es el camino designado por Dios para salvar pecadores: si no conocemos la verdad no podemos ser gobernados por ella.</p>
<br/>
<p class="text-justify">Vv. 8-15.En los tiempos del evangelio la oración no debe limitarse a una casa de oración en particular, pero los hombres deben orar en todas partes.
Debemos orar en nuestros cuartos, orar en nuestras familias, orar cuando comemos, orar cuando viajamos, y orar en las asambleas solemnes, sean públicas o privadas. Debemos orar con amor; sin ira ni contienda, sin enojo con nadie. Debemos orar con fe, sin dudar y sin debatir.
Las mujeres que profesan la religión cristiana deben ser modestas para vestirse, sin demostrar un estilo inadecuadamente elegante u ostentoso o de alto costo. Las buenas obras son el mejor adorno, porque según el criterio de Dios, son de elevado precio. La modestia y la limpieza deben tomarse más en cuenta que la elegancia y la moda en cuanto a la ropa. Sería bueno que las que profesan una piedad seria estén totalmente libres de vanidad para vestirse. Deben gastar más tiempo y dinero en socorrer al pobre y al angustiado que en adornarse ellas mismas y sus hijos. Hacer esto en una forma inadecuada para su rango en la vida, y su profesión de piedad, es pecaminoso. Estas no son fruslerías, sino mandatos divinos. Los mejores adornos para quienes profesan la piedad son las buenas obras.
Según San Pablo no se permite que las mujeres enseñen públicamente en la iglesia, porque enseñar es un oficio de autoridad. Pero las buenas mujeres pueden y deben enseñar los principios de la religión verdadera a sus hijos en casa. Además, las mujeres no deben pensar que están excusadas de aprender lo necesario para la salvación, aunque no deben usurpar la autoridad. Como la mujer fue última en la creación, que es una razón para su sumisión, también fue primera en la transgresión. Pero aquí hay una palabra de consuelo; que las que permanezcan en modestia serán salvas al tener hijos, o con tener hijos, por el Mesías que nació de una mujer. La tristeza especial a que está sometido el sexo femenino, debe hacer que los hombres ejerzan su autoridad con mucha gentileza, ternura y afecto.</p>
<br/>




</div>
