<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Corintios 9</h2>
<p class="text-justify">Vv. 1-5.Cuando queremos que los demás hagan el bien, debemos actuar prudente y tiernamente con ellos, y darles tiempo. Los cristianos deben considerar lo que es para el pretigio de la fe que profesan, y deben esforzarse por adornar en todas las cosas la doctrina de Dios, su Salvador. El deber de ministrar a los santos es tan claro que puede parecer que no es necesario exhortar a los cristianos al respecto; sin embargo, el amor propio contiende con tanto poder contra el amor de Cristo, que suele ser necesario estimular sus mentes por medio del recuerdo.</p>
<br/>
<p class="text-justify">Vv. 6-15.El dinero donado con caridad puede parecer tirado a la basura para la mente carnal, pero cuando se da sobre la base de los principios apropiados, es semilla sembrada de la cual puede esperarse un valioso incremento. Hay que dar con cuidado. Las obras de caridad, como todas las demás buenas obras, deben hacerse de manera reflexiva e intencionada. La debida reflexión sobre nuestras circunstancias, y la de aquellos a quienes vamos a socorrer, orientará nuestras dádivas al servicio de la caridad. La ayuda debe darse con generosidad, sea más o menos, no con renuencia, sino con alegría. Mientras algunos desparraman y aun así crecen, otros retienen más de lo que se ve y eso lleva a la pobreza. Si tuviésemos más fe y amor desperdiciaríamos menos en nosotros mismos, y sembraríamos más con la esperanza de un crecimiento abundante. -¿Puede un hombre perder haciendo aquello con que Dios se agrada? Él puede hacer que toda la gracia abunde para con nosotros, y que abunde en nosotros; puede dar un gran crecimiento de las buenas cosas espirituales y de las temporales. Puede hacer que tengamos suficiente en todas las cosas y que nos contentemos con lo que tenemos. Dios no sólo nos da bastante para nosotros mismos, sino además para que podamos suplir con ello las necesidades del prójimo, y esto debe ser como semilla para sembrar. Debemos mostrar la realidad de nuestra sujeción al evangelio por las obras de caridad. Esto será para mérito de nuestra confesión y para la alabanza y la gloria de Dios. Propongámonos imitar el ejemplo de Cristo, sin cansarnos de hacer el bien, y considerando que es más bienaventurado dar que recibir.
Bendito sea Dios por el don inefable de su gracia, por la cual capacita e inclina a algunos de su pueblo a dar a los demás, y a otros a estar agradecidos por ello; y bendito sea para toda la eternidad su glorioso nombre por Jesucristo, el don de valor inapreciable de su amor, por medio del cual estas y todas las otras cosas, que pertenecen a la vida y la piedad, nos son dadas gratuitamente, más allá de toda expresión, medida o límite.</p>
<br/>




</div>
