<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Juan 1</h2>
<p class="text-justify">Vv. 1-3.La religión vuelve los cumplidos en verdaderas expresiones de respeto y amor. Un discípulo anciano es honorable; un apóstol y líder anciano de los discípulos lo es más. La carta es para una noble señora cristiana y sus hijos; bueno es que el evangelio se halle entre ellos: algunas personas nobles reciben el llamado. Las familias tienen que ser animadas y dirigidas en su amor y deberes hogareños. Los que aman la verdad y la piedad en sí mismos, deben amarla en el prójimo; los cristianos amaban a esta señora, no por su rango, sino por su santidad. Donde esté de verdad la religión, se quedará para siempre.
De las Personas divinas de la deidad el apóstol les desea la gracia, el favor divino y la buena voluntad, la fuente de todas las cosas buenas. Indudablemente es gracia que la bendición espiritual sea dada a los mortales pecadores. La misericordia y el libre perdón, porque los que ya son ricos en gracia, necesitan perdón continuo. Paz, tranquilidad de espíritu, y conciencia limpia, en la reconciliación asegurada con Dios, junto con toda prosperidad externa que es realmente para siempre: estas son deseadas en verdad y amor.</p>
<br/>
<p class="text-justify">Vv 12, 13.El apóstol refiere muchas cosas a una reunión personal. Pluma y tinta eran medios de fortalecer y consolar al prójimo, pero verse es mejor. La comunión de los santos debe ser mantenida por todos los métodos y debe llevar al gozo mutuo. En la comunión con ellos encontramos mucho de nuestro gozo presente y esperamos la felicidad para siempre.</p>
<br/>
<p class="text-justify">Vv. 4-6.Bueno es haber sido enseñado tempranamente en la religión; los niños pueden ser amados por amor de sus padres. Dio gran gozo al apóstol ver a los niños andando en las huellas de sus padres, y probablemente, a su vez, apoyando al evangelio. Que Dios bendiga más y más a esas familias, y levante a muchos que imiten su ejemplo. ¡Qué agradable es el contraste con los muchos que infunden la irreligiosidad, la infidelidad y el vicio en sus hijos! Nuestro camino es verdadero, nuestra conducta es buena, cuando están de acuerdo con la palabra de Dios. Podría decirse que este mandamiento de amor cristiano mutuo es un mandamiento nuevo porque fue declarado por el Señor Cristo, pero, en cuanto a su tema, es antiguo. Este es el amor a nuestras almas, que obedezcamos los mandamientos divinos. La visión anticipada de la declinación de este amor, y de otras apostasías o desvíos, puede ser la explicación de esta exhortación del apóstol al deber y la obediencia a este mandamiento con frecuencia y fervor.</p>
<br/>
<p class="text-justify">Vv. 7-11.Se describen el engañador y su engaño: él trae error acerca de la persona y oficio del Señor Jesús. Tal es un engañador y un anticristo; engaña a las almas y sabotea la gloria y el reino del Señor Cristo. No pensemos que es raro que ahora haya engañadores y opositores del nombre y la dignidad del Señor Cristo, porque los hubo en los tiempos de los apóstoles.
Mientras más abunden los engañadores y los engaños, más alertas deben estar los discípulos. Triste es que los espléndidos logros en la escuela de Cristo se pierdan para siempre. La manera de ganar la recompensa plena es permanecer veraz a Cristo y constante en la religión hasta el final. El aferrarse firme a la verdad cristiana nos une a Cristo, y por Él, también al Padre, porque ellos son uno. Descartemos igualmente a los que no permanecen en la doctrina de Cristo y los que transgreden sus mandamientos. Cualquiera que no profesa ni predica la doctrina de Cristo, respetándole como Hijo de Dios, y la salvación de la culpa y del pecado por medio de Él, no deben ser notados ni tomados en cuenta. Pero en obediencia a este mandamiento debemos demostrar bondad y buen espíritu a los que difieren de nosotros en asuntos menores, pero sostienen firmemente todas las doctrinas importantes de la persona de Cristo y de la santa salvación.</p>
<br/>




</div>
