<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Pedro 3</h2>
<p class="text-justify">Vv. 1-4.Las mentes purificadas tienen que ser estimuladas para que los creyentes se mantengan activos y vivos en la obra de la santidad. Habrá burladores en los postreros tiempos, bajo el evangelio, hombres que toman a la ligera el pecado y se burlan de la salvación por Jesucristo. Un artículo muy importante de nuestra fe se refiere a lo que sólo tiene una promesa para descansar en ella, pero los burladores la atacarán hasta que nuestro Señor venga. Ellos no creen que Él vendrá. Porque no ven cambios, no tienen temor de Dios, Salmo lv, 19. Imaginan que lo que Él nunca ha hecho, no puede ser hecho o nunca lo hará.</p>
<br/>
<p class="text-justify">Vv. 5-10. Si estos burladores hubieran considerado la espantosa venganza con que Dios borró a todo un mundo de impíos, de una sola vez, seguramente no se burlarían de su amenaza de un juicio igualmente terrible. Se declara por la misma palabra que los cielos y la tierra que ahora son serán destruidos por el fuego. Esto ocurrirá con tanta certeza como la verdad y el poder de Dios pueden hacerlo.
Aquí se enseña y afirma a los cristianos en la verdad de la venida del Señor. Aunque, según cuentan los hombres, hay una gran diferencia entre un día y mil años, según la cuenta de Dios no hay diferencia. Todas las cosas, pasadas, presentes y futuras, están siempre delante de Él; la tardanza de mil años no puede ser tanto para Él como para nosotros es postergar algo por un día o por una hora. Si los hombres no tienen conocimiento ni fe en el Dios eterno, se inclinan a pensar que Él es como ellos. ¡Qué difícil es formarse la idea de la eternidad! Lo que los hombres cuentan como tardanza, es paciencia, y es a favor de nosotros; es para dar más tiempo a su pueblo para que avance en conocimiento y piedad, y en el ejercicio de la fe y la paciencia, para que abunde en buenas obras, haciendo y sufriendo aquello para lo que son llamados, para que puedan dar gloria a Dios. Por tanto, pongan en sus corazones que ciertamente serán llamados a dar cuenta de todas las cosas hechas en el cuerpo, sean buenas o malas. Que el andar humilde y diligente ante Dios y el juicio frecuente de vosotros mismos muestren vuestra firme fe en el juicio futuro, aunque muchos vivan como si absolutamente nunca tuvieran que rendir cuentas. El día llegará cuando los hombres estén seguros y no tengan la esperanza del día del Señor. Los majestuosos palacios y todas las cosas deseables que buscan los hombres mundanos, y en las cuales ponen su felicidad, serán quemadas; todas las clases de criaturas que Dios ha hecho y todas las obras de los hombres deben pasar por el fuego, que será fuego consumidor para todo lo que el pecado haya traído al mundo, aunque será fuego purificador para las obras de la mano de Dios. ¿Qué será de nosotros si ponemos nuestros afectos en esta tierra y la hacemos nuestra porción, aunque vemos que todas estas cosas serán quemadas? Por tanto, ¡asegurémonos de la felicidad más allá de este mundo visible!</p>
<br/>
<p class="text-justify">Vv. 11-18.Sobre la base de la doctrina de la segunda venida de Cristo se nos exhorta a la pureza y la piedad. Este es el efecto del verdadero conocimiento. Se requiere una santidad muy exacta y universal, que no se apoye en ninguna baja medida o grado. Los cristianos verdaderos esperan cielos nuevos y una nueva tierra; libres de la vanidad a la que están sujetas las cosas presentes, y del pecado con que están contaminadas. Sólo los vestidos con la justicia de Cristo, y santificados por el Espíritu Santo, serán admitidos para habitar en este santo lugar. No esperes ser hallado en paz en el día de Dios, si eres perezoso y estás ocioso en este tu día, en el cual debemos terminar la obra que se nos ha encomendado hacer. Sólo el creyente diligente será cristiano feliz en el día del Señor. Nuestro Señor vendrá súbitamente, o dentro de muy poco nos llamará a su presencia; ¿y nos va a hallar ociosos? -Aprendamos a usar correctamente la paciencia de nuestro Señor que todavía tarda su venida. Hombres soberbios, carnales y corruptos tratan de eliminar algunas cosas en una aparente concordancia con sus impías doctrinas. Pero hay razón por la cual las epístolas de San Pablo o alguna otra parte de las Escrituras deban ser dejadas de lado; porque los hombres, dejados a su propio criterio, pervierten toda dádiva de Dios. Entonces, procuremos tener preparadas nuestra mente para recibir cosas difíciles de entender, pongamos en práctica las cosas que son más fáciles de entender. Pero debe haber negación de sí, sospecha de nosotros mismos y sumisión a la autoridad de Cristo Jesús antes que podamos recibir de todo corazón todas las verdades del evangelio, por tanto, estamos en gran peligro de rechazar la verdad. El creyente debe desconocer y aborrecer todas las opiniones y los pensamientos de hombres que no concuerden con la ley de Dios, ni sean garantizados por ella.
Los que son descarriados por el error, caen de su propia constancia. Para evitar ser descarriados, debemos tratar de crecer en toda gracia, en fe, en virtud y en conocimento. Esforzaos por conocer más clara y plenamente a Cristo; conocerle para ser más como Él y amarle más. Este es el conocimiento de Cristo tras el cual iba el apóstol Pablo, deseando obtenerlo; y los que saborean este efecto del conocimiento del Señor y Salvador Jesucristo, darán gracias, luego de recibir tal gracia, y le alabarán y se unirán para darle la gloria ahora, con la plena seguridad de hacer lo mismo en el más allá, para siempre.</p>
<br/>




</div>
