<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Pedro 2</h2>
<p class="text-justify">Vv. 1-9.Aunque el camino del error es un camino dañino, muchos son los que siempre están listos para andar por él. Cuidémonos de no dar ocasión al enemigo para que blasfeme el santo nombre por el cual somos llamados o que hablen mal del camino de la salvación por Jesucristo, que es el Camino, la Verdad y la Vida.
Estos seductores usan palabras fingidas, y engañan los corazones de sus seguidores. Los tales ya están condenados y la ira de Dios está sobre ellos. El método habitual de Dios para proceder se muestra con ejemplos. Los ángeles fueron derribados de toda su gloria y dignidad, por su desobediencia. Si las criaturas pecan, aun en el cielo, deben sufrir en el infierno. El pecado es la obra de las tinieblas, y las tinieblas es la paga del pecado.
Nótese cómo trató Dios al mundo antiguo. El número de ofensores no procura más favor que su calidad. Si el pecado es universal, el castigo se extenderá por igual a todos.
Si en un terreno fértil la gente abunda en pecado, Dios puede volver de inmediato una tierra fértil en estéril, y un país bien regado en cenizas. No hay planes ni políticos que puedan impedir los juicios para un pueblo pecador. El que evita que el agua y el fuego dañen a su pueblo, Isaías xliii, 2, puede destruir también a sus enemigos; ellos nunca están a salvo.
Cuando envía destrucción al impío, Dios manda liberación para el justo. En malas compañías no podemos obtener sino culpa o tristeza. Que los pecados de los demás sean tribulación para nosotros. Pero es posible que los hijos del Señor vivan entre los más profanos, pero retengan su integridad; hay más poder en la gracia de Cristo y su morada en ellos que en las tentaciones de Satanás, o que en el ejemplo del malo, con todos sus terrores o seducciones. En nuestras intenciones e inclinaciones a cometer pecado podemos encontrarnos con raros impedimentos, si los notamos. Cuando pretendemos hacer el mal, Dios envía muchas estorbos para detenernos, como diciendo: Cuidado con lo que hacéis.
Su sabiduría y poder lograrán con toda seguridad los propósitos de su amor, y los compromisos de su verdad; aunque los impíos suelen escapar del sufrimiento aquí, es porque son conservados para el día del juicio, cuando serán castigados con el diablo y sus ángeles.</p>
<br/>
<p class="text-justify">Vv. 10-16.Los seductores impuros y sus seguidores incondicionales se entregan a sus propósitos carnales. Rehúsan llevar cautivo cada pensamiento a la obediencia a Cristo, actúan contra los preceptos justos de Dios. Andan en pos de la carne, van por rumbos pecaminosos y alcanzan los mayores grados de impureza y maldad. Además, desprecian a los que Dios ha puesto en autoridad sobre ellos, y a quienes requiere que honren.
Las cosas temporales externas y buenas son la paga que los pecadores esperan y se prometen a sí mismos. Nadie tiene más razón para temblar que los que son osados para entregarse a sus lujurias pecaminosas, por presumir de la gracia y la misericordia divina. Ha habido muchos y hay, que hablan a la ligera de las restricciones de la ley de Dios y no se consideran obligados a obedecerla. Que los cristianos se aparten de los tales.</p>
<br/>
<p class="text-justify">Vv. 17-22.La palabra de verdad es el agua de vida que refresca las almas que la reciben, pero los engañadores diseminan y promueven el error, y quedan vacíos porque no hay verdad en ellos. Como las nubes impiden el paso de la luz del sol, así estos oscurecen el consejo con palabras en que no hay verdad. Viendo que tales hombres aumentan las tinieblas en este mundo, es muy justo que la neblina de las tinieblas sea su porción en el venidero. En medio de su hablar de libertad, estos hombres son los esclavos más viles; sus propias lujurias ganan la victoria absoluta sobre ellos, y en realidad están esclavizados. Cuando los hombres están enredados, los vencen con facilidad; por tanto, los cristianos deben mantenerse cerca de la palabra de Dios y velar contra todos los que procuren confundirlos.
El estado de apostasía es peor que el estado de ignorancia. Dar un mal informe sobre el buen camino de Dios, y una falsa acusación contra el camino de la verdad debe exponer a la condenación más pesada. ¡Qué temible es el estado aquí descrito! Pero aunque tal caso sea deplorable, no está totalmente desprovisto de esperanza; el leproso puede ser limpiado y hasta el muerto puede ser resucitado. ¿Te causa pesar tu desvío? Cree en el Señor Jesús y serás salvo.</p>
<br/>




</div>
