<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Pedro 1</h2>
<p class="text-justify">Vv. 1-11.La fe une verdaderamente a Cristo con el creyente débil y con el fuerte y purifica realmente el corazón de uno y del otro; todo creyente sincero es justificado a ojos de Dios por su fe. La fe obra santidad y produce efectos en el alma que ninguna otra gracia puede producir. En Cristo habita toda la plenitud y el perdón, la paz, la gracia y el conocimiento, y los nuevos principios son así dados por medio del Espíritu Santo.
Las promesas para quienes son partícipes de la naturaleza divina nos harán inquirir si son realmente renovadas en el espíritu de nuestra mente; volvamos todas estas promesas en oraciones por la gracia transformadora y purificadora del Espíritu Santo. El creyente debe agregar conocimiento a su virtud, incrementar la familiaridad con toda la verdad y la voluntad de Dios. Debemos agregar templanza al conocimiento; moderación por las cosas mundanas; y a la templanza debemos agregar paciencia o alegre sometimiento a la voluntad de Dios. La tribulación produce paciencia por la cual soportamos todas las calamidades y las cruces en silencio y sumisión. A la paciencia debemos agregar piedad: esto incluye los santos afectos y disposiciones hallados en el verdadero adorador de Dios; con tierno afecto por todo sus semejantes cristianos que son hijos del mismo Padre, siervos del mismo Amo, miembros de la misma familia, viajeros al mismo país, herederos del mismo legado. Por lo tanto, los cristianos deben laborar para alcanzar la seguridad de su vocación y elección, creyendo y haciendo el bien; y esforzarse en ello cuidadosamente, es un argumento firme de la gracia y misericordia de Dios, que los sostiene para que no caigan completamente.
Los que son diligentes en la obra de la religión, tendrán una entrada triunfal en el reino eterno donde reina Cristo y ellos reinarán con Él para siempre jamás; y es en la práctica de toda buena obra donde debemos esperar entrar al cielo.</p>
<br/>
<p class="text-justify">Vv. 12-15.Debemos ser fundados en la creencia de la verdad, para que no seamos llevados por cualquier viento de doctrina; y especialmente, en la verdad que necesitamos saber en nuestro día lo que corresponde a nuestra paz, y que se opone a nuestro tiempo. El cuerpo no es sino un tabernáculo o tienda del alma. Es una vivienda vil y móvil. La cercanía de la muerte hace diligente al apóstol en el negocio de la vida. Nada puede dar tanta compostura en la perspectiva o en la hora de la muerte como saber que seguimos fiel y sencillamente al Señor Jesús, y buscamos su gloria. Los que temen al Señor, hablan de su paciencia. Este es el modo de diseminar el conocimiento del Señor, y por la palabra escrita ellos son capacitados para hacer esto.</p>
<br/>
<p class="text-justify">Vv. 16-21.El evangelio no es algo débil, pero llega con poder, Romanos 1, 16. La ley pone ante nosotros nuestro miserable estado por el pecado, pero nos deja ahí. Descubre nuestra enfermedad, pero no da a conocer la cura. Ver a Jesús crucificado es lo que sana el alma. Tratad de disuadir al mundano codicioso de su avaricia; unos gramos de oro pesan más que todas las razones. Ofreced quitar la ira con argumentos a un hombre furioso, que no tiene paciencia para oírlos. Tratad de detener al libertino, una sonrisa es más fuerte para él, que toda razón. Pero llegad con el evangelio y exhortadles con la preciosa sangre de Jesucristo, derramada para salvar sus almas del infierno, y para satisfacer sus pecados y esta es la súplica poderosa que hace confesar a los hombres buenos que sus corazones ardían por dentro, y a los malos, como Agripa, decir que casi fueron persuadidos a ser cristianos, Hechos xxvi, 28.
Dios se complace bien con Cristo y con nosotros en Él. Este es el Mesías que fue prometido, a través del cual todos los que creemos en Él seremos aceptados y salvados.
La verdad y la realidad del evangelio son también anunciadas por los profetas y escritores del Antiguo Testamento, que hablaron y escribieron bajo la influencia del Espíritu de Dios, y conforme a su dirección. ¡Qué firme y segura debe ser nuestra fe, que tiene una palabra tan firme y segura sobre la cual apoyarse! Cuando la luz de la Escritura el Espíritu Santo de Dios lanza como dardo a la mente ciega y al entendimiento entenebrecido, es como la aurora que irrumpe, avanza y se difunde por toda el alma hasta que el día es perfecto. Como la Escritura es la revelación de la mente y de la voluntad de Dios, todo hombre debe escudriñarla para entender su sentido y significado. El cristiano sabe que el libro es la palabra de Dios, en el cual saborea la dulzura, y siente el poder, y ve la gloria verdaderamente divina. Y las profecías ya cumplidas en la persona y salvación de Cristo, y en los grandes intereses de la iglesia y el mundo, forman una prueba incuestionable de la verdad del cristianismo. El Espíritu Santo inspiró a hombres santos para hablar y escribir. Él asistió así y los dirigió para entregar lo que ellos habían recibido de Él, para que ellos expresaran claramente lo que daban a conocer. Así que las Escrituras son para ser contadas como las palabras del Espíritu Santo y toda la claridad y simpleza, todo el poder y toda la propiedad de las palabras y expresiones, vienen de Dios. Mezcle la fe con lo que encuentre en las Escrituras, y estime y reverencie la Biblia como libro escrito por hombres santos enseñados por el Espíritu Santo.</p>
<br/>




</div>
