<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Reyes 2</h2>
<p class="text-justify">Vv. 1-8.El Señor hizo saber a Elías que su tiempo estaba cerca. Por tanto, fue a las diversas escuelas de los profetas para darles sus últimas exhortaciones y su bendición. La partida de Elías es un tipo y figura de la ascensión de Cristo, y la apertura del reino de los cielos a todos los creyentes.
Eliseo había seguido por mucho tiempo a Elías y no lo iba a abandonar ahora que esperaba la bendición de su partida. Los que siguen a Cristo no se queden cortos cansándose al final.
Las aguas del Jordán, antes, cedieron ante el arca; ahora, ante el manto del profeta, como señal de la presencia de Dios. Cuando Dios lleva al cielo a sus fieles, la muerte es el Jordán que deben cruzar, y encuentran un camino por donde pasar. La muerte de Cristo dividió las aguas para que pasen los redimidos del Señor. ¡Dónde está, oh, muerte, tu aguijón, el daño que puedes hacer, tu terror?</p>
<br/>
<p class="text-justify">Vv. 9-12.Esa plenitud de donde profetas y apóstoles obtuvieron su provisión, aún existe como antes, y se nos dice que pidamos grandes porciones de ella. La asistencia diligente a Elías, particularmente en sus últimas horas, sería el medio apropiado para que Eliseo obtuviese mucho de su espíritu. Las consolaciones de los santos que parten, y sus experiencias, ayudan a dar brillo a nuestro consuelo y a fortalecer nuestras resoluciones.
Elías es llevado al cielo en un carro de fuego. Se puede hacer muchas preguntas sobre esto, que no pueden ser contestadas. Baste con lo que se nos dice, lo que su Señor lo encontró haciendo cuando vino. Él estaba comprometido en un serio discurso, exhortando e instruyendo a Eliseo sobre el reino de Dios entre los hombres. Nos equivocamos si pensamos que la preparación para el cielo se realiza solamente por la contemplación y por actos de devoción.
El carro y los caballos parecían como de fuego, algo muy glorioso, no por arder sino por su fulgor. Por la manera en que Elías y Enoc fueron sacados de este mundo, Dios nos deja dar un vistazo a la vida eterna sacada a la luz por el evangelio, de la gloria reservada para los cuerpos de los santos, y de la apertura del reino del cielo a todos los creyentes. También fue una figura de la ascensión de Cristo.
Aunque Elías se fue de manera triunfal al cielo, este mundo mal se podía permitir dejarlo ir. Ciertamente están endurecidos los corazones de los que no se sienten llamados por Dios a llorar y hacer duelo cuando Él se lleva a los hombres fieles y útiles. Elías fue para Israel, por sus consejos, reproches y oraciones, mejor que la fuerza más poderosa de carro y caballo, y detuvo los juicios de Dios.
Cristo legó a sus discípulos su precioso evangelio, como el manto de Elías; la prenda del poder divino ejercido para derrumbar el imperio de Satanás, y establecer el reino de Dios en el mundo. El mismo evangelio permanece con nosotros aunque los poderes milagrosos hayan sido retirados, y tiene fuerza divina para la conversión y salvación de los pecadores.</p>
<br/>
<p class="text-justify">Vv. 13-18.Elías dejó su manto a Eliseo como señal del descenso del Espíritu sobre él; era más que si le hubiera dejado miles en oro y plata. Eliseo lo tomó, no como reliquia sagrada que se debe adorar, sino como ropaje significativo para usar. Ahora que Elías fue llevado al cielo, Eliseo pregunta: -1. Por Dios; cuando nuestra consolación de criaturas ha sido quitada, tenemos un Dios al cual acudir, que vive por siempre. -2. Por el Dios que Elías servía, honraba y al que suplicaba. El Señor Dios de los santos profetas es el mismo ayer, hoy y por los siglos, pero ¿de qué nos servirá tener los mantos de aquellos que partieron, sus lugares, sus libros, si no tenemos el espíritu de ellos, el Dios de ellos? -Vea aquí a Eliseo dividiendo el río; el pueblo de Dios no tiene que temer el paso final por el Jordán de la muerte como por tierra seca.
Los hijos de los profetas realizaron una búsqueda innecesaria de Elías. Los hombres sabios pueden ceder, en aras de la paz y la buena opinión de los demás, a aquellos contra lo cual su juicio se opone, en forma tan innecesaria como infructuosa. Atravesar colinas y valles nunca nos conducirá a Elías, pero sí lo hará, en su debido momento, seguir el ejemplo de su santa fe y su celo.</p>
<br/>
<p class="text-justify">Vv. 19-25. Obsérvese el milagro de sanar las aguas. Los profetas debieran mejorar para ellos todo lugar al cual llegan, proponiéndose endulzar los espíritus amargos y hacer fructíferas las almas estériles, por la palabra de Dios, que es como la sal echada al agua por Eliseo. Eso fue un emblema adecuado del efecto producido por la gracia de Dios en el corazón pecador del hombre. A veces hay familias, pueblos y ciudades enteros que tienen un nuevo aspecto por la predicación del evangelio; la maldad y el mal han sido cambiados por fruto de las obras de justicia, que son, por medio de Cristo, para alabanza y gloria de Dios.
He aquí una maldición sobre unos jóvenes de Betel, suficiente para destruirlos; no fue una maldición sin causa, pues ellos abusaron del carácter de Eliseo en cuanto profeta de Dios. Se burlaron incitándole a ‘subir’reflejando el arrebatamiento de Elías al cielo.
El profeta actuó por impulso divino. Si el Espíritu Santo no hubiera dirigido la solemne maldición de Eliseo, la providencia de Dios no la hubiera seguido con un juicio. El Señor debe ser glorificado como Dios justo que odia el pecado y lo castigará. Los jóvenes teman decir malas palabras, pues Dios nota lo que dicen. Que no se burlen de nadie por defectos de mente o cuerpo; es para su especial peligro el burlarse de cualquiera por hacer el bien. Los padres que deseen consuelo para sus hijos, que los eduquen bien y hagan todo lo que puedan para quitar la necedad que está ligada a sus corazones. ¡Cuál será la angustia de los padres que, en el día del juicio, presencien la condenación eterna de su progenie, ocasionada por su propio mal ejemplo, negligencia o mala crianza!</p>
<br/>




</div>
