<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Reyes 6</h2>
<p class="text-justify">Vv. 1-7.Hay algo placentero en la conversación de los siervos de Dios que hace que quienes escuchan olviden el dolor y el cansancio del trabajo. Hasta los hijos de los profetas deben estar dispuestos a trabajar. Que nadie piense que un empleo honesto es una carga o una desgracia. El trabajo intelectual es tan pesado y, muy a menudo, más duro que el trabajo manual.
Tenemos que tener cuidado con lo que es prestado, como si fuera propio, porque debemos hacer como queremos que nos hagan. Este hombre era respetuoso en cuanto al hacha. Para quienes tienen una mente honesta, la más penosa aflicción de la pobreza no es tanto su propia necesidad y desgracia como estar incapacitados para pagar las deudas justas. Pero el Señor cuida a su pueblo en sus pequeñas preocupaciones. La gracia de Dios puede levantar el corazón pesado como hierro que está hundido en el fango de este mundo, y elevar los afectos naturalmente terrenales.</p>
<br/>
<p class="text-justify">Vv. 8-12.El rey de Israel consideró las advertencias que le dio Eliseo como peligro de parte de los sirios, pero no oyó las advertencias del peligro de sus pecados. Tales advertencias son poco escuchadas por la mayoría; quieren salvarse de la muerte, pero no del infierno. Nada que se haga, diga o piense, de parte de alguien en algún lugar en algún momento está fuera del conocimiento de Dios.</p>
<br/>
<p class="text-justify">Vv. 13-23.Lo que Eliseo dijo a su siervo lo dice a todos los siervos fieles de Dios, cuando hay peleas por fuera y temores por dentro. No tenga miedo, con ese temor que tiene tormento y asombro; porque más son los que están con nosotros, para protegernos, que los que están ellos, para destruirnos. Los ojos de su cuerpo fueron abiertos y con ellos vio el peligro. Señor, abre los ojos de nuestra fe para ver con ellos tu mano. Mientras más clara sea la vista que tengamos de la soberanía y del poder del cielo, menos temeremos los problemas de la tierra. Satanás, el dios de este siglo, ciega los ojos de los hombres y los engaña para su propia ruina pero, cuando Dios ilumina sus ojos, ellos se ven en medio de sus enemigos, cautivos de Satanás y ante el peligro del infierno, aunque antes hayan pensado que su condición era buena.
Cuando Eliseo tuvo a su merced a los sirios, hizo evidente que él estaba bajo la influencia de la bondad divina como del poder divino. Que no seamos vencidos por el mal sino que venzamos con el bien el mal. Los sirios vieron que no tenía sentido tratar de atacar a un hombre tan grande y bueno.</p>
<br/>
<p class="text-justify">Vv. 24-33.Aprended a valorar la abundancia y agradecedla; ved cuán despreciable es el dinero cuando en tiempo de hambre se abandona con tanta facilidad, ¡por cualquier cosa que sea comestible! El lenguaje de Joram a la mujer puede ser el lenguaje de la desesperación. Véase cumplida la palabra de Dios; entre las amenazas de los juicios de Dios sobre Israel por sus pecados, este era uno, que ellos comerían la carne de sus propios hijos, Deuteronomio xxviii, 53-57. La verdad y la aterradora justicia de Dios fueron demostradas en esta horrible transacción. ¡He ahí, qué desgracias ha acarreado el pecado al mundo! Pero la necedad del hombre tuerce su camino y, entonces, su corazón se inquieta contra el Señor.
El rey jura matar a Eliseo. Los hombres malos culpan a cualquiera como causa de sus problemas más que a sí mismos y no dejan sus pecados. Si sirviera rasgarse las vestiduras sin tener el corazón contrito y quebrado, si sirviera vestir de saco sin ser renovado en el espíritu de su mente, ellos no se opondrían al Señor. Que toda la palabra de Dios aumente en nosotros el temor reverente y la esperanza santa, para que podamos ser firmes y constantes, creciendo en la obra del Señor siempre, sabiendo que nuestro trabajo en el Señor no es en vano.</p>
<br/>




</div>
