<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Samuel 23</h2>
<p class="text-justify">Vv. 1-7.Estas palabras de David son muy dignas de considerar. Cuando los que han tenido por mucho tiempo la experiencia de la bondad de Dios y el placer de la sabiduría celestial, llegan al final de su carrera, debieran dar su testimonio de la verdad de la promesa.
David admite su inspiración Divina, que el Espíritu de Dios habla por él. Él y otros santos, hablaron y escribieron movidos por el Espíritu Santo.
En muchas cosas tuvo que culpar su conducta y negligencia. Pero David se consuela con que el Señor hizo con él un pacto eterno. Entiende como tal principalmente el pacto de misericordia y paz, que el Señor hizo con él, un pecador que creyó en el Salvador prometido, abrazó las bendiciones prometidas, y se rindió al Señor para ser su siervo redimido. Los creyentes disfrutarán por siempre de las bendiciones del pacto; y Dios Padre, Hijo y Espíritu Santo será para siempre glorificados en la salvación de ellos. Así, el perdón, la justicia, la gracia y la vida eterna son recibidos como dádiva de Dios a través de Jesucristo. Hay una infinita plenitud de gracia, y todas las bendiciones atesorados en Cristo para quienes buscan su salvación.
Este pacto era toda la salvación de David; él conocía tan bien la santa ley de Dios y la magnitud de su propia pecaminosidad, que se dio cuenta que estaba necesitado en su propio caso de esta salvación. Por tanto, era todo su deseo. Comparativamente todos los objetos terrenales pierden su atractivo; estaba dispuesto a darlos todos, o a morir y dejarlos para disfrutar la felicidad plena, Salmo lxxiii, 24-28. Todavía el poder del mal y la debilidad de su fe, esperanza y amor eran su tristeza y su carga. Sin duda, habría reconocido que su propia negligencia y falta de cuidado eran la causa; pero la esperanza de que pronto sería hecho perfecto en gloria, lo alentó en sus momentos de muerte.</p>
<br/>
<p class="text-justify">Vv. 8-39.Una vez David deseó ardientemente el agua del pozo de Belén. Eso parece un instante de debilidad. Tenía sed; en su juventud se había refrescado con el agua de ese pozo a menudo, y la deseó sin pensarlo debidamente. ¿Eran sus valientes tan osados para exponerse, ante la menor señal del deseo de su príncipe, y estaban tan deseosos de complacerlo, y nosotros no desearemos ser aprobados por nuestro Señor Jesús cumpliendo prestamente Su voluntad, según su Palabra, su Espíritu y su providencia? David derramó el agua como libación para el Señor, así enfrentó su fantasía necia, se castigó por permitirla, y demostró tener pensamientos sobrios para corregir las decisiones precipitadas y mostró que sabía negarse a sí mismo. David consideró que el agua era tan preciosa por la manera en que arriesgaron su sangre los hombres que la consiguieron, y nosotros ¿no debiéramos valorar mucho más los beneficios adquiridos con el derramamiento de la sangre de nuestro bendito Salvador? Cuidémonos para no descuidar una salvación tan grandiosa.</p>
<br/>




</div>
