<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Samuel 21</h2>
<p class="text-justify">Vv. 1-9.Toda aflicción surge del pecado y debe llevarnos a arrepentirnos y a humillarnos delante de Dios; pero algunos problemas especialmente muestran que han sido enviados para traer a la memoria el pecado. Los juicios de Dios suelen mirar muy atrás, y eso es lo que requiere que hagamos cuanto antes sus reprensiones. No nos corresponde objetar el hecho de que la gente sufra por el pecado de su rey; quizá le ayudaron. Ni objetar el hecho de que esta generación sufra por el pecado de la anterior. Dios suele castigar los pecados de los padres en los hijos, y no rinde cuentas de nada a nadie. El paso del tiempo no borra la culpa del pecado, ni podemos acariciar la esperanza de escapar porque el juicio tarda. Si no podemos entender todas las razones de la Providencia al respecto, tampoco tenemos derecho a pedir que Dios nos rinda cuenta de sus razones. Debe ser bueno porque es la voluntad de Dios y, al final, resultará ser así.
El dinero no paga la sangre. Pareciera que la posteridad de Saúl anduvo en sus huellas, porque es llamada casa de sangre. Era el espíritu de la familia por lo cual con justicia se les reconoce por su pecado personal como por el de su familia. Los gabaonitas pidieron esto contra Saúl o su familia no por maldad. No era para satisfacer ninguna venganza, sino por el bien público. Fueron ejecutados al comienzo de la cosecha; así pues fueron sacrificados para apaciguar la ira del Dios Todopoderoso que había suspendido la misericordia de las cosechas durante los años anteriores, y para obtener su favor en la cosecha actual. En vano esperamos misericordia de Dios si no hacemos justicia contra nuestros pecados. Las ejecuciones no deben considerarse crueles cuando son por el bien público.</p>
<br/>
<p class="text-justify">Vv. 10-14.Que una tierra culpable disfrutara de muchos años de abundancia, requiere gratitud; no debe maravillarnos que se castigue con escasez la abundancia mal usada; pero cuán pocos están dispuestos a preguntar al Señor la causa pecaminosa, mientras muchos buscan las causas secundarias por medio de las cuales le ha placido obrar. Pero el Señor alega por la causa de los que no pueden o no quieren vengarse; y las oraciones del pobre son de gran poder.
Cuando Dios envió lluvia para regar la tierra, los cuerpos fueron enterrados, porque entonces quedó claro que la petición por la tierra Dios la había oído. Cuando se hace justicia en la tierra, cesa la venganza del cielo. Dios se pacifica, y es puesto a nuestro favor por medio de Cristo, que fue colgado en un madero, hecho maldición por nosotros, para quitar de en medio la culpa, aunque Él mismo era inocente.</p>
<br/>
<p class="text-justify">Vv. 15-22.Estos sucesos parecen haber ocurrido hacia el final del reinado de David. David flaqueaba, pero no huyó, y Dios envió ayuda en tiempo de necesidad. A veces hasta los santos más fuertes desfallecen en los conflictos espirituales; entonces, Satanás los ataca furiosamente, pero quienes defienden su terreno y le resisten, serán aliviados y serán más que vencedores. La muerte es el último enemigo del cristiano, e hijo de Anac; pero, por medio de Aquel que venció por nosotros, los creyentes, al final, serán más que vencedores, aun sobre ese enemigo.</p>
<br/>




</div>
