<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Samuel 24</h2>
<p class="text-justify">Vv. 1-9.Por el pecado del pueblo se dejó que David actuara mal y como retribución recibieron un castigo. Este ejemplo arroja luz sobre el gobierno de Dios sobre el mundo, y da una lección útil.
El orgullo en el corazón de David fue su pecado al hacer el censo del pueblo. Pensó que ésto lo haría parecer más formidable, y confió en el brazo de carne más de lo que debiera, y a pesar de haber escrito tanto sobre confiar solo en Dios. Él no juzga el pecado como nosotros. Lo que a nosotros nos parece inocuo o, al menos, poco ofensivo, puede ser un pecado grande a ojos de Dios, que discierne los pensamientos e intenciones del corazón. Hasta los impíos pueden discernir los malos temperamentos y la mala conducta de los creyentes, de los cuales están, a menudo, inconscientes. Pero Dios rara vez les permite los placeres que desean pecaminosamente aquellos a quienes Él ama.</p>
<br/>
<p class="text-justify">Vv. 10-15.Cuando un hombre peca es bueno que tenga un corazón interior que lo moleste por eso. Si confesamos nuestros pecados, podemos orar con fe que, por misericordia perdonadora, Dios nos perdonará y quitará ese pecado que nosotros desechamos con arrepentimiento sincero. Es justo de parte de Dios que nos quite lo que constituimos motivo de orgullo, o lo haga amargo para nosotros, y lo convierta en nuestro castigo. El castigo debe ser de tal índole puesto que el pueblo tuvo una buena parte en ello, porque aunque el pecado de David abrió la compuerta, los pecados del pueblo fueron todo un diluvio.
En esta dificultad David eligió por un juicio que viniera directamente de Dios, cuyas misericordias él conocía que eran muy grandes, y no del hombre, que habría triunfado en la miseria de Israel y se hubieran endurecido en su idolatría. Escogió la pestilencia; él y su familia estarían tan expuestos a ella como el israelita más pobre; y por un breve lapso seguiría sometido a la disciplina divina, no importa que fuera severa.
La rápida destrucción ocasionada por la pestilencia muestra con cuanta facilidad puede derribar Dios a los pecadores más orgullosos, y cuánto debemos diariamente a la paciencia divina.</p>
<br/>
<p class="text-justify">Vv. 16, 17.Quizá hubo más maldad, especialmente más orgullo, y ese era el pecado que ahora se castigaba en Jerusalén más que en otro lugar, por tanto la mano del destructor se extiende hacia esa ciudad; pero el Señor lo hizo arrepentirse del mal, cambiando no de propósito sino de método.
En el mismo lugar donde le impidió que Abraham sacrificara a su hijo, le impidió al ángel que destruyera Jerusalén, con una contraorden similar. Es por amor del gran sacrificio, que se preserva nuestra vida del ángel destructor. Y en David está el espíritu del verdadero pastor de su pueblo que se ofrece a sí mismo como sacrifico a Dios por la salvación de sus súbditos.</p>
<br/>
<p class="text-justify">Vv. 18-25.Cuando Dios nos exhorta a ofrecerle sacrificios espirituales es una evidencia de su reconciliación de nosotros consigo mismo. David compró el terreno para construir el altar. Dios odia que se robe para ofrecer holocausto. No saben lo que es la religión quienes principalmente se interesan en abaratarla y hacerla fácil para ellos, y se complacen más con lo que les cuesta menos dolores o dinero. ¿Para qué tenemos sustancia sino para honrar a Dios con ella, y cómo puede ser mejor dada? -Véase la edificación del altar y la ofrenda de los sacrificios apropiados en él: Los holocaustos para la gloria de la justicia de Dios, las ofrendas por la paz para la gloria de su misericordia. Cristo es nuestro Altar, nuestro Sacrificio; solo en Él podemos tener esperanza de escapar de su ira y hallar el favor de Dios. La muerte anda destruyendo todo alrededor en tantas formas, y tan repentinamente, que es locura no esperar el fin de la vida y prepararse para ello.</p>
<br/>




</div>
