<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Tesalonicenses 1</h2>
<p class="text-justify">Vv. 1-4.Donde esté la verdad de la gracia, habrá un incremento de ella. La senda del justo es como la luz de la aurora, que brilla y brilla más y más hasta el día perfecto. Y donde haya incremento de la gracia, Dios debe tener toda la gloria. Donde crece la fe, el amor abundará, porque la fe obra por amor. Se demuestra fe y paciencia, como las que puedan proponerse como pauta para el prójimo, cuando las pruebas de parte de Dios y las persecuciones de parte de los hombres, vivifican el ejercicio de esas gracias, porque la paciencia y la fe de la cual se gloriaba el apóstol, lo sostenían y lo capacitaban para soportar todas sus tribulaciones.</p>
<br/>
<p class="text-justify">Vv. 5-10.La religión, si vale algo, lo vale todo; los que no tienen religión, o nada digno de tener, o no saben cómo valorarla, porque no pueden hallar en sus corazones una razón para sufrir por ella. No podemos merecer el cielo por todos nuestros sufrimientos más que por nuestros servicios, pero nuestra paciencia nos prepara para el gozo prometido para cuando estamos sometidos a sufrimientos. Nada marca con más fuerza al hombre para la ruina eterna que el espíritu de persecución y enemistad contra el nombre de Dios y su pueblo. Dios atribulará a los que atribulan a su pueblo. Hay un reposo para el pueblo de Dios: un reposo del pecado y de la tristeza. La certeza de la recompensa futura es probada por la justicia de Dios. Pensar en esto debe ser terrible para los impíos, pero sustenta al justo. La fe, mirando hacia ese gran día, es capacitada parcialmente para entender el libro de la providencia, que parece confuso a los incrédulos.
El Señor Jesús se manifestará en aquel día desde el cielo. Vendrá en la gloria y en el poder del mundo de lo alto. Su luz será penetrante y su poder consumidor, para todos los que en aquel día sean contados como paja. Esta manifestación será terrible para los que no conocen a Dios, especialmente para los que se rebelan contra la revelación y no obedecen el evangelio de nuestro Señor Jesucristo. Este es el gran crimen de las multitudes, el evangelio es revelado y ellos no quieren creerlo, o si pretenden creer, no quieren obedecerlo. Está establecido que creer las verdades del evangelio es para obedecer sus preceptos.
Aunque los pecadores puedan ser tolerados por largo tiempo, al final serán castigados. Hicieron la obra del pecado, y deben recibir la paga del pecado. Aquí Dios castiga a los pecadores usando a las criaturas como instrumento, pero entonces habrá destrucción de parte del Todopoderoso; ¿y quién conoce el poder de su ira? -Será un día de gozo para algunos, para los santos, para los que creen y obedecen el evangelio. Cristo Jesús será glorificado y admirado por sus santos en ese día brillante y bendito. Cristo será glorificado y admirado en ellos. Su gracia y su poder serán demostrados cuando se manifieste lo que Él ha adquirido para los que creen en el Señor, y ha obrado en ellos y les ha otorgado a ellos. Señor, si la gloria dada a tus santos será admirada así, ¡cuánto más serás tú admirado, como el Dador de esa gloria! La gloria de tu justicia en la condenación de los malos será admirada, pero no como la gloria de tu misericordia en la salvación de los creyentes. ¡Cuánta admiración santa provocará esto a los ángeles adoradores, y transportará a tus santos admiradores con arrebato eterno! El creyente más vil disfrutará más de lo que pudiera imaginar el corazón más ensanchado mientras estemos aquí; Cristo será admirado en todos los que creen, sin exceptuar al creyente más vil.</p>
<br/>
<p class="text-justify">Vv. 11, 12.Los pensamientos de fe y de expectativa de la segunda venida de Cristo deben llevarnos a orar más a Dios por nosotros y por el prójimo. Si hay algo bueno en nosotros se debe al buen placer de su bondad, y por tanto, se llama gracia. Hay muchos propósitos de gracia y buena voluntad en Dios para con su pueblo y el apóstol ora que Dios complete en ellos con poder la obra de la fe. Esta es que hagan toda buena obra. El poder de Dios no sólo comienza sino que ejecuta la obra de fe. Este es el gran fin y designio de la gracia de nuestro Dios y Señor Jesucristo, que nos es dada a conocer y que obra en nosotros.</p>
<br/>




</div>
