<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Tesalonicenses 2</h2>
<p class="text-justify">Vv. 1-4.Si surgen errores entre los cristianos debemos corregirlos; y los hombres buenos tendrán cuidado para suprimir los errores que surgen de entender mal sus palabras y acciones. Tenemos un adversario astuto que está velando para hacer el mal y fomentar errores hasta por las palabras de la Escritura. Cualquiera sea la incertidumbre que tengamos o cualquiera sean los errores que surjan sobre el tiempo de la venida de Cristo, la venida misma es inminente. Esta ha sido la fe y la esperanza de todos los cristianos en todas las edades de la Iglesia; fue la fe y la esperanza de los santos del Antiguo Testamento. Todos los creyentes serán reunidos en Cristo para estar con Él y ser felices en su presencia para siempre. Debemos creer firmemente la segunda venida de Cristo, pero los tesalonicenses estaban ante el peligro de cuestionar la verdad o certeza de la cosa misma por estar equivocados en cuanto al tiempo. Las doctrinas falsas son como los vientos que mueven el agua de aquí para allá e inquietan la mentes de los hombres que son tan inestables como el agua. Basta con que nosotros sepamos que nuestro Señor vendrá y recogerá a todos sus santos a Él.
Se da una razón del por qué ellos no debían esperar la venida de Cristo como inmediata. Primero tendría que haber una gran caída, la que ocasionará el levantamiento del anticristo, el hombre de pecado. Ha habido grandes debates sobre quién o qué se entiende por este hombre de pecado e hijo de perdición. El hombre de pecado no sólo practica el pecado; también promueve y comanda el pecado y la maldad en los demás; es el hijo de perdición, porque está dedicado a destrucción cierta, y es el instrumento para destruir a muchos, de cuerpo y alma. Como Dios estuvo en el templo antiguo y allí lo adoraban, ahora está en su Iglesia y con ella; de la misma manera el anticristo aquí mencionado es un usurpador de la autoridad de Dios sobre la Iglesia cristiana, y reclama honores divinos.</p>
<br/>
<p class="text-justify">Vv. 5-12.Algo estorba o retiene al hombre de pecado. Se suponía que fuera el poder del imperio romano, al que el apóstol no menciona claramente en esa época. La corrupción de la doctrina y la adoración entraron por grados, y la usurpación del poder fue gradual; así prevaleció el misterio de la iniquidad. La superstición y la idolatría fueron promovidas por una pretendida devoción y se fomentaron el fanatismo y la persecución por el pretendido celo por Dios y su gloria. Entonces el misterio de iniquidad sólo estaba empezando; cuando aun vivían los apóstoles, hubo personas que pretendían celo por Cristo, pero realmente se le oponían.
La caída o ruina del estado anticristiano está declarada. La pura palabra de Dios, con el Espíritu de Dios, denunciará a este misterio de la iniquidad, y en su debido momento, será destruido por el resplandor de la venida de Cristo.
Se falsifican señales y prodigios, visiones y milagros, pero son señales falsas que sustentan doctrinas falsas; hacen prodigios mentirosos o sólo milagros simulados para engañar a la gente; son notorias las obras diabólicas que el estado anticristiano ha estado sustentando.
Se describe a las personas que son sus súbditos voluntarios. El pecado de ellos es éste: no amaron la verdad, y por tanto, no la creyeron; se agradaron con nociones falsas. Dios los deja entregados a sí mismos, entonces sigue el pecado por cierto, y los juicios espirituales aquí, y los castigos eternos en el más allá.
Estas profecías han llegado a cumplirse, en gran medida, y confirman la verdad de las Escrituras. Este pasaje concuerda exactamente con el sistema del papado que prevalece en la iglesia romana, y bajo los papas romanos. Pero aunque el hijo de perdición haya sido revelado, aunque se haya opuesto y exaltado por encima de todo lo que se llama Dios, o que es adorado, haya hablado y actuado como si fuera un dios en la tierra, y haya proclamado su orgullo insolente, y respaldado sus ilusiones con milagros mentirosos y toda clase de fraudes, aún el Señor no lo ha destruido por completo con el fulgor de Su venida, porque aún quedan por cumplirse estas y otras profecías antes que llegue el final.</p>
<br/>
<p class="text-justify">Vv. 13-15.Cuando oímos de la apostasía de muchos es gran consuelo y gozo que haya un remanente conforme a la elección de gracia que persevera y perseverará; debemos regocijarnos especialmente si tenemos razón para esperar estar en ese número. La preservación de los santos se debe a que Dios los ama con amor eterno desde el comienzo del mundo. El fin y los medios no deben separarse. La fe y la santidad deben unirse así como la santidad y la felicidad. El llamamiento externo de Dios es por el evangelio; y este es hecho efectivo por la obra interior del Espíritu. La creencia en la verdad lleva al pecador a confiar en Cristo, y así a amarle y a obedecerle; están sellados por el Espíritu Santo sobre su corazón. No tenemos prueba cierta de que algo más haya sido entregado por los apóstoles fuera de lo que hallamos contenido en las Sagradas Escrituras. Aferrémonos firmemente a las doctrinas enseñadas por los apóstoles y rechacemos todos los agregados y las vanas tradiciones.</p>
<br/>
<p class="text-justify">Vv. 16, 17.Podemos y debemos dirigir nuestras oraciones no sólo a Dios Padre por medio de nuestro Señor Jesucristo, sino también a nuestro Señor Jesucristo mismo. Debemos orar en su nombre a Dios, no sólo como su Padre sino como nuestro Padre en Él y por medio de Él. Manantial y fuente de todo el bien que tenemos o esperamos es el amor de Dios en Cristo Jesús. Hay buenas razones para grandes bendiciones, porque los santos tienen una buena esperanza por medio de la gracia. La gracia y la misericordia gratuita de Dios son lo que ellos esperan y en las que fundan sus esperanzas, y no algún valor o mérito propio de ellos. Mientras más placer tengamos en la palabra, las obras y los caminos de Dios, más probablemente seremos preservados en ellas, pero si vacilamos en la fe y si tenemos una mente que duda, vacilando y tropezando en nuestro deber, no es raro que seamos extraños a los goces de la religión.</p>
<br/>




</div>
