<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Tesalonicenses 3</h2>
<p class="text-justify">Vv. 1-5.Los que están muy alejados aún pueden reunirse ante el trono de la gracia; y los que no pueden hacer ni recibir ninguna otra bondad, de este modo pueden hacer y recibir una bondad real y muy grande. Los enemigos de la predicación del evangelio, y los perseguidores de los predicadores fieles son hombres impíos e irracionales. Muchos no creen el evangelio; y no es de maravillarse si no tienen quietud y muestran malicia en las acciones emprendidas para resistirlo. El mal del pecado es el mal más grande, pero hay otros males de los que debemos ser preservados, y se nos exhorta que dependamos de la gracia de Dios. Una vez que la promesa es hecha, su cumplimiento es seguro y cierto.
El apóstol tenía confianza en ellos, pero se funda en su confianza en Dios; porque de otro modo no hay confianza en el hombre.
Ora por ellos pidiendo bendiciones espirituales. Nuestro pecado y nuestra miseria es que depositamos nuestros afectos en los objetos equivocados. No hay verdadero amor de Dios sin fe en Jesucristo. Si por la gracia especial de Dios tenemos esa fe, que multitudes no tienen, debemos orar fervorosamente que seamos capacitados sin reservas para obedecer sus mandamientos y que el Señor Espíritu pueda dirigir nuestros corazones al amor de Dios y a la paciencia de Cristo.</p>
<br/>
<p class="text-justify">Vv. 6-15.Los que han recibido el evangelio tienen que vivir en forma coherente con el evangelio. Los que pueden trabajar, y no lo hacen, no tienen que mantenerse ociosos. El cristianismo no debe tolerar la pereza que consume lo que puede dar ánimo al laborioso y para sustentar al enfermo y afligido. El trabajo en nuestra vocación de hombres es deber requerido por nuestro llamamiento cristiano. Pero algunos esperaban ser mantenidos en la ociosidad y se consentían un temperamento curioso y soberbio. Ellos se entrometían en las preocupaciones ajenas y hacían mucho daño. Gran error y abuso de la religión es hacerla manto de la pereza o de cualquier otro pecado. El siervo que espera la pronta llegada de su Señor, debe estar trabajando como manda su Señor. Si estamos ociosos, el diablo y el corazón corrupto pronto nos darán algo que hacer. La mente del hombre es dada a ocuparse; si no se la emplea en hacer el bien, estará haciendo el mal.
Es una unión excelente aunque rara la de estar activo en nuestro propio negocio, pero tranquilo en cuanto al de otros. Si alguien rehusa trabajar con tranquilidad, se le tiene que censurar y separarlo de su compañía, pero se tiene que buscar su bien con amonestaciones hechas con amor.
El Señor está contigo mientras tú estés con Él. Mantén tu camino y sosténte hasta el final. Nunca debemos rendirnos ni cansarnos en nuestro trabajo. Habrá suficiente tiempo para reposar cuando lleguemos al cielo.</p>
<br/>
<p class="text-justify">Vv. 16-18.El apóstol ora por los tesalonicenses. Deseemos las mismas bendiciones para nosotros y para nuestros amigos. Paz con Dios. Se les desea esta paz siempre o en todo. Paz por todos los medios; en toda forma para que, al disfrutar de los medios de gracia, puedan usar todos los métodos para asegurar la paz. Para sentirnos seguros y felices no necesitamos, ni podemos desear algo mejor para nosotros y nuestros amigos, que tener por gracia la presencia de Dios con nosotros y con ellos. No importa dónde estemos si Dios está con nosotros; ni quien está ausente si Dios está presente. Por medio de la gracia de nuestro Señor Jesucristo esperamos tener paz con Dios y disfrutar de la presencia de Dios. Esta gracia es todo lo que nos hace felices; aunque la deseemos mucho para otras personas, es suficiente para nosotros.</p>
<br/>




</div>
