<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Timoteo 2</h2>
<p class="text-justify">Vv. 1-7.A medida que crecen nuestras pruebas necesitamos fortalecernos más en lo que es bueno; nuestra fe, más fuerte; nuestra resolución, más fuerte; nuestro amor a Dios y Cristo, más fuerte. Esto en oposición a que seamos más fuertes según nuestro propio poder.
Todos los cristianos, pero especialmente los ministros, deben ser fieles a su Capitán, y resueltos en su causa. El gran afán del cristiano debe ser agradar a Cristo. Tenemos que esforzarnos para dominar nuestras concupiscencias y corrupciones, pero no podemos esperar el premio si no observamos las leyes. Debemos poner cuidado en hacer el bien de manera correcta, para que no se hable mal del bien que hacemos. Algunos que son activos, desperdician su celo en las formas externas y en disputas dudosas. Pero los que luchan lícitamente serán coronados al final. Si deseamos participar de los frutos, debemos trabajar primero; si deseamos ganar el premio debemos correr la carrera. Debemos hacer la voluntad de Dios antes de recibir lo prometido, para lo cual necesitamos paciencia. Junto con nuestras oraciones por el prójimo, para que el Señor les dé entendimiento en todo, debemos estimularlos y exhortarles que consideren lo que oyen o leen.</p>
<br/>
<p class="text-justify">Vv. 8-13.Que los santos que sufren se acuerden y miren a Jesús, el Autor y Consumador de su fe, que por el gozo que le fue puesto delante, soportó la cruz, menospreció la vergüenza, y ahora está sentado a la diestra del trono de Dios. No debe extrañarnos que los mejores hombres se enfrenten al peor de los tratos; pero esto causa regocijo, porque la palabra de Dios no está atada. Aquí vemos la causa real y verdadera de que el apóstol sufriera aflicciones por amor del evangelio. Si estamos muertos a este mundo, a sus placeres, sus beneficios y sus honores, estaremos por siempre con Cristo en un mundo mejor. Él es fiel a sus advertencias y fiel a sus promesas. Esta verdad asegura la condenación del incrédulo y la salvación del creyente.</p>
<br/>
<p class="text-justify">Vv. 14-21.Los que están dispuestos a esforzarse suelen hacerlo por cosas de poca monta. Pero las disputas de palabras destruyen las cosas de Dios. El apóstol menciona a algunos que erraron. No negaron la resurrección, pero corrompieron la doctrina verdadera. Pero nada puede ser más necio o erróneo, porque trastorna la fe temporal de algunos profesantes. Este fundamento tiene dos cosas escritas en él. Una habla de nuestro consuelo. Nada puede derribar la fe de alguien a quien Dios escogió. El otro habla de nuestro deber. Los que deseen tener el consuelo del privilegio deben tomar conciencia del deber.
Cristo se dio por nosotros para redimirnos de toda iniquidad, Tito ii, 14. La Iglesia de Cristo es como una habitación: algo del mobiliario es de gran valor; otro, de poco valor, y dedicado a usos más viles. Algunos que profesan la religión son como vasos de madera y barro. Cuando los vasos de deshonra sean tirados para ser destruidos, los otros serán llenos de toda la plenitud de Dios. Debemos ocuparnos de que seamos vasos santos. A cada cual a quien apruebe Dios de la Iglesia será dedicado al servicio de su Maestro, y de este modo será equipado para su uso.</p>
<br/>
<p class="text-justify">Vv. 22-26.Mientras más sigamos lo que es bueno, más rápido y más lejos huiremos de lo malo. Mantener la comunión de los santos nos sacará de la comunión con las obras infructuosas de las tinieblas. Nótese cuán a menudo el apóstol advierte contra los debates en la religión; lo cual demuestra con seguridad que la religión consiste más en creer y practicar lo que Dios requiere que en disputas sutiles. Son ineptos para enseñar los que son dados a esforzarse, y son fieros y osados. Enseñanza, no persecución, tal es el método de las Escrituras para tratar a los que están en error.
El mismo Dios que da la revelación de la verdad, por su gracia nos lleva a reconocerlo, de lo contrario nuestros corazones seguirían rebelándose contra ello. No existe el “por si acaso”en cuanto a que Dios perdone a los que se arrepienten, pero no podemos decir que dará arrepentimiento a los que se oponen a su voluntad.
Los pecadores son metidos en una trampa, y en la peor trampa, porque es del diablo; ellos son sus esclavos. Si alguno anhela liberación, que recuerde que no puede escapar excepto por arrepentimiento, que es la dádiva de Dios; que debemos pedirlo a Él con oración fervorosa y perseverante.</p>
<br/>




</div>
