<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">2 Timoteo 1</h2>
<p class="text-justify">Vv. 1-5.La promesa de la vida eterna a los creyentes en Cristo Jesús es el tema principal de los ministros que están empleados conforme a la voluntad de Dios. Las bendiciones aquí nombradas son lo mejor que podemos pedir para nuestros amados amigos, que tengan paz con Dios Padre y nuestro Señor Jesucristo. Dios debe tener la gloria cualquiera sea el bien que hagamos. Los creyentes verdaderos tienen la misma religión como sustancia en toda época. La fe de ellos no es fingida; soporta la prueba y habita en ellos como principio vivo.
De manera que, las mujeres piadosas pueden animarse por el éxito de Loida y Eunice con Timoteo, que resultó ser tan excelente y útil como ministro. Algunos de los ministros más dignos y valiosos con que ha sido favorecida la Iglesia de Cristo, han tenido que bendecir a Dios por las tempranas impresiones religiosas hechas en sus mentes por medio de la enseñanza de sus madres u otras parientas.</p>
<br/>
<p class="text-justify">Vv. 6-14.Dios no nos ha dado espíritu de temor, sino de poder, de amor y de dominio propio para enfrentar dificultades y peligros; el espíritu de amor a Él que nos hará vencer la oposición. El espíritu de una mente sabia, de la tranquilidad mental. El Espíritu Santo no es el autor de una disposición tímida o cobarde ni de temores esclavizantes.
Es probable que tengamos que sufrir aflicciones cuando tengamos el poder y la fuerza de Dios que nos capaciten para soportarlas. Como es habitual en Pablo, cuando menciona a Cristo y su redención, se explaya al respecto, tan pleno estaba de lo que es toda nuestra salvación y que debiera ser todo nuestro deseo. El llamamiento del evangelio es un llamado santo, que santifica. La salvación es por la libre gracia. Se dice que esta nos es dada desde antes de la fundación del mundo, esto es, en el propósito de Dios desde toda la eternidad; en Cristo Jesús, porque todos los dones que vienen de Dios para el hombre pecador, vienen en Jesucristo y a través de Él solo. Como hay una perspectiva tan clara de la dicha eterna por la fe en Aquel que es la Resurrección y la Vida, pongamos más diligencia en asegurar su salvación para nuestras almas.
Los que echan mano del evangelio no tienen que avergonzarse, la causa los librará, pero los que se oponen a éste serán avergonzados. El apóstol había encomendado su vida, su alma y sus intereses eternos al Señor Jesús. Nadie más podría liberar y asegurar su alma por medio de las pruebas de la vida y de la muerte. Viene el día en que nuestras almas serán interrogadas. A ti se te encargó un alma, ¿cómo la ocupaste? ¿al servicio del pecado o al servicio de Cristo? La esperanza del cristiano verdadero de menor estatura descansa sobre el mismo fundamento que la del gran apóstol. También aprendió el valor y el riesgo de su alma; también creyó en Cristo; el cambio obrado en su alma, convence al creyente que el Señor Jesús le guardará para su reino celestial.
Pablo exhorta a Timoteo a que se aferre firme de las Sagradas Escrituras, a la sustancia de la sólida verdad del evangelio en ellas. No basta con asentir a las sabias palabras; hay que amarlas.
La doctrina cristiana es un encargo que se nos ha entregado; tiene valor indecible en sí misma y nos será de ventaja indecible. Se nos ha encargado para ser preservado puro y completo, pero no debemos pensar en mantenerlo por nuestra propia fuerza, sino por el poder del Espíritu Santo que habita en nosotros; y no será ganado por los que confían en sus propios corazones y se inclinan a sus propios entendimientos.</p>
<br/>
<p class="text-justify">Vv. 15-18.El apóstol menciona la constancia de Onesíforo, a menudo refrescado con sus cartas, consejos, y consuelos, y no se avergüenza de él. Un hombre bueno procurará hacer el bien.
El día de la muerte y del juicio es un día temible. Si deseamos tener misericordia, entonces debemos buscarla ahora del Señor. Lo mejor que podemos pedir, para nosotros y para nuestros amigos, es que el Señor conceda que nosotros y ellos podamos hallar misericordia del Señor, cuando seamos llamados a pasar del tiempo a la eternidad y a comparecer al juicio de Cristo.</p>
<br/>




</div>
