<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">3 Juan 1</h2>
<p class="text-justify">Vv. 1-8.Los que son amados de Cristo, amarán a los hermanos por amor a Él. La prosperidad del alma es la mayor bendición a este lado del cielo. La gracia y la salud son ricas compañías. La gracia empleará la salud. El alma rica puede estar alojada en el cuerpo débil; y la gracia debe, entonces, ejercerse para someterse a tal dispensación. Pero podemos desear y orar que los que tienen almas prósperas puedan tener cuerpos sanos; que su gracia pueda brillar donde aún haya lugar para la actividad. Cuántos profesantes hay, sobre los cuales deben volverse las palabras del apóstol, y debemos desear con fervor y orar que sus almas prosperen, ¡al prosperar su salud y sus circunstancias! -La fe verdadera obrará por amor. Dar un buen informe corresponde a los que reciben el bien; ellos no pueden sino testificar a la iglesia lo que hallaron y sintieron. Los hombres buenos se regocijan en la prosperidad del alma del prójimo; y se alegran al oír de la gracia y la bondad de otros. Así como es gozo para los buenos padres, será un gozo para los buenos ministros ver que su gente adorna su profesión.
Gayo pasó por alto diferencias menores entre cristianos serios y ayudó generosamente a todos los que llevaban la imagen y hacían la obra de Cristo. Fue recto en lo que hizo como siervo fiel. Las almas fieles pueden oír que se les elogia sin envanecerse; la felicitación de lo que es bueno en ellos, los pone a los pies de la cruz de Cristo.
Los cristianos deben considerar no sólo lo que deben hacer, sino lo que pueden hacer; y deben hacer hasta las cosas corrientes de la vida, de buena voluntad, con buen ánimo, sirviendo en ello a Dios y procurando así su gloria. Los que dan a conocer libremente el evangelio de Cristo, serán ayudados por los demás a quienes Dios da los medios. Los que no pueden proclamarlo pueden recibir, de todos modos, ayuda y sostener a los que sí lo hacen.</p>
<br/>
<p class="text-justify">Vv. 9-12.Debe vigilarse el corazón y la boca. El temperamento y el espíritu de Diótrefes estaba lleno de orgullo y ambición. Es malo no hacer el bien por nosotros mismos, pero es peor estorbar a los que hacen el bien. Esas advertencias y consejos son aceptados, más probablemente, cuando están sazonados con amor. Seguir lo que es bueno, porque el que hace el bien, deleitándose en ellos, es nacido de Dios. Los malhechores pretenden vanamente o se jactan de conocer a Dios. No sigamos lo que es soberbia, egoísmo y de mala intención, aunque el ejemplo sea dado por personas de alto rango y poder; seamos seguidores de Dios y andemos en amor según el ejemplo de nuestro Señor.</p>
<br/>
<p class="text-justify">Vv. 13, 14.He aquí el carácter de Demetrio. Un nombre en el evangelio o un buen testimonio de las iglesias es mejor que la honra mundana. Después de todo, de pocos se habla bien después de todo; y, a veces, es malo que sea así. Felices aquellos cuyo espíritu y conducta los elogian ante Dios y los hombres. Debemos estar preparados para darles nuestro testimonio; y bueno es cuando los que elogian, pueden apelar a las conciencias de los que conocen mejor a aquellos que son encomiados. La conversación personal, juntos, ahorra tiempo y evita problemas, y los errores que surgen de las cartas; todos los buenos cristianos pueden alegrarse de verse unos a otros. La bendición es, La paz sea contigo; toda la dicha sea contigo. Muy bien pueden saludarse unos a otros en la tierra los que esperan vivir juntos en el cielo. Juntándose con cristianos e imitanto el ejemplo de ellos, tendremos paz interior y viviremos en paz con los hermanos; nuestras comunicaciones con el pueblo del Señor en la tierra serán gratas y seremos contados con ellos en la gloria eterna.</p>
<br/>




</div>
