<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Abdías 1</h2>
<p class="text-justify">Vv. 1-16.Esta profecía es contra Edom. Su destrucción parece haber sido un tipo, como el rechazo de Esaú, su padre, y se refiere a la destrucción de los enemigos de la Iglesia del evangelio.
Véase la predicción del éxito de esa guerra; Edom será saqueado y derribado. Todos los enemigos de la Iglesia de Dios se decepcionarán de las cosas en que se fijaron. Dios puede abatir fácilmente a los que se magnifican y exaltan a sí mismos; y lo hará.
La seguridad carnal prepara al hombre para la ruina, y hace que la ruina sea peor cuando llega. Los tesoros de la tierra no pueden amontonarse con seguridad, porque los ladrones pueden entrar y robar; por tanto es sabiduría nuestra amontonar tesoros en el cielo. Quienes hacen de la carne su confianza, la arman contra sí mismos. El Dios de nuestro pacto nunca nos engañará: pero si confiamos en los hombres con quienes nos juntamos, podemos salir heridos y sin honra.
Con justicia Dios negará el entendimiento para mantenerse fuera de peligro a los que no usan el entendimiento para mantenerse alejados del pecado. Toda violencia, toda injusticia es pecado; pero empeora mucho la violencia cuando se ejerce contra quien sea del pueblo de Dios. Su conducta bárbara hacia Judá y Jerusalén, se carga contra ellos. Al reflexionar en nosotros es bueno que consideremos lo que debíamos hacer; y que comparemos nuestro quehacer con la regla bíblica. El pecado, así mirado en el espejo del mandamiento parecerá excesivamente pecaminoso. Tienen mucho por qué responder los que son espectadores pasivos de los problemas de su prójimo, cuando pueden ser ayudadores activos. Se empobrecen los que piensan que se enriquecen con la ruina del pueblo de Dios; y se engañan los que llaman propio todo aquello sobre lo cual pueden poner sus manos en una época de calamidades. Aunque el juicio empieza por la casa de Dios, no terminará allí. Que los creyentes apenados y los opresores insolentes sepan que los problemas del justo terminarán pronto, pero los del impío serán eternos.</p>
<br/>
<p class="text-justify">Vv. 17-21.Habrá liberación y santidad en Jerusalén, y la casa de Jacob ocupará nuevamente sus posesiones. Mucho de esta profecía se cumplió cuando los judíos regresaron [del cautiverio] a su tierra, pero parece que aquí también se piensa en la salvación y la santidad del evangelio, su difusión y la conversión de los gentiles, y especialmente la restauración de Israel, la destrucción del anticristo, y el próspero estado de la Iglesia, del cual dan testimonio todos los profetas. Cuando Cristo venga, y no antes, será el reino del Señor en todo el pleno sentido de la palabra. Como no prosperará nadie que se exalte a sí mismo contra el Señor, y todos serán humillados, así, nadie que atienda al Señor y ponga su confianza en Él, será jamás desengañado. ¡Bendito sea el Salvador y Juez divino en el Monte Sion! Su palabra será sabor de vida para vida para muchos, en cambio, juzga y condena a los incrédulos obstinados.</p>
<br/>




</div>
