<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 22</h2>
<p class="text-justify">Vv. 1-5.Todos los arroyos del consuelo terrenal son fangosos, pero estos son claros y refrescantes. Dan vida, y preservan la vida, para los que beben de ellos, y así, fluirán para siempre. Indican las influencias vivificantes y santificadoras del Espíritu Santo, según se dan a los pecadores por medio de Cristo. El Espíritu Santo, procedente del Padre y del Hijo, aplica esta salvación a nuestras almas por su amor y poder que crean de nuevo. Los árboles de vida son alimentados por las aguas puras del río que sale del trono de Dios. La presencia de Dios en el cielo es la salud y la dicha de los santos. Este árbol era un símbolo de Cristo y de todas las bendiciones de su salvación; y las hojas para sanar las naciones significan que su favor y presencia suplen todo el bien a los habitantes de ese mundo bendito.
El diablo no tiene poder allí; no puede desviar a los santos de servir a Dios, ni puede perturbarlos en el servicio de Dios. Aquí se habla como de Uno de Dios y del Cordero. El servicio será ahí no sólo libertad, sino honor y dominio. No habrá noche; ni aflicción ni congoja, nada de pausas en el servicio o el placer: nada de diversiones o placeres de invención humana serán deseados allí. ¡Qué diferente todo esto de los puntos de vista puramente humanos y groseros de la dicha celestial, de los que se refieren a los placeres de la mente!</p>
<br/>
<p class="text-justify">Vv. 6-19.El Señor Jesús habló por el ángel, confirmando solemnemente el contenido de este libro, particularmente de esta última visión. Él es el Señor Dios fiel y verdadero. Además, habló por sus mensajeros, los santos ángeles que le comunicaron a los hombres santos de Dios. Estas son cosas que deben finalizar dentro de poco. Cristo vendrá pronto y pondrá todas las cosas fuera de duda. Y habló por la integridad del ángel que había sido el intérprete del apóstol. Él rehusó aceptar la adoración de parte de Juan y lo reprendió por ofrecerla. Esto presenta otro testimonio contra la adoración idólatra de santos y ángeles. Dios llama a cada uno a dar testimonio de las declaraciones aquí hechas. Este libro, así conservado abierto, tendrá efecto en los hombres: el inmundo y el injusto lo será más; pero confirmará, fortalecerá y santificará más a los que son justos para con Dios.
Nunca pensemos que una fe muerta o desobediente nos salvará, porque el Primero y el Último ha declarado que son bienaventurados solo los que hacen sus mandamientos. Este es un libro que excluye del cielo a todas las personas malas e injustas, en particular las que aman y hacen mentiras, por tanto, en sí mismo [este libro] no puede ser una mentira. No hay punto ni condición intermedios.
Jesús, que es el Espíritu de profecía, ha dado a sus iglesias la luz matutina de la profecía para asegurarles la luz del perfecto día que se aproxima. Todo está confirmado por una invitación general directa a la humanidad a ir y participar libremente de las promesas y de los privilegios del evangelio. El Espíritu, por la palabra sagrada, y por las convicciones e influencias en la conciencia del pecador, dice: Ven a Cristo para salvación; y la novia, o toda la Iglesia, en la tierra y el cielo, dice: Ven y comparte nuestra dicha. Para que ninguno dude, se agrega: El que quiera o esté deseoso, venga y tome del agua de la vida gratuitamente. Que cada uno que oiga o lea estas palabras, desee de inmediato aceptar la invitación de gracia. Están condenados todos los que se atrevan a corromper o a cambiar la palabra de Dios sea agregándole o quitándole.</p>
<br/>
<p class="text-justify">Vv. 20, 21.Luego de descubrir estas cosas a su pueblo de la tierra, Cristo parece irse de ellos volviendo al cielo, pero les asegura que no pasará mucho tiempo antes que vuelva otra vez. Mientras estamos ocupados en los deberes de nuestros diferentes puestos en la vida, no importa cuales sean las labores que nos prueben, o las dificultades que nos rodeen, o las congojas que nos opriman, escuchemos con placer a nuestro Señor que proclama: He aquí, yo vengo pronto. Yo vengo a terminar la labor y el sufrimiento de mis siervos. Yo vengo, y mi galardón de gracia conmigo, para premiar, con abundancia verdadera, a toda obra de fe y trabajo de amor. Vengo a recibir a mi pueblo fiel y perseverante para mí mismo, para habitar por siempre en aquel mundo bendito. Amén, así sea, ven, Señor Jesús.
Una bendición cierra todo. Por la gracia de Cristo debemos ser mantenidos en la expectativa gozosa de su gloria, equipados para ella y preservados para ella; y su manifestación gloriosa será de regocijo para los que participan aquí de su gracia y favor. Que todos digan, Amén. Tengamos sed de las grandes medidas de las influencias de gracia del bendito Jesús para nuestras almas y de su presencia de gracia con nosotros hasta que la gloria haga perfecta su gracia en nosotros.
Gloria sea al Padre, al Hijo, y al Espíritu Santo; como era en el principio, es ahora y ha de ser, eternamente en el mundo sin fin. Amén.
FIN</p>
<br/>




</div>
