<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 1</h2>
<p class="text-justify">Vv. 1-3.Este libro es la revelación de Jesucristo; toda la Biblia lo es, porque toda revelación viene por medio de Cristo y todo se relaciona con Él. Su tema principal es exponer los propósitos de Dios acerca de los asuntos de la Iglesia y de las naciones según se relacionan con ella, y del fin del mundo. Todo esto ocurrirá con toda seguridad y empezarán a suceder dentro de muy poco tiempo. Aunque Cristo mismo es Dios y tiene luz y vida en sí, sin embargo, como Mediador entre Dios y el hombre, recibe instrucciones del Padre. A Él debemos el conocimiento de lo que tenemos que esperar de Dios y de lo que Él espera de nosotros. El tema de esta revelación eran las cosas que deben suceder pronto. Se pronuncia una bendición para todos los que leen o escuchan las palabras de esta profecía. Buena ocupación tienen los que investigan la Biblia. No basta con leer y oír, pero debemos mantener en nuestra memoria, en nuestra mente, en nuestros afectos y en la práctica, las cosas que están escritas y seremos bendecidos en la obra. Aun los misterios y las dificultades de este libro están unidos con revelaciones de Dios, adecuadas para imprimir en la mente un temor reverente y para purificar el alma del lector, aunque puede que éste no discierna el significado profético. Ninguna parte de la Escritura expone más plenamente el evangelio y advierte mejor contra el mal del pecado.</p>
<br/>
<p class="text-justify">Vv. 4-8.No puede haber verdadera paz donde no hay verdadera gracia; donde va primero la gracia, seguirá la paz. Esta bendición es en el nombre de Dios, de la Santa Trinidad, es un acto de adoración. Primero se nombra al Padre, descrito como el Señor, que es, el que era y ha de venir, eterno, inmutable. El Espíritu Santo es llamado los siete espíritus, el perfecto Espíritu de Dios, en quien hay diversidad de dones y operaciones. El Señor Jesucristo fue desde la eternidad, un Testigo de todos los consejos de Dios. Él es el Primogénito de los muertos, que por su poder resucitará a su pueblo. Él es el Príncipe de los reyes de la tierra; por Él son derogados sus consejos y ante Él son ellos responsables de rendir cuentas. El pecado deja una mancha de culpa y contaminación en el alma. Nada puede quitar esta mancha, sino la sangre de Cristo, y Cristo derramó su propia sangre para satisfacer la justicia divina, y comprar el perdón y la pureza para su pueblo.
Cristo ha hecho de los creyentes reyes y sacerdotes para Dios y su Padre. Como tales ellos vencen al mundo, mortifican el pecado, gobiernan sus propios espíritus, resisten a Satanás, prevalecen con Dios en oración y juzgarán al mundo. Él los ha hecho sacerdotes, les ha dado acceso a Dios, los ha capacitado para ofrecer sacrificios espirituales aceptables, y por estos favores ellos tienen que darle dominio y gloria para siempre. -Él juzgará al mundo. Llama la atención hacia ese gran día en que todos veremos la sabiduría y la felicidad de los amigos de Cristo y la locura y desdicha de sus enemigos. Pensemos frecuentemente en la segunda venida de Cristo. Él vendrá para terror de quienes le hieren y crucifican de nuevo en su apostasía; Él vendrá para asombro de todo el mundo de los impíos. Él es Principio y Fin; todas las cosas son de Él y para Él; Es el Todopoderoso; el mismo Eterno e Inmutable. Si deseamos ser contados con sus santos en la gloria eterna, debemos someternos ahora voluntariamente a Él, recibirle, y honrarle como Salvador, al que creemos vendrá a ser nuestro Juez. ¡Ay, que hubiera muchos que desearan no morir nunca, y que no hubiera un día de juicio!</p>
<br/>
<p class="text-justify">Vv. 9-11.Consuelo del apóstol es que no sufrió como malhechor, sino por el testimonio de Jesús, por dar testimonio de Cristo como el Emanuel, el Salvador; el Espíritu de gloria y de Dios reposó sobre este perseguido apóstol. El día y la hora de esta visión fue el día del Señor, el día de reposo cristiano, el primer día de la semana, observado en memoria de la resurrección de Cristo. Nosotros, que le llamamos “nuestro Señor”, debemos honrarle en su propio día. El nombre muestra cómo debe observarse este día sagrado; el día del Señor debe ser dedicado absolutamente al Señor y ninguna de sus horas debe emplearse en forma sensual, mundana o en diversiones. -Él estaba en una actitud seria, celestial, espiritual, bajo la influencia de la gracia del Espíritu de Dios. Los que deseen disfrutar de la comunión con Dios en el día del Señor, deben procurar sacar sus pensamientos y afectos de las cosas terrenales. Si a los creyentes se les impide observar el día santo del Señor con las ordenanzas públicas y la comunión de los santos, por necesidad y no por propia opción, pueden buscar consuelo en la meditación y los deberes secretos de la influencia del Espíritu; oyendo la voz y contemplando la gloria de su amado Salvador, de cuyas palabras de gracia y poder no los puede separar confinamiento alguno ni ninguna circunstancia externa. Se nos da una alarma con el sonido de la trompeta, y luego, el apóstol oyó la voz de Cristo.</p>
<br/>
<p class="text-justify">Vv. 12-20.Las iglesias reciben su luz de Cristo y del evangelio, y la muestran a otros. Ellas son los candeleros de oro; deben ser preciosas y puras; no sólo los ministros, sino los miembros de ellas; así debe brillar su luz delante de los hombres, como para llevar a otros a dar gloria a Dios. El apóstol vio como si el Señor Jesucristo apareciera en medio de los candeleros de oro. Él siempre está con sus iglesias, hasta el fin del mundo, llenándolas con luz, vida, y amor. Estaba vestido con un manto hasta los pies, quizá representando su justicia y su sacerdocio, como Mediador. Esta vestimenta estaba ceñida con un cinto de oro, que puede denotar cuán preciosos son su amor y afecto por su pueblo. Su cabeza y cabellos blancos como lana y nieve puede representar su majestad, pureza y eternidad. Sus ojos como llamas de fuego pueden representar su conocimiento de los secretos de todos los corazones y de los sucesos más distantes. Sus pies, como de bronce bruñido que arde en un horno, pueden denotar la firmeza de sus designios y la excelencia de sus procedimientos. Su voz, como el sonido de muchas aguas, puede representar el poder de su palabra, para quitar o destruir. Las siete estrellas eran símbolo de los ministros de las siete iglesias a las cuales tenía que escribir el apóstol, y a quienes Cristo sostenía y mandaba. La espada representa su justicia y su palabra, que alcanza hasta dividir alma y espíritu, Hebreos iv, 12. Su rostro era como el sol, cuando brilla clara y fuertemente; su fuerza demasiado brillante y cegadora para que la contemplen los ojos mortales.
El apóstol estaba sobrecogido con la grandeza del lustre y la gloria con que apareció Cristo. Nosotros bien podemos estar contentos con andar por fe mientras estemos aquí en la tierra. El Señor Jesús dijo palabras de consuelo: No temas. Palabras de instrucción, diciendo quién era el que así aparecía. Su naturaleza divina: el Primero y el Último. Sus sufrimientos anteriores: estuve muerto: el mismo a quien vieron en la cruz sus discípulos. Su resurrección y vid: he vencido a la muerte y soy partícipe de vida eterna. Su oficio y autoridad: el dominio soberano en el mundo invisible y sobre él, como el Juez de todo, de cuya sentencia no hay apelación. Escuchemos la voz de Cristo y recibamos las prendas de su amor, porque ¿qué puede ocultar de aquellos por cuyos pecados murió? Entonces obedezcamos su palabra y entreguémonos totalmente a aquel que dirige rectamente todas las cosas.</p>
<br/>




</div>
