<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 12</h2>
<p class="text-justify">Vv. 1-6.La iglesia, representada por una mujer, la madre de los creyentes, fue vista en el cielo por el apóstol en una visión. Ella estaba vestida de sol, justificada, santificada y brillando por la unión con Cristo, el Sol de la Justicia. La luna estaba bajo sus pies; ella era superior a la luz reflejada y más débil que la revelación hecha por Moisés. Tenía en su cabeza una corona de doce estrellas; la doctrina del evangelio predicada por los doce apóstoles es una corona de gloria de todos los creyentes verdaderos. Estaba con dolor para dar a luz una santa familia; deseosa que la convicción de los pecadores pueda terminar en su conversión. El dragón es emblema conocido de Satanás, y de sus agentes principales, o de los que gobiernan por él en la tierra, como en esa época el imperio pagano de Roma, la ciudad edificada sobre siete colinas. Teniendo diez cuernos, dividida en diez reinos. Tener siete coronas representa siete formas de gobierno. Arrastraba con su cola a la tercera parte de las estrellas del cielo, y las arrojaba a la tierra; perseguía y seducía a los ministros y maestros. Vigilando para aplastar la religión cristiana, pero, a pesar de la oposición de los enemigos, la iglesia sacó adelante a un grupo varonil de profesantes fieles y verdaderos en quienes Cristo fue verdaderamente formado de nuevo; el misterio de Cristo, el Hijo de Dios que gobernará las naciones y a cuya diestra sus miembros participan de la misma gloria. Esta bendita simiente fue protegida por Dios.</p>
<br/>
<p class="text-justify">Vv. 7-11.Los intentos del dragón resultaron infructuosos contra la iglesia, y fatales para sus propios intereses. La sede de esta guerra era el cielo; en la iglesia de Cristo, el reino del cielo en la tierra. Las partes eran Cristo, el gran Ángel del pacto, y sus fieles seguidores; y Satanás y sus instrumentos. La fuerza de la iglesia está en tener al Señor Jesús como Capitán de la salvación de ellos.
La idolatría pagana, que era la adoración de los demonios, fue echada del imperio por la difusión del cristianismo. La salvación y la fuerza de la iglesia sólo deben atribuirse al Rey y Cabeza de la iglesia. El enemigo vencido odia la presencia de Dios, pero está dispuesto a comparecer para acusar al pueblo de Dios. Cuidémonos para no darle causa de acusarnos; cuando hemos pecado, presentémonos ante el Señor, a condenarnos a nosotros mismos y encomendar nuestra causa a Cristo como nuestro Abogado. Los siervos de Dios vencen a Satanás por la sangre del Cordero, como su causa. Por la palabra de su testimonio: la predicación poderosa del evangelio es potente, por medio de Dios, para derribar fortalezas. Por su valor y paciencia en los sufrimientos: ellos no amaron tanto a sus vidas, pero las rindieron por la causa de Cristo. Estos eran los guerreros y las armas por las cuales el cristianismo derrocó el poder de la idolatría pagana; si los cristianos hubieran continuado peleando con estas armas, y con otras como estas, sus victorias hubieran sido más numerosas y gloriosas, y sus efectos, más duraderos.
Los redimidos vencieron por su simple confianza en la sangre de Cristo, como la única base de sus esperanzas. En esto debemos ser como ellos. No debemos mezclar nada más con esto.</p>
<br/>
<p class="text-justify">Vv. 12-17.La iglesia y todos sus amigos bien pueden ser convocados para alabar a Dios por liberar de la persecución pagana, aunque otras angustias les esperen. El desierto es un lugar desolado y lleno de serpientes y escorpiones, incómodo y sin provisiones, pero es lugar seguro donde uno puede estar solo.
Pero estar así de retirada, no es algo que protegiera a la mujer. Muchos explican al torrente de agua como las invasiones de los bárbaros por los cuales fue derrotado el imperio occidental, porque los paganos animaron sus ataques esperando destruir al cristianismo. Pero los hombres impíos protegieron a la iglesia en medio de estos tumultos, debido a sus intereses mundanos, y la derrota del imperio no ayudó a la causa de la idolatría. O, esto puede significar un torrente de error por el cual la Iglesia de Dios estuvo en peligro de ser derribada y descarriada. El diablo, derrotado en sus intenciones contra la Iglesia, vuelve su furia contra personas y lugares. Ser fiel a Dios y Cristo, en doctrina, adoración y práctica, expone a la ira de Satanás y así será hasta que el último enemigo sea destruido.</p>
<br/>




</div>
