<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 18</h2>
<p class="text-justify">Vv. 1-8.La caída y la destrucción de la Babilonia mística están determinadas en los consejos de Dios. Otro ángel viene del cielo. Este parece ser Cristo mismo, que viene a destruir a sus enemigos y a derramar la luz de su evangelio por todas las naciones. La maldad de esta Babilonia era muy grande; había olvidado al Dios verdadero y había puesto ídolos, arrastrando a toda clase de hombres al adulterio espiritual, y por su riqueza y lujo, los mantuvo interesados en ella. Parece representar principalmente la mercadería espiritual, por la cual son multitudes las que han vivido en riquezas de maldad, por los pecados y la necedad de la humanidad.
Se da advertencia justa a todos los que esperan misericordia de Dios de que no sólo deben salir de Babilonia sino ayudar a su destrucción. Dios puede tener pueblo hasta en Babilonia. Pero el pueblo de Dios será llamado a salir de Babilonia, y llamado eficazmente, mientras que los que participan con los impíos en sus pecados, deben recibir sus plagas.</p>
<br/>
<p class="text-justify">Vv. 9-19.Los dolientes habían participado de los placeres sensuales de Babilonia, y habían hecho ganancias por su riqueza y comercio. Eran los reyes de la tierra, a quienes ella había atraído a la idolatría, permitiéndoles ser tiránicos con sus súbditos, aunque obedientes a ella; también eran los mercaderes, los que traficaban sus indulgencias, perdones y honores; ellos son los que se lamentan. Los amigos de Babilonia participaron de sus placeres y beneficios pecaminosos, pero no están dispuestos a participar de sus pestes. El espíritu del anticristo es un espíritu mundano, y el lloro es una pura tristeza mundana; ellos no lloran por la ira de Dios, sino por la pérdida de sus comodidades externas. La magnificencia y las riquezas de los impíos de nada les servirán, pero harán más difícil de soportar la venganza. La mercadería espiritual es aquí aludida cuando menciona como artículos de comercio no sólo a los esclavos, sino las almas de los hombres para la destrucción de las almas de millones. Tampoco esto ha sido peculiar del anticristo romano y su sola culpa.
Pero que los mercaderes prósperos aprendan, con todas sus ganancias, a conseguir las riquezas inescrutables de Cristo; de lo contrario, aun en esta vida, puede que tengan que lamentar que las riquezas crían alas y se alejan volando, y que todos los frutos por los cuales contaminaron de lujuria sus almas, los abandonaron. En todo caso, la muerte terminará pronto su comercio y todas las riquezas de los impíos serán intercambiadas no sólo por el ataúd y el gusano, sino por el fuego que no puede apagarse.</p>
<br/>
<p class="text-justify">Vv. 20-24.Lo que es materia de júbilo para los siervos de Dios en la tierra, es materia de regocijo para los ángeles en el cielo. Los apóstoles, que son honrados y diariamente adorados en Roma, en forma idólatra, se regocijarán por su caída. La caída de Babilonia fue un acto de la justicia de Dios. Como fue una ruina final, este enemigo nunca más les molestará otra vez; de esto tienen la seguridad por una señal. Recibamos la advertencia de las cosas que llevan a los demás a su destrucción, y pongamos nuestros afectos en las cosas de arriba, cuando consideramos la naturaleza variable de las cosas terrenales.</p>
<br/>




</div>
