<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 19</h2>
<p class="text-justify">Vv. 1-10.Alabar a Dios por lo que tenemos es orar por lo que aún va a hacer por nosotros. Hay armonía entre los ángeles y los santos en este cántico triunfal.
Cristo es el Esposo de su Iglesia rescatada. Esta segunda unión será completada en el cielo, pero el comienzo del milenio glorioso (por el cual se significa el reino de Cristo, o estado de dicha por mil años en la tierra) puede ser considerado como la celebración de sus esponsales en la tierra. Entonces, la Iglesia de Cristo, purificada de errores, divisiones y corrupciones de doctrina, disciplina, adoración y práctica, estará preparada para ser públicamente reconocida por Él como su delicia y su amada. La Iglesia apareció, no con el vestido alegre e impúdico de la madre de las prostitutas, sino con lino fino, limpio y blanco. Son las vestiduras de la justicia de Cristo, imputada para justificación e impartida para santificación. Las promesas del evangelio, los dichos verdaderos de Dios, abiertas, aplicadas y selladas por el Espíritu de Dios, en santas ordenanzas, son el festejo nupcial. Esto parece referirse a la abundante gracia y consuelo que recibirán los cristianos en los dichosos días que tienen que venir.
El apóstol ofreció honores al ángel, que los rechazó. Dirigió al apóstol al único objeto verdadero de adoración religiosa: adora a Dios y a Él solo. Esto condena claramente la práctica de los que adoran los elementos del pan y del vino, y santos, y ángeles, y los que no creen que Cristo es verdaderamente, y por naturaleza, Dios, pero le rinden una suerte de adoración. Son reos de idolatría por un mensajero del cielo. Estos son los verdaderos dichos de Dios; del que debe ser adorado como uno con el Padre y el Espíritu Santo.</p>
<br/>
<p class="text-justify">Vv. 11-21.Cristo, la Cabeza gloriosa de la Iglesia, se presenta sobre un caballo blanco, el símbolo de la justicia y la santidad. Tiene muchas coronas, porque es el Rey de reyes y el Señor de señores. Está vestido con un ropaje empapado en su propia sangre, por la cual compró su poder como Mediador; y en la sangre de sus enemigos, sobre los cuales siempre prevalece. Su nombre es “El Verbo de Dios”; nombre que nadie conoce plenamente sino Él mismo; sólo esto sabemos nosotros, que este Verbo era Dios manifestado en la carne; pero sus perfecciones no pueden ser plenamente entendidas por ninguna criatura.
Le siguen ángeles y santos y son como Cristo en su armadura de pureza y justicia. Él va a ejecutar las amenazas de la palabra escrita en sus enemigos. Las insignias de su autoridad son su nombre; afirma su autoridad y poder, y advierte a los príncipes más poderosos que se sometan o caigan ante Él.
Las potestades de la tierra y del infierno hacen su máximo esfuerzo. Estos versículos declaran hechos importantes anunciados por los profetas. Estas personas no fueron excusadas porque hicieron lo que sus jefes les mandaron. ¡Qué vano será el alegato de muchos pecadores en ese gran día! ¡Nosotros seguimos a nuestros jefes! ¡Hicimos lo que vimos que hacían otros! En su Palabra, Dios dio una regla para caminar; ni el ejemplo de la mayoría, ni el del jefe, deben movernos a lo contrario; si hacemos como la mayoría, debemos ir donde va la mayoría, al lago de fuego.</p>
<br/>




</div>
