<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 8</h2>
<p class="text-justify">Vv. 1-6.Se abre el séptimo sello. Hubo un profundo silencio en el cielo por un espacio de tiempo; todo estaba callado en la iglesia, porque cada vez que la iglesia de la tierra grita por la opresión, ese grito llega al cielo; o es un silencio de expectativa. Se dieron trompetas a los ángeles, que tenían que tocarlas. El Señor Jesús es el Sumo Sacerdote de la Iglesia que tiene un incensario de oro y mucho incienso, plenitud de mérito en su persona gloriosa.
Deseable fuera que los hombres quieran conocer la plenitud que hay en Cristo y se propusieran familiarizarse con su excelencia. Que ellos fueran verdaderamente persuadidos de que Cristo tiene el oficio de Intercesor, que ahora desempeña con profunda simpatía. A ninguna oración así recomendada, se le negó jamás el ser oída y aceptada. Estas oraciones, así aceptas en el cielo, produjeron grandes cambios en la tierra.
La adoración y la religión cristiana, puras y celestiales en origen y naturaleza, cuando son enviadas a la tierra y entran en conflicto con las pasiones y los proyectos mundanos de los hombres pecadores, producen notables tumultos, aquí expresados en lenguaje profético, como declaró nuestro Señor mismo, Lucas xii, 49.</p>
<br/>
<p class="text-justify">Vv. 7-13.El primer ángel tocó la primera trompeta y hubo granizo y fuego mezclado con sangre. Una tormenta de herejías, una mezcla de errores espantosos cayó sobre la iglesia o una tempestad de destrucción.
El segundo ángel tocó, y una gran montaña, ardiendo con fuego, fue echada al mar; y la tercera parte del mar se convirtió en sangre. Hay algunos que entienden que la montaña representa a los líderes de las persecuciones; otros, a Roma saqueada por los godos y los vándalos, con gran carnicería y crueldad.
El tercer ángel tocó, y cayó una estrella desde el cielo. Algunos consideran que esto es un gobernador eminente; otros, que es una persona con poder que corrompió a las iglesias de Cristo. Las doctrinas del evangelio, la fuente de la vida, del consuelo y del vigor espiritual para las almas de los hombres, están corrompidas y amargadas por la mezcla de errores peligrosos, de modo que las almas de los hombres encuentran ruina donde antes hallaban refrigerio.
El cuarto ángel tocó, y cayeron tinieblas sobre las grandes lumbreras del cielo que dan el mundo, al sol, a la luna y a las estrellas. Los líderes y los gobernantes están puestos más altos que la gente, y tienen que dispensar luz, y buenas influencias sobre ellos. Donde llega el evangelio a un pueblo, y no tiene los efectos apropiados sobre sus corazones y vidas, es seguido por terribles juicios. Dios da advertencias por la palabra escrita, por los ministros, por las propias conciencias de los hombres y por las señales de los tiempos; de modo que si la gente es sorprendida, es su propia falta. La ira de Dios amarga todos los beneficios y hasta la misma vida se vuelve una carga. Pero Dios, en este mundo, pone límites a los juicios más terribles. La corrupción de la doctrina y la adoración en la iglesia son grandes juicios, y también son las causas y señales habituales de otros juicios venideros para un pueblo.
Antes que se tocaran las otras tres trompetas, hubo una advertencia solemne de lo terrible que serían las calamidades que seguirían. Si los juicios menores no tienen efecto, la iglesia y el mundo deben esperar otros mayores; y cuando Dios viene a castigar al mundo, sus habitantes temblarán ante Él. Que los pecadores tomen las precauciones para huir de la ira venidera; que los creyentes aprendan a valorar y agradecer sus privilegios; y que continúen con paciencia haciendo el bien.</p>
<br/>




</div>
