<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 2</h2>
<p class="text-justify">Vv. 1-7.Estas iglesias estaban en tan diferentes estados de pureza de doctrina y poder de la piedad que las palabras de Cristo para ellas siempre vendrán bien al caso de otras iglesias y creyentes. Cristo conoce y observa el estado de ellas; aunque está en el cielo, de todos modos anda en medio de sus iglesias en la tierra, observando lo que está mal en ellas y qué les falta.
La iglesia de Éfeso es elogiada por la diligencia en el deber. Cristo lleva la cuenta de cada hora de trabajo que sus siervos hacen para Él, y su trabajo en el Señor no será en vano. Pero no es suficiente que seamos diligentes; debe haber paciencia para soportar, y debe haber paciencia para esperar. Aunque debemos mostrar toda mansedumbre a todos los hombres, sin embargo, debemos mostrar justo celo contra sus pecados. El pecado de que Cristo acusa a esta iglesia no es que hubiera dejado y abandonado al objeto de amor, sino que ha perdido el grado de fervor que al principio tuvo. Cristo está descontento con su pueblo cuando los ve ponerse remisos y fríos para con Él. Es seguro que esta mención en la Escritura, de los cristianos que abandonan su primer amor, es un reproche para los que hablan de esto con negligencia, y así, tratan de excusar la indiferencia y pereza en ellos mismos y en otros; nuestro Salvador considera pecaminosa esa indiferencia. Deben arrepentirse; deben dolerse y avergonzarse por su pecaminosa declinación y confesarla humildemente ante los ojos de Dios. Deben proponerse recuperar su primer celo, ternura y fervor y deben orar tan fervorosamente, y velar tan diligentemente, como cuando entraron al principio en los caminos de Dios. Si la presencia de la gracia y del Espíritu de Cristo es descuidada, podemos esperar la presencia de su desagrado. Se hace una mención alentadora de lo que era bueno en ellos. La indiferencia hacia la verdad y el error, hacia lo bueno y lo malo, puede llamarse caridad y mansedumbre, pero no es así, y desagrada a Cristo. La vida cristiana es una guerra contra el pecado, contra Satanás, el mundo y la carne. Nunca debemos ceder ante nuestros enemigos espirituales, y entonces, tendremos un glorioso triunfo y recompensa. Todos los que perseveren, recibirán de Cristo, como el Árbol de la vida, la perfección y la confirmación de la santidad y la felicidad, no en el paraíso terrenal, sino en el celestial.
Esto es una expresión figurada, tomada del relato del huerto de Edén, que significa los goces puros, satisfactorios y eternos del cielo; y la espera de ellos en este mundo, por fe, en comunión con Cristo y con las consolaciones del Espíritu Santo. Creyentes, tomad de aquí vuestra vida de lucha, y esperad y aguardad una vida tranquila en el más allá; pero no hasta entonces: la palabra de Dios nunca promete que aquí tendremos tranquilidad y libertad completa de los conflictos.</p>
<br/>
<p class="text-justify">Vv. 8-11.Nuestro Señor Jesús es el Primero, porque por Él fueron hechas todas las cosas; Él estaba con Dios antes de todas las cosas, y es Dios mismo. Él es el Último, porque será el Juez de todos.
Como Primero y Último, que estuvo muerto y vivió, es el Hermano y Amigo del creyente, debe ser rico en la pobreza más profunda, honorable en medio de la más profunda humillación, y feliz sometido a la más pesada tribulación, como la iglesia de Esmirna. Muchos de los ricos de este mundo, son pobres en cuanto al venidero; y algunos que son pobres por fuera, son ricos por dentro; ricos en fe, en buenas obras, ricos en privilegios, ricos en dones, ricos en esperanza. Donde hay abundancia espiritual, la pobreza externa puede soportarse bien; cuando el pueblo de Dios es empobrecido en cuanto a esta vida, por amor de Cristo y la buena conciencia, Él los compensa en todo con riquezas espirituales. Cristo arma contra las tribulaciones inminentes. No temáis nada de estas cosas; no sólo prohibáis el temor servil, sino sometedlo proporcionando al alma fortaleza y valor. Será para probarlos, no para destruirlos.
Nótese la certeza de la recompensa: “Te daré”; ellos tendrán la recompensa de la mano misma de Cristo. Además, cuán adecuada es: “la corona de la vida”; la vida gastada a su servicio o entregada a su causa, será recompensada con una vida mucho mejor, la que será eterna. La muerte segunda es indeciblemente peor que la primera, tanto en sus agonías como por ser eterna: indudablemente es espantoso morir y estar muriendo siempre. Si un hombre es librado de la segunda muerte y de la ira venidera, puede soportar con paciencia lo que encuentre en este mundo.</p>
<br/>
<p class="text-justify">Vv. 12-17.La palabra de Dios es una espada, capaz de cortar pecado y pecadores. Gira y corta por todas partes, pero el creyente no tiene que temer esta espada; aunque la confianza no puede recibir respaldo sin una obediencia constante. Como nuestro Señor nota todas las ventajas y oportunidades que tenemos para cumplir nuestro deber en los lugares donde habitamos, así nota nuestras tentaciones y desalientos por las mismas causas. En una situación de prueba, la iglesia de Pérgamo no negó la fe, ni por apostasía franca, ni por ceder a fin de evitar la cruz. Cristo elogia su firmeza, pero reprende sus faltas pecaminosas. Una visión equivocada de la doctrina del evangelio y de la libertad cristiana era la raíz de amargura de la cual surgieron malas costumbres. El arrepentimiento es el deber de las iglesias y cuerpos de hombres, y de las personas particulares: los que pecan juntos, deben arrepentirse juntos.
Aquí está la promesa de favor para los que venzan. Las influencias y las consolaciones del Espíritu de Cristo descienden desde el cielo al alma, para apoyarla. Esto está oculto del resto del mundo.
El nombre nuevo es el nombre de la adopción: cuando el Espíritu Santo muestra su obra en el alma del creyente, él comprende el nombre nuevo y su verdadera importancia.</p>
<br/>
<p class="text-justify">Vv. 18-29.Aunque el Señor conoce las obras de su pueblo, que son hechas en amor, fe, celo y paciencia, si sus ojos, que son como de fuego llameante, los ve cometiendo o permitiendo lo que es malo, los reprenderá, corregirá o castigará.
Aquí hay alabanza del ministerio y del pueblo de Tiatira de parte de Aquel que conocía los principios por los cuales ellos actuaban. Ellos se pusieron más sabios y mejores. Todos los cristianos deben desear fervientemente que sus últimas obras sean las mejores. Pero esta iglesia convivía con unos seductores malvados. Dios es conocido por los juicios que ejecuta; por esto, sobre los seductores, muestra su certero conocimiento de los corazones de los hombres, de sus principios, designios, disposición y temperamento. Se da aliento a los que se mantenían puros e incontaminados.
Peligroso es despreciar el misterio de Dios y tan peligroso como recibir los misterios de Satanás. Cuidémonos de las profundidades de Satanás, de las cuales los que menos las conocen son los más dichosos. ¡Qué tierno es Cristo con sus siervos fieles! Él no pone carga sobre sus siervos sino lo que es para su bien. Hay una promesa de amplia recompensa para el creyente perseverante y victorioso; también, conocimiento y sabiduría apropiados para su poder y dominio. Cristo trae consigo al alma el día, la luz de la gracia y la gloria en su presencia y su gozo, su Señor y Salvador. Después de cada victoria sigamos con nuestra ventaja contra el enemigo para que podamos vencer y mantener las obras de Cristo hasta el final.</p>
<br/>




</div>
