<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Apocalipsis 5</h2>
<p class="text-justify">Vv. 1-7.El apóstol vio en la mano del que estaba sentado en el trono un rollo de pergaminos, de la forma habitual de aquellos tiempos, y sellado con siete sellos. Representaba los propósitos secretos de Dios que iban a ser revelados. Los designios y los métodos de la providencia divina para la Iglesia y el mundo están establecidos, determinados y quedan por escrito. Los consejos de Dios están por entero ocultos de los ojos y del entendimiento de la criatura. No se quita el sello ni se abren de inmediato las diversas partes del rollo, sino una parte después de la otra, hasta que todo el misterio del consejo y conducta de Dios esté consumado en el mundo.
Las criaturas no pueden abrirlo ni leerlo; sólo el Señor puede hacerlo. Los que más ven de Dios desean ver más; y los que han visto su gloria desean conocer su voluntad. Pero hasta los hombres buenos pueden estar demasiado anhelantes y apresurados por escudriñar los misterios de la conducta divina. Tales deseos se convierten en lamento y pesar si no son contestados pronto.
Si Juan lloró mucho porque no podía leer el libro de los decretos de Dios, ¡cuánta razón tienen muchos para derramar ríos de lágrimas por su ignorancia del evangelio de Cristo del cual depende la salvación eterna! -Nosotros no tenemos que llorar por no poder prever sucesos futuros acerca de nosotros en este mundo; la ansiosa expectativa de las perspectivas futuras o la previsión de calamidades venideras nos haría, por igual, ineptos para nuestros deberes y conflictos presentes o volverían inquietantes nuestros días de prosperidad. Pero podemos desear saber, por las promesas y profecías de la Escritura, cuál será el suceso final para los creyentes y para la Iglesia; que el Hijo encarnado ha prevalecido para que aprendamos todo lo que necesitamos saber.
Cristo está como Mediador entre Dios y los ministros y el pueblo. Se le llama León, pero aparece como Cordero inmolado. Aparece con las marcas de sus sufrimientos para mostrar que intercede por nosotros en el cielo en virtud de la satisfacción que hizo. Aparece como Cordero, con siete cuernos y siete ojos: el poder perfecto para ejecutar toda la voluntad de Dios, y la sabiduría perfecta para entenderla y hacerla en la manera más eficaz. El Padre puso el libro de sus eternos consejos en la mano de Cristo y Cristo lo tomó, rápida y alegremente, en su mano: porque se deleita en dar a conocer la voluntad de su Padre; y Él da el Espíritu Santo para revelar la verdad y la voluntad de Dios.</p>
<br/>
<p class="text-justify">Vv. 8-14.Es tema de gozo para todo el mundo ver que Dios trata con los hombres con gracia y misericordia por medio del Redentor. Él gobierna el mundo, no sólo como Creador, sino como nuestro Salvador. Las arpas eran instrumentos de alabanza; los vasos estaban llenos de perfume o incienso, que representan las oraciones de los santos: la alabanza y la oración siempre deben ir juntas. Cristo ha redimido a su pueblo de la esclavitud del pecado, de la culpa y de Satanás. No sólo ha comprado libertad para ellos sino la honra y la más alta preferencia; los ha hecho reyes y sacerdotes; reyes, para que reinen sobre sus propios espíritus y para vencer al mundo y al maligno; y los hace sacerdotes dándoles acceso a Él mismo, y libertad para ofrecer sacrificios espirituales. -¡Qué palabras podrían declarar más plenamente que Cristo es, y debe ser, adorado igualmente con el Padre por todas las criaturas por toda la eternidad! Dichosos los que adorarán y alabarán en el cielo, y que por siempre bendecirán al Cordero que los libró y los apartó para sí por su sangre. ¡Cuán digno eres tú, oh Dios, Padre, Hijo y Espíritu Santo, de nuestras alabanzas más excelsas! Todas las criaturas deben proclamar tu grandeza y adorar tu majestad.</p>
<br/>




</div>
