<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Cantares 1</h2>
<p class="text-justify">V. 1.Este es “El Cantar de los Cantares”excelente por sobre todos los demás, porque está totalmente dedicado a describir las excelencias de Cristo y su amor con su pueblo redimido.</p>
<br/>
<p class="text-justify">Vv. 2-6.La Iglesia o, más bien el creyente, habla aquí en su carácter de esposa del Rey, el Mesías.
Los besos de su boca significan la seguridad del perdón con que son favorecidos los creyentes, llenándolos de paz y gozo, al creer, y haciendo que abunden en esperanza por el poder del Espíritu Santo.
Las almas en gracia se complacen hasta lo sumo en amar a Cristo y ser amadas por Él. El amor de Cristo es más valioso y deseable que lo mejor que este mundo puede dar. El nombre de Cristo no es ahora como ungüento sellado, sino como ungüento derramado, lo cual denota la libertad y plenitud del establecimiento de su gracia por el evangelio.
Los que Él ha redimido y santificado son aquí las vírgenes que aman a Jesucristo, y le siguen donde Él vaya, Apocalipsis xiv, 4. Ellos le piden que los guíe por la influencia vivificante de Su Espíritu. Mientras más claramente discernimos la gloria de Cristo, más conscientes estamos de que somos incapaces de seguirle adecuadamente y, al mismo tiempo, estamos más deseosos de hacerlo.
Obsérvese la respuesta pronta dada a esta oración. Quienes esperan en la puerta de la Sabiduría, serán guiados en la verdad y el consuelo. Llevados a esta recámara, se desvanecerán nuestros pesares. No tenemos gozo sino en Cristo y por esto estamos en deuda con Él. Nos acordaremos dar gracias por tu amor; nos causará impresiones más duraderas que cualquier otra cosa de este mundo. No es aceptable el amor a Cristo si no es amor sincero, Efesios vi, 24.
Las hijas de Jerusalén pueden ser profesantes aún no firmes en la fe. La esposa era negra, como las tiendas de los árabes nómadas, pero bella como las cortinas magníficas de los palacios de Salomón. El creyente es negro, por contaminación y pecador por naturaleza, pero bello al ser renovado por la gracia divina en la santa imagen de Dios. Está aún deformado con residuos de pecado, pero bello por ser aceptado en Cristo. A menudo es bajo y despreciable para la estimación de los hombres, pero excelente a ojos de Dios. La negrura se debía al duro trato sufrido. Los hijos de la Iglesia, su madre, pero no de Dios, su Padre, estaban enojados con ella. Ellos la habían hecho sufrir cosas duras que hicieron que ella dejara el cuidado de su alma. Así, pues, bajo el emblema de una pobre mujer, hecha cónyuge escogida de un príncipe, somos llevados a considerar las circunstancias en que Cristo acostumbra a hallar a los objetos de su amor. Eran miserables esclavos del pecado, en trabajos forzados, afligidos, agotados y muy cargados, pero ¡qué grande el cambio cuando el amor de Cristo se manifiesta a sus almas!</p>
<br/>
<p class="text-justify">Vv. 7, 8.Obsérvese el título dado a Cristo: Oh, tú, a quien ama mi alma. Quienes así dicen, pueden ir directamente a Él, y pueden presentarle humildemente su alegato. ¿Hay en el pueblo de Dios un medio día de problemas externos, y conflictos internos? Cristo tiene reposo para ellos. Aquellos cuyas almas aman a Jesucristo, desean fervorosamente compartir los privilegios de su rebaño. Apartarse de Cristo es lo que temen las almas en la gracia más que cualquier otra cosa.
Dios está listo para responder la oración. Sigue el camino, pregunta por el antiguo buen camino, observa las huellas del rebaño, mira lo que ha sido la costumbre del pueblo santo. Siéntate bajo la dirección de buenos ministros; al lado de las tiendas de los pastores. Lleva tu carga a ellos, ellos te darán la bienvenida. Será el deseo y oración ferviente del cristiano que Dios lo dirija así en sus negocios mundanos y que así ordene su situación y ocupación para que él pueda tener a su Señor y Salvador siempre delante de él.</p>
<br/>
<p class="text-justify">Vv. 9-17.El Esposo elogia con altura a su esposa. A la vista de Cristo, los creyentes son lo excelente de la tierra, aptos instrumentos para fomentar su gloria. Los dones y las gracias espirituales que Cristo otorga a todo creyente verdadero, son descritos por los ornamentos entonces en uso, versículos 10, 11.
Las gracias de los santos son muchas, pero dependen unas de otras. Aquel que es el Autor será el Consumador de la buena obra. La gracia recibida de la plenitud de Cristo brota como ejercicio vivo de la fe, el afecto y la gratitud. Pero Cristo, no sus dones, es más precioso para ellos. La palabra traducida “alheña”significa “expiación”o “propiciación”. Cristo es caro para todos los creyentes, porque Él es la propiciación de sus pecados. Ningún pretendiente debe ocupar el lugar de Él en el alma. Ellos resolvieron alojarlo en su corazón toda la noche; durante la continuación de los problemas de la vida.
Cristo se deleita en la buena obra que su gracia ha llevado al alma de los creyentes. Esto debiera comprometer a todos los que son hechos santos para estar muy agradecidos por la gracia que ha hecho justos a quienes, por naturaleza, eran deformes. La esposa (el creyente) tiene ojo humilde y modesto, que descubre la sencillez y la piadosa sinceridad; ojos iluminados y guiados por el Espíritu Santo, esa tórtola bendita. La Iglesia expresa su valor por Cristo. Tú eres el gran Original, pero yo no soy sino una mala copia imperfecta. Muchos son lindos de mirar, pero sus temperamentos los vuelven desagradables; pero Cristo es bello y agradable. El creyente, versículo 16, habla alabando las ordenanzas santas en que los creyentes verdaderos tienen comunión con Cristo. Sea que el creyente esté en los atrios del Señor o en el retiro; sea que esté en sus labores diarias o confinado en el lecho de enfermo o aun en un calabozo, el sentido de la presencia divina convertirá el lugar en un paraíso. Así, pues, el alma, teniendo comunión diaria con el Padre, el Hijo y el Espíritu Santo, disfruta de una esperanza viva de una herencia incorruptible, inmarcesible y eterna, arriba.</p>
<br/>




</div>
