<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Cantares 2</h2>
<p class="text-justify">Vv. 1-7.Los creyentes son hermosos porque están vestidos de la justicia de Cristo; y fragantes, por estar adornados con las gracias de su Espíritu; ellos florecen bajo los refrescantes rayos del Sol de justicia.
El lirio es una planta muy noble en el Oriente; crece a considerable altura, pero tiene un tallo débil. La Iglesia en sí misma es débil, pero es fuerte en el que la sostiene. Las malas, las hijas de este mundo que no tienen amor por Cristo, son como espinas, sin valor e inútiles, nocivas y dañinas. Las corrupciones son espinas en la carne, pero el lirio que está ahora entre espinas, será trasplantado a aquel paraíso donde no hay malezas ni espinas.
El mundo es un árbol estéril para el alma, pero Cristo es el fructífero. Cuando las pobres almas están resecas bajo la convicción de pecado, con los terrores de la ley, o los problemas de este mundo, cansados y muy cargados, deben encontrar reposo en Cristo. No es suficiente pasar bajo su sombra sino que debemos sentarnos bajo ella. Los creyentes han gustado que el Señor Jesús es bueno; sus frutos son todos los preciosos privilegios del nuevo pacto comprados por su sangre, y comunicados por su Espíritu; promesas dulces para el creyente, y también los preceptos. Los perdones son dulces y la paz de conciencia, dulce. Si nuestras bocas están amargas por los placeres del pecado, los consuelos divinos nos serán dulces.
Cristo lleva al alma a que busque y halle consuelo por medio de sus ordenanzas, que son como una casa de banquete donde sus santos festejan con Él. El amor de Cristo, manifestado por su muerte y por su palabra, es la bandera que Él despliega, y los creyentes recurren a Él. -¡Cuánto mejor es para el alma estar enferma de amor por Cristo que cuando está saciada con el amor de este mundo! Aunque Cristo parecía haberse retirado, aún era una ayuda muy presente. Todos sus santos están en su mano, que tiernamente sostiene sus cabezas doloridas. Encontrando a Cristo así de cerca a ella, el alma se cuida mucho de que su comunión con Él sea interrumpida. Contristamos fácilmente al Espíritu con los malos temperamentos. Los que tienen consuelo, teman pecar y perderlo.</p>
<br/>
<p class="text-justify">Vv. 8-13.La iglesia se complace con pensamientos de ulterior comunión con Cristo. Nada fuera de eso puede hablar al corazón. Ella lo ve venir. Esto puede aplicarse a la perspectiva que los santos del Antiguo Testamento tenían de la encarnación de Cristo. Viene como complacido con su comisión. Viene rápidamente. Aun cuando Cristo parece abandonar, no es sino por un momento; pronto retornará con benignidad eterna.
Los santos de antes lo vieron apareciendo a través de los sacrificios y las instituciones ceremoniales. Nosotros lo vemos como a través de un vidrio en oscuridad, como se manifiesta a través de un enrejado.
Cristo invita al nuevo convertido a que se levante de la pereza y la depresión, y abandone al pecado y las vanidades mundanas, para unirse a Él y tener comunión con Él. El invierno puede representar muchos años malos, pasados en la ignorancia y el pecado, infértiles y miserables, o tormentas y tempestades que acompañaron su convicción de culpa y peligro.
Hasta las frutas verdes de la santidad son agradables para Aquel cuyo favor divino las ha producido. Todas estas alentadoras prendas y pruebas del favor divino son motivos para que el alma siga más plenamente a Cristo. Levántate, entonces, y aléjate del mundo y la carne, ven a la comunión con Cristo. Este cambio bendito se debe totalmente a los acercamientos e influencias del Sol de justicia.</p>
<br/>
<p class="text-justify">Vv. 14-17.La Iglesia es la paloma de Cristo; ella regresa a Él, como a su Noé. Cristo es la Roca, el único en quien ella puede sentirse a salvo y encontrarse segura, como tórtola en el agujero de una roca, cuando es atacada por las aves de presa. Cristo la llama que venga directamente al trono de la gracia, teniendo ahí un gran Sumo Sacerdote, para decir cuál es su petición. Habla libremente. No temas al rechazo ni el desprecio. La voz de la oración es dulce y aceptable para Dios; aquellos que son santificados tienen la mejor belleza.
Los primeros albores de pensamiento y deseos pecaminosos, los comienzos de búsquedas fútiles que desperdician el tiempo, las visitas triviales, los pequeños desvíos de la verdad, lo que sea que admita algo de conformidad con el mundo, todos estos, y muchos más son zorras pequeñas que destruyen sus gracias y consuelos, y aplastan los buenos comienzos. Lo que encontremos sea un estorbo para nosotros en lo que es bueno, debemos hacerlo a un lado. -Él se alimentó entre los lirios; esto muestra la graciosa presencia de Cristo entre los creyentes. Él es amable con todo Su pueblo. Les corresponde creer esto, cuando están abandonados y ausentes, para poder rechazar las tentaciones.
Las sombras de la dispensación judía fueron disipadas por el alba del día del evangelio. Y un día de consuelo vendrá después de una noche de abandono. Sube los montes de Beter, “los montes que dividen”, esperando por ese día de luz y amor. Cristo vendrá sobre cada monte divisorio para llevarnos a casa a Él mismo.</p>
<br/>




</div>
