<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Cantares 8</h2>
<p class="text-justify">Vv. 1-4.La Iglesia desea la intimidad y libertad constantes con el Señor Jesús que una hermana tiene con un hermano. Que sean como sus hermanos, que los son, cuando por gracia son hechos partícipes de la naturaleza divina. Cristo llega a ser como nuestro hermano; donde lo hallemos, estemos preparados para reconocer nuestra relación con Él, y nuestro afecto por Él, y no temamos ser despreciados por eso. ¿Hay en nosotros un deseo ardiente de servir más y mejor a Cristo? Entonces, ¿qué hemos almacenado para mostrar nuestro afecto por el Amado de nuestra alma? ¿Qué fruto de santidad? -La Iglesia encarga a todos sus hijos que nunca provoquen a Cristo a retirarse. Debemos razonar con nosotros mismos, cuando estamos tentados a hacer lo que contristaría al Espíritu.</p>
<br/>
<p class="text-justify">Vv. 5-7.La Iglesia judía salió del desierto sostenida por el poder y el favor divinos. La Iglesia cristiana fue sacada de un estado bajo y desolado apoyada por la gracia de Cristo. Los creyentes son sacados del desierto por el poder de la gracia. El estado pecador es un desierto en que no hay bienestar verdadero; es un estado menesteroso y vagabundo; no hay salida de este desierto sino apoyarse en Cristo como Amado nuestro, por fe; no apoyándonos en nuestro propio entendimiento, no confiando en ninguna justicia propia sino en el poder de Aquel que es el Señor nuestra justicia.
Las palabras de la Iglesia a Cristo que siguen, construyen un lugar permanente en su amor, y de protección por su poder. Ponme como un sello sobre tu corazón; déjame tener siempre un lugar en tu corazón; déjame poner la impronta de amor en tu corazón. El alma será asegurada de esto y sin esto no se halla reposo. Los que aman verdaderamente a Cristo son celosos de todo lo que lo aleje de ellos; especialmente de ellos mismos no sea que hagan algo que lo provoque a retirarse de ellos. Si amamos a Cristo, el temor de perder su amor o las tentaciones de abandonarlo serán sumamente penosas para nosotros. No hay agua que pueda sofocar el amor de Cristo por nosotros, ni anegación que lo ahogue. Que nada abata nuestro amor por Él. Ni la vida ni todos sus bienestares incitan al creyente para que deje de amar a Cristo. El amor de Cristo nos capacita para rechazar y vencer las tentaciones de las sonrisas del mundo, como asimismo de sus ceños fruncidos.</p>
<br/>
<p class="text-justify">Vv. 8-12.La Iglesia ruega por los gentiles que entonces no tenían la palabra de Dios ni los medios de gracia. Quienes son llevados a Cristo debieran concebir lo que pueden hacer para ayudar al prójimo a ir a Él. Siempre hay bebés en Cristo entre los cristianos, y el bienestar de sus hermanos débiles es objeto de oración continua de los creyentes fuertes. Si los comienzos de esta obra se comparan a una pared edificada sobre Él como Fundamento precioso y piedra angular, entonces la Iglesia gentil llegaría a ser como un palacio para el gran Rey, edificado de plata maciza. Si la primera predicación del evangelio fuera como abrir una puerta en el muro divisorio, esa puerta sería duradera, como hecha de tablas de cedro. Ella estaría cuidadosa y eficazmente protegida, cercada como para no ser dañada. La Iglesia está llena de cuidado por los aún no llamados. Cristo dice: Yo haré todo lo que es necesario hacer por ellos.
Véase con cuánta satisfacción nosotros debemos mirar atrás, a las épocas y temporadas en que a sus ojos éramos como los que encuentra favor; nuestros corazones son los viñedos que debemos mantener con toda diligencia. Todos nuestros frutos deben ser dedicados a Cristo y a su alabanza. Toda esa obra por Cristo, obra en favor de ellos mismos, y serán ganadores indecibles por ella.</p>
<br/>
<p class="text-justify">Vv. 13, 14.Estos versículos cierran la conferencia entre Cristo y su Iglesia. Él se dirige primero a ella, como que habita en los jardines, las asambleas y ordenanzas de sus santos. Él la exhorta a ser constante y frecuente en oración, súplica, y alabanzas, en lo cual Él se complace. Ella contesta, anhelando su pronto retorno para que la lleve a estar totalmente con Él. Los cielos, los elevados montes de dulces especias, deben contener a Cristo hasta que llegue el tiempo cuando todo ojo lo verá en toda la gloria del mundo mejor. Los creyentes verdaderos, como ellos andan buscando, así apresuran la venida del día del Señor. Que todo cristiano se proponga cumplir los deberes de su posición para que los hombres vean sus buenas obras y glorifiquen a su Padre celestial. Al seguir fervientes orando por lo que nos falta, abundará nuestra acción de gracias y nuestro gozo será completo; nuestras almas serán enriquecidas y prosperadas nuestras labores. Seremos capacitados para esperar la muerte y el juicio sin temer. Hasta entonces, ven, Señor Jesús</p>
<br/>




</div>
