<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Colosenses 1</h2>
<p class="text-justify">Vv. 1-8.Todos los cristianos verdaderos son hermanos entre sí. La fidelidad va en todo aspecto y relación de la vida cristiana.
La fe, la esperanza, y el amor son las tres virtudes principales de la vida cristiana, y el tema apropiado para orar y dar gracias. Mientras más fijamos nuestras esperanzas en la recompensa del otro mundo, más libres estaremos para hacer el bien con nuestro tesoro terrenal. Estaba reservado para ellos ; ningún enemigo podía quitárselos.
El evangelio es la palabra de verdad y podemos arriesgar nuestras almas sobre esta base, con la seguridad de un buen resultado. Todos los que oyen la palabra del evangelio, deben dar el fruto del evangelio, obedecerla y tener sus principios y vidas formados conforme a ello. El amor al mundo surge de puntos de vista interesados, o de similitud en modales; el amor carnal surge del apetito de placeres. A estos siempre se aferra algo corrupto, egoísta y bajo. Pero el amor cristiano surge del Espíritu Santo y está lleno de santidad.</p>
<br/>
<p class="text-justify">Vv. 9-14.El apóstol era constante para orar que los creyentes fueran llenos del conocimiento de la voluntad de Dios con toda sabiduría. Las buenas palabras no sirven sin buenas obras. El que emprende el fortalecimiento de su pueblo es un Dios de poder, y de poder glorioso. El bendito Espíritu es el autor de esto. Al orar por fuerza espiritual, no somos presionados ni confinados en las promesas, y no debemos serlo en nuestras esperanzas y deseos. La gracia de Dios en los corazones de los creyentes es el poder de Dios y hay gloria en este poder. El uso especial de esta fuerza era para los sufrimientos. Hay obra que realizar aunque estemos sufriendo.
En medio de todas sus tribulaciones ellos daban gracias al Padre de nuestro Señor Jesucristo cuya gracia especial los preparaba para participar de la herencia provista para los santos. Para ejecutar este cambio fueron hechos súbditos de Cristo, los que eran esclavos de Satanás. Todos los que están destinados para el cielo en el más allá, están preparados ya para el cielo. Los que tienen la herencia de hijos tienen la educación de hijos, y la disposición de hijos. Por fe en Cristo disfrutan esta redención, como la compra de su sangre expiatoria mediante la cual se otorgan el perdón de los pecados y todas las demás bendiciones. Seguramente entonces consideraremos un favor el ser liberados del reino de Satanás y llevados al de Cristo, sabiendo que todas las tribulaciones terminarán pronto y que cada creyente será contado entre los salidos de la gran tribulación.</p>
<br/>
<p class="text-justify">Vv. 15-23.Cristo en su naturaleza humana es la revelación visible del Dios invisible y quien le ha visto a Él ha visto al Padre. Adoremos estos misterios con fe humilde y contemplemos la gloria de Jehová en Cristo Jesús. Nació o fue engendrado antes de toda la creación, antes que fuera hecha la primera criatura; este el modo de la Escritura de representar la eternidad, y por el cual la eternidad de Dios nos es representada. Siendo todas las cosas creadas por Él, fueron creadas para Él; siendo hechas por su poder, fueron hechas conforme a su beneplácito y para alabanza de su gloria. No sólo las creó todas al principio; por la palabra de su poder las sustenta.
Cristo como Mediador es la Cabeza del cuerpo, la Iglesia; toda gracia y fuerza son de Él; y la Iglesia es su cuerpo. Toda plenitud habita en Él; la plenitud de mérito y justicia, de fuerza y gracia para nosotros. Dios mostró su justicia al requerir plena satisfacción. Este modo de redimir a la humanidad por la muerte de Cristo fue el más apto. Aquí se presenta ante nuestra visión el método de ser reconciliado. Pese al odio hacia el pecado por parte de Dios, plugo a Dios reconciliar consigo al hombre caído. Si estamos convencidos en nuestra mente de que éramos enemigos por las malas obras, y que ahora estamos reconciliados a Dios por el sacrificio y muerte de Cristo según nuestra naturaleza, no intentaremos explicar ni siquiera pensar en comprender plenamente estos misterios, pero veremos la gloria de este plan de redención y nos regocijaremos en la esperanza que nos es puesta por delante. Si el amor de Dios por nosotros es tan grande, ¿ahora qué podemos hacer por Dios? Orar con frecuencia y abundar en los deberes santos y no vivir más para sí mismo, sino para Cristo, el que murió por nosotros. Pero, ¿para qué? ¿para que sigamos viviendo en el pecado? No, sino para que muramos al pecado y vivamos entonces no para nosotros sino para Él.</p>
<br/>
<p class="text-justify">Vv. 24-29.Los sufrimientos de la Cabeza y de los miembros son llamados sufrimientos de Cristo, y hechos, como si lo fueran, un cuerpo de sufrimientos. Pero Él sufrió por la redención de la Iglesia; nosotros sufrimos por otras cosas, porque sólo saboreamos ligeramente esa copa de aflicciones que Cristo bebió primero hasta las heces. Puede decirse que el cristiano cumple lo que falta de los sufrimientos de Cristo cuando toma su cruz, y según la pauta de Cristo, sufre pacientemente las aflicciones que Dios le asigna.
Seamos agradecidos que Dios nos haya dado a conocer los misterios ocultos por edades y generaciones y haya mostrado las riquezas de su gloria entre nosotros. Al predicarse a Cristo entre nosotros preguntemos honestamente si Él habita y reina en nosotros; porque sólo esto puede garantizar nuestra esperanza de su gloria. Debemos ser fieles hasta la muerte en medio de todas las pruebas para recibir la corona de vida y alcanzar la meta de nuestra fe: la salvación de nuestras almas.</p>
<br/>




</div>
