<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Colosenses 2</h2>
<p class="text-justify">Vv. 1-7.El alma prospera cuando conocemos claramente la verdad en Jesús. Entonces creemos no sólo con el corazón, sino que estamos dispuestos a confesar con la boca cuando se nos pida. El conocimiento y la fe enriquecen el alma. Mientras más fuerte es nuestra fe, y más cálido nuestro amor, más grande será nuestro consuelo. Los tesoros de la sabiduría están ocultos, no de nosotros, sino para nosotros en Cristo. Fueron escondidos de los incrédulos orgullosos, pero exhibidos en la persona y la redención de Cristo.
Nótese el peligro de las palabras persuasivas: ¡cuántos se destruyen con los disfraces falsos y las bellas apariencias de principios malos y de las prácticas impías! Estad vigilantes y temed a los que desean seducir para cualquier mal, porque su propósito es corromperos. Todos los cristianos han recibido al Señor Jesucristo; al menos por profesión le aceptaron y le tomaron como suyo. No podemos edificar ni crecer en Cristo si primero, no estamos arraigados o fundamentados en Él. Estando afirmados en la fe podemos abundar y mejorar más y más en ella. Dios quita con justicia este beneficio a quienes no lo reciben con acción de gracias; con justicia, Dios requiere gratitud por sus misericordias.</p>
<br/>
<p class="text-justify">Vv. 8-17.Hay una filosofía que ejercita correctamente nuestras facultades de raciocinio: el estudio de las obras de Dios, que nos lleva al conocimiento de Dios y confirma nuestra fe en Él. Pero hay una filosofía que es vana y engañosa; y aunque complace las fantasías de los hombres, obstaculiza la fe de ellos: tales son las especulaciones curiosas sobre cosas que no trascienden o no nos interesan. Los que van por el camino del mundo se han apartado de seguir a Cristo. En Él tenemos la sustancia de todas las sombras de la ley ceremonial. Todos los defectos de la ley están compensados en el evangelio de Cristo por su sacrificio completo por el pecado, y por la revelación de la voluntad de Dios. Ser completo es estar equipado con todas las cosas necesarias para la salvación. Por esta sola palabra, “completo”se indica que tenemos todo lo requerido en Cristo. “En Él”, no cuando miramos a Cristo como si estuviese lejos de nosotros, sino cuando tenemos a Cristo habitando y permaneciendo en nosotros. Cristo está en nosotros y nosotros en Él cuando por el poder del Espíritu, la fe obra en nuestros corazones por el Espíritu y somos unidos a nuestra Cabeza. La circuncisión del corazón, la crucifixión de la carne, la muerte y sepultación al pecado y al mundo, y la resurrección a la novedad de vida, simbolizadas en el bautismo, y por fe obrada en nuestros corazones, demuestran que nuestros pecados han sido perdonados, y que estamos completamente liberados de la maldición de la ley.
Por medio de Cristo somos resucitados los que estábamos muertos en el pecado. La muerte de Cristo fue la muerte de nuestros pecados; la resurrección de Cristo es la vivificación de nuestras almas. Cristo sacó del camino la ley de las ordenanzas que fue yugo para los judíos, y muro de separación para los gentiles. Las sombras huyeron cuando la sustancia se hizo presente. Como todo mortal es culpable de muerte, por lo escrito en la ley, ¡qué espantosa es la situación de los impíos réprobos que pisotean la sangre del Hijo de Dios, que es lo único con que puede borrarse esta sentencia! Que nadie se perturbe con los juicios fanáticos relacionados a la carne o a las solemnidades judías. Apartar un tiempo para adorar y servir a Dios es un deber ineludible que no depende necesariamente del séptimo día de la semana, el día de reposo de los judíos. El primer día de la semana o el día del Señor es el tiempo que los cristianos guardan santo en memoria de la resurrección de Cristo. Todos los ritos judaicos eran sombra de las bendiciones del evangelio.</p>
<br/>
<p class="text-justify">Vv. 18-23.Parecía humildad recurrir a los ángeles, como si los hombres tuviesen conciencia de su indignidad para hablar directamente a Dios, pero eso no tiene respaldo, porque toma la honra debida sólo a Cristo y se la confiere a la criatura. En esta humildad aparente había un verdadero orgullo. Los que adoran ángeles desconocen a Cristo que es el único Mediador entre Dios y el hombre. Recurrir a otros mediadores fuera de Cristo es un insulto para Él, que es la Cabeza de la Iglesia. Cuando los hombres se apartan de Cristo, se asen de eso que no les sirve.
El cuerpo de Cristo es un cuerpo que crece. Los creyentes verdaderos no pueden vivir según las modas del mundo. La sabiduría verdadera es mantenerse apegado a los designios del evangelio: por entero sometidos a Cristo que es la única Cabeza de su Iglesia. Los sufrimientos y los ayunos impuestos a uno mismo pueden dar el espectáculo de rara espiritualidad y voluntad de sufrir, pero no son “ningún honor”para Dios. Todo tendía, erróneamente, a satisfacer la mente carnal gratificando la voluntad propia, la sabiduría propia, la justicia propia y despreciando al prójimo. Siendo las cosas como son, no tienen en sí mismas sólo la apariencia de la sabiduría o son una simulación tan débil que no le hacen bien al alma, ni proveen para la satisfacción de la carne. Lo que el Señor ha determninado que sea indiferente, considerémolo como tal, y permitamos una libertad semejante al prójimo; recordando la naturaleza pasajera de las cosas terrenales, procuremos glorificar a Dios al usarlas.</p>
<br/>




</div>
