<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Daniel 12</h2>
<p class="text-justify">Vv. 1-4.Miguel significa “Él que es como Dios”y su nombre, con el título de “El gran príncipe”apunta al divino Salvador. Cristo se puso como sacrificio en lugar de los hijos de nuestro pueblo, llevó la maldición por ellos y la sacó de ellos. Él está a favor de ellos rogando por ellos ante el trono de gracia. Y después de la destrucción del anticristo, el Señor Jesús volverá a la tierra en el último día; y Él se manifestará para la redención completa de su pueblo. Cuando Dios obra en favor de ellos la liberación de la persecución, es como la vida de entre los muertos. Cuando su evangelio se predica, muchos de los que duermen en el polvo, judíos y gentiles, serán despertados de su paganismo o judaísmo. Y al final, despertará la multitud que duerme en el polvo; muchos serán levantados para vida eterna y muchos para vergüenza.
Hay gloria reservada para todos los santos en el estado futuro, para todos los que son sabios, sabios para sus almas y para la eternidad. Los que llevaron a muchos a la justicia, que volvieron a los pecadores de los errores de sus caminos, y ayudaron a salvar sus almas de la muerte, Santiago v, 20, participarán de la gloria de quienes ellos ayudaron a ir al cielo, lo que se sumará a su propia gloria.</p>
<br/>
<p class="text-justify">Vv. 5-13.Uno de los ángeles pregunta cuán largo será el tiempo que resta hasta el fin de estos prodigios; se da una respuesta solemne de que será por un tiempo, tiempos y la mitad de un tiempo, el período mencionado en el capítulo vii, 25, y en el Apocalipsis. Significa 1260 días o años proféticos, empezando desde el tiempo en que el poder del pueblo santo sea diseminado. La impostura de Mahoma y la usurpación papal empezaron casi al mismo tiempo, y estos fueron un ataque doble contra la Iglesia de Dios. Pero todo terminará bien al final. Todo rey, principado y potestad contrario será derribado y triunfarán la santidad y el amor, y serán con honor y para la eternidad. El final, este final, llegará. ¡Qué asombrosa profecía es esta, de tantos hechos variados, y extendiéndose a través de tantas épocas sucesivas, hasta la resurrección general! -Daniel debe de haberse consolado con la perspectiva halagüeña de su propia dicha en la muerte, en el juicio, y para la eternidad. Bueno es para todos nosotros que pensemos mucho en irnos de este mundo. Ese debe ser nuestro camino, pero nuestro consuelo es que no nos vamos sino hasta que Dios nos llame al otro mundo, y hasta que Él haya terminado con nosotros en este mundo; hasta que diga: Ve por tu camino, tú que has hecho tu obra, por tanto, ahora, ve por tu camino y deja que otros tomen tu lugar. Fue un consuelo para Daniel, y es un consuelo para todos los santos que cualquiera sea su suerte en los días de su vida, tendrán una suerte feliz al final de los días. Debe ser el más grande interés y preocupación de cada uno de nosotros asegurarse esto. Entonces, podemos estar muy contentos con nuestra suerte actual, y acoger la voluntad de Dios. Los creyentes son felices en todo momento; ellos reposan en Dios por fe ahora, y les está reservado el reposo en el cielo, al final.</p>
<br/>




</div>
