<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Deuteronomio 2</h2>
<p class="text-justify">Vv. 1-7.Sólo se da un breve relato de la larga permanencia de Israel en el desierto. Dios no sólo los castigó por su murmuración e incredulidad; también los preparó para Canaán: Los humilló por pecar, enseñándoles a mortificar sus lujurias, a seguir a Dios y consolarse en Él. Aunque Israel tenga que estar por mucho tiempo a la espera de liberación y prosperidad, ellas al fin llegarán.
Antes que Dios llevara a Israel a destruir a sus enemigos en Canaán, les enseñó a perdonar a sus enemigos en Edom. No debían pensar, bajo el pretexto del pacto y conducta de Dios, en apropiarse de todo cuanto pudieran echar mano. El dominio no se funda en la gracia. El Israel de Dios será bien puesto, pero no debe esperar ser puesto solo en medio de la tierra. La religión nunca debe ser un manto para la injusticia.
Desdeñad el sentiros obligados con los edomitas, cuando tenéis un Dios todo suficiente del cual dependéis. Usad lo que tengáis, usadlo con alegría. Puesto que habéis tenido la experiencia del cuidado de la providencia divina, nunca uséis métodos retorcidos para vuestro abastecimiento. Todo esto ha de aplicarse por igual a la experiencia del creyente.</p>
<br/>
<p class="text-justify">Vv. 8-23.Tenemos el origen de los moabitas, edomitas y amonitas. Moisés también proporciona un caso más antiguo que cualquiera de ellos: los caftoreos echaron a los aveos de su territorio. Estas revoluciones muestran cuán inseguras son las pertenencias mundanas. Así fue antaño y así será siempre. Las familias declinan y su fortuna se trasladan a familias que prosperan; tan poca continuidad hay en esas cosas. Esto queda escrito para animar a los hijos de Israel. Si la providencia de Dios ha hecho esto por moabitas y amonitas, mucho más hará su promesa por Israel, su pueblo peculiar. Se les advierte que no se metan con los moabitas ni amonitas. No se debe hacer daño ni siquiera a los impíos. Dios da y preserva las bendiciones externas para los impíos; estas no son las cosas mejores, pues Él tiene cosas mejores aún reservadas para sus hijos.</p>
<br/>
<p class="text-justify">Vv. 24-37.Dios prueba a su pueblo prohibiéndoles entrometerse con los ricos países de Moab y Amón. Les da la tierra de los amorreos como posesión. Si nosotros nos abstenemos de los que Dios prohíbe, no perderemos por obedecer. De Jehová es la tierra y su plenitud; Él la da a quien le place; pero cuando no hay una expresión directa, nadie puede rogar que Él conceda esos bienes.
Aunque Dios asegura a los israelitas que la tierra será de ellos, no obstante tienen que contender con el enemigo. Debemos esforzarnos para obtener lo que Dios nos da. ¡Qué mundo nuevo era aquel al que ahora entra Israel! De mayor gozo será el cambio que las almas santas experimentarán cuando pasen del desierto de este mundo a la patria mejor, esto es, la celestial, a la ciudad que tiene fundamentos. Que al reflexionar en los tratos de Dios con Israel, su pueblo, seamos guiados a meditar en los años de nuestra vanidad, a causa de nuestras transgresiones. Pero bienaventurados los que Jesús ha librado de la ira venidera; a quien haya dado el fervor de su Espíritu en su corazón. Su herencia no la pueden afectar las revoluciones de los reinos, ni los cambios de las posesiones terrenales.</p>
<br/>




</div>
