<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Deuteronomio 32</h2>
<p class="text-justify">Vv. 1, 2.Moisés comienza con una apelación solemne al cielo y tierra en cuanto a la verdad e importancia de lo que iba a decir. Su doctrina es el evangelio, el discurso de Dios, la doctrina de Cristo; la doctrina de la gracia y misericordia por medio de Él, y de la vida y salvación por Él.</p>
<br/>
<p class="text-justify">Vv. 3-6.“¡Él es una Roca!”. Esta es la primera vez que se llama así a Dios en la Escritura. La expresión denota que el poder, la fidelidad y el amor divino, revelados en Cristo y el evangelio, forman un fundamento que no puede ser cambiado ni movido, sobre el cual podemos edificar nuestras esperanzas de felicidad. Bajo su protección podemos encontrar refugio de todos nuestros enemigos y en todos nuestros problemas; como las rocas de aquellos países escudaban contra los rayos abrasadores del sol, y de las tempestades o eran fortalezas contra el enemigo. -”Su obra es perfecta”: la de redención y salvación en que se despliega completa la perfección divina en todas sus partes. Todos los tratos de Dios con sus criaturas están regulados por una sabiduría que no puede errar y por su perfecta justicia. Ciertamente Él es justo y recto; Él cuida que nadie se pierda por Él.
Se presenta una gran acusación contra Israel. Aun los hijos de Dios tienen sus máculas mientras están en este estado imperfecto; pues si decimos que no tenemos pecado, ninguna mancha, nos engañamos a nosotros mismos. Pero el pecado de Israel no era habitual, notable e impenitente, lo cual es característico de los hijos de Satanás.
Fueron necios al abandonar sus misericordias a cambio de las vanidades mentirosas. Todos los pecadores voluntarios, especialmente los pecadores de Israel, son necios e ingratos.</p>
<br/>
<p class="text-justify">Vv. 7-14.Moisés da ejemplos particulares de la bondad de Dios y su preocupación por ellos. El cuidado que el águila da a sus polluelos es un bello emblema del amor de Cristo que vino a mediar entre la justicia divina y nuestra alma culpable, y a llevar nuestros pecados en su propio cuerpo sobre el madero. Por medio de la predicación del evangelio y la influencia del Espíritu Santo, Él estimula a los pecadores y prevalece sobre ellos para que dejen la esclavitud de Satanás.
En los versículos 13 y 14 se encuentran los emblemas de la victoria que los creyentes tienen, en y por medio de Cristo, sobre sus enemigos espirituales, el pecado, Satanás y el mundo. También de la seguridad y triunfo de ellos en Él; del marco de felicidad de su alma cuando está por sobre el mundo y sus cosas. Este será el caso bendito del Israel espiritual en todo sentido en el día postrero.</p>
<br/>
<p class="text-justify">Vv. 15-18.He aquí dos ejemplos de la iniquidad de Israel; cada uno fue una apostasía contra Dios.
Esta gente era llamada Jesurún, “un pueblo recto”por algunos; “un pueblo visionario”para otros; pero pronto perdieron la reputación de su saber y de su rectitud. Se dieron el gusto en cuanto a apetitos como si no tuvieran nada que hacer sino hacer provisión para la carne a fin de satisfacer sus concupiscencias. Los que se endiosan y hacen un ídolo de su estómago, con orgullo y jactancia, y no toleran que se lo digan, abandonan por ello a Dios, con lo que demuestran que le estiman a la ligera. Hay solo un camino para la aceptación y santificación del pecador, aunque sean diferentes los modos en que la falta de religión o la falsa religión le muestra consideración para atraerlo a otros caminos, actitud que a menudo, se califica mal como candidez. ¡Cuán locos están los idólatras que abandonan la Roca de salvación para correr sobre la roca de la perdición!</p>
<br/>
<p class="text-justify">Vv. 19-25.La rebelión de Israel se describió en los versículos anteriores, y aquí siguen las resoluciones de la justicia divina sobre ellos. Nos engañamos si pensamos que Dios puede ser burlado por un pueblo infiel. El pecado nos hace odiosos a la vista del santo Dios. Obsérvese cuánta maldad hace el pecado, y cuéntense como necios quienes se burlan de esto.</p>
<br/>
<p class="text-justify">Vv. 26-38.La idolatría y las rebeliones de Israel merecían, como lo exige la justicia de Dios, que ellos fueran desarraigados. Pero Él perdona a Israel y los deja que sigan siendo los testigos vivos de la verdad de la Biblia, para silenciar a los incrédulos. Han sido preservados para propósitos sabios y santos, y las profecías nos dan una idea de cuáles son esos propósitos. El Señor nunca traerá vergüenza sobre el trono de su gloria.
Muy sabio es, y ayudará al regreso de los pecadores a Dios, la consideración seria del final o el estado futuro de ellos. Esto se refiere particularmente a lo que Dios anunció por medio de Moisés tocante a su pueblo en los días postreros; pero puede dársele una aplicación más general. Oh, que los hombres consideraran la felicidad que perderán y la desgracia en que ciertamente se hundirán si siguen en sus transgresiones! ¿Qué será el fin de ellos? Jeremías, v, 31. Porque el Señor derrotará en su debido tiempo a los enemigos de la iglesia, desagradado por su maldad. Cuando los pecadores se consideren más seguros, vendrá sobre ellos destrucción repentina. Y el tiempo de Dios para venir a liberar a su pueblo es cuando las cosas están peores para ellos. Pero los que confían en cualquier roca que no es Dios, hallarán que les falla cuando más la necesitan.
El rechazo del Mesías por parte de la nación judía es la continuidad de su antigua idolatría, apostasía y rebelión. Serán llevados a humillarse ante el Señor, a arrepentirse de sus pecados y a confiar en su largamente rechazado Mediador para salvación. Entonces Él los librará y hará que su prosperidad sea grande.</p>
<br/>
<p class="text-justify">Vv. 39-43.La conclusión del cántico dice: -1. Gloria a Dios . No puede haber escapatoria de su poder.
2. Terror a sus enemigos . Sin duda terror para aquellos que le odian. La ira de Dios se revela aquí desde el cielo contra ellos.
3. Consuelo a su pueblo . El cántico concluye con palabras de gozo. Cualesquiera sean los juicios traídos contra los pecadores, al pueblo de Dios le irá bien.</p>
<br/>
<p class="text-justify">Vv. 44-47.Aquí está la solemne entrega de este cántico a Israel con el encargo de dar importancia a todas las buenas palabras que Moisés les había dicho. No es cosa trivial sino cuestión de vida o muerte: dadle importancia y estad listos para siempre; descuidadlo y estaréis deshechos para siempre. ¡Oh, que los hombres fueran plenamente persuadidos de que la religión es la vida de ellos, aun la vida de sus almas!</p>
<br/>
<p class="text-justify">Vv. 48-52.Ahora Moisés había acabado su obra, ¿por qué iba a desear vivir un día más? Dios le recuerda el pecado del cual era culpable, el que le impidió entrar a Canaán. Bueno es para el mejor de los hombres morir arrepentido de los males de que esté consciente. Pero pueden morir consolados y tranquilos cuando Dios los llama, a pesar de los pecados que recuerdan contra sí mismos, porque tienen la perspectiva del creyente y la esperanza de vida eterna más allá de la muerte bien cimentada.</p>
<br/>




</div>
