<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Deuteronomio 34</h2>
<p class="text-justify">Vv. 1-4.Moisés parecía no deseoso de dejar su obra pero, acabada esta, no manifestó indisposición a morir. Dios había declarado que no entraría a Canaán, pero el Señor también había prometido que Moisés la vería y que Él le mostraría toda esa buena tierra. Ahora los creyentes ven, por medio de la gracia, la bendición y la gloria de su estado futuro. A veces, Dios reserva los descubrimientos más esplendorosos de Su gracia para apoyar a Su pueblo en los momentos de muerte. Los que mueren en la fe de Cristo y en la esperanza del cielo pueden dejar con júbilo este mundo.</p>
<br/>
<p class="text-justify">Vv. 5-8.Moisés obedeció esta orden de Dios con la misma disposición con que obedeció cualquier otra, aunque esta parecía más dura. Esto se parece a nuestro Señor Jesucristo. Pero Moisés murió con honra, en paz y de una manera más fácil; el Salvador murió sobre la desgraciada y torturante cruz. Moisés murió con toda facilidad; él murió “conforme a la palabra de Jehová”, según la voluntad de Dios. Cuando los siervos del Señor han hecho todas sus demás obras, deben morir por fin, y estar dispuestos a irse a casa, cuando su Amo manda por ellos, Hechos xxi, 13. No se conoce el lugar de su tumba. Si el alma está reposando con Dios tiene poca importancia donde repose el cuerpo. No hubo declinación en la fuerza de su cuerpo, ni del vigor y actividad de su mente; su entendimiento y su memoria eran tan claros como siempre. Esta fue la recompensa de sus servicios, el efecto de su mansedumbre extraordinaria.
Hubo duelo solemne por él. Sin embargo, por grande que sea nuestra pérdida, no debemos entregarnos al dolor. Si esperamos ir al cielo regocijándonos, ¿por qué hemos de ir a la tumba lamentándonos?</p>
<br/>
<p class="text-justify">Vv. 9-12.Moisés llevó a Israel hasta las fronteras de Canaán y, luego, murió y los dejó. Esto significa que nada perfeccionó la ley, Hebreos vii, 19. Lleva a los hombres a un desierto de convicción de pecado, pero no al Canaán del reposo y paz estable. Esa honra quedó reservada para Josué, nuestro Señor Jesús, del cual Josué era un tipo (y el nombre es el mismo), que hace por nosotros lo que la ley no podía hacer, Romanos viii, 3. Por Él entramos al reposo espiritual de conciencia y al reposo eterno en el cielo.
Moisés fue mayor que cualquier otro profeta del Antiguo Testamento. Pero nuestro Señor Jesús fue más allá que él, mucho más allá que los demás profetas que se quedaron atrás respecto de Él. Y vemos aquí un fuerte parecido entre el redentor de los hijos de Israel y el Redentor de la humanidad. Moisés fue enviado por Dios a liberar a los israelitas de una cruel esclavitud; él los sacó y venció a sus enemigos. Él llegó a ser no sólo el libertador de ellos, sino su legislador; no sólo su legislador, sino su juez; y, finalmente, los condujo a la frontera de la tierra prometida. Nuestro bendito Salvador vino a rescatarnos de la esclavitud del diablo y a restaurarnos a la libertad y la felicidad. Él vino a confirmar cada precepto moral del primer legislador; y a escribirlos no sobre tablas de piedra, sino sobre tablas de carne del corazón. Él vino para ser nuestro Juez también, por cuanto ha designado un día en que juzgará todos los secretos de los hombres y recompensará o castigará conforme a ello. Esta grandeza de Cristo por sobre Moisés es una razón por la cual los cristianos deben ser obedientes y fieles a la santa religión por la cual profesan ser seguidores de Cristo. ¡Dios nos haga a todos así por Su gracia!</p>
<br/>




</div>
