<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Eclesiastés 12</h2>
<p class="text-justify">Vv. 1-7.Debemos acordarnos de los pecados cometidos contra nuestro Creador, arrepentirnos, y pedir perdón. Debemos recordar nuestro deber y afrontarlo, buscando en Él la gracia y el poder. Esto debe hacerse temprano, mientras el cuerpo es fuerte y el espíritu activo. Cuando el hombre siente dolor al revisar una vida malgastada, de no haber abandonado el pecado ni las vanidades del mundo hasta que se ve obligado a decir: yo no tengo en ellos contentamiento, su sinceridad se vuelve muy cuestionable. Luego, sigue una descripción figurada de la vejez y sus dolencias, la cual tiene ciertas dificultades, pero el significado es claro: mostrar cuán incómodos son, por lo general, los días de la vejez. Como los cuatro versículos, 2-5, son una descripción figurativa de las enfermedades que habitualmente acompañan a la vejez, así, el versículo 6, comenta las circunstancias que acompañan la hora de la muerte. Si el pecado no hubiera entrado al mundo, no se hubieran conocidos estas enfermedades. Ciertamente, entonces, el viejo debiera reflexionar en el mal del pecado.</p>
<br/>
<p class="text-justify">Vv. 8-14.Salomón repite su texto: VANIDAD DE VANIDADES, TODO ES VANIDAD. Estas son las palabras de uno que podía hablar por propia y cara experiencia de la vanidad del mundo, que nada puede hacer para aliviar a los hombres de la carga del pecado.
Al considerar el valor de las almas, presta buena atención a lo que dijo y escribió: palabras de verdad que siempre serán palabras aceptables. Las verdades de Dios son como aguijones para quienes son torpes y alejados; y clavos para los que andan descarriados y desviados; medios de estabilizar al corazón a fin de que nunca nos apartemos de nuestro deber ni seamos quitados de este.
El Pastor de Israel es el Dador de la sabiduría inspirada. Todos los maestros y los guías reciben sus comunicaciones. El título se aplica en la Escritura al Señor Jesucristo, el Hijo de Dios. Los profetas inquirieron y diligentemente indagaron qué persona y qué tiempo, indicaba el Espíritu de Cristo que estaba en ellos, cuando anunciaron de antemano los sufrimientos de Cristo, y las glorias que vendrían tras ellos.
Escribir muchos libros no era adecuado para la corta vida humana, y sería cansancio para el escritor y el lector; entonces era mucho más para ambos de lo que es ahora. Todas las cosas serían vanidad y aflicción, a menos que condujesen a esta conclusión: temer a Dios y obedecer sus mandamientos es el todo del hombre. El temor de Dios incluye en sí todos los afectos del alma, los que son producidos por el Espíritu Santo. Puede haber terror donde no hay amor, sí, donde hay odio. Pero esto es diferente del gracioso temor de Dios, como los sentimientos de un niño afectuoso. A menudo se pone en el corazón el temor de Dios como el todo de la religión verdadera, lo que comprende sus resultados prácticos en la vida.
Atendamos a lo único necesario y, ahora, vayamos a Él como Salvador misericordioso, que pronto vendrá como Juez todopoderoso, cuando saque a la luz las cosas de las tinieblas y exponga los consejos de todos los corazones. ¿Por qué Dios registra en su palabra que TODO ES VANIDAD sino para impedir que nos engañemos para nuestra ruina? Él hace que nuestro deber sea nuestro interés. Que se grabe en nuestros corazones: Teme a Dios y guarda sus mandamientos porque esto es el todo del hombre.</p>
<br/>




</div>
