<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Efesios 2</h2>
<p class="text-justify">Vv. 1-10.El pecado es la muerte del alma. Un hombre muerto en delitos y pecados no siente deseos por los placeres espirituales. Cuando miramos un cadáver, da una sensación espantosa. El espíritu que nunca muere se ha ido, y nada ha dejado sino las ruinas de un hombre. Pero si viéramos bien las cosas, deberíamos sentirnos mucho más afectados con el pensamiento de un alma muerta, un espíritu perdido y caído.
El estado de pecado es el estado de conformidad con este mundo. Los hombres impíos son esclavos de Satanás que es el autor de esa disposición carnal orgullosa que hay en los hombres impíos; él reina en los corazones de los hombres. De la Escritura queda claro que si los hombres han sido más dados a la iniquidad espiritual o sensual, todos los hombres, siendo naturalmente hijos de desobediencia, son también por naturaleza hijos de ira. Entonces, ¡cuánta razón tienen los pecadores para procurar fervorosamente la gracia que los hará hijos de Dios y herederos de la gloria, habiendo sido hijos de ira! -El amor eterno o la buena voluntad de Dios para con sus criaturas es la fuente de donde fluyen todas sus misericordias para nosotros; ese amor de Dios es amor grande, y su misericordia es misericordia rica. Todo pecador convertido es un pecador salvado; librado del pecado y de la ira. La gracia que salva es la bondad y el favor libre e inmerecido de Dios; Él salva, no por las obras de la ley, sino por la fe en Cristo Jesús.
La gracia en el alma es vida nueva en el alma. Un pecador regenerado llega a ser un ser viviente; vive una vida de santidad, siendo nacido de Dios: vive, siendo librado de la culpa del pecado, por la gracia que perdona y justifica. Los pecadores se revuelcan en el polvo; las almas santificadas se sientan en los lugares celestiales, levantadas por sobre este mundo por la gracia de Cristo.
La bondad de Dios al convertir y salvar pecadores aquí y ahora, estimula a los demás a esperar, en el futuro, en su gracia y misericordia. Nuestra fe, nuestra conversión, y nuestra salvación eterna no son por las obras, para que ningún hombre se jacte. Estas cosas no suceden por algo que nosotros hagamos, por tanto, toda jactancia queda excluida. Todo es dádiva libre de Dios y efecto de ser vivificado por su poder. Fue su propósito para lo cual nos preparó bendiciéndonos con el conocimiento de su voluntad, y su Espíritu Santo produce tal cambio en nosotros que glorificaremos a Dios por nuestra buena conversación y perseverancia en la santidad. Nadie puede abusar de esta doctrina apoyándose en la Escritura, ni la acusa de ninguna tendencia al mal. Todos los que así hacen, no tienen excusa.</p>
<br/>
<p class="text-justify">Vv. 11-13.Cristo y su pacto son el fundamento de todas las esperanzas del cristiano.
Aquí hay una descripción triste y terrible pero ¿quién es capaz de quitarse de ello? ¿No desearíamos que esto no fuera una descripción verdadera de muchos bautizados en el nombre de Cristo? ¿Quién puede, sin temblar, reflexionar en la miseria de una persona separada por siempre del pueblo de Dios, cortada del cuerpo de Cristo, caída del pacto de la promesa, sin tener esperanza ni Salvador y sin ningún Dios sino un Dios de venganza por toda la eternidad? ¡No tener parte en Cristo! ¿Qué cristiano verdadero puede oír esto sin horror? -La salvación está lejos del impío, pero Dios es una ayuda a mano para su pueblo y esto es por los sufrimientos y la muerte de Cristo.</p>
<br/>
<p class="text-justify">Vv. 14-18.Jesucristo hizo la paz por el sacrificio de sí mismo; en todo sentido Cristo era la Paz de ellos, el autor, el centro y la sustancia de estar ellos en paz con Dios, y de su unión con los creyentes judíos en una iglesia. A través de la persona, el sacrificio y la mediación de Cristo, se permite a los pecadores acercarse a Dios Padre y son llevados con aceptación a su presencia, con su adoración y su servicio, bajo la enseñanza del Espíritu Santo, como uno con el Padre y el Hijo. Cristo compró el permiso para que nosotros vayamos a Dios; y el Espíritu da el corazón para ir, y la fuerza para ir y, luego, la gracia para servir aceptablemente a Dios.</p>
<br/>
<p class="text-justify">Vv. 19-22.La iglesia se compara con una ciudad, y todo pecador convertido está libre de eso. También es comparada con una casa, y todo pecador convertido es uno de la familia; un siervo y un hijo en la casa de Dios.
También se compara la Iglesia con un edificio fundado en la doctrina de Cristo, entregada por los profetas del Antiguo Testamento, y los apóstoles del Nuevo Testamento. Dios habita ahora en todos los creyentes; ellos llegan a ser el templo de Dios por la obra del bendito Espíritu. Entonces, preguntémonos si nuestras esperanzas están fijadas en Cristo conforme a la doctrina de su palabra. ¿Nos consagramos a Dios como templos santos por medio de Él? ¿Somos morada de Dios en el Espíritu, estamos orientados espiritualmente y llevamos los frutos del Espíritu? Cuidémonos de no contristar al santo Consolador. Deseemos su graciosa presencia y sus influencias en nuestros corazones. Procuremos cumplir los deberes asignados a nosotros para la gloria de Dios.</p>
<br/>




</div>
