<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Efesios 1</h2>
<p class="text-justify">Vv. 1, 2.Todos los cristianos deben ser santos; si no llegan a ese carácter en la tierra, nunca serán santos en la gloria. Los que no son fieles no son santos, no creen en Cristo ni son veraces a la profesión que hacen de su relación con su Señor. Por gracia entendemos el amor y el favor libre e inmerecido de Dios, y las gracias del Espíritu que fluyen; por la paz, todas las demás bendiciones temporales y espirituales, fruto de lo anterior. No hay paz sin gracia. No hay paz ni gracia, sino de Dios Padre y del Señor Jesucristo; y los mejores santos necesitan nuevas provisiones de la gracia del Espíritu, y deseos de crecer.</p>
<br/>
<p class="text-justify">Vv. 3-8.Las bendiciones celestiales y espirituales son las mejores bendiciones; con las cuales no podemos ser miserables, y sin las cuales no podemos sino serlo. Esto viene de la elección de ellos en Cristo, antes de la fundación del mundo, para que fuesen hechos santos por la separación del pecado, siendo apartados para Dios y santificados por el Espíritu Santo, como consecuencia de su elección en Cristo. Todos los escogidos para la felicidad como fin, son escogidos para santidad como medio. Fueron predestinados o preordenados con amor para ser adoptados como hijos de Dios por fe en Cristo Jesús, y ser abiertamente recibidos en los privilegios de la elevada relación con Él. El creyente reconciliado y adoptado, el pecador perdonado, da toda la alabanza de su salvación a su bondadoso Padre. Su amor estableció este método de redención, no escatimó a su propio Hijo, y trajo a los creyentes a que oyeran y abrazaran esta salvación. Fue riqueza de su gracia proveer como garantía a su propio Hijo, y entregarlo libremente. Este método de la gracia no estimula el mal; muestra el pecado en toda su odiosidad, y cuánto merece la venganza. Las acciones del creyente, y sus palabras, declaran las alabanzas de la misericordia divina.</p>
<br/>
<p class="text-justify">Vv. 9-14.Las bendiciones fueron dadas a conocer a los creyentes cuando el Señor les muestra el misterio de su soberana voluntad, y el método de redención y salvación. Pero esto debiera haber estado por siempre oculto de nosotros, si Dios no las hubiera dado a conocer por su palabra escrita, la predicación de su evangelio, y su Espíritu de verdad.
Cristo unió en su persona los dos bandos en disputa, Dios y el hombre, y dio satisfacción por el mal que causó la separación. Obró por su Espíritu las gracias de fe y amor por las cuales somos hechos uno con Dios, y unos con otros. Dispensa todas sus bendiciones de acuerdo a su beneplácito. Su enseñanza divina condujo a los que quiso, a que vieran la gloria de las verdades, mientras otros fueron dejados para blasfemar. -¡Qué promesa de gracia es esta que asegura la dádiva del Espíritu Santo a quienes lo piden! La obra santificadora y consoladora del Espíritu Santo sella a los creyentes como hijos de Dios y herederos del cielo. Estas son las primicias de la santa dicha. Para esto fuimos hechos y para esto fuimos redimidos; este es el gran designio de Dios en todo lo que ha hecho por nosotros; que todo sea atribuido para la alabanza de su gloria.</p>
<br/>
<p class="text-justify">Vv. 15-23.Dios ha puesto bendiciones espirituales en su Hijo el Señor Jesús; pero nos pide que las busquemos y las obtengamos por la oración. Aun los mejores cristianos necesitan que se ore por ellos; y mientras sepamos del bienestar de los amigos cristianos debemos orar por ellos.
Hasta los creyentes verdaderos tienen gran necesidad de sabiduría celestial. ¿Acaso aun los mejores de nosotros somos renuentes a uncirnos al yugo de Dios aunque no hay otro modo de hallar reposo para el alma? ¿Acaso no nos alejamos de nuestra paz por un poco de placer? Si discutiéramos menos y oráramos más con y por unos y otros, diariamente veríamos más y más cuál es la esperanza de nuestra vocación, y las riquezas de la gloria divina en esta herencia. Deseable es sentir el fuerte poder de la gracia divina que empieza y ejecuta la obra de la fe en nuestras almas. Pero cuesta mucho llevar a un alma a creer plenamente en Cristo y aventurarse toda ella y su esperanza de vida eterna en su justicia. Nada menos que el poder omnipotente obrará esto en nosotros.
Aquí se significa que es Cristo el Salvador quien suple todas las necesidades de los que confían en Él, y les da todas las bendiciones en la más rica abundancia. Siendo partícipes en Cristo mismo llegamos a ser llenos con la plenitud de la gracia y la gloria en Él. Entonces, ¡cómo pueden olvidarse a sí mismos esos que andan buscando la justicia fuera de Él! Esto nos enseña a ir a Cristo. Si supiéramos a qué estamos llamados, qué podemos hallar en Él, con toda seguridad que iríamos y seríamos parte de Él. Cuando sentimos nuestra debilidad y el poder de nuestros enemigos, es cuando más notamos la grandeza de ese poder que efectúa la conversión del creyente y que está dedicado a perfeccionar su salvación. Ciertamente esto nos constreñirá por amor para vivir para la gloria de nuestro Redentor.</p>
<br/>




</div>
