<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Efesios 6</h2>
<p class="text-justify">Vv. 1-4.El gran deber de los hijos es obedecer a sus padres. La obediencia comprende la reverencia interna y los actos externos, y en toda época la prosperidad ha acompañado a los que se distinguen por obedecer a sus padres.
El deber de los padres. No seáis impacientes ni uséis severidades irracionales. Tratad a vuestos hijos con prudencia y sabiduría; convencedlos en sus juicios y obrad en la razón de ellos. Criadlos bien; bajo la corrección apropiada y compasiva, y en el conocimiento del deber que Dios exige. Este deber es frecuentemente descuidado hasta entre los que profesan el evangelio. Muchos ponen a sus hijos en contra de la religión, pero esto no excusa la desobediencia de los hijos aunque lamentablemente pueda ocasionarla. Dios solo puede cambiar el corazón, pero Él da su bendición a las buenas lecciones y ejemplos de los padres, y responde sus oraciones. Pero no deben esperar la bendición de Dios los que tienen como afán principal que sus hijos sean ricos y realizados, sin importar lo que suceda con sus almas.</p>
<br/>
<p class="text-justify">Vv. 5-9.El deber de los siervos está resumido en una palabra: obediencia. Los siervos de antes por lo general eran esclavos. Los apóstoles tenían que enseñar sus deberes a los amos y a los siervos, porque haciendo esto aminorarían los males hasta que la esclavitud llegara a su fin por la influencia del cristianismo. Los siervos tienen que reverenciar a los que están por encima de ellos. Tienen que ser sinceros; no deben pretender obediencia cuando quieren desobedecer, sino sirviendo fielmente. Deben servir a sus amos no sólo cuando éstos los ven; pero deben ser estrictos para cumplir con su deber cuando están ausentes o no los ven. La consideración constante del Señor Jesucristo hará fieles y sinceros a los hombres de toda posición, no a regañadientes ni por coerción, sino por un principio de amor a sus amos y a sus intereses. Esto les hace fácil servir, agrada a sus amos, y es aceptable para el Señor Cristo. Dios recompensará hasta lo más mínimo que se haya hecho por sentido del deber, y con la mira de glorificarlo a Él.
He aquí el deber de los amos. Actuad de la misma manera. Sed justos con vuestros siervos según como esperáis que ellos sean con vosotros; mostrad la misma buena voluntad e interés por ellos y tened cuidado, para ser aprobado delante de Dios. No seáis tiránicos ni opresores. Vosotros tenéis un Amo al cual obedecer y vosotros y ellos no son sino consiervos respecto a Cristo Jesús. Si los amos y los siervos consideraran sus deberes para con Dios, y la cuenta que deben rendirle dentro de poco tiempo, se preocuparían más de sus deberes mutuos y, de ese modo, las familias serían más ordenadas y felices.</p>
<br/>
<p class="text-justify">Vv. 10-18.La fuerza y el valor espiritual son necesarios para nuestra guerra y sufrimiento espiritual. Los que desean demostrar que tienen la gracia verdadera consigo, deben apuntar a toda gracia; y ponerse toda la armadura de Dios, que Él prepara y da. La armadura cristiana está hecha para usarse y no es posible dejar la armadura hasta que hayamos terminado nuestra guerra y finalizado nuestra carrera. El combate no es tan sólo contra enemigos humanos, ni contra nuestra naturaleza corrupta; tenemos que vérnosla con un enemigo que tiene miles de maneras para engañar a las almas inestables. Los diablos nos asaltan en las cosas que corresponden a nuestras almas y se esfuerzan por borrar la imagen celestial de nuestros corazones.
Debemos resolver, por la gracia de Dios, no rendirnos a Satanás. Resístidle, y de vosotros huirá. Si cedemos, él se apoderará del terreno. Si desconfiamos de nuestra causa o de nuestro Líder o de nuestra armadura, le damos ventaja.
Aquí se describen las diferentes partes de la armadura de los soldados bien pertrechados, que tienen que resistir los asaltos más feroces del enemigo. No hay nada para la espalda; nada que defienda a los que se retiran de la guerra cristiana.
La verdad o la sinceridad es el cinto. Esto rodea todas las otras partes de la armadura y se menciona en primer lugar. No puede haber religión sin sinceridad.
La justicia de Cristo, imputada a nosotros, es una coraza contra los dardos de la ira divina. La justicia de Cristo, implantada en nosotros, fortifica el corazón contra los ataques de Satanás.
La resolución debe ser como las piezas de la armadura para resguardar las partes delanteras de las piernas, y para afirmarse en el terreno o caminar por sendas escarpadas, los pies deben estar protegidos con el apresto del evangelio de la paz. Los motivos para obedecer en medio de las pruebas deben extraerse del claro conocimiento del evangelio.
La fe es todo en todo en la hora de la tentación. La fe, tener la certeza de lo que no se ve, como recibir a Cristo y los beneficios de la redención, y de ese modo, derivar gracia de Él, es como un escudo, una defensa en toda forma. El diablo es el malo. Las tentaciones violentas, por las cuales el alma se enciende con fuego del infierno, son dardos que Satanás nos arroja. Además, los malos pensamientos de Dios y de nosotros mismos. La fe que aplica la palabra de Dios y a la gracia de Cristo, es la que apaga los dardos de la tentación.
La salvación debe ser nuestro yelmo. La buena esperanza de salvación, la expectativa bíblica de la victoria, purifican el alma e impiden que sea contaminada por Satanás.
El apóstol recomienda al cristiano armado para la defensa en la batalla, una sola arma de ataque, la cual es suficiente, la espada del Espíritu, que es la palabra de Dios. Somete y mortifica los malos deseos y los pensamientos blasfemos a medida que surgen adentro; y responde a la incredulidad y al error a medida que asaltan desde afuera. Un solo texto bien entendido y rectamente aplicado, destruye de una sola vez la tentación o la objeción y somete al adversario más formidable.
La oración deben asegurar todas las demás partes de nuestra armadura cristiana. Hay otros deberes de la religión y de nuestra posición en el mundo, pero debemos mantener el tiempo de orar. Aunque la oración solemne y estable pueda no ser factible cuando hay otros deberes que cumplir, de todos modos las oraciones piadosas cortas que se lancen son siempre como dardos.
Debemos usar pensamientos santos en nuestra vida corriente. El corazón vano también será vano para orar. Debemos orar con toda clase de oración, pública, privada y secreta; social y solitaria; solemne y súbita; con todas las partes de la oración: confesión de pecado, petición de misericordia y acción de gracias por los favores recibidos. Y debemos hacerlo por la gracia de Dios Espíritu Santo, dependiendo de su enseñanza y conforme a ella. Debemos perseverar en pedidos particulares a pesar del desánimo. Debemos orar no sólo por nosotros sino por todos los santos. Nuestros enemigos son fuertes y nosotros no tenemos fuerza, pero nuestro Redentor es todopoderoso, y en el poder de su fuerza, podemos vencer. Por eso debemos animarnos a nosotros mismos. ¿No hemos dejado de responder a menudo cuando Dios ha llamado? Pensemos en esas cosas y sigamos orando con paciencia.</p>
<br/>
<p class="text-justify">Vv. 19-24.El evangelio era un misterio hasta que fue dado a conocer por la revelación divina; anunciarlo es obra de los ministros de Cristo. Los ministros mejores y más eminentes necesitan las oraciones de los creyentes. Debe orarse especialmente por ellos porque están expuestos a grandes dificultades y peligros en su obra.
Paz sea a los hermanos, y amor con fe. Por paz entiéndase toda clase de paz: paz con Dios, paz de conciencia, paz entre ellos mismos. La gracia del Espíritu, produciendo fe y amor y toda gracia. Él desea eso para aquellos en quienes ya fueron empezadas. Y toda la gracia y las bendiciones vienen a los santos desde Dios, por medio de nuestro Señor Jesucristo. La gracia, esto es, el favor de Dios, y todos los bienes espirituales y temporales, que son de ella, es y será con todos los que así amen a nuestro Señor Jesucristo con sinceridad, y sólo con ellos.</p>
<br/>




</div>
