<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Éxodo 2</h2>
<p class="text-justify">Vv. 1-4.Observe el orden de la Providencia: justo en el momento en que la crueldad de Faraón llega al máximo, mandando matar a los niños hebreos, nace el libertador. Cuando los hombres se confabulan para llevar la iglesia a la ruina, Dios está preparando su salvación.
Los padres de Moisés vieron que era un niño hermoso. La fe viva se siente fortalecida con el menor indicio del favor divino. Hebreos xi, 23 dice que por fe los padres de Moisés lo escondieron; tenían la promesa de que Israel sería preservado, y la creyeron. La fe en la promesa de Dios anima a usar medios legales para obtener misericordia. El cumplimiento de nuestro deber, va seguido de los hechos de Dios. La fe en Dios siempre nos pondrá por encima del temor al hombre.
Al cabo de tres meses, cuando ya no podían esconder más al bebé, lo colocaron en un arquilla de juncos a la orilla del río, y a su hermana para que vigilara. Si el débil afecto de una madre fue tan cuidadoso, qué pensaremos de Aquel cuyo amor, cuya compasión son infinitos, como Él. Moisés nunca tuvo protección más poderosa a su alrededor; ni aun cuando tenía a todos los israelitas alrededor de su tienda en el desierto, que ahora cuando yace a solas, un indefenso bebé sobre las aguas. No hay agua, no hay egipcio que pueda dañarlo. Dios está más presente a nuestro lado cuando parecemos más abandonados y desamparados.</p>
<br/>
<p class="text-justify">Vv. 5-10.Venid, ved el lugar donde ese gran hombre, Moisés, yace siendo un niñito; en un canasto de juncos a orilla del río. Si hubiera quedado largo tiempo allí, hubiera perecido. Pero al lugar donde está este pobre infante desamparado la Providencia trae a la hija del Faraón e inclina su corazón a la compasión, cosa que ella se atreve a hacer cuando nadie más podía. El cuidado que Dios tuvo de nosotros en nuestra infancia debiéramos mencionarlo a menudo para su alabanza. El faraón trató cruelmente de destruir a Israel, pero su propia hija tuvo lástima de un niño hebreo y, no sólo eso, sino que, sin saberlo, preservó al libertador de Israel y dio a Moisés una buena nodriza, esto es, su propia madre. Para que tuviera una nodriza hebrea, la hermana de Moisés trajo a su madre por nodriza.
Moisés fue tratado como hijo de la hija de Faraón. Muchos que tienen un nacimiento oscuro y pobre, por actos sorprendentes de la Providencia son puestos a gran altura en el mundo, para que los hombres sepan que Dios reina.</p>
<br/>
<p class="text-justify">Vv. 11-15.Moisés asumió atrevidamente la causa del pueblo de Dios. Queda claro en Hebreo xi, que esto fue hecho por la fe, con el propósito pleno de abandonar los honores, las riquezas y los placeres del rango que tenía entre los egipcios. Por la gracia de Dios fue un partícipe de la fe en Cristo, que vence al mundo. Puesto que tenía la seguridad de que Israel era el pueblo de Dios, estaba dispuesto, no sólo a arriesgarlo todo, sino a sufrir por amor a Él.
Por concesión especial del Cielo, que no sienta jurisprudencia para otros casos, Moisés mató a un egipcio y rescató a un israelita oprimido. Además, trató de poner fin a una disputa entre dos hebreos. El reproche de Moisés aún podría usarse. ¿No podemos aplicarlo a quienes disputan, y con sus ardientes debates, dividen y debilitan la iglesia cristiana? Olvidan que son hermanos. El que hacía lo malo atacó a Moisés. Enojarse por la reprensión es señal de culpa. Los hombres no saben lo que hacen, ni cuán enemigos son de sí mismos, cuando resisten y desprecian la reprensión fiel y al que la hace. Moisés podría haber dicho: “Si este es el espíritu de los hebreos, me iré de regreso a la corte y seré el hijo de la hija del Faraón”. Pero debemos tener cuidado de no ponernos en contra de los caminos de Dios y de su pueblo, por la necedad y los malos modales de algunas personas que profesan la religión. Moisés se vio obligado a huir a la tierra de Madián. Dios ordenó esto con fines sabios y santos.</p>
<br/>
<p class="text-justify">Vv. 16-22.Moisés encontró refugio en Madián. Aunque se había criado y educado en la sabiduría de la corte, estuvo dispuesto a ayudar a las hijas de Reuel a que abrevaran sus rebaños. Moisés le gustaba hacer justicia y actuar en defensa de quienes veía dañados, cosa que todo hombre debiera hacer si está a su alcance. Él le gustaba hacer lo bueno ; donde quiera que nos ponga la providencia de Dios, debemos desear ser útiles y tratar de serlo; y cuando no podamos hacer el bien que debemos, tenemos que estar preparados para hacer el bien que podamos. Moisés se recomendó solo al príncipe de Madián, el cual casó una de sus hijas con Moisés, con la cual tuvo un hijo, Gersón, “un extraño ahí”para que le recordara la tierra en que había sido extranjero.</p>
<br/>
<p class="text-justify">Vv. 23-25.Aunque no siguió el asesinato de los niños varones, continuó la sevidumbre de los israelitas en Egipto. A veces, el Señor tolera que la vara de los malos caiga larga y pesada sobre la suerte del justo. Al final, sometidos a sus tribulaciones, empezaron a pensar en Dios. Es señal de que el Señor viene a nosotros con liberación cuando se inclina y hace que clamemos a Él. Dios oyó sus gemidos ; dejó en claro que había tomado nota de sus gemidos. Él recordó su pacto, del cual nunca se olvida. Esto tuvo en consideración y no algún mérito de ellos. Él miró a los hijos de Israel. Moisés los miró y los compadeció pero, ahora, Dios los miró y los ayudó. Él tuvo respeto hacia ellos. Sus ojos estaban ahora fijos sobre Israel para mostrarse en favor de ellos. Dios siempre es así, una muy pronta ayuda en las tribulaciones. Entonces, animaos vosotros, que conscientes de culpa y servidumbre, estáis esperando en Él para ser liberados. Dios en Cristo Jesús también os mira. Una llamada de amor se une a una promesa del Redentor. Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar, Mateo xi, 28.</p>
<br/>




</div>
