<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Éxodo 7</h2>
<p class="text-justify">Vv. 1-7.Dios se glorifica a sí mismo. Da a conocer a su pueblo que Él es Jehová. Israel lo llega a saber por el cumplimiento de las promesas dadas a ellos y a los egipcios, derramando su ira sobre éstos.
Moisés, como embajador de Jehová, hablando en su nombre, dio órdenes al Faraón, le notificó amenazas e invocó un juicio en su contra. Faraón, orgulloso y grande como era, no pudo resistir. Moisés no se sintió sobrecogido ante Faraón; más bien lo hizo temblar. Esto parecen querer decir las palabras: Tú serás dios para Faraón. Al fin Moisés es liberado de sus temores. Ya no plantea objeciones; fortalecido en la fe, hace su tarea con valentía y sigue adelante con perseverancia.</p>
<br/>
<p class="text-justify">Vv. 8-13.Nada que disguste a los hombres, porque se opone a su orgullo y lujuria, los convencerá. Pero es fácil hacerles creer que son ciertas las cosas que desean. Dios manda siempre con su palabra pruebas concluyentes de su autoridad divina, pero cuando los hombres se inclinan a la desobediencia, y quieren poner objeciones, Él permite a menudo que se ponga ante ellos una trampa donde ellos mismos quedan atrapados. Los magos eran engañadores que, por medio de tretas o trucos secretos, trataron de copiar los milagros verdaderos de Moisés cosa que lograron hacer en pequeña medida, como para engañar a los observadores; pero, finalmente, se vieron obligados a confesar que no podían imitar los efectos del poder divino. Nadie ayuda más a destruir pecadores que aquellos que resisten la verdad distrayendo a los hombres con algo parecido a la verdad, pero falso. Satanás debe ser temido con mayor razón cuando se transforma en ángel de luz.</p>
<br/>
<p class="text-justify">Vv. 14-25.He aquí la primera de las diez plagas: Conversión de las aguas en sangre. Fue una plaga espantosa . La vista de tan vastos torrentes de sangre no podía sino inspirar horror. Nada es más común que el agua; tan sabia y tan bondadosamente la Providencia ha ordenado que lo que es tan necesario y útil para el bienestar de la vida humana, sea barato y esté disponible casi en todo lugar; sin embargo, ahora los egipcios tenían que beber sangre o morir de sed. Egipto era una tierra agradable, pero los peces muertos y la sangre deben de haberla puesto muy desagradable. Era una plaga justa , enviada con justicia sobre los egipcios, porque el Nilo, el río de Egipto, era su ídolo. Esa criatura que idolatramos es lo que Dios nos quita justamente o hace que nos sea amarga. Habían manchado el río con la sangre de los niños de hebreos y, ahora, Dios había convertido el río en sangre. Nunca habían tenido sed de sangre, pero, tarde o temprano, se hartaron. Era una plaga significativa ; Egipto dependía mucho de su río, Zacarías xiv, 18; de modo que el atacar el río, para ellos era una advertencia de la destrucción de toda la producción de su país. El amor de Cristo a sus discípulos cambia todas sus misericordias comunes en bendiciones espirituales; la ira de Dios contra sus enemigos convierte en maldición y miseria para ellos las ventajas más apreciadas.
Aarón tiene que convocar la plaga golpeando el río con su vara. Fue hecho a la vista del Faraón y sus ayudantes, pues los verdaderos milagros de Dios no se realizan como los prodigios mentirosos de Satanás; la verdad no se esconde en los rincones. Véase el poder omnipotente de Dios. Cada criatura es para nosotros lo que Él la hace ser: agua o sangre. Nótese con qué cambios nos podemos encontrar en las cosas de este mundo; lo que siempre es vano, pronto puede convertirse en tribulación. Nótese qué mala obra hace el pecado. Si las cosas que han sido nuestra consolación resultan ser nuestra cruz, es gracias a nosotros mismos. El pecado es lo que convierte nuestras aguas en sangre.
La plaga duró siete días; y en todo ese tiempo el orgulloso corazón de Faraón no le dejó desear que Moisés orara para eliminar la plaga. Así los hipócritas de corazón acumulan ira sobre sí. No es de asombrarse que la ira de Dios no se haya apaciguado, sino que su mano aún siga extendida.</p>
<br/>




</div>
