<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Éxodo 15</h2>
<p class="text-justify">Vv. 1-21.Este cántico es el más antiguo que conocemos. Es un cántico santo para el honor de Dios, para exaltar su nombre y celebrar su alabanza y solamente la suya pues en lo más mínimo magnifica a ningún hombre. La santidad al Señor está en cada parte suya. Puede ser considerado como tipo y profecía de la destrucción final de los enemigos de la iglesia.
Dichosos aquellos cuyo Dios es el Señor. Ellos tienen trabajo para hacer, tentaciones con las cuales contender y aflicciones que soportar y en sí mismos son débiles pero su gracia es la fortaleza de ellos. A menudo están apenados pero en Él tienen consuelo; Él es el cántico de ellos. El pecado y la muerte y el infierno los amenazan pero Él es y será la salvación de ellos. El Señor es un Dios todopoderoso y ¡ay de aquellos que luchan con su Hacedor! Él es un Dios de incomparable perfección; Él es glorioso en santidad; su santidad es su gloria. Su santidad se muestra en el odio del pecado y su ira contra los pecadores obstinados. Se ve en la liberación de Israel y su fidelidad a su propia promesa. Él es temible en alabanzas; aquello que es materia de alabanza para los siervos de Dios, es muy espantoso para sus enemigos. Él está obrando prodigios , cosas fuera del curso corriente de la naturaleza; maravillas para aquellos en cuyo favor son hechas, que son tan indignos que no tenían razón para esperarlas. Hubo prodigios de poder y prodigios de gracia; en ambos Dios era para ser humildemente adorado.</p>
<br/>
<p class="text-justify">Vv. 22-27.En el desierto de Shur los israelitas no tuvieron agua. En Mara tuvieron agua pero era amarga de modo que no pudieron beberla. Dios puede hacernos amargo eso que más nos prometamos a nosotros mismos y, a menudo lo hace así en el desierto de este mundo, para que nuestras carencias y desengaños en la criatura nos lleven al Creador en cuyo solo favor puede tenerse consuelo verdadero.
En su malestar la gente se afanó y peleó con Moisés. Los hipócritas pueden mostrar mucho afecto y parecer fervorosos en los ejercicios religiosos pero caen en el momento de la tentación. Aun los creyentes verdaderos será tentados, en momentos de aguda prueba, a afanarse, desconfiar y rezongar. Pero en cada prueba debemos echar nuestra preocupación sobre el Señor y derramar nuestros corazones ante Él. Entonces hallaremos que una voluntad sumisa, una conciencia pacífica y los consuelos del Espíritu Santo volverán soportable a la prueba más amarga, hasta agradable, sí.
Moisés hizo lo que el pueblo había descuidado hacer; él clamó al Señor. Dios proveyó bondadosamente para ellos. Él dirigió a Moisés hacia un árbol que arrojó a las aguas que, de inmediato, fueron endulzadas. Algunos hacen de este árbol un tipo de la cruz de Cristo que endulza las aguas amargas de la aflicción para todos los fieles y les capacita para regocijarse en la tribulación. Pero el israelita rebelde no saldrá mejor librado que el egipcio rebelde. La amenaza es solamente implícita, la promesa es explícita. Dios es el gran Médico. Si somos bien conservados, es Él que nos mantiene; si somos mejorados, Él es quien nos recupera. Él es nuestra vida y el largo de nuestros días. No olvidemos que somos preservados de la destrucción y librados de nuestros enemigos para ser los siervos del Señor.
En Elim tuvieron agua buena y suficiente. Aunque por un tiempo Dios puede ordenar que su pueblo acampe al lado de las aguas amargas de Mara, esa no será por siempre su suerte. No desfallezcamos en las tribulaciones.</p>
<br/>




</div>
