<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Éxodo 16</h2>
<p class="text-justify">Vv. 13-21.Al anochecer llegaron las codornices y la gente atrapó fácilmente cuantas necesitaran. El maná llegó con el rocío. Ellos lo llamaron Maná, Man hu que significa “¿Qué es esto?”“Es una porción; es lo que nuestro Dios nos ha asignado y lo tomaremos, y estemos agradecidos”. Era una comida agradable; era un alimento saludable. El maná llovía del cielo; cuando el rocío cesaba de descender, aparecía como una cosa menuda redonda, menuda como la escarcha que cubre la tierra, como la semilla del cilantro, de un color semejante al de las perlas. El maná caía sólo seis días de la semana y en doble cantidad el sexto día; se agusanaba y se descomponía si se guardaba por más de un día, excepto en el día de reposo. La gente nunca lo había visto antes. Podían molerlo en el molino, o machacarlo en un mortero, y luego hacer tortas y hornearlas. Duró los cuarenta años que los israelitas estuvieron en el desierto, por donde fueran, y cesó cuando entraron en Canaán. Todo esto muestra cuán diferente era de cualquier cosa hallada antes o ahora.
Ellos tenían que recoger el maná cada mañana. Aquí se nos enseña: -1. A ser prudentes y diligentes para proveer comida para nosotros y nuestros hogares; trabajar tranquilos y comer nuestro propio pan, no el pan del ocio o del engaño. La abundancia de parte de Dios da lugar al deber del hombre; así era aun cuando llovía maná; ellos no debían comer sino hasta haber recogido.
2. A estar contentos con lo suficiente. Quienes más tienen, tienen sólo alimento y vestimenta para sí mismos; los que tienen menos, por lo general tienen esas cosas, de modo que quien recoge mucho nada tiene que sobre y al que junta poco nada le falta. No hay desproporción entre uno y el otro en el disfrute de las cosas de esta vida, como la hay en la simple posesión de ellas.
3. A confiar en la Providencia: que duerman en paz aunque no tengan pan en sus tiendas, ni en todo el campamento, confiando en que Dios, al día siguiente, les traerá el pan cotidiano. Estaba más seguro y a salvo en el almacén de Dios que en su poder, y de ahí, vendría más dulce y más fresco. Véase aquí cuán necio es acumular. El maná acumulado por algunos, que se creyeron más sabios y mejores administradores que sus vecinos, y que quisieron abastecerse para que no les fuera a faltar al día siguiente, se agusanó y se descompuso. Resultará completamente desperdiciado lo que se ahorra codiciosamente y sin fe. Tales riquezas son corruptas, Santiago, v, 2, 3.
La misma sabiduría, poder y bondad que desde lo alto trajo para los israelitas alimento diario en el desierto, produce el alimento anualmente desde la tierra en el curso constante de la naturaleza, y nos da todas las cosas ricamente para disfrutar.</p>
<br/>
<p class="text-justify">Vv. 22-31.Aquí se menciona un séptimo día de reposo. Era conocido, no sólo antes de darse la ley en el monte Sinaí, sino antes que saliera Israel de Egipto, aun desde el principio, Génesis ii, 3. Separar un día de cada siete para la obra sagrada, y para el descanso santo, estaba establecido desde que Dios creó al hombre sobre la tierra, y es la más antigua de las leyes divinas. Al designar el séptimo día para el descanso, Él se preocupó que debido a ello no fueran a salir perdiendo; y nadie nunca saldrá perdiendo por servir a Dios. En ese día tenían que juntar suficiente para dos días y dejarlo preparado. Esto nos enseña a ordenar los asuntos familiares para que nos estorben lo menos posible en la obra del día de reposo. Hay trabajos necesarios que inevitablemente deben hacerse ese día, pero es deseable tener lo menos posible para hacer, a fin de que podamos dedicarnos más libremente a prepararnos para la vida venidera. Cuando guardaban maná en contra del mandamiento, se podría; cuando lo guardaban por una orden, era dulce y bueno; todo es santificado por la palabra de Dios y la oración. Dios no enviaba maná en el séptimo día, por tanto ellos no debían esperarlo ni salir a juntarlo. Esto mostraba que era producido en forma milagrosa.</p>
<br/>
<p class="text-justify">Vv. 32-36.Habiendo Dios provisto el maná para que fuera el alimento de su pueblo en el desierto, debían guardar una cantidad como recuerdo. El pan comido no debe olvidarse. Los milagros y las misericordias de Dios son para recordarlos. La palabra de Dios es el maná por el cual se nutren nuestras almas, Mateo iv, 4. Las consolaciones del Espíritu son maná escondido, Apocalipsis ii, 17. Estas vienen del cielo, como el maná, y son el sustento y el consuelo de la vida divina en el alma, mientras estamos en el desierto de este mundo. Cristo en la palabra es para aplicarlo al alma y los medios de gracia son para usarse. Cada uno de nosotros debe juntar para sí mismo y debe hacerlo en la mañana de nuestros días, la mañana de nuestras oportunidades; si lo dejamos irse, puede que se haga muy tarde para recoger. El maná no es para acumularlo sino para comérselo; quienes han recibido a Cristo deben vivir por fe en Él, y no recibir en vano su gracia. Hubo maná suficiente para todos, suficiente para cada uno, y nadie tuvo demasiado; así, pues, en Cristo hay suficiente pero no más de lo que necesitamos. Los que comieron maná, volvieron a tener hambre, murieron finalmente, y de muchos de ellos no se agradó Dios; mientras los que se alimentaron de Cristo por fe, nunca volverán a tener hambre ni morirán jamás y de ellos se agradará Dios para siempre. Busquemos fervorosamente la gracia del Espíritu Santo para que convierta todo nuestro conocimiento de la doctrina de Cristo crucificado en el alimento espiritual de nuestras almas por fe y amor.</p>
<br/>




</div>
