<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Éxodo 14</h2>
<p class="text-justify">Vv. 1-9.Faraón pensó que todo Israel estaba atrapado en el desierto y que sería presa fácil. Pero Dios dijo: Seré glorificado en Faraón. Siendo todos los hombres hechos para honra de su Hacedor, Él será honrado en aquellos por quienes Él no es honrado. Lo que pareciera ser para la ruina de la iglesia a menudo suele ser utilizado para ruina de los enemigos de la iglesia. Aunque Faraón satisfizo su maldad y venganza, él ayudó a que se cumplieran los consejos de Dios acerca de él. Aunque había dejado salir a Israel con toda razón, ahora estaba enojado consigo mismo por haberlo hecho. Dios hace que la envidia y furia de los hombres contra su pueblo, sea un tormento para ellos mismos. Los que vuelven sus rostros al cielo y viven piadosamente en Cristo Jesús deben esperar el acoso de las tentaciones y terrores de Satanás. Él no dejará mansamente que nadie salga de su servicio.</p>
<br/>
<p class="text-justify">Vv. 10-14.No había camino abierto para Israel, sino hacia arriba y, de ahí, vino la liberación de ellos. Nosotros podemos estar en el camino del deber, siguiendo a Dios, y avanzando hacia el cielo, pero podemos estar rodeados de tribulaciones. Algunos clamaron al Señor; el temor los hizo orar y eso estuvo bien. Dios nos pone en aprietos para ponernos de rodillas. Otros clamaron contra Moisés; el miedo los hizo murmurar como si Dios no fuera aún capaz de hacer milagros. Ellos riñeron con Moisés por haberlos sacado de Egipto y, así, estaban enojados con Dios por la bondad más grande que se les había hecho; así de groseros son los absurdos de la incredulidad.
Moisés dice: No temáis. Cuando no podamos salir de los problemas, siempre es nuestro deber e interés, ponernos por sobre nuestros temores; que aviven nuestras oraciones y esfuerzos, pero que no silencien nuestra fe y esperanza. -“Estad firmes”; no penséis en salvaros a vosotros mismos luchando o huyendo; esperad las órdenes de Dios y obedecedlas. Conservad la serenidad, confiados en Dios para que penséis pacíficamente en la gran salvación que Dios está por obrar por vosotros. Si Dios permite que su pueblo esté en aprietos, hallará el camino para sacarlos.</p>
<br/>
<p class="text-justify">Vv. 15-20.Las silenciosas oraciones de fe de Moisés prevalecieron delante de Dios más que los fuertes gritos de terror de Israel. La nube y la columna de fuego iban tras ellos donde necesitaban guardia, y eran un muro entre ellos y sus enemigos. La palabra y providencia de Dios tienen un lado negro y tenebroso para el pecado y los pecadores, pero un lado luminoso y agradable para el pueblo del Señor. Aquel que separó la luz de las tinieblas, Génesis i, 4, asignó la oscuridad a los egipcios y la luz a los israelitas. Esa diferencia habrá entre la herencia de los santos en luz y las negras tinieblas que será la porción de los hipócritas para siempre.</p>
<br/>
<p class="text-justify">Vv. 21-31.La división del Mar Rojo fue terror para los cananeos, Josué ii, 9, 10; la alabanza y el triunfo de los israelitas, Salmo cxiv, 3; cvi, 9; cxxxvi, 13. Fue un tipo de bautismo, 1 Corintios x, 1, 2. El paso de los israelitas en medio del mar era tipo de la conversión de almas, Isaías xi, 15; y que los egipcios fueran ahogados en él era tipo de la ruina final de los pecadores impenitentes.
Dios mostró su omnipotencia abriendo un paso en medio de las aguas, de unas cuantas millas de largo. Dios puede llevar a su pueblo a través de las dificultades más grandes, y hacer camino donde no haya. Fue un ejemplo de su favor maravilloso hacia su Israel. Ellos pasaron en medio del mar, caminaron en seco por el fondo del mar. Fue hecho para animar al pueblo de Dios de todas las épocas para que confíen en Dios en las dificultades más grandes. ¿Qué no puede hacer el que hizo esto? ¿Qué no hará Él por quienes le temen y aman, puesto que hizo esto por los israelitas quejosos e incrédulos? -Luego sobrevino la ira recta y justa de Dios sobre sus enemigos y los de su pueblo. La ruina de los pecadores la acarrean ellos mismos por su propio furor y soberbia. Ellos pudieran haber dejado en paz a Israel, pero no quisieron; ahora les gustaría huir del rostro de Israel, pero no pueden. Los hombres no se convencen hasta que es demasiado tarde, de que los que se meten contra el pueblo de Dios, lo hacen para su propio perjuicio.
Se ordenó a Moisés que extendiera su mano sobre el mar; las aguas regresaron y ahogaron a toda la hueste de los egipcios. Faraón y sus siervos, que se habían endurecido mutuamente en pecado, juntos cayeron ahora, sin escapar ninguno. Los israelitas vieron muertos a los egipcios sobre las arenas. El espectáculo los afectó mucho. Cuando los hombres ven las obras de Dios y se dan cuenta del beneficio recibido, le temen y confían en Él. ¡Qué bueno sería para nosotros si siempre estuviéramos de buen ánimo, como a veces pasa! He aquí el fin hacia el cual puede mirar el cristiano. Sus enemigos arden de furor y son poderosos; pero mientras él esté firmemente sostenido por Dios, pasará a salvo las olas, guardado por el mismo poder de su Salvador, que descenderá contra cada enemigo espiritual. Los enemigos de su alma que haya visto hoy, no los verá nunca más.</p>
<br/>




</div>
