<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Ezequiel 1</h2>
<p class="text-justify">Vv. 1-14.Misericordia es que nos traigan la palabra de Dios y deber es atenderla con diligencia cuando estamos afligidos. La voz de Dios vino con plenitud de luz y poder por el Espíritu Santo. Estas visiones parecen haber sido enviadas para poseer la mente del profeta con pensamientos grandes y elevados de Dios. Para golpear con terror a los pecadores. Para hablar consuelo a los que temían a Dios y se humillaban.
En los versículos 4-14 está la primera parte de la visión; representa a Dios atendido y servido por una vasta compañía de ángeles que son, todos, sus mensajeros, sus ministros que ejecutan sus mandamientos. Esta visión impresionaría la mente con arrobamiento y temor solemne del descontento divino aunque suscitando expectativas de bendiciones.
El fuego está rodeado de gloria. Aunque busquemos no podemos hallar a Dios a la perfección pero, de todos modos, vemos el fulgor que lo rodea. La semejanza de los seres vivientes sale del medio del fuego; los ángeles derivan su ser y poder de Dios. Ellos tienen el entendimiento del hombre y mucho más. Un león se destaca en fuerza y arrojo. Un buey se destaca en diligencia y paciencia, en el cumplimiento infatigable del trabajo que tiene que hacer. El águila se destaca por la rapidez y la vista muy aguda y por remontarse muy alto; y los ángeles que superan al hombre en todos esos aspectos, se presentan con ese aspecto. Los ángeles tienen alas; y cualquier cosa que Dios les mande, no pierden tiempo. Ellos están erguidos, firmes y constantes. No sólo tenían alas para moverse, sino manos para la acción. Muchas personas son rápidas, pero no son activas, se apresuran, pero sin hacer nada con propósito; tienen alas, pero no manos. Sin embargo, donde quiera que las alas de los ángeles los llevaran, tenían sus manos consigo para hacer lo que el deber requería. Cualesquiera fuera el servicio que los ocupaba, iban directo a ellos cada vez. Cuando vamos derecho, vamos adelante; cuando servimos a Dios con un solo corazón, hacemos obra. Ellos no se volvían cuando iban. Ellos no cometían errores y su obra no había que volver a hacerla. Ellos no retaceaban sus actividades para entretenerse con cualquier cosa. Ellos iban donde el Espíritu de Dios quería que fueran.
El profeta vio a estos seres vivientes por su propia luz, porque su aspecto era como de brasas de fuego; son serafines o “ardientes”lo cual denota el ardor de su amor por Dios y el ferviente celo a su servicio.
Nosotros podemos aprender lecciones provechosas de los temas en que podemos entrar o entender por completo. Pero atendamos a las cosas que se relacionan a nuestra paz y deber, y dejemos las cosas secretas al único Señor al cual le pertenecen.</p>
<br/>
<p class="text-justify">Vv. 15-25.La providencia, representada por las ruedas, produce cambios.
A veces, un rayo de la rueda está arriba, a veces otro; pero el movimiento de la rueda sobre su propio eje es uniforme y constante. No tenemos que desfallecer en la adversidad; las ruedas giran y nos levantarán en el momento debido, mientras quienes presumen de prosperidad, no saben cuán pronto pueden ser derribados.
La rueda está cerca de los seres vivientes; los ángeles son empleados como ministros de la providencia de Dios. El espíritu de los seres vivientes estaba en las ruedas; la misma sabiduría, poder, y santidad de Dios que guía y gobierna a los ángeles, ordena por ellos todos los sucesos en este mundo de abajo. La rueda tenía cuatro caras, denotando eso que la providencia de Dios se ejerce en todas sus partes. Mire de todas maneras la rueda de la providencia, tiene una cara hacia usted. Su aspecto y obra era como de una rueda en el medio de otra rueda. Las disposiciones de la Providencia nos parecen oscuras, confusas y son innumerables, pero todas están sabiamente ordenadas para lo mejor.
El movimiento de las ruedas era uniforme, regular y constante. Iban como mandaba el Espíritu, por tanto, no retornaban. No tenemos que deshacer, por arrepentirnos, lo que hicimos mal si seguimos la dirección del Espíritu. Los anillos o bordes de las ruedas eran tan vastos que, cuando se ponían en movimiento, el profeta temió mirarlos. La consideración de la altura y profundidad de los consejos de Dios debe arrobarnos con asombro. Estaban llenas de ojos en su contorno. Los movimientos de la Providencia son, todos, dirigidos por la sabiduría infinita. Todos los hechos están determinados por los ojos del Señor, que están en todas partes contemplando el mal y el bien; porque no existe cosa tal como la suerte o la fortuna.
El firmamento de arriba era como cristal, glorioso pero en forma terrible. Eso que nosotros consideramos que es una nube negra es claro como el cristal para Dios, a través del cual mira a todos los habitantes de la tierra. Cuando los ángeles despertaron a un mundo desconsiderado, ellos bajaron sus alas, para que se oyera claramente la voz de Dios. La voz de la providencia es para abrir los oídos de los hombres a la voz de la palabra.
Los sonidos de la tierra deben despertar nuestra atención a la voz del cielo; porque ¿cómo escaparemos si nos alejamos de Aquel que habla desde allá?</p>
<br/>
<p class="text-justify">Vv. 26-28.El Hijo eterno, la Segunda Persona de la Trinidad, que después tomó la naturaleza humana, se denota aquí. Lo primero que se observa es un trono. Es un trono de gloria, un trono de gracia, un trono de triunfo, un trono de gobierno, un trono de juicio. Es buena nueva para los hombres que el trono por encima del firmamento esté lleno con Uno que parece, aun allí, semejanza de hombre. El trono está rodeado con un arco iris, el bien conocido sacramento del pacto, que representa la misericordia y el amor pactado de Dios a su pueblo. El fuego de la ira de Dios estaba irrumpiendo contra Jerusalén, pero se le pondrían límites; Él miraría por encima del arco y recordaría el pacto.
Todo lo que el profeta vio fue solamente para prepararlo para lo que iba a oír. Cuando cayó postrado sobre su rostro, oyó la voz de Uno que habló. Dios se deleita en enseñar al humilde. Entonces, que los pecadores se humillen ante Él. Que los creyentes piensen en su gloria, para que paulatinamente sean cambiados a su imagen por el Espíritu del Señor.</p>
<br/>




</div>
