<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Filemón 1</h2>
<p class="text-justify">Vv. 1-7.La fe en Cristo y el amor a Él debe unir a los santos más estrechamente que cualquier relación externa que pueda unir a la gente del mundo. Pablo era minucioso para recordar en sus oraciones privadas a sus amigos. Nosotros debemos recordar, mucho y frecuentemente, a los amigos cristianos según su necesidad, llevándolos en nuestros pensamientos y en nuestros corazones ante Dios. Los sentimientos y las maneras diferentes en lo que no es esencial, no deben constituir diferencia de afecto respecto a la verdad. Él pregunta por sus amigos, respecto de la verdad, el crecimiento y su fruto en la gracia, de su fe en Cristo y su amor a Él, y a todos los santos. El bien que hacía Filemón era motivo de gozo y consuelo para él y para los demás, que en consecuencia deseaban que continuara y abundara más y más en buenos frutos para gloria de Dios.</p>
<br/>
<p class="text-justify">Vv. 8-14.Patrocinar a alguien no rebaja a nadie, y ni siquiera suplicar cuando, en estricto derecho, podríamos mandar; el apóstol argumenta a partir del amor más que de la autoridad, a favor de un convertido por su intermedio, el cual era Onésimo. Aludiendo a ese nombre que significa, “provechoso”, el apóstol admite que, antes, éste no había sido provechoso para Filemón, apresurándose a mencionar el cambio por el cual se había vuelto provechoso . Las personas impías no son provechosas; no responden a la gran finalidad de su ser, pero, ¡qué cambio dichoso efectúa la conversión! De lo malo a lo bueno; de inútil, a útil. Los siervos religiosos son el tesoro de una familia. Estos tendrán conciencia de su tiempo y su tarea, y administrarán todo lo que puedan para mejor.
Ninguna perspectiva de servicio debe conducir a que alguien descuide sus obligaciones o deje de obedecer a sus superiores. Una gran prueba de arrepentimiento verdadero es volver a cumplir los deberes abandonados. Onésimo se había fugado cuando era inconverso, para menoscabo de su amo, pero ahora había visto su pecado y se había arrepentido, y estaba dispuesto y deseoso de regresar a su deber. Poco saben los hombres con qué propósito el Señor permite que algunos cambien su situación o emprendan cosas, quizá con malos motivos. Si el Señor no hubiera impedido algunos de nuestros proyectos impíos, fuéramos el reflejo de casos en que nuestra destrucción era segura.</p>
<br/>
<p class="text-justify">Vv. 15-22.Cuando hablamos de la naturaleza de un pecado u ofensa contra Dios, no debemos minimizar su mal, pero en el pecador arrepentido debemos hacerlo así, porque Dios lo cubre. Los caracteres cambiados suelen llegar a ser bendición para todos aquellos con quienes residen.
El cristianismo no elimina nuestros deberes para con los demás; nos enseña a hacerlo bien. Los verdaderos arrepentidos estarán abiertos para admitir sus faltas, como evidentemente lo hizo Onésimo con Pablo, al ser despertado y llevado al arrepentimiento; especialmente en caso de haber dañado al prójimo. La comunión de los santos no destruye las distinciones de la propiedad.
Este pasaje es un ejemplo de lo que se imputa a uno, pero es contraído por otro; y de uno que está dispuesto a responder por otro, por compromiso voluntario para que sea liberado del castigo debido a sus delitos, conforme a la doctrina de Cristo, que por su propia voluntad, soportó el castigo de nuestros pecados para que nosotros pudiéramos recibir la recompensa de su justicia.
Filemón era hijo de Pablo por la fe, pero lo trata como hermano. Onésimo era un pobre esclavo, pero Pablo ruega por él, como si pidiera algo grande para sí mismo. Los cristianos deben hacer lo que puedan para regocijo de los corazones de unos y otros. Del mundo esperan problemas; deberán hallar consuelo y gozo los unos en los otros. Cuando nos quiten algo de lo recibido por misericordias, nuestra confianza y esperanza deben estar en Dios. Debemos usar diligentemente los medios, y si nadie está a la mano, abundar en oración. Pero, aunque la oración prevalece, no merece las cosas obtenidas. Si los cristianos no se conocen en la tierra, aún la gracia del Señor Jesús estará con sus espíritus y pronto se reunirán ante el trono para unirse para siempre a admirar las riquezas del amor redentor. El ejemplo de Onésimo puede dar ánimo a los pecadores más viles para regresar a Dios, pero está vergonzosamente pervertido el que por ello se siente estimulado a persistir en los malos rumbos. ¿No son muchos quitados en sus pecados mientras otros se endurecen en ellos? No hay que resistir las convicciones actuales , no vaya a ser que nunca más vuelvan.</p>
<br/>
<p class="text-justify">Vv. 23-25.Nunca encuentran más gozo de Dios los creyentes que cuando sufren juntos por Él. La gracia es el mejor deseo para nosotros mismos y para el prójimo; con ella empieza y termina el apóstol. Toda gracia es de Cristo; Él la adquirió y Él la concede. ¿Qué más necesitamos para hacernos felices, que tener la gracia de nuestro Señor Jesucristo con nuestro espíritu? Hagamos ahora lo que debemos hacer en el último suspiro. Entonces, los hombres están dispuestos a renunciar al mundo y a preferir la porción mínima de gracia y fe antes que un reino.</p>
<br/>




</div>
