<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Filipenses 3</h2>
<p class="text-justify">Vv. 1-11.Los cristianos sinceros se regocijan en Cristo Jesús. El profeta trata de perros mudos a los falsos profetas, Isaías lvi, 10, a lo cual parece referirse el apóstol. Perros por su malicia contra los fieles profesantes del evangelio de Cristo, que les ladran y los muerden. Imponen las obras humanas oponiéndolas a la fe de Cristo, pero Pablo los llama hacedores de iniquidad.
Los trata de mutiladores, porque rasgan la Iglesia de Cristo y la despedazan. La obra de la religión no tiene propósito alguno si el corazón no está en ella; debemos adorar a Dios con la fuerza y la gracia del Espíritu divino. Ellos se regocijan en Cristo Jesús, no solo en el deleite y cumplimiento externo. Nunca nos resguardaremos con demasía de quienes se oponen a la doctrina de la salvación gratuita, o abusan de ella.
Para gloriarse y confiar en la carne, el apóstol hubiera tenido muchos motivos como cualquier hombre. Pero las cosas que consideró ganancia mientras era fariseo, y las había reconocido, las consideró como pérdida por Cristo. El apóstol no les pedía que hicieran algo fuera de lo que él mismo hacía; ni que se aventuraran en algo, sino en aquello en lo cual él mismo arriesgó su alma inmortal. Él considera que todas esas cosas no eran sino pérdida comparadas con el conocimiento de Cristo, por fe en su persona y salvación.
Habla de todos los deleites mundanos y de los privilegios externos que buscaban en su corazón un lugar junto a Cristo, o podían pretender algún mérito y algo digno de recompensa, y los cuenta como pérdida, pero puede decirse que es fácil decirlo, pero, ¿qué haría cuando llegara la prueba? Había sufrido la pérdida de todo por los privilegios de ser cristiano. Sí, no sólo los consideraba como pérdida, sino como la basura más vil, sobras tiradas a los perros; no sólo menos valiosas que Cristo, sino en sumo grado despreciables cuando se las compara con Él.
El verdadero conocimiento de Cristo modifica y cambia a los hombres, sus juicios y modales, y los hace como si fueran hechos de nuevo. El creyente prefiere a Cristo sabiendo que es mejor para nosotros estar sin todas las riquezas del mundo que sin Cristo y su palabra. Veamos a qué resolvió aferrarse el apóstol: a Cristo y el cielo. Estamos perdidos, sin justicia con la cual comparecer ante Dios, porque somos culpables. Hay una justicia provista para nosotros en Jesucristo, la que es justicia completa y perfecta. Nadie puede tener el beneficio de ella si confía en sí mismo. La fe es el medio establecido para solicitar el beneficio de la salvación. Es por fe en la sangre de Cristo. Somos hechos conformes a la muerte de Cristo cuando morimos al pecado como Él murió por el pecado; y el mundo nos es crucificado como nosotros al mundo por la cruz de Cristo. El apóstol está dispuesto a hacer o sufrir cualquier cosa para alcanzar la gloriosa resurrección de los santos. Esta esperanza y perspectiva lo hacen pasar por todas las dificultades de su obra. No espera lograrlo por su mérito ni su justicia propia sino por el mérito y la justicia de Jesucristo.</p>
<br/>
<p class="text-justify">Vv. 12-21.Esta sencilla dependencia y fervor de alma no se mencionan como si el apóstol hubiera alcanzado el premio o ya fuera perfecto a semejanza del Salvador. Olvida lo que queda detrás para no darse por satisfecho por las labores pasadas o las actuales medidas de gracia. Se extiende adelante, prosigue hacia la meta; expresiones que demuestran gran interés por llegar a ser más y más como Cristo.
El que corre una carrera nunca debe detenerse antes de la meta; debe seguir adelante tan rápido como pueda; de esta manera, los que tienen el cielo en su mira, deben aún seguir adelante en santo deseo, esperanza y esfuerzo constante. La vida eterna es la dádiva de Dios, pero está en Cristo Jesús; debe venirnos por medio de su mano, de la manera que Él la logró para nosotros. No hay forma de llegar al cielo como a nuestra casa, sino por medio de Cristo nuestro Camino. Los creyentes verdaderos, al buscar esta seguridad y al glorificarlo, buscarán más de cerca parecerse a Él en sus padecimientos y muerte, muriendo al pecado y crucificando la carne con sus pasiones y concupiscencias. En estas cosas hay una gran diferencia entre los cristianos verdaderos, pero todos conocen algo de ellas. Los creyentes hacen de Cristo su todo en todo y ponen sus corazones en el otro mundo. Si difieren unos de otros, y no tienen el mismo juicio en cuestiones menores, aún así, no deben juzgarse unos a otros, porque todos se reúnen ahora en Cristo y esperan reunirse en el cielo en breve. Que ellos se unan en todas las cosas grandes en que concuerden y esperen más luz en cuanto a las cosas menores en que difieren.
A los enemigos de la cruz de Cristo no les importa nada, sino sus apetitos sensuales. El pecado es la vergüenza del pecador, especialmente cuando se glorían en eso. El camino de los que se ocupan de las cosas terrenales puede parecer agradable, pero la muerte y el infierno están al final. Si elegimos el camino de ellos, compartiremos su final.
La vida del cristiano está en el cielo donde está su Cabeza y su hogar, y donde espera estar dentro de poco tiempo; pone sus afectos en las cosas de arriba y donde esté su corazón, ahí estará su tesoro.
Hay gloria reservada para los cuerpos de los santos, gloria que se hará presente en la resurrección. Entonces el cuerpo será hecho glorioso; no sólo resucitado a la vida, sino resucitado para mayor ventaja. Nótese el poder por el cual será efectuado este cambio. Estemos siempre preparados para la llegada de nuestro Juez; esperando tener nuestros cuerpos viles cambiados por su poder todopoderoso, y recurriendo diariamente a Él para que haga una nueva creación de nuestras almas para la piedad; para que nos libre de nuestros enemigos y que emplee nuestros cuerpos y nuestras almas como instrumentos de justicia a su servicio.</p>
<br/>




</div>
