<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Filipenses 4</h2>
<p class="text-justify">V. 1.La esperanza y la perspectiva creyente de la vida eterna deben afirmarnos y hacernos constantes en nuestra carrera cristiana. Hay diferencia de dones y gracias, pero estando renovados por el mismo Espíritu, somos hermanos. Estar firmes en el Señor es afirmarse en su fuerza y por su gracia.</p>
<br/>
<p class="text-justify">Vv. 2-9.Los creyentes sean unánimes y estén dispuestos a ayudarse mutuamente. Como el apóstol había hallado el beneficio de la asistencia de ellos, sabía cuán consolador sería para sus colaboradores tener la ayuda de otros. Procuremos asegurarnos que nuestros nombres estén escritos en el libro de la vida.
El gozo en Dios es de gran importancia en la vida cristiana; es necesario llamar continuamente a ello a los cristianos. El gozo supera ampliamente todas las causas de pesar. Los enemigos deben darse cuenta de lo moderados que eran en cuanto a las cosas externas, y con cuánta moderación sufrían las pérdidas y las dificultades. El día del juicio llegará pronto, con la plena redención de los creyentes y la destrucción de los impíos.
Es nuestro deber mostrar cuidadosa diligencia en armonía con una sabia previsión y con la debida preocupación; pero hay un afanarse de temor y desconfianza que es pecado y necedad, y sólo confunde y distrae la mente. Como remedio contra la preocupación que confunde se recomienda la constancia en la oración. No sólo los tiempos establecidos de oración, sino constancia en todo por medio de la oración. Debemos unir la acción de gracias con las oraciones y las súplicas; no sólo buscar provisiones de lo bueno, sino reconocer las misericordias que recibimos. Dios no necesita que le digamos nuestras necesidades o deseos porque los conoce mejor que nosotros, pero quiere que le demostremos que valoramos su misericordia y sentimos que dependemos de Él. La paz con Dios, esa sensación consoladora de estar reconciliados con Dios, y de tener parte de su favor, y la esperanza de la bendición celestial, son un bien mucho más grande de lo que puede expresarse con plenitud. Esta paz mantendrá nuestros corazones y mentes en Jesucristo; nos impedirá pecar cuando estemos sometidos a tribulaciones y de hundirnos debajo de ellas; nos mantendrá calmos y con una satisfacción interior.
Los creyentes tienen que conseguir y mantener un buen nombre; un nombre para todas las cosas con Dios y los hombres buenos.
Debemos recorrer en todo los caminos de la virtud y permanecer en ellos; entonces, sea que nuestra alabanza sea o no de los hombres, será de Dios. El apóstol es un ejemplo. Su doctrina armonizaba con su vida. La manera de tener al Dios de paz con nosotros es mantenernos dedicados a nuestro deber. Todos nuestros privilegios y la salvación proceden de la misericordia gratuita de Dios, pero el goce de ellos depende de nuestra conducta santa y sincera. Estas son obras de Dios, pertenecientes a Dios, y a Él solo se deben atribuir y a nadie más, ni hombres, ni palabras ni obras.</p>
<br/>
<p class="text-justify">Vv. 10-19.Buena obra es socorrer y ayudar a un buen ministro en dificultades. La naturaleza de la verdadera simpatía cristiana no es tan sólo sentirse preocupados por nuestros amigos en sus problemas, sino hacer lo que podamos para ayudarlos. El apóstol solía estar en cadenas, prisiones y necesidades, pero en todo aprendió a estar contento, a llevar su mente a ese estado, y aprovechar el máximo de eso. El orgullo, la incredulidad, el vano insistir en algo que no tenemos y el descontento variable por las cosas presentes, hacen que los hombres estén disgustados aun en circunstancias favorables. Oremos por una sumisión paciente y por esperanza cuando estemos aplastados; por humildad y una mente celestial cuando estemos jubilosos. Es gracia especial tener siempre un temperamento mental sereno. Cuando estemos humillados no perdamos nuestro consuelo en Dios ni desconfiemos de su providencia, ni tomemos un camino malo para nuestra satisfacción. En estado próspero no seamos orgullosos ni nos sintamos seguros ni mundanos. Esta es una lección mucho más difícil que la otra, porque las tentaciones de la plenitud y de la prosperidad son más que las de la aflicción y la necesidad.
El apóstol no tenía la intención de moverlos a dar más, sino exhortarlos a una bondad que tendrá una recompensa gloriosa en el más allá. Por medio de Cristo tenemos la gracia para hacer lo que es bueno, y por medio de Él hemos de esperar la recompensa; como tenemos todas las cosas por Él, hagamos todas las cosas por Él y para su gloria.</p>
<br/>
<p class="text-justify">Vv. 20-23.El apóstol termina con alabanzas para Dios. Debemos mirar a Dios en todas nuestras debilidades y temores, no como enemigo, sino como Padre, dispuesto a compadecerse de nosotros y a ayudarnos. Debemos dar gloria a Dios como Padre. La gracia y el favor de Dios, que disfrutan las almas reconciliadas, con todas las virtudes en nosotros, que fluyen de Él, son todas adquiridas para nosotros por los méritos de Cristo, y aplicadas por su intercesión a nuestro favor; por lo cual se llaman con justicia, la gracia de nuestro Señor Jesucristo.</p>
<br/>




</div>
