<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Filipenses 2</h2>
<p class="text-justify">Vv. 1-4.Estas son otras exhortaciones a los deberes cristianos; a la unanimidad, a la humildad, conforme al ejemplo del Señor Jesús. La bondad es la ley del reino de Cristo, la lección de su escuela, el uniforme de su familia.
Se mencionan diversos motivos para el amor fraternal. Si esperáis o experimentáis el beneficio de las compasiones de Dios para sí mismo, sed compasivos unos con otros. Es el gozo de los ministros ver la unanimidad de su gente.
Cristo vino a hacernos humildes para que no haya entre nosotros espíritu de orgullo. Debemos ser severos con nuestras propias faltas, y rápidos para observar nuestros defectos, pero estar dispuestos para favorecer con concesiones al prójimo. Debemos cuidar bondadosamente a los demás, y no meternos en asuntos ajenos. No se puede disfrutar de paz interior ni exterior sin humildad.</p>
<br/>
<p class="text-justify">Vv. 5-11.El ejemplo de nuestro Señor Jesucristo es puesto ante nosotros. Debemos parecernos a Él en su vida, si deseamos el beneficio de su muerte.
Fijémonos en las dos naturalezas de Cristo: su naturaleza Divina y la humana. Siendo en la forma de Dios, participó de la naturaleza divina, como el eterno Hijo Unigénito de Dios, Juan i, 1, y no estimó que fuera usurpación ser igual a Dios y recibir la adoración de los hombres que corresponde a la Divinidad. Su naturaleza humana: en ella se hizo como nosotros en todo excepto el pecado. Así, humillado, por su propia voluntad, descendió de la gloria que tenía con el Padre desde antes que el mundo fuese.
Se comentan los dos estados de Cristo, el de humillación y el de exaltación. Cristo no sólo asumió la semejanza y el estilo o forma de hombre, sino el de uno de estado humilde; no se manifestó con esplendor. Toda su vida fue una vida de pobreza y sufrimientos, pero el paso más bajo fue morir la muerte de cruz, la muerte de un malhechor y de un esclavo; expuesto al odio y burla del público.
La exaltación fue de la naturaleza humana de Cristo, en unión con la divina. Todos deben rendir homenaje solemne al nombre de Jesús, no al solo sonido de la palabra, sino a la autoridad de Jesús. Confesar que Jesucristo es el Señor es para la gloria de Dios Padre; porque es su voluntad que todos los hombres honren al Hijo como honran al Padre, Juan v, 23. Aquí vemos tales motivos para el amor que se niega a sí mismo, que ninguna otra cosa podría suplir. ¿Amamos y obedecemos así al Hijo de Dios?</p>
<br/>
<p class="text-justify">Vv. 12-18.Debemos ser diligentes en el uso de todos los medios que llevan a nuestra salvación perseverando en ellos hasta el fin, con mucho cuidado no sea que con todas nuestras ventajas no lleguemos. Ocupaos en vuestra salvación, porque es Dios quien obra en vosotros. Esto nos anima a hacer lo más que podamos porque nuestro trabajo no será en vano; aún debemos depender de la gracia de Dios. La obra de la gracia de Dios en nosotros es vivificar y comprometer nuestros esfuerzos. La buena voluntad de Dios para nosotros es la causa de su buena obra en nosotros.
Cumplid vuestro deber sin murmuraciones. Cumplidlo y no le atribuyáis defectos. Preocupaos de vuestro trabajo y no lo hagáis motivo de contienda. Sed apacibles: no déis ocasión justa de ofensa. Los hijos de Dios deben distinguirse de los hijos de los hombres. Mientras más perversos sean los otros, mas cuidadosos debemos ser nosotros para mantenernos sin culpa e inocentes. La doctrina y el ejemplo coherente de los creyentes iluminará a otros y dirigirá su camino a Cristo y a la piedad, así como la luz del faro advierte a los marinos que eviten los escollos y dirige su rumbo al puerto. Tratemos de brillar así.
El evangelio es la palabra de vida, nos da a conocer la vida eterna por medio de Jesucristo. Correr connota fervor y vigor, seguir continuamente hacia delante; esfuerzo, connota constancia y aplicación estrecha.
La voluntad de Dios es que los creyentes estén con mucho regocijo; y los que estén tan felices por tener buenos ministros, tienen mucha razón para regocijarse con ellos.</p>
<br/>
<p class="text-justify">Vv. 19-30.Mejor es para nosotros cuando nuestro deber se nos hace natural. Por cierto, esto es sinceramente y no sólo por pretensión; con corazón dispuesto y puntos de vista rectos. Nuestra tendencia es preferir nuestro propio mérito, comodidad y seguridad antes que la verdad, la santidad y el deber, pero Timoteo no era así. Pablo deseaba libertad no para darse placeres, sino para hacer el bien.
Epafrodito estaba dispuesto a ir donde los filipenses para que fuera consolado con los que se habían condolido con él cuando estuvo enfermo. Parece que su enfermedad fue causada por la obra de Dios. El apóstol les pide que le amen más por esa razón. Es doblemente agradable que Dios restaure nuestras misericordias, después del gran peligro de perderlas; y esto debiera hacerlas mucho más valiosas.
Lo dado en respuesta a la oración debe recibirse con gran gratitud y gozo.</p>
<br/>




</div>
