<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Filipenses 1</h2>
<p class="text-justify">Vv. 1-7.El más alto honor de los ministros más eminentes es ser siervos de Cristo. Los que no son verdaderos santos en la tierra nunca serán santos en el cielo. Fuera de Cristo los mejores santos son pecadores e incapaces de estar delante de Dios. No hay paz sin gracia. La paz interna surge de percibir el favor divino. No hay gracia sin paz, sino de nuestro Padre Dios, la fuente y el origen de todas las bendiciones.
El apóstol fue maltratado en Filipos y vio poco fruto de su labor, pero recuerda con gozo a los filipenses. Debemos agradecer a nuestro Dios las gracias y consuelos, los dones y el servicio de otros, cuando recibimos el beneficio y Dios recibe la gloria. La obra de gracia nunca será perfeccionada sino hasta el día de Jesucristo, el día de su manifestación. Pero estemos siempre confiados en que Dios completará su buena obra en toda alma donde la haya comenzado por la regeneración, aunque no debemos confiarnos de las apariencias externas, ni en nada sino en la nueva creación para santidad. La gente es querida por sus ministros cuando reciben el beneficio de su ministerio. Los que sufren juntos en la causa de Dios deben amarse mutuamente.</p>
<br/>
<p class="text-justify">Vv. 8-11.¿No compadeceremos y no amaremos a las almas que Cristo ama y compadece? Los que abunden en alguna gracia tienen que abundar más. Probemos diferentes cosas; aprobemos lo excelente. Las verdades y las leyes de Cristo son excelentes y se recomiendan a sí mismas como tales a toda mente atenta. La sinceridad debe ser la marca de nuestra conversación en el mundo, y es la gloria de todas nuestras virtudes. Los cristianos no deben ofenderse y deben tener mucho cuidado en no ofender a Dios ni a los hermanos. Las cosas que más honran a Dios son las que más nos beneficiarán. No demos cabida a ninguna duda sobre si hay o no algún fruto bueno en nosotros. Nadie debe sentirse satisfecho con una medida pequeña de amor, conocimiento y fruto cristiano.</p>
<br/>
<p class="text-justify">Vv. 12-20.El apóstol estaba preso en Roma y para borrar el vituperio de la cruz muestra la sabiduría y la bondad de Dios en sus sufrimientos. Estas cosas le hicieron conocido donde nunca hubiera sido conocido de otro modo; debido a ellas algunos se interesaron en el evangelio. Sufrió de parte de los falsos amigos y de los enemigos. ¡Miserable carácter el de los que predican a Cristo por envidia y contienda y añaden aflicción a las cadenas que oprimían a éste, el mejor de los hombres! -El apóstol estaba cómodo en medio de todo. Debemos regocijarnos, puesto que nuestros trastornos pueden hacer bien a muchos. Todo lo que resulte para nuestra salvación es por el Espíritu de Cristo y la oración es el medio designado para buscarlo. Nuestras expectativas y esperanzas más fervientes no deben ser lograr que nos honren los hombres ni escapar de la cruz, sino ser sustentado en medio de la tentación, el desprecio y la aflicción. Dejemos a Cristo la manera en que nos hará útiles para su gloria, ya sea por labores o sufrimientos, por diligencia o paciencia, por vivir para su honra trabajando para Él o morir para su honra sufriendo por Él.</p>
<br/>
<p class="text-justify">Vv. 21-26.La muerte es una pérdida grande para el hombre carnal y mundano, porque pierde todas las bendiciones terrenales y todas sus esperanzas, pero para el creyente verdadero es ganancia, porque es el fin de todas sus debilidades y miserias. Le libra de todos los males de la vida y le lleva a poseer el bien principal. La disyuntiva del apóstol no era entre vivir en este mundo y vivir en el cielo; entre ellos no hay comparación; era entre servir a Cristo en este mundo y disfrutar de Él en el otro. No entre dos cosas malas, sino entre dos cosas buenas: vivir para Cristo o estar con Él. Véase el poder de la fe y de la gracia divina; puede hacernos dispuestos para morir. En este mundo estamos rodeados de pecado, pero estando con Cristo escaparemos del pecado y de la tentación, la tristeza y la muerte para siempre. Pero quienes tienen más razón para partir deben estar dispuestos a quedarse en el mundo en la medida que Dios tenga alguna obra para que ellos hagan. Mientras más inesperadas sean las misericordias antes que ellos se vayan, más de Dios se verá en ellos.</p>
<br/>
<p class="text-justify">Vv. 27-30.Los que profesan el evangelio de Cristo deben vivir como corresponde a los que creen las verdades del evangelio, se someten a las leyes del evangelio y dependen de las promesas del evangelio. La palabra original por “comportéis”connota la conducta de los ciudadanos que procuran el prestigio, la seguridad, la paz y la prosperidad de su ciudad. En la fe del evangelio existe aquello por lo cual vale la pena esforzarse; hay mucha oposición y se necesita esfuerzo. El hombre puede dormirse e irse al infierno, pero el que quiere ir al cielo, debe cuidar de sí y ser diligente. Puede que haya unanimidad de corazón y afecto entre los cristianos donde haya diversidad de juicio sobre muchas cosas.
La fe es el don de Dios por medio de Cristo; la habilidad y la disposición para creer son de Dios. Si sufrimos reproche y pérdida por Cristo, tenemos que contarlos como dádiva y apreciarlos como tales. Pero la salvación no debe atribuirse a las aflicciones corporales, como si las aflicciones y las persecuciones mundanas la hicieran merecer; la salvación es únicamente de Dios: la fe y la paciencia son sus dádivas.</p>
<br/>




</div>
