<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Gálatas 2</h2>
<p class="text-justify">Vv. 1-10.Nótese la fidelidad del apóstol al dar un relato completo de la doctrina que había predicado entre los gentiles, y que aún estaba resuelto a predicar, la del cristianismo, libre de toda mezcla con el judaísmo. Esta doctrina sería desagradable para muchos, pero él no temía reconocerla. Su preocupación era que no decayera el éxito de sus labores pasadas, o fuera estorbado en su utilidad futura. Mientras dependamos claramente de Dios para el éxito en nuestras labores, debemos usar toda la cautela necesaria para eliminar errores, y contra los opositores. Hay cosas que se pueden cumplir lícitamente, pero cuando no se pueden hacer sin traicionar la verdad, deben rechazarse. No debemos dar lugar a ninguna conducta por la cual sea rechazada la verdad del evangelio.
Aunque Pablo hablaba con los otros apóstoles, no recibió de ellos nada nuevo para su conocimiento o autoridad. Se dieron cuenta de la gracia que le fue dada, y le dieron a él y a Bernabé, la diestra de compañía, por la cual reconocían que había sido nombrado en el oficio y dignidad de apóstol como ellos mismos. Acordaron que los dos debían ir a los gentiles mientras ellos seguían predicando a los judíos; juzgaron que agradaba a Cristo la idea de dividirse así en la obra.
Aquí aprendemos que el evangelio no es nuestro, sino de Dios, y que los hombres somos sólo sus custodios; por esto tenemos que alabar a Dios. El apóstol mostró su disposición caritativa y cuán dispuesto estaba para aceptar como hermanos a los judíos convertidos, aunque muchos de ellos dificilmente permitirían igual favor a los gentiles convertidos; pero la sola diferencia de opinión no era razón para que no les ayudara. He aquí un patrón de la caridad cristiana, que debemos extender a todos los discípulos de Cristo.</p>
<br/>
<p class="text-justify">Vv. 11-14.A pesar del carácter de Pedro, cuando Pablo lo vio actuando como para dañar la verdad del evangelio y la paz de la iglesia, no tuvo temor de reprenderlo. Cuando vio que Pedro y los demás no vivían conforme al principio que enseña el evangelio, y que ellos profesaban, a saber, que por la muerte de Cristo fue derribado el muro divisorio entre judío y gentil, y la observancia de la ley de Moisés dejaba de tener vigencia; como la ofensa de Pedro era pública, él lo reprendió públicamente. Hay una diferencia muy grande entre la prudencia de San Pablo, que sustentó, y usó por un tiempo, las ceremonias de la ley como no pecaminosas, y la conducta tímida de San Pedro que, por apartarse de los gentiles, llevó a otros a pensar que estas ceremonias eran necesarias.</p>
<br/>
<p class="text-justify">Vv. 15-19.Habiendo así demostrado Pablo que él no era inferior a ningún apóstol, ni al mismo Pedro, habla de la gran doctrina fundamental del evangelio. ¿Para qué creímos en Cristo? ¿No fue para que fuésemos justificados por la fe de Cristo? De ser así, ¿no es necio volver a la ley, y esperar ser justificados por el mérito de obras morales, de los sacrificios o de las ceremonias? La ocasión de esta declaración surgió indudablemente de la ley ceremonial; pero el argumento es tan fuerte contra toda dependencia de las obras de la ley moral para lograr la justificación. Para dar mayor peso a esto se agrega aquí, “pero si buscando ser justificados en Cristo, también nosotros somos hallados pecadores, ¿es por eso Cristo ministro de pecado?”Esto sería muy deshonroso para Cristo y también muy dañino para ellos. Considerando la misma ley, entendió que no debía esperar la justificación por las obras de la ley, y que ahora ya no había más necesidad de los sacrificios y sus purificaciones, puesto que fueron terminados en Cristo al ofrecerse Él como sacrificio por nosotros. No esperaba ni temía nada de ello; no más que un hombre muerto para sus enemigos. Pero el efecto no era una vida descuidada e ilícita. Era necesario que él pudiera vivir para Dios y dedicado a él por medio de los motivos y la gracia del evangelio. No es objeción nueva, pero sumamente injusto, que la doctrina de la justificación por la sola fe, tienda a estimular a la gente a pecar. No es así, porque aprovecharse de la libre gracia, o de su doctrina, es vivir en pecado, es tratar de hacer de Cristo ministro de pecado, idea que debiera estremecer a todos los corazones cristianos.</p>
<br/>
<p class="text-justify">Vv. 20, 21.Aquí, en su propia persona, el apóstol describe la vida espiritual y oculta del creyente. El viejo hombre ha sido crucificado, Romanos vi, 6; pero el nuevo hombre está vivo; el pecado es mortificado y la gracia es vivificada. Tiene las consolaciones y los triunfos de la gracia, pero esa gracia no es de sí mismo sino de otro. Los creyentes se ven viviendo en un estado de dependencia de Cristo. De ahí que, aunque viva en la carne, sin embargo, no vive según la carne. Los que tienen fe verdadera, viven por esa fe; y la fe se afirma en que Cristo se dio a sí mismo por nosotros. -Él me amó y se dio por mí. Como si el apóstol dijera: El Señor me vio huyendo más y más de Él. Tal maldad, error e ignorancia estaban en mi voluntad y entendimiento, y no era posible que yo fuera rescatado por otro medio que por tal precio. Considérese bien este precio.
Aquí nótese la fe falsa de muchos. Su confesión concuerda: tienen la forma de la piedad sin el poder de ella. Piensan que creen bien los artículos de la fe, pero están engañados. Porque creer en Cristo crucificado no sólo es creer que fue crucificado, sino también creer que yo estoy juntamente crucificado con Él. Esto es conocer a Cristo crucificado. De ahí aprendemos cuál es la naturaleza de la gracia. La gracia de Dios no puede estar unida al mérito del hombre. La gracia no es gracia a menos que sea dada libremente en toda forma. Mientras más sencillamente el creyente confíe en Cristo para todo, más devotamente andará delante de Él en todas sus ordenanzas y mandamientos. Cristo vive y reina en él, y él vive aquí en la tierra por la fe en el Hijo de Dios, que obra por amor, produce obediencia y cambia a su santa imagen. De este modo, no abusa de la gracia de Dios ni la hace vana.</p>
<br/>




</div>
