<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Gálatas 6</h2>
<p class="text-justify">Vv. 1-5.Tenemos que sobrellevar las cargas los unos de los otros. Así cumplimos la ley de Cristo. Esto nos obliga a la tolerancia mutua y a la compasión de unos con otros, conforme a su ejemplo. Nos corresponde llevar las cargas de unos y otros como compañeros de viaje.
Muy corriente es que el hombre se considere más sabio y mejor que todos los demás hombres, y bueno para mandarlos. Se engaña a sí mismo; pretende lo que no tiene, se engaña a sí mismo, y tarde o temprano, se hallará con lamentables efectos. Este nunca ganará la estima de Dios ni la de los hombres. Se advierte a cada uno que examine su obra. Mientras mejor conozcamos nuestro corazón y nuestros modales, menos despreciaremos a los demás y más dispuestos estaremos para ayudarles cuando tengan enfermedades y aflicciones. Cuán leves les parecen los pecados a los hombres cuando los cometen, pero los hallarán como carga pesada cuando tengan que dar cuenta a Dios de ellos. Nadie puede pagar el rescate por un hermano; y el pecado es una carga para el alma. Es una carga espiritual; y mientras menos la sienta alguien, más causa tiene para sospechar de sí. La mayoría de los hombres están muertos en sus pecados y, por tanto, no ven ni sienten la carga espiritual del pecado. Al sentir el peso y carga de nuestros pecados, debemos procurar ser aliviados por el Salvador, y darnos por advertidos contra todo pecado.</p>
<br/>
<p class="text-justify">Vv. 6-11.Muchos se excusan de la obra de la religión, aunque pueden simularla y profesarla. Pueden imponerse a los demás, pero se engañan si piensan que pueden engañar a Dios, que conoce sus corazones y sus acciones; y como Él no puede ser engañado, así no será burlado. Nuestro tiempo es tiempo de siembra; en el otro mundo segaremos lo que sembramos ahora. Hay dos clases de siembra, una para la carne, y otra para el Espíritu: así será la rendición de cuentas en el más allá. Los que llevan una vida sensual y carnal, no deben esperar otro fruto de ese camino que no sea miseria y ruina. Pero los que, bajo la dirección y el poder del Espíritu Santo, llevan una vida de fe en Cristo, y abundan en la gracia cristiana, cosecharán vida eterna del Espíritu Santo.
Todos somos muy proclives a cansarnos del deber, particularmente de hacer el bien. Debemos velar con gran cuidado y guardarnos al respecto. La recompensa se promete sólo a la perseverancia en hacer el bien.
Aquí hay una exhortación a todos para hacer el bien en donde están. Debemos tener cuidado de hacer el bien en nuestra vida y hacer de él la actividad de nuestra vida, especialmente si se presentan ocasiones nuevas, y hasta donde alcance nuestro poder.</p>
<br/>
<p class="text-justify">Vv. 12-15.Los corazones orgullosos, vanos y carnales se contentan precisamente con tanta religión como la que les ayude a simular en buena forma. Pero el apóstol profesa su propia fe, esperanza y gozo, y que su gloria principal está en la cruz de Cristo. Por la cual se significan aquí sus sufrimientos y muerte en la cruz, la doctrina de la salvación por el Redentor crucificado. Por Cristo, o por la cruz de Cristo, el mundo es crucificado para el creyente y él para el mundo. Mientras más consideremos los sufrimientos del Redentor de parte del mundo, menos probable es que amemos al mundo. Al apóstol lo afectaban tan poco sus encantos como el espectador lo sería por cualquier cosa que fuese graciosa en la cara de una persona crucificada, cuando la contempla ennegrecida en las agonías de la muerte. Él no era más afectado por los objetos que le rodeaban como alguien que expira fuera afectado con alguna de las perspectivas que sus ojos moribundos pudieran ver desde la cruz de la cual cuelga. Y en cuanto a aquellos que han creído verdaderamente en Cristo Jesús, todas las cosas les son contadas como supremamente inválidas comparadas con Él. Hay una nueva creación: las viejas cosas pasaron, he aquí los nuevos puntos de vista y las nuevas disposiciones son traídas bajo las influencia regeneradoras de Dios Espíritu Santo. Los creyentes son llevados a un nuevo mundo, y siendo creados en Cristo Jesús para nuevas obras, son formados para una vida de santidad. Es un cambio de mentalidad y corazón por el cual somos capacitados para creer en el Señor Jesús y vivir para Dios; y donde falte esta religión interior práctica, las profesiones o los nombres externos nunca la reemplazarán.</p>
<br/>
<p class="text-justify">Vv. 16-18.Una nueva creación a imagen de Cristo que demuestra fe en Él es la distinción más grande entre uno y otro hombre y una bendición declarada a todos los que andan conforme a esta regla. Las bendiciones son paz y misericordia. Paz con Dios y nuestra conciencia, y todos los consuelos de esta vida en la medida que sean necesarios. Y la misericordia, el interés en el amor y favor gratuitos de Dios en Cristo, el manantial y la fuente de todas las demás bendiciones.
La palabra escrita de Dios es la regla por la que tenemos que guiarnos, tanto por sus preceptos como por sus doctrinas. Que Su gracia esté siempre con nuestro espíritu, para santificarnos, vivificarnos y alegrarnos y que siempre nosotros estemos listos para sostener el honor de Aquel que indudablemente es nuestra vida. El apóstol tenía en su cuerpo las marcas del Señor Jesús, las cicatrices de las heridas infligidas por los enemigos perseguidores porque él se aferraba a Cristo y a la doctrina del evangelio.
El apóstol trata de hermanos suyos a los gálatas, mostrando con ellos su humildad y su tierno afecto por ellos, y se va con una oración muy seria pidiendo que ellos disfruten del favor de Cristo Jesús en sus efectos a la vez que en sus pruebas. No tenemos que desear más que la gracia de nuestro Señor Jesucristo para hacernos felices. El apóstol no ora que la ley de Moisés o la justicia de las obras sea con ellos sino que la gracia de Cristo sea con ellos; para que pueda estar en sus corazones y con sus espíritus, reviviéndoles, consolándoles y fortaleciéndoles: a todo lo cual pone su Amén; con ello significando su deseo de que así sea, y su fe en que así será.</p>
<br/>




</div>
