<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Gálatas 4</h2>
<p class="text-justify">Vv. 1-7.El apóstol trata claramente con los que querían imponer la ley de Moisés junto con el evangelio de Cristo, proponiéndose sujetar a los creyentes a su esclavitud. No podían entender plenamente el significado de la ley dada por Moisés. Como esa era una dispensación de tinieblas, era de esclavitud; ellos estaban atados a tantos ritos y observancias fatigosas, por los que se les enseñaba, y se les mantenía sujetos, como niño a tutores y curadores.
Bajo la dispensación del evangelio aprendemos el estado más feliz de los cristianos. Nótese en estos versículos las maravillas del amor y la misericordia divina, particularmente de Dios Padre al enviar a su Hijo al mundo para redimir y salvarnos; del Hijo de Dios al someterse a tanta bajeza y sufrir tanto por nosotros; y del Espíritu Santo al condescender a habitar en los corazones de los creyentes para tales propósitos de gracia. Además, las ventajas que disfrutan los cristianos bajo el evangelio. Aunque por naturaleza hijos de ira y desobediencia, ellos llegan a ser por gracia hijos del amor y participan de la naturaleza de los hijos de Dios; porque Él hará que todos sus hijos se le parezcan. El hijo mayor es el heredero entre los hombres; pero todos los hijos de Dios tendrán la herencia de los primogénitos. Que el temperamento y la conducta de los hijos muestre para siempre nuestra adopción y que el Espíritu Santo testifique a nuestros espíritus que somos hijos y herederos de Dios.</p>
<br/>
<p class="text-justify">Vv. 8-11.El cambio feliz por el cual los gálatas se volvieron de los ídolos al Dios vivo, y recibieron, por medio de Cristo, la adopción de hijos, fue el efecto de su libre y rica gracia. Ellos fueron puestos bajo la obligación mayor de mantener la libertad con que Él los hizo libres. Todo nuestro conocimiento de Dios empieza de su lado; lo conocemos porque somos conocidos por Él.
Aunque nuestra religión prohíbe la idolatría, aún hay muchos que practican la idolatría espiritual en sus corazones. Porque lo que más ama un hombre, y aquello que más le interesa, eso es su dios: algunos tienen sus riquezas como su dios; algunos, sus placeres, y otros, sus lujurias. Muchos adoran, sin saber, a un dios de su propia hechura; un dios todo hecho de misericordia sin ninguna justicia. Porque se convencen de que hay misericordia de Dios para ellos aunque no se arrepientan y sigan en sus pecados.
Es posible que los que hicieron una gran profesión de la religión, después sean desviados de la pureza y simplicidad. Mientras más misericordia haya mostrado Dios al llevar a alguien a conocer el evangelio, y sus libertades y privilegios, más grande es su pecado y necedad al tolerar que ellos mismos sean privados de ello. De aquí, pues, que todos los miembros de la iglesia externa deban aprender a temer su yo, y a sospechar de sí mismos. No debemos contentarnos con tener algunas cosas buenas en nosotros. Pablo teme que su labor fuera en vano, pero aún se esfuerza; y el hacerlo así, siga lo que siguiere, es la verdadera sabiduría y el temor de Dios. Esto debe recordar cada hombre en su puesto y llamamiento.</p>
<br/>
<p class="text-justify">Vv. 12-18.El apóstol desea que ellos sean unánimes con él en cuanto a la ley de Moisés y unidos con él en amor. Al reprender a los otros, debemos cuidar de convencerlos de que nuestra reprensión viene de una sincera consideración de la honra de Dios y la religión y del bienestar de ellos. El apóstol recuerda a los gálatas la dificultad con que trabajó cuando estuvo entre ellos por primera vez. Pero nota que fue un mensajero bien recibido por ellos. Sin embargo, ¡cuán inciertos son el favor y el respeto de los hombres! Esforcémonos por ser aceptos a Dios.
Una vez os creísteis dichosos por recibir el evangelio; ¿ahora tenéis razón para pensar lo contrario? Los cristianos no deben dejar de decir la verdad por temor de ofender al prójimo. Los falsos maestros que desviaron a los gálatas de la verdad del evangelio, eran hombres astutos. Pretendían afecto, pero no eran sinceros ni rectos. Se da una regla excelente. Bueno es ser siempre celoso de algo bueno; no sólo por una vez, o cada tanto tiempo, sino siempre. Dichoso sería para la Iglesia de Cristo si este celo fuese mejor sostenido.</p>
<br/>
<p class="text-justify">Vv. 19, 20.Los gálatas estaban listos para considerar enemigo al apóstol, pero él les asegura que era su amigo; que por ellos tenía sentimientos paternales. Duda del estado de ellos y ansía conocer el resultado de sus engaños presentes. Nada es prueba tan segura de que un pecador ha pasado al estado de justificación como que Cristo se esté formando en él por la renovación del Espíritu Santo, pero esto no puede esperarse mientras los hombres dependan de la ley para ser aceptados por Dios.</p>
<br/>
<p class="text-justify">Vv. 21-27.La diferencia de los creyentes que descansan sólo en Cristo y los que confían en la ley queda explicada por las historias de Isaac e Ismael. Estas cosas son una alegoría en que el Espíritu de Dios señala algo más además del sentido literal e histórico de las palabras. Agar y Sara eran emblemas adecuados de las dos dispensaciones diferentes del pacto. La Jerusalén celestial, la Iglesia verdadera de lo alto, representada por Sara está en estado de libertad y es la madre de todos los creyentes que nacen del Espíritu Santo. Por regeneración y fe verdadera fueron parte de la verdadera semilla de Abraham, conforme a la promesa hecha a él.</p>
<br/>
<p class="text-justify">Vv. 28-31.Se aplica la historia así expuesta. Entonces, hermanos, no somos hijos de la esclava sino de la libre. Si los privilegios de todos los creyentes son tan grandes, conforme al pacto nuevo, ¡qué absurdo sería que los convertidos gentiles estén bajo esa ley que no pudo librar a los judíos incrédulos de la esclavitud o de la condenación! -Nosotros no hubiésemos hallado esta alegoría en la historia de Sara y Agar si no nos hubiera sido señalada, pero no podemos dudar que así fue concebido por el Espíritu Santo. Es una explicación del tema, no un argumento que lo compruebe. En esto están prefigurados los dos pactos, el de obras y el de gracia, y los profesantes legales y los evangélicos. Las obras y los frutos producidos por el poder del hombre son legales, pero si surgen de la fe en Cristo son evangélicos. El espíritu del primer pacto es de esclavitud al pecado y la muerte. El espíritu del segundo pacto es de libertad y liberación; no de libertad para pecar sino en deber y para el deber. El primero es un espíritu de persecución; el segundo es un espíritu de amor. Que miren a este los profesantes que tengan un espíritu violento, duro y autoritario hacia el pueblo de Dios. Pero así como Abraham desechó a Agar, así es posible que el creyente se desvíe en algunas cosas al pacto de obras, cuando por incredulidad y negligencia de la promesa actúe en su propio poder conforme a la ley; o en un camino de violencia, no de amor, hacia sus hermanos. Sin embargo, no es su espíritu hacerlo así, de ahí que nunca repose hasta que regrese a su dependencia de Cristo. Reposemos nuestras almas en las Escrituras, y mostremos, por una esperanza evangélica y la obediencia jubilosa, que nuestra conversión y tesoro están, sin duda, en el cielo.</p>
<br/>




</div>
