<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Gálatas 1</h2>
<p class="text-justify">Vv. 1-5.San Pablo era apóstol de Jesucristo; fue expresamente nombrado por Él, en consecuencia, por Dios Padre, que es uno con Él en su naturaleza divina, y nombró Mediador a Cristo. La gracia, incluye la buena voluntad de Dios hacia nosotros, y su buena obra en nosotros; y la paz, todo ese consuelo interior o prosperidad externa que nosotros realmente necesitamos. Estas proceden de Dios Padre como fuente por medio de Jesucristo, pero nótese primero la gracia, luego la paz. No puede haber paz verdadera sin la gracia.
Cristo se dio por nuestros pecados para hacer expiación por nosotros: esto exigía la justicia de Dios y a esto se sometió libremente. Aquí debe observarse la infinita grandeza del precio pagado, y entonces, será evidente que el poder del pecado es tan grande que no podía ser quitado, de ninguna manera, salvo que el Hijo de Dios fuera dado en rescate. El que considera bien estas cosas, entiende que el pecado es lo más horrible que pueda expresarse, lo cual debiera conmovernos, y sin duda, asustarnos. Nótense bien especialmente las palabras “por nuestros pecados”. Porque aquí empieza de nuevo nuestra débil naturaleza que primero desea ser digna por sus propias obras. Desea llevar ante Él a los que están sanos y no al que necesita médico.
No sólo para redimirnos de la ira de Dios y la maldición de la ley, sino también para separarnos de las malas costumbres y prácticas, a las cuales estábamos esclavizados naturalmente. Pero en vano es que los que no han sido librados de este presente mundo malo por la santificación del Espíritu, tengan la expectativa de ser liberados de su condenación por la sangre de Jesús.</p>
<br/>
<p class="text-justify">Vv. 6-9.Los que desean establecer cualquier otro camino al cielo fuera del que revela el evangelio de Cristo, se hallarán miserablemente errados. El apóstol imprime a los gálatas la debida sensación de su culpa por abandonar el camino de la justificación según el evangelio, aunque la reprensión la hace con ternura y los retrata como arrastrados a eso por las artes de algunos que los perturbaban. Debemos ser fieles cuando reprendemos a otros, y dedicarnos, no obstante, a restaurarlos con el espíritu de mansedumbre.
Algunos desean instalar las obras de la ley en el lugar de la justicia de Cristo, y de este modo, corrompen el cristianismo. El apóstol denuncia con solemnidad, por maldito, a todo aquel que intente poner un fundamento tan falso. Todos los demás evangelios, fuera del de la gracia de Cristo, sean más halagadores para el orgullo de la justicia propia, o más favorables para las lujurias mundanas, son invenciones de Satanás. Mientras declaremos que rechazar la ley moral como regla de vida tiende a deshonrar a Cristo, y a destruir la religión verdadera, debemos también declarar que toda dependencia de las buenas obras para la justificación, sean reales o imaginarias, es igualmente fatal para los que persisten en ellas. Mientras seamos celosos de las buenas obras tengamos cuidado de no ponerlas en el lugar de la justicia de Cristo, y no proponer ninguna cosa que pudiera traicionar al prójimo con un engaño tan horrendo.</p>
<br/>
<p class="text-justify">Vv. 10-14.Al predicar el evangelio el apóstol buscaba llevar personas a la obediencia, no de los hombres, sino de Dios. Pero Pablo no deseaba alterar la doctrina de Cristo, sea para ganar el favor de ellos o evitar la furia de ellos. En un asunto tan importante no debemos temer el enojo de los hombres, ni buscar su favor usando palabras de humana sabiduría.
En cuanto a la manera en que él recibió el evangelio, fue por revelación desde el Cielo. No fue llevado al cristianismo, como muchos, sólo por la educación.</p>
<br/>
<p class="text-justify">Vv. 15-24.San Pablo fue llevado maravillosamente al conocimiento y la fe de Cristo. Todos los convertidos para salvación son llamados por la gracia de Dios; la conversión de ellos es obra de su poder y gracia que obran en ellos. De poco nos servirá que tengamos a Cristo revelado a nosotros si Él no es revelado también en nosotros. Estaba preparado para obedecer instantáneamente, sin importar su interés, crédito, comodidad mundano o la misma vida. Qué motivo de acción de gracias y de gozo es para las iglesias de Cristo cuando saben de casos semejantes para la alabanza de la gloria de su gracia, ¡sea que los hayan visto o no alguna vez! Ellos glorifican a Dios por su poder y misericordia al salvar a tales personas, y por todo el servicio hecho a su pueblo y a su causa, y el servicio que puede esperarse con posterioridad.</p>
<br/>




</div>
