<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 27</h2>
<p class="text-justify">Vv. 1-5.Las promesas del Mesías y de la tierra de Canaán habían pasado a Isaac. Ahora tenía unos 135 años de edad y sus hijos, alrededor de 75. No habiendo considerado debidamente la palabra divina referida a sus dos hijos de que el mayor serviría al menor, resolvió dar todo el honor y el poder que había en la promesa a Esaú, su hijo mayor. Nosotros somos muy buenos para tomar medidas conforme a nuestro propio razonar más que según la revelación divina y, por eso, perdemos frecuentemente nuestro camino.</p>
<br/>
<p class="text-justify">Vv. 6-17.Rebeca sabía que la bendición estaba preparada para Jacob y esperaba que él la tuviera. Pero hizo mal a Isaac al engañarlo; hizo mal a Jacob al tentarlo para que hiciera mal. Puso una piedra de tropiezo en el camino de Esaú y le dio un pretexto para odiar a Jacob y aborrecer la religión. Todos eran culpables. Era una de aquellas medidas retorcidas que a menudo se adoptan para hacer progresar las promesas divinas; como si el fin justificase o excusase los medios incorrectos. Así, pues, muchos han actuado mal con la idea de ser útiles para fomentar la causa de Cristo. La respuesta a todas esas cosas es la que Dios dirigió a Abraham: “Yo soy el Dios Todopoderoso; anda delante de mí y sé perfecto”.
Fue un decir muy apresurado de Rebeca: “Hijo mío, sea sobre mí tu maldición”. Cristo ha llevado la maldición de la ley por todos los que se uncen al yugo del mandamiento, el mandamiento del evangelio. Pero es demasiado osado que una criatura diga: “sea sobre mí tu maldición”.</p>
<br/>
<p class="text-justify">Vv. 18-29.Con cierta dificultad, Jacob se salió con la suya y obtuvo la bendición. Esta bendición es en términos muy generales. No se mencionan las misericordias distintivas del pacto con Abraham. Esto podría deberse a que Isaac pensaba en Esaú, aunque era Jacob quien estaba delante suyo. No podía ignorar la forma en que Esaú había despreciado las cosas mejores. Además, su inclinación por Esaú, al punto de no tomar en cuenta la voluntad de Dios, debe haber debilitado enormemente su propia fe en esas cosas. Por tanto, podría esperarse que la escasez estuviera en su bendición, concorde con su estado mental.</p>
<br/>
<p class="text-justify">Vv. 30-40.Cuando Esaú comprendió que Jacob había obtenido la bendición, clamó con un muy grande y amargo llanto. Viene el día en que quienes ahora se toman a la ligera las bendiciones del pacto y venden su derecho a las bendiciones espirituales por lo carente de valor, en vano las pedirán con urgencia. Isaac tembló mucho cuando se dio cuenta el engaño que le hicieron. Los que siguen la opción de sus propios afectos más que la voluntad divina, se meten en confusión. Pero él pronto se recuperó y confirmó la bendición que había dado a Jacob diciendo: Yo lo bendije y será bendito.
Los que se apartan de su sabiduría y de su gracia, de su fe y de la buena conciencia, en aras de los honores, las riquezas o los placeres de este mundo, por más que finjan celo por la bendición, se han juzgado indignos de ella y su condenación será la que les corresponde.
Una bendición corriente fue dada a Esaú. Era lo que deseaba. Los deseos débiles de felicidad sin la elección correcta del fin, y el uso correcto de los medios, engañan a muchos llevándolos a su propia ruina. Las multitudes van al infierno con sus bocas llenas de buenos deseos.
La gran diferencia es que no hay nada en la bendición de Esaú que apunte a Cristo; y sin eso, la grosura de la tierra y el producto del campo, de bien poco valen. Así, pues, por fe Isaac bendijo a sus dos hijos, según lo que debía ser su suerte.</p>
<br/>
<p class="text-justify">Vv. 41-46.Esaú aborreció a Jacob por la bendición que éste obtuvo. Así siguió por el camino de Caín, que asesinó a su hermano porque había recibido la aceptación de Dios, de la cual Caín se había hecho indigno. Esaú se propuso impedir que Jacob o su descendencia tuviera el dominio, quitándole la vida. Los hombres pueden inquietarse por los consejos de Dios, pero no pueden cambiarlos. Para evitar una tragedia Rebeca advirtió a Jacob del peligro y le aconsejó que se fuera en aras de su seguridad. No debemos esperar demasiada sabiduría y decisión aún en los más prometedores de los hijos; más bien debemos tener cuidado de mantenerlos apartados del camino del mal. Cuando leemos este capítulo no debemos dejar de observar que no debemos seguir ni al mejor de los hombres más allá de lo que hagan conforme a la ley de Dios. No debemos hacer mal para que venga bien. Aunque para cumplir sus propósitos Dios no tomó en cuenta las malas acciones registradas en este capítulo, de todos modos vemos su juicio en las penosas consecuencias para todas las partes involucradas.
Fue privilegio y ventaja particular de Jacob transmitir estas bendiciones espirituales a todas las naciones. El Cristo, el Salvador del mundo, iba a nacer de cierta familia y Jacob fue preferido y no Esaú por el beneplácito del Dios Omnipotente que ciertamente es el mejor juez de lo que es bueno y tiene el derecho indudable de dispensar sus favores según lo estime conveniente, Romanos ix, 12-15.</p>
<br/>




</div>
