<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 9</h2>
<p class="text-justify">Vv. 1-3.La bendición de Dios es la causa de nuestro bienestar. Dependemos de Él, debemos estar agradecidos de Él. No olvidemos la ventaja y el placer que tenemos del trabajo de las bestias, y el que su carne suministra. Tampoco debemos ser menos agradecidos por la seguridad que disfrutamos en cuanto a las bestias salvajes y dañinas, por el temor del hombre que Dios ha puesto en lo profundo de ellas. Vemos el cumplimiento de esta promesa todos los días y en todas partes. Este obsequio de los animales para comida garantiza plenamente el uso de ellos, pero no el abuso por glotonería y menos por crueldad. No debemos causarle dolor innecesariamente mientras vivan, ni cuando les quitamos las vidas.</p>
<br/>
<p class="text-justify">Vv. 4-7.La razón principal de prohibir comer la sangre, sin duda, se debió a que el derramamiento de sangre en los sacrificios tenía por objeto que los adoradores tuvieran su pensamiento puesto en la gran expiación; aunque también parece tener el propósito de controlar la crueldad, para que los hombres, acostumbrándose a derramar la sangre de los animales y alimentarse de ella, se pusieran insensibles frente a ello y les afectara poco la idea de derramar sangre humana.
El hombre no debe tomar su propia vida. Nuestra vida es de Dios y debemos darla solamente cuando a Él le plazca. Si precipitamos de alguna forma nuestra propia muerte, debemos responder ante Dios por ello.
Cuando Dios le pide a un hombre que responda por una vida que quitó injustamente, el homicida no puede responder y, por tanto, debe entregar la propia vida a cambio. En uno u otro momento, en este mundo o en el venidero, Dios descubrirá los crímenes y castigará aquellos homicidios cuyo castigo quedó fuera del alcance del poder del hombre. Pero hay quienes son ministros de Dios para proteger al inocente, para infundir temor a los malhechores y que no deben esgrimir en vano la espada, Romanos, xiii, 4. El homicidio deliberado debe ser siempre castigado con la muerte. A esta ley se le agrega una razón. Todavía hay remanentes de la imagen de Dios en el hombre caído, de modo que quien mata injustamente a un hombre, desfigura la imagen de Dios y lo deshonra.</p>
<br/>
<p class="text-justify">Vv. 8-17.Como el mundo antiguo fue destruido para ser un monumento de justicia, así este mundo permanece hasta ahora como un monumento de misericordia. Pero el pecado, que ahogó al mundo antiguo, quemará a este. Entre los hombres se sellan acuerdos, para que lo prometido pueda ser más solemne y para hacer que lo pactado sea más seguro para mutua satisfacción. Este pacto fue sellado con el arco iris que, probablemente, haya sido visto antes en las nubes, pero nunca como sello del pacto, hasta ahora. El arco iris aparece cuando hay mayor razón para temer que la lluvia prevalezca; entonces Dios muestra este sello de la promesa, de que no prevalecerá. Mientras más densa la nube, más brillante el arco en la nube. Así, como abundan las aflicciones amenazadoras, abundan mucho más los consuelos alentadores. El arco iris es el reflejo de los rayos del sol que brillan sobre o a través de las gotas de lluvia: toda la gloria de los sellos del pacto derivan de Cristo, el Sol de la justicia. Y Él derramará gloria sobre las lágrimas de sus santos. Un arco habla de terror, pero este no tiene cuerda ni flecha; y un arco solo hará poco daño. Es un arco, pero está dirigido hacia arriba, no hacia la tierra; pues los sellos del pacto tienen la intención de consolar, no de aterrar. Como Dios mira el arco para recordar el pacto, así nosotros debemos tener presente el pacto con fe y gratitud. Sin revelación no pudiera ser conocida esta bondadosa seguridad; y sin fe no sería útil para nosotros; y, así es tocante a los peligros aún mayores a que todos están expuestos, y en cuanto al nuevo pacto con sus bendiciones.</p>
<br/>
<p class="text-justify">Vv. 18-23.La embriaguez de Noé está registrada en la Biblia, con esa transparencia que solamente se halla en la Escritura, como caso y prueba de la debilidad e imperfección humana, aunque haya sido tomado de sorpresa por el pecado, y para mostrar que el mejor de los hombres no puede estar en pie si no depende de la gracia divina y es sostenido por ella. Cam parece haber sido un hombre malo y, probablemente, se alegró de encontrar a su padre en una situación impropia. De Noé se dice que era perfecto en sus generaciones, capitulo vi, 9; pero esto se refiere a la sinceridad, no a la perfección sin pecado. Noé, que se mantuvo sobrio en compañía de borrachos, ahora está borracho en compañía de sobrios. El que piensa que está firme, mire que no caiga. Tenemos que poner mucho cuidado cuando usamos abundantemente las buenas cosas creadas por Dios, para no usarlas en exceso, Lucas xxi, 34.
La consecuencia del pecado de Noé fue la vergüenza. Obsérvese aquí el gran mal del pecado de la ebriedad. Descubre a los hombres; cuando están ebrios delatan los males que tienen, y, entonces, se les sacan fácilmente los secretos. Los porteros borrachos mantienen las puertas abiertas. Trae desgracia a los hombres y los expone al desprecio. En la medida que los delata los avergüenza. Cuando están embriagados, los hombres dicen y hacen cosas que, estando sobrios, los haría enrojecer sólo el pensarlo. Fíjese el cuidado de Sem y Jafet para tapar la vergüenza de su padre. Hay un manto de amor que se puede poner sobre las faltas de todos, 1 Pedro iv, 8. Además de eso, hay un manto de reverencia que se puede poner sobre las faltas de los padres y de otros superiores. La bendición de Dios espera a quienes honran a sus padres, y su maldición se enciende especialmente contra quienes los deshonran.</p>
<br/>
<p class="text-justify">Vv. 24-29.Noé pronuncia una maldición sobre Canaán, el hijo de Cam; quizás este nieto suyo fuera más culpable que los demás. Aun entre sus hermanos iba a ser un esclavo de siervos, esto es, el menor y más despreciable de los siervos. Esto ciertamente apunta a las victorias obtenidas por Israel en épocas posteriores, sobre los cananeos, en las cuales fueron pasados a espada o llevados cautivos para pagar tributo. Todo el continente de África estaba poblado principalmente por los descendientes de Cam; y ¡por cuántas épocas han estado las mejores partes de ese territorio bajo el dominio de los romanos, luego de los sarracenos y, ahora, de los turcos!﻿1﻿¡Enmedio de cuánta maldad, ignorancia, barbarie, esclavitud y miseria vive la mayoría de sus habitantes! Y de los pobres negros, ¡cuántos son vendidos y comprados anualmente como bestias en el mercado y llevados de uno a otro rincón del mundo a hacer el trabajo de bestias! Pero esto de ningún modo excusa la codicia y barbarie de los que se enriquecen con el producto del sudor y la sangre de ellos. Dios no nos ha mandado a esclavizar a los negros y, sin duda, castigará severamente todas estas crueles fechorías. El cumplimiento de esta profecía, que contiene casi la historia del mundo, libera a Noé de la sospecha de haberla pronunciado por enojo personal. Prueba plenamente que el Espíritu Santo usó como ocasión la ofensa de Cam para revelar sus propósitos secretos. -“Bendito sea el Señor Dios de Sem”. La iglesia sería edificada y continuaría en la posteridad de Sem; de él vinieron los judíos, que fueron, por largo tiempo, el único pueblo profesante que tuvo Dios en el mundo. Cristo, que era Jehová Dios, en su naturaleza humana descendería de Sem; pues de él, en lo que a la carne concierne, vino Cristo. Noé también bendice a Jafet y, en él, las islas de los gentiles que fueron pobladas por su simiente. Habla de la conversión de los gentiles y entrada de ellos a la iglesia. Podemos leerlo, “Engrandezca Dios a Jafet, y habite en las tiendas de Sem”. Judíos y gentiles serán unidos en el redil del evangelio; ambos serán uno en Cristo. Noé vivió para ver dos mundos; pero siendo heredero de la justicia que es por la fe, ahora reposa en esperanza, para ver un mundo mejor que esos dos.</p>
<br/>




</div>
