<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 25</h2>
<p class="text-justify">Vv. 1-10.No todos los días, hasta de los mejores y más grandes santos, son días notables; algunos se deslizan silenciosamente; tales fueron los últimos días de Abraham. He aquí una lista de los hijos de Abraham con Cetura y la disposición que él hizo de su patrimonio. Después de nacer estos hijos puso su casa en orden, con prudencia y justicia. Hizo esto mientras estaba vivo. Sabio es que los hombres hagan lo que tengan que hacer mientras viven, en la mayor medida posible.
Abraham vivió 175 años; justo cien años más que al entrar en Canaán; todo ese tiempo fue peregrino en un país extranjero. Poco importa que nuestra estada en esta vida sea larga o corta siempre y cuando dejemos detrás un testimonio de la fidelidad y bondad del Señor, y un buen ejemplo para nuestra familia. Se nos cuenta que sus hijos Isaac e Ismael lo sepultaron. Parece que el mismo Abraham los había reunido mientras él vivía.
No cerremos la historia de la vida de Abraham sin bendecir a Dios por tal testimonio del triunfo de la fe.</p>
<br/>
<p class="text-justify">Vv. 11-18.Ismael tuvo doce hijos, cuyas familias llegaron a ser distintas tribus. Poblaron un país muy grande que yace entre Egipto y Asiria, llamado Arabia. La cantidad y la fuerza de esta familia fue el fruto de la promesa hecha a Agar y a Abraham en lo tocante a Ismael.</p>
<br/>
<p class="text-justify">Vv. 19-26.Isaac parece no haber sido muy probado sino que pasó sus días tranquilamente. Jacob y Esaú fueron respuesta a la oración; sus padres los obtuvieron por oración luego de estar mucho tiempo sin hijos. El cumplimiento de la promesa de Dios siempre es seguro, aunque suele ser lento. La fe de los creyentes prueba y ejercita su paciencia, y las misericordias largamente esperadas son mejor recibidas cuando llegan.
Isaac y Rebeca tenían presente la promesa de que todas las naciones serían benditas en su descendencia, por tanto, no solamente deseaban hijos sino que ansiaban todas las cosas que parecieran marcar el futuro carácter de ellos. Nosotros debemos preguntar al Señor en oración por todas nuestras dudas. En muchos de nuestros conflictos con el pecado y la tentación podríamos adoptar las palabras de Rebeca: “Si es así, ¿para qué vivo yo?”Si uno es hijo de Dios, ¿por qué soy tan negligente o carnal? Si uno es hijo de Dios, ¿por qué tan temeroso o tan cargado con el pecado?</p>
<br/>
<p class="text-justify">Vv. 27, 28. Esaú cazaba las bestias del campo con destreza y éxito hasta que llegó a ser un vencedor que dominaba a sus vecinos. Jacob era un hombre sencillo, que gustaba de los deleites verdaderos del retiro, más que de todos los pretendidos placeres. Él fue un extranjero y peregrino en su espíritu, y un pastor todos sus días. Isaac y Rebeca tuvieron solo estos dos hijos: uno era el favorito del padre y el otro de la madre. Aunque los padres piadosos deben sentir más afecto hacia un hijo piadoso, sin embargo, no deben mostrar preferencias. Que sus afectos los conduzcan a hacer lo que es justo y equitativo con cada hijo o surgirán males.</p>
<br/>
<p class="text-justify">Vv. 29-34.Aquí tenemos la transacción hecha entre Jacob y Esaú por la primogenitura, que era de Esaú por nacimiento pero de Jacob por la promesa. Era un privilegio espiritual y vemos el deseo de Jacob por la primogenitura pero procuró obtenerla por medios torcidos, no según su carácter de hombre sencillo. Él tenía razón al codiciar fervientemente los mejores dones; hizo mal al aprovecharse de la necesidad de su hermano. La herencia de los bienes mundanos del padre de ellos no le correspondía a Jacob y no estaba incluida en esta proposición. Pero que incluía la posesión futura de la tierra de Canaán por parte de los hijos de sus hijos, y el pacto hecho con Abraham en cuanto a Cristo la Simiente prometida. El creyente Jacob valoró estas cosas por encima de todo; el incrédulo Esaú las despreció. Aunque debemos tener el juicio de Jacob para procurar la primogenitura, debemos evitar cuidadosamente toda malicia al tratar de conseguir aun las mayores ventajas.
El guiso de Jacob agradó a los ojos de Esaú. “Te ruego que me des a comer de ese guiso rojo”; por eso fue llamado Edom o Rojo. Satisfacer el apetito sensual arruina miles de almas preciosas. Cuando los corazones de los hombres andan en pos de sus ojos, Job xxxi, 7, y cuando sirven a sus vientres, pueden tener la seguridad de que serán castigados. Si nos empeñamos en negarnos a nosotros mismos, rompemos la fuerza de la mayoría de las tentaciones. No puede suponerse que Esaú estuviera muriéndose de hambre en la casa de Isaac. Las palabras significan yo voy hacia la muerte; él parece decir: “Yo nunca viviré para heredar Canaán o ninguna de estas supuestas bendiciones futuras y lo que signifiquen para quien las tenga cuando yo esté muerto y haya partido”. Este sería el lenguaje de lo profano con que el apóstol lo califica, Hebreos xii, 16; y este menosprecio de la primogenitura es su culpa, versículo 34. Es la mayor necedad separarnos de nuestro interés en Dios, Cristo y el cielo, por las riquezas, los honores y los placeres de este mundo; es un negocio tan malo como el que vende su primogenitura por un plato de guiso.
Esaú comió y bebió, agradó a su paladar, satisfizo su apetito y, luego, se levantó descuidadamente y se fue, sin pensar seriamente ni lamentar el mal negocio que había hecho. Así, Esaú despreció su primogenitura. Por su negligencia y desprecio posteriores y justificándose en lo que había hecho, puso el asunto en el olvido. La gente es destruida no tanto por hacer lo que es malo como por hacerlo y no arrepentirse de ello.</p>
<br/>




</div>
