<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 30</h2>
<p class="text-justify">Vv. 1-13.Raquel envidiaba a su hermana: la envidia es dolerse porque el prójimo está bien; no hay pecado que sea más odioso para Dios que ese o más dañino para nuestro prójimo y nosotros mismos. Ella no consideró que Dios establece la diferencia y que en otras cosas ella tenía la ventaja. Cuidadosamente estemos vigilantes contra todos las apariciones y obras de esta pasión en nuestra mente. Que nuestro ojo no sea malo para con ninguno de nuestros consiervos porque el ojo de nuestro Amo es bueno.
Jacob amaba a Raquel y, por tanto, la reprendió por hablar mal. Las reprimendas fieles revelan un verdadero afecto. Dios puede ocupar el lugar de cualquier criatura en nosotros pero es pecado y necedad poner a una criatura en el lugar de Dios y depositar en la criatura la confianza que sólo a Él debe darse.
Jacob, convencido por Raquel, tomó a Bilha, doncella de ella, como esposa para que, conforme a las costumbres de la época, sus hijos fueran de su señora. Si su corazón no hubiera estado influido por las malas pasiones, Raquel hubiera pensado en los hijos de su hermana, más cercanos a ella y con más derecho a su cariño que los de Bilha. Pero le eran más deseables los hijos a quienes ella tenía derecho de mandar que los hijos a quienes ella tenía más razón para amar. Como ejemplo precoz de su poder sobre estos hijos, ella se complace en darles nombres que llevan en sí la marca de su rivalidad con su hermana. Véase lo que son las raíces de amargura, envidia y discordia y cuánto mal hacen entre los seres queridos.
Jacob, convencido por Lea, tomó a Zilpa, su doncella, como esposa también. Véase el poder de los celos y la rivalidad y admírese la sabiduría del designio divino, que une a un solo hombre con una sola mujer; porque Dios nos ha llamado a la paz y a la pureza.</p>
<br/>
<p class="text-justify">Vv. 14-24.El deseo de ser la madre de la Simiente prometida, bueno en sí mismo, pero a menudo demasiado grande e irregular, junto con el honor de tener muchos hijos y el reproche de ser estéril, fueron algunas causas de esta inconveniente disputa entre las hermanas. La verdad parece ser que ellas estaban influidas por las promesas de Dios a Abraham a cuya posteridad se le dio la promesa de las más ricas bendiciones, y de quienes iba a venir el Mesías.</p>
<br/>
<p class="text-justify">vv. 25-43.Pasados los catorce años, Jacob estaba deseoso de partir sin provisión, salvo la promesa de Dios. Pero en muchas formas, tenía un justo reclamo sobre la fortuna de Labán y era voluntad de Dios que él recibiera provisión de ella. Él refirió su causa a Dios en vez de acordar los salarios estipulados con Labán, cuyo egoísmo era muy grande. Pareciera que actuó honestamente cuando no se halló ningún ganado entre los suyos sino aquellos de los colores acordados. Labán pensó egoístamente que su ganado produciría pocos de color diferente de los suyos.
Se ha considerado que la conducta de Jacob después de este acuerdo, es un ejemplo de su política y administración. Pero ocurrió así a instancias de Dios y como señal de su poder. El Señor de una u otra manera defenderá la causa del oprimido y honrará a los que sencillamente confían en su providencia. Tampoco pudo Labán quejarse de Jacob puesto que no tenía nada más que lo que fuera libremente acordado; tampoco fue dañado, sino muy beneficiado por los servicios de Jacob. Que todas nuestras misericordias sean recibidas con acción de gracias y oración, para que viniendo de su generosidad, nos lleven a alabarle.</p>
<br/>




</div>
