<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 12</h2>
<p class="text-justify">Vv. 1-3.Dios eligió a Abram y lo separó de entre sus congéneres idólatras para reservar un pueblo para sí, entre los cuales se mantuviese la verdadera adoración hasta la venida de Cristo. Desde aquí en adelante Abram y su simiente son casi el único tema de la historia de la Biblia. Se probó a Abram, si amaba a Dios más que a todo y si podía dejar voluntariamente todo para ir con Dios. Sus parientes y la casa de su padre eran una constante tentación para él; no podía seguir entre ellos sin el riesgo de ser contaminado por ellos. Quienes dejan sus pecados y se vuelven a Dios ganarán lo indecible con el cambio.
La orden que Dios dio a Abram es en gran medida igual que el llamamiento del evangelio, porque los afectos naturales debe ceder el paso a la gracia divina. El pecado y todas sus oportunidades deben abandonarse, en particular, las malas compañías.
He aquí muchas promesas grandes y preciosas. Todos los preceptos de Dios van acompañados de promesas para el obediente.
1. Haré de ti una nación grande. Cuando Dios sacó a Abram de su pueblo, prometió hacerle cabeza de otro pueblo.
2. Te bendeciré. Los creyentes obedientes estarán seguros de heredar la bendición.
3. Engrandeceré tu nombre. El nombre de los creyentes obedientes ciertamente será engrandecido.
4. Serás bendición. Los hombres buenos son bendición para sus países.
5. Bendeciré a los que te bendijeren, y a los que te maldijeren maldeciré. Dios se ocupará de que nadie sea perdedor por algún servicio hecho en favor de su pueblo.
6. En ti serán benditas todas las familias de la tierra. Jesucristo es la gran bendición del mundo, la más grande que el mundo haya poseído jamás. Toda verdadera bienaventuranza en el mundo ahora o que alguna vez llegue a tener, se debe a Abram y su descendencia. Por medio de ellos tenemos una Biblia, un Salvador y un evangelio. Ellos son la cepa sobre la cual ha sido injertada la iglesia cristiana.
Abram creyó que la bendición del Todopoderoso supliría todo lo que él pudiera perder o dejar atrás, satisfaría todas sus carencias y respondería, más aun, sobrepasaría todos sus deseos, y sabía que nada sino la desgracia seguiría a la desobediencia. Este tipo de creyentes, justificados por fe en Cristo, tienen paz con Dios.
Ellos siguen en su camino a Canaán. No se desalientan por las dificultades del camino ni son arrastrados fuera del camino por los deleites que encuentran. Los que se dirigen al cielo deben perseverar hasta el fin. Los que emprendemos el camino en obedeciencia a la orden de Dios y atendiendo humildemente su providencia, ciertamente triunfaremos y finalmente tendremos consuelo. Canaán no era, como otras tierras, una simple posesión externa, sino un tipo del cielo y, en este sentido, los patriarcas la apreciaban fervientemente.</p>
<br/>
<p class="text-justify">Vv. 6-9.Abram halló la tierra poblada por cananeos que eran malos vecinos. Él viajó, y siguió adelante aún. A veces la suerte de los hombres buenos es no estar establecidos y, a menudo, cambiar a diversos estados. Los creyentes deben considerarse como peregrinos y extranjeros en este mundo, Hebreos xi, 8, 13, 14. Pero observe cuánto consuelo tenía Abram en Dios. Cuando tuvo escasa satisfacción en sus contactos con los cananeos que allí encontró, tuvo abundante placer en la comunión con aquel Dios que lo había llevado hasta ahí, y que no lo desamparó. La comunión con Dios se mantiene por la palabra y la oración. Dios se revela Él mismo y sus favores en forma gradual a su pueblo; antes había prometido mostrarle a Abram la tierra; ahora, promete dársela: a medida que crece la gracia, crece el consuelo. Pareciera que Abram lo entendió también como la concesión de una tierra mejor, de la cual esta era tipo, porque esperaba un país celestial, Hebreos xi, 16.
Abram se estableció tan pronto como llegó a Canaán, y aunque no era sino extranjero y peregrino ahí, mantuvo la adoración de Dios en su familia. No sólo se preocupó de la parte ceremonial de la religión, la presentación de sacrificios, sino tomó conciencia de buscar a Dios e invocar su nombre, el sacrificio espiritual con el cual se agrada Dios. Predicaba sobre el nombre del Señor; enseñó a su familia y a sus vecinos el conocimiento del Dios verdadero y de su santa religión. La adoración familiar es un buen camino antiguo, nada nuevo, sino la antigua costumbre de los santos. Abram era rico y tuvo una familia numerosa, aun no estaba establecido, y estaba rodeado de enemigos; sin embargo, doquiera levantara su campamento, edificaba un altar: donde quiera que vayamos no dejemos de llevar nuestra religión con nosotros.</p>
<br/>
<p class="text-justify">Vv. 10-20.No hay en la tierra una situación libre de pruebas, ni personaje libre de defectos. Hubo hambruna en Canaán, la más gloriosa de todas las tierras, como hubo incredulidad, en Abram el padre de los fieles, con los males que siempre conlleva. La felicidad perfecta y la pureza perfecta están solamente en el cielo. Abram, cuando debe dejar Canaán por un tiempo, va a Egipto, con la intención de demorarse allí no más de lo necesario, para que no pareciera que mira hacia atrás.
Ahí Abram oculta su relación con Sarai, equivocado, y pide a su esposa y a sus siervos que hagan lo mismo. Él ocultó una verdad como un modo de negarla efectivamente, y por ello, expone al pecado tanto a su esposa como a los egipcios. La gracia por la cual más se destacaba Abram era la fe; sin embargo, así cayó por la incredulidad y desconfianza en la providencia divina, aun después que Dios le había aparecido dos veces. ¡Ay, qué será de una fe débil cuando la fe firme se ve así remecida! Muchas veces, si Dios no nos librara de las angustias e inquietudes en que nos metemos nosotros mismos, por nuestro propio pecado y necedad, estaríamos destruidos. Él no nos trata conforme a lo que merecemos.
Son castigos felices aquellos que nos impiden ir por el camino del pecado y nos lleva a cumplir nuestro deber, particularmente el deber de hacer reparación por lo que hemos tomado o conservado indebidamente.
La reprensión de faraón para Abram fue muy justa: “¿Qué es esto que has hecho conmigo?”¡Cuán inapropiado de un hombre sabio y bueno! Si quienes profesan la fe hacen lo injusto y engañoso, especialmente si dicen lo que está al borde de la mentira, deben estar dispuestos a oír una reprensión, y tienen razón para agradecer a quienes les hablen de esa manera.
La despedida fue bondadosa. El faraón estaba tan lejos de toda intención de matar a Abram, como éste temía, que tuvo un particular cuidado de él. A menudo, nos confundimos con temores que no tienen absolutamente ningún fundamento. Muchas veces tememos cuando nada hay que temer. El faraón encargó a sus hombres que no dañaran en nada a Abram. No basta que los que tienen la autoridad no hieran por sí mismos; ellos deben impedir que sus siervos y quienes los rodean hagan daño.</p>
<br/>




</div>
