<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 10</h2>
<p class="text-justify">Vv. 1-7.Este capítulo habla de los tres hijos de Noé, que de estos se esparcieron las naciones en la tierra. Ninguna nación, excepto los judíos, puede estar segura de cuál de estos setenta desciende. Por amor al Mesías, solo los judíos conservaron la lista de nombres de padres e hijos. Sin embargo, muchos hombres doctos han mostrado, con alguna probabilidad, qué naciones de la tierra descendieron de cada uno de los hijos de Noé. A la posteridad de Jafet fueron asignadas las islas de los gentiles; probablemente, la isla de Bretaña entre las demás. Todos los lugares de ultramar más allá de Judea son llamados islas, Jeremías xxv, 22 [o costas, RVR 1960]. Esa promesa, Isaías xlii, 4, “las costas esperarán su ley”, habla de la conversión de los gentiles a la fe de Cristo.</p>
<br/>
<p class="text-justify">Vv. 8-14.Nimrod fue un gran hombre en su época; él comenzó a ser poderoso en la tierra. Los anteriores a él se contentaban con estar al mismo nivel de su prójimo y, aunque cada hombre reinaba en su propia casa, ningún hombre pretendía ser más. Nimrod estaba decidido a enseñorearse de sus vecinos. El espíritu de los gigantes de antes del diluvio, que llegaron a ser hombres poderosos y hombres de renombre, Génesis vi, 4, revivió en él.
Nimrod fue vigoroso cazador . En aquel entonces cazar era el método de impedir el aumento dañino de las bestias salvajes. Esto requería mucho valor y destreza y así dio a Nimrod, una oportunidad para mandar a los demás y, paulatinamente, sumó una cantidad de hombres bajo un jefe. Probablemente desde tal comienzo Nimrod empezó a gobernar y a obligar a los demás a someterse. Él invadió los derechos y propiedades de sus vecinos y persiguió a hombres inocentes; proponiéndose hacer todo suyo por la fuerza y la violencia. Ejecutó sus opresiones y la violencia desafiando al mismo Dios. Nimrod fue un gran rey . De una u otra forma, por la razón o la fuerza, obtuvo poder y, así, fundó una monarquía que fue el terror del fuerte y con buenas probabilidades de gobernar todo el mundo. Nimrod fue un gran constructor . Obsérvese en Nimrod la naturaleza de la ambición. No tiene límites; lo mucho quiere tener más, y todavía clama: Dame, dame. Es incansable; Nimrod, cuando tuvo cuatro ciudades bajo su mando, no pudo contentarse hasta que tuvo cuatro más. Es cara; Nimrod prefería encargarse de levantar ciudades si no tenía el honor de gobernarlas. Es atrevida, y ante nada se detendrá. El nombre de Nimrod significa rebelión; los tiranos entre los hombres son rebeldes ante Dios. Vienen días en que los conquistadores no ya serán encomiados, como en las historias parciales del hombre; más bien llevarán el sello de la infamia, como en los registros imparciales de la Biblia.</p>
<br/>
<p class="text-justify">Vv. 15-32.La posteridad de Canaán fue numerosa, rica y gratamente establecida; sin embargo, Canaán estaba bajo una maldición divina, y no una maldición sin causa. Quienes están sometidos a la maldición de Dios pueden, quizá, florecer y prosperar en este mundo; porque nosotros no podemos conocer el amor o el odio, la bendición o la maldición por lo que está delante sino por lo que está dentro de nosotros. La maldición de Dios siempre obra realmente y siempre es terrible. Quizá sea una maldición secreta, una maldición para el alma y no obra de modo que los demás pueden verla; o es una maldición lenta y no obra pronto; pero los pecadores están reservados por ella para el día de la ira. Canaán tiene aquí una tierra mejor que Sem o Jafet y, sin embargo, ellos tienen mejor suerte pues heredan la bendición.
Abram y su simiente, el pueblo del pacto de Dios, descendieron de Heber, y por él fueron llamados hebreos. Cuanto mejor es ser como Heber, el padre de una familia de hombres santos y honestos que ser el padre de una familia de cazadores de poder, de riquezas mundanas o de vanidades. La bondad es la verdadera grandeza.</p>
<br/>




</div>
