<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 4</h2>
<p class="text-justify">Vv. 1-7.Cuando nació Caín, Eva dijo: He engendrado un varón del Señor. Quizá pensó que era la simiente prometida. De ser así, tuvo una amarga desilusión. Abel significa vanidad : cuando ella pensó que tenía la simiente prometida en Caín, cuyo nombre significa posesión , ella se absorbió tanto con él que otro hijo era como vanidad para ella.
Fíjese que cada hijo tenía un llamamiento. La voluntad de Dios para todos es que cada uno tenga algo que hacer en este mundo. Los padres deben criar a sus hijos para trabajar. Déles una Biblia y un llamamiento, decía el buen señor Dod, y Dios sea con ellos. Podemos suponer que, después de la caída, Dios mandó a Adán que derramara la sangre de animales inocentes y, una vez muertos, quemara parte o todo los cuerpos con fuego. Así fueron prefigurados el castigo que merecen los pecadores, esto es, la muerte del cuerpo, y la ira de Dios, de la cual el fuego es un emblema bien conocido, además de los sufrimientos de Cristo. Observe que la adoración religiosa de Dios no es un invento nuevo. Fue desde el comienzo; es el buen camino antiguo , Jeremías vi, 16.
Las ofrendas de Caín y Abel fueron diferentes. Caín demostró un orgulloso corazón incrédulo. En consecuencia, él y su ofrenda fueron rechazados. Abel llegó en calidad de pecador y, conforme a lo establecido por Dios, por medio de su sacrificio expresaba humildad, sinceridad y obediencia y fe. De este modo, al buscar el beneficio del nuevo pacto de misericordia, por medio de la Simiente prometida, su sacrificio tenía una expresión que Dios aceptó. Abel ofrendó en fe pero no Caín, Hebreos xi, 4. En todas las épocas ha habido dos clases de adoradores, a la manera de Caín y Abel; a saber, los orgullosos y endurecidos que desprecian el método de salvación del evangelio, que intentan agradar a Dios con métodos diseñados por ellos mismos; y, los creyentes humildes que se acercan a él por el camino que él ha revelado.
Caín se entregó a la ira maligna contra Abel. Albergó un espíritu maligno de descontento y rebelión contra Dios. Dios nota todas nuestras pasiones y descontentos pecaminosos. No hay mirada de enojo, envidia o de fastidio que escape a su ojo vigilante. El Señor razonó con este hombre rebelde; si tomaba el camino correcto, sería aceptado. Algunos entienden esto como un anuncio de misericordia. “Si no hicieres bien, el pecado, esto es, la ofrenda por el pecado está a la puerta y tú pudieras beneficiarte de ella”. La misma palabra significa pecado y sacrificio por el pecado. “Aunque no hayas hecho bien, no te desesperes todavía; el remedio está a la mano”. Se dice que Cristo, la gran ofrenda por el pecado, está a la puerta, Apocalipsis iii, 20. Bien merecen perecer en sus pecados los que no van a la puerta a pedir el beneficio de esta ofrenda por el pecado. La aceptación de la ofrenda de Abel por parte de Dios no cambió el derecho de primogenitura haciéndolo suyo; entonces, ¿por qué había de enojarse tanto Caín? Los apasionamientos e inquietudes pecaminosas se desvanecen cuando se busca en forma estricta y justa la causa.</p>
<br/>
<p class="text-justify">Vv. 8-15.La maldad del corazón termina en el asesinato hecho con las manos. Caín mató a Abel, su propio hermano, el hijo de su propia madre, a quien debiera haber amado; a su hermano menor, a quien debiera haber protegido; un hermano bueno, que nunca le había hecho nada malo. ¡Qué efectos fatales del pecado de nuestros primeros padres fueron estos, y cómo deben de haberse llenado de angustia sus corazones! Observe el orgullo, la incredulidad y la soberbia de Caín. Niega el crimen, como si pudiera ocultarlo de Dios. Trata de tapar un homicidio deliberado con una mentira deliberada. El asesinato es un pecado que clama. La sangre pide sangre, la sangre del asesino por la sangre del asesinado. -¿Quién conoce el alcance y el peso de una maldición divina, cuán lejos llega, cuán profundo penetra? Los creyentes se salvan de ella sólo en Cristo, y heredan la bendición. Caín fue maldecido por la tierra. Él halló su castigo ahí donde eligió su suerte y puso su corazón. Toda criatura es para nosotros lo que Dios la haga, un consuelo o una cruz, una bendición o una maldición. La maldad del malo trae maldición a todo lo que hacen y a todo lo que tienen.
Caín se queja, no de su pecado, sino de su castigo. Se muestra gran dureza de corazón cuando nos preocupan más nuestros sufrimientos que nuestros pecados. Dios tiene propósitos sabios y santos al prolongar las vidas hasta de los hombres más malos. Vano es inquirir cuál fue la señal puesta sobre Caín. Indudablemente era conocida tanto como marca de infamia sobre Caín, y como señal de Dios para que no lo mataran.
Abel hablaba aún estando muerto. Habla de la odiosa culpa del crimen y nos avisa que debemos reprimir los primeros accesos de ira y nos enseña que el justo debe esperar persecución. También, que hay un estado futuro y una recompensa eterna para disfrutar, por fe en Cristo y su sacrificio expiatorio. Él nos habla de la excelencia de la fe en el sacrificio y la sangre expiatoria del Cordero de Dios. Caín mató a su hermano porque sus propias obras eran malas y las de su hermano, justas, 1 Juan iii, 12. Como consecuencia de la enemistad puesta entre la Simiente de la mujer y la simiente de la serpiente estalló la guerra, que se ha librado continuamente desde entonces. En esta guerra estamos todos comprometidos, nadie es neutral; nuestro Capitán ha declarado que él que no es conmigo, contra mí es. Apoyemos decididamente, pero con mansedumbre, la causa de la verdad y justicia contra Satanás.</p>
<br/>
<p class="text-justify">Vv. 16-18.Caín desechó todo el temor de Dios y no quiso escuchar los mandatos de Dios. Los profesantes hipócritas que fingen y se niegan a tomar en serio a Dios, son justamente abandonados a su suerte para que hagan algo extremadamente escandaloso. Así, pues, se desprenden de aquella forma de santidad para la cual han sido reproche y cuyo poder niegan. Caín se fue de la presencia del Señor y nunca encontramos que haya regresado, para su consuelo. La tierra en que habitó Caín fue llamada la tierra de Nod, que significa ‘estremecimiento’o ‘tembloroso’que, de ese modo, muestra la inquietud e incomodidad de su espíritu, o ‘la tierra de un vagabundo’: Quienes se apartan de Dios nunca pueden hallar reposo en ninguna otra parte.
Los que en la tierra buscaban la ciudad celestial, optaron por morar en tabernáculos o carpas; pero Caín, por no importarle esa ciudad, edificó una en la tierra. Así, todos los maldecidos por Dios procuran su estabilidad y satisfacción aquí abajo.</p>
<br/>
<p class="text-justify">Vv. 19-24.Uno de la perversa raza de Caín es el primero que se registra quebrantando la ley del matrimonio. Hasta aquí, un hombre tenía sólo una esposa a la vez; pero Lamec tomó dos.
Las únicas cosas sobre las que pone su corazón la perversa gente carnal son las cosas de este mundo, y son sumamente astutos y diligentes al respecto. Así ocurrió con la raza de Caín. Aquí había un padre de pastores y un padre de músicos, pero no un padre de fieles. Aquí hay uno que enseña sobre el bronce y el hierro, pero no hay quien enseñe el buen conocimiento del Señor: aquí hay recursos para enriquecerse y para ser poderoso y estar alegres, pero nada de Dios, de su temor y su servicio. Las cosas presentes llenan las cabezas de la mayoría.
Lamec tenía enemigos, a quienes había provocado. Hace una comparación entre él mismo y su antepasado Caín; y se elogia por ser mucho menos criminal. Parece abusar de la paciencia de Dios al dispensar a Caín, tomando eso como una estímulo para tener la expectativa de pecar y no recibir castigo.</p>
<br/>
<p class="text-justify">Vv. 25, 26.Nuestros primeros padres fueron consolados en su aflicción por el nacimiento de un hijo, al que llamaron Set, esto es: ‘sustituto’, ‘establecido’o ‘colocado’; en su simiente la humanidad continuaría hasta el fin del tiempo, y de él descendería el Mesías. Mientras Caín, la cabeza de la apostasía, es hecho un errante, Set, de quien iba a venir la iglesia verdadera, es uno establecido. En Cristo y su iglesia está el único establecimiento verdadero. Set anduvo en los pasos de su martirizado hermano Abel; fue partícipe de una fe igualmente preciosa en la justicia de nuestro Dios y Salvador Jesucristo y, así, llegó a ser un nuevo testigo de la gracia e influencia de Dios Espíritu Santo. Dios concedió a Adán y Eva que vieran el avivamiento religioso en su familia.
Los adoradores de Dios empezaron a hacer más en religión; algunos, por una profesión franca de la verdadera religión, protestaban contra la maldad del mundo circundante. Mientras peores sean los demás, mejores debemos ser nosotros, y más celosos. Entonces empezó la distinción entre profesantes y profanos, la cual ha seguido desde entonces y seguirá mientras haya mundo.</p>
<br/>




</div>
