<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 16</h2>
<p class="text-justify">Vv. 1-3.Sarai que ya no esperaba tener hijos propios, propuso a Abram que tomara otra esposa, cuyos hijos ella podría adoptar: su esclava, cuyos hijos serían propiedad de Sarai. Esto fue hecho sin pedir el consejo del Señor. Obró la incredulidad, y olvidaron el poder omnipotente de Dios. Fue un mal ejemplo y fuente de múltiple incomodidad. En toda relación y situación de la vida hay una cruz que debemos llevar: gran parte del ejercicio de la fe consiste en someterse pacientemente, en esperar el tiempo del Señor y usar solamente aquellos medios que Él designa para remover la cruz. Las tentaciones necias pueden tener pretensiones muy lindas y estar pintadas con eso que luce muy plausible. La sabiduría carnal nos saca del camino de Dios. Esto no sería así si pidiésemos el consejo de Dios por su palabra y oración antes de intentar aquello que es dudoso.</p>
<br/>
<p class="text-justify">Vv. 4-6.El desdichado matrimonio de Abram con Agar logró muy pronto hacer mucha maldad. Podemos agradecernos la culpa y pena que nos siguen cuando nos salimos del camino de nuestro deber. Véalo en este caso.
La gente apasionada suele pelear con el prójimo por cosas de las cuales ellos mismos deben llevar la culpa. Sarai había dado su doncella a Abram pero ella grita: “Mi afrenta sea sobre ti.”Nunca se dice sabiamente aquello que el orgullo y la ira ponen en nuestras bocas. No siempre tienen la razón aquellos que son más ruidosos y osados para apelar a Dios: tales prisa e imprecaciones osadas hablan corrientemente de culpa y de una mala causa. Agar olvidó que ella misma había provocado primero al despreciar a su señora. Aquellos que sufren por sus faltas deben soportarlo con paciencia, 1 Pedro ii, 20.</p>
<br/>
<p class="text-justify">Vv. 7-16.-Agar estaba fuera de su lugar y fuera del camino de su deber y seguía descarriándose más cuando el Ángel la halló. Gran misericordia es ser detenido en un camino pecador, sea por la conciencia o por la providencia. ¿De dónde vienes tú? Considera que está huyendo del deber y de los privilegios con que eras bendecida en la tienda de Abram. Bueno es vivir en una familia religiosa, cosa que debieran considerar aquellos que tienen esta ventaja. ¿A dónde ira? Está corriendo al pecado; si Agar regresa a Egipto, volverá a los ídolos endiosados y al peligro del desierto por el cual debe viajar. Recordar quienes somos a menudo nos enseña nuestro deber. Inquirir de donde venimos debiera mostrarnos nuestro pecado y necedad. Considerar donde iremos, descubre nuestro peligro y desgracia. Aquellos que dejan sus lugares y deberes, deben apresurar su regreso por mortificante que sea.
La declaración del Ángel, “Yo quiero”, señala que este Ángel era la Palabra eterna e Hijo de Dios. Agar no pudo sino admirar la misericordia del Señor y sentir, ¿he sido yo, que soy tan indigna, favorecida con una bondadosa visita del Señor? Ella fue llevada a un mejor temperamento, regresó y con su conducta ablandó a Sarai y recibió un trato más amable. ¡Que nosotros seamos siempre impresionados apropiadamente con este pensamiento: ¡Dios, Tú me ves!</p>
<br/>




</div>
