<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">Vv. 1, 2.El primer versículo de la Biblia nos da un relato satisfactorio y útil del origen de la tierra y de los cielos. La fe del cristiano humilde entiende esto mejor que la fantasía de los hombres más doctos. De lo que vemos del cielo y la tierra aprendemos el poder del gran Creador. Que el hecho de ser creados y nuestro lugar como hombres, nos recuerden nuestro deber cristiano de mantener siempre el cielo a la vista y la tierra bajo nuestros pies.
El Hijo de Dios, uno con el Padre, estaba con Él cuando éste hizo el mundo; mejor dicho, a menudo se nos dice que el mundo fue hecho por Él y que sin Él nada fue hecho. ¡Oh, qué elevados pensamientos debiera haber en nuestra mente hacia el gran Dios que adoramos, y hacia ese gran Mediador en cuyo nombre oramos! Aquí, en el principio mismo del texto sagrado, leemos de ese Espíritu Divino cuya obra en el corazón del hombre se menciona tan a menudo en otras partes de la Biblia.
Observe que, al principio nada deseable había para ver, pues el mundo estaba informe y vacío; era confusión y desolación. En manera similar, la obra de la gracia en el alma es una nueva creación: y en un alma sin gracia, que no ha nacido de nuevo, hay desorden, confusión y toda mala obra: está vacía de todo bien porque está sin Dios; es oscura, es las tinieblas mismas: este es nuestro estado por naturaleza, hasta que la gracia del Todopoderoso efectúa en nosotros un cambio.</p>
<br/>
<p class="text-justify">Vv. 3-5.Dijo Dios: Sea la luz; Él la quiso, e inmediatamente hubo luz. ¡Qué poder el de la palabra de Dios! En la nueva creación, lo primero que se lleva al alma es la luz: el bendito Espíritu obra en la voluntad y en los afectos iluminando el entendimiento. Quienes por el pecado eran tinieblas, por gracia se convierten en luz en el Señor. Las tinieblas hubieran estado siempre sobre el hombre caído si el Hijo de Dios no hubiera venido para darnos entendimiento, 1 Juan v. 20. La luz que Dios quiso, la aprobó. Dios separó la luz de las tinieblas, pues, ¿qué comunión tiene la luz con las tinieblas? En los cielos hay perfecta luz y ningunas tinieblas; en el infierno, la oscuridad es absoluta y no hay un rayo de luz. El día y la noche son del Señor; usemos ambos para su honra: cada día en el trabajo para Él y descansando en Él cada noche. Meditando día y noche en su ley.</p>
<br/>
<p class="text-justify">Vv. 6-13.La tierra estaba desolada, pero por una palabra se llenó de las riquezas de Dios, que todavía son suyas. Aunque se permite al hombre su uso, son de Dios y para su servicio y honor deben usarse. La tierra, a su mandato, produce pasto, hierbas y frutos. Dios debe tener la gloria de todo el provecho que recibimos del producto de la tierra. Si tenemos interés en Él, que es la Fuente, por la gracia, nos regocijaríamos en Él cuando se secan los arroyos temporales de la misericordia.</p>
<br/>
<p class="text-justify">Vv. 14-19.El cuarto día de trabajo da cuenta de la creación del sol, la luna y las estrellas. Todo es obra de Dios. Se habla de las estrellas tal como aparecen antes nuestros ojos, sin decir su cantidad, naturaleza, lugar, tamaño o movimientos; las Escrituras no fueron hechas para satisfacer la curiosidad ni para hacernos astrónomos, sino para conducirnos a Dios y hacernos santos. Las luces del cielo fueron hechas para servirle a Él; lo hacen fielmente y brillan a su tiempo sin faltar. Nosotros estamos como luces en este mundo para servir a Dios; pero, ¿respondemos en manera similar a la finalidad para la que fuimos creados? No: nuestra luz no resplandece ante Dios como sus luces brillan ante nosotros. Hacemos uso de la creación de nuestro Amo, pero nos importa poco la obra de nuestro Amo.</p>
<br/>
<p class="text-justify">Vv. 20-25.Dios mandó que se hicieran los peces y las aves. Él mismo ejecutó esta orden. Los insectos, que son más numerosos que las aves y las bestias, y tan curiosos, parecen haber sido parte de la obra de este día. La sabiduría y el poder del Creador son admirables tanto en una hormiga como en un elefante.
El poder de la providencia de Dios preserva todas las cosas y la feracidad es el efecto de su bendición.</p>
<br/>
<p class="text-justify">Vv. 26-28.El hombre fue hecho después de todas las criaturas: esto era tanto un honor como un favor para él. Sin embargo, el hombre fue hecho el mismo día que las bestias; su cuerpo fue hecho de la misma tierra que el de ellas; y mientras él está en el cuerpo, habita en la misma tierra con ellas. ¡No permita Dios que dándole gusto al cuerpo y a sus deseos, nos hagamos como las bestias que perecen! El hombre fue hecho para ser una criatura diferente de todas las que habían sido hechas hasta entonces. En él tenían que unirse la carne y el espíritu, el cielo y la tierra. Dios dijo: “Hagamos al hombre”. El hombre, cuando fue hecho, fue creado para glorificar al Padre, Hijo y Espíritu Santo. En ese gran nombre somos bautizados pues a ese gran nombre debemos nuestro ser. Es el alma del hombre la que lleva especialmente la imagen de Dios.
El hombre fue hecho recto, Eclesiastés vii. 29. Su entendimiento veía clara y verdaderamente las cosas divinas; no había yerros ni equivocaciones en su conocimiento; su voluntad consentía de inmediato a la voluntad de Dios en todas las cosas. Sus afectos eran normales y no tenía malos deseos ni pasiones desordenadas. Sus pensamientos eran fácilmente llevados a temas sublimes y quedaban fijos en ellos. Así de santos, así de felices, eran nuestros primeros padres cuando tenían la imagen de Dios en ellos. ¡Pero cuán desfigurada está la imagen de Dios en el hombre! ¡Quiera el Señor renovarla en nuestra alma por su gracia!</p>
<br/>
<p class="text-justify">Vv. 29, 30.Las hierbas y las frutas deben ser la comida del hombre, incluido el maíz y todos los productos de la tierra. Que el pueblo de Dios ponga sobre Él su carga y no se afane por qué comerán ni qué beberán. El que alimenta las aves del cielo no permitirá que sus hijitos pasen hambre.</p>
<br/>
<p class="text-justify">V. 31.Cuando nos ponemos a pensar en nuestras obras hallamos, para vergüenza nuestra, que en gran parte han sido muy malas; pero cuando Dios vio su obra, todo era muy bueno. Bueno pues todo era cabalmente como el Creador quería que fuera. Todas sus obras, en todos los lugares de su señorío le bendicen y, por tanto, bendice, alma mía, al Señor. Bendigamos a Dios por el evangelio de Cristo y, al considerar su omnipotencia, huyamos nosotros, los pecadores, de la ira venidera. Si somos creados de nuevo conforme a la imagen de Dios en santidad, finalmente entraremos en los “cielos nuevos y tierra nueva, en los cuales mora la justicia”.</p>
<br/>




</div>
