<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 21</h2>
<p class="text-justify">Vv. 1-8.En el Antiguo Testamento son pocos los que vinieron al mundo con tantas expectativas como Isaac. En esto fue un tipo de Cristo, esa Simiente que el santo Dios prometiera mucho tiempo antes y que los hombres santos esperaron por tanto tiempo. Nació conforme a la promesa en el momento designado del cual Dios había hablado. Las misericordias prometidas por Dios ciertamente llegarán en el momento que Él determina y ese es el mejor momento. Isaac significa “risa”habiendo buena razón para el nombre, capítulo xvii, 17; xviii, 13. Cuando el Sol del consuelo se levanta en el alma, es bueno recordar cuán bien recibida fue el alba del día.
Cuando Sara recibió la promesa, se rió con desconfianza y duda. Cuando Dios nos da las misericordias de las que empezamos a desesperar, debiéramos recordar con pena y vergüenza nuestra pecadora desconfianza en su poder y promesa, cuando estábamos en busca de ellas.
Esta misericordia llenó a Sara con gozo y asombro. Los favores de Dios para su pueblo del pacto son tales que superan sus propios pensamientos y expectativas como también los ajenos: ¿quién podía imaginar que Él hiciera tanto por aquellos que merecen tan poco, más aun, para aquellos que merecen recibir el mal? ¿Quién hubiera dicho que Dios enviaría a su Hijo a morir por nosotros, su Espíritu para hacernos santos, sus ángeles para servirnos? ¿Quién hubiera dicho que pecados tan grandes serían perdonados, que servicios tan mezquinos serían aceptados y que gusanos tan indignos serían integrados en el pacto? -Se hace un breve relato de la infancia de Isaac. Hay que reconocer la bendición de Dios sobre la crianza de los niños y su preservación a través de los peligros de la edad infantil, como ejemplo de señales del cuidado y ternura de la providencia divina. Vea Salmo xxii, 9, 10; Oseas xi, 1. 2.</p>
<br/>
<p class="text-justify">Vv. 9-13.No descuidemos la manera en que este asunto familiar nos enseña a no descansar en los privilegios externos o en nuestras propias obras. Procuremos las bendiciones del nuevo pacto por fe en la certeza Divina. La conducta de Ismael fue de persecución, con desprecio profano del pacto y la promesa, y con malicia contra Isaac. Dios se fija en lo que dicen y hacen los niños en sus juegos; y les tomará en cuenta si dicen o hacen mal, aunque no lo hagan sus padres. Burlarse es un pecado grande y resulta en provocación contra Dios. Los hijos de la promesa deben esperar que se burlen de ellos.
Abraham se dolió de que Ismael se portara mal y que Sara exigiera un castigo tan severo. Pero Dios le mostró que Isaac debe ser el padre de la Simiente prometida; por tanto, “manda lejos a Ismael no sea que corrompa las costumbres o trate de usurpar los derechos de Isaac”. La semilla del pacto de Abraham debe ser un pueblo por sí mismo, no mezclado con los que están fuera del pacto: Sara poco pensó en lo que hizo, pero Dios rectificó lo que ella dijo.</p>
<br/>
<p class="text-justify">Vv. 14-21.Si Agar e Ismael se hubieran comportado bien en la familia de Abraham, hubieran continuado ahí pero fueron justamente castigados. Nosotros perdemos los privilegios por abusar de ellos. Los que no saben cuándo están bien, conocerán el valor de las misericordias cuando les faltan.
Ellos fueron llevados a la angustia en el desierto. No se dice que se acabaran las provisiones ni que Abraham los echara sin dinero. Pero se acabó el agua y, habiendo perdido su camino, en ese clima cálido, Ismael fue rápidamente vencido por la fatiga y la sed. La prontitud de Dios para ayudarnos cuando estamos en problemas, no debe disminuir sino apurar nuestros esfuerzos para ayudarnos a nosotros mismos.
La promesa tocante a su hijo es repetida como razón por qué Agar debe ponerse en acción ella misma para ayudarle. Debemos comprometer nuestra atención y cuidados por los niños y jóvenes al considerar que no sabemos cuál sea la gran tarea que Dios les tiene designada ni sabemos lo que pueda hacer de ellos.
El ángel le muestra una provisión presente. Muchos que tienen razón para estar consolados, pasan condoliéndose de día en día porque no ven que haya una razón para tener consuelo. Hay un pozo de agua cerca de ellos en el pacto de gracia, pero ellos no se dan cuenta hasta que el mismo Dios que abrió sus ojos para ver sus heridas, se los abre para que vean el remedio.
Parán era un lugar silvestre, adecuado para un hombre rudo como Ismael. Los que nacen según la carne se acomodan al desierto de este mundo, mientras los hijos de la promesa que se dirigen a la Canaán celestial no pueden tener reposo hasta que están allá. Sin embargo, Dios estaba con el muchacho; su bienestar exterior se debía a esto.</p>
<br/>
<p class="text-justify">Vv. 22-34.Abimelec se sintió seguro de que las promesas de Dios le serían cumplidas a Abraham. Es sabio que nos relacionemos con quienes son bendecidos por Dios; y hemos de pagar con bondad a quienes han sido bondadosos con nosotros. Los pozos de agua son escasos y valiosos en los países orientales. Abraham tuvo cuidado de asegurar su derecho al pozo para evitar futuras disputas. No puede esperarse otra cosa de un hombre honesto sino que esté listo para hacer el bien tan pronto como sepa que ha hecho mal.
Abraham, estando ahora en un buen lugar, se quedó mucho tiempo en él. Allí hizo no sólo una práctica constante, sino además una profesión franca de su religión. Allí invocó el nombre de Jehová como el Dios eterno; probablemente el tamarisco que plantó, fue su lugar de oración. Abraham mantuvo el culto público, en el cual podían participar sus vecinos. Los hombres buenos deben hacer todo lo que puedan para hacer que los demás lleguen a ser buenos. Donde quiera que peregrinemos no debemos descuidar la adoración de Jehová, ni avergonzarnos de hacerlo.</p>
<br/>




</div>
