<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 50</h2>
<p class="text-justify">Vv. 1-6.Aunque los parientes y amistades piadosos hayan vivido hasta una edad bien avanzada y estemos confiados de que se han ido a la gloria, podemos sentir la pérdida y respetar su recuerdo llorándolos. La gracia no destruye, sino que purifica, modera y regula el afecto natural. El alma que se fue está fuera del alcance de toda muestra de nuestro afecto pero es apropiado mostrar respeto al cuerpo, del cual esperamos una resurrección gloriosa y gozosa, sea lo que sea que suceda con sus restos en este mundo. Así, pues, José mostró su fe en Dios y su amor por su padre. Mandó que el cuerpo fuera embalsamado o envuelto con especias para preservarlo. Vea cuán viles son nuestros cuerpos cuando el alma los ha abandonado: se ponen en muy poco tiempo fétidos y desagradables.</p>
<br/>
<p class="text-justify">Vv. 7-14.El cuerpo de Jacob fue velado no sólo por su familia sino por los grandes de Egipto. Ahora que conocían mejor a los hebreos, empezaron a respetarlos. Los que profesan la religión deben proponerse eliminar, por sabiduría y amor, los prejuicios que muchos tienen en contra de ellos. Los espectadores vieron esto como un llanto grande. La muerte de los hombres buenos es una pérdida en cualquier parte y debe ser grandemente lamentada.</p>
<br/>
<p class="text-justify">Vv. 15-21.Diversos son los motivos que pudieron hacer que los hijos de Jacob siguieran en Egipto, a pesar de la visión profética que Abraham tuvo de su esclavitud allá. Juzgando a José con el temperamento general de la naturaleza humana, pensaron que ahora él se vengaría de los que lo habían odiado y dañado sin causa. No siendo capaces de resistir ni de huir, intentaron ablandarlo humillándose. Le suplicaron como siervos del Dios de Jacob. José se sintió muy afectado al ver el cumplimiento total de sus sueños. Les manda que no le teman a él sino a Dios; que se humillen ante el Señor y busquen el perdón divino. Les garantiza su propia bondad para con ellos. Véase que espíritu excelente era José y aprendamos de él a devolver bien por mal. Él los consoló y, para disipar todos sus temores, les habló amablemente. Los espíritu quebrantados deben ser curados y animados. No sólo debemos hacer el bien a quienes amamos y perdonamos; también debemos hablarles bondadosamente.</p>
<br/>
<p class="text-justify">Vv. 22-26.Al honrar a su padre, José tuvo días largos en la tierra que, por el presente, Dios le había dado. Cuando vio que se acercaba su muerte, consoló a sus hermanos con la seguridad del regreso de ellos a Canaán en el debido momento. Debemos consolarnos unos a otros con las mismas consolaciones con que hemos sido consolados por Dios y animarlos a descansar en las promesas que son nuestro apoyo. Como una confesión de su propia fe y una confirmación de la de ellos, les encarga que dejen sin enterrar sus restos hasta el día glorioso en que ellos se establezcan en la tierra prometida. Así, pues, José por fe en la doctrina de la resurrección y en la promesa de Canaán, dio mandamiento acerca de sus huesos. Esto iba a mantener viva la expectativa de ellos en cuanto a una pronta salida de Egipto y a tener a Canaán presente en forma continua. Además, esto uniría a la posteridad de José con sus hermanos.
La muerte, como también la vida de este eminente santo, fue verdaderamente excelente; ambas nos dan una firme exhortación de perseverancia en el servicio de Dios. ¡Cuán dichoso empezar temprano en la carrera celestial, seguir firme y terminar la carrera con gozo! Esto que hizo José, nosotros también podemos hacer. Hasta cuando los dolores de la muerte estén sobre nosotros, si hemos confiado en quien confiaron los patriarcas, los profetas y los apóstoles, no temamos decir: “mi carne y mi corazón desfallecen, mas la roca de mi corazón y mi porción es Dios para siempre”.</p>
<br/>




</div>
