<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 28</h2>
<p class="text-justify">Vv. 1-5.Jacob tenía promesas de bendiciones para este mundo y para el venidero pero sale para trabajar en forma ardua. Esto lo ayudó a corregirse por el fraude perpetrado a su padre. La bendición le será conferida, pero tendrá agudo dolor por el curso indirecto tomado para obtenerla.
Jacob es despedido por su padre con un solemne encargo. Él no debe tomar esposa de las hijas de Canaán: Los que profesan la religión no deben casarse con quienes no se preocupan por la fe. Además, le da una bendición solemne. Isaac lo había bendecido antes sin querer; ahora lo hace deliberadamente. Esta bendición es más completa que la anterior; es una bendición evangélica. Esta promesa apunta tan alto como el cielo, del cual Canaán era un tipo. Esa era la patria mejor que Jacob y los demás patriarcas tenían en vista.</p>
<br/>
<p class="text-justify">Vv. 6-9.Los buenos ejemplos impresionan aun al profano y malo. Pero Esaú pensó complacer a sus padres en una cosa para expiar los otros males cometidos. Los corazones carnales son dados a creerse tan buenos como debieran ser porque en algún aspecto no son tan malos como pudieran haber sido.</p>
<br/>
<p class="text-justify">Vv. 10-15.La conducta de Jacob hasta ahora, según el relato, no era la de alguien que simplemente tiene temor de Dios y confia en Él. Pero ahora, con problemas, obligado a huir, sólo buscó a Dios para que le permita estar a salvo y poder acostarse a dormir a la intemperie con su cabeza sobre una piedra. Todo creyente verdadero debe estar dispuesto a arreglarse con la almohada de Jacob, supuesto que pueda tener la visión de Jacob. El tiempo de Dios para visitar a su gente con sus consolaciones es cuando están completamente privados de otros consuelos y de otros consoladores.
Jacob vio una escalera que iba de la tierra al cielo, los ángeles subiendo y bajando por ella y al mismo Dios en lo alto de ella. Esto representa: -1. La providencia de Dios, por la cual se mantiene un intercambio constante entre el cielo y la tierra. Esto hace saber a Jacob que él tenía a la vez un buen guía y un buen guardián.
2. La mediación de Cristo. Él es esta escalera; el pie en la tierra es su naturaleza humana; lo alto en el cielo es su naturaleza divina. Cristo es el Camino; todos los favores de Dios vienen a nosotros y todos nuestros servicios van a Él por Cristo, Juan i, 51. Por este camino los pecadores se acercan al trono de la gracia con aceptación. Por fe vemos este camino y, en oración, nos acercamos a él. En respuesta a la oración recibimos todas las necesarias bendiciones de la providencia y la gracia. No tenemos camino para llegar al cielo sino por Cristo. Cuando el alma, por fe, puede ver estas cosas, entonces, todo lugar se volverá agradable y toda perspectiva, gozosa. Él nunca nos dejará hasta que su última promesa sea cumplida para nuestra felicidad eterna.
Dios habló ahora consoladoramente a Jacob. Le habló desde lo alto de la escalera. Todas las felices nuevas que recibimos del cielo vienen por medio de Jesucristo. El Mesías debía venir de Jacob. Cristo es la gran bendición del mundo. Todos los que son bendecidos, son bendecidos en Él, y nadie, de ninguna familia queda fuera de la bendición en Él sino aquellos que se excluyen a sí mismos. Jacob tenía que temer el peligro de su hermano Esaú, pero Dios promete guardarle. Él tenía un largo viaje por delante a un país desconocido pero, “He aquí, yo estoy contigo”y Dios promete traerlo de vuelta a esta tierra. Parecía abandonado por todos sus amigos, pero Dios le dio esta seguridad, Yo no te dejaré. Dios nunca abandona al que ama.</p>
<br/>
<p class="text-justify">Vv. 16-19.Dios se manifestó Él mismo y su favor a Jacob cuando éste dormía. El Espíritu, como el viento, sopla cuando y donde quiere, y la gracia de Dios, como el rocío no se retrasa para los hijos de los hombres. Jacob procuró superarse a partir de la visita que Dios le hizo. Doquiera estemos, en la ciudad o en el desierto, en la casa o en el campo, en la tienda o en la calle, podemos mantener nuestra relación con el Cielo, si no es así, es nuestra propia falta. Pero mientras más veamos de Dios, más causa tendremos para un santo temblor delante de Él.</p>
<br/>
<p class="text-justify">Vv. 20-22.En esta ocasión Jacob formuló un solemne voto. Obsérvese lo siguiente: -1. La fe de Jacob. Él confía que Dios estará con él y que le guardará; él confía en esto.
2. La moderación de Jacob en sus deseos. No pide ropa suave ni carne exquisita. Si Dios nos da mucho, tenemos que estar agradecidos y usarlo para Él; si nos da poco, tenemos que estar contentos y disfrutar alegremente de Él en lo poco.
3. La piedad de Jacob y su consideración de Dios, que se ven en lo que deseó, que Dios estuviera con Él y le guardara. No tenemos que desear más para que nos haga cómodos y felices. También su resolución es aferrarse al Señor como su Dios del pacto. Cuando recibimos más que la gracia común de Dios, debemos abundar en gratitud para Él. El diezmo es una proporción adecuada para consagrar a Dios y emplearla para Él aunque puede ser más o menos, según Dios nos prospere, 1 Corintios xvi, 2. Entonces, ¡recordemos nuestros Beteles, cómo estamos comprometidos por votos solemnes a rendirnos al Señor, para tomarlo por nuestro Dios y consagrar todo lo que tenemos y somos para su gloria!</p>
<br/>




</div>
