<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 23</h2>
<p class="text-justify">Vv. 1-13.La vida más prolongada debe pronto llegar a su fin. Bendito sea Dios de que hay un mundo donde el pecado, la muerte, la vanidad y la vejación no pueden entrar. Bendito sea su nombre de que ni siquiera la muerte puede separar a los creyentes de la unión con Cristo. Aquellos a quienes más amamos, sí, hasta nuestros cuerpos, que cuidamos tanto, deben pronto volverse asquerosos montones de polvo y ser enterrados fuera de la vista. Entonces, ¡cuán sueltos estaremos de todas las ataduras y adornos terrenales! Procuremos más bien que nuestras almas estén adornadas con gracias celestiales.
Abraham rindió honor y respeto a los príncipes de Het, aunque eran impíos cananeos. La religión de la Biblia nos insta a respetar debidamente a todos los que están en autoridad, sin halagar sus personas ni alentar sus delitos si son persona indignas. La noble generosidad de estos cananeos avergüenza y condena el carácter cerrado, egoísta y áspero de muchos que se califican de israelitas. No fue por orgullo que Abraham rechazó la dádiva porque detestara estar obligado a Efrón, sino por justicia y prudencia. Abraham podía pagar el terreno y, por tanto, no quiso aprovecharse de la generosidad de Efrón. La honestidad, así como el honor nos prohíben aprovecharnos de la generosidad de nuestro prójimo e imponernos sobre los que dan libremente.</p>
<br/>
<p class="text-justify">Vv. 14-20.La prudencia y la justicia nos mandan ser equitativos y francos en nuestros tratos; los negocios engañosos no iluminan. Abraham paga el dinero sin fraude ni demora. Paga todo de inmediato sin dejarse nada; y bien pesado, de buena ley entre mercaderes, sin engaño. Véase cómo se usaba antiguamente el dinero, para facilidad del comercio, y con cuánta honestidad debía pagarse una deuda. Aunque toda la tierra de Canaán era de Abraham por la promesa, aún no había llegado el tiempo de poseerla, y él tuvo la ocasión de comprar y pagar. El dominio no se funda en la gracia. El derecho de los santos a una herencia eterna no les da derecho a las posesiones de este mundo ni les justifica para hacer el mal.
Honesta y equitativamente Efrón hace un título válido de la tierra. Como aquello se compra, debe pagarse con honestidad, así lo que se vende debe ser entregado y asegurado honestamente. Manejemos nuestras preocupaciones con puntualidad y exactitud para evitar discordias.
Abraham enterró a Sara en la cueva o bóveda, que había en el campo comprado. Eso le haría querida la tierra a su descendencia. Vale la pena notar que un lugar para sepultar era el único trozo de tierra que Abraham poseía en Canaán. Los que menos tienen en esta tierra, encuentran una tumba en ella. Este sepulcro estaba en el extremo del campo; cualesquiera sean nuestras posesiones, hay un lugar para sepultura al final de ellas. Era una señal de su fe y esperanza de resurrección. Abraham se contenta con seguir siendo un peregrino mientras viva, pero se asegura un lugar donde, cuando muerta, su carne pueda descansar con esperanza. Después de todo, la principal preocupación es con quién resucitaremos.</p>
<br/>




</div>
