<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 49</h2>
<p class="text-justify">Vv. 1, 2.Todos los hijos de Jacob estaban vivos. Su llamado que los hizo reunirse fue un precepto para que ellos se unieran en amor y no se mezclaran con los egipcios; y predijo que no iban a separarse como lo hicieran los hijos de Abraham y de Isaac, sino que todos debían formar un solo pueblo.
No vamos a considerar este discurso como expresión de sentimientos particulares de afecto, resentimiento o parcialidad, sino como lenguaje del Espíritu Santo que declara el propósito de Dios respecto del carácter, las circunstancias y la situación de las tribus que descendían de los hijos de Jacob y que puede identificarse en sus historias.</p>
<br/>
<p class="text-justify">Vv. 3-7.Rubén fue el primogénito pero por gran pecado perdió su primogenitura. El carácter de Rubén era inestable como el agua. Los hombres no prosperan porque no se establecen. El pecado de Rubén dejó una infamia perdurable en su familia. Nunca hagamos mal y, entonces, no temeremos que nos hablen al respecto.
Simeón y Leví eran apasionados y vengativos. El asesinato de los siquemitas es una prueba. Jacob protestó contra ese acto bárbaro. Nuestra alma es nuestro honor; por sus capacidades somos distinguidos de las bestias que perecen, y somos elevados por sobre ellas. De todo corazón debemos aborrecer a todo hombre sanguinario y malo. Maldita sea su ira. Jacob no maldice a sus personas sino sus lujurias. Yo las dividiré. La sentencia acerca de Leví se iba a convertir en bendición. Esta tribu realizó un servicio agradable a Dios en su celo contra los adoradores del becerro de oro, Éxodo xxxii. Habiendo sido apartados por Dios como sacerdotes, en ese carácter fueron esparcidos por la nación de Israel.</p>
<br/>
<p class="text-justify">Vv. 8-12.El nombre de Judá significa alabanza. Dios era alabado por su causa, capítulo xxix, 35, alabado por él y alabado en él; por tanto, sus hermanos le alabarán. Judá será una tribu fuerte y valiente. Judá es comparado, no con un león enfurecido y rugiente, sino con un león que disfruta la satisfacción de su fuerza y éxito sin vejar a los demás; esto es ser verdaderamente grande. Judá será la tribu real, la tribu de la cual vendrá el Mesías Príncipe. Silo, esa Simiente prometida en quien la tierra será bendecida, “ese pacífico y próspero”, o “Salvador”vendrá de Judá. Así, pues, el moribundo Jacob vio, de lejos, el día de Cristo y eso le fue consuelo y sostén en su lecho de muerte. Hasta la venida de Cristo, Judá poseyó autoridad, pero, después de su crucifixión, esta fue disminuida y, conforme a lo anunciado por Cristo, Jerusalén fue destruida y todo el remanente pobre y perseguido de los judíos fue confundido.
Mucho de lo que aquí se dice de Judá, debe aplicarse a nuestro Señor Jesús. En Él hay abundancia de todo lo que alimenta y refresca el alma y que mantiene y alegra la vida divina en ella. Él es la vid verdadera; el vino es el símbolo señalado de su sangre, que se bebe, derramada en favor de los pecadores y aplicada por fe; y todas las bendiciones de su evangelio son vino y leche, sin dinero y sin precio, a lo cual es bienvenida toda alma sedienta, Isaías lv, 1.</p>
<br/>
<p class="text-justify">Vv. 13-18.Acerca de Zabulón: si la profecía dice que Zabulón será un puerto de barcos, ciertamente la providencia lo hará así. Dios designa los límites de nuestra habitación. Sabiduría y deber nuestro es acomodarnos a nuestra suerte y mejorarla; si Zabulón habita en el puerto del mar, que sea refugio de barcos.
Tocante a Isacar: él vio que la tierra era deleitosa, produciendo no sólo perspectivas gratas sino buenos frutos para recompensar sus esfuerzos. Veamos, con el ojo de la fe, que el reposo celestial sea bueno y la tierra prometida deleitosa; esto hará que nuestro servicio presente sea fácil.
Dan iba a ganar, por artes y política y sorpresa, ventajas contra sus enemigos, como serpiente que muerde el calcañar del viajero.
Jacob, casi extenuado y listo para desmayar, lo alivia con estas palabras: “Tu salvación esperé, oh Jehová”. La salvación que esperaba era Cristo, la Simiente prometida; ahora que él iba a ser reunido con su pueblo, suspira por Aquel a cuyo alrededor será la reunión del pueblo. Declara sencillamente que busca el cielo, la patria mejor, Hebreos xi, 13, 14. Ahora que va a disfrutar la salvación, se consuela por haber esperado la salvación. Como nuestro camino al cielo hay que esperar en Cristo, y el cielo, hay que esperarlo como nuestro reposo en Cristo. Es consuelo del santo moribundo haber esperado la salvación del Señor, pues entonces tendrá lo que ha estado esperando.</p>
<br/>
<p class="text-justify">Vv. 19-21.En cuanto a Gad, alude Jacob a su nombre que significa ejército y anuncia el carácter de esta tribu. La causa de Dios y su pueblo, aunque por una vez pueda parecer derrotada y acabada, al final será victoriosa. Representa al conflicto cristiano. La gracia del alma suele ir envuelta en sus conflictos; las huestes de corrupción la vencen, pero la causa es de Dios y al final la gracia saldrá vencedora, sí, más que vencedora, Romanos viii, 37.
Aser debe ser una tribu rica. Su herencia bordeaba el Carmelo que era proverbialmente fructífero.
Neftalí, es una cierva suelta. Podemos considerarlo como descripción del carácter de esta tribu. A diferencia del laborioso buey y del asno, está deseoso de comodidad y libertad, activo, pero más notorio por la acción rápida que por la labor constante y la perseverancia. Como el suplicante que, con palabras buenas, anhela misericordia. Que no se censuren ni envidien unos a otros los que tienen diferentes temperamentos y dones.</p>
<br/>
<p class="text-justify">Vv. 22-27.La bendición de José es muy plena. Lo que dice Jacob de él es historia y profecía. Jacob le recuerda las dificultades y fieros dardos de las tentaciones con que anteriormente luchó. Su fe no falló, antes bien, en medio de sus pruebas llevó todas sus cargas con firmeza y no hizo nada inconveniente. Toda nuestra fortaleza para resistir las tentaciones y soportar las aflicciones viene de Dios; su gracia es suficiente.
José llegó a ser el pastor de Israel para cuidar de su padre y de su familia, y la roca de Israel, su fundamento y firme soporte. En esto, como en muchas otras cosas, José fue un notable tipo del Buen Pastor y la Piedra del Ángulo probada de toda la iglesia de Dios.
Las bendiciones son prometidas para la posteridad de José, típicas de las vastas y eternas bendiciones que vienen sobre la simiente espiritual de Cristo. Jacob bendijo a todos sus hijos pero especialmente a José, “que fue apartado de sus hermanos”. No sólo separado en Egipto sino, por poseer una eminente dignidad y por ser más consagrado a Dios.
Se dice de Benjamín que arrebatará como lobo. Jacob fue guiado por el Espíritu de profecía en lo que dijo y no por el afecto natural; de lo contrario, hubiera hablado con más ternura de su amado hijo Benjamín. Tocante a él solamente prevé y predice que su posteridad será una tribu guerrera, fuerte y osada, y que se enriquecerá con los despojos de sus enemigos; que serán activos. El bendito Pablo era de esta tribu, Romanos xi, 1; Filipenses iii, 5; en el amanecer de su día, devoró la presa como perseguidor, pero en el ocaso repartió el botín como predicador; él compartió las bendiciones del León de Judá y participó en sus victorias.</p>
<br/>
<p class="text-justify">Vv. 28-33.Jacob bendijo a cada uno conforme a las bendiciones que Dios tenía como objetivo otorgarles en tiempos posteriores.
Habló del lugar de su sepultura desde un principio de fe en la promesa de Dios, de que Canaán sería la heredad de su simiente en el momento debido. Cuando hubo terminado sus bendiciones y sus encargos y, por tanto, su testimonio, se concentró en su tarea de morir. Encogió los pies en la cama, no sólo como uno que pacientemente se somete al golpe, sino como quien alegremente se acomoda para descansar, ahora que estaba agotado. Entregó libremente su espíritu en la mano de Dios, el Padre de los espíritus. Si el pueblo de Dios es nuestro pueblo, la muerte nos reunirá con ellos. Bajo el cuidado del Pastor de Israel, nada nos faltará para el cuerpo o el alma. Permaneceremos firmes hasta que esté terminada nuestra obra; entonces, expiraremos nuestras almas en las manos de Aquel cuya salvación hemos esperado, partiremos en paz y dejaremos tras nosotros una bendición para nuestros hijos.</p>
<br/>




</div>
