<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 5</h2>
<p class="text-justify">Vv. 1-5.Adán fue hecho a imagen de Dios; pero estando caído engendró un hijo a su propia imagen, pecador y corrupto, frágil, miserable y mortal, como él mismo. No solamente hombre como él mismo, compuesto de cuerpo y alma, sino pecador como él mismo. Esto es lo contrario de la semejanza divina en que fue hecho Adán; habiéndola perdido, no podía transmitirla a su simiente.
Adán vivió 930 años en total; y entonces murió, conforme a la sentencia dictada: “al polvo volverás”.
Aunque no murió el día en que comió el fruto prohibido, ese mismo día se volvió mortal. Entonces empezó a morir; toda su vida posterior no fue sino una ejecución demorada, una vida condenada y perdida; fue una vida moribunda y desolada. La vida del hombre no es sino un morir gradualmente.</p>
<br/>
<p class="text-justify">Vv. 6-20.Se dice ‘y murió’de cada uno de estos, salvo de Enoc. Bueno es observar la muerte de los demás. Todos ellos vivieron mucho; ni uno solo de ellos murió sino hasta tener casi ochocientos años y, algunos vivieron mucho más que eso; un tiempo muy largo para que un alma inmortal esté presa en una vivienda de barro. Seguramente la vida presente no era para ellos tanta carga como lo es corrientemente ahora, de otro modo se hubieran cansado de ella. Tampoco la vida futura había sido entonces tan claramente revelada como ahora bajo el evangelio, de lo contrario hubieran estado urgidos por irse a ella. Todos los patriarcas que vivieron antes del diluvio, salvo Noé, nacieron antes que muriera Adán. De él deben de haber recibido un relato total de la creación, la caída, la promesa y los preceptos divinos sobre la adoración y la vida religiosa. Así, Dios mantuvo en su iglesia el conocimiento de su voluntad.</p>
<br/>
<p class="text-justify">Vv. 21-24.Enoc fue el séptimo contando desde Adán. La piedad es caminar con Dios: lo cual muestra la reconciliación con Dios, pues dos no pueden andar juntos si no estuvieren de acuerdo, Amos iii. 3. Incluye todas las partes de una vida santa, recta y sobria. Caminar con Dios es tener a Dios siempre delante de nosotros, actuar como estando siempre bajo su mirada. Es preocuparse constantemente de agradar a Dios en todas las cosas y en nada ofenderle. Es ser seguidores de él como hijos amados. El Espíritu Santo dice que caminó Enoc con Dios en lugar de decir vivió Enoc (con Dios). Esta fue su preocupación y trabajo constante; mientras los demás vivían para sí mismos y el mundo, él vivió para Dios. Era el gozo de su vida.
Enoc fue llevado a un mundo mejor. Como él no vivió como el resto de la humanidad, él no salió del mundo por la muerte, como los demás. No fue hallado porque lo traspuso Dios, Hebreos xi, 5. Él había vivido sólo 365 años que, según la edad de los hombres de aquel entonces, era solo la mitad de la vida de ellos. A menudo Dios se lleva más pronto a los que Él ama; el tiempo perdido en la tierra lo ganan en el cielo, inefable ventaja para ellos. Vea cómo se expresa la trasposición de Enoc: desapareció porque le llevó Dios.
Ya no estuvo más en este mundo; fue transformado, como lo serán todos los santos que estén vivos en la segunda venida de Cristo.
Quienes empiezan a caminar con Dios cuando son jóvenes tienen la esperanza de caminar con Él larga, cómoda y servicialmente. La marcha constante en santidad del cristiano verdadero, por muchos años, hasta que Dios lo lleve, es la mejor recomendación para la religión a la que muchos se oponen y contra la cual muchos abusan. Caminar con Dios concuerda bien con las preocupaciones, consuelos y deberes de la vida.</p>
<br/>
<p class="text-justify">Vv. 25-32.Matusalén significa “cuando él muera, vendrá como un dardo”, o ‘un envío’a saber el diluvio que vino el año en que murió Matusalén. Vivió 969 años la vida más larga de un hombre sobre la tierra; pero aun el que viva más debe morir al fin.
Noé significa descanso ; sus padres le dieron ese nombre, con la perspectiva de que él fuera una gran bendición para su generación. Observe la queja de su padre acerca del estado calamitoso de la vida humana, debido a la entrada del pecado y a la maldición por el pecado. Toda nuestra vida se gasta en trabajar y nuestro tiempo se llena con esfuerzo continuo. Por haber maldecido Dios a la tierra, lo más que algunos pueden hacer, con el mayor cuidado y aflicciones, es obtener una dura manutención de ésta. Lamec esperaba alivio por el nacimiento de este hijo: “Este nos aliviará de nuestras obras”. Eso significa no sólo el deseo y expectativa que generalmente tienen los padres tocante a sus hijos, de que ellos sean consuelo y ayuda para ellos, aunque a menudo resultan ser otra cosa; sino que también significa una perspectiva de algo más. ¿Cristo es nuestro? ¿El cielo es nuestro? En nuestro afán y aflicción necesitamos mejores consoladores que las más caras relaciones y la más prometedora descendencia; podemos buscar y hallar consuelo en Cristo.</p>
<br/>




</div>
