<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 2</h2>
<p class="text-justify">Vv. 1-3.Después de seis días Dios cesó todas las obras de creación. En los milagros ha usado leyes superiores de la naturaleza, pero nunca ha cambiado su curso establecido, ni le ha agregado. Dios no descansó como si estuviera cansado sino como alguien que está muy complacido. Nótese al comienzo mismo del reino de gracia, la santificación o la observancia sagrada del día de reposo. La observancia solemne de un día de cada siete como día de sagrado reposo y de santo trabajo, para la honra de Dios, es deber de toda persona a quien Dios ha dado a conocer sus santos días de reposo. En este momento, nadie de la raza humana tenía ser sino nuestros primeros padres. Para ellos fue instituido el día de reposo y, es claro, también para todas las generaciones sucesivas. El reposo cristiano que observamos es un día séptimo y en él celebramos el reposo del Dios Hijo y la consumación de la obra de nuestra redención.</p>
<br/>
<p class="text-justify">Vv. 4-7.Aquí se da un nombre al Creador: “Jehová”. Jehová es el nombre de Dios que denota que sólo Él tiene su ser de sí mismo, y que Él da el ser a todas las criaturas y cosas.
Además se destacan las plantas y las hierbas porque fueron hechas y señaladas como alimento para el hombre. La tierra no produjo sus frutos por su propio poder: esto fue hecho por el poder del Omnipotente. De la misma manera, la gracia del alma no crece por sí misma en el terreno de la naturaleza; es la obra de Dios. La lluvia es también dádiva de Dios; no llovió sino hasta que Dios hizo llover. Aunque Dios obra usando medios, cuando le agrada puede, no obstante, hacer su obra sin medios; y aunque nosotros no hemos de tentar a Dios descuidando los medios, debemos confiar en Él tanto en el uso como en la falta de medios. De una u otra manera Dios regará las plantas de su plantío. La gracia divina desciende como el rocío y silenciosamente riega la iglesia sin hacer ruido. El hombre fue hecho de polvo menudo, como el que hay en la superficie de la tierra. El alma no fue hecha de la tierra como el cuerpo: lástima entonces que deba apegarse a la tierra y preocuparse por las cosas terrenales. En breve daremos cuenta a Dios por la forma en que hemos empleado estas almas; y si se encuentra que las hemos perdido, aunque fuera para ganar el mundo, ¡estamos perdidos para siempre! Los necios desprecian sus propias almas al preocuparse de sus cuerpos antes que de sus almas.</p>
<br/>
<p class="text-justify">Vv. 8-14.El lugar fijado para que Adán habitara no era un palacio sino un huerto. Mientras mejor nos arreglemos con cosas sencillas y menos busquemos las cosas que complacen el orgullo y la lujuria, más cerca estaremos de la inocencia. La naturaleza se contenta con un poco y aquello que es más natural; la gracia con menos ; pero la lujuria lo desea todo y se contenta con nada . Ningún placer puede satisfacer el alma sino aquello que Dios mismo ha provisto y señalado para ello. Edén significa deleite y placer. No importa cuál haya sido su localización, tenía todas las comodidades deseables, sin ninguna desventaja, como nunca jamás haya sido otra casa o huerto en la tierra. Estaba adornado con todo árbol agradable a la vista y enriquecido con todo árbol que diera fruto agradable al paladar y bueno para comer. Como Padre tierno, Dios deseaba no sólo el provecho de Adán, sino su placer; porque hay placer con inocencia, mejor aun, hay verdadero placer sólo en la inocencia. Cuando la Providencia nos pone en un lugar de abundancia y placer, debiéramos servir a Dios con alegría de corazón por las cosas buenas que nos da. Edén tenía dos árboles exclusivos.
1. En el medio del huerto estaba el árbol de la vida. El hombre podría comer de este y vivir. Cristo es ahora el Árbol de la vida para nosotros, Apocalipsis ii. 7; xxii. 2; y el Pan de vida, Juan vi. 48, 51.
2. Estaba el árbol de la ciencia del bien y el mal, llamado así porque había una revelación positiva de la voluntad de Dios acerca de este árbol, de manera que por él el hombre podía llegar a conocer el bien y el mal moral. ¿Qué es bueno? Bueno es no comer de este árbol. ¿Qué es malo? Malo es comer de este árbol. En estos dos árboles Dios puso ante Adán el bien y el mal, la bendición y la maldición.</p>
<br/>
<p class="text-justify">V. 15.Después que Dios hubo formado a Adán, lo puso en el huerto. Así toda jactancia quedó excluida. Solamente el que nos hizo puede hacernos felices; el que es el Formador de nuestros cuerpos, y el Padre de nuestros espíritus, y nadie sino Él, puede proveer plenamente para la felicidad de cuerpo y alma. Aún en el mismo paraíso el hombre tenía que trabajar. Ninguno de nosotros fue enviado al mundo para estar ocioso. El que hizo nuestras almas y cuerpos, nos ha dado algo con qué trabajar; y el que nos dio esta tierra por habitación, nos ha dado algo sobre qué trabajar. Los hijos y herederos del cielo, mientras están en el mundo, tienen algo que hacer por esta tierra, la cual debe tener su cuota de tiempo y preocupación de parte de ellos; y si lo hacen mirando a Dios, y le sirven tan verdaderamente en ello como cuando están de rodillas. Observe que el llamamiento del agricultor es un llamado antiguo y honorable; era necesario hasta en el paraíso. Además, hay verdadero placer en las tareas a las que Dios nos llama y en las que nos emplea. Adán no hubiera podido ser feliz si hubiera estado ocioso: sigue siendo la ley de Dios que aquel que no trabaja no tiene derecho a comer, 2 Tesalonicenses iii. 10.</p>
<br/>
<p class="text-justify">Vv. 16, 17.No pongamos nunca nuestra propia voluntad contra la santa voluntad de Dios. No sólo se otorgó libertad al hombre para tomar los frutos del paraíso, sino se le aseguró la vida eterna por su obediencia. Se había establecido una prueba para su obediencia. Por la transgresión él perdería el favor de su Hacedor y se haría merecedor de su desagrado, con todos sus espantosos efectos; de esta manera él quedaría propenso al dolor, la enfermedad y la muerte. Peor que eso, él iba a perder la santa imagen de Dios y todo el consuelo de su aprobación; y sintiendo el tormento de las pasiones pecaminosas y el terror de la venganza de su Hacedor, la cual tendría que soportar para siempre con su alma que nunca muere. La prohibición de comer el fruto de un árbol en particular era sabiamente adecuada para el estado de nuestros primeros padres. En su estado de inocencia y apartados de los demás, ¿qué ocasión o qué tentación tenían para romper alguno de los diez mandamientos? El desarrollo de los acontecimientos prueba que toda la raza humana estaba comprometida en la prueba y caída de nuestros primeros padres. Argumentar contra estas cosas es luchar contra hechos irrebatibles, y contra la revelación divina; porque el hombre es pecador y muestra por sus primeros actos y por su conducta posterior, que está siempre dispuesto para hacer el mal. Está sometido al desagrado divino, expuesto a los sufrimientos y a la muerte. Las Escrituras siempre hablan del hombre como que tiene un carácter pecador y está en este estado de miseria; y estas cosas valen para los hombres de todas las épocas y de todas las naciones.</p>
<br/>
<p class="text-justify">Vv. 18-25.El hombre recibió el poder sobre las criaturas y, como prueba de esto, les puso nombre a todas. Este hecho muestra además su discernimiento en cuanto a las obras de Dios. Aunque era señor de las criaturas, nada de este mundo era una ayuda idónea para el hombre. De Dios son todas nuestras ayudas. Si descansamos en Dios Él obrará todo para bien. Dios hizo que un sueño profundo cayera sobre Adán; por cuanto no conoce el pecado, Dios cuida que el hombre no sienta dolor. Dios, como Padre de ella, trajo la mujer al hombre, como su segundo ser y como su ayuda idónea. Esa esposa, hechura de Dios por gracia especial, y producto de Dios por providencia especial, probablemente demuestre ser la ayuda idónea para el hombre. Véase qué necesidad hay, tanto de prudencia como de oración, al elegir esta relación que es tan cercana y tan duradera. Había necesidad de hacer bien esto que se hace para toda la vida.
Nuestros primeros padres no necesitaban ropa para cubrirse del frío o el calor pues no podían dañarlos: tampoco la necesitaban para ataviarse. Así de desahogada, así de feliz era la vida del hombre en su estado de inocencia. ¡Cuán bueno era Dios para él! ¡Con cuántos favores Él le cargó! ¡Cuán ligeras eran las leyes que le fueron dadas! Sin embargo, el hombre, en medio de toda esta honra, no entendió su propio interés sino que pronto se volvió como las bestias que perecen.</p>
<br/>




</div>
