<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">Vv. 1-5.Satanás atacó a nuestros primeros padres para llevarlos a pecar; la tentación les resultó fatal. El tentador fue el diablo, en la forma y semejanza de una serpiente. El plan de Satanás era arrastrar a nuestros primeros padres al pecado y, así, poner separación entre ellos y su Dios. De este modo el diablo fue desde el comienzo un homicida y gran obrador de maldades. La persona tentada fue la mujer: la táctica de Satanás fue entablar una conversación con ella mientras estaba sola. Hay muchas tentaciones en las que el estar a solas da gran ventaja al tentador; en cambio, la comunión de los santos cuida en gran medida la fortaleza y seguridad de ellos. Satanás sacó ventaja de hallar a la mujer sola cerca del árbol prohibido.
Satanás tentó a Eva para, a través ella, poder tentar a Adán. Su táctica es enviar las tentaciones por medios que no sospechamos, y por quienes tienen la mayor influencia sobre nosotros. Satanás puso en duda si era o no era pecado comer de este árbol. No dejó al descubierto su designio al comienzo, pero planteó una pregunta que parecía inocente. El que quiera estar a salvo debe cuidarse de no hablar con el tentador. Citó mal el mandamiento. Él habló en forma sarcástica. El diablo, así como es un mentiroso, es también un escarnecedor desde el principio; y los escarnecedores son sus hijos. El arte de Satanás consiste en hablar de la ley divina como dudosa o irracional y, así, atrae la gente al pecado; nuestra sabiduría consiste en mantener firme nuestra creencia en el mandamiento de Dios y un elevado respeto por Él. ¿Conque Dios dijo: ¿No mentiréis, no tomaréis su nombre en vano, no os emborracharéis, etc.? Sí, estoy seguro que lo dijo, y está bien dicho; y, por su gracia, yo lo cumpliré.
El entablar esta conversación con la serpiente fue debilidad de Eva: por su pregunta debió notar que no tenía buenas intenciones, y por tanto, debió retroceder. Satanás enseña primero a los hombres a dudar y, luego, a negar. Les promete beneficios si comen de este fruto. Su objetivo es introducir el descontento con su estado presente, como si no fuera tan bueno como pudiera y debiera ser. Ningún estado por si mismo dará contento a menos que la mente sea puesta en ello. Los tienta para que busquen ascender como si fueran dignos de ser dioses. Satanás se arruinó a sí mismo cuando deseó ser como el Altísimo, luego, procuró infectar a nuestros primeros padres con el mismo deseo para arruinarlos también. El diablo sigue aún atrayendo a la gente a su esfera de interés sugiriéndoles pensamientos malos acerca de Dios y falsas esperanzas de lograr beneficios por medio del pecado. Por tanto, pensemos siempre bien de Dios como el sumo bien y pensemos mal del pecado como el sumo mal: así resistiremos al diablo y él huirá de nosotros.</p>
<br/>
<p class="text-justify">Vv. 6-8.Observe los pasos de la transgresión: no son pasos ascendentes sino descen-dentes hacia el abismo.
1. Ella vio . Una gran cantidad de pecado viene por los ojos. No miremos aquello que trae consigo el riesgo de estimular la concupiscencia, Mateo v. 28.
2. Ella tomó . Fue su propio acto y obra. Satanás puede tentar pero no puede obligar; puede persuadirnos a que nos arrojemos al precipicio pero no puede arrojarnos, Mateo iv. 6.
3. Ella comió . Cuando miró quizás no tuviera la intención de tomarlo; o cuando lo tomó no tuviera la intención de comer; pero acabó en eso. Es sabiduría detener los primeros movimientos del pecado, y abandonarlo antes de verse comprometido con él.
4. También dio a su marido. Quienes han hecho mal, están dispuestos a arrastrar a otros a hacer lo mismo.
5. Ella comió . Al no tomar en cuenta el árbol de la vida. Del cual se le permitía comer, y al comer del árbol del conocimiento, que estaba prohibido, Adán claramente muestra su desdén por lo que Dios le ha otorgado, y su deseo por lo que Dios consideró prudente no darle. Deseaba tener lo que quería y hacer lo que le placiera. En una palabra su pecado fue la desobediencia, Romanos v, 19; la desobediencia a un mandato claro, simple y expreso. No tenía una naturaleza pecaminosa que lo traicionara; en cambio tenía libertad de voluntad, con toda su fuerza, no debilitada ni desequilibrada. Se apartó con mucha prontitud. Arrastró a toda su posteridad al pecado y a la miseria. Entonces, ¿quién puede decir que el pecado de Adán en sí causó poco daño? -Ya era demasiado tarde, cuando Adán y Eva vieron la necedad de comer la fruta prohibida. Vieron la felicidad de la cual cayeron y la miseria en que se hundieron. Vieron a un Dios amante irritado, y la pérdida de su gracia y su favor. Véase aquí qué deshonra y trastorno produce el pecado; hace maldad doquiera se introduce y destruye todo consuelo. Tarde o temprano acarrea la vergüenza; sea la vergüenza del arrepentimiento verdadero, que termina en gloria, o la vergüenza y confusión perpetua, en la cual despertarán los malos en el gran día. Véase aquí en qué consiste corrientemente la necedad de quienes han pecado. Cuidan más de salvar su crédito ante los hombres que obtener el perdón de Dios. Las excusas que dan los hombres para cubrir y restar importancia a sus pecados, son vanas y frívolas; como los delantales de hojas de higuera que se hicieron, no logran mejorar las cosas: no obstante, todos tenemos la tendencia a cubrir nuestras transgresiones como Adán. Antes de pecar ellos acogían con gozo humilde las bondadosas visitas de Dios; ahora Él se convertía en un terror para ellos. No cabe asombrarse de que se convirtieran en terror para sí mismos y se llenaran de confusión. Esto muestra la falsedad del tentador y el fraude de sus tentaciones. Satanás prometió que estarían a salvo. Pero ¡ellos no pueden ni pensar que sea así! Adán y Eva eran, ahora, consoladores desdichados el uno para el otro!</p>
<br/>
<p class="text-justify">Vv. 9-13.Observe la sorprendente pregunta: ¿Adán, dónde estás tú? Aquellos que se descarrían de Dios por el pecado deben considerar seriamente donde están: están lejos de todo bien, en medio de sus enemigos, esclavizados a Satanás, y en el camino real a la ruina total. Esta oveja perdida hubiera vagado sin fin si el buen Pastor no la hubiera buscado y le hubiera dicho que el lugar donde estaba descarriado, no podría ser fácil ni cómodo. Si los pecadores quisieran considerar donde están, no descansarían hasta regresar a Dios.
Es falla y necedad común de quienes han hecho mal cuando se les pregunta al respecto, el reconocer sólo lo que es tan evidente que no se puede negar. Como Adán tenemos razón para tener miedo de acercarnos a Dios si no estamos cubiertos y vestidos con la justicia de Cristo. El pecado aparece más claro en el espejo del mandamiento, así que, Dios lo puso ante Adán; y en ese espejo debemos mirar nuestro rostro. Pero en lugar de reconocer el pecado en toda su magnitud, y asumir la vergüenza en ellos mismos, Adán y Eva justificaron el pecado y cargaron la vergüenza y la culpa en otros. En quienes son tentados existe una extraña tendencia a decir que son tentados por Dios; como si nuestro abuso de los dones de Dios disculpara nuestra transgresión de las leyes de Dios. Los que están prontos a aceptar el placer y ganancia del pecado son tardos para asumir la culpa y la vergüenza de ello. Aprendamos entonces, que las tentaciones de Satanás son todas seducciones; sus argumentos, todos engañosos; sus incentivos son todos trampas; cuando habla bien, no hay que creerle. Es por el engaño del pecado que el corazón se endurece. Vea Romanos vii. 11; Hebreos iii, 13. Aunque la sutileza de Satanás pudiera arrastrarnos al pecado, de ninguna manera nos justifica que estemos en pecado. Aunque él es el tentador, nosotros somos los pecadores. Que no disminuya nuestro pesar por el pecado el que hayamos sido engañados; antes bien, que aumente nuestra indignación con nosotros mismos por haber permitido ser engañados por un conocido tramposo y enemigo jurado, que quiere la destrucción de nuestra alma.</p>
<br/>
<p class="text-justify">Vv. 14, 15.Dios dicta sentencia; y comienza donde empezó el pecado, con la serpiente. Los instrumentos del diablo deben compartir los castigos del diablo. Bajo el disfraz de la serpiente el diablo es sentenciado a ser degradado y maldecido por Dios; detestado y aborrecido por toda la humanidad: también a ser destruido y arruinado al final por el gran Redentor, cosa significada por el aplastamiento de su cabeza. Se declara la guerra entre la Simiente de la mujer y la simiente de la serpiente. El fruto de esta enemistad es que haya una guerra continua entre la gracia y la corrupción en los corazones del pueblo de Dios. Satanás, por medio de sus corrupciones los abofetea, los zarandea y procura devorarlos. El cielo y el infierno nunca pueden ser reconciliados, tampoco la luz y las tinieblas; no más que Satanás y un alma santificada. Además, hay una lucha continua entre los malos y los santos de este mundo. Se hace una promesa bondadosa sobre Cristo, como el libertador del hombre caído del poder de Satanás. Esta era la aurora del día del evangelio: tan pronto como fue hecha la herida se proveyó y reveló el remedio. Esta bondadosa revelación de un Salvador llegó sin que la pidieran ni la buscaran. Sin una revelación de misericordia, que da esperanzas de perdón, el pecador convicto se hundiría en la desesperación y se endurecería. Por fe en esta promesa fueron justificados y salvados nuestros primeros padres, y los patriarcas anteriores al diluvio. Se dan detalles sobre Cristo.
1. Su encarnación o venida en la carne. Que su Salvador sea la Simiente de la mujer, hueso de nuestro hueso, da gran aliento a los pecadores, Hebreos ii. 11, 14.
2. Sus sufrimientos y muerte ; señalados en que Satanás heriría su calcañar, esto es, su naturaleza humana. Los sufrimientos de Cristo continúan en los sufrimientos de los santos por su nombre. El diablo los tienta, los persigue y los mata; y así, hiere el calcañar de Cristo, que es afligido en las aflicciones de los santos. Pero mientras el calcañar es herido en la tierra, la Cabeza está en el cielo.
3. Su victoria sobre Satanás. Cristo frustró las tentaciones de Satanás, rescató almas de sus manos. Por su muerte asestó un golpe fatal al reino del diablo, una herida incurable en la cabeza de esta serpiente. A medida que el evangelio gana terreno, Satanás cae.</p>
<br/>
<p class="text-justify">Vv. 16-19.Por su pecado la mujer es condenada a un estado de pesar y sumisión; castigo adecuado de ese pecado en que ella procuró satisfacer la concupiscencia de los ojos y de la carne, y su orgullo. El pecado trajo dolor al mundo; hizo del mundo un valle de lágrimas. No es de extrañar que nuestros dolores se multipliquen cuando nuestros pecados se multiplican. Él se enseñoreará de ti, es sólo el mandamiento de Dios: Esposas, someteos a vuestros maridos.
Si el hombre no hubiera pecado, siempre se hubiera enseñoreado con sabiduría y amor; si la mujer no hubiera pecado, ella siempre hubiera obedecido con humildad y mansedumbre. Adán culpó a su esposa, pero aunque había sido falta suya el convencerlo para que comiera el fruto prohibido, fue falta de Adán el haberle hecho caso. Así que las frívolas excusas de los hombres se volverán contra ellos en el día del juicio de Dios. Dios puso marcas de desagrado en Adán.
1. Maldice su habitación. Dios dio la tierra a los hijos de los hombres para que fuera una morada cómoda, pero ahora está maldita por el pecado del hombre. Sin embargo, Adán mismo no es maldecido, como lo fue la serpiente, sino tan sólo el suelo por amor a él.
2. Sus esfuerzos y placeres le son amargos . El trabajo es nuestro deber y debemos realizarlo fielmente; es parte de la sentencia del hombre, cosa que la ociosidad desafía atrevidamente. La incomodidad y el cansancio en el trabajo son nuestro justo castigo, al cual debemos someternos con paciencia, puesto que son menos que lo merecido por nuestra iniquidad. El alimento del hombre se le volverá desagradable. Pero el hombre no es sentenciado a comer polvo como la serpiente, solamente a comer la hierba del campo.
3. Su vida también es acortada; pero considerando cuán llenos de problemas están sus días, es un favor que sean pocos. La muerte es espantosa por naturaleza, a pesar de que la vida es desagradable, y con eso concluye el castigo. El pecado introdujo la muerte al mundo: si Adán no hubiera pecado, no habría muerto. Él cedió a la tentación pero el Salvador la resistió. ¡Cuán admirablemente la satisfacción de nuestro Señor Jesús, por su muerte y sufrimientos, respondió a la sentencia dictada contra nuestros primeros padres! ¿Entraron los dolores de parto a causa del pecado? Leemos del fruto de la aflicción del alma de Cristo, Isaías, liii, 11; y los dolores de la muerte que lo retuvo, son así llamados, Hechos ii, 24. ¿Entró el quedar bajo la ley con el pecado? Cristo nació bajo la ley, Gálatas iv, 4. ¿Entró la maldición con el pecado? Cristo fue hecho maldición por nosotros, y murió una muerte maldita, Gálatas iii, 13. ¿Vinieron las espinas con el pecado? Él fue coronado con espinas por nosotros. ¿El sudor llega a causa del pecado? Él sudó por nosotros, y su sudor fue como grandes gotas de sangre. ¿Llegó el dolor con el pecado? Él fue un varón de dolores; en su agonía su alma estuvo sobre manera dolorida. ¿Vino la muerte con el pecado? Él se hizo obediente hasta la muerte. Así, la venda es tan grande como la herida. Bendito sea Dios por su Hijo nuestro Señor Jesucristo.</p>
<br/>
<p class="text-justify">Vv. 20, 21.Dios le puso nombre al hombre y lo llamó Adán, que significa tierra roja ; Adán le puso nombre a la mujer y la llamó Eva, esto es, vida . Adán lleva el nombre del cuerpo mortal, Eva el del alma viva. Probablemente Adán haya tenido en cuenta la bendición de un Redentor, la Simiente prometida, al llamar Eva o vida a su esposa; pues Él sería la vida de todos los creyentes, y en Él serían benditas todas las familias de la tierra.
Véase, además, el cuidado de Dios por nuestros primeros padres a pesar de su pecado. La vestimenta se introdujo con el pecado. Poca razón tenemos al enorgullecernos de nuestras ropas que no son sino la insignia de nuestra vergüenza. Cuando Dios hizo ropa para nuestros primeros padres, las hizo abrigadoras y fuertes, rústicas y muy sencillas; no mantos de escarlata sino túnicas de pieles. Que quienes están pobremente vestidos aprendan de aquí a no quejarse. Teniendo comida y abrigo, que estén contentos; ellos están tan bien como Adán y Eva. Que aquellos que están finamente vestidos, aprendan a no hacer de las vestimentas su adorno.
Se supone que las bestias, de cuyas pieles los vistió Dios, fueron muertas, no para comida del hombre, sino para sacrificio, para tipificar a Cristo, el gran Sacrificio. Adán y Eva se hicieron delantales de hojas de higuera, cubierta demasiado estrecha para envolverlos, Isaías xxviii, 20. Tales son todos los trapos de nuestra justicia propia. Pero Dios les hizo túnicas de pieles, grandes, firmes, durables y de su medida: tal es la justicia de Cristo; por tanto, vestíos del Señor Jesucristo.</p>
<br/>
<p class="text-justify">Vv. 22-24.Dios expulsó al hombre; le dijo que ya no debía ocupar ni disfrutar ese huerto: pero al hombre le gustaba el lugar y no estaba dispuesto a irse, por tanto, Dios lo hizo salir. Esto significó la exclusión de él y toda su raza culpable de la comunión con Dios, que era la bendición y la gloria del paraíso. Pero el hombre fue solamente enviado a labrar el suelo del cual fue tomado. Él fue enviado a un lugar de trabajo arduo, no a un lugar de tormento. Nuestros primeros padres fueron excluidos de los privilegios de su estado de inocencia, aunque no fueron librados a la desesperación.
Se cerró el camino al árbol de la vida. De ahí en adelante sería en vano que él y los suyos esperaran rectitud, vida y felicidad por el pacto de obras; porque al quebrantar el mandamiento de ese pacto, su maldición cobra plena vigencia: somos todos destruidos si somos juzgados por ese pacto. Dios reveló esto a Adán, no para llevarlo a la desesperación, sino para animarlo a buscar la vida y la felicidad en la Simiente prometida, por quien se abre ante nosotros un camino nuevo y vivo hacia el lugar santísimo.</p>
<br/>




</div>
