<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 8</h2>
<p class="text-justify">Vv. 1-3. Toda la raza de la humanidad, salvo Noé y su familia, estaban ahora muertos, de modo que el acordarse Dios de Noé, fue el retorno de su misericordia a la humanidad, a la cual no había exterminado por completo. Las exigencias de la justicia divina habían sido contestadas por la ruina de los pecadores. Dios envió el viento para secar la tierra y selló sus aguas. La misma mano que trae la desolación debe traer la liberación; por tanto, debemos mirar siempre esa mano. Cuando las aflicciones han hecho la obra para la cual fueron enviadas, sea obra que mata o que cura, serán quitadas. Como la tierra no fue anegada en un día, tampoco se secó en un día. Dios suele liberar gradualmente a su pueblo para que no sea despreciado el día de las cosas pequeñas ni haya desconsuelo por el día de las grandes cosas.</p>
<br/>
<p class="text-justify">Vv. 4-12.El arca descansó sobre una montaña, hacia donde fue dirigida por la sabia y bondadosa providencia de Dios, para que pudiera descansar más pronto. Dios tiene tiempos y lugares de reposo para su pueblo después de haber sido zarandeado; y muchas veces Él hace provisión para que se establezca cómoda y oportunamente, sin estratagemas propias de ellos, y completamente más allá de lo que ellos pudieran prever.
Dios había dicho a Noé cuando vendría el diluvio, aunque no le dio una revelación detallada de los tiempos y pasos por los cuales terminaría. El conocimiento de lo anterior era necesario para la preparación del arca, pero el conocimiento de lo último hubiera servido sólo para satisfacer la curiosidad; el ocultárselo ejercitaría su fe y paciencia.
Noé envió a un cuervo del arca que siguió volando y comiendo de los cadáveres que flotaban. Luego Noé envió una paloma que volvió, la primera vez, sin buena noticia; pero la segunda vez, trajo en su pico una hoja que había arrancado de un olivo, mostrando simplemente que los árboles, los frutales, empezaban a aparecer sobre el agua. La segunda vez Noé envió la paloma a los siete días de la primera, y la tercera vez fue también a los siete días; probablemente en el día de reposo. Habiendo guardado el día de reposo con su pequeña iglesia, él esperaba una bendición especial del cielo y preguntó por ella. La paloma es un emblema de un alma bondadosa que, no hallando paz o satisfacción firmes en este mundo inundado y corrupto, regresa a Cristo como a su arca, como a su Noé, su reposo. El corazón carnal, como el cuervo, se arregla con el mundo y come de la carroña que encuentra ahí; pero, vuelve a mi reposo, oh alma mía, a tu Noé, así dice la palabra, Salmo cxvi, 7. Como Noé sacó su mano, tomó la paloma y la atrajo a él, al interior del arca, así Cristo salvará, ayudará y acogerá a los que huyen a Él en busca de reposo.</p>
<br/>
<p class="text-justify">Vv. 13-19.Dios consulta nuestro beneficio más que nuestros deseos; Él sabe lo que es bueno para nosotros mejor que nosotros mismos, y por cuánto tiempo más es conveniente que continúen nuestras restricciones y sean demoradas las misericordias anheladas. Nosotros saldríamos del arca antes que estuviera seco el suelo; y, quizá, si la puerta está cerrada, estamos dispuestos a tirar la cubierta y trepar de alguna forma; pero el tiempo de Dios para mostrar misericordia es el mejor tiempo. Como Noé recibió la orden de entrar al arca así, por tedioso que haya sido su confinamiento, él iba a esperar de nuevo una orden para salir. Nosotros debemos reconocer a Dios en todos nuestros caminos y ponerlo delante de nosotros en todos nuestros movimientos. Solamente van bajo la protección de Dios, los que siguen las instrucciones de Dios y se someten a Él.</p>
<br/>
<p class="text-justify">Vv. 20-22.Noé ahora iba a salir a un mundo desolado, donde, uno hubiera podido pensar, su primera preocupación debiera ser edificar una casa para él, pero empieza con un altar para Dios. Empieza bien quien empieza con Dios. Aunque el ganado de Noé era poco y salvado con gran cuidado y trabajo, él no se quejó para servir de ello a Dios. Servir a Dios con lo poco que tenemos es la manera de hacerlo crecer; nunca debemos pensar que es desperdicio aquello con que honramos a Dios. La primera cosa hecha en el nuevo mundo fue un acto de adoración. Ahora tenemos que expresar nuestro agradecimiento, no con holocaustos, sino con alabanza, devociones y conversaciones piadosas. Dios se sintió bien agradado con lo que se hizo. La carne quemada no puede agradar más a Dios que la sangre de toros y machos cabríos, salvo como tipo del sacrificio de Cristo y como expresión de la fe y la consagración humilde de Noé a Dios.
El diluvio eliminó la raza de hombres malos, pero no quitó el pecado de la naturaleza del hombre, que siendo concebido y nacido en pecado, piensa, imagina y ama la maldad, aun desde su juventud, y tanto antes como después del diluvio. Pero Dios por gracia declaró que nunca anegaría de nuevo al mundo. Mientras permanezca la tierra, y el hombre en ella, habrá verano e invierno. Es claro que esta tierra no va a permanecer para siempre. En breve debe ser quemada junto con todas las obras de ella; y veremos nuevos cielos y una nueva tierra, cuando todas estas cosas sean deshechas. Pero en la medida que permanecen, la providencia de Dios hará que el curso de los tiempos y de las estaciones prosiga y cada una tenga su lugar. Y basados en esta palabra, confiamos en que así sea. Vemos que se cumplen las promesas de Dios a las criaturas y podemos inferir que de la misma manera serán cumplidas sus promesas a todos los creyentes .</p>
<br/>




</div>
