<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 24</h2>
<p class="text-justify">Vv. 1-9.El efecto del buen ejemplo, la buena enseñanza y la adoración de Dios en una familia, generalmente se ve en la piedad, la fidelidad, la prudencia y el afecto de los siervos. Vivir en esas familias o tener tales siervos son, ambas cosas, bendiciones de Dios que deben ser altamente valoradas y reconocidas con gratitud. Sin embargo, no hay en la vida preocupación de mayor importancia para nosotros, el prójimo o la iglesia de Dios que el matrimonio. Por tanto, siempre debe emprenderse con mucho cuidado y prudencia especialmente en referencia a la voluntad de Dios, y con oración por su dirección y bendición. Donde no se consulta ni se considera a los buenos padres, no puede esperarse bendiciones de Dios. Al disponer de sus hijos, los padres deben consultar cuidadosamente el bienestar de sus almas, y su progreso en el camino al cielo.
Obsérvese el cometido que Abraham dio a un buen siervo, uno cuya conducta, fidelidad y afecto, para con él y su familia, conocía desde hacía mucho tiempo. Obsérvese también que Abraham recuerda que Dios lo sacó prodigiosamente de la tierra de su nacimiento, por un llamado de su gracia, y, por tanto, no duda que Él prospere su preocupación de no llevar a su hijo de regreso allá. Dios hará que eso termine en consuelo para nosotros cuando sinceramente tenemos la mira puesta en su gloria.</p>
<br/>
<p class="text-justify">Vv. 10-28.El siervo de Abraham reconocía devotamente a Dios. Nosotros estamos autorizados para encargar en detalle nuestros asuntos al cuidado de la divina providencia. Propone una señal, no porque tratara de no seguir más adelante si no era prosperado en ello; más bién es una oración para que Dios provea una buena esposa para su joven amo; y esa fue una buena oración. Ella debía ser sencilla, trabajadora, humilde, alegre, servicial y hospedadora. No importa cuál sea la moda, el sentido común y la piedad nos indican que estas son las cualidades apropiadas para una esposa y madre, pues es quien será compañera de su marido, administradora de las cosas domésticas y encargada de la formación de la mente de sus hijos. Cuando el mayordomo fue a buscar una esposa para su amo, no fue a lugares de diversión y placer pecaminoso orando para encontrar a una allí, sino que fue al pozo de agua, esperando encontrar allí a una que estuviera ocupada. Oró que agradara a Dios hacer claro y llano su camino ante él en este asunto. Nuestros tiempos están en las manos de Dios; no sólo los sucesos mismos sino sus tiempos. Debemos cuidarnos de no ser audaces en exceso insistiendo en lo que Dios debe hacer, no sea que los hechos debiliten nuestra fe en lugar de fortalecerla. Pero Dios lo escuchó y le allanó el camino. En todos los aspectos Rebeca respondía a las características que él buscaba en la mujer que iba a ser la esposa de su amo. Cuando llegó al pozo, ella se agachó, llenó su jarro y se enderezó para irse a casa. No se detuvo a mirar al forastero y sus camellos sino que se ocupó de sus asuntos y no hubiera sido apartada de ellos sino por una oportunidad de hacer el bien. No se puso a conversar con él por curiosidad o confiada, sino que le respondió con modestia. Satisfecho de que el Señor había oído su oración, regaló a la doncella unos adornos de los que se usan en los países orientales; al mismo tiempo que le preguntaba sobre su familia. Al saber que era pariente de su amo, inclinó la cabeza y adoró, bendiciendo a Dios. Sus palabras fueron dirigidas al Señor pero dichas al alcance del oído de Rebeca, que pudo darse cuenta quién era él y de dónde venía.</p>
<br/>
<p class="text-justify">Vv. 29-53.La concertación del matrimonio de Isaac y Rebeca se narra con mucho detalle. Tenemos que notar la providencia de Dios en los hechos corrientes de la vida humana y, en ellos, ejercer prudencia y otras gracias.
Labán fue a pedirle al siervo de Abraham que entrara pero no antes de ver el aro y el brazalete en manos de su hermana. Conocemos el carácter de Labán por su conducta posterior y podemos pensar que él no hubiera estado tan libre para hospedarlo si no hubiera esperado ser bien recompensado.
El siervo estaba dedicado a su tarea. Aunque terminaba un viaje y había llegado a la casa que buscaba, no comería sino hasta cumplir su diligencia. Hacer nuestro trabajo y cumplir nuestros cometidos, sean para Dios o el hombre, debe ser preferido por nosotros antes que la comida; era la comida y bebida de nuestro Salvador, Juan iv, 34. Les cuenta el encargo que su amo le dio, con la razón de ellos. Relata lo pasado en el pozo, para apoyar la proposición, mostrando sencillamente el dedo de Dios en ello. Los sucesos que nos parecen efecto de una elección, de planes o del azar, son determinados por Dios. Esto no impide, más bien estimula, el uso de todos los medios apropiados. Ellos aceptan libre y alegremente la proposición; cuando procede del Señor, todo asunto probablemente resultará fácil. El siervo de Abraham reconoce agradecido el buen éxito que ha hallado. Él era un hombre humilde y los hombres humildes no se avergüenzan de su situación en la vida, cualquiera sea. Todas nuestras preocupaciones temporales son dulces si se mezclan con la piedad.</p>
<br/>
<p class="text-justify">Vv. 54-67.El siervo de Abraham, como quien opta por su trabajo antes que por su placer, estaba presuroso por llegar a casa. Demorarse y quedarse no son propios en absoluto de un hombre sabio y bueno que es fiel a su deber.
Como los hijos no deben casarse sin el consentimiento de sus padres, así los padres no deben casarlos sin el de ellos. Rebeca consintió, no sólo en ir sino en irse de inmediato. La bondad del carácter de Rebeca muestra que nada incorrecto había en su respuesta aunque no concuerde con nuestras costumbres modernas. Podemos esperar que ella tuviera una idea tal de la religión y piedad de la familia a la que iba, que se sintió dispuesta a olvidar a su propia gente y la casa de su padre. Sus amigas la despidieron con atenciones apropiadas y con cordiales buenos deseos. Ellas bendijeron a Rebeca. Cuando nuestras relaciones entran en una situación nueva, debemos encomendarlas por medio de la oración a la bendición y gracia de Dios.
Isaac estaba bien ocupado cuando se encontró con Rebeca. Salió a aprovechar una tarde tranquila en un lugar solitario para meditar y orar, esos ejercicios divinos por los cuales conversamos con Dios y con nuestros propios corazones. Las almas santas aman el retiro; nos hará bien estar a solas con frecuencia si usamos eso en forma correcta; y nunca estamos menos solos que cuando estamos a solas.
Observe qué hijo tan afectuoso era Isaac: casi tres años habían pasado desde que murió su madre y, sin embargo, él aún no se había consolado. Vea también qué marido cariñoso fue con su esposa. Los hijos respetuosos prometen ser maridos cariñosos; el que cumple con honor su primera posición en la vida, probablemente haga lo mismo en las siguientes.</p>
<br/>




</div>
