<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 6</h2>
<p class="text-justify">Vv. 8-11.Noé no halló favor ante los ojos de los hombres; ellos lo odiaron y persiguieron porque por su vida y predicación él condenaba al mundo: pero halló gracia ante los ojos del Señor y eso lo hizo más verdaderamente honorable que los hombres de renombre. Que este sea nuestro deseo principal, esforcémonos para que podamos ser aceptados por Él. Cuando el resto del mundo era malo Noé mantuvo su integridad. La buena voluntad de Dios para con Noé produjo esta buena obra en él. Él era justo, esto es, un hombre justificado ante Dios por fe en la Simiente prometida. Como tal fue hecho santo y tuvo principios justos. Y fue justo en su conducta. No sólo fue honesto sino devoto; su afán constante era hacer la voluntad de Dios. Dios mira con favor a quienes miran sinceramente a Él con los ojos de la fe. Fácil es ser religioso cuando la religión está de moda; pero muestra fe y resolución firmes nadar contra la corriente y estar por Dios cuando nadie más está por Él; Noé lo hizo así.
Toda clase de pecados se hallaban entre los hombres. Ellos corrompieron la adoración de Dios. El pecado llena la tierra con violencia y esto justificaba plenamente la decisión de Dios de destruir el mundo. El contagio se disemina. Cuando la maldad se vuelve general, la ruina no está lejos; mientras en una nación haya un remanente de gente que ora, vaciando así la medida antes que se llene, los juicios pueden ser aplazados; pero cuando todas las manos están ocupadas en echar abajo las cercas, por el pecado, y nadie se pone en la brecha para repararla, ¿qué puede esperarse sino un diluvio de ira?</p>
<br/>
<p class="text-justify">Vv. 12-21.Dios contó a Noé su propósito de destruir el mundo malo con agua. La comunión íntima del Señor es con los que le temen, Salmo xxv, 14. Está con los creyentes capacitándolos para entender y aplicar las declaraciones y advertencias de la palabra escrita. Dios optó por hacerlo con inundación de las aguas que anegarían el mundo. Al elegir la vara con que corrige a sus hijos, Él escoge la espada con que corta a sus enemigos.
Dios estableció su pacto con Noé. Este es el primer lugar de la Biblia en que se halla la palabra “pacto”; parece significar, -1. El acuerdo de providencia; que el curso de la naturaleza continuará hasta el fin del tiempo.
2. El pacto de gracia en que Dios será el Dios de Noé, y que de su simiente Dios tomaría un pueblo para sí.
Dios dio órdenes a Noé para que hiciera un arca. Esta arca era como el casco de un navío, adecuado para flotar sobre las aguas. Era muy grande, la mitad del tamaño de la catedral de San Pablo [Londres, Inglaterra]. Y podría contener más de dieciocho de las naves más grandes usadas en nuestro tiempo. Dios hubiera podido salvar a Noé sin ponerlo a pasar trabajos, dolores ni problemas, pero lo empleó para construir lo que iba a ser el medio de preservarlo, para prueba de su fe y obediencia. La providencia y la gracia de Dios poseen y coronan al obediente y diligente. Dios dio a Noé órdenes específicas sobre cómo hacer el arca, que, por tanto, no podían sino ser perfectas para su propósito.
Dios prometió a Noé que él y su familia serían mantenidos vivos en el arca. Probablemente nosotros y nuestras familias tengamos el beneficio de lo que hacemos por obediencia a Dios. La piedad de los padres da bien a sus hijos en esta vida y los encamina más por la senda a la vida eterna, si ellos mejoran.</p>
<br/>
<p class="text-justify">Vv. 17.La cosa más notable acerca del mundo antiguo es su destrucción por el diluvio. Se nos cuenta la abundante iniquidad de ese mundo malo: la justa ira de Dios y su santa resolución de castigarlo. En todas las épocas ha habido una maldición específica de Dios para el matrimonio entre un profesante de la verdadera religión y sus enemigos declarados. El mal ejemplo del cónyuge impío corrompe o hiere mucho al otro. Se acaba la religión de la familia y los niños son educados conforme a las máximas mundanas del progenitor que no tiene temor de Dios. Si profesamos ser hijos e hijas del Señor Todopoderoso, no debemos casarnos sin su consentimiento. Él no nos dará su bendición, si preferimos la belleza, la inteligencia, la riqueza o los honores mundanales a la fe y la santidad.
El Espíritu de Dios contendió con los hombres enviando a Enoc, Noé y quizá a otros, para que les predicaran; esperaba mostrar su gracia a pesar de sus rebeliones despertando temor y convicción en sus conciencias. Pero el Señor declaró que su Espíritu no siempre contendería así con los hombres; Él los dejaría endurecerse en el pecado y madurar para la destrucción. Esto lo determinó Él porque el hombre era carne: no sólo frágil y débil, sino carnal y depravado, habiendo usado mal los poderes nobles de su alma para satisfacer sus inclinaciones corruptas.
Dios ve toda la maldad que hay entre los hijos de los hombres; no la pueden ocultar de Él ahora; y si no se arrepienten de ella, será dada a conocer por Él dentro de poco. Indudablemente la maldad de un pueblo es grande, cuando los pecadores notorios son hombres célebres entre ellos. Muchísimo pecado se cometía en todas partes por toda clase de personas. Cualquiera podía ver que la maldad del hombre era grande: pero Dios vio que toda imaginación o propósito de los pensamientos del corazón del hombre era de continuo solamente el mal. Esto era la raíz amarga, la fuente corrupta. El corazón era engañoso y perverso; los principios eran corruptos; los hábitos y las disposiciones, malas. Sus intenciones y planes eran malvados. Ellos hacían el mal deliberadamente, y se las ingeniaban para hacer perversidades. No había bien entre ellos. Dios vio la maldad del hombre como quien es herido y maltratado por ella. La vio como un padre tierno ve la necedad y porfía de un hijo rebelde y desobediente, cosa que le aflige y le hace desear no haber tenido hijos. Las palabras usadas aquí son muy notables; las usa según el entendimiento de los hombres y no significan que Dios pueda cambiar o sentirse infeliz. ¿Dios odia así nuestro pecado? Y nosotros, ¿no debiéramos afligirnos de corazón por eso? ¡Oh, que podamos mirar a Aquel a quien hemos afligido, y lamentar! -Dios se arrepintió de haber hecho al hombre; pero nunca lo encontramos arrepentido de haber redimido al hombre. Dios resuelve destruir al hombre: la palabra original es muy impactante, “raeré de sobre la faz de la tierra a los hombres”como se barre el polvo o la suciedad de un lugar que debe estar limpio y se arroja al montón de basura, el lugar apropiado para ello. Dios habla del hombre como de su propia criatura, cuando resuelve su castigo. Pierden su vida los que no responden al propósito de sus vidas. Dios tomó esta decisión sobre los hombres después que su Espíritu había contendido por mucho tiempo con ellos pero en vano. Nadie es castigado por la justicia de Dios sino aquellos que detestan ser reformados por la gracia de Dios.</p>
<br/>
<p class="text-justify">V. 22.La fe de Noé triunfó sobre todos los razonamientos corruptos. Armar un edificio tan grande, como nunca antes había visto, y proporcionar comida para las criaturas vivas, iba a requerir de él mucha dedicación, trabajo y gastos. Sus vecinos se iban a reír de él. Pero todas esas objeciones superó Noé por la fe; su obediencia era pronta y resuelta. Habiendo empezado a construir, no lo dejó hasta que hubo terminado: así hizo él y así debemos hacerlo nosotros.
Tuvo temor del diluvio y, por tanto, preparó el arca. En la advertencia dada a Noé hay una advertencia aún más solemne dada a nosotros: huir de la ira venidera que raerá el mundo de los incrédulos arrojándolos al abismo de la destrucción. Cristo, el verdadero Noé, que nos consolará personalmente, ya preparó el arca por sus sufrimientos y bondadosamente nos invita a entrar por fe. Mientras dure el día de su paciencia, oigamos y obedezcamos su voz.</p>
<br/>




</div>
