<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Habacuc 3</h2>
<p class="text-justify">Vv. 1, 2.Parece que aquí se usa la palabra oración en el sentido de acto de devoción. El Señor avivará obra entre la gente en medio de los años de la adversidad. Esto puede aplicarse a cada temporada en que la Iglesia o los creyentes, sufren aflicciones y pruebas. La misericordia es a lo que debemos huir en busca de refugio, y confiar en ella como nuestro único argumento. No debemos decir: Recuerda nuestro mérito, sino Señor, acuérdate de la misericordia.</p>
<br/>
<p class="text-justify">Vv. 3-15.Cuando el pueblo de Dios está angustiado y a punto de desesperar, busca ayuda considerando los días antiguos y los años de los tiempos antiguos, presentándolos en oración como argumento a Dios. El parecido de los cautiverios egipcio y babilónico se presenta naturalmente a la mente, así como la posibilidad de una liberación semejante por medio del poder de Jehová.
Dios se manifestó en su gloria. Todos los poderes de la naturaleza son remecidos, y el curso de la naturaleza es cambiado, pero todo es para la salvación del pueblo de Dios. Hasta lo que parezca menos probable obrará para la salvación de ellos. Aquí se da un tipo y figura de la redención del mundo por Jesucristo. Es para la salvación con tu ungido. Josué, que dirigió los ejércitos de Israel, era una figura de Aquel cuyo nombre llevaba, Jesús, nuestro Josué. En todas las salvaciones obradas para ellos, Dios miraba a Cristo, el Ungido, y traía liberaciones que pasaran por Él. Todas las maravillas hechas por el Israel de antes, fueron nada para lo que se hizo cuando el Hijo de Dios sufrió la cruz por los pecados de su pueblo. ¡Cuán gloriosa su resurrección y ascensión! ¡Cuánto más gloriosa será su segunda venida a poner fin a todo lo que se opone a Él, y a todo lo que hace sufrir a su pueblo!</p>
<br/>
<p class="text-justify">Vv. 16-19.Cuando vemos que se acerca un tiempo difícil, nos corresponde prepararnos. Una buena esperanza a través de la gracia se fundamenta en el santo temor.
El profeta mira a las experiencias de la Iglesia de épocas anteriores y observa qué cosas tan grandes había hecho Dios por ellos, y así no sólo se recuperó, sino fue lleno de santo gozo. Resolvió deleitarse y triunfar en el Señor; porque cuando todo se va, su Dios no se va.
Destruid las vides y las higueras y haréis que cese todo el gozo carnal. Pero los que disfrutaban a Dios en todos cuando estaban llenos, ahora vacíos y pobres, pueden disfrutar todo en Dios . Pueden sentarse sobre la pila de ruinas de sus consuelos humanos, y aun entonces alabar al Señor, como el Dios de su salvación, la salvación del alma, y regocijarse en Él como tal, en sus angustias más grandes. El gozo en el Señor es especialmente oportuno cuando nos topamos con pérdidas y cruces en el mundo. Aunque estén cortadas las provisiones, para demostrar que el hombre no vive solamente de pan, podemos ser abastecidos por la gracia y la consolación del Espíritu de Dios. Entonces seremos fuertes para la obra y la guerra espiritual, y con el corazón ensanchado podemos correr por el camino de sus mandamientos, y superar nuestros problemas. Y seremos exitosos en las empresas espirituales.
Así, el profeta que empezó su oración con temor y temblor, la termina con gozo y triunfo. Y así la fe en Cristo prepara para todo acontecimiento. El nombre de Jesús, cuando podemos hablar de él como nuestro, es bálsamo para toda herida, un cordial para toda preocupación. Es un ungüento derramado, que difunde fragancia a través de toda el alma. Con la esperanza de una corona celestial, soltemos todas las posesiones y comodidades terrenales, y soportemos alegremente cuando estemos debajo de las cruces. Aún un poquito y el que ha de venir vendrá y no tardará; donde Él esté, nosotros también estaremos.</p>
<br/>




</div>
