<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Habacuc 2</h2>
<p class="text-justify">Vv. 1-4.Debemos estar en guardia contra las tentaciones de ser impacientes cuando estamos inquietos y confundidos con dudas sobre los métodos de la providencia. Cuando hemos derramado quejas y peticiones ante Dios, debemos observar las respuestas que Dios da por su palabra, su Espíritu, y providencia, lo que el Señor dirá a nuestro caso. Dios no desilusionará las expectativas de fe de los que esperan oír lo que Él les dirá. Todos son aludidos en las verdades de la palabra de Dios.
Aunque el favor prometido sea largamente postergado, al final llegará y nos recompensará abundantemente por esperar. El pecador humilde, de corazón quebrantado y arrepentido, solo busca obtener un interés en esta salvación. Descansará su alma en la promesa y en Cristo, en quien y por medio del cual le es dada. Así, pues, anda, trabaja, y vive por fe, persevera hasta el fin y es exaltado a la gloria; en cambio, los que desconfían de, o desprecian la absoluta suficiencia de Dios, no andarán rectamente con Él. El justo vivirá por la fe en estas preciosas promesas mientras se difiera su cumplimiento. Sólo los que son hechos justos por la fe, vivirán, serán felices aquí y para siempre.</p>
<br/>
<p class="text-justify">Vv. 5-14.El profeta lee la condena de todas las potestades orgullosas y opresivas que maltratan al pueblo de Dios. la concupiscencia de la carne, la concupiscencia de los ojos y la soberbia de la vida son los lazos que enredan a los hombres; encontramos al que llevó cautivo a Israel, cautivo por cada una de ellas.
No debe contar como nuestro, más de lo que tenemos, de lo que obtenemos honestamente. Las riquezas no son sino barro, fango espeso; ¿qué son el oro y la plata, sino tierra amarilla y blanca? Los que pasan por el barro espeso son obstaculizados y ensuciados en su jornada; así son quienes pasan por el mundo en medio de la abundancia de riqueza. Qué necios los que se cargan con el cuidado continuo de ello; con muchísima culpa por conseguirla, ahorrarla y gastarla, ¡y con una pesada cuenta que deben rendir otro día! Se sobrecargan con este barro espeso y, así, se hunden en la destrucción y la perdición. Véase cuál será el final de esto; lo que se consigue del prójimo por la violencia, será quitado con violencia por otros.
La codicia ocasiona inquietud e incomodidad a la familia; el que ambiciona ganancia perturba su propia casa; lo que es peor, se acarrea la maldición de Dios para todos los asuntos de ella. Hay ganancia lícita que, por la bendición de Dios puede ser consuelo para una casa, pero lo que se obtiene por fraude e injusticia, traerá pobreza y ruina a una familia. Pero eso no es lo peor: Tú has pecado contra tu propia alma, la has puesto en peligro. Los que hacen mal a sus vecinos hacen un daño mucho más grande a sus propias almas. Si el pecador piensa que ha manejado con arte e ingenio sus engaños y su violencia, las riquezas y posesiones que haya amontonado, darán testimonio en su contra. No hay esclavos más grandes en el mundo que los que son esclavos de las puras empresas mundanas. ¿Y qué resulta de eso? Se hallan desilusionados de eso y desilusionados en eso; reconocerán que es peor que la vanidad, es aflicción de espíritu. Dios manifiesta y magnifica su gloria manchando y hundiendo la gloria terrenal, y llena la tierra con el conocimiento de ella, tan abundantemente como las aguas cubren el mar, que son profundas y se esparcen lejos y ampliamente.</p>
<br/>
<p class="text-justify">Vv. 15-20.Se pronuncia un ay severo contra la ebriedad; muy temible es para todos los que son culpables de ebriedad en cualquier momento y en cualquier parte, desde el palacio majestuoso a la taberna despreciable. Caridad es dar un trago al que está necesitado, al que tiene sed y es pobre, o al viajero agotado o al que está listo para perecer; pero es maldad dar un trago al vecino, que puede dejarlo desnudo, descubrir preocupaciones secretas o arrastrarlo a un mal negocio, o para cualquiera de tales propósitos. Ser culpable de este pecado, complacerse en esto, es hacer lo que podemos para asesinar el alma y el cuerpo. Hay un ay para él, y castigo que responde al pecado.
La necedad de adorar ídolos es dejada al descubierto. El Señor está en su santo templo del cielo, donde tenemos acceso a Él en la manera que ha designado. Que demos la bienvenida a su salvación y que le adoremos en sus templos terrenales por medio de Cristo Jesús, y por la influencia del Espíritu Santo.</p>
<br/>




</div>
