<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hageo 2</h2>
<p class="text-justify">Vv. 1-9.Los que ponen su corazón al servicio del Señor recibirán aliento para proceder. Pero entonces no pudieron edificar un templo como el que edificó Salomón. Aunque nuestro gracioso Dios se complace si hacemos lo mejor que podemos a su servicio, nuestros corazones orgullosos, no obstante, no nos dejarán complacernos a menos que hagamos tan bien como otros, cuyas habilidades superan con mucho a las nuestras.-Se da aliento a los judíos para que, sin embargo, sigan en la obra. Tienen a Dios consigo, su Espíritu y su presencia especial. Aunque castiga transgresiones, su fidelidad no falla. El Espíritu aún permanecía entre ellos. Tendrán al Mesías entre ellos dentro de poco tiempo más: “El que vendrá”.
Las convulsiones y los cambios tendrán lugar en la iglesia judía y el estado judío, pero primero debe haber grandes revoluciones y conmociones entre las naciones. -Él vendrá como el Deseado de todas las naciones; deseable para todas las naciones, porque en Él será bendecida toda la tierra con la mejor de las bendiciones; largamente esperado y deseado por todos los creyentes. La casa que estaban construyendo deberá llenarse de una gloria mucho mayor que la del templo de Salomón. Esta casa será llena con gloria de otra naturaleza. Si tenemos plata y oro, debemos servir y honrar a Dios con eso, pues le pertenece. Si no tenemos plata ni oro debemos honrarlo con lo que tengamos, y Él nos aceptará.
Que se consuelen ellos con que la gloria de esta casa será mucho mayor que la de la anterior, en lo que será más que todas las glorias de la primera casa, la presencia del Mesías, el Hijo de Dios, el Señor de gloria, personalmente, y en naturaleza humana. Nada sino la presencia del Hijo de Dios, en forma y naturaleza humana, podría cumplir esto. Jesús es el Cristo, Él es el que debe venir y no tenemos que esperar a nadie más. Esta sola profecía basta para acallar a los judíos y condenar su obstinado rechazo de Aquel de quien hablaron todos los profetas. Si Dios está con nosotros, la paz está con nosotros. Pero los judíos del último templo tuvieron muchos problemas; pero esta promesa se cumple en esa paz espiritual que Jesucristo ha adquirido por su sangre para todos los creyentes. Todos los cambios harán camino para que Cristo sea deseado y valorado por todas las naciones. Y los judíos tendrán abiertos sus ojos para contemplar cuán precioso es Él, al cual hasta ahora habían rechazado.</p>
<br/>
<p class="text-justify">Vv. 10-19.Muchos echaron a perder esta buena obra yendo a ella con corazones y manos impías, y probablemente no sacaron ventaja de ello. El resumen de estas dos reglas de la ley es que se aprende más fácilmente de los demás el pecado que la santidad. La impureza de sus corazones y vidas hará inmunda a la obra de sus manos y todas sus ofrendas ante Dios. El caso es el mismo nuestro. Cuando estamos empleados en alguna buena obra debemos vigilarnos, no sea que la hagamos inmunda con nuestras corrupciones.
Cuando empezamos a tomar conciencia del deber para con Dios, podemos esperar su bendición y el que es sabio, que entienda la paciencia del Señor. Dios maldecirá las bendiciones del impío y amargará la prosperidad del negligente; pero endulzará la copa de aflicción para quienes le sirven diligentemente.</p>
<br/>
<p class="text-justify">Vv. 20-23.El Señor preservará a Zorobabel y al pueblo de Judá en medio de sus enemigos. Aquí también se anuncia el establecimiento y la continuidad del reino de Cristo; por la unión con que su pueblo es sellado con el Espíritu Santo, sellado con su imagen y, así, es distinguido de todos los demás.
Aquí también se predicen los cambios, aun en ese tiempo, cuando el reino de Cristo desplace y ocupe el lugar de todos los imperios que se opusieron a su causa. La promesa se refiere especialmente a Cristo, que descendió de Zorobabel en línea directa, y que es el solo edificador del templo del evangelio. Nuestro Señor Jesús es el Sello en la diestra de Dios, porque toda potestad le es dada a Él, y derivada de Él. Por Él y en Él todas las promesas de Dios son sí y amén. Cualesquiera sean los cambios que acontezcan en la tierra, todos promoverán el consuelo, el honor y la felicidad de sus siervos.</p>
<br/>




</div>
