<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hageo 1</h2>
<p class="text-justify">Vv. 1-11.Obsérvese el pecado de los judíos después de regresar del cautiverio en Babilonia. Los empleados por Dios pueden ser sacados de su obra por una tormenta, pero deben retornar a ella. No dijeron que no construirían un templo sino, no todavía. Así, pues, los hombres no dicen que nunca se arrepentirán ni se reformarán, ni serán religiosos sino, no todavía. Así queda sin hacer el gran negocio para hacer el cual fuimos mandados al mundo. Hay en nosotros la tendencia a pensar mal de los desalientos en nuestro deber como si fueran una exoneración de nuestro deber cuando son sólo para probar nuestro coraje y fe. Descuidaron la edificación de la casa de Dios para tener más tiempo y dinero para las cosas mundanas.
Para que el castigo corresponda al pecado, la pobreza que pensaron evitar no edificando el templo, Dios la trajo por no edificarlo. Se han pensado muchas buenas obras, pero no se han hecho porque los hombres supusieron que no había sido el tiempo apropiado. Así, pues, los creyentes dejan pasar las oportunidades de ser útiles, y los pecadores demoran los beneficios para sus almas hasta que es demasiado tarde.
Si trabajamos sólo para la comida que perece, como aquí los judíos, corremos el riesgo de perder nuestro esfuerzo, pero estamos seguros que no será en vano en el Señor, si trabajamos por la comida que a vida eterna permanece. Si deseamos tener el consuelo y la continuidad de los goces temporales, debemos tener a Dios como Amigo nuestro. Véase también Lucas xii. 33.
Cuando Dios cruza nuestros asuntos temporales y nos topamos con problemas y desilusiones, encontramos que la causa es que la obra que tenemos que hacer para Dios y por nuestras almas, se deja sin hacer y buscamos nuestras cosas más que las cosas de Cristo. ¡Cuántos que dicen que no se pueden dar el lujo de dar para obras de piedad o caridad, suelen dar diez veces más para gastos innecesarios en sus casas y en sí mismos! Ajenos a sus propios intereses son los que se preocupan mucho por adornar y enriquecer sus casas, mientras el templo de Dios en sus corazones está desperdiciado.
El gran interés de cada uno es aplicarse al deber necesario de examinarse a sí mismo y tener comunión con nuestros propios corazones acerca de nuestro estado espiritual. El pecado es por lo que debemos responder; el deber es lo que debemos hacer. Pero muchos de los rápidos para mirar los caminos ajenos, son negligentes con el propio. Si se ha descuidado un deber no hay razón para seguir descuidándolo. Cualquiera sea la cosa en que Dios se complazca cuando está hecha, nosotros debemos complacernos en hacerla. Que los que postergaron su regreso a Dios, retornen con todo su corazón mientras haya tiempo.</p>
<br/>
<p class="text-justify">Vv. 12-15.El pueblo regresó a Dios por el camino del deber. Al asistir a los ministros de Dios debemos respetar a Aquel que los envió. La palabra del Señor tiene éxito cuando, por su gracia, Él despierta nuestros espíritus para cumplirla. Es en el día del poder divino que somos hechos voluntarios. Cuando Dios tiene obra que hacer, encontrará a los hombres o los hará aptos para ella. Cada uno ayudó como era su habilidad; y esto hicieron con respeto al Señor su Dios.-Los que han perdido tiempo, tienen que redimirlo; y mientras más tiempo hemos saqueado con necedad, más apresurados debemos estar. Dios los encontró en el camino de la misericordia. Los que trabajan para Él, lo tienen a Él consigo; y si Él está por nosotros, ¿quién puede estar contra nosotros? Esto debiera alentarnos a ser diligentes.</p>
<br/>




</div>
