<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hebreos 2</h2>
<p class="text-justify">Vv. 1-4.Habiendo demostrado que Cristo es superior a los ángeles, se aplica la doctrina. La mente y la memoria son como vasos quebrados que no retienen lo que en ellos se vierte, si no se pone mucho cuidado. Esto procede de la corrupción de nuestra naturaleza, las tentaciones, los afanes y los placeres del mundo. Pecar contra el evangelio es rechazar esta salvación grandiosa; es despreciar la gracia salvadora de Dios en Cristo, tomándola con liviandad, sin interesarse por ella ni considerar el valor de la gracia del evangelio o su necesidad, ni a nuestro estado de condenación sin ella.
Los juicios del Señor durante la dispensación del evangelio son principalmente espirituales, pero tienen que temerse más por eso. Aquí se apela a la conciencia de los pecadores. Ni siquiera su descuido parcial escapará de las reprimendas; porque suelen traer oscuridad a las almas que no destruyen definitivamente.
La proclamación del evangelio fue continuada y confirmada por los que oyeron a Cristo, por los evangelistas y apóstoles que fueron testigos de lo que Jesucristo empezó a hacer y a enseñar; por los dones del Espíritu Santo fueron equipados para la obra a la cual fueron llamados. Todo esto fue conforme a la voluntad de Dios. Era la voluntad de Dios que nosotros tuviéramos una base firme para nuestra fe y un fuerte cimiento para nuestra esperanza al recibir el evangelio. Preocupémonos de esta sola cosa necesaria, y escuchemos las Sagradas Escrituras, escritas por los que oyeron las palabras de nuestro Señor de gracia y que fueron inspiradas por su Espíritu; entonces, seremos bendecidos con la buena parte que no puede ser quitada.</p>
<br/>
<p class="text-justify">Vv. 5-9.En el estado presente de la Iglesia, ni en su estado más plenamente restaurado cuando los reinos de la tierra sean el reino de Cristo, cuando el príncipe de este mundo sea expulsado, está gobernada por los ángeles; Él asumirá su gran poder y reinará. ¿Cuál es la causa activa de toda la bondad que Dios muestra a los hombres al darles a Cristo a ellos y por ellos? Es la gracia de Dios. Como recompensa por la humillación de Cristo al sufrir la muerte, Él tiene un dominio ilimitado sobre todas las cosas; así se cumplió en Él esta antigua Escritura. De manera que, Dios ha hecho en la creación y en la providencia cosas maravillosas por nosotros, las cuales hemos devuelto con suma vileza.</p>
<br/>
<p class="text-justify">Vv. 10-13.No importa lo que pudiera imaginar u objetar el soberbio, carnal e incrédulo, la mente espiritual verá la gloria peculiar de la cruz de Cristo y se satisfará con que fue Él, quien en todas las cosas despliega sus perfecciones al llevar a tantos hijos a la gloria, quien hizo perfecto al Autor por medio de sus sufrimientos. Su camino a la corona pasó por la cruz y así debe ser con su pueblo. Cristo santifica; Él adquirió y envió al Espíritu santificador; el Espíritu santifica como el Espíritu de Cristo. Los creyentes verdaderos son santificados, dotados con principios y poderes santos, puestos aparte para usos y propósitos elevados y santos.
Cristo y los creyentes son todos de un solo Padre celestial, que es Dios. Son llevados a una relación de parentesco con Cristo. Pero las palabras, que no se avergüenzan de llamarlos hermanos, expresan la elevada superioridad de Cristo respecto de la naturaleza humana.
Esto se muestra en tres pasajes de la Escritura: Salmo xxii, 22; xviii, 2; Isaías viii, 18.</p>
<br/>
<p class="text-justify">Vv. 14-18.Los ángeles cayeron y quedaron sin esperanza ni socorro. Cristo nunca concibió ser el Salvador de los ángeles caídos, por tanto, no asumió la naturaleza de ellos; la naturaleza de los ángeles no podía ser sacrificio expiatorio por el pecado del hombre. Aquí hay un precio pagado, suficiente para todos, y apto para todos, porque fue en nuestra naturaleza. Aquí se demuestra el amor maravilloso de Dios, porque cuando Cristo supo lo que debía sufrir en nuestra naturaleza y cómo debía morir en ella, la asumió prestamente. La expiación dio lugar a la liberación de su pueblo de la esclavitud de Satanás, y al perdón de sus pecados por la fe. Los que temen la muerte y se esfuerzan por sacar lo mejor de sus terrores, no sigan intentando superarlos o ahogarlos, que no sigan siendo negligentes o se hagan malos por la desesperación. No esperen ayuda del mundo ni de los artificios humanos, pero busquen el perdón, la paz, la gracia y la esperanza viva del cielo por fe en el que murió y resucitó, para que así puedan superar el temor a la muerte.
El recuerdo de sus tristezas y tentaciones hace que Cristo se interese por las pruebas de su pueblo y esté listo para ayudarles. Él está pronto y dispuestos a socorrer a quienes son tentados y le buscan. Se hizo hombre, y fue tentado, para que fuera apto en toda forma para socorrer a su pueblo, habiendo pasado Él por las mismas tentaciones, pero siguiendo perfectamente libre de pecado. Entonces, que el afligido y el tentado no desesperen ni den lugar a Satanás, como si las tentaciones hicieran que fuese malo acudir en oración al Señor. Ningún alma pereció jamás siendo tentada, si desde su verdadera alarma por el peligro, clamó al Señor con fe y esperanza de alivio. Este es nuestro deber en cuanto somos sorprendidos por las tentaciones y queremos detener su avance, lo que es nuestra sabiduría.</p>
<br/>




</div>
