<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hebreos 13</h2>
<p class="text-justify">Vv. 1-6.El designio de Cristo al darse por nosotros, es adquirir un pueblo peculiar, celoso de buenas obras; la religión verdadera es el lazo de amistad más firme. Estas son algunas serias exhortaciones a diversos deberes cristianos, especialmente el contentamiento. El pecado opuesto a esta gracia y deber es la codicia, un deseo excesivamente apasionado de la riqueza de este mundo, unido a la envidia hacia los que tienen más que nosotros. Teniendo tesoros en el cielo podemos estar contentos con las pocas cosas de aquí. Los que no pueden estar así, no estarán contentos aunque Dios mejore su situación. Adán estaba en el paraíso, pero no estaba contento; algunos ángeles no estaban contentos en el cielo, pero el apóstol Pablo, aunque humillado y vacío, había aprendido a estar contento en todo estado, en cualquier estado. Los cristianos tienen razón para estar contentos con su suerte actual. Esta promesa contiene la suma y la sustancia de todas las promesas: “No te desampararé ni te dejaré”. En el lenguaje original hay no menos de cinco negativas juntas para confirmar la promesa: el creyente verdadero tendrá la presencia bondadosa de Dios consigo en la vida, en la muerte, y por siempre. Los hombres no pueden hacer nada contra Dios, y Dios puede hacer que resulte para bien todo lo que los hombres hacen contra su pueblo.</p>
<br/>
<p class="text-justify">Vv. 7-15.Las instrucciones y el ejemplo de los ministros que terminaron sus testimonios en forma honorable y consoladora, deben ser recordadas en particular por los que les sobreviven. Aunque algunos de sus ministros estaban muertos, otros moribundos, aun así la gran Cabeza, y Sumo Sacerdote de la Iglesia, el Obispo de sus almas, vive siempre y siempre es el mismo. Cristo es el mismo de la época del Antiguo Testamento y del evangelio, y siempre será así para su pueblo: igualmente misericordioso, poderoso y absolutamente suficiente. Él aún llena al hambriento, alienta al tembloroso y da la bienvenida a los pecadores arrepentidos; aún rechaza al soberbio y al de la justicia propia, aborrece la pura confesión y enseña a todos los que salva, a amar la justicia y a odiar la iniquidad.
Los creyentes deben procurar que sus corazones estén establecidos por el Espíritu Santo en una dependencia simple de la libre gracia, que consolará sus corazones y los hará resistentes al engaño.
Cristo es nuestro Altar y nuestro Sacrificio; Él santifica el don. La cena del Señor es la fiesta de la pascua del evangelio.
Habiendo mostrado que mantener la ley levítica conforme a sus propias reglas, impediría que los hombres fueran al altar de Cristo, el apóstol agrega: Salgamos, pues, a Él, fuera del campamento, fuera de la ley ceremonial, del pecado, del mundo y de nosotros mismos. Viviendo por fe en Cristo, apartados para Dios por medio de su sangre, separémonos voluntariamente de este mundo malo. El pecado, los pecadores, la muerte no dejarán que continuemos aquí por mucho tiempo más; por tanto, salgamos ahora por fe y busquemos en Cristo el reposo y la paz que este mundo no nos puede proporcionar. Llevemos nuestros sacrificios a este altar y a este nuestro Sumo Sacerdote, y ofrezcámoslo por su intermedio. Siempre debemos ofrecer el sacrificio de alabanza a Dios. En estos se cuentan la alabanza, la oración y la acción de gracias.</p>
<br/>
<p class="text-justify">Vv. 16-21.Conforme a lo que podamos, tenemos que dar para las necesidades de las almas y de los cuerpos de los hombres: Dios aceptará estas ofrendas con agrado, y aceptará y bendecirá a los que ofrendan por medio de Cristo.
El apóstol expresa en seguida cual es el deber de ellos para con los ministros vivos: obedecerles y someterse a ellos en la medida que sea conforme a la idea y voluntad de Dios dadas a conocer en su palabra. Los cristianos no deben pensar que saben demasiado, que son demasiado buenos o demasiado grandes para aprender. El pueblo debe escudriñar las Escrituras, y en la medida que los ministros enseñen conforme a esa regla, deben recibir sus instrucciones como palabra de Dios que obra en los que creen. Interesa a los oyentes que la cuenta que sus ministros den de sí mismos sea con gozo y no con tristeza. Los ministros fieles entregarán sus propias almas, porque la ruina de un pueblo infiel y estéril recaerá sobre sus propias cabezas.
Mientras el pueblo ore con más fervor por sus ministros, más beneficio pueden esperar de su ministerio. La buena conciencia respeta todos los mandamientos de Dios y todo nuestro deber. Los que tienen esta buena conciencia necesitan, sin embargo, las oraciones de los demás. Cuando los ministros van a un pueblo que ora por ellos, van con mayor satisfacción para sí y éxito para el pueblo. Debemos procurar con oración todas nuestras misericordias.
Dios es el Dios de paz, completamente reconciliado a los creyentes; Él ha abierto camino a la paz y la reconciliación de sí con los pecadores, y que ama la paz en la tierra, especialmente en sus iglesias. Él es el Autor de la paz espiritual en los corazones y las conciencias de su pueblo. -¡Qué pacto más firme es aquel que tiene su fundamento en la sangre del Hijo de Dios! El perfeccionamiento de los santos en toda buena obra es la gran cosa deseada por y para ellos; y que ellos puedan ser, en el largo plazo, equipados para el empleo y la dicha del cielo. No hay cosa buena obrada en nosotros que no sea la obra de Dios. Nada bueno obra Dios en nosotros sino por medio de Cristo por amor a Él y a su Espíritu.</p>
<br/>
<p class="text-justify">Vv. 22-25.Tan malos son los hombres, aun los creyentes, por los restos de su corrupción, que necesitan que se les estimule y se les exhorte a oír cuando se les entrega la doctrina más importante y consoladora, para su propio bien, y con las pruebas más convincentes, para que la reciban y no se descaminen con ella, la descuiden o la rechacen.
Bueno es que la ley del amor santo y la bondad sea escrita en los corazones de los cristianos, los unos a los otros. La religión enseña el civismo verdadero y la buena crianza a los hombres. No es de temperamento malo ni descortés. Que el favor de Dios esté con vosotros y que su gracia obre continuamente en vosotros y con vosotros, dando los frutos de la santidad como las primicias de la gloria.</p>
<br/>




</div>
