<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hebreos 10</h2>
<p class="text-justify">Vv. 1-10.Habiendo mostrado que el tabernáculo y las ordenanzas del pacto del Sinaí eran solamente emblemas y tipos del evangelio, el apóstol concluye que los sacrificios que los sumos sacerdotes ofrecían continuamente no podían perfeccionar a los adoradores en cuanto al perdón y la purificación de sus conciencias, pero cuando “Dios manifestado en carne”se hizo sacrificio, y el rescate fue su muerte en el madero maldito, entonces, por ser de infinito valor el que sufrió, sus sufrimientos voluntarios fueron de infinito valor. El sacrificio expiatorio debe ser capaz de consentimiento, y debe ponerse por propia voluntad en el lugar del pecador: Cristo hizo así. La fuente de todo eso que Cristo ha hecho por su pueblo es la soberana voluntad y gracia de Dios. La justicia introducida y el sacrificio ofrendado una sola vez por Cristo son de poder eterno, y su salvación nunca será quitada. Son de poder para hacer perfectos a todos los que vengan a Él; ellos sacan de la sangre expiatoria la fuerza y los motivos para obedecer y para el consuelo interior.</p>
<br/>
<p class="text-justify">Vv. 11-18.Bajo el nuevo pacto o la dispensación del evangelio, se tiene perdón pleno y definitivo. Esto significa una enorme diferencia del pacto nuevo respecto del antiguo. En el antiguo debían repetirse a menudo los sacrificios, y después de todo, se obtenía por ellos perdón sólo en este mundo. Bajo el nuevo , basta con un solo Sacrificio para procurar el perdón espiritual de todas las naciones y todas las eras, o para ser librado del castigo en el mundo venidero. Bien se puede llamar pacto nuevo a este. Que nadie suponga que las invenciones humanas pueden valer de algo para quienes los pongan en lugar del sacrificio del Hijo de Dios. ¿Qué queda entonces sino que busquemos un interés por fe en este Sacrificio; y el sello de ello en nuestras almas por la santificación del Espíritu para obediencia? Así que, como la ley está escrita en nuestros corazones, podemos saber que somos justificados, y que Dios no recordará más nuestros pecados.
* * * * * * *</p>
<br/>
<p class="text-justify">Vv. 19-25.Habiendo terminado la primera parte de la epístola, el apóstol aplica la doctrina a propósitos prácticos. Como los creyentes tenían el camino abierto a la presencia de Dios, entonces les convenía usar este privilegio. El camino y los medios por los cuales los cristianos disfrutan de estos privilegios pasa por la sangre de Jesús, por el mérito de esa sangre que Él ofrendó como sacrificio expiatorio. El acuerdo de la santidad infinita con la misericordia que perdona, no se entendió claramente hasta que la naturaleza humana de Cristo, el Hijo de Dios, fue herida y molida por nuestros pecados. Nuestro camino al cielo pasa por el Salvador crucificado; su muerte es para nosotros el camino de vida y para los que creen esto, Él es precioso. Deben acercarse a Dios; sería despreciar a Cristo seguir de lejos.
Sus cuerpos tenían que ser lavados con agua pura, aludiendo a los lavamientos ordenados por la ley: de esta manaera, el uso del agua en el bautismo era para recordar a los cristianos que sus conductas deben ser puras y santas. Como ellos derivan consuelo y gracia de su Padre reconciliado a sus propias almas, adornan la doctrina de Dios su Salvador en todas las cosas.
Los creyentes tienen que considerar cómo pueden servirse los unos a los otros, especialmente estimulándose unos a otros al ejercicio más vigoroso y abundante del amor, y a la práctica de las buenas obras. La comunión de los santos es una gran ayuda y privilegio, y un medio de constancia y perseverancia. Debemos observar la llegada de tiempos de prueba, y por ellos ser despertados a una mayor diligencia. Hay un día de prueba que viene para todos los hombres: el día de nuestra muerte.</p>
<br/>
<p class="text-justify">Vv. 26-31. Las exhortaciones contra la apostasía y a favor de la perseverancia son enfatizadas por muchas razones de peso. El pecado aquí mencionado es la falla total y definitiva en que los hombres desprecian y rechazan, con voluntad y resolución total y firme, a Cristo el único Salvador; desprecian y resisten al Espíritu, el único Santificador; y desprecian y renuncian al evangelio, el único camino a la salvación, y las palabras de vida eterna. De esta destrucción Dios da, todavía en la tierra, un aviso previo temible a las conciencias de algunos pecadores, que pierden la esperanza de ser capaces de soportarla o de escaparse de ella. Pero ¿qué castigo puede ser más doloroso que morir sin misericordia? Respondemos, morir por misericordia, por la misericordia y la gracia que ellos despreciaron. ¡Qué temible es el caso cuando no sólo la justicia de Dios, sino su gracia y misericordia, abusadas, claman venganza! Todo esto no significa en lo más mínimo que queden excluidas de la misericordia las almas que se lamentan por el pecado, o que se les niegue el beneficio del sacrificio de Cristo a alguien dispuesto a aceptar estas bendiciones. Cristo no echará fuera al que acuda a Él.</p>
<br/>
<p class="text-justify">Vv. 32-39.Muchas y variadas aflicciones se conjugaron contra los primeros cristianos y ellos tuvieron gran conflicto. El espíritu cristiano no es un espíritu egoísta; nos lleva a compadecer al prójimo, a visitarles, ayudarles y rogar por ellos.
Aquí todas las cosas no son sino sombras. La felicidad de los santos durará para siempre en el cielo; los enemigos nunca pueden quitarla, como los bienes terrenales. Esto hará rica restauración por todo lo que perdimos y sufrimos aquí. La parte más grande de la dicha de los santos está todavía en la promesa. Es una prueba de la paciencia de los cristianos tener que contentarse con vivir después que su obra esté hecha, y seguir en pos de su recompensa hasta que llegue el tiempo de Dios para darla. Pronto Él vendrá a ellos, en la muerte, para terminar todos sus sufrimientos y darles la corona de vida. El actual conflicto del cristiano puede ser agudo, pero pronto terminará. Dios nunca se complace con la profesión formal y los deberes y servicios externos de los que no perseveran, sino que los contempla con mucho desagrado. Los que han sido mantenidos fieles en las grandes pruebas del tiempo pasado, tienen razón para esperar que la misma gracia les ayude aún a vivir por fe hasta que reciban el objetivo de su fe y paciencia, la salvación misma de sus almas. Viviendo por fe y muriendo por fe nuestras almas están a salvo para siempre.</p>
<br/>




</div>
