<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hebreos 1</h2>
<p class="text-justify">Vv. 1-3.Dios habló a su pueblo antiguo en diversos tiempos, en generaciones sucesivas y de maneras diversas, como le pareció apropiado; a veces, por instrucciones personales, a veces por sueños, a veces por visiones, a veces por influencia divina en la mente de los profetas. La revelación del evangelio supera a la anterior en excelencia por ser una revelación que Dios ha hecho por medio de su Hijo. Al contemplar el poder, la sabiduría y la bondad del Señor Jesucristo, contemplamos el poder, la sabiduría y la bondad del Padre, Juan xiv, 7; la plenitud de la Deidad habita no sólo como en un tipo o en una figura, sino realmente en Él. Cuando, en la caída del hombre, el mundo fue despedazado bajo la ira y la maldición de Dios, el Hijo de Dios emprendió la obra de la redención, sustentándolas por su poder y bondad todopoderosa.
De la gloria de la persona y el oficio de Cristo, pasamos a la gloria de su gracia. La gloria y naturaleza de su Persona, dio a sus sufrimientos tal mérito que eran satisfacción plena para la honra de Dios, que sufrió un daño y afrenta infinitas por los pecados de los hombres. Nunca podremos estar suficientemente agradecidos que Dios nos haya hablado de la salvación en tantas formas y con claridad creciente, a nosotros, pecadores caídos. Que Él mismo nos haya limpiado de nuestros pecados es un prodigio de amor superior a nuestra capacidad de admiración, gratitud y alabanza.</p>
<br/>
<p class="text-justify">Vv. 4-14.Muchos judíos tenían un respeto supersticioso o idólatra por los ángeles, porque habían recibido la ley y otras noticias de la voluntad divina por su ministración. Los consideraban como mediadores entre Dios y los hombres, y algunos llegaron tan lejos como para darles una especie de homenaje religioso o adoración. De manera que, era necesario no sólo que el apóstol insistiera en que Cristo es el Creador de todas las cosas, y por tanto, crerador de los mismos ángeles, sino en que era el Mesías en naturaleza humana resucitado y exaltado, a quien están sujetos los ángeles, las autoridades y las potestades. Para probar esto cita varios pasajes del Antiguo Testamento. Comparando lo que Dios dice ahí de los ángeles con lo que dice a Cristo, se manifiesta claramente la inferioridad de los ángeles respecto de Cristo. Aquí está el oficio de los ángeles: son los ministros o siervos de Dios para hacer su voluntad, pero, ¡qué cosas grandiosas dice el Padre de Cristo! Reconozcámosle y honrémosle como Dios, porque si no hubiera sido Dios, nunca hubiera hecho la obra de mediación y nunca hubiera llevado la corona del Mediador. Se declara cómo Cristo fue apto para el oficio de Mediador y cómo fue confirmado en él: Lleva el nombre de Mesías por ser el Ungido. Sólo como Hombre tiene sus semejantes, y como ungido con el Espíritu Santo; pero está por sobre todos los profetas, sacerdotes y reyes, que hayan jamás sido empleados al servicio de Dios en la tierra.
Se cita otro pasaje de la Escritura, Salmo cii, 25-27, en el cual se declara el poder omnipotente del Señor Jesucristo, tanto al crear el mundo como al mudarlo. Cristo envolverá este mundo como si fuera un ropaje, para que no se abuse más de él, ni sea usado como lo ha sido. Como soberano, cuando los ropajes de su estado estén doblados y guardados, sigue siendo el soberano, de la misma manera nuestro Señor seguirá siendo el Señor cuando haya dejado de lado la tierra y los cielos como un ropaje. Entonces no pongamos nuestros corazones en lo que no es lo que creemos que es, y no será lo que es ahora. El pecado ha hecho un gran cambio en el mundo, para peor, y Cristo hará un gran cambio para mejor. Que estos pensamientos nos alerten, diligentes y deseosos del mundo mejor.
El Salvador ha hecho mucho para hacer que todos los hombres sean sus amigos, pero tiene enemigos, aunque serán puestos por estrado de sus pies, por la sumisión humilde o por la destrucción extrema. Cristo seguirá venciendo y para vencer. Los ángeles más excelsos no son sino espíritus ministradores, sólo siervos de Cristo para ejecutar sus mandamientos. Los santos son herederos en el presente que aún no han entrado en plena posesión. Los ángeles les ministran oponiéndose a la maldad y al poder de los malos espíritus, protegiendo y cuidando sus cuerpos, instruyendo y consolando sus almas, sometidos a Cristo y al Espíritu Santo. Los ángeles reunirán a todos los santos en el último día, cuando sean echados de la presencia de Cristo a la miseria eterna todos los que pusieron su corazón y sus esperanzas en los tesoros perecederos y en las glorias pasajeras.</p>
<br/>




</div>
