<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 4</h2>
<p class="text-justify">Vv. 1-4.Los apóstoles predicaron la resurrección de los muertos por medio de Jesús. Incluye toda la dicha del estado futuro; ellos predicaron esto a través de Jesucristo, porque sólo por medio de Él se puede obtener. Miserable es el caso de aquellos para quienes es un dolor la gloria del reino de Cristo, porque dado que la gloria de ese reino es eterna, el dolor de ellos también será eterno.
Los siervos inofensivos y útiles de Cristo, como los apóstoles, suelen verse afligidos por su trabajo de fe y obra de amor, cuando los impíos han escapado. Hasta la fecha no faltan los casos en que la lectura de las Escrituras, la oración en grupo y la conversación sobre temas religiosos encuentran ceños fruncidos y restricciones, pero, si obedecemos los preceptos de Cristo, Él nos sostendrá.</p>
<br/>
<p class="text-justify">Vv. 5-14.Estando lleno del Espíritu Santo, Pedro deseaba que todos entendieran que el milagro había sido obrado en el nombre y el poder de Jesús de Nazaret, el Mesías, al que ellos habían crucificado; y esto confirmaba el testimonio de su resurrección de entre los muertos, lo cual probaba que era el Mesías. Estos dirigentes debían ser salvados por ese Jesús al que habían crucificado o perecer por siempre. El nombre de Jesús es dado a los hombres de toda edad y nación, porque los creyentes son salvos de la ira venidera solo por Él. Sin embargo, cuando la codicia, el orgullo o cualquier pasión corrupta reina por dentro, los hombres cierran sus ojos y cierran sus corazones, con enemistad contra la luz, considerando ignorantes e indoctos a todos los que desean no saber nada si no es Cristo crucificado. Los seguidores de Cristo actuarán en esa forma para que todos los que hablen con ellos, sepan que han estado con Jesús. Esto los hace santos, celestiales, espirituales y jubilosos, y los eleva por encima de este mundo.</p>
<br/>
<p class="text-justify">Vv. 15-22.Todo el interés de los gobernantes es que la doctrina de Cristo no se difunda entre el pueblo, aunque no pueden decir que sea falsa o peligrosa o de alguna mala tendencia; y se avergüenzan de reconocer la razón verdadera: que testifica contra su hipocresía, iniquidad y tiranía. Quienes saben valorar con justicia las promesas de Cristo, saben despreciar, con justicia, las amenazas del mundo. Los apóstoles miran preocupados las almas que perecen y saben que no pueden huir de la ruina eterna sino por Jesucristo; por tanto, son fieles al advertir y mostrar el camino recto.
Nadie disfrutará paz mental ni actuará rectamente hasta que haya aprendido a guiar su conducta por la norma de la verdad, y no por las opiniones y fantasías vacilantes de los hombres. Cuidaos especialmente del vano intento de servir a dos amos, a Dios y al mundo; el final será que no puede servir fielmente a ninguno.</p>
<br/>
<p class="text-justify">Vv. 23-31.Los seguidores de Cristo andan en mejor forma cuando van en compañía, siempre y cuando la compañía sea la de otros como ellos. Estimula a los siervos de Dios tanto al hacer obra como al sufrir el trabajo, saber que sirven al Dios que hizo todas las cosas y, por tanto, dispone todos los sucesos; y que las Escrituras deben cumplirse. Jesús fue ungido para ser Salvador; por tanto, estaba determinado que fuera sacrificio expiatorio por el pecado. Pero el pecado no es el mal menor para que Dios saque bien de él.
En las épocas amenazantes nuestro interés no debe ser tanto evitar los problemas como poder seguir adelante con júbilo y valor en nuestra obra y deber. Ellos no oran, Señor déjanos alejarnos de nuestra tarea ahora que se ha vuelto peligrosa, sino: Señor, danos tu gracia para seguir adelante con constancia en nuestra obra, y no temer el rostro del hombre. Aquellos que desean ayuda y exhortación divina, pueden depender de que las tienen, y deben salir y seguir adelante en el poder del Señor Dios. -Él dio una señal de aceptar sus oraciones. El lugar tembló para que la fe de ellos se estabilizara y no fuera vacilante. Dios les dio mayor grado de su Espíritu y todos ellos fueron llenos con el Espíritu Santo más que nunca; por ello no sólo fueron estimulados, sino capacitados para hablar con denuedo la palabra de Dios. Cuando hallan que el Señor Dios les ayuda por su Espíritu, saben que no serán confundidos, Isaías l, 7.</p>
<br/>
<p class="text-justify">Vv. 32-37.Los discípulos se amaban unos a otros. Esto era el bendito fruto del precepto de la muerte de Cristo para sus discípulos, y su oración por ellos cuando estaba a punto de morir. Así fue entonces y así será otra vez, cuando el Espíritu sea derramado sobre nosotros desde lo alto. La doctrina predicada era la resurrección de Cristo; un hecho cumplido que, cuando se explica debidamente, es el resumen de todos los deberes, privilegios y consuelos de los cristianos. Había frutos evidentes de la gracia de Cristo en todo lo que decían y hacían.
Estaban muertos para este mundo. Esto era una prueba grande de la gracia de Dios en ellos. No se apoderaban de la propiedad ajena, sino que eran indiferentes a ella. No lo llamaban propio, porque con afecto habían dejado todo por Cristo, y esperaban ser despojados de todo para aferrarse a Él. No asombra, pues, que fueran de un solo corazón y un alma, cuando se desprendieron de esa manera de la riqueza de este mundo. En efecto, tenían todo en común, de modo que no había entre ellos ningún necesitado, y cuidaban de la provisión para ellos. El dinero era puesto a los pies de los apóstoles. Se debe ejercer gran cuidado en la distribución de la caridad pública para dar a los necesitados, puesto que no son capaces de procurarse el sostén para sí mismos; se debe proveer a los que están reducidos a la necesidad por hacer el bien, y por el testimonio de una buena conciencia. He aquí uno mencionado en particular, notable por esta caridad generosa: era Bernabé. Como quien es nombrado para ser un predicador del evangelio, él se desembarazó y soltó de los asuntos de esta vida. Cuando prevalecen tales disposiciones, y se las ejerce conforme a las circunstancias de los tiempos, el testimonio tendrá un poder muy grande sobre el prójimo.</p>
<br/>




</div>
