<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 11</h2>
<p class="text-justify">Vv. 1-18.El estado imperfecto de la naturaleza humana se manifiesta con mucha fuerza, cuando personas santas se molestan aun al oír que se ha recibido la palabra de Dios, porque no se prestó atención a su método. Somos muy dados a desesperar de hacer el bien a los que, al probarlos, muestran que tienen deseos de ser enseñados. Causa de la ruina y daño de la iglesia es excluir de ella, y del beneficio de los medios de gracia, a los que no son como nosotros en todo. Pedro contó todo lo pasado. En todo momento debemos soportar las debilidades de nuestros hermanos y, en lugar de ofendernos o de contestar tibiamente, debemos explicar los motivos y mostrar la naturaleza de nuestros procedimientos.
Ciertamente es correcta la predicación con la que se da el Espíritu Santo. Aunque los hombres son muy celosos de sus propios reglamentos, deben cuidarse de no resistir a Dios; y quienes aman al Señor le glorificarán cuando se aseguren que ha otorgado arrepentimiento para vida a todos sus congéneres pecadores. El arrepentimiento es don de Dios; no sólo lo acepta su libre gracia; su gracia omnipotente obra en nosotros, la gracia quita el corazón de piedra y nos da uno de carne. El sacrificio de Dios es un espíritu quebrantado.</p>
<br/>
<p class="text-justify">Vv. 19-24.Los primeros predicadores del evangelio en Antioquía fueron dispersados desde Jerusalén por la persecución; de ese modo lo que pretendía dañar la Iglesia, se hizo que obrara para su bien. La ira del hombre se convierte en alabanza a Dios. -¿Qué deben predicar los ministros de Cristo sino a Cristo? ¿A Cristo, y crucificado? ¿A Cristo, y glorificado? La predicación de ellos fue acompañada de poder divino. La mano del Señor estaba con ellos para llevar a los corazones y a las conciencias de los hombres lo que sólo se podía decir al oído externo. Ellos creyeron, fueron convencidos de la verdad del evangelio. Se convirtieron desde una manera de vivir carnal e indolente a una vida santa, espiritual y celestial. Se convirtieron de adorar a Dios para ser vistos y por formalismo a adorarle en Espíritu y en verdad. Se convirtieron al Señor Jesús que llegó a ser todo en todo para ellos. Esta fue la obra de conversión realizada en ellos y la que debe efectuarse en cada uno de nosotros. Fue fruto de su fe; todos los que creen sinceramente, se convertirán al Señor. Cuando se predica al Señor Jesús con claridad, y conforme a las Escrituras, Él dará éxito; y cuando los pecadores son de esta manera llevados al Señor, los hombres realmente buenos, que están llenos de fe y del Espíritu Santo, admirarán y se regocijarán en la gracia de Dios concedida a ellos. Bernabé estaba lleno de fe; lleno de la gracia de la fe, y lleno de los frutos de la fe que obra por amor.</p>
<br/>
<p class="text-justify">Vv. 25-30.Hasta ahora los seguidores de Cristo eran llamados discípulos, esto es, aprendices, estudiantes, pero desde esa época fueron llamados cristianos. El significado apropiado de este nombre es seguidor de Cristo; denota a uno que, con pensamiento serio, abraza la religión de Cristo, cree sus promesas, y hace que su principal tarea sea formar su vida por los preceptos y el ejemplo de Cristo. De aquí, pues, que es claro que hay multitudes que adoptan el nombre de cristianos, a las cuales no les corresponde correctamente, porque el nombre sin la realidad sólo añade a nuestra culpa. Mientras la sola profesión de fe no otorga provecho ni deleite, la posesión de ella da la promesa para la vida presente y la venidera. Concede, Señor, que los cristianos se olviden de otros nombres y distinciones y se amen unos a otros como deben hacer los seguidores de Cristo. Los cristianos verdaderos sentirán compasión por sus hermanos que pasan por aflicciones. Así se lleva fruto para la alabanza y la gloria de Dios. Si toda la humanidad fuera verdaderamente cristiana, ¡con cuánto júbilo se ayudarían unos a otros! Toda la tierra sería como una gran familia, esforzándose cada miembro por cumplir su deber y ser bondadoso.</p>
<br/>




</div>
