<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 5</h2>
<p class="text-justify">Vv. 1-11.El pecado de Ananías y Safira era que ambicionaban que se pensara que ellos eran discípulos eminentes, cuando no eran discípulos verdaderos. Los hipócritas pueden negarse a sí mismos, pueden dejar sus ventajas mundanas en un caso si tienen la perspectiva de encontrar beneficios en otra cosa. Ambicionaban la riqueza del mundo y desconfiaban de Dios y su providencia. Pensaban que podían servir a Dios y a mamón. Pensaban engañar a los apóstoles. El Espíritu de Dios en Pedro vio el principio de incredulidad que reinaba en el corazón de Ananías. Cualquiera haya sido la sugerencia de Satanás, éste no podría haber llenado su corazón con esta maldad si Ananías no hubiera consentido. La falsedad fue un intento de engañar al Espíritu de verdad que hablaba y actuaba tan manifiestamente por medio de los apóstoles. El delito de Ananías no fue que retuviera parte del precio del terreno; podría haberse quedado con todo si así gustaba; su delito fue tratar de imponerse sobre los apóstoles con una mentira espantosa con el deseo de ser visto, unido a la codicia. Si pensamos que podemos engañar a Dios, engañaremos fatalmente nuestra propia alma. ¡Qué triste es ver las relaciones que debieran estimularse mutuamente a las buenas obras, como se endurecen mutuamente en lo que es malo! Este castigo fue, en realidad, una misericordia para muchísimas personas. Haría que se examinaran estrictamente a sí mismas, con oración y terror de la hipocresía, codicia y vanagloria, y debiera seguir haciéndolo así. Impediría el aumento de los falsos profesantes. Aprendamos de esto cuán odiosa es la falsedad para el Dios de la verdad, y no sólo a evitar la mentira directa, sino todas las ventajas obtenidas de usar expresiones dudosas, y doble significado en nuestra habla.</p>
<br/>
<p class="text-justify">Vv. 12-16.La separación de los hipócritas por medio de juicios discriminatorios, debe hacer que los sinceros se aferren más estrechamente unos a otros y al ministerio del evangelio. Todo lo que tienda a la pureza y reputación de la Iglesia, fomenta su crecimiento, pero aquel poder solo, que obraba tales milagros por medio de los apóstoles, es el que puede rescatar pecadores del poder del pecado y Satanás, y agregar nuevos creyentes a la compañia de sus adoradores. Cristo obra por medio de todos sus siervos fieles y todo el que recurra a Él, será sanado.</p>
<br/>
<p class="text-justify">Vv. 17-25.No hay cárcel tan oscura ni tan segura, que Dios no pueda visitar a su gente en ella y, si le place, sacarlos de ahí. La recuperación de las enfermedades, la liberación de los problemas son concedidas, no para que disfrutemos las consolaciones de la vida, sino para que Dios sea honrado con los servicios de nuestra vida. No es propio que los predicadores del evangelio de Cristo se escondan en los rincones cuando tienen oportunidad de predicar a una gran congregación. Deben predicar a los más viles, cuyas almas son tan preciosas para Cristo como las almas de los más nobles. Habladle a todos, porque todos están incluidos. Hablad como los que deciden defender, vivir y morir por algo. Decid todas las palabras de esta vida celestial divina, comparada con la cual no merece el nombre de vida esta actual vida terrenal. Las palabras de vida que el Espíritu Santo pone en vuestra boca. Las palabras del evangelio son palabras de vida; palabras por las cuales podemos ser salvados. -¡Qué desdichados son los que se sienten angustiados por el éxito del evangelio! ¡No pueden dejar de ver que la palabra y el poder del Señor están contra ellos, y temblando por las consecuencias, de todos modos, siguen adelante!</p>
<br/>
<p class="text-justify">Vv. 26-33.Muchos hacen osadamente algo malo, pero, después no toleran oír de eso o que se les acuse de ello. No podemos esperar ser redimidos y sanados por Cristo si no nos entregamos para ser mandados por Él. La fe acepta al Salvador en todos sus oficios, porque Él vino, no a salvarnos en nuestros pecados sino a salvarnos de nuestros pecados. Si Cristo hubiera sido enaltecido para dar dominio a Israel, los principales sacerdotes le hubieran dado la bienvenida. Sin embargo, el arrepentimiento y la remisión de pecados son bendiciones que ellos no valoraron ni vieron que las necesitaban; por tanto, no reconocieron su doctrina en absoluto.
Donde se obra el arrepentimiento, sin falta se otorga remisión.
Nadie se libra de la culpa y del castigo del pecado, sino los que son liberados del poder y dominio del pecado; los que se apartan del pecado y se vuelven en su contra. Cristo da arrepentimiento por su Espíritu que obra por la palabra para despertar la conciencia, para obrar pesadumbre por el pecado y un cambio eficaz del corazón y la vida. Dar el Espíritu Santo es una prueba evidente de que la voluntad de Dios es que Cristo sea obedecido. Con toda seguridad destruirá a los que no quieren que Él reine sobre ellos.</p>
<br/>
<p class="text-justify">Vv. 34-42.El Señor aún tiene todos los corazones en su mano y, a veces, dirige la prudencia del sabio mundano para frenar a los perseguidores. El sentido común nos dice que seamos cautos puesto que la experiencia y la observación indican que ha sido muy breve el éxito de los fraudes en materia de religión. El reproche por Cristo es la preferencia verdadera, porque hace que nos conformemos a su pauta y sirvamos su interés.
Ellos se regocijaron en eso. Si sufrimos el mal por hacer el bien, siempre y cuando lo suframos bien, como debemos, tenemos que regocijarnos en esa gracia que nos capacitó para hacerlo así. Los apóstoles no se predicaban a sí mismos, sino a Cristo. Esta era la predicación que más ofendía a los sacerdotes. Predicar a Cristo debe ser la actividad constante de los ministros del evangelio: a Cristo crucificado; a Cristo glorificado; nada fuera de esto, sino lo que se refiera a esto. Cualquiera sea nuestra situación o rango en la vida, debemos procurar haberle conocido y glorificar su nombre.</p>
<br/>




</div>
