<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 15</h2>
<p class="text-justify">Vv. 1-6.Unos de Judea enseñaban a los gentiles convertidos de Antioquía que no podían ser salvos a menos que observaran toda la ley ceremonial, tal como fue dada por Moisés; de este modo, procuraban destruir la libertad cristiana. Tenemos una extraña tendencia a pensar que quienes no hacen como nosotros, hacen todo mal. Su doctrina era muy desalentadora. Los hombres sabios y buenos desean evitar las contiendas y los debates hasta donde puedan, pero cuando los falsos maestros se oponen a las principales verdades del evangelio o traen doctrinas nocivas, no debemos dejar de resistirles.</p>
<br/>
<p class="text-justify">Vv. 7-21.De las palabras “purificando por la fe sus corazones”y del sermón de San Pedro, entendemos que no se pueden separar la justificación por la fe, y la santificación por el Espíritu Santo y que ambas son don de Dios. Tenemos mucha razón para bendecir a Dios porque oímos el evangelio. Tengamos esa fe que aprueba el gran Escudriñador de los corazones, y certifica el sello del Espíritu Santo. Entonces, serán purificados de la culpa del pecado nuestros corazones y nuestras conciencias, y seremos liberados de las cargas que algunos tratan de echar encima de los discípulos de Cristo.
Pablo y Bernabé demostraron por hechos comprobados, que Dios reconoció la predicación del puro evangelio a los gentiles sin la ley de Moisés; por tanto, imponerles esa ley era deshacer lo que Dios había hecho. La opinión de Santiago era que los convertidos gentiles no debían ser molestados por los ritos judíos, pero debían abstenerse de carnes ofrendadas a los ídolos, para mostrar su odio por la idolatría. Además, que se les debía advertir contra la fornicación, que no era aborrecida por los gentiles como debía ser, y que hasta formaba parte de algunos de sus rituales. Se les aconsejó abstenerse de comer animales ahogados, y de comer sangre; esto era prohibido por la ley de Moisés y, también aquí, por reverencia a la sangre de los sacrificios, que siendo entonces ofrecida, iba a insultar innecesariamente a los convertidos judíos y a prejuiciar más aun a los judíos inconversos. Pero como hace mucho que cesó el motivo, nosotros somos libres en esto, como en materias semejantes. Los convertidos sean precavidos para que eviten toda apariencia de los males que antes practicaban o a los que probablemente sean tentados; y adviértaseles que usen la libertad cristiana con moderación y prudencia.</p>
<br/>
<p class="text-justify">Vv. 22-35.Teniendo la garantía de declararse dirigidos por el poder inmediato del Espíritu Santo, los apóstoles y los discípulos tuvieron la seguridad de que parecía bien a Dios Espíritu Santo, y a ellos, no imponer, a los convertidos, sea por propia cuenta o por las circunstancias presentes otra carga que las cosas necesarias mencionadas.
Fue un consuelo oír que ya no les serían impuestas las ordenanzas carnales, que confundían sus conciencias, sin poder purificarlas ni pacificarlas; y fueron acallados los que perturbaban sus mentes, de modo que fue restaurada la paz de la iglesia, y se suprimió lo que era amenaza de división. Todo esto fue consuelo por el cual bendijeron a Dios.
Había muchos más en Antioquía. Donde muchos trabajan en la palabra y la doctrina, puede aún haber oportunidad para nosotros: el celo y la utilidad del prójimo debe estimularnos, no adormecernos.</p>
<br/>
<p class="text-justify">Vv. 36-41.Aquí tenemos una pelea en privado de dos ministros, nada menos que Pablo y Bernabé, pero hecha para terminar bien. Bernabé deseaba que su sobrino Juan Marcos fuera con ellos. Debemos sospechar que somos parciales, y cuidarnos de ello, cuando ponemos primero a nuestros parientes. Pablo no pensaba que era digno del honor ni apto para el servicio, quien se había separado de ellos sin que lo supieran o sin el consentimiento de ellos: vea capítulo xiii, 13. Ninguno cedía, por tanto, no hubo remedio sino separarse. Vemos que los mejores hombres no son sino hombres, sujetos a pasiones como nosotros. Quizá hubo faltas de ambos lados como es habitual en tales contiendas. Sólo el ejemplo de Cristo es inmaculado. Pero no tenemos que pensar que es raro que haya diferencias aun entre los hombres buenos y sabios. Será así mientras estemos en este estado imperfecto; nunca seremos todos unánimes hasta que lleguemos al cielo. ¡Sin embargo, cuánta maldad hacen en el mundo, y en la iglesia, los remanentes de orgullo y pasión que se hallan aun en los mejores hombres! Muchos de los que habitaban en Antioquía, que poco y nada habían sabido de la devoción y piedad de Pablo y Bernabé, supieron de su disputa y separación; así nos ocurrirá si cedemos a la discordia. Los creyentes deben orar constantemente que nunca sean guiados a dañar la causa que realmente desean servir por los vestigios del temperamento impío. Pablo habla con estima y afecto de Bernabé y Marcos, en sus epístolas escritas después de este suceso. Todos los que profesan tu nombre, oh amante Salvador, sean completamente reconciliados por ese amor derivado de ti, que no se deja provocar con facilidad y que olvida pronto y entierra las injurias.</p>
<br/>




</div>
