<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 2</h2>
<p class="text-justify">Vv. 1-4.No podemos olvidar con cuánta frecuencia, aunque su Maestro estaba con ellos, hubo discusiones entre los discípulos sobre cuál sería el más grande, pero ahora todas esas discordias habían terminado. Habían orado juntos más que antes. Si deseamos que el Espíritu sea derramado sobre nosotros desde lo alto, tengamos unanimidad. Pese a las diferencias de sentimientos e intereses, como las había entre esos discípulos, pongámonos de acuerdo para amarnos unos a otros, porque donde los hermanos habitan juntos en unidad, ahí manda el Señor su bendición.
Un viento recio llegó con mucha fuerza. Esto era para significar las influencias y la obra poderosa del Espíritu de Dios en las mentes de los hombres, y por medio de ellos, en el mundo. De esta manera, las convicciones del Espíritu dan lugar a sus consolaciones; y las ráfagas recias de ese viento bendito preparan el alma para sus céfiros suaves y amables. Hubo una apariencia de algo como llamas de fuego, que iluminó a cada uno de ellos, según lo que Juan el Bautista decía de Cristo: Él os bautizará con el Espíritu Santo y con fuego. El Espíritu, como fuego, derrite el corazón, quema la escoria, y enciende afectos piadosos y devotos en el alma, en la cual, como el fuego del altar, se ofrecen los sacrificios espirituales.
Fueron llenos del Espíritu Santo más que antes. Fueron llenos de las gracias del Espíritu, y más que antes, puestos bajo su influencia santificadora; más separados de este mundo, y más familiarizados con el otro. Fueron llenos más con las consolaciones del Espíritu, se regocijaron mas que antes en el amor de Cristo y la esperanza del cielo: en eso fueron sorbidos todos sus temores y sus penas. Fueron llenos de los dones del Espíritu Santo; tuvieron poderes milagrosos para el avance del evangelio. Hablaron, no de pensamientos o meditaciones previos, sino como el Espíritu les daba que hablasen.</p>
<br/>
<p class="text-justify">Vv. 5-13.La diferencia de lenguas que surgió en Babel ha estorbado mucho la difusión del conocimiento y de la religión. Los instrumentos que el Señor empleó primero para difundir la religión cristiana, no podrían haber progresado sin este don, lo cual probó que su autoridad era de Dios.</p>
<br/>
<p class="text-justify">Vv. 14-21.El sermón de Pedro muestra que estaba completamente recuperado de su caída y cabalmente restaurado al favor divino; porque el que había negado a Cristo, ahora lo confesaba osadamente. Su relato del derramamiento milagroso del Espíritu Santo estaba concebido para estimular a sus oyentes a que abrazaran la fe de Cristo y se unieran a su Iglesia. Fue cumplimiento de la Escritura y fruto de la resurrección y ascensión de Cristo, y prueba de ambos. Aunque Pedro estaba lleno del Espíritu Santo y hablaba en lenguas conforme el Espíritu le daba que hablase, no pensó en dejar de lado las Escrituras. Los sabios de Cristo nunca aprenden más que su Biblia; y el Espíritu es dado, no para suprimir las Escrituras, sino para capacitarnos para entenderlas, aprobarlas y obedecerlas. Con toda seguridad nadie escapará a la condenación del gran día salvo los que invocan el nombre del Señor, en y por medio de su Hijo Jesucristo, como el Salvador de pecadores, y el Juez de toda la humanidad.</p>
<br/>
<p class="text-justify">Vv. 22-36.A partir de este don del Espíritu Santo, Pedro les predica a Jesús: y he aquí la historia de Cristo. Hay aquí un relato de su muerte y sus sufrimientos, que ellos presenciaron unas pocas semanas antes. Su muerte es considerada como acto de Dios y de maravillosa gracia y sabiduría. De manera que la justicia divina debe ser satisfecha, Dios y el hombre reunidos de nuevo, y Cristo mismo glorificado, conforme al consejo eterno que no puede ser modificado. En cuanto al acto de la gente; fue un acto de pecado y necedad horrendos en ellos. La resurrección de Cristo suprime el reproche de su muerte; Pedro habla mucho de esto. Cristo era el Santo de Dios, santificado y puesto aparte para su servicio en la obra de redención. Su muerte y sufrimiento deben ser la entrada a una vida bendecida para siempre jamás, no sólo para Él sino para todos los suyos. Este hecho tuvo lugar según estaba profetizado y los apóstoles fueron testigos.
La resurrección no se apoyó sobre esto solo; Cristo había derramado dones milagrosos e influencias divinas sobre sus discípulos, y ellos fueron testimonio de sus efectos. Mediante el Salvador se dan a conocer los caminos de la vida y se nos exhorta a esperar la presencia de Dios y su favor para siempre. Todo esto surge de la creencia segura que Jesús es el Señor y el Salvador ungido.</p>
<br/>
<p class="text-justify">Vv. 37-41.Desde la primera entrega del mensaje divino se vio que en él había poder divino; miles fueron llevados a la obediencia de la fe. Pero ni las palabras de Pedro ni el milagro presenciado pudieron producir tales efectos si no se hubiera dado el Espíritu Santo. Cuando los ojos de los pecadores son abiertos, no pueden sino sentir remordimiento de corazón por el pecado, no pueden menos que sentir una inquietud interior. El apóstol les exhorta a arrepentirse de sus pecados y confesar abiertamente su fe en Jesús como el Mesías, y ser bautizados en su nombre. Así, pues, profesando su fe en Él, iban a recibir la remisión de sus pecados, y a participar de los dones y gracias del Espíritu Santo.
Separarse de la gente impía es la única manera de salvarnos de ellos. Los que se arrepienten de sus pecados y se entregan a Jesucristo, deben probar su sinceridad desembarazándose de los impíos. Debemos salvarnos de ellos, lo cual supone evitarlos con horror y santo temor. Por gracia de Dios tres mil personas aceptaron la invitación del evangelio. No puede haber duda que el don del Espíritu Santo, que todos recibieron, y del cual ningún creyente verdadero ha sido jamás exceptuado, era ese Espíritu de adopción, esa gracia que convierte, guía y santifica, la cual se da a todos los miembros de la familia de nuestro Padre celestial. El arrepentimiento y la remisión de pecados aún se predican a los principales de los pecadores en el nombre del Redentor; el Espíritu Santo aún sella la bendición en el corazón del creyente; aun las promesas alentadoras son para nosotros y para nuestros hijos; y aún se ofrecen las bendiciones a todos los que están lejos.</p>
<br/>
<p class="text-justify">Vv. 42-47.En estos versículos tenemos la historia de la iglesia verdaderamente primitiva, de sus primeros tiempos; su estado de verdadera infancia, pero, como aquel, su estado de mayor inocencia. Se mantuvieron cerca de las ordenanzas santas y abundaron en piedad y devoción; porque el cristianismo, una vez que se admite en su poder, dispone el alma a la comunión con Dios en todas esas formas establecidas para que nos encontremos con Él, y en que ha prometido reunirse con nosotros.
La grandeza del suceso los elevó por sobre del mundo, y el Espíritu Santo los llenó con tal amor que hizo que cada uno fuera para otro como para sí mismo, y, de este modo, hizo que todas las cosas fueran en común, sin destruir la propiedad, sino suprimiendo el egoísmo y provocando el amor. Dios que los movió a ello, sabía que ellos iban a ser rápidamente echados de sus posesiones en Judea. El Señor, de día en día, inclinaba más los corazones a abrazar el evangelio; no simples profesantes, sino los que eran realmente llevados a un estado de aceptación ante Dios, siendo partícipes de la gracia regeneradora. Los que Dios ha designado para la salvación eterna, serán eficazmente llevados a Cristo hasta que la tierra sea llena del conocimiento de su gloria.</p>
<br/>




</div>
