<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 14</h2>
<p class="text-justify">Vv. 1-7.Los apóstoles hablaban con tanta sencillez, con tanta demostración y pruebas del Espíritu y con tal poder; tan cálidamente y con tanto interés por las almas de los hombres, que quienes les escuchaban no podían decir sino que Dios estaba de verdad con ellos. Pero el éxito no debía atribuirse a su estilo de predicar, sino al Espíritu de Dios que usaba ese medio. La perseverancia para hacer el bien en medio de peligros y dificultades es una bendita muestra de gracia. Dondequiera que sean llevados los siervos de Dios, deben tratar de decir la verdad. Cuando iban en el nombre y el poder de Cristo, Él no dejaba de dar testimonio de la palabra de su gracia. Nos asegura que es la palabra de Dios y que podemos jugarnos nuestras almas por ella. Los gentiles y los judíos estaban enemistados unos con otros, pero unidos contra los cristianos. Si los enemigos de la Iglesia se unen para destruirla, ¿no se unirán sus amigos para preservarla? Dios tiene un refugio para su pueblo en caso de tormenta: Él es y será su refugio. En las épocas de persecución los creyentes pueden tener motivos para irse de un lugar aunque no dejen la obra de su Maestro.</p>
<br/>
<p class="text-justify">Vv. 8-18.Todas las cosas son posibles para el que cree. Cuando tenemos fe, don tan precioso de Dios, seremos librados de la falta de defensa espiritual en que nacimos, y del dominio de los hábitos pecaminosos desde que se formaron; seremos capacitados para ponernos de pie y andar jubilosos en los caminos del Señor.
Cuando Cristo, el Hijo de Dios, se manifestó en semejanza de hombres, e hizo muchos milagros, los hombres distaban tanto de hacerle sacrificio, que lo hicieron sacrificio a Él para la soberbia y maldad de ellos. Sin embargo, Pablo y Bernabé fueron tratados como dioses por haber hecho un milagro. El mismo poder del dios de este mundo, que cierra la mente carnal contra la verdad, hace que sean fácilmente admitidos los yerros y las equivocaciones.
No leemos que hayan rasgado sus vestiduras cuando el pueblo habló de lapidarlos, sino cuando hablaron de adorarles; ellos no pudieron tolerarlo, estando más preocupados por la honra de Dios que por la propia. La verdad de Dios no necesita los servicios de la falsedad del hombre. Los siervos de Dios pueden obtener fácilmente honras indebidas si ceden a los errores y vicios de los hombres, pero deben aborrecer y detestar ese respeto más que a todo reproche.
Cuando los apóstoles predicaron a los judíos que odiaban la idolatría, sólo tuvieron que predicar la gracia de Dios en Cristo, pero cuando tuvieron que predicarle a los gentiles, debieron corregir los errores de la religión natural. Compárese la conducta y la declaración de ellos con opiniones de quienes piensan falsamente que la adoración de Dios, bajo cualquier nombre o de cualquier manera, es igualmente aceptable para el Señor Todopoderoso.
Los argumentos de mayor fuerza, los discursos más fervientes y afectuosos, hasta con milagros, apenas bastan para resguardar a los hombres de absurdos y abominaciones; mucho menos pueden, sin la gracia especial, volver los corazones de los pecadores a Dios y a la santidad.</p>
<br/>
<p class="text-justify">Vv. 19-28.Nótese cuán incansable era la furia de los judíos contra el evangelio de Cristo. La gente apedreó a Pablo en un tumulto popular. Tan fuerte es la inclinación del corazón corrupto y carnal, que con suma dificultad los hombres se retienen del mal, por una parte, así como con gran facilidad son persuadidos a hacer el mal por la otra. Si Pablo hubiera sido Mercurio, hubiera podido ser adorado, pero si es ministro fiel de Cristo, será apedreado y echado de la ciudad. Así, pues, los hombres que se someten fácilmente a fuertes ilusiones, detestan recibir la verdad con amor.
Todos los que son convertidos tienen que ser confirmados en la fe; todos los que son plantados tienen que criar raíces. La obra de los ministros es establecer a los santos y despertar a los pecadores. La gracia de Dios, y nada menos, establece eficazmente las almas de los discípulos. Es cierto que podemos contar con mucha tribulación, pero es estimulante que no estamos perdidos ni pereceremos en ella.
La Persona a cuyo poder y gracia están encomendados los convertidos y las iglesias recién establecidas, era claramente el Señor Jesús, “en quien todos creyeron”. Fue un acto de adoración.
Todo el elogio de lo poco bueno que hacemos en cualquier momento, debe atribuirse a Dios, porque Él es quien no sólo obra en nosotros el querer como el hacer, sino también obra con nosotros para que alcance el éxito. Todos los que aman al Señor Jesús se regocijarán al oír que ha abierto de par en par la puerta de la fe a los que eran ajenos a Él y a su salvación. Como los apóstoles, habitemos con los que conocen y aman al Señor.</p>
<br/>




</div>
