<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 3</h2>
<p class="text-justify">Vv. 1-11.Los apóstoles y los primeros creyentes asistían al servicio de adoración en el templo a la hora de la oración. Parece que Pedro y Juan fueron llevados por dirección divina a obrar un milagro en un hombre de más de cuarenta años, inválido de nacimiento. En el nombre de Jesús de Nazaret, Pedro le manda levantarse y caminar. Así, si intentamos con buen propósito la sanidad de las almas de los hombres, debemos ir en el nombre y el poder de Jesucristo, llamando a los pecadores incapacitados que se levanten y anden en el camino de la santidad por fe en Él. ¡Qué dulce para nuestra alma es pensar que el nombre de Jesucristo de Nazaret puede hacernos íntegros, respecto de todas las facultades paralizadas de nuestra naturaleza caída! ¡Con cuánto gozo y arrobamiento santo andaremos por los atrios santos cuando Dios Espíritu nos haga entrar en ellos por su poder!</p>
<br/>
<p class="text-justify">Vv. 12-18.Nótese la diferencia en el modo de hacer los milagros. Nuestro Señor siempre habla como teniendo poder omnipotente, sin vacilar jamás para recibir la honra más grande que le fue conferida por sus milagros divinos. Pero los apóstoles referían todo al Señor y se negaban a recibir honra, salvo como sus instrumentos sin méritos. Esto muestra que Jesús era uno con el Padre, e igual con Él; mientras los apóstoles sabían que eran hombres débiles y pecadores, dependientes en todo de Jesús, cuyo poder era el que curaba. Los hombres útiles deben ser muy humildes. No a nosotros, oh Señor, no a nosotros, sino a tu nombre gloria. Toda corona debe ser puesta a los pies de Cristo.
El apóstol muestra a los judíos la enormidad de su delito, pero sin querer enojarlos ni desesperarlos. Con toda seguridad los que rechazan, rehusan o niegan a Cristo lo hacen por ignorancia, pero eso no se puede presentar como excusa en ningún caso.</p>
<br/>
<p class="text-justify">Vv. 19-21.La absoluta necesidad del arrepentimiento debe cargarse solemnemente en la conciencia de todos los que desean que sus pecados sean borrados y que puedan tener parte en el refrigerio que nada puede dar, sino el sentido del amor perdonador de Cristo. Bienaventurados los que han sentido esto. No era necesario que el Espíritu Santo diera a conocer los tiempos y las sazones de esta dispensación. Estos temas aún quedan oscuros, pero cuando los pecadores tengan convicción de sus pecados, clamarán perdón al Señor; y al penitente convertido y creyente le llegarán tiempos de refrigerio de la presencia del Señor. En un estado de tribulación y prueba el glorioso Redentor estará fuera de la vista, porque debemos vivir por fe en Él.</p>
<br/>
<p class="text-justify">Vv. 22-26.He aquí un discurso fuerte para advertir a los judíos las consecuencias temibles de su incredulidad, con las mismas palabras de Moisés, su profeta preferido, dado el celo fingido de quienes estaban listos para rechazar el cristianismo y tratar de destruirlo. Cristo vino al mundo a traer una bendición consigo y envió a su Espíritu para que fuera la gran bendición. Cristo vino a bendecirnos convirtiéndonos de nuestras iniquidades y salvándonos de nuestros pecados. Por naturaleza nosotros nos aferramos al pecado; el designio de la gracia divina es hacernos volver de eso para que no sólo podamos abandonarlo, sino odiarlo. Que nadie piense que puede ser feliz continuando en pecado cuando Dios declara que la bendición está en apartarse de toda la iniquidad. Que nadie piense que entiende o cree el evangelio si sólo busca liberación del castigo del pecado, pero no espera felicidad al ser liberado del pecado mismo. Nadie espere ser apartado de su pecado a no ser que crea en Cristo el Hijo de Dios, y lo reciba como sabiduría, justicia, santificación y redención.</p>
<br/>




</div>
