<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 13</h2>
<p class="text-justify">Vv. 1-3.¡Qué equipo tenemos aquí! Vemos en estos nombres que el Señor levanta instrumentos para su obra de diversos lugares y estados sociales; el celo por su gloria induce a los hombres a renunciar a relaciones y perspectivas halagadoras para fomentar su causa. Los ministros de Cristo están capacitados y dispuestos para su servicio por su Espíritu, y se les retira de otros intereses que les estorban. Los ministros de Cristo deben dedicarse a la obra de Cristo y, bajo la dirección del Espíritu, actuar para la gloria de Dios Padre. Son separados para emprender trabajos con dolor y no para asumir rangos.
Buscaron la bendición para Pablo y Bernabé en su presente empresa, para que fuesen llenos con el Espíritu Santo en su obra. No importa qué medios se usen o que reglas se observen, solo el Espíritu Santo puede equipar a los ministros para su importante obra, y llamarlos a ella.</p>
<br/>
<p class="text-justify">Vv. 4-13.Satanás está especialmente ocupado con los grandes hombres y los hombres que están en el poder para impedir que sean religiosos, porque su ejemplo influye a muchos.
Aquí por primera vez Saulo es llamado Pablo, y nunca más Saulo. Cuando era hebreo su nombre era Saulo; como ciudadano de Roma su nombre era Pablo. Bajo la influencia directa del Espíritu Santo, dio a Elimas su carácter verdadero, pero no en forma apasionada. La plenitud del engaño y la maldad reunidas pueden hacer, sin duda, que un hombre sea hijo del diablo. Quienes son enemigos de la doctrina de Jesús son enemigos de toda justicia, porque en ella se cumple toda justicia. Los caminos del Señor Jesús son los únicos caminos rectos al cielo y a la dicha. Hay muchos que no sólo se descarrían de estos caminos, sino que también ponen al prójimo en contra de esos caminos. Ellos están frecuentemente tan endurecidos que no cesarán de hacer el mal. El procónsul quedó asombrado por la fuerza de la doctrina en su propio corazón y conciencia, y por el poder de Dios con que fue confirmada. La doctrina de Cristo deja atónito; y mientras más sabemos de ella, más razón veremos para maravillarnos de ella.
Los que ponen su mano en el arado y miran hacia atrás, no son aptos para el reino de Dios. Quienes no están preparados para enfrentar oposición y soportar dificultades, no son aptos para la obra del ministerio.</p>
<br/>
<p class="text-justify">Vv. 14-31.Cuando nos reunimos para adorar a Dios debemos hacerlo no sólo con oración y alabanza, sino para leer y oír la palabra de Dios. No basta con la sola lectura de las Escrituras en las asambleas públicas; ellas deben ser expuestas y se debe exhortar a la gente con ellas. Esto es ayudar a que la gente haga lo necesario para sacar provecho de la palabra, para aplicarla a sí mismos.
En este sermón se toca todo cuanto debiera convencer de la mejor manera a los judíos para recibir y abrazar a Cristo como el Mesías prometido. Toda opinión, no importa cuán breve o débil sea, sobre los tratos del Señor con su Iglesia, nos recuerda su misericordia y paciencia, y la ingratitud y perversidad del hombre.
Pablo va desde David al Hijo de David, y demuestra que este Jesús es su Simiente prometida; el Salvador que hace por ellos, sus peores enemigos, lo que no podían hacer los jueces de antes, para salvarlos de sus pecados. Cuando los apóstoles predicaban a Cristo como el Salvador, distaban mucho de ocultar su muerte, tanto que siempre predicaban a Cristo crucificado.
Nuestra completa separación del pecado la representa el que somos sepultados con Cristo. Pero Él resucitó de entre los muertos y no vio corrupción: esta era la gran verdad que había que predicar.</p>
<br/>
<p class="text-justify">Vv. 32-37.La resurrección de Cristo era la gran prueba de que es el Hijo de Dios. No era posible que fuera retenido por la muerte, porque era el Hijo de Dios, y por tanto, tenía la vida en sí mismo, la cual no podía entregar sin el propósito de volverla a tomar. La seguridad de las misericordias de David es la vida eterna, de la cual era señal segura la resurrección; y las bendiciones de la redención en Cristo son una primicia cierta aun en este mundo. David fue una gran bendición para la época en que vivió. No nacemos para nosotros mismos, pero alrededor nuestro vive gente, a quienes debemos tener presentes para servir. Pero aquí radica la diferencia: Cristo iba a servir a todas las generaciones. Miremos a Aquel que es declarado ser Hijo de Dios por su resurrección de entre los muertos para que, por fe en Él, podamos andar con Dios, y servir a nuestra generación según su voluntad; y cuando llegue la muerte, durmamos en Él con la esperanza gozosa de una bendita resurrección.</p>
<br/>
<p class="text-justify">Vv. 38-41.Todos los que oyen el evangelio de Cristo sepan estas dos cosas: -1. Que a través de este Hombre, que murió y resucitó, se os predica el perdón de pecado. Vuestros pecados, aunque muchos y grandes, pueden ser perdonados, y pueden serlo sin perjuicio de la honra de Dios.
2. Por Cristo solo, y por nadie más, son justificados de todas las cosas los que creen en Él; justificados de toda la culpa y mancha del pecado de lo cual no pudieron ser justificados por la ley de Moisés. El gran interés de los pecadores convictos es ser justificados, ser exonerados de toda su culpa y aceptados como justos ante los ojos de Dios, porque si algo queda a cargo del pecador, estará acabado. Por Jesucristo podemos obtener la justificación completa; porque por Él fue hecha la completa expiación por el pecado. Somos justificados no sólo por Él como nuestro Juez, sino por Él como Jehová Justicia nuestra. Lo que la ley no podía hacer por nosotros, por cuanto era débil, lo hace el evangelio de Cristo. Esta es la bendición más necesaria que trae todas las demás.
Las amenazas son advertencias; lo que se nos dice que les sobrevendrá a los pecadores impenitentes, está concebido para despertarnos a estar alertas, no sea que caiga sobre nosotros. Destruye a muchos que desprecian la religión. Quienes no se maravillen y sean salvos, se asombrarán y perecerán.</p>
<br/>
<p class="text-justify">Vv. 42-52.Los judíos se oponían a la doctrina que predicaban los apóstoles y, cuando no pudieron hallar qué objetar, blasfemaron a Cristo y su evangelio. Corrientemente los que empiezan por contradecir, terminan por blasfemar. Cuando los adversarios de la causa de Cristo son osados, sus abogados deben ser aun más atrevidos. Mientras muchos no se juzgan dignos de la vida eterna, otros que parecen menos probables, desean oír más de la buena nueva de la salvación.
Esto es conforme a lo que fue anunciado en el Antiguo Testamento. ¡Qué luz, qué poder, qué tesoro trae consigo este evangelio! ¡Cuán excelentes son sus verdades, sus preceptos, sus promesas! Vinieron a Cristo aquellos a quienes trajo el Padre, y a quienes el Espíritu hizo el llamamiento eficaz, Romanos viii, 30. Todos los que estaban ordenados para la vida eterna, todos los que estaban preocupados por su estado eterno y querían asegurarse la vida eterna, todos ellos creyeron en Cristo, en quien Dios había guardado la vida, y es el único Camino a ella; y fue la gracia de Dios que la obró en ellos.
Bueno es ver que mujeres devotas nobles; mientras menos tengan que hacer en el mundo, más deben hacer por sus propias almas, y las almas del prójimo, pero entristece que ellas traten de mostrar odio a Cristo bajo el matiz de la devoción a Dios. Mientras más nos deleitemos con las consolaciones y exhortaciones que hallamos en el poder de la santidad, y mientras más llenos estén nuestros corazones con ellos, mejor preparados estamos para enfrentar las dificultades de la profesión de santidad.</p>
<br/>




</div>
