<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 26</h2>
<p class="text-justify">Vv. 1-11.El cristianismo nos enseña a dar razón de la esperanza que hay en nosotros y, también, a honrar a quien se debe rendir honores, sin halagos ni temor al hombre. Agripa era bien versado en las Escrituras del Antiguo Testamento, por tanto, podía juzgar mejor en la polémica de que Jesús es el Mesías. Ciertamente los ministros pueden esperar, cuando predican la fe de Cristo, que se les oiga con paciencia. Pablo confiesa que él aún adhería a todo lo bueno en que fue primeramente educado y preparado. Véase aquí cuál era su religión. Era un moralista, un hombre virtuoso, y no había aprendido las artes de los astutos fariseos codiciosos; a él no se podía acusar de ningún vicio franco ni de profano. Era firme en la fe. Siempre había tenido santa consideración por la antigua promesa hecha por Dios a los padres, y edificado su esperanza sobre ella. El apóstol sabía muy bien que todo eso no lo justificaba ante Dios, pero sabía que era para su reputación entre los judíos, y un argumento de que no era la clase de hombre que ellos decían que era. Aunque contaba esto como pérdida para ganar a Cristo, aún así, lo menciona cuando sirve para honrar a Cristo.
Véase aquí cuál es la religión de Pablo; él no tiene el celo por la ley ceremonial que tuvo en su juventud; los sacrificios y las ofrendas designadas por ella, están terminadas por el gran Sacrificio que ellas tipificaban. No hace mención de los lavados ceremoniales y piensa que el sacerdocio levítico terminó por el sacerdocio de Cristo, pero en cuanto a los principales fundamentos de su religión, sigue tan celoso como siempre. Cristo y el cielo son las dos grandes doctrinas del evangelio; que Dios nos ha dado vida eterna, y esta vida está en su Hijo. Estos son el tema de la promesa hecha a los antepasados. El servicio del templo o el curso continuo de los deberes religiosos, día y noche, era mantenido como profesión de fe en la promesa de la vida eterna, y como expectativa de ella. La perspectiva de la vida eterna debe comprometernos a ser diligentes y constantes en todos los ejercicios religiosos. No obstante, los saduceos odiaban a Pablo por predicar la resurrección; y los otros judíos se unieron a ellos porque él testificaba que Jesús había resucitado y que era el prometido Redentor de Israel. Muchas cosas se piensan que están más allá de la creencia, sólo porque pasan por alto la naturaleza y las perfecciones infinitas de quien las reveló, cumplió o prometió.
Pablo reconoce que mientras fue fariseo, era un enemigo enconado del cristianismo. Este era su carácter y estilo de vida al comienzo de su tiempo; y había toda clase de cosas que obstaculizaban que él fuese cristiano. Quienes han sido más estrictos en su conducta antes de la conversión, después verán que hay muchos motivos para humillarse aún por cosas que entonces pensaban que debían hacerse.</p>
<br/>
<p class="text-justify">Vv. 12-23.Pablo fue hecho cristiano por el poder divino; por una revelación de Cristo a él y en él, cuando estaba en el apogeo de su carrera de pecado. Fue hecho ministro por autoridad divina: el mismo Jesús que le apareció en esa luz gloriosa, le mandó predicar el evangelio a los gentiles. El mundo que está en tinieblas debe ser iluminado; deben ser llevados a conocer las cosas que corresponden a su paz eterna los que aún las ignoran. El mundo que yace en la iniquidad debe ser santificado y reformado; no basta con que a ellos se les haya abierto los ojos, ellos deben tener renovados sus corazones; no basta con ser vueltos desde la oscuridad a la luz; deben volverse del poder de Satanás a Dios. Todos los que son convertidos del pecado a Dios, no sólo son perdonados; tienen la concesión de una rica herencia. El perdón de pecados da lugar a esto. Nadie que no sea santo puede ser feliz; y para ser santos en el cielo debemos primero ser santos en la tierra. Somos hechos santos y salvados por fe en Cristo; por la cual confiamos en Cristo como Jehová Justicia nuestra, y nos entregamos a Él como Jehová nuestro Rey; por esto recibimos la remisión de pecados, el don del Espíritu Santo, y la vida eterna.
La cruz de Cristo era una piedra de tropiezo para los judíos, y ellos estaban furiosos porque Pablo predicaba el cumplimiento de las predicciones del Antiguo Testamento. Cristo debe ser el primero que resucitara de entre los muertos; la Cabeza o el Principal. Además, los profetas anunciaron que los gentiles serían llevados a conocer a Dios por medio del Mesías; ¿y en qué podían desagradarse los judíos de esto, con justicia? Así, pues, el convertido verdadero puede dar razón de su esperanza y una buena cuenta del cambio manifiesto en él. Pero por andar por ahí y llamar a los hombres a arrepentirse y ser convertidos de esta manera, muchísimas personas han sido culpadas y perseguidas.</p>
<br/>
<p class="text-justify">Vv. 24-32.Nos corresponde, en todas las ocasiones, decir palabras de verdad y sobriedad y, entonces, no tendremos que turbarnos por las censuras injustas de los hombres. Los seguidores activos y esforzados del evangelio han sido frecuentemente despreciados por soñadores o locos, por creer tales doctrinas y tales hechos maravillosos; y por atestiguar que la misma fe y diligencia, y una experiencia como la de ellos, es necesaria para todos los hombres, cualesquiera sea su rango, para su salvación. Pero los apóstoles y los profetas, y el mismo Hijo de Dios, fueron expuestos a esta acusación; nadie tiene que conmoverse por eso cuando la gracia divina los han hechos sabios para salvación. Agripa vio que había mucha razón para el cristianismo. Su entendimiento y su juicio fueron convencidos momentáneamente, pero su corazón no fue cambiado. Su conducta y temperamento eran muy diferentes de la humildad y espiritualidad del evangelio. Muchos de los que están casi persuadidos de ser religiosos, no están completamente persuadidos; están sometidos a fuertes convicciones de su deber y de la excelencia de los caminos de Dios, aunque no procuran sus convicciones.
Pablo instaba que era interés de cada uno llegar a ser un cristiano verdadero: que hay gracia suficiente en Cristo para todos. Expresa su pleno convencimiento de la verdad del evangelio, la necesidad absoluta de fe en Cristo para salvación. La salvación de la esclavitud es lo que el evangelio de Cristo ofrece a los gentiles; a un mundo perdido. Sin embargo, es con mucha dificultad que se puede convencer a cualquier persona de que necesita la obra de gracia en su corazón, como necesaria para la conversión de los gentiles. Tengamos cuidado de la vacilación fatal de nuestra propia conducta; y acordémonos de cuánto dista el estar casi persuadido de ser cristiano, de serlo por completo como es todo creyente verdadero.</p>
<br/>




</div>
