<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 9</h2>
<p class="text-justify">Vv. 1-9.Tan mal informado estaba Saulo que pensaba que debía hacer todo lo que pudiera contra el nombre de Cristo, y que con eso le hacía un servicio a Dios; parecía que en esto estaba en su elemento. No perdamos la esperanza de la gracia renovadora para la conversión de los peores pecadores, ni dejemos que ellos pierdan la esperanza en la misericordia de Dios que perdona el pecado más grande. Es señal del favor divino impedirnos, por medio de la obra interior de su gracia o por los sucesos exteriores de su providencia continuar o ejecutar objetivos pecaminosos. Saulo vio al Justo, capítulo xxii, 14, y capítulo xxvi, 13. ¡Qué cerca de nosotros está el mundo invisible! Si Dios sólo corre el velo, los objetos se presentan a la vista, comparados con los cuales, lo que más se admira en la tierra, resulta vil y despreciable. Saulo se sometió sin reservas, deseoso de saber lo que quería el Señor Jesús que él hiciera. Las revelaciones de Cristo a las pobres almas son humillantes; las abaten profundamente con pobres pensamientos sobre sí mismas.
Saulo no comió durante tres días, y agradó a Dios dejarlo sin alivio durante ese tiempo. Ahora sus pecados fueron puestos en orden ante él; estaba en tinieblas sobre su propio estado espiritual, y herido en el espíritu por el pecado. Cuando el pecador es llevado a una percepción adecuada de su estado y conducta, se arroja totalmente a la misericordia del Salvador, preguntando qué quiere que haga. Dios dirige al pecador humillado, y aunque suele no llevar a los transgresores al gozo y la paz de creer sin dolor ni intranquilidad de conciencia, bajo los cuales el alma es profundamente comprometida con las cosas eternas, de todos modos son bienaventurados los que siembran con lágrimas, porque cosecharán con gozo.</p>
<br/>
<p class="text-justify">Vv. 10-22.Una buena obra fue comenzada en Saulo cuando fue llevado a los pies de Cristo con estas palabras: Señor, ¿qué quieres que yo haga? Nunca Cristo dejó a nadie que llegara a ese punto. Contémplese al fariseo orgulloso, el opresor despiadado, el blasfemo atrevido, ¡orando! Aun ahora ocurre lo mismo con el infiel orgulloso o el pecador abandonado. ¡Qué nuevas felices son aquellas para todos los que entienden la naturaleza y el poder de la oración, de una oración como la que presenta el pecador humillado rogando las bendiciones de la salvación gratuita! Ahora empezó a orar de una manera diferente de lo que hacía antes, cuando decía sus oraciones, pero ahora las oraba. La gracia regeneradora pone a orar a la gente; más fácil es que halle a un hombre vivo que no respira que a un cristiano vivo que no ora. Pero hasta los discípulos eminentes como Ananías vacilan, a veces, ante las órdenes de su Señor. Sin embargo, es la gloria del Señor superar nuestras bajas expectativas y mostrar que son vasos de su misericordia los que consideramos objetos de su venganza.
La enseñanza del Espíritu Santo elimina del entendimiento las escamas de ignorancia y orgullo; entonces, el pecador llega a ser una nueva criatura y se dedica a recomendar al Salvador ungido, el Hijo de Dios, a sus compañeros de antes.</p>
<br/>
<p class="text-justify">Vv. 23-31.Cuando entramos en el camino de Dios debemos esperar pruebas; pero el Señor sabe librar al santo y también dará, junto con la prueba, la salida. Aunque la conversión de Saulo fue y es prueba de la verdad del cristianismo, aún así, no podía, por sí misma, convertir un alma enemistada con la verdad; porque nada puede producir fe verdadera sino ese poder que crea de nuevo el corazón.
Los creyentes son dados a sospechar demasiado de aquellos en contra de los cuales tienen prejuicios. El mundo está lleno de engaño y es necesario ser cauto, pero debemos ejercer caridad, 1 Corintios xiii, 5. El Señor esclarece el carácter de los creyentes verdaderos, los une a su pueblo, y a menudo, les da oportunidad de dar testimonio de su verdad, ante quienes fueron testigos de su odio. Ahora Cristo se apareció a Saulo y le mandó que saliera rápidamente de Jerusalén, porque debía ser enviado a los gentiles: véase el capítulo xxii 21. Los testigos de Cristo no pueden ser muertos mientras no hayan terminado sus testimonios.
Las persecuciones fueron soportadas. Los profesantes del evangelio anduvieron rectamente y gozaron de mucho consuelo de parte del Espíritu Santo en la esperanza y la paz del evangelio, y otros fueron ganados para ellos. Vivieron del consuelo del Espíritu Santo no sólo en los días de trastorno y aflicción, sino en los días de reposo y prosperidad. Es más probable que caminen gozosamente los que caminan con cautela.</p>
<br/>
<p class="text-justify">Vv. 32-35.Los cristianos son santos o pueblo santo; no sólo los eminentes como San Pedro y San Pablo, sino todo sincero profesante de la fe de Cristo. Cristo eligió a pacientes con enfermedades incurables según el curso natural, para mostrar cuán desesperada es la situación de la humanidad caída. Cuando éramos completamente débiles, como este pobre hombre, Él mandó su palabra para sanarnos. Pedro no pretende sanar por poder propio, pero dirige a Eneas a que mire a Cristo en busca de ayuda. Nadie diga que por cuanto es Cristo el que por el poder de su gracia, obra todas nuestras obras en nosotros, no tenemos obra que hacer, ni deber que cumplir; porque, aunque Jesucristo te haga íntegro, tú debes levantarte, y usar el poder que Él te da.</p>
<br/>
<p class="text-justify">Vv. 36-43.Muchos de los que están llenos de buenas palabras están vacíos y estériles de buenas obras; pero Tabita era una gran hechora, no una gran conversadora. Los cristianos que no tienen propiedad para dar como caridad pueden, aún, ser capaces de hacer obras de caridad, trabajando con sus manos o yendo con sus pies para el bien del prójimo. Son ciertamente mejor elogiados aquellos cuyas obras los elogian, sea que las palabras de los demás lo hagan o no. Sin duda son ingratos los que no reconocen el bien que se les hace mostrando la bondad hecha a ellos. Mientras vivimos de la plenitud de Cristo para nuestra plena salvación, debemos desear estar llenos de buenas obras para gloria de su nombre y para beneficio de sus santos. Caracteres como Dorcas son útiles donde moren, porque muestran la excelencia de la palabra de verdad por medio de sus vidas. ¡Qué viles son, entonces, las preocupaciones de tantas mujeres que no buscan distinción, sino en el ornamento externo, y desperdician sus vidas en la frívola búsqueda de vestidos y vanidades! -El poder se unió a la palabra y Dorcas volvió a la vida. Así es en la resurrección de las almas muertas a la vida espiritual: la primera señal de vida es abrir los ojos de la mente. Aquí vemos que el Señor puede compensar toda pérdida; que Él gobierna cada hecho para el bien de quienes confían en Él, y para gloria de su nombre.</p>
<br/>




</div>
