<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 28</h2>
<p class="text-justify">Vv. 1-10.Dios puede hacer que los extraños sean amigos; amigos en la angustia. Quienes son despreciados por sus maneras acogedoras suelen ser más amistosos que los más educados; y la conducta de los paganos, o de las personas calificadas de bárbaros, condena a muchos en las naciones civilizadas, que profesan ser cristianas.
La gente pensó que Pablo era un asesino, y que la víbora fue enviada por la justicia divina para que fuera la vengadora de la sangre. Sabían que hay un Dios que gobierna el mundo, de modo que las cosas no acontecen por casualidad, no, ni el suceso más mínimo, sino que todo es por dirección divina; y que el mal persigue a los pecadores; que hay buenas obras que Dios recompensará, y malas obras que castigará. Además, que el asesinato es un delito horrible y que no pasará mucho tiempo sin que sea castigado. Pero pensaban que todos los malos eran castigados en esta vida. Aunque algunos son hechos ejemplos en este mundo para probar que hay un Dios y una providencia, aún muchos son dejados sin castigar para probar que hay un juicio venidero. También pensaban que era gente mala todos los que eran notablemente afligidos en esta vida. La revelación divina pone este asunto bajo la luz verdadera. Los hombres buenos suelen ser sumamente afligidos en esta vida para la prueba y el aumento de su fe y paciencia.
Fijaos en la liberación de Pablo ante el peligro. Y, así, en el poder de la gracia de Cristo, los creyentes se sacuden las tentaciones de Satanás con santa resolución. Cuando despreciamos las censuras y los reproches de los hombres, y los miramos con santo desprecio, teniendo el testimonio de nuestras conciencias, entonces, como Pablo, sacudimos a la víbora tirándola al fuego. No nos hace daño excepto si por ello nos mantenemos fuera de nuestro deber. Con eso Dios hace notable a Pablo para esa gente y, de ese modo, abrió el camino para la recepción del evangelio. El Señor levanta amigos para su pueblo en todo lugar donde los lleve, y los hace bendición para los afligidos.</p>
<br/>
<p class="text-justify">Vv. 11-16.Los acontecimientos corrientes de los viajes raramente son dignos de ser narrados, pero merece mención particular el consuelo de la comunión con los santos, y la bondad mostrada por los amigos. Los cristianos de Roma estaban tan lejos de avergonzarse por Pablo, o de tener miedo de reconocerlo porque él era un prisionero, que tuvieron más cuidado en mostrarle respeto. Tuvo mucho consuelo con esto. Y, si nuestros amigos son buenos con nosotros, Dios lo ha puesto en sus corazones y debemos dar a Él la gloria. Cuando vemos, aún en el extranjero, a los que llevan el nombre de Cristo, temen a Dios y le sirven, debemos elevar nuestros corazones al cielo en acción de gracias. ¡Cuántos hombres grandes han hecho su entrada en Roma, coronados y llevados en triunfo, siendo realmente plagas para el mundo! Pero he aquí a un hombre bueno que hace su entrada en Roma encadenado como pobre cautivo, siendo para el mundo una bendición más grande que cualquier otro humano. ¿No basta esto para dejar de pavonearnos por el favor mundano? -Esto puede animar a los prisioneros de Dios, porque Él puede darles favor ante los ojos de los que los llevan presos. Cuando Dios no libra pronto a su pueblo de la esclavitud, de todos modos se las hace ligera o los calma mientras están sometidos a ella, y tienen razón para estar agradecidos.</p>
<br/>
<p class="text-justify">Vv. 17-22.Fue para honra de Pablo que los que examinaron su caso, lo exoneraran. En su apelación no procuró acusar a su nación, sino sólo aclarar su condición.
El cristianismo verdadero establece lo que es de interés común para toda la humanidad, y no se edifica sobre las opiniones estrechas ni sobre intereses privados. No apunta a ningún beneficio o ventaja mundana, pero todas sus ganancias son espirituales y eternas. La suerte de la santa religión de Cristo es, y siempre ha sido, que hablen en contra de ella. Obsérvese en toda ciudad y pueblo donde se enaltezca a Cristo como el único Salvador de la humanidad, y donde la gente es llamada a seguirlo a la vida nueva, y nótese que aún son tratados de secta, de partido, y se reprocha a los que se entregan a Cristo. Y este es el trato que recibirán con seguridad, mientras haya un hombre impío sobre la tierra.</p>
<br/>
<p class="text-justify">Vv. 23-31.Pablo persuadió a los judíos acerca de Jesús. Algunos fueron trabajados por la palabra y otros, endurecidos; algunos recibieron la luz, y otros cerraron sus ojos contra ella. Este ha sido siempre el efecto del evangelio. Pablo se separó de ellos observando que el Espíritu Santo había descrito bien el estado de ellos. Todos los que oyen el evangelio, sin obedecerlo, tiemblen ante su sino, porque, ¿quién los sanará si Dios no? -Los judíos razonaron mucho entre ellos, después. Muchos de los que tienen un gran razonamiento no razonan correctamente. Hallan defectuosas las opiniones de unos y otros, pero no se rinden a la verdad. Ni tampoco los convencerá el razonamiento de los hombres, si la gracia de Dios no les abre el entendimiento. Mientras nos dolemos por los desdeñosos, debemos regocijarnos que la salvación de Dios sea enviada a otros que la recibirán; si somos de ese grupo, debemos estar agradecidos de Aquel que nos ha hecho diferir. El apóstol se adhirió a su principio de no conocer ni predicar otra cosa sino a Cristo, y éste crucificado. Cuando los cristianos son tentados por su ocupación principal, deben retrotraerse con esta pregunta, ¿qué tiene que ver esto con el Señor Jesús? ¿Qué tendencia hay en eso que nos lleve a Él y nos mantenga caminando en Él? El apóstol no se predicaba a sí mismo, sino a Cristo y no se avergonzaba del evangelio de Cristo.
Aunque a Pablo lo pusieron en una condición muy estrecha para ser útil, no se sintió perturbado por ella. Aunque no era una puerta ancha la que se le abrió a él, sin embargo, no toleró que nadie la cerrara; y para muchos era una puerta eficaz, de modo que hubo santos hasta en la casa de Nerón, Filipenses iv, 22. También de Filipenses i, 13, aprendemos cómo Dios pasa por alto la prisión de Pablo para el avance del evangelio. Y no sólo los residentes de Roma, sino toda la iglesia de Cristo, hasta el día presente, y en el rincón más remoto del planeta, tienen mucha razón para bendecir a Dios porque él fuera detenido como prisionero durante el período más maduro de su vida cristiana. Fue desde su prisión, probablemente encadenado mano a mano con el soldado que lo custodiaba, que el apóstol escribió las epístolas a los Efesios, Filipenses, Colosenses, y Hebreos; estas epístolas muestran, quizá más que cualesquiera otras, el amor cristiano con que rebosaba su corazón, y la experiencia cristiana con que estaba llena su alma.
El creyente de la época actual puede tener menos triunfo y menos gozo celestial que el apóstol, pero todo seguidor del mismo Salvador está igualmente seguro de estar a salvo y en paz al final. Procuremos vivir más y más en el amor del Salvador; trabajar para glorificarle con toda acción de nuestra vida; y con toda seguridad por su poder, estaremos entre los que ahora vencen a sus enemigos; y por su gracia gratuita y misericordia, en el más allá estaremos en la compañía bendita que se sentará con Él en su trono, así como Él venció y está sentado en el trono de su Padre, a la diestra de Dios para siempre jamás.</p>
<br/>




</div>
