<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 21</h2>
<p class="text-justify">Vv. 1-7.Debemos reconocer la providencia cuando nos salen bien las cosas. Dondequiera que fuera Pablo, preguntaba cuántos discípulos había ahí y los buscaba. Previendo sus problemas, por amor a él, y preocupación por la iglesia, ellos pensaron, equivocadamente, que sería más para la gloria de Dios que siguiera libre, pero su celo para disuadirlo volvió más ilustre su santa resolución. Él nos ha enseñado con el ejemplo y por la regla, a orar sin cesar. El último adiós de ellos fue endulzado con oración.</p>
<br/>
<p class="text-justify">Vv. 8-18.Pablo había sido expresamente advertido de sus problemas para que, cuando llegaran, no fueran sorpresa ni terror para él. Debemos darle el mismo uso a la noticia general que se nos da de que debemos entrar al reino de Dios a través de mucha tribulación. El llanto de ellos empezó a debilitar y desanimar la resolución de ellos. ¿No nos dijo nuestro Maestro que tomemos nuestra cruz? Para él fue un problema que ellos lo presionaran con tanta insistencia para hacer aquello con que no podía satisfacerlos sin dañar su propia conciencia. Cuando vemos que se acercan problemas no sólo nos corresponde decir, debe cumplirse la voluntad del Señor, y no hay más remedio, sino que se cumpla la voluntad del Señor, porque su voluntad es su sabiduría y Él hace todo conforme a su consejo. Debe apaciguar nuestro pesar que se cumple la voluntad del Señor cuando llega un problema; debe silenciar nuestros temores cuando lo vemos venir que se cumplirá la voluntad del Señor, y debemos decir: Amén, que se cumpla .
Honroso es ser un discípulo viejo de Jesucristo, haber sido capacitado por la gracia de Dios para seguir por largo tiempo en el curso del deber, constante en la fe, creciendo más y más experimentado a una buena vejez. Uno debiera optar por habitar con estos discípulos viejos, porque la multitud de sus años enseñará sabiduría.
Muchos hermanos de Jerusalén recibieron alegremente a Pablo. Pensamos que, quizá si lo tuviéramos con nosotros, lo recibiríamos con gozo, pero no lo haríamos si, teniendo su doctrina, no la recibimos con gozo.</p>
<br/>
<p class="text-justify">Vv. 19-26.Pablo atribuye todo su éxito a Dios y a Dios da la alabanza. Dios le había honrado más que a ninguno de los apóstoles, aunque ellos no lo envidiaban, pero por el contrario, glorificaban al Señor. Ellos no podían hacer más que exhortar a Pablo para que siguiera alegremente en su obra. Santiago y los ancianos de la iglesia de Jerusalén, le pidieron a Pablo que satisficiera a los judíos creyentes con el cumplimiento de algún requisito de la ley ceremonial. Ellos pensaron que era prudente que se conformara hasta ese punto. Fue una gran debilidad querer tanto la sombra cuando había llegado la sustancia.
La religión que Pablo predicaba no tendía a destruir la ley, sino a cumplirla. Él predicaba a Cristo, el fin de la ley por la justicia, el arrepentimiento y la fe, con que tenemos que usar mucho la ley. La debilidad y la maldad del corazón humano aparecen fuertemente cuando consideramos cuántos, siendo discípulos de Cristo, no tuvieron debida consideración hacia el ministro más eminente que haya vivido jamás. La excelencia de su carácter ni el éxito con que Dios bendijo sus labores no pudieron ganarle la estima y el afecto de ellos, que veían que él no rendía el mismo respeto que ellos a las observancias ceremoniales. ¡Cuán cuidadosos debemos ser con los prejuicios! Los apóstoles no estuvieron libres de culpa en todo lo que hicieron, y sería difícil defender a Pablo de la acusación de ceder demasiado en esta materia. Vano es tratar de conseguir el favor de los zelotes o fanáticos de un partido. Este cumplimiento de Pablo no sirvió, por lo mismo con que esperaba apaciguar a los judíos, los provocó y lo metió en problemas, pero el Dios omnisciente pasó por alto el consejo de ellos y el cumplimiento de Pablo, para servir un propósito mejor de lo que se pensaba. Era vano tratar de complacer a los hombres que no se agradarían con nada sino la destrucción del cristianismo. Es más probable que la integridad y la rectitud nos preserven más que los cumplimientos mentirosos. Esto debiera advertirnos para no presionar a los hombres para que hagan lo contrario a su propio juicio por complacernos.</p>
<br/>
<p class="text-justify">Vv. 27-40.En el templo, donde Pablo debiera haber estado protegido por ser lugar seguro, fue violentamente atacado. Lo acusaron falsamente de mala doctrina y de mala costumbre contra las ceremonias mosaicas. No era nada nuevo para quienes tienen intenciones honestas y actúan conforme a la regla, que les acusen de cosas que no conocen y en las que nunca pensaron. Común es para el sabio y bueno que la gente mala le acuse de aquello con que creyeron agradarlos.
Dios suele hacer que protejan a su pueblo los que no los quieren, sino sólo se compadecen de los que sufren y se preocupan por la paz pública. Véase aquí con qué nociones falsas y equivocadas de la gente buena y de los buenos ministros se van muchos. Pero Dios interviene oportunamente para asegurar a sus siervos contra los hombres malos e irracionales; y les da oportunidades para que hablen defendiendo el Redentor y difundiendo ampliamente su glorioso evangelio.</p>
<br/>




</div>
