<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 24</h2>
<p class="text-justify">Vv. 1-9.Aquí vemos la desdicha de los grandes hombres, y es una gran desgracia que le alaben sus servicios más allá de toda medida, sin que nunca se le hable fielmente de sus faltas; por eso, se endurecen y animan en el mal, como Félix. A los profetas de Dios se les acusó de ser los perturbadores de la tierra, y a nuestro Señor Jesucristo, de pervertir a la nación; las mismas acusaciones fueron formuladas contra Pablo. Las malas pasiones egoístas de los hombres les impelen adelante y las gracias y el poder del habla han sido usados frecuentemente para dirigir mal y prejuiciar a los hombres contra la verdad. ¡Cuán diferentes serán los caracteres de Félix y Pablo en el día del juicio, según son representados en el discurso de Tértulo! Que los cristianos no valoren el aplauso y ni se turben por los reproches de los hombres impíos, que presentan casi como dioses a los más viles de la raza humana, y como pestes y promotores de sedición a los excelentes de la tierra.</p>
<br/>
<p class="text-justify">Vv. 10-21.Pablo da un justo relato de sí mismo que lo exonera de delito e igualmente muestra la verdadera razón de la violencia contra él. No seamos sacados de un camino bueno porque tenga mala fama. Al adorar a Dios muy consolador es considerarle como el Dios de nuestros padres, sin establecer ninguna otra regla de fe o conducta que no sean las Escrituras. Esto muestra aquí que habrá una resurrección para el juicio final. Los profetas y sus doctrinas tenían que probarse por sus frutos.
La mira de Pablo era tener una conciencia desprovista de ofensa. Su interés y finalidad era abstenerse de muchas cosas y abundar en todos los momentos en los ejercicios de la religión con Dios y con el hombre. Si nos culpan de ser más celosos en las cosas de Dios que nuestro prójimo, ¿qué contestamos? ¿Nos encogemos ante la acusación? ¡Cuántos hay en el mundo que prefieren ser acusados de cualquier debilidad, sí, hasta de maldad, y no de un sentimiento de amor, fervoroso y anhelante por el Señor Jesucristo, y de consagración a su servicio! ¿Pueden los tales pensar que los confesará cuando venga en su gloria y ante los ángeles de Dios? Si hay una visión placentera para el Dios de nuestra salvación, y una visión ante la cual se regocijan los ángeles, es contemplar a un seguidor devoto del Señor, aquí en la tierra, que reconoce que es culpable, si fuese crimen, de amar con todo su corazón, alma, mente y fuerza al Señor que murió por él. No se puede quedar callado al ver que se desprecia la palabra de Dios o escucha que se profana su nombre. Este se arriesgará, antes bien, al ridículo y al odio del mundo, antes que causar enojo a ese ser bondadoso cuyo amor es mejor que la vida.</p>
<br/>
<p class="text-justify">Vv. 22-27.El apóstol razona acerca de la naturaleza y las obligaciones de la justicia, la templanza y del juicio venidero, demostrando así al juez opresor y a su amante disoluta la necesidad que tenían ellos del arrepentimiento, el perdón y la gracia del evangelio. La justicia en relación a nuestra conducta en la vida, particularmente con referencia al prójimo; la templanza, al estado y gobierno de nuestras almas con relación a Dios. El que no se ejercita en estas no tiene ni la forma ni el poder de la piedad y debe ser abrumado con la ira divina en el día de la manifestación de Dios.
La perspectiva del juicio venidero es suficiente para hacer que tiemble el corazón más recio. Félix tembló, pero eso fue todo. Muchos de los que se asombran con la palabra de Dios, no son cambiados por ella. Muchos temen las consecuencias del pecado pero continúan amándolo y practicándolo. Las demoras son peligrosas en los asuntos de nuestras almas. Félix postergó este asunto para un momento más propicio, pero no hallamos que haya llegado nunca el momento más conveniente. Considérese que es ahora el tiempo aceptadble: escucha hoy la voz del Señor. Él tuvo apuro para dejar de oír la verdad. ¡Había un asunto más urgente para él que reformar su conducta o más importante que la salvación de su alma! Los pecadores empiezan, a menudo, como un hombre que despierta de su sueño por un ruido fuerte pero pronto vuelve a hundirse en su sopor habitual. No os dejéis engañar por las apariencias ocasionales en nosotros mismos o en el prójimo. Por sobre todo no juguemos con la palabra de Dios. ¿Esperamos que se ablanden nuestros corazones al ir avanzando en la vida o que disminuya la influencia del mundo? ¿No corremos en este momento el peligro de perdernos para siempre? Ahora es el día de salvación; mañana puede ser demasiado tarde.</p>
<br/>




</div>
