<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 16</h2>
<p class="text-justify">Vv. 1-5.La Iglesia bien puede esperar mucho servicio de ministros jóvenes que tengan el mismo espíritu que Timoteo. Sin embargo, cuando los hombres no se sujetan en nada ni se obligan a nada, parece que faltaran los principales elementos del carácter cristiano; y hay mucha razón para creer que no enseñarán con éxito las doctrinas y los preceptos del evangelio. Siendo el designio del decreto dejar de lado la ley ceremonial, y sus ordenanzas en la carne, los creyentes fueron confirmados en la fe cristiana porque estableció una forma espiritual de servir a Dios, adecuada para la naturaleza de Dios y del hombre. Así, la Iglesia crecía diariamente en número.</p>
<br/>
<p class="text-justify">Vv. 6-15.El itinerario de los ministros y su labor en la dispensación de los medios de gracia están sometidos particularmente a la conducción y dirección divina. Debemos seguir la providencia y cualquier cosa que procuremos hacer, si no nos permite, debemos someternos y creer que es para mejor.
La gente necesita mucha ayuda para sus almas y es su deber buscarla e invitar de entre los ministros a los que puedan ayudarles. Los llamados de Dios deben cumplirse con presteza.
Los adoradores de Dios deben tener, si es posible, una asamblea solemne en el día de reposo. Si no tenemos sinagoga debemos agradecer los lugares más privados y recurrir a ellos sin abandonar las reuniones según sean nuestras oportunidades.
Entre los oyentes de Pablo había una mujer de nombre Lidia. Tenía un trabajo honesto que el historiador registra para elogio de ella. Aunque tenía que desempeñar ese trabajo, hallaba tiempo para aprovechar las ventajas para su alma. No nos disculpará de los deberes religiosos decir, tenemos un negocio que administrar, porque ¿no tenemos también un Dios que servir, y almas que cuidar? La religión no nos saca de nuestros negocios en el mundo, pero nos dirige en ellos. El orgullo, el prejuicio y el pecado dejan fuera las verdades de Dios hasta que su gracia les hace camino en el entendimiento y los afectos; solo el Señor te puede abrir el corazón para que recibas y creas su palabra. Debemos creer en Jesucristo; no hay acceso a Dios como Padre sino por el Hijo como Mediador.</p>
<br/>
<p class="text-justify">Vv. 16-24.Aunque es el padre de las mentiras Satanás, declara las verdades más importantes cuando por ellas puede servir sus propósitos. Mucha maldad hacen a los siervos verdaderos de Cristo los impíos y falsos predicadores del evangelio, que son confundidos con aquellos por los observadores indiferentes. Quienes hacen el bien sacando del pecado a los hombres, pueden esperar ser insultados como alborotadores de la ciudad. Mientras enseñen a los hombres a temer a Dios, a creer en Cristo, a abandonar el pecado y llevar vidas santas, serán acusados de enseñar malas costumbres.</p>
<br/>
<p class="text-justify">Vv. 25-34.No son pocos ni pequeños los consuelos de Dios para sus siervos que sufren. ¡Cuánto más felices son los cristianos verdaderos que sus prósperos enemigos! Desde lo profundo y desde las tinieblas debemos clamar a Dios. No hay lugar, no hay tiempo que sean malos para orar si el corazón va a ser elevado a Dios. Ningún problema, por penoso que sea, debe impedirnos alabar. Se demuestra que el cristianismo es de Dios en que nos obliga a ser rectos con nuestra vida.
Pablo gritó fuerte para que el carcelero escuchara, y hacerle obedecer, diciendo: No te hagas daño. Todas las advertencias de la palabra de Dios contra el pecado y todas sus apariencias, y todas sus aproximaciones, tienen esta tendencia. Hombre, mujer, no te hagas daño; no te hieras, porque nadie más puede herirte; no peques, porque nada puede herirte sino eso. Aun con referencia al cuerpo se nos advierte contra los pecados que lo dañan. La gracia que convierte cambia el lenguaje de la gente al de la buena gente y de los buenos ministros. -¡Qué grave es la pregunta del carcelero! Su salvación se convierte en su gran interés; lo que yace más cerca de su corazón es lo que antes distaba más de sus pensamientos. Está preocupado por su alma preciosa. Los que están enteramente convencidos de su pecado y verdaderamente interesados en su salvación, se entregarán a Cristo. Aquí está el resumen de todo el evangelio, el pacto de gracia en pocas palabras: Cree en el Señor Jesucristo y serás salvo, tú y tu casa.
El Señor bendijo tanto la palabra que el carcelero fue de inmediato ablandado y humillado. Los trató con bondad y compasión, y al profesar fe en Cristo fue bautizado en ese nombre, con su familia. El Espíritu de gracia obró una fe tan fuerte en ellos, que disipó toda duda ulterior; y Pablo y Silas supieron por el Espíritu, que Dios había hecho una obra en ellos. Cuando los pecadores así se convierten, amarán y honrarán a los que antes despreciaban y odiaban, y procurarán aminorar los sufrimientos que antes deseaban acrecentar. Cuando los frutos de la fe empiezan a aparecer, los terrores serán sustituidos por la confianza y el gozo en Dios.</p>
<br/>
<p class="text-justify">Vv. 35-40.Aunque Pablo estaba dispuesto a sufrir por la causa de Cristo, y sin ningún deseo de vengarse, prefirió no partir llevando la acusación equivocada de haber merecido un castigo, por tanto, pidió ser despedido de manera honorable. No fue una mera cuestión de honor en que el apóstol insistió, sino de justicia, y no para él tanto como para su causa. Cuando se da la disculpa apropiada, los cristianos nunca deben expresar enojo personal ni insistir estrictamente en las reparaciones personales. El Señor los hará más que vencedores en todo conflicto; en lugar de ser aplastados por sus sufrimientos, ellos se volverán consoladores de sus hermanos.</p>
<br/>




</div>
