<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 20</h2>
<p class="text-justify">Vv. 1-6.Los tumultos o la resistencia pueden constreñir al cristiano para irse de su lugar de trabajo o cambiar su propósito, pero su obra y su placer serán los mismos dondequiera que vaya. Pablo pensó que valía la pena emplear cinco días para ir a Troas, aunque tuvo que estar siete días, pero sabía, y así debiéramos nosotros, redimir aun el tiempo de viaje haciendo que se volviera en algo provechoso.</p>
<br/>
<p class="text-justify">Vv. 7-12.Aunque los discípulos leían, y meditaban, oraban y cantaban a solas, y así mantenían su comunión con Dios, de todos modos se reunían para adorar a Dios y así mantener la comunión de unos con otros. Se reunían en el primer día de la semana, el día del Señor. Debe ser observado religiosamente por todos los discípulos de Cristo. Al partir el pan se conmemora no sólo el cuerpo de Cristo partido por nosotros, para ser sacrificio por nuestros pecados; representa al cuerpo de Cristo partido para nosotros como alimento y fiesta para nuestras almas. En los primeros tiempos se acostumbraba a recibir la cena del Señor cada día del Señor, celebrando así la memoria de la muerte de Cristo.
Pablo predicó en esta asamblea. La predicación del evangelio debe ir unida a los sacramentos. Ellos estaban dispuestos a oír, él vio que era así, y alargó su sermón hasta la medianoche.
Dormirse cuando se escucha la palabra es mala señal, señal de poca estima de la palabra de Dios. Debemos hacer lo que podamos para no dormirnos; no dormirnos sino lograr que nuestro corazón sea afectado por la palabra que oímos de forma que echemos lejos el sueño. La enfermedad requiere ternura, pero el desprecio merece severidad. Interrumpió la predicación del apóstol, pero para confirmar su predicación.
Eutico fue devuelto a la vida. Como no sabían cuando tendrían nuevamente la compañía de Pablo, la aprovecharon lo mejor que pudieron y reconocieron que perder una noche de sueño era bueno para tal propósito. ¡Con cuánta rareza se pierden horas de reposo con el propósito de la devoción, pero con cuánta frecuencia se hace por la mera diversión o jolgorio pecaminoso! ¡Tanto cuesta que la vida espiritual florezca en el corazón del hombre y tan natural es que allí florezcan las costumbres carnales!</p>
<br/>
<p class="text-justify">Vv. 13-16.Pablo se apresuró a partir hacia Jerusalén, pero trató de hacer el bien en el camino, cuando iba de lugar en lugar, como debe hacer todo hombre bueno. Muy a menudo debemos contrariar nuestra voluntad y la de nuestros amigos al hacer la obra de Dios; no debemos perder tiempo con ellos cuando el deber nos llama a otro lado.</p>
<br/>
<p class="text-justify">Vv. 17-27.Los ancianos sabían que Pablo no era hombre interesado en sí mismo ni manipulador. Los que sirven al Señor en algún oficio en forma aceptable y provechosa para el prójimo, deben hacerlo con humildad. Él era un predicador simple , uno que decía el mensaje para que se entendiera. Él era un predicador poderoso , predicaba el evangelio como testimonio a ellos si lo recibían, pero como testimonio contra ellos si lo rechazaban. Era un predicador de provecho , que tenía la mira de informar sus juicios y reformar sus corazones y vidas. Era un predicador sufrido , muy esforzado en su obra. Era un predicador fiel , que no se reservaba los reproches cuando eran necesarios, ni dejaba de predicar la cruz. Era un predicador verdaderamente cristiano evangélico , no predicaba de temas o nociones dudosas, ni de los asuntos de estado o el gobierno civil; predicaba la fe y el arrepentimiento. No puede darse un mejor resumen de estas cosas sin las cuales no hay salvación: el arrepentimiento para con Dios, y la fe en nuestro Señor Jesucristo, con sus frutos y efectos. Ningún pecador puede escapar sin ellos, y nadie quedará fuera de la vida eterna con estos. Que no se piense que Pablo se fue de Asia por miedo a la persecución; él estaba esperando problemas, pero resolvió seguir adelante bien seguro de que era por mandato divino. Gracias a Dios que no sabemos las cosas que nos sucederán durante el año, la semana, o el día que ha empezado. Para el hijo de Dios basta con saber que su fuerza será igual a su día. No sabe ni quiere saber qué le traerá el día por delante. Las influencias poderosas del Espíritu Santo enlazan al cristiano verdadero con su deber. Aunque espere persecución y aflicción, el amor de Cristo le constriñe a seguir. Ninguna de estas cosas sacó a Pablo de su tarea; no le privaron de su consuelo. La actividad de nuestra vida es proveer para una muerte gozosa.
Creyendo que esta era la última vez que le verían, él apela de su integridad. Les había predicado todo el consejo de Dios. Al predicarles puramente el evangelio, se los había predicado, así, completo; él hizo fielmente su obra ya fuera que los hombres lo soportaran o lo rechazaran.</p>
<br/>
<p class="text-justify">Vv. 28-38.Si el Espíritu Santo ha hecho ministros supervisores del rebaño, esto es, pastores, ellos deben ser leales a su cometido. Que consideren el interés de su Maestro por el rebaño encargado a su cuidado: es la Iglesia que Él compró con su sangre. La sangre era la suya en cuanto Hombre; tan íntima es la unión de la naturaleza divina y la humana que aquí es llamada sangre de Dios, porque era la sangre de Aquel que es Dios. Eso le confiere tal valor y dignidad como para rescatar a los creyentes de todo mal y adquirir todo lo bueno. Pablo habló de sus almas con afecto y preocupación.
Estaban muy preocupados por lo que sería de ellos. Pablo los guía a mirar a Dios con fe, y los encomienda a la palabra de la gracia de Dios, no sólo como fundamento de su esperanza y su fuente de gozo, sino como la regla de su andar. Los cristianos más maduros son capaces de crecer y hallarán que la palabra de gracia ayuda a su crecimiento. Como los que no están santificados no pueden ser huéspedes bienvenidos para el santo Dios, así el cielo no será cielo para ellos, pero está asegurado para todos los que nazcan de nuevo, y en quienes se ha renovado la imagen de Dios, puesto que el poder omnipotente y la verdad eterna así lo hacen. Él se pone a sí mismo como ejemplo para ellos de no preocuparse por las cosas de este mundo actual; hallarán que esto les ayudara para un paso cómodo a través de él. Podría parecer un dicho duro; por lo que Pablo agrega un dicho de su Maestro, que desea que siempre recuerden: “Más bienaventurado es dar que recibir”, parece que eran palabras usadas a menudo con sus discípulos. La opinión de los hijos de este mundo es contraria a esto; ellos temen dar a menos que esperen recibir. La ganancia clara es para ellos la cosa más bendita que pueda haber; pero Cristo nos dice qué es más bienaventurado, más excelente. Nos hace más como Dios, que da a todos y recibe de nadie; y al Señor Jesús que andaba haciendo el bien. Que también esté en nosotros el sentir que había en Cristo Jesús.
Cuando los amigos se separan es bueno que se separen orando. Los que exhortan y oran, los unos por los otros, pueden tener muchas temporadas de llanto y separaciones dolorosas, pero se reunirán ante el trono de Dios para nunca más separarse. Para todos fue consuelo que la presencia de Cristo fuera con él y se quedara con ellos.</p>
<br/>




</div>
