<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 1</h2>
<p class="text-justify">Vv. 1-5.Nuestro Señor dijo a los discípulos la obra que tenían que hacer. Los apóstoles se reunieron en Jerusalén, habiéndoles mandado Cristo que no se fueran de ahí pero esperasen el derramamiento del Espíritu Santo. Esto sería un bautismo por el Espíritu Santo, que les daría poder para hacer milagros e iba a iluminar y a santificar sus almas. Esto confirma la promesa divina y nos anima para depender de ella, porque la oímos de Cristo y en Él todas las promesas de Dios son sí y amén.</p>
<br/>
<p class="text-justify">Vv. 6-11.Se apresuraron para preguntar lo que su Maestro nunca les mandó ni les animó a buscar. Nuestro Señor sabía que su ascensión y la enseñanza del Espíritu Santo pronto pondrían fin a esas expectativas y, por tanto, sólo los reprendió; pero esto es una advertencia para su Iglesia de todos los tiempos: cuidarse de desear conocimientos prohibidos. Había dado instrucciones a sus discípulos para que cumplieran su deber, tanto antes de su muerte y desde su resurrección, y este conocimiento basta para el cristiano. Basta que Él se haya propuesto dar a los creyentes una fuerza igual a sus pruebas y servicios; que, bajo el poder del Espíritu Santo, sean de una u otra manera testigos de Cristo en la tierra, mientras en el cielo Él cuida con perfecta sabiduría, verdad y amor de sus intereses.
Cuando nos quedamos mirando y ocupados en nimiedades, que el pensar en la segunda venida de nuestro Maestro nos estimule y despierte: cuando nos quedemos mirando y temblando, que nos consuelen y animen. Que nuestra expectativa así sea constante y jubilosa, poniendo diligencia en ser hallados irreprensibles por Él.</p>
<br/>
<p class="text-justify">Vv. 12-14.Dios puede hallar lugares de refugio para su pueblo. Ellos suplicaron. Todo el pueblo de Dios es pueblo de oración. Ahora era el momento de los problemas y peligros para los discípulos de Cristo; pero si alguien está afligido, ore; eso acallará sus preocupaciones y temores. Ahora tenían una gran obra que hacer y, antes que la empezaran, oraron fervientemente a Dios pidiendo su presencia. Esperando el derramamiento del Espíritu y abundando en oración. Los que están orando son los que están en mejor situación para recibir bendiciones espirituales. Cristo había prometido enviar pronto al Espíritu Santo; esa promesa no tenía que eliminar la oración, sino vivificarla y alentarla. Un grupo pequeño unido en amor, de conducta ejemplar, ferviente para orar, y sabiamente celoso para el progreso de la causa de Cristo, probablemente crezca con rapidez.</p>
<br/>
<p class="text-justify">Vv. 15-26.La gran cosa de la que los apóstoles debían atestiguar ante el mundo era la resurrección de Cristo, porque era la gran prueba de que Él es el Mesías, y el fundamento de nuestra esperanza en Él. Los apóstoles fueron ordenados, no para asumir dignidades y poderes mundanales, sino para predicar a Cristo y el poder de su resurrección.
Se efectuó una apelación a Dios: “Tú, Señor, que conoces los corazones de todos”, cosa que nosotros no, y es mejor que ellos conozcan el suyo. Es adecuado que Dios escoja a sus siervos y, en la medida que Él, por las disposiciones de su providencia o los dones del Espíritu, muestra a quien ha escogido, o qué ha escogido para nosotros, debemos adecuarnos a su voluntad. Reconozcamos su mano en la determinación de cada cosa que nos sobrevenga, especialmente en alguna comisión que nos sea encargada.</p>
<br/>




</div>
