<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Hechos 19</h2>
<p class="text-justify">Vv. 1-7.Pablo halló en Éfeso a algunas personas religiosas que consideraban a Jesús como el Mesías. No habían sido llevados a esperar los poderes milagrosos del Espíritu Santo, ni les habían informado que el evangelio era, especialmente, la ministración del Espíritu. Sin embargo, parecían dispuestos para recibir bien esa noticia. Pablo les demuestra que Juan nunca pretendió que los que bautizaba, se quedaran hasta ahí, pero, les decía que debían creer en Aquel que vendría después de Él, esto es, en Cristo Jesús. Ellos aceptaron, agradecidos, esa revelación y fueron bautizados en el nombre del Señor Jesús.
El Espíritu Santo descendió a ellos de modo sorprendente y sobrecogedor: hablaron en lenguas y profetizaron, como hacían los apóstoles y los primeros convertidos gentiles. Aunque ahora no esperamos poderes milagrosos, todos los que profesan ser discípulos de Cristo deben ser llamados a que examinen si han recibido el sello del Espíritu Santo con sus influencias santificadoras, para la sinceridad de su fe. Muchos no parecen haber escuchado que hay un Espíritu Santo, y muchos consideran que es una ilusión todo lo que se dice de su gracia y sus consolaciones. De los tales puede preguntarse con propiedad: “¿En qué, pues, fuisteis bautizados?”Porque, evidentemente, desconocen el significado de este signo externo del que dependen tanto.</p>
<br/>
<p class="text-justify">Vv. 8-12.Cuando las discusiones y las persuasiones sólo endurecen a los hombres en la incredulidad y la blasfemia, debemos separarnos, nosotros y otros, de esa impía compañía. Agradó a Dios confirmar la enseñanza de estos santos varones de antaño para que si sus oyentes no les creían a ellos, pudieran creer por sus obras.</p>
<br/>
<p class="text-justify">Vv. 13-20.Era corriente, en especial entre los judíos, que las personas trataran de expulsar espíritus malignos. Si resistimos al diablo por fe en Cristo, él huirá de nosotros, pero si pensamos en resistirle usando el nombre de Cristo, o sus obras como conjuro o encantamiento, Satanás nos vencerá. Donde haya verdadera contrición del pecado, habrá una libre confesión de pecado a Dios en toda oración; y confesión a la persona que hayamos ofendido, cuando el caso así lo requiera. Si la palabra de Dios ha prevalecido entre nosotros, con toda seguridad que muchos libros licenciosos, infieles y malos serán quemados por sus dueños. ¿Estos convertidos de Éfeso no se levantarán en juicio contra los profesantes que trafican con tales obras por amor a una ganancia o que se permiten tener tales libros? Si deseamos ser honestos en la gran obra de la salvación, debemos renunciar a toda empresa y deseo que estorbe el efecto del evangelio en la mente o que afloje su dominio en el corazón.</p>
<br/>
<p class="text-justify">Vv. 21-31.La gente que venía desde lejos a rendir culto en el templo de Éfeso, compraba pequeños santuarios de plata o modelos del templo, para llevárselos a casa. Nótese aquí cómo los artesanos se aprovechan de la superstición de la gente, y sirven sus propósitos mundanos con ello. Los hombres son celosos de aquello por lo cual obtienen sus riquezas, y muchos se ponen en contra del evangelio de Cristo porque saca a los hombres de todas las malas artes, por mucha que sea la ganancia que obtengan con ellas. Hay personas que defienden lo que es más groseramente absurdo, irracional y falso con que sólo tenga de su lado el interés mundano, como en este caso en que aquellos eran dioses hechos con sus propias manos. Toda la ciudad estaba llena de confusión, que es el efecto común y natural del celo por la religión falsa.
El celo por el honor de Cristo, y el amor por los hermanos, exhorta a los creyentes celosos a correr peligros. A menudo surgen amigos de entre aquellos que son ajenos a la verdadera religión, pero que han visto la conducta honesta y coherente de los cristianos.</p>
<br/>
<p class="text-justify">Vv. 32-41.Los judíos pasaron adelante en este tumulto. Los que así se preocupan de distinguirse de los siervos de Cristo ahora, temiendo ser confundidos con ellos, tendrán su correspondiente condena en el gran día. Uno que tenía autoridad acalló, por fin, el barullo. Muy buena regla en todo tiempo, tanto para los asuntos públicos como privados, es no apresurarse a actuar, sino tomarse tiempo para pensar y mantener siempre controladas nuestras pasiones. Debemos conservar la serenidad y no hacer nada con aspereza, ni precipitación de lo que tengamos que arrepentirnos después. Los métodos habituales de la ley siempre deben detener los tumultos populares, cosa que será así en las naciones bien gobernadas. La mayoría de la gente se maravilla ante los juicios de los hombres más que del juicio de Dios. ¡Qué bueno sería si acalláramos de este modo nuestras pasiones y apetitos desordenados, considerando la cuenta que debemos rendir dentro de poco al Juez de cielo y tierra! Nótese cómo mantiene la paz pública la providencia suprema de Dios, por un poder inexplicable sobre los espíritus de los hombres. Así se mantiene al mundo con cierto orden y se frena a los hombres para que no se coman unos a otros. Apenas miramos a nuestro alrededor sin ver hombres que se comportan como Demetrio y los artífices. Contender con bestias salvajes es tan seguro como con los hombres enfurecidos por el celo partidario y la codicia desencantada, que piensan que todos los argumentos quedan sin respuesta, cuando han mostrado que ellos se enriquecen por medio de las prácticas a las cuales surgió oposición. Cualquiera sea el bando que este espíritu adopte en las disputas religiosas, o cualquiera sea el nombre que tome, es tan mundano que debe ser repudiado por todos los que guardan la verdad y la piedad. No desfallezcamos: el Señor de lo alto es más poderoso que el ruido de muchas aguas; Él puede aquietar la furia de la gente.</p>
<br/>




</div>
