<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Isaías 8</h2>
<p class="text-justify">Vv. 1-8.El profeta tiene que escribir en un rollo grande o sobre una estela de metal, unas palabras que significan: “El despojo se apresura, la presa se precipita”, señalando que el ejército asirio vendría veloz y haría mucho botín. Muy pronto las riquezas de Damasco y Samaria, ciudades entonces seguras y formidables, serían llevadas por el rey de Asiria.
El profeta argumenta con el prometido Mesías, que debería aparecer en la tierra en la plenitud del tiempo, y como Dios, la preservará en mientras tanto. Como un arroyo suave es símbolo apropiado de un gobierno suave, un torrente que anega todo representa a un conquistador y tirano. El éxito del invasor también se describe como ave de presa que extiende sus alas sobre toda la tierra.
Quienes rechazan a Cristo hallarán que lo que llaman libertad es la esclavitud más vil. Pero ningún enemigo sacará al creyente de la mano de Emanuel, ni le quitará su herencia celestial.</p>
<br/>
<p class="text-justify">Vv. 9-16.El profeta desafía a los enemigos de los judíos. Sus esfuerzos serán vanos y ellos mismos serán despedazados. Nos concierne en épocas de problemas vigilar todos los temores que nos llevan por rumbos torcidos en pos de nuestra propia seguridad. El temor de Dios del creyente preserva del inquietante temor al hombre. Si pensamos rectamente en la grandeza y la gloria de Dios, veremos restringido todo el poder de nuestros enemigos. El Señor, que será Santuario para quienes confían en Él, será la Roca de tropiezo y Roca de escándalo para quienes hacen de la criatura su temor y esperanza. Si las cosas de Dios para nosotros son ofensa, nos desharán. El apóstol cita esto a todos los que persisten en no creer el evangelio de Cristo, 1 Pedro ii, 8. El Emanuel crucificado, que fue y es piedra de tropiezo y Roca de escándalo para los judíos incrédulos, no lo es menos para los miles que son llamados cristianos. La predicación de la cruz es locura según su criterio; sus doctrinas y preceptos los ofenden.</p>
<br/>
<p class="text-justify">Vv. 17-22.El profeta anuncia que el Señor escondería su rostro, pero esperaría su regreso a favor de ellos. Aunque no constituyen señales milagrosas, los nombres de los hijos fueron monumentos de Dios, útiles para excitar la atención.
Los judíos incrédulos eran proclives a buscar consejo en caso de dificultades, e iban a diversas clases de adivinadores, a cuyas ceremonias necias y pecaminosos se alude. -¿Sabríamos nosotros buscar a nuestro Dios e ir a conocer su propósito? A la ley y al testimonio: porque ahí verás lo que es bueno y lo que requiere el Señor. Debemos hablar de las cosas de Dios con las palabras que nos enseñe el Espíritu Santo, y ser mandados por ellas. Para los que recurren a los espíritus y no consideran la ley y testimonio de Dios, habrá horror y miseria. Los que se alejan de Dios, se salen del camino de todo lo bueno, porque el afán es un pecado que es su propio castigo. Desesperan y no ven alivio cuando maldicen a Dios. Sus temores representan todo como aterrador. Los que cierran sus ojos contra la luz de la palabra de Dios, serán justamente dejados en tinieblas. Todas las desgracias que alguna vez sintieron o presenciaron en la tierra, son nada comparadas con las que abrumarán a los que dejan las palabras de Cristo para seguir sus ilusiones.</p>
<br/>




</div>
