<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Isaías 1</h2>
<p class="text-justify">Vv. 1-9.Isaías significa “la salvación del Señor”; nombre muy apropiado para este profeta que habla tanto de Jesús el Salvador y su salvación.
El pueblo profesante de Dios no sabía o no consideraba que ellos debían su vida y su bienestar al cuidado y bondad paternal de Dios. ¿Cuántos descuidan en los asuntos de su alma? No considerar lo que sabemos de religión nos daña tanto como la ignorancia de lo que deberíamos saber.
La iniquidad era universal. Aquí hay una comparación tomada de un cuerpo doliente y enfermo. La enfermedad amenaza ser mortal. Desde la planta de los pies a la cabeza; desde el campesino más bajo al mayor de los nobles, no hay salud, ni buen principio, ni religión, porque esa es la salud del alma. Nada sino culpa y corrupción; los tristes efectos de la caída de Adán. Este pasaje declara la depravación total de la naturaleza humana. Mientras el pecado persista sin arrepentimiento, nada se hace para sanar tales heridas y evitar sus efectos fatales.
Jerusalén estaba expuesta y desprotegida, como las chozas o refugios edificados para guardar fruta madura. Esto aun se ve en el Oriente, donde la fruta constituye gran parte de la comida estival de la gente.
Pero el Señor tenía un pequeño remanente de siervos piadosos en Jerusalén. Es por la misericordia de Jehová que nosotros no somos consumidos. La naturaleza mala está en cada uno de nosotros; sólo Jesús y su Espíritu santificador pueden restaurarnos a la salud espiritual.</p>
<br/>
<p class="text-justify">Vv. 10-15.Judea estaba desolada y sus ciudades, quemadas. Esto los despertó para llevar sacrificios y ofrendas, como si sobornaran a Dios para levantar el castigo y tener permiso para seguir en el pecado. Muchos que fácilmente se desprenden de bienes para ofrecer sacrificios no se convencen fácilmente que deben desprenderse de sus pecados. Confían en la pura formalidad como servicio que merece recompensa. Las más costosas devociones de los malos, sin la transformación completa del corazón y la vida, no son aceptables para Dios. No sólo no los acepta sino que los aborrece. Todo esto muestra que el pecado es muy odioso para Dios. Si nos comprometemos en pecados secretos o nos damos libertades ilícitas; si rechazamos la salvación de Cristo, nuestras oraciones mismas se vuelven abominación.</p>
<br/>
<p class="text-justify">Vv. 16-20.No sólo hemos de sentir dolor por el pecado cometido, sino romper la práctica. Debemos hacer, no quedarnos ociosos. Debemos hacer el bien que el Señor nuestro Dios pide. Es claro que los sacrificios de la ley no podían expiar ni siquiera uno, los delitos superficiales de la nación. Pero, bendito sea Dios, hay una Fuente abierta en la cual pueden ser lavados los pecados de toda edad y rango. Aunque nuestros pecados hayan sido como la grana y el carmesí, de tintura doble y profunda, primero en la lana de la corrupción original y, luego, en los muchos hilos de la transgresión presente; aunque a menudo nos hemos hundido en el pecado, por muchos deslices, de todos modos la misericordia que perdona lavará la mancha, Salmo li, 7.
Debieran tener toda la felicidad y el bienestar deseado. La vida y la muerte, el bien y el mal, están puestos delante nuestro. Oh, Señor, inclínanos a todos a vivir para tu gloria.</p>
<br/>
<p class="text-justify">Vv. 21-31.Ni las ciudades santas ni las reales son fieles a su comisión si la religión no permanece en ellos. La escoria puede brillar como plata y el vino mezclado con agua todavía puede tener el color del vino. Mucho por qué responder tienen los que no ayudan al oprimido, sino que lo oprimen. Los hombres pueden hacer mucho por medio de restricciones externas; pero sólo Dios obra eficazmente por la influencia de su Espíritu, como Espíritu de juicio.
El pecado es el peor cautiverio, la peor esclavitud.
La redención de la Sion espiritual, por la justicia y la muerte de Cristo y por su gracia poderosa, concuerda muy plenamente con lo que aquí se representa. Se amenaza con la destrucción extrema. Los judíos llegarían a ser como árbol quemado por el calor; como jardín sin agua, que en aquellos países cálidos pronto se seca. Así, pues, serán los que confían en ídolos o en brazo de carne. Hasta el hombre fuerte será como estopa; no sólo quebrantado y despedazada con prontitud, sino de combustión fácil. Cuando el pecador se ha hecho como de estopa y centella, y Dios se hace fuego consumidor, ¿qué puede impedir la destrucción total del pecador?</p>
<br/>




</div>
