<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Isaías 28</h2>
<p class="text-justify">Vv. 1-4.Aquello de lo que los hombres están orgullosos, aunque sea tan egoísta, para ellos es como una corona; pero el orgullo es el precursor de la destrucción. ¡Cuán neciamente actúan los ebrios! Los que son vencidos por el vino son vencidos por Satanás; y no hay esclavitud mayor en el mundo que el beber excesivo. La salud se arruina; los hombres son quebrantados en sus trabajo y en su patrimonio, y sus familias son arruinadas. Sus almas peligran de ser deshechadas para siempre, y todo simplemente por satisfacer una lujuria vil. En el pueblo que profesa a Dios, como Israel, es peor que en cualquier otro. Él es justo al quitarles la abundancia de la que así abusan. La abundancia de la que se enorgullecen no es sino una flor que se marchita; es como el fruto temprano que es cortado y comido tan pronto como lo descubren.</p>
<br/>
<p class="text-justify">Vv. 5-15.El profeta se vuelve en seguida a Judá, a la cual llama residuo de su pueblo. Dichosos los que solo se glorían en el Señor de los ejércitos. De ahí que su pueblo tenga sabiduría y fuerza para todo servicio y todo conflicto. Pero sólo en Cristo Jesús se comunica el santo Dios con el pecador. Si los que enseñan están borrachos con vino o intoxicados con falsas doctrinas y nociones acerca del reino y la salvación del Mesías, no sólo yerran ellos sino que descarrían a multitudes. Todos los lugares donde esas personas han enseñado están llenos de errores.
Para nuestra instrucción en las cosas de Dios es necesario que el mismo precepto y la misma línea se nos repitan a menudo, para que podamos entenderlas mejor.
Dios, por Su palabra, nos llama a lo que realmente es para nuestro provecho; el servicio de Dios es el único reposo verdadero para los cansados de servir al pecado y no hay descanso sino bajo el ligero yugo del Señor Jesús. Todo esto tuvo poco efecto en el pueblo. Los que no entiendan lo que es claro, antes se burlan y lo desprecian por vil y fútil, serán justamente castigados.
Si estamos en paz con Dios, hemos hecho efectivamente un pacto con la muerte; cuando venga no puede hacernos ningún daño real si somos de Cristo. Pero es absurdo pensar en hacer de la muerte nuestra amiga mientras por el pecado estamos haciendo de Dios nuestro enemigo. ¿No convierten en mentira su refugio los que confían en su justicia propia o en un arrepentimiento en el lecho de muerte, que es una resolución de no pecar más cuando ya no está en su poder hacerlo?</p>
<br/>
<p class="text-justify">Vv. 16-22.Aquí hay una promesa de Cristo como único fundamento para la esperanza de escapar de la ira venidera. Este fundamento fue echado en Sion, en los consejos eternos de Dios. Este fundamento es una roca firme y capaz de sostener su Iglesia. Es piedra probada piedra escogida, aprobada por Dios, y nunca falló a quien la probara. Una piedra angular , que une a todo el edificio, y sostiene todo el peso; preciosa a ojos del Señor, y de todo creyente; un fundamento seguro sobre el cual edificar. En cualquier época o nación el que cree este testimonio y pone todas sus esperanzas, y su alma que nunca muere, sobre este fundamento, no será confundido. El efecto justo de la fe en Cristo es acallar y calmar el alma hasta que los sucesos sean ordenados en el tiempo por quien tiene todos los tiempos y poder en su mano. La protección en que los hombres confíen para justificación, que no sea la justicia de Cristo; o para sabiduría, fuerza y santidad, que no sea la influencia del Espíritu Santo; o para felicidad que no sea el favor de Dios, la protección en que pensaron ampararse resultará insuficiente para responder esa intención. Los que descansan en una justicia propia se habrán engañado a sí mismos: la cama es demasiado corta, las tapas son demasiado estrechas. Dios será glorificado en el cumplimiento de sus consejos. Si los que profesan ser miembros de la Iglesia de Dios se hacen como filisteos y cananeos, deben esperar ser tratados como tales. Entonces, no osen ridiculizar las reprensiones de la palabra de Dios o los anuncios de juicios.</p>
<br/>
<p class="text-justify">Vv. 23-29. El agricultor se aplica a su tarea con dolores y prudencia en todas sus obras, conforme a la naturaleza de ellas. Así el Señor, que ha dado esta sabiduría a los hombres, es maravilloso en consejo y excelente en su obrar. Como lo requiere la ocasión amenaza, corrige, salva, muestra misericordia o ejecuta venganza. Las aflicciones son los instrumentos trilladores de Dios para soltarnos del mundo, para separar entre nosotros y nuestra cizaña, y prepararnos para ser usados. Dios las hará proporcionales a nuestra fuerza; no serán más pesadas de lo necesario. Cuando su fin sea logrado, cesarán las pruebas y los sufrimientos de su pueblo; su trigo será reunido en el granero, pero la paja será quemada con fuego que no se apaga.</p>
<br/>




</div>
