<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Isaías 40</h2>
<p class="text-justify">Vv. 1-11.Toda vida humana es una guerra; la vida cristiana lo es más; pero la lucha no durará siempre. Los problemas son quitados por amor cuando se perdona el pecado. En la gran expiación de la muerte de Cristo, Dios ejerció su misericordia para la gloria de su justicia. En Cristo y en sus sufrimientos, los verdaderos arrepentidos reciben de la mano del Señor el doble por todos sus pecados; porque la satisfacción hecha por Cristo en su muerte fue de valor infinito.
El profeta tiene alguna referencia al retorno de los judíos desde Babilonia. Pero este es un suceso pequeño comparado con lo señalado por el Espíritu Santo en el Nuevo Testamento, cuando Juan el Bautista proclama la cercanía de Cristo. Cuando los príncipes orientales marchaban por los países desérticos, les preparaban caminos y se quitaban los obstáculos. Que el Señor prepare nuestros corazones por la enseñanza de su palabra y las convicciones de su Espíritu, para que sean derribados los pensamientos altos y orgullosos, sean plantados buenos deseos, se enderecen y suavicen los temperamentos torcidos y abruptos, y todo impedimento sea removido, para que estemos preparados para su voluntad en la tierra, y preparados para su reino celestial. -¡Qué es todo lo que pertenece al hombre caído o todo lo que hace sino como el pasto y su flor! ¡De qué servirán todos los títulos y posesiones de un pecador moribundo cuando lo dejen sometido a condena! La palabra del Señor puede hacer por nosotros lo que toda la carne no puede.
La buena nueva de la venida de Cristo iba a ser enviada hasta los confines de la tierra. Satanás es el hombre fuerte armado, pero nuestro Señor Jesús es más fuerte y Él procederá y hará todo lo que se propone.
Cristo es el buen Pastor; Él muestra tierno cuidado por los jóvenes convertidos, por los creyentes débiles y por los de espíritu triste. Por su palabra Él requiere no más servicio, y por su providencia, inflige no más aflicción que aquello para lo cual los fortalecerá. Conozcamos la voz de nuestro Pastor y sigámosle, y demostrémonos como sus ovejas.</p>
<br/>
<p class="text-justify">Vv. 12-17.Todos los seres humanos se reducen a nada comparados con el Creador. Cuando el Señor, por su Espíritu, hizo el mundo nada lo dirigió, ni le aconsejó qué hacer o como hacerlo. Las naciones, comparadas con Él, son como gota que queda en el balde, comparadas con el vasto océano; o como menudo polvo en la balanza, que no la mueve, comparado con toda la tierra. Esto magnifica el amor de Dios por el mundo que, aunque de poca monta y valor para Él, sin embargo, para su redención dio a su Hijo unigénito, Juan iii, 16. Los servicios de la Iglesia no pueden añadirle nada. Nuestras almas debieran haber perecido para siempre si el unigénito Hijo del Padre no se hubiera dado por nosotros.</p>
<br/>
<p class="text-justify">Vv. 18-26.Lo que estimemos o amemos, temamos o esperemos más que a Dios, esa criatura igualamos con Dios, aunque no nos hagamos imágenes ni las adoremos. El que es tan pobre que casi no tiene un sacrificio para ofrecer, sin embargo, no deja de tener ídolo propio. No escatiman costos para sus ídolos y nosotros nos quejamos de lo que se gasta en el servicio de nuestro Dios.
Para probar la grandeza de Dios, el profeta apela a todas las eras y naciones. Los que ignoran esto, son voluntariamente ignorantes. Dios tiene el mando de todas las criaturas, y de todas las cosas creadas. El profeta nos lleva a usar nuestra razón y nuestros sentidos; a considerar al creador del ejército del cielo y a rendirle nuestro homenaje. Nadie deja de cumplir su voluntad. No olvidemos que Él hizo todas las promesas y se comprometió a cumplirlas.</p>
<br/>
<p class="text-justify">Vv. 27-31.El pueblo de Dios es reprobado por su descreimiento y desconfianza en Dios. Recuerden que tomaron los nombres de Jacob e Israel de uno que Dios halló fiel a Él en todas sus aflicciones. Llevan ese nombre como su pueblo del pacto. Muchos afanes necios y temores necios se desvanecen antes de inquirir las causas. Malo es tener malos pensamientos que surgen en nuestra mente, pero peor es convertirlos en palabras malas. Lo que ellos conocieron y oyeron era suficiente para silenciar todos sus temores y desconfianzas.
Donde Dios ha empezado la obra de gracia, la perfeccionará. Él ayuda a los que, en humilde dependencia de Él, se ayudan a sí mismos. Su fuerza será según el día. En el poder de la gracia divina nuestras almas ascenderán por sobre el mundo. Correrán alegremente por el camino de los mandamientos de Dios. Velemos contra el descreimiento, el orgullo y la confianza en uno mismo. Si vamos adelante por nuestra propia fuerza, desmayaremos y caeremos totalmente; pero teniendo nuestros corazones y esperanzas en el cielo, seremos llevados por sobre todas las dificultades y seremos dotados para echar mano del premio de nuestra alta vocación en Cristo Jesús.</p>
<br/>




</div>
