<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Job 1</h2>
<p class="text-justify">Vv. 1-5.Job era rico y, no obstante, piadoso. Aunque sea difícil y raro, no es imposible que un rico entre al reino del cielo. Por la gracia de Dios se pueden vencer las tentaciones de la riqueza mundana. El relato de la piedad y prosperidad de Job antecede a la historia de sus grandes aflicciones, mostrando que nada salvará de los problemas.
Aunque Job contemplaba con satisfacción la armonía y el bienestar de sus hijos, su conocimiento del corazón humano le hacía temer por ellos. Él los enviaba y los santificaba, recordándoles que se examinaran a sí mismos, que confesaran sus pecados, que procuraran el perdón y, como quién espera aceptación de parte de Dios a través del Salvador prometido, él ofrecía un holocausto por cada uno de ellos. Percibimos su cuidado por el alma de ellos, su concoimiento del estado pecador del hombre, su dependencia total de la misericordia de Dios en la manera en que Él la haya designado.</p>
<br/>
<p class="text-justify">Vv. 6-12.Las aflicciones de Job comenzaron por la maldad de Satanás, con el permiso del Señor, para propósitos sabios y santos. Hay un espíritu malo, el enemigo de Dios y de toda justicia, que continuamente está procurando alterar, descarriar y, si fuera posible, destruir a los que aman a Dios. No sabemos cuán lejos puede extenderse su influencia pero, probablemente, mucha inestabilidad e infelicidad de los cristianos se puede atribuir a él. Mientras estemos en esta tierra, estamos a su alcance. Por eso, nos concierne estar sobrios y alertas, 1 Pedro v, 8.
Vea aquí como Satánas censura a Job. Esta es la manera corriente de los calumniadores; ellos sugieren aquello de lo cual no tienen motivo para pensar que sea verdadero. Pero como nada hay que debamos temer más que el ser realmente hipócritas, así que nada hay que debamos temer menos que ser llamados y contados así sin causa. Nada malo hay en poner la mira en la recompensa eterna de nuestra obediencia pero es malo ponerla en las ventajas mundanas de nuestra religión. El pueblo de Dios está bajo Su especial protección; ellos y todo lo que les pertenece. La bendición de Dios enriquece; el mismo Satanás lo admite.
Dios soportó que Job fuera probado, como toleró que Pedro fuera zarandeado. Nuestro consuelo es que Dios tenga encadenado al diablo, Apocalipsis xx, 1, 2 Este no tiene poder para llevar a los hombres al pecado sino que ellos mismos le den; ni tampoco poder para afligir a los hombres sino el que le es dado de lo alto. Todo esto está aquí descrito para nosotros conforme a la manera de los hombres. La Escritura habla así para enseñarnos que Dios dirige los asuntos del mundo.</p>
<br/>
<p class="text-justify">Vv. 13-19.Satanás ocasionó los trastornos de Job en el día en que sus hijos empezaron sus fiestas. Todos los problemas recayeron sobre Job de una sola vez; mientras que un mensajero de malas noticias hablaba, el otro lo seguía. Sus posesiones más valiosas y queridas eran sus diez hijos; se le trae la noticia que están muertos. Fueron arrebatados cuando él más los necesitaba para que lo consolaran de sus otras pérdidas. Solamente en Dios tenemos una ayuda presente en todos los tiempos.</p>
<br/>
<p class="text-justify">Vv. 20-22.Job se humilló bajo la mano de Dios. Él razona a partir del estado corriente de la vida humana, cosa que describe. Nada de los bienes de este mundo traemos al mundo sino que los recibimos de otras personas. Job queda reducido a su primer estado con todas sus pérdidas. Él está justo donde debería haber estado al final y sólo es despojado o, más bien, descargado un poco antes de lo que él esperaba. Si nos sacamos la ropa antes de irnos a la cama, es poco conveniente, pero puede soportarse mejor cuando es casi hora de acostarse. De la misma forma, quien dio, quitó. Vea cómo Job mira por encima de los instrumentos y mantiene fijos sus ojos en la Primera Causa. Las aflicciones no deben desviarnos de la religión sino estimularnos a ella. Si miramos al Señor en todos nuestros problemas, Él nos sostendrá.
El Señor es justo. Todo lo que tenemos es por Su dádiva; nosotros lo perdimos por el pecado y no debiéramos quejarnos si Él nos quita una parte. El descontento y la impaciencia acusan de necedad a Dios. Job vigiló cuidadosamente contra ellos y, así debemos hacerlo nosotros, reconociendo que como Dios ha hecho lo bueno pero nosotros hemos hecho lo malo, asimismo Dios ha hecho sabiamente pero nosotros hemos hecho muy neciamente. Y que la maldad y el poder de Satanás hagan más precioso para nuestras almas a ese Salvador que vino a destruir las obras del diablo; Aquel que por nuestra salvación sufrió de parte de ese enemigo muchísimo más de lo que sufrió Job, o de lo que podemos pensar.</p>
<br/>




</div>
