<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Job 42</h2>
<p class="text-justify">Vv. 1-6.Ahora Job entendía su culpa; él ya no hablaría más para excusarse; se aborrecía por pecador de corazón y vida, especialmente por murmurar contra Dios y asumió la vergüenza. Cuando el entendimiento es iluminado por el Espíritu de gracia, nuestro conocimiento de las cosas divinas excede en mucho al que teníamos antes, así como el ver con nuestros ojos excede lo que se nos informa y lo que es de conocimiento común. Por la enseñanza de los hombres, Dios revela su Hijo a nosotros, pero por la enseñanza de su Espíritu revela a su Hijo en nosotros, Gálatas i, 16, y nos cambia a su misma imagen, 2 Corintios iii, 18. Nos corresponde humillarnos profundamente por los pecados de los cuales somos convictos. Aborrecerse a sí mismo es siempre la compañía del arrepentimiento verdadero. El Señor llevará a los que ama, a que le adoren aborreciéndose a sí mismos; mientras la gracia verdadera siempre los llevará a confesar sus pecados sin justificarse.</p>
<br/>
<p class="text-justify">Vv. 7-9.Después que el Señor hubo convencido y humillado a Job, llevándolo al arrepentimiento, lo reconoce, lo consuela y le da honores.
El diablo se había propuesto demostrar que Job era hipócrita y sus tres amigos lo condenaron por malo; pero si Dios dice: Bien hecho, buen siervo fiel, de escasa importancia es que alquien diga lo contrario. Los amigos de Job habían hecho mal ante Dios, al hacer de la prosperidad una marca de la iglesia verdadera, y de la aflicción la prueba cierta de la ira de Dios. Job, más que sus amigos, había referido las cosas al juicio futuro y al estado futuro; por tanto, dijo de Dios lo que era bueno, mejor de lo que habían hecho sus amigos. Y como Job oró y ofreció sacrificios por quienes habían contristado y herido su espíritu, así Cristo oró por sus perseguidores, y siempre vive, intercediendo por los transgresores. Los amigos de Job eran hombres buenos y eran de Dios y Él no los iba a dejar en su error, no más que a Job; pero habiéndo humillado a Job con su discurso desde el torbellino, toma otro camino para humillarlos a ellos.
Ellos no tienen que discutir de nuevo el asunto; tienen que ponerse de acuerdo para un sacrificio y una oración, y eso debe reconciliarlos. Quienes difieren en su juicio sobre cosas menores, siendo uno en Cristo, el gran Sacrificio, deben en consecuencia amarse y soportarse unos a otros. Cuando Dios se enojó con los amigos de Job, los puso en camino de hacer la paz con Él. Nuestras peleas con Dios siempre empiezan de parte nuestra, pero hacer la paz empieza de la suya. La paz con Dios se tiene solamente a su manera y según sus condiciones. Estos nunca parecerá duros a quienes sepan valorar esta bendición: como los amigos de Job, se alegrarán con cualquier condición por humillante que sea. Job no se ofendió con sus amigos, sino que, estando Dios bondadosamente reconciliado con él, fue fácilmente reconciliado con ellos. En todas nuestras oraciones y servicios debemos apuntar a ser aceptados por el Señor; no a ser elogiados por los hombres, sino complacer a Dios.</p>
<br/>
<p class="text-justify">Vv. 10-17.Al comienzo de este libro tenemos como ejemplo la paciencia de Job sometida a problemas; aquí, para nuestra exhortación a seguir ese ejemplo, tenemos su final feliz. Sus problemas empezaron con la maldad de Satanás, que Dios limitó; su restauración empezó con la misericordia de Dios, a la que Satanás no se pudo oponer. La misericordia no retornó cuando Job disputaba con sus amigos, sino cuando oró por ellos. Se sirve y se complace a Dios con nuestras cálidas devociones, no con nuestras cálidas discusiones.
Dios duplicó las posesiones de Job. Podemos perder mucho para el Señor, pero no perderemos nada por Él. Sea que el Señor nos dé o no salud y bendiciones temporales, si sufrimos pacientemente conforme a su voluntad, al final seremos felices. La fortuna de Job aumentó. La bendición del Señor enriquece; Él es quien nos da poder para obtener riqueza y nos da éxito en las empresas honestas. Los últimos días de un hombre bueno, a veces resultan ser los mejores; sus últimas obras, las mejores; sus últimos consolaciones, las mejores; porque su senda, como la luz de la aurora, va en aumento hasta que el día es perfecto.</p>
<br/>




</div>
