<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jonás 4</h2>
<p class="text-justify">Vv. 1-4.Jonás hizo tema de reflexión sobre Dios lo que todos los santos hacen tema de gozo y alabanza; como si mostrar misericordia fuera una imperfección de la naturaleza divina, que es la mayor gloria suya. A su misericordia que perdona y salva todos debemos estar fuera del infierno. -Él desea la muerte; este era lenguaje de la necedad, la pasión y la corrupción intensa. Surgen en Jonás restos de un espíritu orgulloso y nada caritativo; él no esperaba ni deseaba el bienestar de los ninivitas, sino que sólo había venido a declarar y presenciar su destrucción. No se había humillado debidamente por sus propios pecados, ni estaba dispuesto a confiar en el Señor con su crédito y seguridad. Con este estado mental, despreció el bien del prójimo para los que él había sido un instrumento, y la gloria de la misericordia divina. A menudo debemos preguntarnos, ¿está bien hablar así, hacer así? ¿Puedo justificarlo? ¿Hago bien en enojarme tan rápido, tan a menudo, por tanto tiempo y hablar mal a los demás en mi enojo? ¿Hago bien al enojarme con la misericordia de Dios para los pecadores arrepentidos? Ese fue el delito de Jonás. ¿Hago bien al enojarme con eso que es para la gloria de Dios y el avance de su reino? Que la conversión de los pecadores, que es el gozo del cielo, sea nuestro gozo y nunca nuestra tristeza.</p>
<br/>
<p class="text-justify">Vv. 5-11.Jonás salió de la ciudad, pero se quedó cerca, como si esperara y deseara su destrucción. Los que tienen espíritus inquietos y afanosos a menudo se crean problemas para tener algo de que quejarse. Véase cuán tierno es Dios con su pueblo en sus aflicciones, aunque ellos sean necios y atrevidos. Una cosa pequeña en sí misma, pero que llega a tiempo, puede ser una bendición valiosa. Una calabacera en el lugar preciso puede servirnos más que un cedro. Las criaturas menores pueden ser grandes plagas o gran consuelo según le plazca a Dios hacerlas.
Las personas de pasiones fuertes son proclives a decaer ante cualquier fruslería que les moleste o a elevarse con cualquier cosa vana que les guste. Véase qué son nuestros consuelos humanos y qué podemos esperar que sean; son cosas que se están agostando. Un gusanillo en la raíz destruye una calabacera grande: nuestras calabaceras se marchitan y no sabemos cuál es la causa. Quizá nos sean continuados los consuelos de criaturas, pero nos son amargados; la criatura continúa, pero el consuelo se va. Dios preparó un viento para hacer que Jonás sintiera la falta de la calabacera. Justo es que se queden sin nada de que quejarse quienes aman el quejarse. Cuando las providencias que afligen se llevan las relaciones, las posesiones y los goces, no debemos enojarnos con Dios. Lo que debe silenciar especialmente al descontento es que al desaparecer nuestra calabacera, nuestro Dios no desaparece. El pecado y la muerte son muy espantosos, pero Jonás, en su ardor, se los toma a la ligera a ambos.
Un alma es de más valor que todo el mundo; entonces, por cierto que un alma tiene más valor que muchas calabaceras: debemos interesarnos más por las almas preciosas, las nuestras y las del prójimo, que por las riquezas y goces de este mundo. Gran aliento es tener esperanza de hallar misericordia en el Señor, que Él esté listo para mostrar misericordia. Habrá que hacer que los murmuradores entiendan que, por muy dispuestos que estén a conservar la gracia divina para sí y los que son como ellos, hay un solo Señor sobre todos, que es rico en misericordia para con los que le invocan. -¿Nos maravillamos por la paciencia de Dios hacia su perverso siervo? Estudiemos nuestros corazones y modales; no olvidemos nuestra ingratitud y obstinación; y quedémonos atónitos con la paciencia de Dios con nosotros.</p>
<br/>




</div>
