<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jonás 1</h2>
<p class="text-justify">Vv. 1-3.Entristece pensar cuánto pecado se comete en las grandes ciudades. Su maldad, como la de Nínive, es afrenta franca y directa a Dios. Jonás debe irse de inmediato a Nínive, y ahí en terreno, clamar contra la maldad de ellos.
Jonás no quiere ir. Probablemente haya unos cuantos entre nosotros que no hubiesen tratado de declinar tal misión. La providencia parece darle una oportunidad para escapar; nosotros podemos salirnos del camino del deber y hasta encontrar viento a favor. El camino fácil no siempre es el camino recto. Véase lo que son los mejores hombres cuando Dios los deja librados a sí mismos; y la necesidad que tenemos, cuando nos llega la palabra del Señor, de tener al Espíritu del Señor para que lleve cautivo cada pensamiento nuestro a la obediencia a Cristo.</p>
<br/>
<p class="text-justify">Vv. 4-7.Dios manda un perseguidor tras Jonás, un fuerte temporal. El pecado trae tormentas y temporales al alma, a la familia, a las iglesias y a las naciones; es cosa inquietante y perturbadora. Habiendo pedido socorro a sus dioses, los marineros hicieron lo que pudieron para ayudarse. ¡Oh, que los hombres fueran así de sabios con sus almas, y estuvieran dispuestos a separarse de la riqueza, placer y honor que no pueden conservar sin hacer naufragio en la fe y la buena conciencia y arruinar para siempre sus almas! -Jonás dormía profundamente. El pecado atonta y tenemos que hacer caso, no sea que, en cualquier momento, nuestros corazones sean endurecidos por lo engañoso de ellos. ¿Qué quieren decir los hombres con eso de dormirse en el pecado, cuando la palabra de Dios y las acusaciones de sus propias conciencias les advierten que se levanten y clamen al Señor si quieren escapar de la miseria eterna? ¿No debiéramos advertirnos unos a otros para despertar, levantarnos, clamar a nuestro Dios, si Él quisiera librarnos? -Los marineros concluyeron que la tormenta era un mensajero de la justicia divina enviado contra alguien a bordo de ese barco. Cualquiera sea el mal sobre nosotros en cualquier momento, tiene su causa; y cada uno debe orar, Señor, muéstrame en qué contiendes conmigo.
La suerte recayó en Jonás. Dios tiene muchas maneras para sacar a la luz los pecados y pecadores ocultos, y hacer manifiesta esa necedad que se pensaba oculta de los ojos de todos los vivientes.</p>
<br/>
<p class="text-justify">Vv. 8-12.Jonás da cuenta de su religión, porque esa era su ocupación. Podemos tener la esperanza que él dijera esto con pena y vergüenza, justificando a Dios, condenándose así mismo y explicando a los marineros qué Dios grande es Jehová. Ellos le dijeron: ¿Por qué nos has hecho esto? Si temías al Dios que hizo el mar y la tierra seca, ¿por qué fuiste tan necio para pensar que podías huir de su presencia? Si los que profesan la fe hacen mal, lo sabrán de parte de quienes no hacen tal profesión. Cuando el pecado ha levantado una tempestad, y nos ha tirado encima las señales del descontento de Dios, debemos considerar que debe hacerse con el pecado que provocó la tormenta.
Jonás usa el lenguaje de los penitentes verdaderos que desean que nadie, sino ellos mismos, sufran lo peor por sus pecados y necedades. Jonás entiende que esto es el castigo de su iniquidad, lo acepta y justifica a Dios en ello. Cuando se despierta la conciencia, y se levanta tormenta, nada la calmará, sino dejar el pecado que causó el trastorno. Dejar nuestro dinero no pacificará la conciencia, Jonás debe ser tirado por la borda.</p>
<br/>
<p class="text-justify">Vv. 13-17.Los marineros remaron contra el viento y la marea, el viento del descontento de Dios, la marea de sus consejos, pero es en vano pensar en salvarnos a nosotros mismos de otra manera que no sea destruyendo nuestros pecados. Hasta la conciencia natural no puede sino temer la culpa sangrienta. Cuando somos guiados por la providencia, Dios hace lo que le place, y debemos estar satisfechos, aunque pueda no gustarnos.
Tirar al mar a Jonás puso fin a la tempestad. Dios no afligirá por siempre, Él sólo contenderá hasta que nos sometamos y nos devolvamos de nuestros pecados.
Seguramente esos marineros paganos se levantarán en juicio contra muchos que se llaman cristianos, que ni ofrecen oraciones cuando están angustiados ni agradecen por las señales de liberación.
El Señor manda a todas las criaturas y puede hacer que cualquiera sirva a sus designios de misericordia para su pueblo. Veamos esta salvación del Señor y admiremos su poder, que así pudo salvar a un hombre que se ahogaba, y su piedad, que así pudo salvar a uno que huía de Él, y que le había ofendido. Era por las misericordias de Jehová que Jonás no fuera consumido. Jonás vivió tres días y sus noches en el pez: esto era imposible para la naturaleza, pero para el Dios de la naturaleza todas las cosas son posibles.
Jonás fue hecho tipo de Cristo por esta salvación milagrosa, como nuestro Señor bendito lo declara, Mateo xii, 40.</p>
<br/>




</div>
