<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jonás 2</h2>
<p class="text-justify">Vv. 1-9.Fíjese cuando ora Jonás. Cuando estaba en problemas, sometido a las señales del descontento de Dios contra él por pecar: cuando estamos afligidos debemos orar. Oró siendo mantenido con vida por milagro. El sentido de la buena voluntad de Dios para con nosotros, a pesar de nuestras ofensas, abre en oración los labios que estaban cerrados con el miedo a la ira. También, donde oró; en el vientre del pez. Ningún lugar es malo para orar. Los hombres pueden impedirnos la comunión de unos con otros, pero no la comunión con Dios. A quién oró; al Señor su Dios. Esto anima a retornar aun a los descarriados. Qué fue su oración. Esto parece relatar su experiencia y reflexiones, entonces y después, más que ser la forma o sustancia de su oración. Jonás reflexiona en el fervor de su oración y la prontitud de Dios para oír y responder. Si nos volvemos buenos por nuestros problemas, debemos notar la mano de Dios en ellos. Había huido malamente de la presencia del Señor, que podía quitarle con justicia su Espíritu Santo, para nunca más visitarlo. Son miserables sólo aquellos a quienes Dios no reconoce ni favorece más. Aunque estaba perplejo, no estaba desesperado, Jonás reflexiona en el favor de Dios para él, cuando buscó a Dios y confió en Él en su angustia.
Amonesta a los demás, y les dice que se mantengan cerca de Dios. Los que abandonan su deber, abandonan su propia misericordia; los que huyen de la obra de su lugar y día, huyen del consuelo de ella. En cuanto un creyente copia a los que siguen las vanidades mentirosas, se olvida de su propia misericordia, y vive por debajo de sus privilegios. Pero la experiencia de Jonás estimula a los demás, de todas las épocas, a confiar en Dios como Dios de salvación.</p>
<br/>
<p class="text-justify">V. 10.La liberación de Jonás puede ser considerada como ejemplo del poder de Dios sobre todas las criaturas. Como ejemplo de la misericordia de Dios para un pobre penitente que, en angustia, ora a Él: y como tipo y figura de la resurrección de Cristo. En medio de todas nuestras diversas experiencias y de los cambiantes escenarios de la vida, tenemos que mirar por fe, fijamente, a nuestro Redentor, una vez sufriente y moribundo, pero ahora resurrecto y ascendido. Confesemos nuestros pecados, consideremos la resurrección de Cristo como primicia de la propia, y recibamos agradecidos cada temporal y liberación espiritual como señal de nuestra redención eterna.</p>
<br/>




</div>
