<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Josué 24</h2>
<p class="text-justify">Vv. 1-14.Nunca debemos dar por terminada nuestra obra para Dios, hasta que haya terminado nuestra vida. Si alarga nuestros días más allá de lo esperado, como Josué, se debe a que tiene otro servicio para encomendarnos. El que quiere tener el mismo sentir que hubo también en Cristo Jesús, se gloriará en dar el último testimonio de la bondad de su Salvador, y en proclamar a los cuatro vientos, las obligaciones con que lo ha enlazado la inmerecida bondad que Dios le ha mostrado.
La asamblea se reunió en solemne actitud religiosa. Josué les habló en nombre de Dios y de parte de Él. Su sermón fue doctrina y aplicación. La parte doctrinaria es la historia de las grandes cosas que Dios había hecho por su pueblo y por sus antepasados. La aplicación de la historia de las misericordias de Dios para con ellos, es una exhortación a temer y servir a Dios como gratitud por su favor, y que pueda continuar.</p>
<br/>
<p class="text-justify">Vv. 15-28.Es esencial que el servicio del pueblo de Dios sea hecho con actitud voluntaria. Porque el amor es el único principio genuino del cual puede provenir todo servicio aceptable a Dios. El Padre tales adoradores busca que le adoren: los que le adoran en espíritu y en verdad. Los designios de la carne son enemistad contra Dios, por tanto, el hombre carnal es incapaz de dar adoración espiritual. De ahí la necesidad de nacer de nuevo. Pero gran cantidad de personas se quedan solo en las formalidades cuando se les imponen tareas.
Josué les dio a elegir, pero no como si fuera indiferente que ellos sirvieran o no a Dios. Escogeos a quien sirváis, ahora las cosas están clara ante vosotros. Él resuelve servir a Dios, sea lo que fuere que los demás hagan. Quienes resuelven servir a Dios no deben importarles estar solos de ahí en adelante. Los que van al cielo deben estar dispuestos a nadar contra la corriente. No deben hacer como la mayoría , sino como los mejores . Nadie puede comportarse como debiera en cualquier situación sin considerar profundamente sus deberes religiosos en las relaciones familiares.
Los israelitas estuvieron de acuerdo con Josué, influidos por el ejemplo del hombre que había sido una bendición tan grande para ellos; nosotros también serviremos al Señor. Fijaos cuánto bien hacen los grandes hombres por su influencia, si son celosos en la religión.
Josué los lleva a expresar el pleno propósito del corazón de ser fieles al Señor. Deben despojarse de toda confianza en su propia suficiencia o de lo contrario, sus propósitos serán vanos. Cuando hubieron decidido deliberadamente servir a Dios, Josué los ata con un pacto solemne. Hace un monumento para memoria. De esta manera emotiva Josué se despidió de ellos; si perecen, la sangre de ellos será sobre sus cabezas.
Aunque la casa de Dios, la mesa del Señor y hasta los muros y árboles ante los cuales hemos expresado nuestros propósitos solemnes de servirle, dieran testimonio en contra nuestra si lo negáremos, de todos modos podemos confiar en Él, que pondrá temor en nuestro corazón para que no nos apartemos de Él. Sólo Dios puede dar gracia, sin embargo, bendice nuestros esfuerzos por hacer que los hombres se comprometan en su servicio.</p>
<br/>
<p class="text-justify">Vv. 29-33.José murió en Egipto, pero dio órdenes tocante a sus huesos, para que no descansaran en su tumba hasta que Israel descansara en la tierra prometida.
Nótese además la muerte y sepultura de Josué y de Eleazar, el sumo sacerdote. Los hombres más útiles, habiendo servido a su generación conforme a la voluntad de Dios, uno tras otro, caen dormidos y ven corrupción. Pero Jesús, habiendo pasado y terminado su vida en la tierra en forma más efectiva que José y Josué, resucitó de entre los muertos y no vio corrupción. Los redimidos del Señor heredarán el reino que preparó para ellos desde la fundación del mundo. Ellos hablarán admirados de la gracia de Jesús: “Al que nos amó, y nos lavó de nuestros pecados con su sangre, y nos hizo reyes y sacerdotes para Dios, su Padre; a Él sea gloria e imperio por los siglos de los siglos. Amén.”</p>
<br/>




</div>
