<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 10</h2>
<p class="text-justify">Vv. 1-5.He aquí una parábola o símil tomado de las costumbres del Oriente para el manejo de las ovejas. Los hombres, como criaturas que dependen de su Creador, son llamados ovejas de su prado. La Iglesia de Dios en el mundo es como un redil de ovejas, expuesto a los engañadores y los perseguidores. El gran Pastor de las ovejas conoce a todas las suyas, las cuida por su providencia, las guía por su Espíritu y su palabra, y va delante de ellas, como los pastores orientales iban delante de sus ovejas para ponerlas en el camino tras sus pasos. Los ministros deben servir a las ovejas en sus preocupaciones espirituales. El Espíritu de Cristo les pondrá por delante una puerta abierta. Las ovejas de Cristo obedecerán a su Pastor y serán cautelosas y tímidas con los extraños que las quieran sacar de la fe en Él y llevarlas a las fantasías sobre Él.</p>
<br/>
<p class="text-justify">Vv. 6-9.Muchos que oyen la palabra de Cristo no la entienden porque no quieren, pero nosotros hallaremos que un pasaje explica a otro al otro, y el Espíritu bendito da a conocer al bendito Jesús.
Cristo es la Puerta, ¿y qué mayor seguridad tiene la Iglesia de Dios que el Señor Jesús esté entre ella y todos sus enemigos? Él es una puerta abierta para pasar y comunicar. He aquí instrucciones claras sobre cómo entrar al redil; debemos entrar por Jesucristo en cuanto es la Puerta. Por fe en Él como el gran Mediador entre Dios y el hombre. Además, tenemos promesas preciosas para los que obedecen esta instrucción. Cristo da todo el cuidado a su Iglesia, y a cada creyente, que un buen pastor da a su rebaño; y Él espera que la Iglesia, y cada creyente, le atienda y se mantenga en su pastura.</p>
<br/>
<p class="text-justify">Vv. 10-18.Cristo es el Buen Pastor; muchos no eran ladrones, pero fueron negligentes con su deber, y el rebaño fue muy dañado por su descuido. Los malos principios son la raíz de las malas costumbres.
El Señor Jesús sabe a quienes ha escogido y está seguro de ellos; también ellos saben en quien confiaron y están seguros de Él.
Véase aquí la gracia de Cristo: puesto que nadie podría quitarle la vida, Él la entrega, por sí, para nuestra redención. Él se ofrendó para ser el Salvador: He aquí, Yo vengo. La necesidad de nuestro caso lo pedía, y Él se ofreció para el Sacrificio. Fue el que ofrenda y ofrenda, de modo que la entrega de su vida fue la ofrenda de sí mismo. De eso queda en claro que Él murió en el lugar y como sustituto de los hombres para lograr que ellos fueran librados del castigo del pecado, para obtener el perdón del pecado para ellos; y para que su muerte adquiriera ese perdón. Nuestro Señor no entregó su vida por su doctrina, sino por sus ovejas.</p>
<br/>
<p class="text-justify">Vv. 19-21.Satanás destruye a muchos quitándoles el interés por la palabra y las ordenanzas. Los hombres no toleran que se rían de ellos por su alimento necesario, pero toleran que se rían de ellos por lo que es mucho más necesario. Si nuestro celo y fervor en la causa de Cristo, especialmente en la bendita obra de llevar sus ovejas a su redil, nos acarrea mala fama, no la escuchemos, pero recordemos que así reprocharon a nuestro Maestro antes que a nosotros.</p>
<br/>
<p class="text-justify">Vv. 22-30.Todos los que tienen algo que decir a Cristo, pueden encontrarlo en el templo. Cristo nos hará creer; nosotros nos hacemos dudar. Los judíos entendieron su significado, pero no pudieron dar forma a sus palabras como acusación completa en su contra. Él describió la disposición de gracia y el estado de dicha de sus ovejas; ellas oyeron y creyeron su palabra, le siguieron como sus fieles discípulos, y ninguna de ellas perecerá, porque el Hijo y el Padre eran uno. Así, pues, pudo defender a sus ovejas contra todos sus enemigos, lo cual prueba que pretendió tener poder y perfección divinos iguales al Padre.</p>
<br/>
<p class="text-justify">Vv. 31-38.Las obras de poder y misericordia de Cristo le proclaman ser. Dios bendijo sobre todo por los siglos, para que todos sepan y crean que Él es en el Padre, y el Padre en Él. A quien el Padre envía, santifica. El santo Dios recompensará y, por tanto, empleará sólo a quienes Él haga santos. El Padre era en el Hijo, de modo que por el poder divino, Aquél obró sus milagros; el Hijo era en el Padre, de modo que conocía toda su mente. Nosotros no podemos hallar esto a la perfección buscándolo, pero debemos conocer y creer estas declaraciones de Cristo.</p>
<br/>
<p class="text-justify">Vv. 39-42.No prosperará ningún arma forjada contra nuestro Señor Jesús. No escapó porque tuviera temor de sufrir, sino porque su hora no había llegado. Aquél que sabía librarse a sí mismo, sabe librar de sus tentaciones a los santos, y hacerles un camino para que escapen. Los perseguidores pueden echar a Cristo y su evangelio de la ciudad o país de ellos pero no pueden echarlos del mundo. Cuando por fe en nuestros corazones conocemos a Cristo, encontramos que es verdad todo lo que la Escritura dice de Él.</p>
<br/>




</div>
