<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 2</h2>
<p class="text-justify">Vv. 1-11.Es muy deseable que cuando haya un matrimonio Cristo lo reconozca y lo bendiga. Los que quieran tener a Cristo consigo en su matrimonio deben invitarlo por medio de la oración y Él vendrá. Mientras estamos en este mundo nos hallamos, a veces, en aprietos aun cuando creemos estar en abundancia. Había una necesidad en la fiesta de bodas. Los que son dados a preocuparse por las cosas del mundo deben esperar problemas y contar con el desencanto. Cuando hablamos a Cristo debemos exponer con humildad nuestro caso ante Él y, luego, encomendarnos a Él para que haga como le plazca.
No hubo falta de respeto en la respuesta de Cristo a su madre. Usó la misma palabra cuando le habló con afecto desde la cruz, pero es testimonio presente contra la idolatría de las épocas posteriores que rinde honores indebidos a su madre.
Su hora llega cuando no sabemos qué hacer. La tardanza de la misericordia no es una negación de las oraciones. Los que esperan los favores de Cristo deben obedecer sus órdenes con prontitud. El camino del deber es el camino a la misericordia, y no hay que objetar los métodos de Cristo.
El primero de los milagros de Moisés fue convertir agua en sangre, Exodo vii, 20; el principio de los milagros de Cristo fue convertir agua en vino, lo cual puede recordarnos la diferencia que hay entre la ley de Moisés y el evangelio de Cristo. Él demuestra que beneficia con consuelos de la creación a todos los creyentes verdaderos y que a ellos los convierte en verdadero consuelo. Las obras de Cristo son todas para bien. ¿Ha convertido tu agua en vino, te dio conocimiento y gracia? Es para aprovecharlo; por tanto, saca ahora y úsalo. Era el mejor vino. Las obras de Cristo se recomiendan por sí mismas aun ante quienes no conocen a su Autor. Lo que es producido por milagro siempre ha sido lo mejor de su clase. Aunque con esto Cristo permite el uso correcto del vino, no anula en lo más mínimo su advertencia de que nuestros corazones, en ningún momento, se carguen con glotonería ni embriaguez, Lucas xxi, 34. Aunque no tenemos que ser melindrosos para festejar con nuestras amistades en ocasiones apropiadas, de todos modos, toda reunión social debe realizarse de tal modo que podamos invitar a reunise con nosotros al Redentor, si ahora estuviera en la tierra; toda liviandad, lujuria y exceso le ofenden.</p>
<br/>
<p class="text-justify">Vv. 12-22.La primera obra pública en que hallamos a Cristo es expulsar del templo a los cambistas que los codiciosos sacerdotes y dirigentes apoyaban para que convirtieran en mercado sus atrios. Los que ahora hacen de la casa de Dios un mercado, son los que tienen sus mentes llenas con el interés por los negocios del mundo cuando asisten a los ejercicios religiosos, o los que desempeñan oficios divinos por amor a una ganancia.
Habiendo purificado el templo, Cristo dio una señal a los que le pidieron que probara su autoridad para actuar: Anuncia su muerte por la maldad de los judíos. Destruid este templo. Yo os permitiré destruirlo. Anuncia su resurrección por su propio poder: En tres días lo levantaré. Cristo volvió a la vida por su poder. Los hombres se equivocan cuando entienden literalmente cuando las Escrituras hablan figuradamente. Cuando Jesús resucitó de entre los muertos, sus discípulos recordaron que había dicho esto. Mucho ayuda a nuestro entendimiento de la palabra divina que observemos el cumplimiento de las Escrituras.</p>
<br/>
<p class="text-justify">Vv. 23-25.Nuestro Señor conocía a todos los hombres, su naturaleza, sus disposiciones, sus afectos y sus intenciones, de una manera que nosotros no conocemos a nadie, ni siquiera a nosotros mismos. Conoce a sus astutos enemigos, y todos sus proyectos secretos; a sus amigos falsos y su verdadero carácter. Él sabe quienes son verdaderamente suyos, conoce su rectitud, y conoce sus debilidades. Sabemos lo que los hombres hacen; Cristo sabe lo que hay en ellos, Él prueba el corazón. Cuidado con una fe muerta o una profesión de fe formal: No hay que confiar en los profesantes carnales y vacíos, y aunque los hombres se impongan a otros o a sí mismos, no pueden imponerse al Dios que escudriña el corazón.</p>
<br/>




</div>
