<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 8</h2>
<p class="text-justify">Vv. 1-11.Cristo no halló defecto en la ley ni excusó la culpa de la mujer prisionera; tampoco tomó en cuenta el pretendido celo de los fariseos. Se condenan a sí mismos los que juzgan a los demás y, sin embargo, hacen lo mismo. Todos los que de alguna manera son llamados a culpar las faltas del prójimo, están especialmente preocupados de mirarse a sí mismos y mantenerse puros. En este asunto Cristo asistió a la gran obra por la cual vino al mundo, la cual era, llevar pecadores al arrepentimiento, no para destruir, sino para salvar. Él apuntaba a llevar al arrepentimiento no sólo al acusado demostrándole su misericordia, sino también a los acusadores demostrándoles sus pecados; ellos pensaron tenderle una trampa; Él procuró convencerlos y convertirlos. -Él rehusó inmiscuirse en el oficio de juez. Muchos delitos merecen un castigo más severo que el recibido, pero no debemos dejar nuestra propia obra para asumir aquella a la cual no hemos sido llamados. Cuando Cristo la mandó irse, fue con esta precaución: Vete y no peques más. Los que ayudan a salvar la vida de un delincuente deben ayudar a salvar el alma con el mismo cuidado.
Son verdaderamente felices aquellos a quienes Cristo no condena. El favor de Cristo para nosotros al perdonar los pecados pasados debe prevalecer en nosotros: Vete, y no peques más.</p>
<br/>
<p class="text-justify">Vv. 12-16.Cristo es la Luz del mundo. Dios es luz, y Cristo es la imagen del Dios invisible. Un sol ilumina a todo el mundo; así lo hace un solo Cristo y no se necesita más. ¡Qué mazmorra oscura sería el mundo sin el sol! Así sería sin Jesús por el cual vino la luz al mundo.
Quienes siguen a Cristo no andarán en tinieblas. No serán dejados sin las verdades necesarias para impedir el error destructor, y sin las instrucciones en el camino del deber, necesarias para guardarlos del pecado condenador.</p>
<br/>
<p class="text-justify">Vv. 17-20.Si conociéramos mejor a Cristo conoceríamos mejor al Padre. Se vuelven vanos en sus imaginaciones acerca de Dios los que no aprenden de Cristo. Los que no conocen su gloria ni su gracia, no conocen al Padre que le envió. El tiempo de nuestra partida de este mundo depende de Dios. Nuestros enemigos no pueden apresurarlo más, ni nuestros amigos, demorarlo respecto del tiempo designado por el Padre. Todo creyente verdadero puede mirar arriba y decir con placer: Mis tiempos están en tu mano, y mejor en ellas que en las mías. Para todos los propósitos de Dios hay un tiempo.</p>
<br/>
<p class="text-justify">Vv. 21-29.Los que viven en incredulidad están acabados para siempre si mueren en la incredulidad. Los judíos pertenecían a este mundo malo actual, pero Jesús era de naturaleza divina y celestial, de modo que su doctrina, su reino y sus bendiciones no se adaptarían al gusto de ellos. Pero la maldición de la ley es quitada para todos los que se someten a la gracia del evangelio. Nada, sino la doctrina de la gracia de Cristo, será un argumento suficientemente poderoso para hacernos volver del pecado a Dios; y ese Espíritu es dado, y esa doctrina está dada, para obrar sólo en quienes creen en Cristo. Algunos dicen: ¿Quién es este Jesús? Ellos le reconocen como un profeta, maestro excelente, y aun como algo más que una criatura, pero no pueden reconocerle, por sobre todo, como Dios bendito por los siglos. ¿No bastará eso? Aquí responde Jesús la pregunta: ¿Es esto para honrarle como Padre? ¿Reconoce que Jesús es la Luz del mundo y la Vida de los hombres, uno con el Padre? Todos sabrán por su conversión o en su condenación que Él siempre habló e hizo lo que agradaba al Padre, aun cuando reclamaba para sí los honores más excelsos.</p>
<br/>
<p class="text-justify">Vv. 30-36.Un poder tal acompañaba las palabras de nuestro Señor que muchos se convencieron y profesaron creer en Él. Él los estimuló para que escucharan sus enseñanzas, a confiar en sus promesas, y obedecer sus mandamientos a pesar de todas las tentaciones al mal. Iban a ser verdaderamente sus discípulos haciendo eso, y aprenderían por la enseñanza de su palabra y su Espíritu, donde están la esperanza y la fuerza de ellos.
Cristo habló de libertad espiritual, pero los corazones carnales no sienten otros pesares aparte de los que molestan al cuerpo y perturban sus asuntos mundanos. Si se les habla de su libertad y propiedad, del despilfarro perpetrado en sus tierras o del daño infligido a sus casas, entenderán muy bien, pero si se les habla de la esclavitud del pecado, de la cautividad con Satanás y de la libertad por Cristo, del mal hecho a sus preciosas almas, y el riesgo de su bienestar eterno, entonces usted lleva cosas raras a sus oídos. Jesús les recordó claramente que el hombre que practica cualquier pecado es, efectivamente, un esclavo de pecado, como era el caso de la mayoría de ellos. Cristo nos ofrece libertad en el evangelio; tiene poder para darla, y aquellos a quienes Cristo hace libres, realmente lo son. Sin embargo, a menudo vemos a las personas que debaten sobre libertades de toda clase mientras son esclavos de alguna lujuria pecaminosa.</p>
<br/>
<p class="text-justify">Vv. 37-40.Nuestro Señor resiste el orgullo y la vana confianza de estos judíos, mostrándoles que su descendencia desde Abraham no aprovecha a los de espíritu contrario a Él. Donde la palabra de Dios no tiene lugar, no debe esperarse nada bueno; ahí se da lugar a toda iniquidad.
Un enfermo que regresa de ver al médico y no toma ningún remedio ni come, ha perdido la esperanza de recuperarse. La verdad sana y nutre los corazones de quienes la reciben. La verdad enseñada por los filósofos no tiene este poder ni este efecto, sino sólo la verdad de Dios. Quienes reclaman los privilegios de Abraham, deben hacer las obras de Abraham; deben ser extranjeros y peregrinos en este mundo; mantener la adoración de Dios en su familia y andar siempre delante de Dios.</p>
<br/>
<p class="text-justify">Vv. 41-47.Satanás dispone a los hombres a excesos por los cuales se asesinan a sí mismos y al prójimo, mientras lo que pone en la mente tiende a destruir las almas de los hombres. Él es el gran promotor de toda clase de falsedad. Es mentiroso, todas sus tentaciones las efectúa llamando bueno a lo malo y malo a lo bueno, y prometiendo libertad en el pecar. Él es el autor de todas las mentiras; a él se parecen y evocan los mentirosos, con quienes tendrá su porción para siempre, como todos los mentirosos. Las lujurias especiales del diablo son la maldad espiritual, las lujurias de la mente, y los razonamientos corruptos, la soberbia y la envidia, la ira y la malicia, la enemistad para con lo bueno, y estimular al prójimo al mal. Aquí la verdad es la voluntad revelada de Dios para salvación de los hombres por Jesucristo, la verdad que ahora estaba predicando Cristo y a la cual se opusieron los judíos.</p>
<br/>
<p class="text-justify">Vv. 48-53.Obsérvese el desprecio de Cristo por los aplausos de los hombres. Los que están muertos para los elogios de los hombres pueden tolerar el desprecio de ellos. Dios procura el honor de todos los que no buscan lo suyo propio.
En estos versículos tenemos la doctrina de la dicha eterna de los creyentes. Tenemos el carácter del creyente; éste es el que guarda las palabras del Señor Jesús. El privilegio del creyente es que no verá para siempre la muerte de ninguna manera. Aunque ahora no pueden evitar ver la muerte y, también saborearla, sin embargo, dentro de poco tiempo estarán donde para siempre no habrá más muerte, Exodo xiv, 13.</p>
<br/>
<p class="text-justify">Vv. 54-59.Cristo y todos los suyos, dependen de Dios en cuanto al honor. Los hombres pueden ser capaces de debatir sobre Dios aunque no le conozcan. Se pone juntos a los que no conocen a Dios con los que no obedecen el evangelio de Cristo, 2 Tesalonisenses i, 8. Todos los que conocen rectamente algo de Cristo desean fervorosamente saber más de Él. Los que disciernen el alborear de la luz del Sol de Justicia, desean ver su levante. -“YO SOY antes que Abraham”. Esto habla de Abraham como una criatura y de nuestro Señor como el Creador; por tanto, bien puede Él engrandecerse más que Abraham. YO SOY es el nombre de Dios, Exodo iii, 14; habla de su existencia de Sí mismo y por sí mismo; Él es el Primero y el Último, siempre el mismo, Apocalipsis i, 8. Así, pues, no sólo era antes que Abraham, sino antes que todos los mundos, Proverbios viii, 23; capítulo i, 1. Como Mediador fue el Mesías ungido mucho antes de Abraham; el Cordero inmolado desde la fundación del mundo, Apocalipsis xiii, 8. El Señor Jesús fue hecho Sabiduría, Justicia, Santificación y Redención de Dios para Adán y Abel, y para todos los que antes de Abraham vivieron y murieron por fe en Él.
Los judíos estaban por lapidar a Jesús por blasfemar, pero Él se retiró; por su poder milagroso pasó ileso a través de ellos. Profesemos constantemente lo que sabemos y creemos acerca de Dios; y si somos herederos de la fe de Abraham, nos regocijaremos esperando el día en que el Salvador se aparecerá en gloria para confusión de sus enemigos, y para completar la salvación de todos los que creen en Él.</p>
<br/>




</div>
