<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 21</h2>
<p class="text-justify">Vv. 1-14.Cristo se da a conocer a su pueblo habitualmente en sus ordenanzas pero, a veces, por su Espíritu los visita cuando están ocupados en sus actividades. Bueno es que los discípulos de Cristo estén juntos en la conversación y en las actividades corrientes. Aún no había llegado la hora para que entraran en acción. Contribuirían para sustentarse a sí mismos a fin de no ser carga para nadie.
El tiempo de Cristo para darse a conocer a su pueblo es el momento en que ellos están más perdidos. Él conoce las necesidades temporales de su pueblo y les ha prometido no sólo gracia suficiente, sino alimento conveniente. La providencia divina se extiende a las cosas más minuciosas, y felices son los que que reconocen a Dios en todos sus caminos. Los humildes, diligentes y pacientes, serán coronados aunque sus labores sean terribles; a veces, viven para ver que sus asuntos toman un giro favorable después de muchas luchas. Nada se pierde con obedecer las órdenes de Cristo; es tirar la red al lado derecho del bote. Jesús se manifiesta a su pueblo haciendo por ellos lo que nadie más puede hacer, y lo que ellos no esperaban. Él cuidará que a los que dejaron todo por Él, no les falte ningún bien. Y los favores tardíos deben traer a la memoria los favores previos, para que no se olvide el pan comido.
Aquel a quien Jesús amaba fue el primero en decir: Es el Señor. Juan se había aferrado más estrechamente a su Maestro en sus sufrimientos y lo conoció mucho antes. Pedro era el más celoso, y alcanzó primero a Cristo. ¡Con qué variedad dispensa Dios las dádivas y cuánta diferencia puede haber entre uno y otro creyente en su modo de honrar a Cristo, pero todos son aceptados por Él! Otros se quedan en el bote, arrastran la red y traen la pesca a la playa, y no debemos culpar de mundanas a esas personas, porque ellos, en sus puestos, están sirviendo verdaderamente a Cristo, como los demás.
El Señor Jesús tenía provisión lista para ellos. No tenemos que curiosear inquiriendo de dónde provino, pero consolémonos con el cuidado de Cristo por sus discípulos. Aunque había tantos peces y tan grandes, no perdieron ninguno ni dañaron su red. La red del evangelio ha capturado a multitudes, pero es tan fuerte como siempre para llevar almas a Dios.</p>
<br/>
<p class="text-justify">Vv. 15-19.Nuestro Señor se dirigió a Pedro por su nombre original, como si hubiera dejado el de Pedro cuando lo negó. Ahora contestó: Tú sabes que te amo, pero sin declarar que ama a Jesús más que los otros. No debemos sorprendernos con que nuestra sinceridad sea cuestionada cuando nosotros mismos hemos hecho lo que la vuelve dudosa. Todo recuerdo de pecados pasados, aun de pecados perdonados, renueva la tristeza del penitente verdadero. Consciente de su sinceridad, Pedro apeló solemnemente a Cristo, que conoce todas las cosas, hasta los secretos de su corazón. Bueno es que nuestras caídas y errores nos vuelvan más humildes y alertas. La sinceridad de nuestro amor a Dios debe ser puesta a prueba. Y nos conviene rogar con oración perseverante y ferviente al Dios que escudriña los corazones, que nos examine y nos pruebe a ver si somos capaces de resistir esta prueba. Nadie que no ame al buen Pastor más que a toda ventaja u objeto terrenal, puede ser apto para apacentar las ovejas y los corderos de Cristo.
El gran interés de todo hombre bueno, cualquiera sea la muerte de que muera, es glorificar a Dios en ella, porque ¿cuál es nuestro objetivo principal sino este: morir por el Señor cuando lo pida?</p>
<br/>
<p class="text-justify">Vv. 20-24.Los sufrimientos, los dolores, y la muerte parecen formidables aun al cristiano experimentado; pero, en la esperanza de glorificar a Dios, de dejar un mundo pecador, y estar presente con su Señor, aquel se vuelve presto a obedecer el llamado del Redentor y seguirle hacia la gloria a través de la muerte.
La voluntad de Cristo es que sus discípulos se ocupen de su deber sin andar curioseando hechos futuros, sea acerca de sí o del prójimo. Somos buenos para ponernos ansiosos por muchas cosas que nada tienen que ver con nosotros. Los asuntos de otras personas nada son para que nos entrometamos; debemos trabajar tranquilamente y ocuparnos de nuestros asuntos. Se hacen muchas preguntas curiosas sobre los consejos de Dios, y el estado del mundo invisible, a las cuales podemos responder, ¿qué a nosotros? Si atendemos el deber de seguir a Cristo, no hallaremos corazón ni tiempo para meternos en lo que no nos corresponde. -¡Cuán poco se puede confiar en las tradiciones orales! Que la Escritura se interprete y se explique a sí misma; porque en gran medida, es evidencia y prueba en sí misma, porque es luz. Nótese la facilidad de enmendar errores, como aquellos, por la propia palabra de Cristo. El lenguaje de la Escritura es el canal más seguro para la verdad de la Escritura: las palabras que enseña el Espíritu Santo, 1 Corintios ii, 13. Los que no concuerdan en los mismos términos del arte, y su aplicación, pueden, no obstante, estar de acuerdo en los mismos términos de la Escritura, y amarse unos a otros.</p>
<br/>
<p class="text-justify">V. 25.Se escribió sólo una pequeña parte de los actos de Jesús; pero bendigamos a Dios por todo lo que está en las Escrituras y agradezcamos que haya tanto en tan poco espacio. Suficiente quedó escrito para dirigir nuestra fe, y regir nuestra práctica; más, hubiera sido innecesario.
Mucho de lo escrito es pasado por alto, mucho se olvida, y mucho es hecho cuestión de controversias dudosos. Sin embargo, podemos esperar el gozo que recibiremos en el cielo del conocimiento más completo de todo lo que Jesús hizo y dijo, y de la conducta de su providencia y gracia en sus tratos con cada uno de nosotros. Sea esta nuestra felicidad. Pero éstas se han escrito para que creáis que Jesús es el Cristo, el Hijo de Dios; y para que creyendo, tengáis vida en su nombre, capítulo xx, 31.</p>
<br/>




</div>
