<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 9</h2>
<p class="text-justify">Vv. 1-7.Cristo curó a muchos que eran ciegos por enfermedad o accidente; aquí sana a uno que nació ciego. Así mostró su poder para socorrer en los casos más desesperados, y la obra de su gracia en las almas de los pecadores, que da vista a los que son ciegos por naturaleza. Este pobre hombre no podía ver a Cristo, pero Cristo lo vio a Él. Y si sabemos o captamos algo de Cristo se debe a que primeramente fuimos conocidos por Él. Cristo habla de calamidades extraordinarias, que no siempre tienen que considerarse como castigos especiales del pecado; a veces, son para la gloria de Dios y para manifestar sus obras.
Nuestra vida es nuestro día en el que nos corresponde hacer el trabajo del día. Debemos estar ocupados y no desperdiciar el tiempo del día; el tiempo de reposo será cuando nuestro día esté terminado, porque no es sino un día. El acercamiento de la muerte debiera estimularnos para aprovechar todas las oportunidades de hacer y recibir el bien. Debemos hacer rápidamente el bien que tengamos oportunidad de hacer. Y aquel que nunca hace una buena obra hasta que no hay nada que objetar contra ella, dejará más de una buena obra sin hacer, Eclesiastés xi, 4.
Cristo magnificó su poder al hacer que un ciego viera, haciendo lo que uno pensaría como más probable para enceguecer a uno que ve. La razón humana no puede juzgar los métodos del Señor que usa medios e instrumentos que los hombres desprecian. Los que serán sanados por Cristo deben ser gobernados por Él. Regresó desde el estanque maravillándose y maravillado; se fue viendo. Esto representa los beneficios de prestar atención a las ordenanzas señaladas por Cristo; las almas llegan débiles y se van fortalecidas; llegan dudando y se van satisfechas; llegan de duelo y se van jubilosas; llegan ciegas y se van viendo.</p>
<br/>
<p class="text-justify">Vv. 8-12.Se sabe que aquellos cuyos ojos son abiertos y sus corazones limpiados por la gracia, son las mismas personas, pero de carácter completamente diferente, y viven como monumentos de la gloria del Redentor y recomiendan su gracia a todos los que desean la misma preciosa salvación. Bueno es fijarse en el camino y el método de las obras de Dios y se verán más maravillosas. Aplíquese esto espiritualmente. En la obra de gracia obrada en el alma vemos el cambio, pero no vemos la mano que lo efectúa: el camino del Espíritu es como el del viento, del cual uno oye el sonido, pero no puede decir de dónde viene ni adónde va.</p>
<br/>
<p class="text-justify">Vv. 13-17.Cristo no sólo obró milagros en el día de reposo, pero su modo hizo que se ofendieran los judíos, porque pareció no ceder ante los escribas ni los fariseos. El celo de ellos por los puros ritos consumió los asuntos importantes de la religión; por tanto, Cristo no quiso darles cabida. Además, se permiten las obras de necesidad y de misericordia y el reposo sabático debe guardarse para la obra del día de reposo. ¡Cuántos ojos cegados han sido abiertos predicando el evangelio en el día del Señor! ¡Cuántas almas impotentes son curadas en ese día! Muchos juicios impíos y despiadados vienen de los hombres que agregan sus propias fantasías a los designios de Dios. ¡Qué perfecto en sabiduría y santidad es nuestro Redentor, cuando sus enemigos no pudieron hallar nada en su contra, sino la acusación de violar el día de reposo, tan a menudo refutada! Seamos capaces de silenciar la ignorancia de los hombres necios haciendo el bien.</p>
<br/>
<p class="text-justify">Vv. 18-23.Los fariseos esperaron vanamente refutar este notable milagro. Esperaban a un Mesías, pero no toleraban pensar que este Jesús fuera Aquel, porque sus preceptos eran del todo contrarios a las tradiciones de ellos, y porque tenían la expectativa de un Mesías con pompa y esplendor externo. El temor del hombre pondrá lazo, Proverbios xxix, 25, y, a menudo, hace que la gente niegue y desconozca a Cristo, sus verdades y caminos, y actúe contra sus conciencias. El indocto y pobre, que son de corazón simple, extraen prestamente inferencias apropiadas de las pruebas de la luz del evangelio, pero aquellos cuyos deseos son de otro camino, aunque estén siempre aprendiendo, nunca llegan al conocimiento de la verdad.</p>
<br/>
<p class="text-justify">Vv. 24-34.Como las misericordias de Cristo son de valor supremo para quienes perciben sus necesidades, eran ciegos y ahora ven; así, los afectos más poderosos y duraderos por Cristo surgen de conocerle verdaderamente.
Aunque no podemos decir cuándo, cómo y por cuales pasos se obró el cambio bendito de la obra de gracia en el alma, aun así, podemos tener el consuelo, si por gracia podemos decir: Yo era ciego, pero ahora veo. Yo llevaba una vida mundana sensual pero ahora, gracias a Dios, es lo contrario, Efesios v, 8. Indudablemente prodigiosa es la incredulidad de los que disfrutan los medios de conocimiento y convicción. Todos los que han sentido el poder y la gracia del Señor Jesús, se maravillan ante la disposición voluntaria de otros que le rechazan. Este les discute con fuerza que no sólo Jesús no era pecador, sino que era de Dios. Que cada uno de nosotros podamos saber por esto si somos o no de Dios: ¿Qué hacemos? ¿Qué hacemos por Dios? ¿Qué hacemos por nuestra alma? ¿Qué hacemos más que otros?</p>
<br/>
<p class="text-justify">Vv. 35-38.Cristo reconoce a quienes le reconocen a Él, su verdad y sus caminos. Se nota en particular a los que sufren en la causa de Cristo y del testimonio de una buena conciencia. Nuestro Señor Jesús se revela por gracia al hombre. Ahora éste fue hecho sensato; qué misericordia inexpresable fue ser curado de su ceguera, para que pudiera ver al Hijo de Dios. Nadie sino Dios debe ser adorado; así que, al adorar a Jesús, le reconoció como Dios. Le adorarán todos los que creen en Él.</p>
<br/>
<p class="text-justify">Vv. 39-41.Cristo vino al mundo a dar vista a los espiritualmente ciegos. Además, para que los que ven sean cegados; para que los que tienen un elevado concepto de su propia sabiduría, sean sellados en su ignorancia. La predicación de la cruz era considerada locura por quienes no conocieron a Dios por la sabiduría carnal. Nada fortifica los corazones corruptos de los hombres contra las convicciones de la palabra más que la elevada opinión que los otros tienen de ellos; como si todo lo que los hombres aplauden, debiera ser aceptado por Dios.
Cristo los silenció, pero persiste el pecado del vanidoso y del que confía en sí mismo; ellos rechazan el evangelio de la gracia, por tanto, la culpa de su pecado sigue sin ser perdonada, y el poder de su pecado sigue intacto.</p>
<br/>




</div>
