<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 11</h2>
<p class="text-justify">Vv. 1-6.Estar enfermos no es nada nuevo para quienes Cristo ama; las dolencias corporales corrigen la corrupción y prueban las gracias del pueblo de Dios. Él no vino a resguardar a su pueblo de estas aflicciones, sino a salvarlos de sus pecados, y de la ira venidera; sin embargo, nos corresponde apelar a Él por cuenta de nuestros amigos y parientes cuando están enfermos y afligidos. Que esto nos reconcilie con el lado más oscuro de la Providencia, que todo es para la gloria de Dios: así son enfermedad, pérdida, desilusión; y debemos satisfacernos si Dios es glorificado. Jesús amaba a Marta, a su hermana y a Lázaro. Favorecidas grandemente son las familias en que abundan el amor y la paz, pero son felices hasta lo sumo aquellas a las que Jesús ama, y por las que es amado. Ay, que este raras veces sea el caso de cada persona, aun en familias pequeñas.
Dios tiene intenciones buenas aun cuando parece demorar. Cuando tarda la obra de liberación temporal o espiritual, pública o personal, se debe a que espera el momento oportuno.</p>
<br/>
<p class="text-justify">Vv. 7-10.Cristo nunca pone en peligro a su pueblo si no va con ellos. Somos dados a pensar que somos celosos por el Señor cuando, en realidad, somos celosos sólo por nuestra riqueza, crédito, comodidad y seguridad; por tanto, necesitamos probar nuestros principios. Nuestro día será prolongado hasta que nuestra obra esté hecha y finalizado nuestro testimonio. El hombre tiene consuelo y satisfacción mientras va en el camino de su deber, según lo estipule la palabra de Dios, y esté determinado por la providencia de Dios. Donde quiera que Cristo fue, anduvo en el día, y así nosotros si seguimos sus pasos. Si un hombre anda en el camino de su corazón, conforme al rumbo de este mundo, si considera más sus razonamientos carnales que la voluntad y la gloria de Dios, cae en tentaciones y trampas. Tropieza porque no hay luz en él, porque la luz en nosotros es a nuestras acciones morales como la luz alrededor de nosotros es a nuestras acciones naturales.</p>
<br/>
<p class="text-justify">Vv. 11-16.Puesto que estamos seguros de resucitar al final, ¿por qué la esperanza que cree en la resurrección a la vida eterna, no nos facilita el sacarnos el cuerpo y morir, como si fuera sacarse la ropa e irse a dormir? Cuando muere el cristiano verdadero no hace sino dormir; descansa de las labores del día pasado. Sí, de aquí que la muerte sea mejor que dormir, porque dormir es sólo un descanso breve, pero la muerte es el fin de todas las preocupaciones y esfuerzos terrenales. Los discípulos pensaban que ahora no era necesario que Cristo fuera donde Lázaro y se expusiera Él junto con ellos. Así, a menudo, esperamos que la buena obra que somos llamados a hacer, sea hecha por alguna otra mano si hay riesgos en hacerla. Pero cuando Cristo resucitó a Lázaro de entre los muertos, muchos fueron llevados a creer en Él; y se hizo mucho para perfeccionar la fe de los que creyeron. Vayamos a Él ; la muerte no puede separarnos del amor de Cristo ni ponernos fuera del alcance de su llamado.
Como Tomás, los cristianos deben animarse unos a otros en tiempos difíciles. La muerte del Señor Jesús debe darnos la disposición de morir cuando Dios nos llame.</p>
<br/>
<p class="text-justify">Vv. 17-32.Aquí había una casa donde estaba el temor de Dios y sobre la cual reposaba su bendición, pero fue hecha casa de duelo. La gracia evita el duelo en el corazón, pero no el de la casa.
Cuando Dios, por su gracia y providencia, viene a nosotros por caminos de misericordia y consuelo, como Marta, debemos salir por fe, esperanza y oración a encontrarlo. Cuando Marta salió a encontrar a Jesús, María se quedó tranquila en casa; anteriormente este temperamento fue ventajoso para ella, cuando la puso a los pies de Cristo para oír su palabra, pero en el día de la aflicción, el mismo temperamento la dispuso a la melancolía. Sabiduría nuestra es velar contra la tentación y usar las ventajas de nuestro temperamento natural.
Cuando no sabemos qué pedir o esperar en particular, encomendémonos a Dios; dejémosle hacer lo que le plazca. Para aumentar las expectativas de Marta, nuestro Señor declara que es la Resurrección y la Vida. Es la resurrección en todo sentido: fuente, sustancia, primicia, y causa de la resurrección. El alma redimida vive feliz después de la muerte y, después de la resurrección, el cuerpo y el alma son resguardados de todo mal para siempre.
Cuando leamos u oigamos la palabra de Cristo sobre las grandes cosas del otro mundo, debemos preguntarnos ¿creemos esta verdad? Las cruces y los consuelos de esta época no nos impresionarían tan profundamente como lo hacen, si creyéramos como debemos las cosas de la eternidad.
Cuando Cristo, nuestro Maestro, viene, nos llama. Él viene en su palabra y ordenanza, y nos llama a ellas, nos llama por ellas, y nos llama a sí mismo. Los que, en un día de paz, se ponen a los pies de Cristo para que les enseñe, pueden, con consuelo, echarse a sus pies para hallar su favor en un día de inquietud.</p>
<br/>
<p class="text-justify">Vv. 33-46.La tierna simpatía de Cristo por estos amigos afligidos se manifestó por la angustia de su Espíritu. Él es afligido en todas las aflicciones de los creyentes. Su preocupación por ellos lo demuestra su bondadosa pregunta por los restos de su amigo fallecido. Él actúa en la forma y a la manera de los hijos de los hombres, al ser hallado a semejanza de hombre. Eso lo demostró por sus lágrimas. Era varón de dolores y experimentado en quebranto. Las lágrimas de compasión se parecen a las de Cristo, pero éste nunca aprobó esa sensibilidad de la cual se enorgullecen tantos de los que lloran por simples relatos de problemas, pero se endurecen ante el ay de verdad. Nos da el ejemplo al apartarse de las escenas de hilaridad frívola, para que consolemos al afligido. No tenemos un sumo sacerdote que no pueda compadecerse de nuestras debilidades.
Es un buen paso para levantar un alma a la vida espiritual, cuando se quita la piedra, cuando se eliminan y superan los prejuicios, dando lugar para que la palabra entre al corazón. Si recibimos la palabra de Cristo, y confiamos en su poder y fidelidad, veremos la gloria de Dios y nos alegraremos al verla. Nuestro Señor Jesús nos enseña, con su ejemplo, a llamar Padre a Dios en la oración y a acercarnos a Él como hijos al padre, con reverencia humilde, pero con santa osadía. Habló directamente a Dios con los ojos alzados y en voz alta, para que ellos se convencieran que el Padre le había enviado al mundo como su Hijo amado. -Él podía resucitar a Lázaro por el ejercicio silencioso de su poder y voluntad, y la obra invisible del Espíritu de vida, pero lo hizo en voz alta. Era un tipo del llamado del evangelio por el cual se sacan las almas muertas de la tumba del pecado: tipo del sonido de la trompeta del arcángel del último día, con que serán despertados todos los que duermen en el polvo, y serán convocados a comparecer ante el gran tribunal. La tumba del pecado y este mundo no son lugar para aquellos que Cristo revivió; ellos deben salir. Lázaro fue revivido completamente y regresó, no sólo a la vida, sino a la salud. El pecador no puede revivir su propia alma, pero tiene que usar los medios de gracia; el creyente no puede santificarse a sí mismo, pero tiene que dejar de lado todo peso y estorbo. No podemos convertir a nuestros parientes y amistades, pero debemos instruirlos, precaverlos e invitarlos.</p>
<br/>
<p class="text-justify">Vv. 47-53.Difícilmente haya un descubrimiento más claro de la locura del corazón del hombre y de su enemistad enconada contra Dios que lo aquí registrado. Las palabras de la profecía en la boca no son prueba clara de un principio de gracia en el corazón. Por el pecado tomamos el rumbo más eficaz para echarnos encima la calamidad, de la cual procuramos escapar, como hacen quienes creen que fomentan su propio interés mundano oponiéndose al reino de Cristo. Lo que el impío teme le vendrá. La conversión de las almas es la reunión de ellas con Cristo como su rey y refugio; Él murió para efectuar esto. Al morir las compró para sí mismo, y adquirió el don del Espíritu Santo para ellas: Su amor al morir por los creyentes debe unirlos estrechamente.</p>
<br/>
<p class="text-justify">Vv. 54-57.Debemos renovar nuestro arrepentimiento antes de la pascua del evangelio. Así, por una purificación voluntaria y por ejercicios religiosos, muchos, más devotos que su prójimo, pasan un tiempo en Jerusalén antes de la pascua. Cuando esperamos reunirnos con Dios debemos prepararnos con solemnidad. Ningún artificio del hombre puede alterar los propósitos de Dios, y aunque los hipócritas se diviertan con formas y disputas, y los hombres mundanos procuren sus propios planes, Jesús sigue ordenando todas las cosas para su gloria y para la salvación de su pueblo.</p>
<br/>




</div>
