<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 1</h2>
<p class="text-justify">Vv. 1-5.La razón más simple del por qué se llama Verbo al Hijo de Dios, parece ser, que como nuestras palabras explican nuestras ideas a los demás, así fue enviado el Hijo de Dios para revelar el pensamiento de Su Padre al mundo.
Lo que dice el evangelista acerca de Cristo prueba que Él es Dios. Afirma su existencia en el comienzo; su coexistencia con el Padre. El Verbo estaba con Dios. Todas las cosas fueron hechas por Él, y no como instrumento. Sin Él nada de lo que ha sido hecho fue hecho, desde el ángel más elevado hasta el gusano más bajo. Esto muestra cuán bien calificado estaba para la obra de nuestra redención y salvación. La luz de la razón, y la vida de los sentidos, deriva de Él, y depende de Él. Este Verbo eterno, esta Luz verdadera resplandece, pero las tinieblas no la comprendieron. Oremos sin cesar que nuestros ojos sean abiertos para contemplar esta Luz, para que andemos en ella; y así seamos hechos sabios para salvación por fe en Jesucristo.</p>
<br/>
<p class="text-justify">Vv. 6-14.Juan el Bautista vino a dar testimonio de Jesús. Nada revela con mayor plenitud las tinieblas de la mente de los hombres que cuando apareció la Luz y hubo necesidad de un testigo para llamar la atención a ella. Cristo era la Luz verdadera; esa gran Luz que merece ser llamada así. Por su Espíritu y gracia ilumina a todos los que están iluminados para salvación; y los que no están iluminados por Él, perecen en las tinieblas. Cristo estuvo en el mundo cuando asumió nuestra naturaleza y habitó entre nosotros. El Hijo del Altísimo estuvo aquí en este mundo inferior. Estuvo en el mundo, pero no era del mundo. Vino a salvar a un mundo perdido, porque era un mundo de Su propia hechura. Sin embargo, el mundo no le conoció. Cuando venga como Juez, el mundo le conocerá. Muchos dicen que son de Cristo, aunque no lo reciben porque no dejan sus pecados ni permiten que Él reine sobre ellos.
Todos los hijos de Dios son nacidos de nuevo. Este nuevo nacimiento es por medio de la palabra de Dios, 1 Pedro i, 23, y por el Espíritu de Dios en cuanto a Autor. Por su presencia divina Cristo siempre estuvo en el mundo, pero, ahora que iba a llegar el cumplimiento del tiempo, Él fue, de otra manera, Dios manifestado en la carne. Obsérvese, no obstante, los rayos de su gloria divina que perforaron este velo de carne. Aunque tuvo en la forma de siervo, en cuanto a las circunstancias externas, respecto de la gracia su forma fue la del Hijo de Dios cuya gloria divina se revela en la santidad de su doctrina y en sus milagros. Fue lleno de gracia, completamente aceptable a su Padre, por tanto, apto para interceder por nosotros; y lleno de verdad, plenamente consciente de las cosas que iba a revelar.</p>
<br/>
<p class="text-justify">Vv. 15-18.Cronológicamente y en la entrada en su obra, Cristo vino después de Juan, pero en toda otra forma fue antes que él. La expresión muestra claramente que Jesús tenía existencia antes de aparecer en la tierra como hombre. En Él habita toda plenitud, de quien solo los pecadores caídos tienen, y recibirán por fe, todo lo que los hace sabios, fuertes, santos, útiles y dichosos. Todo lo que recibimos por Cristo se resume en esta sola palabra: gracia; recibimos: “gracia sobre gracia”un don tan grande, tan rico, tan inapreciable; la buena voluntad de Dios para con nosotros, y la buena obra de Dios en nosotros. La ley de Dios es santa, justa y buena; y debemos hacer el uso apropiado de ella. Pero no podemos derivar de ella el perdón, la justicia o la fuerza. Nos enseña a adornar la doctrina de Dios nuestro Salvador, pero no puede tomar el lugar de esa doctrina. Como ninguna misericordia procede de Dios para los pecadores sino por medio de Jesucristo, ningún hombre puede ir al Padre sino por Él; nadie puede conocer a Dios salvo que Él lo dé a conocer en el Hijo unigénito y amado.</p>
<br/>
<p class="text-justify">Vv. 19-28.Juan niega ser el Cristo esperado. Vino en el espíritu y el poder de Elías, pero no era la persona de Elías. Juan no era aquel Profeta del cual Moisés habló, que el Señor levantaría de sus hermanos como para Él. No era el profeta que ellos esperaban los rescataría de los romanos. Se presentó de tal manera que podría haberlos despertado y estimulado para que lo escucharan. Bautizó a la gente con agua como profesión de arrepentimiento y como señal externa de las bendiciones espirituales que les conferiría el Mesías, que estaba en medio de ellos, aunque ellos no le conocieron, Aquel al cual él era indigno de dar el servicio más vil.</p>
<br/>
<p class="text-justify">Vv. 29-36.Juan vio a Jesús que venía a él, y lo señaló como el Cordero de Dios. El cordero pascual, en el derramamiento y rociamiento de su sangre, el asar y comer su carne y todas las demás circunstancias de la ordenanza, representaban la salvación de los pecadores por fe en Cristo. Los corderos sacrificados cada mañana y cada tarde pueden referirse sólo a Cristo muerto como sacrificio para redimirnos para Dios por su sangre. Juan vino como predicador de arrepentimiento, aunque dijo a sus seguidores que tenían que buscar el perdón de sus pecados sólo en Jesús y en su muerte. Concuerda con la gloria de Dios perdonar a todos los que dependen del sacrificio expiatorio de Cristo. Él quita el pecado del mundo; adquiere perdón para todos los que se arrepienten y creen el evangelio. Esto alienta nuestra fe; si Cristo quita el pecado del mundo entonces, ¿por qué no mi pecado? Él llevó el pecado por nosotros y, así, lo quita de nosotros. Dios pudiera haber quitado el pecado quitando al pecador, como quitó el pecado del viejo mundo, pero he aquí una manera de quitar pecado salvando al pecador, haciendo pecado a su Hijo, esto es, haciéndole ofrenda por el pecado por nosotros. Véase a Jesús quitando el pecado y que eso nos haga odiar el pecado y decidirnos en su contra. No nos aferremos de eso que el Cordero de Dios vino a quitar.
Para confirmar su testimonio de Cristo, Juan declara su aparición a su bautismo, cosa que el mismo Dios atestiguó. Vio y tomó nota de que es el Hijo de Dios. Este es el fin y el objetivo del testimonio de Juan: que Jesús era el Mesías prometido. Juan aprovechó toda oportunidad que se le ofreció para guiar la gente a Cristo.</p>
<br/>
<p class="text-justify">Vv. 37-42.El argumento más fuerte y dominante de un alma vivificada para seguir a Cristo es que Él es el único que quita el pecado. Cualquiera sea la comunión que haya entre nuestras almas y Cristo, Él es quien empieza la conversación. Preguntó, ¿qué buscáis? La pregunta que les hace Jesús es la que debiéramos hacernos todos cuando empezamos a seguirle, ¿qué queremos y qué deseamos? Al seguir a Cristo, ¿buscamos el favor de Dios y la vida eterna? Los invita a acudir sin demora. Ahora es el tiempo aceptable, 2 Corintios vi, 2. Bueno es para nosotros estar donde esté Cristo, dondequiera que sea.
Debemos trabajar por el bienestar espiritual de nuestros parientes, y procurar llevarlos a Él. Los que van a Cristo deben ir con la resolución fija de ser firmes y constantes en Él, como piedra, sólida y firme; y es por su gracia que son así.</p>
<br/>
<p class="text-justify">Vv. 43-51.Véase la naturaleza del cristianismo verdadero: seguir a Jesús; dedicarnos a Él y seguir sus pisadas. Fijaos en la objeción que hizo Natanael. Todos los que desean aprovechar la palabra de Dios deben cuidarse de los prejuicios contra lugares o denominaciones de los hombres. Deben examinarse por sí mismos y, a veces, hallarán el bien donde no lo buscaron. Mucha gente se mantiene fuera de los caminos de la religión por los prejuicios irracionales que conciben. La mejor manera de eliminar las falsas nociones de la religión es juzgarla.
No había engaño en Natanael. Su profesión no era hipócrita. No era un simulador ni deshonesto; era un carácter sano, un hombre realmente recto y piadoso. Cristo sabe, sin duda, lo que son los hombres. ¿Nos conoce? Deseemos conocerle. Procuremos y oremos para ser un verdadero israelita en quien no hay engaño, cristianos verdaderamente aprobados por el mismo Cristo. Algunas cosas débiles, imperfectas y pecaminosas se encuentran en todos, pero la hipocresía no corresponde al carácter del creyente. Jesús dio testimonio de lo que pasó cuando Natanael estaba debajo de la higuera. Probablemente, entonces, estaban orando con fervor, buscando dirección acerca de la Esperanza y el Consuelo de Israel, donde ningún ojo humano lo viera. Esto le demostró que nuestro Señor conocía los secretos de su corazón.
Por medio de Cristo tenemos comunión con los santos ángeles y nos beneficiamos de ellos; y se reconcilian y unen las cosas del cielo y las cosas de la tierra.</p>
<br/>




</div>
