<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 3</h2>
<p class="text-justify">Vv. 1-8.Nicodemo temía, o se avergonzaba de ser visto con Cristo, por tanto, acudió de noche. Cuando la religión está fuera de moda, hay muchos Nicodemos, pero aunque vino de noche, Jesús lo recibió, y por ello nos enseña a animar los buenos comienzos, aunque sean débiles. Aunque esta vez vino de noche, después reconoció públicamente a Cristo. No habló con Cristo de asuntos de estado, aunque era un gobernante, sino de los intereses de su propia alma y de su salvación, hablando al respecto de una sola vez.
Nuestro Salvador habla de la necesidad y naturaleza de la regeneración o nuevo nacimiento y, de inmediato llevó a Nicodemo a la fuente de santidad del corazón. El nacimiento es el comienzo de la vida; nacer de nuevo es empezar a vivir de nuevo, como los que han vivido muy equivocados o con poco sentido. Debemos tener una nueva naturaleza, nuevos principios, nuevos afectos, nuevas miras. Por nuestro primer nacimiento somos corruptos, formados en el pecado; por tanto, debemos ser hechos nuevas criaturas. No podía haberse elegido una expresión más fuerte para significar un cambio de estado y de carácter grande y muy notable. Debemos ser enteramente diferentes de lo que fuimos antes, como aquello que empieza a ser en cualquier momento, no es, y no puede ser lo mismo que era antes. Este nuevo nacimiento es del cielo, capítulo i, 13, y tiende al cielo. Es un cambio grande hecho en el corazón del pecador por el poder del Espíritu Santo. Significa que algo es hecho en nosotros y a favor de nosotros que no podemos hacer por nosotros mismos. Algo obra por lo que empieza una vida que durará por siempre. De otra manera no podemos esperar un beneficio de Cristo; es necesario para nuestra felicidad aquí y en el más allá.
Nicodemo entendió mal lo que dijo Cristo, como si no hubiera otra manera de regenerar y moldear de nuevo un alma inmortal que volver a dar un marco al cuerpo. Sin embargo, reconoció su ignorancia, lo que muestra el deseo de ser mejor informado. Entonces, el Señor Jesús explica más. Muestra al Autor de este bendito cambio. No es obra de nuestra sabiduría o poder propio, sino del poder del bendito Espíritu. Somos formados en iniquidad, lo que hace necesario que nuestra naturaleza sea cambiada. No tenemos que maravillarnos de esto, porque cuando consideramos la santidad de Dios, la depravación de nuestra naturaleza, y la dicha puesta ante nosotros, no tenemos que pensar que es raro que se ponga tanto énfasis sobre esto.
La obra regeneradora del Espíritu Santo se compara con el agua. También es probable que Cristo se haya referido a la ordenanza del bautismo. No se trata que sean salvos todos aquellos bautizados, y sólo ellos; pero sin el nuevo nacimiento obrado por el Espíritu, y significado por el bautismo, nadie será súbdito del reino del cielo.
La misma palabra significa viento y Espíritu. El viento sopla de donde quiere hacia nosotros; Dios lo dirige. El Espíritu envía sus influencias donde, y cuando, y a quien, y en qué medida y grado le plazca. Aunque las causas estén ocultas, los efectos son evidentes, cuando el alma es llevada a lamentarse por el pecado y a respirar según Cristo.</p>
<br/>
<p class="text-justify">Vv. 9-13.La exposición hecha por Cristo de la doctrina y la necesidad de la regeneración pareciera no haber quedado clara para Nicodemo. Así, las cosas del Espíritu de Dios son necedad para el hombre natural. Muchos piensan que no puede ser probado lo que no pueden creer.
El discurso de Cristo sobre las verdades del evangelio, versículos 11-13, muestra la necedad de aquellos que hacen que estas cosas sean extrañas para ellos; y nos recomienda que las investiguemos. Jesucristo es capaz en toda forma de revelarnos la voluntad de Dios; porque descendió del cielo, y aún está en el cielo. Aquí tenemos una nota de las dos naturalezas distintas de Cristo en una persona, de modo que es el Hijo del Hombre, aunque está en el cielo. Dios es “EL QUE ES”y el cielo es la habitación de su santidad. Este conocimiento debe venir de lo alto y solo puede ser recibido por fe.</p>
<br/>
<p class="text-justify">Vv. 14-18.Jesucristo vino a salvarnos sanándonos, como los hijos de Israel, picados por serpientes ardientes fueron curados y vivieron al mirar a la serpiente de bronce, Números xxi, 6-9. Obsérvese en esto la naturaleza mortal y destructora del pecado. Pregúntese a conciencias vivificadas, pregúntese a pecadores condenados, quienes dirán que, por encantadoras que sean las seducciones del pecado, al final muerde como serpiente. Véase el remedio poderoso contra esta enfermedad fatal. Cristo nos es propuesto claramente en el evangelio. Aquel a quien ofendimos es nuestra Paz, y la manera de solicitar la curación es creer. Si alguien hasta ahora toma livianamente la enfermedad del pecado o el método de curación de Cristo, y no recibe a Cristo en las condiciones que Él pone, su ruina pende sobre su cabeza. Él dijo: Mirad y sed salvos, mirad y vivid; alzad los ojos de la fe a Cristo crucificado. Mientras no tengamos la gracia para hacer esto, no seremos curados, sino seguiremos heridos por los aguijones de Satanás, y en estado moribundo.
Jesucristo vino a salvarnos perdonándonos, para que no muriéramos por la sentencia de la ley. He aquí el evangelio, la verdadera, la buena nueva. He aquí al amor de Dios al dar a su Hijo por el mundo. Tanto amó Dios al mundo, tan verdaderamente, tan ricamente. ¡Mirad y maravillaos, que el gran Dios ame a un mundo tan indigno! -Aquí, también, está el gran deber del evangelio: creer en Jesucristo. Habiéndolo dado Dios para que fuera nuestro Profeta, Sacerdote y Rey, nosotros debemos darnos para ser gobernados y enseñados, y salvados por Él. He aquí el gran beneficio del evangelio, que quienquiera que crea en Cristo no perecerá mas tendrá vida eterna. Dios estaba en Cristo reconciliando al mundo consigo mismo, y de ese modo, lo salvaba. No podía ser salvado sino por medio de Él; en ningún otro hay salvación.
De todo esto se muestra la dicha del creyente verdadero: el que cree en Cristo no es condenado. Aunque ha sido un gran pecador, no se le trata según lo que merecen sus pecados.</p>
<br/>
<p class="text-justify">Vv. 18-21.¡Cuán grande es el pecado de los incrédulos! Dios envió a Uno que era el más amado por Él, para salvarnos; ¿y no será el más amado para nosotros? ¡Cuán grande es la miseria de los incrédulos! Ya han sido condenados, lo que habla de una condenación cierta ; una condenación presente . La ira de Dios ahora se desata sobre ellos; y los condenan sus propios corazones. También hay una condenación basada en su culpa anterior ; ellos están expuestos a la ley por todos sus pecados; porque no están interesados por fe en el perdón del evangelio. La incredulidad es un pecado contra el remedio. Brota de la enemistad del corazón del hombre hacia Dios, del amor al pecado en alguna forma. Léase también la condenación de los que no quieren conocer a Cristo. Las obras pecadoras son las obras de las tinieblas. El mundo impío se mantiene tan lejos de esta luz como puede, no sea que sus obras sean reprobadas. Cristo es odiado porque aman el pecado. Si no odiaran el conocimiento de la salvación, no se quedarían contentos en la ignorancia condenadora.
Por otro lado, los corazones renovados dan la bienvenida a la luz. Un hombre bueno actúa verdadera y sinceramente en todo lo que hace. Desea saber cuál es la voluntad de Dios, y hacerla, aunque sea contra su propio interés mundanal. Ha tenido lugar un cambio en todo su carácter y conducta. El amor a Dios es derramado en su corazón por el Espíritu Santo, y llega a ser el principio rector de sus acciones. En la medida que siga bajo una carga de culpa no perdonada, solo puede tener un temor servil a Dios, pero cuando sus dudas se disipan, cuando ve la base justa sobre la cual se edifica su perdón, lo asume como si fuera propio, y se une con Dios por un amor sin fingimiento. Nuestras obras son buenas cuando la voluntad de Dios es la regla de ellas, y la gloria de Dios, su finalidad; cuando se hacen en su poder y por amor a Él; a Él, y no a los hombres.
La regeneración, o el nuevo nacimiento, es un tema al cual el mundo tiene aversión; sin embargo, es el gran ganancia en comparación con la cual todo lo demás no es sino fruslería. ¿Qué significa que tengamos comida para comer con abundancia, y una variedad de ropa para ponernos, si no hemos nacido de nuevo? ¿Si después de unas cuantas mañanas y tardes pasadas en alegría irracional, placer carnal y desorden, morimos en nuestros pecados y yacemos en el dolor? ¿De que vale que seamos capaces de desempeñar nuestra parte en la vida, en todo otro aspecto, si al final oímos de parte del Juez Supremo: “Apartaos de mí, no os conozco, obradores de maldad?”</p>
<br/>
<p class="text-justify">Vv. 22-36.Juan se satisfizo por completo con el lugar y la obra asignada, pero Jesús vino a una obra más importante. Él también sabía que Jesús crecería en honor e influencia, porque de Su reino y la paz no habría fin, mientras a él lo seguirían cada vez menos. Juan sabía que Jesús vino del cielo como el Hijo de Dios, mientras él era un hombre mortal y pecador, que sólo podía hablar de las cosas más sencillas de la religión. Las palabras de Jesús eran la palabra de Dios; Él tenía el Espíritu, no según medida como los profetas, sino en toda su plenitud. La vida eterna puede tenerse sólo por fe en Él, y así puede obtenerse; pero no pueden participar de la salvación todos los que no creen en el Hijo de Dios, sino que la ira de Dios está sobre ellos para siempre.</p>
<br/>




</div>
