<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 15</h2>
<p class="text-justify">Vv. 1-8.Jesucristo es la Vid, la Vid verdadera. La unión de la naturaleza divina con la humana, y la plenitud del Espíritu que hay en Él, recuerdan la raíz de la vida que fructifica por la humedad de la buena tierra. Los creyentes son los pámpanos de esta Vid. La raíz no se ve y nuestra vida está escondida con Cristo; la raíz sustenta al árbol, le difunde la savia, y en Cristo están todos los sustentos y provisiones. Los pámpanos de la vid son muchos, pero al unificarse en la raíz no son sino una sola vid; de este modo, todos los cristianos verdaderos, aunque disten entre sí en cuanto a lugar y opinión, se unen en Cristo. Los creyentes, como los pámpanos de la vid, son débiles e incapaces de permanecer, sino como nacieron.
El Padre es el Dueño de la vid. Nunca hubo un dueño tan sabio, tan cuidadoso con su viña como Dios por su Iglesia que, por eso, debe prosperar. Debemos ser fructíferos. Esperamos uvas de una vid, y del cristiano esperamos un temperamento, una disposición y una vida cristiana. Debemos honrar a Dios y hacer el bien, esto es, llevar fruto. Los estériles son cortados. Hasta las ramas fructíferas necesitan poda, porque, en el mejor de los casos, tenemos ideas, pasiones y humores que requieren ser quitados, cosa que Cristo ha prometido hacer por su palabra, Espíritu y providencia. Si se usan medios drásticos para avanzar la santificación de los creyentes, ellos estarán agradecidos por ellos. La palabra de Cristo se da a todos los creyentes; y hay en esa palabra una virtud que limpia al obrar la gracia y deshacer la corrupción. Mientras más fruto demos, más abundaremos en lo que es bueno, y más glorificado será nuestro Señor.
Para fructificar debemos permanecer en Cristo, debemos estar unidos a Él por la fe. El gran interés de todos los discípulos de Cristo es mantener constante la dependencia de Cristo y la comunión con Él. Los cristianos verdaderos hallan, por experiencia, que toda interrupción del ejercicio de su fe hace que mengüen los afectos santos, revivan sus corrupciones y languidezcan sus consolaciones. Los que no permanecen en Cristo, aunque florezcan por un tiempo en la profesión externa, llegan, no obstante, a nada. El fuego es el lugar más adecuado para las ramas marchitas; no son buenas para otra cosa. Procuremos vivir más simplemente de la plenitud de Cristo, y crecer más fructíferos en todo buen decir y hacer, para que sea pleno nuestro gozo en Él y en su salvación.</p>
<br/>
<p class="text-justify">Vv. 9-17.Aquellos a quienes Dios ama como Padre pueden despreciar el odio de todo el mundo. Como el Padre amó a Cristo que fue digno hasta lo sumo, así amó a sus discípulos, que eran indignos. Todos los que aman al Salvador deben perseverar en su amor por Él, y aprovechar todas las ocasiones para demostrarlo. El gozo del hipócrita dura sólo un momento, pero el gozo de los que permanecen en Cristo es una fiesta continua. Tienen que demostrar su amor por Él obedeciendo sus mandamientos. Si el mismo poder que primero derramó el amor de Cristo en nuestros corazones, no nos mantuviera en ese amor, no permaneceríamos en ese amor por mucho tiempo.
El amor de Cristo por nosotros debe llevarnos a amarnos mutuamente. Él habla como si estuviera por encargar muchas cosas, pero nombra sólo a esta: abarca muchos deberes.</p>
<br/>
<p class="text-justify">Vv. 18-25.¡Qué poco piensan muchas personas que al oponerse a la doctrina de Cristo como Profeta, Sacerdote y Rey, se muestran ignorantes del único Dios vivo y verdadero, al cual profesan adorar! El nombre en el cual son bautizados los discípulos de Cristo es aquel por el cual vivirán y morirán. Consuelo es para los grandes dolientes si sufren por amor al nombre de Cristo. La ignorancia del mundo es la causa verdadera de su odio por los discípulos de Jesús. Mientras más claros y plenos sean los descubrimientos de la gracia y verdad de Cristo, más grande es nuestro pecado si no le amamos ni creemos en Él.</p>
<br/>
<p class="text-justify">Vv. 26, 27.El Espíritu bendito mantendrá la causa de Cristo en el mundo, a pesar de la resistencia que encuentra. Los creyentes enseñados y exhortados por sus influencias deben dar testimonio de Cristo y su salvación.</p>
<br/>




</div>
