<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Juan 16</h2>
<p class="text-justify">Vv. 1-6.Nuestro Señor Jesús al dar a sus discípulos la noticia de tribulaciones se propuso que el terror no fuera una sorpresa para ellos. Puede que los enemigos reales, que están al servicio de Dios, finjan celo por éste, lo que no aminora el pecado de los perseguidores; las villanías nunca cambian por adosarles el nombre de Dios. Como Jesús en sus sufrimientos, asimismo sus seguidores en los suyos deben mirar al cumplimiento de la Escritura. No se los dijo antes, porque estaba con ellos para enseñarles, guiarlos y consolarlos; entonces ellos no necesitaban esta promesa de la presencia del Espíritu Santo.
Nos silencia preguntarnos ¿de dónde vienen los problemas? Nos satisfará preguntarnos, ¿adónde van? Porque sabemos que obran para bien. Falta y necedad comunes de los cristianos tristes es mirar sólo el lado oscuro de la nube haciendo oídos sordos a la voz de gozo y júbilo. Lo que llenó de pena los corazones de los discípulos era un afecto demasiado grande por esta vida presente. Nada obstaculiza más nuestro gozo en Dios que el amor al mundo, y la tristeza del mundo que viene con aquel.</p>
<br/>
<p class="text-justify">Vv. 7-15.La partida de Cristo era necesaria para la venida del Consolador. Enviar el Espíritu iba a ser el fruto de la muerte de Cristo, que fue su partida. Su presencia corporal podía estar solamente en un lugar a la vez, pero su Espíritu está en todas partes, en todos los lugares, en todos los tiempos, dondequiera que dos o tres estén reunidos en su nombre.
Véase en esto el oficio del Espíritu, primero reprobar , o convencer de pecado. La obra de convicción de pecado es obra del Espíritu, que puede hacerla eficazmente, y nadie sino Él solamente. El Espíritu Santo adopta el método de condenar el pecado primero, y luego consolar. El Espíritu convencerá al mundo de pecado ; simplemente no se limitará a decírselo. El Espíritu convence de que el pecado es un hecho; de la falta del pecado; de la necedad del pecado; de la inmundicia del pecado, que por eso llegamos a ser aborrecidos por Dios; de la fuente del pecado: la naturaleza corrupta; y, por último, del fruto del pecado cuyo fin es la muerte. El Espíritu Santo demuestra que todo el mundo es culpable ante Dios. Él convence al mundo de justicia ; que Jesús de Nazaret fue Cristo, el justo; además, de la justicia de Cristo que nos es imputada para justificación y salvación. Él les muestra de dónde se obtiene y cómo pueden ser aceptados por justos según el criterio de Dios. La ascensión de Cristo prueba que el rescate fue aceptado y consumada la justicia por medio de la cual los creyentes iban a ser justificados. De juicio porque el príncipe de este mundo es juzgado. Todo estará bien cuando sea roto el poder del que hizo todo el mal. Como Satanás es vencido por Cristo, esto nos da confianza, porque ningún otro poder puede resistir ante Él. Y del día del juicio.
La venida del Espíritu iba a ser una ventaja indecible para los discípulos. El Espíritu Santo es nuestro Guía, no sólo para mostrarnos el camino, sino para ir con nosotros con ayudas e influencias continuas. Ser guiados a una verdad es más que conocerla apenas; no es tener su noción tan sólo en nuestra cabeza, sino su deleite, su sabor y su poder en nuestros corazones. Él enseñará toda la verdad sin retener nada que sea provechoso, porque mostrará cosas venideras. Todos los dones y las gracias del Espíritu, toda la predicación, y todos los escritos de los apóstoles bajo la influencia del Espíritu, todas las lenguas y milagros, eran para glorificar a Cristo. Corresponde a cada uno preguntarse si el Espíritu Santo ha empezado la buena obra en su corazón. Sin la revelación clara de nuestra culpa y peligro nunca entenderíamos el valor de la salvación de Cristo, pero cuando se nos da a conocer correctamente, empezamos a entender el valor del Redentor. Tendríamos visiones más plenas del Redentor y afectos más vivos por Él si oráramos más por el Espíritu Santo y dependiésemos más de Él.</p>
<br/>
<p class="text-justify">Vv. 16-22.Bueno es considerar cuán cerca de su final están nuestras temporadas de gracia para que seamos estimulados a tener provecho de ellas, porque el dolor de los discípulos serán pronto convertido en gozo, como los de la madre cuando ve a su recién nacido bebé. El Espíritu Santo será el Consolador de ellos y ni los hombres ni los demonios, ni los sufrimientos en la vida y en la muerte, les quitarán para siempre su gozo. Los creyentes tienen gozo o pena según su visión de Cristo y las señales de su presencia. Viene un dolor al impío que nada puede aminorar; el creyente es heredero del gozo que nadie puede quitar. ¿Dónde está ahora el gozo de los asesinos de nuestro Señor y el dolor de sus amigos?</p>
<br/>
<p class="text-justify">Vv. 23-27.Pedirle al Padre muestra la percepción de las necesidades espirituales, y el deseo de bendiciones espirituales con el convencimiento de que deben obtenerse sólo de Dios. Pedir en el nombre de Cristo es reconocer nuestra indignidad para recibir favores de Dios, y demuestra nuestra total dependencia de Cristo como Jehová justicia nuestra.
Nuestro Señor había hablado hasta aquí con frases cortas y de peso o con parábolas, cuya magnitud no captaban plenamente los discípulos, pero después de su resurrección tenía pensado enseñarles claramente cosas referidas al Padre y del camino a Él, por medio de su intercesión. La frecuencia con que nuestro Señor pone en vigencia la ofrenda de peticiones en su nombre, señala que el gran fin de la mediación de Cristo es imprimir en nosotros el profundo sentido de nuestra pecaminosidad y del mérito y poder de su muerte, por lo cual tenemos acceso a Dios. Recordemos siempre que es lo mismo dirigirnos al Padre en el nombre de Cristo que dirigirnos al Hijo en cuanto Dios que habita en la naturaleza humana, y reconcilia al mundo consigo, puesto que Padre e Hijo son uno.</p>
<br/>
<p class="text-justify">Vv. 28-33.He aquí una clara afrimación de la venida de Cristo desde el Padre y de su regreso a Él. En su venida el Redentor fue Dios manifiesto en carne, y en su Partida fue recibido en gloria. Los discípulos aprovecharon el conocimiento diciendo eso; también, en fe: “ahora estamos seguros”. ¡Sí! No conocían su propia debilidad.
La naturaleza divina no desertó de la naturaleza humana, pero la sostuvo y dio consuelo y valor a los sufrimientos de Cristo. Mientras tengamos la presencia favorable de Dios estamos felices y debemos estar tranquilos, aunque todo el mundo nos abandone.
La paz en Cristo es la única paz verdadera, los creyentes la tienen en Él solamente. A través de Él tenemos paz con Dios y, así en Él tenemos paz en nuestra mente. Debemos animarnos porque Cristo ha vencido al mundo ante nosotros, pero mientras pensemos que resistimos, cuidemos de no caer. No sabemos cómo debemos actuar y entramos en tentación: estemos alertas y orando sin cesar para que no seamos dejados solos.</p>
<br/>




</div>
