<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Judas 1</h2>
<p class="text-justify">Vv. 1-4.Los cristianos son llamados del mundo, de su mal espíritu y temperamento; son llamados a ponerse por sobre el mundo, para cosas más elevadas y mejores, para el cielo, para las cosas invisibles y eternas; llamados del pecado a Cristo, de la vanidad a la seriedad, de la inmundicia a la santidad; y esto conforme al propósito y la gracia divino. Si somos santificados y glorificados, todo el honor y la gloria deben atribuirse a Dios y a Él solo. Como es Dios quien empieza la obra de gracia en las almas de los hombres, así es Él quien la ejecuta y la perfecciona. No confiemos en nosotros ni en nuestra cuota de gracia ya recibida, sino en Él y sólo en Él. La misericordia de Dios es el manantial y la fuente de todo lo bueno que tenemos o esperamos; la misericordia, no sólo para el miserable, sino para el culpable. Luego de la misericordia está la paz, que recibimos del sentido de haber obtenido misericordia. De la paz brota el amor; el amor de Cristo a nosotros, nuestro amor a Él, y nuestro amor fraternal de los unos a los otros. El apóstol ruega no que los cristianos se contenten con poco, sino que su alma y sus asociados puedan estar llenas de estas cosas. Nadie es excluido de la oferta e invitación del evangelio, sino los que obstinada y malvadamente se excluyen a sí mismos. Pero la aplicación es para todos los creyentes y sólo para ellos. Es para el débil y para el fuerte.
Los que han recibido la doctrina de esta salvación común deben contender por ella, eficazmente no furiosamente . Mentir en favor de la verdad es malo; castigar en nombre de la verdad, no es mejor. Los que han recibido la verdad deben contender por ella como hicieron los apóstoles; sufriendo con paciencia y valor por ella, no haciendo sufrir a los demás, si ellos no aceptan cada noción de lo que llamamos fe o juzgamos importante. Debemos contender eficazmente por la fe oponiéndonos a los que la corrompen o depravan; los que se infiltran sin ser notados; los que reptan como sierpes. Ellos son los peores impíos, los que toman tan atrevidamente la exhortación a pecar porque la gracia de Dios abundó y aún abunda tan maravillosamente, y los que están endurecidos por la magnitud y plenitud de la gracia del evangelio, cuyo designio es librar al hombre del pecado y llevarlo a Dios.</p>
<br/>
<p class="text-justify">Vv. 5-7.Los privilegios externos, la profesión y la conversión aparente no pueden guardar de la venganza de Dios contra los que se desvían volviéndose a la incredulidad y a la desobediencia. La destrucción de los israelitas incrédulos en el desierto demuestra que nadie debe presumir de sus privilegios. Ellos tuvieron milagros como su pan diario, pero aún así, perecieron en la incredulidad. Un gran número de ángeles no se agradó con los puestos que Dios les asignó; el orgullo fue la causa principal y directa de su caída. Los ángeles caídos están reservados para el juicio del gran día; ¿y los hombres caídos quieren escapar de este? Con toda seguridad que no. Considérese esto en el momento debido. La destrucción de Sodoma es una advertencia a toda voz para todos, para que le prestemos atención, y huyamos de las concupiscencias carnales que batallan contra el alma, 1 Pedro ii, 11. Dios es el mismo Ser puro, justo y santo ahora que entonces. Por lo tanto, temblad y no pequéis, Salmo iv, 4. No descansemos en nada que no someta al alma a la obediencia de Cristo, porque nada sino la renovación de nuestra alma conforme a la imagen divina, que obra el Espíritu Santo, puede impedir que seamos destruidos entre los enemigos de Dios. Considérese el caso de los ángeles y nótese que ninguna dignidad ni valor de criatura sirve. ¡Entonces, cómo debe temblar el hombre que bebe la iniquidad como si fuese agua! Job xv, 16.</p>
<br/>
<p class="text-justify">Vv. 8-16.Los falsos maestros son soñadores; mancillan grandemente y hieren penosamente el alma. Estos maestros son de mente perturbada y espíritu sedicioso; olvidan que las potestades que hay han sido ordenadas por Dios, Romanos xiii, 1.
En cuanto a la disputa por el cuerpo de Moisés, parece que Satanás deseaba dar a conocer el lugar de su sepulcro a los israelitas para tentarlos a adorarle, pero se le impidió y descargó su furor con blasfemias desesperadas. Esto debe recordar a todos los que discuten, que nunca se hagan acusaciones con lenguaje ofensivo. Además, de aquí aprendan que debemos defender a los que Dios reconoce. Difícil, si no imposible, es hallar enemigos de la religión cristiana que no vivan, ni hayan vivido, en abierta o secreta oposición a los principios de la religión natural. Aquí son comparados con las bestias aunque a menudo se jactan de ser los más sabios de la humanidad. Ellos se corrompen en las cosas más sencillas y abiertas. La falta reside, no en sus entendimientos sino en sus voluntades depravadas y en sus apetitos y afectos desordenados.
Gran reproche es para la religión, aunque injusto, que los que la confiesen, se opongan a ella de corazón y vida. El Señor remediará esto a su tiempo y a su modo, no a la manera ciega de los hombres que arrancan las espigas de trigo junto con la cizaña. Triste es que los hombres que empezaron en el Espíritu terminen en la carne. Dos veces muertos: ellos estuvieron muertos en su estado natural caído, pero ahora están muertos de nuevo por las pruebas evidentes de su hipocresía. Árboles muertos, ¡por qué cargan al suelo! ¡Fuera con ellos, al fuego! Las olas rugientes son el terror de los pasajeros que navegan, pero cuando llegan a puerto, el ruido y el terror terminan. Los falsos maestros tienen que esperar el peor castigo en este mundo y en el venidero. Brillan como meteoros o estrellas errantes que caen, y luego, se hunden en la negrura de las tinieblas para siempre.
No hay mención de la profecía de Enoc en otra parte de la Escritura; sin embargo, un texto claro de la Escritura prueba cualquier punto que tengamos que creer. De este descubrimos que la venida de Cristo a juzgar fue profetizada tan al principio como fueron los tiempos anteriores al diluvio. El Señor viene: ¡qué tiempo glorioso será! -Fijaos cuán a menudo se repite la palabra “impío”. Ahora, muchos no se refieren a los vocablos pío o impío a menos que sea para burlarse aun de las palabras; pero no es así en el lenguaje que nos enseña el Espíritu Santo. Las palabras duras de unos a otros, especialmente si están mal fundamentadas, ciertamente serán tomadas en cuenta en el día del juicio.
Los hombres malos y seductores se enojan con todo lo que sucede, y nunca están contentos con su propio estado y condición. Su voluntad y su fantasía son su única regla y ley. Los que complacen sus apetitos pecaminosos tienden más a rendirse a las pasiones ingobernables. Los hombres de Dios, desde el comienzo del mundo, han declarado la condena que se les denunció. Evitemos a los tales. Tenemos que seguir a los hombres que sólo siguen a Cristo.</p>
<br/>
<p class="text-justify">Vv. 17-23.Los hombres sensuales se separan de Cristo y de su Iglesia, y se unen al diablo, al mundo y a la carne, con prácticas impías y pecaminosas. Esto es infinitamente peor que separarse de cualquier rama de la iglesia visible por cuestión de opiniones o modos y circunstancias de gobierno externo o de la adoración. Los hombres sensuales no tienen el espíritu de santidad, y quienquiera no lo tenga, no pertenece a Cristo. La gracia de la fe es santa hasta lo sumo, porque obra por amor, purifica el corazón y vence al mundo por lo cual se distingue de la fe falsa y muerta. Muy probablemente prevalezcan nuestras oraciones cuando oramos en el Espíritu Santo, bajo su dirección y poder, conforme a la regla de su palabra, con fe, fervor y anhelo; esto es orar en el Espíritu Santo. La fe en la expectativa de vida eterna nos armará contra las trampas del pecado: la fe viva en esta bendita esperanza nos ayudará a mortificar nuestras concupiscencias.
Debemos vigilarnos los unos a los otros; fielmente, pero con prudencia para reprobarnos los unos a los otros, y a dar buen ejemplo a todos los que nos rodean. Esto debe hacerse con compasión, diferenciando entre el débil y el soberbio. Debemos tratar a algunos con ternura. A otros, salvar con temor; enfatizando los terrores del Señor. Todas los esfuerzos deben realizarse con aborrecimiento decidido de los delitos, cuidándonos de evitar todo lo que lleve a la comunión con ellos, o que haya estado conectado con ellos, en obras de tinieblas, manteniéndonos lejos de lo que es malo o parece serlo.</p>
<br/>
<p class="text-justify">Vv. 24, 25.Dios es poderoso, y tan dispuesto como poderoso, para impedir que caigamos y para presentarnos sin defecto ante la presencia de su gloria. No como quienes nunca hubiesen faltado, sino como quienes, por la misericordia de Dios, y los sufrimientos y los méritos de un Salvador, hubieran sido, en su gran mayoría, justamente condenados hace mucho tiempo. Todos los creyentes sinceros le fueron dados por el Padre; y de todos los así dados, Él no perdió a ninguno, ni perderá a ninguno. Ahora, nuestras faltas nos llenan de temores, dudas y tristeza, pero el Redentor se ha propuesto que su pueblo sea presentado sin defecto. Donde no hay pecado, no habrá pena; donde hay perfección de santidad, habrá perfección de gozo. Miremos con más frecuencia a Aquel que es capaz de impedir que caigamos, de mejorar y de mantener la obra que ha empezado en nosotros hasta que seamos presentados sin culpa delante de la presencia de su gloria. Entonces, nuestros corazones conocerán un gozo más allá del que puede permitir la tierra; entonces Dios también se regocijará por nosotros y se completará el gozo de nuestro compasivo Salvador. Al que ha formado el plan tan sabiamente, y que lo cumplirá fiel y perfectamente, a Él sea la gloria y la majestad, imperio y potencia, ahora y por todos los siglos. Amén.</p>
<br/>




</div>
