<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jueces 16</h2>
<p class="text-justify">Vv. 1-3.Hasta ahora el carácter de Sansón ha parecido glorioso, aunque poco común. En este capítulo lo hallamos comportándose en forma tan mala que muchos se cuestionan si era o no un hombre santo. Pero el apóstol ha dirimido esto en Hebreos xi, 32. Al dirigir nuestra atención a las doctrinas y ejemplos de la Escritura, a los artificios de Satanás, a lo engañoso del corazón humano y a los métodos con que frecuentemente el Señor trata a su pueblo, podemos aprender lecciones útiles de esta historia, en la cual innecesariamente tropiezan algunos, mientras que otros critican y objetan. El tiempo específico en que vivió Sansón, puede dar razón de muchas cosas que, si se hicieran en nuestra época, y sin el designio especial del Cielo, serían altamente criminales. Puede que él haya hecho muchos ejercicios piadosos que, si se hubieran registrado, hubieran echado una luz diferente a su carácter.
Obsérvese el peligro de Sansón. ¡Oh, que todos los que satisfacen sus apetitos sensuales con borracheras o cualquier lujuria sensual, se vean a sí mismos de este modo rodeados, vencidos y marcados para el desastre por sus enemigos espirituales! Mientras más profundo duerman, más seguros se sienten, pero mayor es su peligro. Esperamos que fuera con una resolución piadosa de no volver a su pecado que él se levantó por miedo del peligro en que estaba. ¿Puedo yo estar a salvo bajo esta culpa? Fue malo que él se echara a dormir sin controlar su situación; pero hubiera sido peor si hubiera permanecido tranquilo.</p>
<br/>
<p class="text-justify">Vv. 4-17.Sansón había sido llevado más de una vez a la maldad y peligro por el amor a las mujeres, sin embargo, no aprendió de tales advertencias, y por tercera vez cayó en la misma trampa y, esta vez fue fatal. El libertinaje es una de las cosas que quita el corazón. Es un pozo profundo en que muchos han caído, y del cual pocos han escapado, y ésos por un milagro de misericordia, con la pérdida de su reputación y la inutilización casi total, excepto su alma. La angustia del sufrimiento es diez mil veces más grande que todos los placeres del pecado.</p>
<br/>
<p class="text-justify">Vv. 18-21.Véase los efectos fatales de la falsa seguridad. Satanás destruye a los hombres halagándolos para que adquieran una buena opinión de su propia firmeza, y así, los lleva a que nada les importe y nada teman; y, entonces, les roba su fuerza y honor, y los lleva cautivos a su voluntad. Cuando dormimos, nuestros enemigos espirituales no duermen. Los ojos de Sansón fueron la entrada de su pecado (versículo 1), y ahora su castigo empieza por los ojos. Los filisteos lo dejaron ciego y tuvo tiempo para recordar que su propia lujuria lo había cegado antes. La mejor forma de preservar los ojos es quitarlos de la vanidad que se contempla. Aprended de su caída; velad cuidadosamente contra todas las concupiscencias carnales; porque toda nuestra gloria se va y nuestra defensa nos abandona cuando profanamos nuestra separación para Dios, en nuestra calidad de nazareos espirituales.</p>
<br/>
<p class="text-justify">Vv. 22-24.Las aflicciones de Sansón fueron el medio de llevarlo al arrepentimiento profundo. Al perder su vista corporal, se abrieron los ojos de su entendimiento; y al privarlo de su fuerza corporal, plugo al Señor renovar su fuerza espiritual. El Señor permite que unos pocos se descarríen lejos y se hundan profundamente, pero al final los recobra y los salva de hundirse en el abismo de la destrucción, marcando su desagrado por el pecado con graves sufrimientos temporales. Los hipócritas pueden abusar de estos ejemplos, y los infieles pueden burlarse de ellos, pero los cristianos verdaderos se harán por ellos, más humildes, dispuestos a velar y ser prudentes, más sencillos en su confianza en el Señor, más fervorosos para orar pidiendo ser guardados de caer, y en la alabanza por haber sido preservados; y, si caen, se les guardará para que no se hundan en la desesperación.</p>
<br/>
<p class="text-justify">Vv. 25-31.Nada completa los pecados de una persona o un pueblo con mayor rapidez que burlarse de los siervos de Dios y maltratarlos, aunque la causa sea su propia necedad. Dios puso en el corazón de Sansón, como personaje público, vengar de esta manera en ellos la lucha de Dios, de Israel y la suya. La fuerza perdida por el pecado, la recuperó por la oración. Esto no fue por pasión ni venganza personal, sino por santo celo por la gloria de Dios e Israel, lo que queda en claro por el hecho de que Dios acepta y responde su oración.
El templo derribado, no por la fuerza natural de Sansón, sino por la omnipotencia de Dios. En su caso estuvo bien que él vindicara la causa de Dios e Israel. No se le debe acusar de suicida. No procuraba su muerte, sino la liberación de Israel y la destrucción de sus enemigos.
Sansón murió encadenado y entre los filisteos como espantoso rechazo de sus pecados, pero murió arrepentido. Los efectos de su muerte tipifican los de la muerte de Cristo que, por su propia voluntad, puso su vida entre transgresores y de esa manera destruyó el fundamento del reino de Satanás, y proveyó para la liberación de Su gente. Aunque fue grande el pecado de Sansón, y aunque mereció los juicios que se acarreó, finalmente halló la misericordia del Señor; y todo penitente que huya a refugiarse en el Salvador cuya sangre limpia de todo pecado, obtendrá misericordia. Pero aquí nada hay que estimule a ceder al pecado, con la esperanza ellos finalmente se arrepentirán y serán salvos.</p>
<br/>




</div>
