<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jueces 1</h2>
<p class="text-justify">Vv. 1-8.Los israelitas estaban convencidos que había que continuar la guerra contra los cananeos; pero dudaban sobre el modo de ejecutarla después de la muerte de Josué. Preguntaron al Señor al respecto. Dios encarga que le sirvan de acuerdo con la fortaleza que Él ha otorgado. De los más capaces se espera más. Judá era el primero en dignidad y debe ser el primero en el deber. El servicio de Judá será de poca utilidad si Dios no da el éxito; pero Dios no dará el éxito a menos que Judá se dedique al servicio. Judá era la más considerable de todas las tribus y Simeón, la menor; sin embargo, Judá implora la amistad de Simeón y les pide socorro. Corresponde a los israelitas ayudarse unos a otros contra los cananeos; todos los cristianos, aun los de tribus diferentes, deben fortalecerse unos a otros. Los que se ayudan mutuamente con amor, tienen razón para esperar que Dios les ayude a ambos en su gracia.
Adoni-bezec fue hecho prisionero. Este príncipe había sido un tirano severo. Los israelitas, evidentemente bajo la dirección divina, le hicieron sufrir lo que él había hechos a otras personas. Así, a veces, el justo Dios, en su providencia, hace que el castigo corresponda al pecado.</p>
<br/>
<p class="text-justify">Vv. 9-20.Los cananeos tenían carros de hierro, pero Israel tenía a Dios de su lado, cuyos carros son millares de ángeles, Salmo lxviii, 17. Pero aun ellos dejaron que sus temores prevalecieran sobre su fe. Leemos de Caleb en Josué xv, 16-19. Los ceneos se habían establecido en la tierra. Israel dejó que se establecieran donde gustaran, siendo un pueblo tranquilo y no ambicioso. A los que no molestan a nadie, nadie los molesta. Bienaventurados los mansos porque ellos heredarán la Tierra.</p>
<br/>
<p class="text-justify">Vv. 21-36. El pueblo de Israel fue muy negligente con su deber y con sus beneficios. Si no fuera por la pereza y la cobardía, no habrían tenido dificultades para completar sus conquistas. También se debía a su codicia: estaban dispuestos a dejar que los cananeos vivieran entre ellos para aprovecharse de ellos. No tenían el terror ni el odio por la idolatría que deberían tener. La misma incredulidad que mantuvo a sus antepasados por cuarenta años fuera de Canaán, les impedía ahora tomar completa posesión de la tierra. La desconfianza en el poder y la promesa de Dios les privaba de los beneficios y los metía en problemas. De esa manera, muchos creyentes que empiezan bien, se ven retardados. Sus gracias languidecen, sus concupiscencias reviven, Satanás los acosa con tentaciones adecuadas, el mundo recupera su dominio; tienen sentimiento de culpa, llenan de angustia su corazón, desacreditan su carácter y hacen caer reproche sobre el evangelio. Aunque se le reprenda imperiosamente, y ser recuperado para que no perezca, tendrá, sin embargo, que lamentar profundamente su necedad por el resto de sus días; en su lecho de muerte tendrá que lamentar las oportunidades que perdió de glorificar a Dios y servir a la iglesia. No podemos tener comunión con los enemigos de Dios en nosotros o fuera de nosotros sino para propio daño; en consecuencia, nuestra única sabiduría es librar una guerra incesante contra ellos.</p>
<br/>




</div>
