<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jueces 5</h2>
<p class="text-justify">Vv. 1-5.No debe haber pérdida de tiempo para agradecer al Señor sus misericordias; porque nuestras alabanzas son más aceptables, agradables y provechosas cuando fluyen de un corazón satisfecho. Por esto, se debe estimularse más el amor y el agradecimiento, y fijarse más profundamente, en el corazón del creyente; los acontecimientos serán más conocidos y recordados por más tiempo. El Señor es quien debe tener toda la alabanza, no importa cuánto hayan hecho Débora, Barac o el ejército. La voluntad, el poder y el éxito fueron todos de Dios.</p>
<br/>
<p class="text-justify">Vv. 6-11.Débora describe el estado afligido de Israel bajo la tiranía de Jabín, para destacar que su salvación era pura gracia. Muestra la causa de su miseria. Fue su idolatría. Escogieron nuevos dioses con nombres nuevos. Pero tras todas esas imágenes era Satanás a quien adoraban. Débora fue una madre para Israel al fomentar diligentemente la salvación de sus almas. Llama a los que compartieron las ventajas de esta gran salvación para que ofrezcan su gratitud a Dios. A los que se les ha restaurado, no sólo su libertad como a los demás israelitas, sino a su dignidad, que alaben a Dios.
Esta es obra del Señor. En los actos suyos hizo justicia sobre sus enemigos. En épocas de persecución se recurre a las ordenanzas de Dios, las fuentes de salvación, de donde se extrae el agua de vida, con peligro para la vida de quienes los que le prestan atención. En todo momento Satanás tratará de impedir que el creyente se acerque al trono de la gracia. Fijaos en la bondad de Dios hacia su pueblo tembloroso. La gloria de Dios es proteger a quienes están más expuestos y ayudar al más débil. Notemos el beneficio que tenemos por la paz pública, especialmente los habitantes de las aldeas, y demos la alabanza a Dios.</p>
<br/>
<p class="text-justify">Vv. 12-23.Débora invoca a su propia alma para que sea la más ferviente. El que enciende el fuego en los corazones de otros hombres con el amor de Cristo, debe arder primero con el mismo amor. Alabar a Dios es una tarea a la cual debemos despertar, y despertarnos para ella. Se da cuenta quiénes pelearon contra Israel, quiénes pelearon por ellos y quiénes se mantuvieron lejos. Quienes pelearon contra ellos. Eran enemigos obstinados del pueblo de Dios, por tanto, los más peligrosos.
Quiénes pelearon por ellos. Las diversas tribus que los ayudaron se mencionan aquí con honor; porque aunque Dios debe ser glorificado por sobre todo, los que son utilizados deben recibir su debido elogio para estímulo de los demás. Pero toda la creación está en guerra contra los que tienen a Dios por enemigo.
El río Cisón peleó contra sus enemigos. La mayor parte de las veces era poco profundo pero ahora, probablemente por la gran lluvia que cayó, estaba tan crecido y la corriente era tan profunda y fuerte, que quienes trataron de cruzarlo se ahogaron.
El alma de la misma Débora peleó contra ellos. Cuando se emplea el alma en piadosos ejercicios y se hace obra de corazón, por la gracia de Dios, la fuerza de nuestros enemigos espirituales será pisoteada y caerán ante nosotros.
Observe quiénes se mantuvieron a la distancia y no se pusieron del lado de Israel, como pudiera haberse esperado. Así, muchos no cumplen su deber por miedo a los problemas, el amor a la comodidad y el indebido afecto por sus negocios y ventajas mundanales. Los espíritus estrechos y egoístas no se cuidan por lo que le suceda a la iglesia de Dios con tal de conseguir, guardar y ahorrar dinero. Todos buscan lo suyo propio, Filipenses ii, 21. Algo pequeño les servirá de pretexto para quedarse en casa, a quienes no tienen la intención de comprometerse en servicios necesarios, porque presentan dificultades y peligros. Pues no podemos mantenernos fuera de la lucha entre el Señor y sus enemigos; y si no nos metemos activamente a fomentar su causa en este mundo malo, caeremos bajo la maldición contra los obreros de maldad. Aunque no necesita ayuda humana, sin embargo, Dios se agrada en aceptar los servicios de quienes mejoran sus talentos para el progreso de su causa. Él requiere que cada hombre haga esto.</p>
<br/>
<p class="text-justify">Vv. 24-31.Jael tuvo una bendición especial. Los que echan su suerte en la tienda, en una esfera baja y estrecha, si sirven a Dios según los poderes que les ha dado, no perderán su recompensa.
La madre de Sísara esperaba su regreso, no temiendo en lo más mínimo por su éxito. Cuidémonos de abrigar deseos ardientes por algún bien temporal, particularmente en cuanto a acariciar la vanagloria, pues eso era lo que aquí ella deseaba. -¡Qué cuadro presenta ella de un corazón impío y sensual! ¡Cuán vergonzosos e infantiles son los deseos de una madre anciana y de sus asistentes para su hijo! De esta manera, Dios a menudo arruina a sus enemigos cuando están más hinchados de orgullo.
Débora concluye con una oración a Dios por la destrucción de todos sus enemigos y por el consuelo de todos sus amigos. Tal será la honra, y el gozo de todos los que aman a Dios con sinceridad; por siempre brillarán como el sol en el firmamento.</p>
<br/>




</div>
