<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Jueces 2</h2>
<p class="text-justify">Vv. 1-5.Era el gran Ángel del pacto, el Verbo, el Hijo de Dios, quien habló con autoridad divina como Jehová y que ahora los llama a rendir cuentas de su desobediencia. Dios expone lo que ha hecho por Israel y lo que había prometido. Quienes desechan la comunión con Dios y tienen comunión con las obras infructuosas de las tinieblas no saben lo que hacen, y nada tendrán que decir a su favor en el día cercano de la rendición de cuentas. Tienen que esperar sufrimientos a cambio de su necedad. Se engañan a sí mismos quienes esperan sacar ventaja de su amistad con los enemigos de Dios. A menudo Dios hace que el pecado de los hombres sea su castigo; hay espinas y trampas en el camino del obstinado que anda en contra de Dios.
El pueblo lloró, quejándose de su propia insensatez e ingratitud. Temblaron ante la palabra y no sin causa. Es un prodigio que los pecadores puedan hasta leer la Biblia con los ojos secos. Si se hubieran mantenido cerca de Dios y de su deber, ninguna voz sino la de los cánticos se hubiera oído pero, por su pecado y necedad, hicieron otra obra para sí mismos y nada se oirá sino la voz del lloro. La adoración de Dios, en su propia naturaleza, es gozo, alabanza y acción de gracias; nuestros pecados solo hacen necesario el llanto. Agrada ver que los hombres lloren por sus pecados, pero nuestras lágrimas, oraciones y ni aun las enmiendas pueden expiar el pecado.</p>
<br/>
<p class="text-justify">Vv. 6-23.Tenemos una idea general del curso de las cosas en Israel durante la época de los Jueces. La nación se volvió tan miserable y desgraciada por abandonar a Dios, como hubieran sido grandes y felices si hubieran continuado siendo fieles a Él. El castigo correspondió al mal que habían hecho. Sirvieron a los dioses de las naciones que los rodeaban aun al menor, y Dios hizo que sirvieran a los príncipes de las naciones de sus contornos, aun al menor. Quienen han hallado que Dios es fiel a sus promesas, pueden estar seguros que será igualmente fiel con sus amenazas.
Con justicia, podría haberlos abandonado, pero por compasión no lo hizo. El Señor estaba con los jueces que levantaba, y de esa manera llegaron a ser salvadores. En los días de las mayores tribulaciones de la iglesia, habrá algunos a quienes Dios halle o haga aptos para ayudarla.
Los israelitas no fueron cabalmente reformados; porque estaban tan enloquecidos por sus ídolos y tan obstinadamente inclinados a descarriarse. De esta manera, los que han abandonado los buenos caminos de Dios, que una vez conocieron y profesaron, generalmente se ponen más atrevidos y desesperados en el pecado y sus corazones se endurecen.
Su castigo fue que los cananeos fueron perdonados, y de esa manera, ellos fueron golpeados con su propia vara. Los hombres abrigan y toleran sus corruptos apetitos y pasiones; en consecuencia, Dios los deja justamente librados a su suerte, bajo el poder de sus pecados, lo que será su ruina. Dios nos ha dicho cuán engañoso y desesperadamente perverso es nuestro corazón, pero no estamos dispuestos a creerlo hasta que, haciéndonos osados por la tentación, descubrimos por triste experiencia, que es verdad. Tenemos que examinarnos a nosotros mismos y orar sin cesar para que habite Cristo por la fe en nuestros corazones, arraigados y cimentados en amor. Declaremos la guerra a todo pecado y sigamos la santidad todos nuestros días.</p>
<br/>




</div>
