<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Levítico 1</h2>
<p class="text-justify">Vv. 1, 2.La ofrenda de sacrificios era una ordenanza para la religión verdadera, desde la caída del hombre hasta la venida de Cristo. Pero parece que no hubo reglamentos muy detallados hasta que los israelitas estuvieron en el desierto. El designio general de estas leyes es claro. Los sacrificios tipificaban a Cristo; además eran sombras del deber, carácter, privilegio y comunión del creyente con Dios. Casi no hay algo que la Escritura diga del Señor Jesús que, además, no tenga referencia a su pueblo. Este libro empieza con las leyes de los sacrificios; los más antiguos eran los holocaustos, sobre los cuales Dios da órdenes a Moisés en este pasaje. Se da por sentado que el pueblo estaba dispuesto a traer ofrendas al Señor. La luz misma de la naturaleza dirige al hombre de una u otra manera para honrar a su Hacedor como su Señor. Los sacrificios fueron ordenados inmediatamente después de la caída.</p>
<br/>
<p class="text-justify">Vv. 3-9.En la correcta ejecución de las ordenanzas levíticas, los misterios del mundo espiritual son representados por los objetos naturales correspondientes. En sus ritos se exhiben sucesos futuros. Sin esto, todo el conjunto parecerá un ceremonial sin sentido. -¿Hay en estas cosas un tipo de los sufrimientos del Hijo de Dios, que iba a ser un sacrificio por los pecados de todo el mundo? Quemar el cuerpo de un animal solo era una débil representación de la miseria eterna, que todos merecemos, y que nuestro bendito Señor llevó en su cuerpo y en su alma, cuando murió bajo la carga de nuestras iniquidades.
Obsérvese: -1. La bestia que se ofrendaba debía ser sin defecto . Esto significaba la fuerza y pureza que había en Cristo y la vida santa que debe haber en su pueblo.
2. El propietario debía ofrecerlo por propia y libre voluntad . Lo que se hace en la religión para agradar a Dios debe hacerse por amor. Cristo se ofrendó voluntariamente por nosotros.
3. Debía ofrecerse en la puerta del tabernáculo donde estaba el altar de bronce del holocausto, que santificaba la dádiva: debía ofrecerlo en la puerta como quien es indigno de entrar y reconociendo que un pecador no puede tener comunión con Dios, sino por el sacrificio.
4. El ofrendante debía poner su mano sobre la cabeza de la ofrenda significando con ello su deseo y esperanza de ser aceptado, de su parte, como expiación por él.
5. El sacrificio tenía que ser muerto delante el Señor , en forma ordenada y para honrar a Dios. Significaba también que en el cristiano debe ser crucificada la carne con sus afectos corruptos y sus concupiscencias.
6. Los sacerdotes tenían que rociar la sangre sobre el altar ; puesto que la sangre es la vida, es ella la que hace expiación. Esto representa la pacificación y purificación de nuestra conciencia, por medio del rociamiento de la sangre de Jesucristo sobre ella, por fe.
7. El animal tenía que ser partido en varios pedazos y, luego, ser quemado sobre el altar. La quema del sacrificio representa los agudos sufrimientos de Cristo y el afecto devoto con que, como fuego santo, el cristiano debe ofrecerse completamente, espíritu, alma y cuerpo a Dios.
8. Se dice que esto era una ofrenda de olor grato . Como acto de obediencia a un mandato divino, y como tipo de Cristo, era agradable a Dios; los sacrificios espirituales de los creyentes son aceptables para Dios por medio de Cristo, 1 Pedro ii, 5.</p>
<br/>
<p class="text-justify">Vv. 10-17.Los que no podían ofrendar un vacuno tenían que traer una oveja o una cabra; los que no podían hacer eso eran aceptados por Dios si traían una tórtola o un palomino. Las criaturas escogidas para el sacrificio tenían que ser mansas, delicadas e inofensivas para mostrar la inocencia y mansedumbre que hubo en Cristo, y que debe haber en los cristianos. La ofrenda del pobre es tan tipo de la expiación de Cristo como los sacrificios más caros, y expresaba tan completamente como los otros el arrepentimiento, fe y devoción a Dios.
No tenemos excusa si rehusamos el culto a Dios agradable y racional ahora requerido.
Pero no podemos ofrecer el sacrificio de un corazón quebrantado, o de alabanza y acción de gracias, así como un israelita no podía ofrendar un vacuno o cabra, si Dios no se daba a sí mismo primero. Mientras más hagamos en el servicio del Señor, más obligados estamos con Él, por su voluntad, la capacitación y la oportunidad. En muchas cosas Dios deja que nosotros fijemos lo que deberá gastarse en su servicio, sea de nuestro tiempo o de nuestra sustancia; sin embargo, cuando la providencia de Dios haya dado mucho a un hombre, no se aceptarán ofrendas magras, pues no son expresiones correctas de una mente bien dispuesta. Consagrémonos a su servicio en cuerpo y alma, sea lo que fuere que nos pida que demos, aventuremos, hagamos o suframos por amor a Él.</p>
<br/>




</div>
