<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Lucas 22</h2>
<p class="text-justify">Vv. 1-6.Cristo conocía a todos los hombres y tuvo fines sabios y santos al aceptar que Judas fuera un discípulo. Aquí se nos dice cómo aquel que conocía tan bien a Cristo, llegó a traicionarlo: Satanás entró en Judas. Cuesta mucho decir si hacen más daño al reino de Cristo el poder de sus enemigos declarados o la traición de falsos amigos, pero sin éstos, los enemigos no podrían hacer tanto mal como el que hacen.</p>
<br/>
<p class="text-justify">Vv. 7-18.Cristo guardó las ordenanzas de la ley, particularmente la de la pascua para enseñarnos a observar las instituciones del evangelio y, más que nada, la de la cena del Señor. Los que andan por la palabra de Cristo no tienen que temer desilusiones. Según las instrucciones que les dio, todos los discípulos se prepararon para la pascua.
Jesús expresa su alegría por celebrar esta pascua. La deseaba, aunque sabía que luego vendrían sus sufrimientos, porque tenía como objetivo la gloria de su Padre y la redención del hombre. Se despide de todas las pascuas significando que terminan las ordenanzas de la ley ceremonial, de la cual la pascua era una de las primeras y la principal. El tipo fue dejado de lado, porque ahora en el reino de Dios había llegado la sustancia.</p>
<br/>
<p class="text-justify">Vv. 19, 20.La cena del Señor es una señal o conmemoración de Cristo que ya vino, que nos liberó muriendo por nosotros; su muerte se pone ante nosotros de manera especial en esta ordenanza, por la que la recordamos. Aquí el partimiento del pan nos recuerda el quebranto del cuerpo de Cristo en sacrificio por nosotros. Nada puede ser mejor alimento y más satisfactorio para el alma que la doctrina de la expiación del pecado hecha por Cristo y la seguridad de tener parte en esa expiración. Por tanto, hacemos esto en memoria de lo que Él hizo por nosotros cuando murió por nosotros; y como recordatorio de lo que hacemos, al unirnos a Él en el pacto eterno. El derramamiento de la sangre de Cristo, por lo cual se hace la expiación, se representa por el vino en la copa.</p>
<br/>
<p class="text-justify">Vv. 21-38.¡Qué inconveniente para el carácter del seguidor de Jesús es la ambición mundana de ser el más grande, sabiendo que Cristo asumió la forma de siervo y se humilló hasta la muerte de cruz! En el camino a la dicha eterna tenemos que esperar ser atacados y zarandeados por Satanás. Si no puede destruirnos, tratará de hacernos desdichados o de angustiarnos. Nada precede con mayor certeza a la caída de un seguidor confeso de Cristo, que la confianza en sí mismo, con desconsideración por las advertencias y desprecio del peligro. A menos que velemos y oremos siempre podemos ser arrastrados en el curso del día a aquellos pecados contra los cuales estábamos más decididos en la mañana. Si los creyentes fueran dejados a sí mismos, caerían, pero son mantenidos por el poder de Dios, y la oración de Cristo.
Nuestro Señor les anuncia la aproximación de un cambio muy grande de circunstancias. Los discípulos no deben esperar que sus amigos sean amables con ellos como antes. Por tanto, el que tenga dinero, que lo lleve consigo porque puede necesitarlo. Ahora deben esperar que sus enemigos sean más feroces que antes y necesitarán armas. En esa época los apóstoles entendieron que Cristo quería decir armas reales, pero Él sólo hablaba de las armas de la guerra espiritual. La espada del Espíritu es la espada con que deben armarse los discípulos de Cristo.</p>
<br/>
<p class="text-justify">Vv. 39-46.Cada descripción que dan los evangelistas de la disposición mental con que nuestro Señor enfrenta este conflicto, prueba la terrible naturaleza del ataque, y el perfecto conocimiento anticipado de sus terrores que poseía el manso y humilde Jesús. Aquí hay tres cosas que no están en los otros evangelistas: -1. Cuando Cristo agoniza se presenta un ángel del cielo que le fortalece. Parte de su humillación fue tener que ser fortalecido por un espíritu ministrador.
2. Estando en agonía oró más fervorosamente. La oración, aunque nunca es inoportuna, es especialmente oportuna cuando agonizamos.
3. En esta agonía su sudor fue como grandes gotas de sangre que caían. Esto muestra el sufrimiento de su alma. Debemos orar también para ser capacitados para resistir hasta derramar nuestra sangre en la lucha contra el pecado, si alguna vez se nos llama a eso. -¡La próxima vez que en tu imaginación te detengas a deleitarte en algún pecado favorito, piensa en sus efectos como los que ves aquí! Mira sus terribles efectos en el huerto de Getsemaní y desea profundamente odiar y abandonar a ese enemigo, con la ayuda de Dios, y rescatar pecadores por los cuales el Redentor oró, agonizó y sangró.</p>
<br/>
<p class="text-justify">Vv. 47-53.Nada puede ser mayor afrenta o dolor para el Señor Jesús que ser traicionado por los que profesan ser sus seguidores, y dicen que le aman. Muchos ejemplos hay de Cristo traicionado por quienes, bajo la apariencia de piedad, luchan contra su poder. Aquí Jesús dio un ejemplo ilustre de su regla de hacer el bien a los que nos odian, como después lo dio sobre orar por quienes nos tratan desdeñosamente. La naturaleza corrompida envuelve nuestra conducta hasta el extremo; debemos buscar la dirección del Señor antes de actuar en circunstancias difíciles. Cristo estuvo dispuesto a esperar sus triunfos hasta que su guerra estuviera consumada, y así debemos hacer nosotros también. La hora y el poder de las tinieblas fueron cortos, y siempre será así con los triunfos de los impíos.</p>
<br/>
<p class="text-justify">Vv. 54-62.La caída de Pedro fue negar que conocía a Cristo y que era su discípulo; lo negó debido a la angustia y el peligro. El que una vez dice una mentira es tentado fuertemente a persistir: el comienzo de ese pecado, como en las luchas, es como dejar correr el agua. El Señor se vuelve y mira a Pedro: -1. Fue una mirada acusadora . Jesús se volvió y lo miró como diciendo, Pedro, ¿no me conoces? -2. Fue una mirada de reproche . Pensemos con que aspecto de reprensión nos mira Cristo, con justicia, cuando pecamos.
3. Fue una mirada de amonestación. ¡Tú que eras el más dispuesto a confesarme como Hijo de Dios, y prometiste solemnemente no negarme jamás! -4. Fue una mirada compasiva . Pedro, ¡cuán caído y deshecho estás si no te ayudo! -5. Fue una mirada de mando&lt;D, vé y reflexiona.
6. Fue una mirada significante . Significaba la transmisión de gracia al corazón de Pedro para capacitarlo, para que se arrepintiera. La gracia de Dios obra en la palabra de Dios y por ella, la trae a la mente y la hace llegar a la conciencia, y así da al alma el feliz regreso. Cristo miró a los principales sacerdotes, pero no los impresionó como a Pedro. No fue la sola mirada de Cristo lo que restauró a Pedro, sino su gracia divina en ella.</p>
<br/>
<p class="text-justify">Vv. 63-71.Los que condenaron a Jesús por blasfemo eran los más viles blasfemos. Los refirió a su segunda venida como prueba completa de que era el Cristo, para confusión de ellos, puesto que no reconocerían la prueba que los dejaría convictos. Se reconoce Hijo de Dios aunque sabe que debía sufrir por ello. Ellos basaron en esto su condena. Cegados sus ojos, se precipitaron. Meditemos en esta asombrosa transacción y consideremos a Aquel que soportó tal contradicción de los pecadores contra sí mismo.</p>
<br/>




</div>
