<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Lucas 7</h2>
<p class="text-justify">Vv. 1-10.Los siervos deben pensar en encariñarse con sus amos. Los amos deben cuidar particularmente a sus siervos cuando se enferman. Aún podemos, por la oración fiel y ferviente, recurrir a Cristo, y debemos hacerlo así cuando hay enfermedad en nuestra familia. Edificar lugares para la adoración religiosa es buena obra, y un ejemplo de amor a Dios y su pueblo. Nuestro Señor Jesús se agradó con la fe del centurión; nunca deja de responder las expectativas de la fe que honra su poder y amor. La cura fue prontamente obrada y perfecta.</p>
<br/>
<p class="text-justify">Vv. 11-18.Cuando el Señor vio a la viuda pobre siguiendo a su hijo a la tumba, tuvo compasión de ella. Véase aquí el poder de Cristo sobre la muerte misma. El evangelio llama a toda la gente, en particular a los jóvenes: Levántate de entre los muertos, y te alumbrará Cristo. Cuando Cristo le dio vida, se vio porque el joven se sentó. ¿Tenemos la gracia de Cristo? Mostrémosla.
Empezó a hablar: cada vez que Cristo da vida espiritual, abre los labios en oración y alabanza. Cuando las almas muertas son levantadas a la vida espiritual por el poder divino del evangelio, debemos glorificar a Dios, y considerarlo como una visita de gracia a su pueblo. Procuremos tener un interés tal en nuestro Salvador compasivo, que podamos esperar con gozo la época en que la voz del Redentor llamará a todos los que están en los sepulcros. Que seamos llamados a la resurrección de vida, no a la de condenación.</p>
<br/>
<p class="text-justify">Vv. 19-35.A sus milagros en el reino de la naturaleza, Cristo agrega este en el reino de la gracia. Se predica el evangelio a los pobres. Señala claramente la naturaleza espiritual del reino de Cristo, como el heraldo que envió a preparar su camino lo hiciera al predicar el arrepentimiento y el cambio de corazón y de vida.
Aquí se recalca con justicia la responsabilidad de quienes no fueron atraídos por el ministerio de Juan el Bautista o del mismo Jesucristo. Se burlaron de los métodos que Dios adoptó para hacerles el bien. Esta es la ruina de multitudes: no son serios en los intereses de sus almas. Pensemos en el modo de mostrarnos como hijos de la sabiduría atendiendo a las instrucciones de la Palabra de Dios y venerando los misterios y la buena nueva que los infieles y los fariseos ridiculizan y blasfeman.</p>
<br/>
<p class="text-justify">Vv. 36-50.Nadie puede percibir verdaderamente cuán precioso es Cristo, y la gloria del evangelio, salvo el quebrantado de corazón. Aunque lo sientan, éstos no pueden expresar suficiente aborrecimiento de sí por el pecado, ni admiración por Su misericordia, pero el autosuficiente se disgustará porque el evangelio anima a los pecadores arrepentidos. El fariseo limita sus pensamientos al mal carácter anterior de la mujer, en vez de regocijarse por las señales de su arrepentimiento. Sin perdón gratuito ninguno de nosotros puede escapar de la ira venidera; nuestro bondadoso Salvador lo compró con su sangre para darlo gratuitamente a todo aquel que cree en Él.
Cristo, por una parábola, obligó a Simón a reconocer que la gran pecadora que fue esta mujer, debía demostrar amor más grande por Él cuando le fueron perdonados sus pecados. Aprended aquí que el pecado es una deuda y que todos sois pecadores y deudores del Dios Todopoderoso. Algunos pecadores son deudores mayores, pero sea nuestra deuda más o menos grande, es más de lo que somos capaces de pagar. Dios está presto a perdonar, y habiendo adquirido su Hijo el perdón para los que creen en su evangelio lo promete, y su Espíritu sella a los pecadores arrepentidos, y les da consuelo. Mantengámonos lejos del espíritu orgulloso del fariseo y dependamos sencillamente solo de Cristo y regocijémonos en Él, y así, estemos preparados para obedecerle con más celo y recomendarlo con más fuerza a nuestro alrededor. Mientras más expresemos nuestro dolor por el pecado y nuestro amor a Cristo, más clara será la prueba que tenemos del perdón de nuestros pecados. ¡Qué cambio maravilloso efectúa la gracia en el corazón y la vida de un pecador y en su estado ante Dios, por la completa remisión de todos sus pecados por la fe en el Señor Jesús!</p>
<br/>




</div>
