<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Lucas 1</h2>
<p class="text-justify">Vv. 1-4.Lucas no escribe sobre cosas acerca de las cuales pueden diferir entre sí los cristianos, y tener vacilaciones, sino de las cosas que son y deben ser creídas con toda seguridad. La doctrina de Cristo es en lo que los más sabios y mejores hombres han aventurado sus almas con confianza y satisfacción. Los grandes sucesos de los que dependen nuestras esperanzas, fueron narrados por escrito por los que, desde el comienzo, fueron testigos oculares y ministros de la palabra, y fueron perfeccionados en su entendimiento por medio de la inspiración divina.</p>
<br/>
<p class="text-justify">Vv. 5-25.El padre y la madre de Juan el Bautista eran pecadores como todos somos y fueron justificados y salvados en la misma forma que los demás, pero fueron eminentes por su piedad e integridad. No tenían hijos, y no podía esperarse que Elisabet los tuviera a su avanzada edad.
Mientras Zacarías quemaba el incienso en el templo, toda la multitud oraba afuera. Todas las oraciones que ofrecemos a Dios son aceptadas y exitosas sólo por la intercesión de Cristo en el templo de Dios en lo alto. No podemos tener la expectativa de poseer un interés allí si no oramos, si no oramos con nuestro espíritu, y si no oramos con fervor. Tampoco podemos esperar que lo mejor de nuestras oraciones sean aceptadas y traigan una respuesta de paz, si no es la mediación de Cristo, que siempre vive haciendo intercesión.
Las oraciones que Zacarías ofrecía frecuentemente recibieron una respuesta de paz. Las oraciones de fe son archivadas en el cielo y no se olvidan. Las oraciones hechas cuando éramos jóvenes y entrábamos al mundo, pueden ser contestadas cuando seamos viejos y estemos saliendo del mundo. Las misericordias son doblemente dulces cuando son dadas como respuestas a la oración.
Zacarías tendrá un hijo a edad avanzada, el cual será instrumento para la conversión de muchas almas a Dios, y para su preparación para recibir el evangelio de Cristo. Se presentará ante Él con coraje, celo, santidad y una mente muerta a los intereses y placeres mundanos. Los desobedientes y los rebeldes serían convertidos a la sabiduría de sus antepasados justos, o más bien, llevados a atender la sabiduría del Justo que iba a venir a ellos.
Zacarías oyó todo lo que dijo el ángel, pero habló su incredulidad. Dios lo trató justamente al dejarlo mudo, porque él había objetado la palabra de Dios. Podemos admirar la paciencia de Dios para con nosotros. Dios lo trató amablemente , porque así le impidió hablar más cosas apartadas de la fe y en incredulidad. Así, también, Dios confirmó su fe. Si por las reprensiones a que estamos sometidos por nuestro pecado, somos guiados a dar más crédito a la palabra de Dios, no tenemos razón para quejarnos. Aun los creyentes verdaderos son dados a deshonrar a Dios con incredulidad; y sus bocas son cerradas con silencio y confusión, cuando por el contrario, hubieran debido estar alabando a Dios con gozo y gratitud.
En los tratos de la gracia de Dios con nosotros tenemos que observar sus consideraciones bondadosas para con nosotros. Nos ha mirado con compasión y favor y, por tanto, así nos ha tratado.</p>
<br/>
<p class="text-justify">Vv. 26-38.Aquí tenemos un relato de la madre de nuestro Señor; aunque no debemos orar a ella, de todos modos debemos alabar a Dios por ella. Cristo debía nacer milagrosamente. El discurso del ángel sólo significa: “Salve, tú que eres la escogida y favorecida especial del Altísimo para tener el honor que las madres judías han deseado por tanto tiempo”.
Esta aparición y saludo prodigiosos turbaron a María. El ángel le aseguró entonces que ella había hallado favor con Dios y que sería la madre de un hijo cuyo nombre ella debía llamar Jesús, el Hijo del Altísimo, uno en naturaleza y perfección con el Señor Dios. ¡JESÚS! El nombre que refresca los espíritus desfallecientes de los pecadores humillados; dulce para pronunciar y dulce de oír, Jesús, el Salvador. No conocemos su riqueza y nuestra pobreza, por tanto, no corremos a Él; no nos damos cuenta que estamos perdidos y pereciendo, en consecuencia, Salvador es palabra de poco deleite. Si estuviéramos convencidos de la inmensa masa de culpa que hay en nosotros, y la ira que pende sobre nosotros, lista para caer sobre nosotros, sería nuestro pensamiento continuo: ¿Es mío el Salvador? Para que podamos hallarlo, debemos pisotear todo lo que estorba nuestro camino a Él. La respuesta de María al ángel fue el lenguaje de la fe y humilde admiración, y ella no pidió señal para confirmar su fe. Sin controversia, grande fue el misterio de la santidad, Dios manifestado en carne, 1 Timoteo iii, 16. La naturaleza humana de Cristo debía producirse de esa manera, para que fuera adecuada para Aquel que iba a ser unido con la naturaleza divina. Debemos, como María aquí, guiar nuestros deseos por la palabra de Dios. En todos los conflictos tenemos que recordar que nada es imposible para Dios; y al leer y oír sus promesas, convirtámoslas en oraciones: He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.</p>
<br/>
<p class="text-justify">Vv. 39-56.Muy bueno es que aquellos en cuyas almas ha comenzada la obra de la gracia se comuniquen entre sí. Elisabet estaba consciente, cuando llegó María, de que se acercaba la que iba a ser la madre del gran Redentor. Al mismo tiempo, fue llena del Espíritu Santo, y bajo su influencia declaró que María y ella esperaban hijos que serían altamente bendecidos y felices, y particularmente honrados y queridos para el Dios Altísimo.
María, animada por el discurso de Elisabet, y también bajo la influencia del Espíritu Santo, prorrumpió en gozo, admiración, y gratitud. Se sabía pecadora que necesitaba un Salvador, y que, de lo contrario, no podía regocijarse en Dios más que como interesada en su salvación por medio del Mesías prometido. Los que captan su necesidad de Cristo, y que están deseosos de tener justicia y vida en Él, a ésos llena con cosas buenas, con las cosas mejores; y son abundantemente satisfechos con las bendiciones que da. Él satisfará los deseos del pobre en espíritu que anhela bendiciones espirituales, mientras los autosuficientes serán enviados lejos.</p>
<br/>
<p class="text-justify">Vv. 57-66.En estos versículos tenemos un relato del nacimiento de Juan el Bautista, y del gran gozo de todos los familiares. Se llamaría Juan o “lleno de gracia”, porque introducirá el evangelio de Cristo, en el cual brilla más la gracia de Dios.
Zacarías recuperó el habla. La incredulidad cerró su boca y al creer se la volvió a abrir: cree, por tanto, habla. Cuando Dios abre nuestros labios, las bocas deben mostrar su alabanza; y mejor estar mudo que no usar el habla para alabar a Dios. Se dice que la mano del Señor estaba obrando en Juan. Dios tiene maneras de obrar en los niños, en su infancia, que nosotros no podemos entender. Debemos observar los tratos de Dios y esperar el acontecimiento.</p>
<br/>
<p class="text-justify">Vv. 67-80.Zacarías pronuncia una profecía acerca del reino y la salvación del Mesías. El evangelio trae luz consigo: en él alborea el día. En Juan el Bautista empezó a alborear y su luz fue en aumento hasta que el día fue perfecto. El evangelio es conocimiento ; muestra aquello en lo cual estábamos completamente en tinieblas; es para dar luz a los que se sienten a oscuras, la luz del conocimiento de la gloria de Dios en la faz de Jesucristo. Revive ; trae luz a los que se sientan en sombra de muerte, como prisioneros condenados en la mazmorra. Guía , encamina nuestros pasos por el camino de paz, a ese camino que nos traerá la paz al fin, Romanos iii, 17. Juan dio pruebas de fe firme, afectos fuertes y piadosos y de estar por encima del miedo y del amor al mundo. Así, él maduró para el servicio, pero llevó una vida retirada, hasta que salió a escena, abiertamente, como el precursor del Mesías. Sigamos la paz con todos los hombres, y procuremos la paz con Dios y con nuestras propias conciencias. Si es la voluntad de Dios y vivamos desconocidos para el mundo, aún así busquemos diligentemente crecer firmes en la gracia de Jesucristo.</p>
<br/>




</div>
