<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Lucas 2</h2>
<p class="text-justify">Vv. 1-7.La plenitud del tiempo estaba ahora por llegar, cuando Dios enviaría a su Hijo, hecho de mujer, y sometido a la ley. Las circunstancias de su nacimiento fueron muy viles. Cristo nació en una posada; vino al mundo a estar aquí por un tiempo, como en una posada, y a enseñarnos a hacer lo mismo. El pecado nos hace como un infante abandonado, indefenso y solitario; y así fue Cristo. Él supo bien cuán poca voluntad hay para que nos alojen, nos vistan, nos alimenten pobremente; cuánto deseamos tener a nuestros hijos ataviados y consentidos; cuán dados son los pobres a envidiar al rico, y cuánto tienden los ricos a desdeñar a los pobres. Pero cuando por fe vemos al Hijo de Dios que es hecho hombre y yace en un pesebre, nuestra vanidad, ambición y envidia son frenadas. No podemos buscar grandes cosas para nosotros mismos o para nuestros hijos teniendo este objeto justo ante de nosotros.</p>
<br/>
<p class="text-justify">Vv. 8-20.Los ángeles fueron heraldos del recién nacido Salvador, pero fueron enviados solo a unos pastores pobres, humildes, piadosos, trabajadores, que estaban ocupados en su vocación, vigilando sus rebaños. No estamos fuera del camino de las visitas divinas cuando estamos empleados en una vocación honesta y permanecemos con Dios en ello. Que Dios tenga el honor de esta obra; Gloria a Dios en lo alto. La buena voluntad de Dios para con los hombres, manifestada en el envío del Mesías, redunda para su gloria. Otras obras de Dios son para su gloria, pero la redención del mundo es para su gloria en lo alto. La buena voluntad de Dios al enviar al Mesías, trajo paz a este mundo inferior. La paz es puesta aquí para todo lo bueno que fluye a nosotros desde que Cristo asumió nuestra naturaleza. Dicho fiel es éste, avalado por una compañía incontable de ángeles, y bien digno de toda aceptación: Que la buena voluntad de Dios para con los hombres es gloria a Dios en lo alto, y paz en la tierra.
Los pastores no perdieron tiempo; se fueron presurosos al lugar. Se satisficieron y dieron a conocer por todas partes acerca de este niño, que Él era el Salvador, Cristo el Señor.
María observa cuidadosamente y piensa en todas estas cosas, que eran tan buenas para vivificar sus piadosos afectos. Debemos ser librados más de los errores de juicio y práctica si sopesáramos más plenamente estas cosas en nuestros corazones. Aun se proclama en nuestros oídos que nos es nacido un Salvador, Cristo el Señor. Esta debe ser buena nueva para todos.</p>
<br/>
<p class="text-justify">Vv. 21-24.Nuestro Señor Jesús no nació en pecado y no necesitó la mortificación de una naturaleza corrupta o la renovación para santidad, que significaba la circuncisión. Esta ordenanza fue, en su caso, una prenda de su futura obediencia perfecta de toda la ley, en medio de sufrimientos y tentaciones, aun hasta la muerte por nosotros.
Al final de los cuarenta días, María fue al templo a ofrecer los sacrificios establecidos para su purificación. José presenta también al santo niño Jesús, porque como primogénito, tenía que ser presentado al Señor, y ser redimido conforme a la ley. Presentemos nuestros hijos al Señor que nos los dio, rogándole que los rescate del pecado y la muerte, y los haga santos para Él.</p>
<br/>
<p class="text-justify">Vv. 25-35.El mismo Espíritu que proveyó para sostener la esperanza de Simeón, proveyó para su gozo. Los que desean ver a Cristo deben ir a su templo. He aquí una confesión de su fe, que el Niño que tiene en sus brazos era el Salvador, la salvación misma, la salvación planificada por Dios. Se despide de este mundo. ¡Cuán pobre le parece este mundo al que tiene a Cristo en sus brazos, y la salvación a la vista! Véase aquí, cuán consoladora es la muerte de un hombre bueno; se va en paz con Dios, en paz con su conciencia, en paz con la muerte. Los que dieron la bienvenida a Cristo, pueden dar la bienvenida a la muerte.
José y María se maravillaban antes las cosas que se decían del Niño. Simeón les muestra igualmente cuánta razón tenían para regocijarse con temblor. Aún se habla contra Jesús, su doctrina y su pueblo; aún se niega y blasfema su verdad y su santidad; su palabra predicada sigue siendo la piedra de toque del carácter de los hombres. Los buenos afectos secretos de las mentes de algunos, serán revelados al abrazar a Cristo; las corrupciones secretas de los demás serán reveladas por su enemistad con Cristo. Los hombres serán juzgados por los pensamientos de sus corazones en relación a Cristo. Él será un Jesús sufriente; su madre sufrirá con Él debido a la cercanía de la relación y el afecto de ella.</p>
<br/>
<p class="text-justify">Vv. 36-40.Entonces había mucho mal en la Iglesia, sin embargo, Dios no se quedó sin testigo. Ana siempre estaba ahí o, al menos iba al templo. Estaba si siempre en espíritu de oración; se entregaba a la oración y en todas las cosas servía a Dios. Aquellos a quienes Cristo se da a conocer, tienen muchos motivos para dar gracias al Señor. Ella enseñaba a los demás acerca de Él. Que el ejemplo de los venerables santos, Simeón y Ana, den valor a aquellos cuyas cabezas canas, como las de ellos, son corona de gloria, si se encuentran en el camino de la justicia. Los labios que pronto se silenciarán en la tumba, deben dar alabanzas al Redentor.
En todas las cosas convino a Cristo ser hecho semejante a sus hermanos, por tanto, pasó la infancia y la niñez como los otros niños, pero sin pecado y con pruebas evidentes de la naturaleza divina en Él. Por el Espíritu de Dios todas sus facultades desempeñaron los oficios de una manera no vista en nadie más. Otros niños tienen abundante necedad en sus corazones, lo que se advierte en lo que dicen o hacen, pero Él estaba lleno de sabiduría por el poder del Espíritu Santo; todo lo que dijo e hizo fue dicho y hecho sabiamente, por sobre su edad. Otros niños muestran la corrupción de su naturaleza; nada sino la gracia de Dios estaba sobre Él.</p>
<br/>
<p class="text-justify">Vv. 41-52.Por el honor de Cristo es que los niños deben asistir al servicio público de adoración. Sus padres no regresaron hasta que se quedaron los siete días de la fiesta. Bueno es quedarse hasta el final de una ordenanza como corresponde a quienes dicen: Bueno es estar aquí. Los que perdieron sus consolaciones en Cristo, y las pruebas de que tenían parte en Él, deben reflexionar dónde, y cuándo y cómo los perdieron y deben regresar. Los que recuperen su perdida familiaridad con Cristo, deben ir al lugar en que Él ha puesto su nombre; allí pueden esperar encontrarlo.
Ellos lo hallaron en alguna parte del templo, donde los doctores de la ley tenían sus escuelas; estaba sentado allí, oyendo su instrucción, planteando preguntas y respondiendo interrogantes, con tal sabiduría, que quienes lo oían se deleitaban con Él. Las personas jóvenes deben procurar el conocimiento de la verdad divina, asistir al ministerio del evangelio, y hacer tales preguntas a sus ancianos y maestros que tiendan a incrementar su conocimiento.
Los que buscan a Cristo con lloro, lo hallarán con el gozo más grande. ¿No sabíais que en los negocios de mi Padre debo estar? Debo estar en la casa de mi Padre; en la obra de mi Padre; debo ocuparme en el negocio de mi Padre. He aquí un ejemplo, porque conviene a los hijos de Dios, en conformidad con Cristo, asistir al negocio de su Padre celestial y hacer que todos los demás intereses le cedan el lugar. Aunque era el Hijo de Dios, no obstante, estuvo sometido a sus padres terrenales; entonces, ¿cómo responderán los hijos de los hombres, débiles y necios, que desobedecen a sus padres? -Como sea que rechacemos los dichos de los hombres, porque son oscuros, no debemos pensar así de los dichos de Dios. Lo que al principio es oscuro puede, después, volverse claro y fácil. Los más grandes y más sabios, los más eminentes, pueden aprender de este admirable Niño Divino, que conocer nuestro lugar y oficio es la grandeza más verdadera del alma; para negarnos las diversiones y placeres que no condicen con nuestro estado y vocación.</p>
<br/>




</div>
