<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Lucas 24</h2>
<p class="text-justify">Vv. 1-12.Véase el afecto y el respeto que las mujeres demostraron hacia Cristo, después que murió y fue sepultado. Obsérvese la sorpresa cuando hallaron removida la piedra y vacía la tumba. Los cristianos suelen quedar confundidos con lo que debiera consolarlos y animarlos. Esperaban hallar a su Maestro en su sudario, en vez de ángeles en ropajes refulgentes. Los ángeles les aseguraron que había resucitado de entre los muertos; ha resucitado por su poder. Estos ángeles del cielo no traen un evangelio nuevo, pero recuerdan a las mujeres las palabras de Cristo, y les enseñan a aplicarlas.
Podemos maravillarnos de estos discípulos, que creían que Jesús es el Hijo de Dios y el Mesías verdadero, a los que tan a menudo les había dicho que debía morir y resucitar, y luego entrar en su gloria, y que en más de una ocasión le habían visto resucitar muertos, pudieran tardar tanto en creer en su resurrección por su poder. Todos nuestros errores en la religión surgen de ignorar u olvidar las palabras que Cristo ha dicho.
Ahora Pedro corre al sepulcro, él que tan recientemente había huido de su Maestro. Estaba asombrado. Hay muchas cosas que nos causan estupefacción y confusión, y que serían claras y provechosas si entendiésemos correctamente las palabras de Cristo.</p>
<br/>
<p class="text-justify">Vv. 13-27.Esta aparición de Jesús a los dos discípulos que iban a Emaús, sucedió el mismo día en que resucitó de entre los muertos. Muy bien corresponde a los discípulos de Cristo hablar de su muerte y resurrección, cuando están juntos; de este modo pueden beneficiarse del conocimiento mutuo, refrescarse mutuamente la memoria y estimularse unos a otros sus afectos devotos. Dónde haya sólo dos que estén ocupados en este tipo de obra, Él vendrá a ellos y será el tercero. Los que buscan a Cristo lo hallarán: Él se manifestará a los que preguntan por Él; y dará conocimiento a los que usan las ayudas que tienen para el conocimiento.
No importa cómo fue, pero ocurre que ellos no lo conocieron; Él lo ordenó así para que ellos pudieran conversar más libremente con Él. Los discípulos de Cristo suelen entristecerse y apenarse aunque tienen razón para regocijarse, pero por la debilidad de su fe, no pueden tomar el consuelo ofrecido. Aunque Cristo entró a su estado de exaltación, todavía nota la tristeza de sus discípulos y se aflige de sus aflicciones.
Son forasteros en Jerusalén los que no saben de la muerte y de los padecimientos de Jesús. Los que tienen el conocimiento de Cristo crucificado, deben tratar de difundir ese saber. Nuestro Señor Jesús les reprochó la debilidad de su fe en las Escrituras del Antiguo Testamento. Si supiéramos más de los consejos divinos según han sido dados a conocer en las Escrituras, no estaríamos sujetos a las confusiones en que a menudo nos enredamos. Les muestra que los padecimientos de Cristo eran, realmente, el camino designado a su gloria, pero la cruz de Cristo era aquello en que ellos no se podían reconciliar por sí mismos. Empezando por Moisés, el primer escritor inspirado del Antiguo Testamento, Jesús les expone cosas acerca de sí mismo. Hay muchos pasajes en todas las Escrituras con referencia a Cristo, y es muy provechoso reunirlos. No nos adentramos en ningún texto sin encontrar algo referido a Cristo, una profecía, una promesa, una oración, un tipo u otra cosa. El hilo de oro de la gracia del evangelio recorre toda la trama del Antiguo Testamento. Cristo es el mejor expositor de la Escritura y, aun después de su resurrección, condujo a la gente a conocer el misterio acerca de sí mismo; no por el planteamiento de nociones nuevas, sino mostrándoles cómo se cumplió la Escritura, y volviéndolos al estudio ferviente de ellas.</p>
<br/>
<p class="text-justify">Vv. 28-35.Si deseamos tener a Cristo habitando en nosotros, debemos ser honestos con Él. Los que han experimentado el placer y el provecho de la comunión con Él, sólo pueden desear más de su compañía. Tomó el pan, lo bendijo y lo partió, y lo dio a ellos. Esto hizo con la autoridad y afecto acostumbrado, en la misma forma, quizás con las mismas palabras. Aquí nos enseña a desear una bendición para cada comida. Véase cómo Cristo, por su Espíritu y su gracia, se da a conocer a las almas de su pueblo. Les abre las Escrituras. Se reúne con ellos en su mesa, en la ordenanza de la cena del Señor; se da a conocer a ellos al partir el pan, pero la obra se completa abriéndoles los ojos del entendimiento; tenemos breves visiones de Cristo en este mundo, pero cuando entremos al cielo lo veremos para siempre.
Ellos habían encontrado poderosa la predicación, aunque no reconocieron al predicador. Las Escrituras que hablan de Cristo harán arder los corazones de sus verdaderos discípulos. Probablemente nos haga el mayor bien lo que nos afecta con el amor de Jesús al morir por nosotros. Es deber de aquellos a quienes se ha mostrado, dar a conocer al prójimo lo que Él ha hecho por sus almas. De gran uso para los discípulos de Cristo es comparar sus experiencias y contárselas unos a otros.</p>
<br/>
<p class="text-justify">Vv. 36-49.Jesús se apareció de manera milagrosa, asegurando a los discípulos su paz, aunque ellos lo habían olvidado tan recientemente, y prometiéndoles paz espiritual con cada bendición. Muchos pensamientos conflictivos que inquietan nuestra mente, proceden de errores sobre Cristo. Todos los pensamientos conflictivos que surgen en nuestros corazones en cualquier momento son conocidos por el Señor Jesús, y le desagradan. Habló con ellos sobre su incredulidad irracional. Nada ha pasado, sino lo anunciado por los profetas, y lo necesario para la salvación de los pecadores. Ahora, se debe enseñar a todos los hombres la naturaleza y la necesidad del arrepentimiento para el perdón de sus pecados. Se debe procurar estas bendiciones por fe en el nombre de Jesús. Cristo por su Espíritu obra en las mentes de los hombres. Hasta los hombres buenos necesitan que se les abra el entendimiento, pero para que piensen bien de Cristo, nada se necesita más que se les haga entender las Escrituras.</p>
<br/>
<p class="text-justify">Vv. 50-53.Cristo ascendió desde Betania, cerca del Monte de los Olivos. Ahí estaba el huerto donde empezaron sus sufrimientos; ahí estuvo en su agonía. Los que van al cielo deben ascender desde la casa de los sufrimientos y los dolores. Los discípulos no lo vieron salir de la tumba; su resurrección pudo probarse viéndolo vivo después: pero lo vieron ascender al cielo; de lo contrario, no hubiesen tenido pruebas de su ascensión.
Levantó las manos y los bendijo. No se fue descontento, sino con amor, dejando una bendición tras Él. Como resucitó, así ascendía, por su poder.
Ellos le adoraron. Esta nueva muestra de la gloria de Cristo sacó de ellos nuevos reconocimientos. Volvieron a Jerusalén con gran gozo. La gloria de Cristo es el gozo de todos los creyentes verdaderos, ya en este mundo. Mientras esperamos las promesas de Dios, debemos salir a recibirlas con alabanzas. Nada prepara mejor la mente para recibir al Espíritu Santo. Los temores son acallados, las penas endulzadas y aliviadas, y se conservan las esperanzas. Esta es la base de la confianza del cristiano ante el trono de la gracia; sí, el trono del Padre es el trono de la gracia para nosotros, porque también es el trono de nuestro Mediador, Jesucristo. Descansemos en sus promesas e invoquémoslas. Atendamos a sus ordenanzas, alabemos y bendigamos a Dios por sus misericordias, pongamos nuestros afectos en las cosas de arriba, y esperemos la venida del Redentor para completar nuestra felicidad. Amén. Sí, Señor Jesús, ven pronto.</p>
<br/>




</div>
