<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Malaquías 4</h2>
<p class="text-justify">Vv. 1-3.Aquí hay una referencia a la primera y segunda venida de Cristo: Dios ha fijado el día de ambas. Los que hacen el mal, los que no temen la ira de Dios, la sentirán. Ciertamente esto debe aplicarse al día del juicio en que Cristo será revelado en fuego llameante para ejecutar el juicio del orgulloso y de todos los que hacen el mal. En ambos, Cristo es luz de regocijo para los que le sirven fielmente.
Por el Sol de Justicia entendemos a Jesucristo. Por medio de Él los creyentes son justificado y santificados y, así, llevados a ver la luz. Sus influencias hacen santo, gozoso y fructífero al pecador. Es aplicable a las gracias y consolaciones del Espíritu Santo, llevadas a las almas de los hombres. Cristo dio el Espíritu a los que son suyos para que brillen como la mañana; es lo que ellos esperan, más que los que esperan la mañana. Cristo vino como el Sol a traer, no sólo luz a un mundo oscuro, sino salud a un mundo enfermo.
Las almas aumentarán en conocimiento y fuerza espiritual. Su crecimiento es como el de los terneros del establo, no como el de la flor del campo, que es esbelta y débil, y pronto se marchita. Los triunfos de los santos se deben, todos, a las victorias de Dios; no es que ellos hagan esto, sino que es Dios quien lo hace por ellos. He aquí, otro día llega, mucho más temible para todos los que hacen el mal que cualquiera de antes. ¡Qué grande entonces la dicha del creyente, cuando vaya de la oscuridad y miseria del mundo a regocijarse por siempre jamás en el Señor!</p>
<br/>
<p class="text-justify">Vv. 4-6.Aquí hay una solemne conclusión, no sólo de esta profecía, sino del Antiguo Testamento. La conciencia nos pide que recordemos la ley. Aunque no tenemos profetas, no obstante, en la medida que tenemos Biblias, podemos mantener nuestra comunión con Dios. Que los demás se jacten en su razonamiento orgulloso, y lo llame iluminación, pero mantengámonos nosotros cerca de esa palabra sagrada, por medio de la cual brilla este Sol de Justicia en las almas de su pueblo.
Ellos deben mantener la expectativa fiel del evangelio de Cristo, y deben esperar el comienzo de este. Juan el Bautista predicó arrepentimiento y reforma, como lo hizo Elías. El volverse de las almas a Dios y a su deber, es el mejor preparativo de ellos para el grande y temible día de Jehová. Juan predicará una doctrina que alcanzará los corazones de los hombres, y obrará un cambio en ellos. Así, él preparará el camino para el reino del cielo. La nación judía, por maldad, se abrió a la maldición. Dios estaba listo para ocasionarles ruina, pero, una vez más, probará si se arrepienten y vuelven a Él; por tanto, envió a Juan el Bautista para predicarles el arrepentimiento.
Que el creyente espere con paciencia su liberación y jubilosamente espere el gran día cuando Cristo venga por segunda vez a completar nuestra salvación. Pero los que no se vuelven al que los golpea con una vara, deben esperar ser golpeados con una espada, con una maldición. Nadie puede tener la expectativa de escapar de la maldición de la ley quebrantada de Dios, ni disfrutar la felicidad de su pueblo escogido y redimido, a menos que sus corazones se vuelvan del pecado y del mundo hacia Cristo y la santidad. La gracia de nuestro Señor Jesucristo sea con todos nosotros. Amén.</p>
<br/>




</div>
