<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Malaquías 1</h2>
<p class="text-justify">Vv. 1-5.Todas las ventajas, sean circunstancias externas, o privilegios espirituales, vienen del gratuito amor de Dios, que hace que una difiera de la otra. Todos los males que sienten y temen los pecadores, son la justa recompensa de sus delitos, mientras todas sus esperanzas y consuelos vienen de la misericordia inmerecida del Señor. Él escogió a su pueblo para que fuera santo. Si le amamos, es porque Él nos amó primero; pero todos tendemos a subvalorar las misericordias de Dios y a disculpar nuestras ofensas.</p>
<br/>
<p class="text-justify">Vv. 6-14.Podemos cargarnos con lo que aquí se carga a los sacerdotes. Nuestro parentesco con Dios, como Padre y Señor nuestro, nos obliga poderosamente a temerle y honrarle. Pero ellos se mofaban tanto que desdeñaban el reproche. Los pecadores se destruyen tratando de ahogar su convicción de pecado.
Los que viven en negligente descuido de las santas ordenanzas, los que asisten a ellas sin reverencia, y se van de ellas sin preocupación, dicen en efecto: La mesa de Jehová es despreciable. Ellos despreciaron el nombre de Dios en lo que hicieron. Evidente es que éstos no entendieron el significado de los sacrificios, como sombras del inmaculado Cordero de Dios; ellos reclaman por el gasto, pensando que todo era desperdicio si no les daba ganancia. Si adoramos a Dios con ignorancia y sin entendimiento, ofrecemos animal ciego como sacrificio; si lo hacemos despreocupadamente, si somos fríos, torpes y muertos en esto, llevamos la enferma; si nos apoyamos en el ejercicio corporal y no lo hacemos obra de corazón, llevamos el cojo; y si toleramos que se alojen en nosotros vanos pensamientos y distracciones, llevamos al despedazado. ¿Y esto no es malo? ¿No es una gran afrenta a Dios y un gran mal y lesión para nuestra propia alma? Para la aceptación de nuestras acciones por parte de Dios, no basta hacer lo bueno sólo por hacerlo, sino que debemos hacerlo por un principio bueno, en la manera buena y para un fin bueno. Nuestras constantes misericordias de parte de Dios, empeoran la pereza y tacañería de nuestra respuesta de deber a Dios. Será establecida la adoración espiritual. Se ofrecerá incienso al nombre de Dios, lo que significa oración y alabanza. Y ser una ofrenda pura.
Cuando llegó la hora en que los verdaderos adoradores adorarían al Padre en espíritu y en verdad, entonces se ofrendó el incienso, la ofrenda pura.
Podemos reposar en la misericordia de Dios por el perdón para lo pasado, pero no como indulgencia para el pecado en el futuro. Si hay una mente dispuesta, será aceptada, aunque esté defectuosa pero si hay un engañador dedicando lo mejor suyo a Satanás y a sus lujurias, está bajo maldición. Ahora los hombres profanan el nombre del Señor, aunque en manera diferente, contaminan su mesa, y muestran desprecio por su adoración.</p>
<br/>




</div>
