<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Malaquías 2</h2>
<p class="text-justify">Vv. 1-9.Lo que aquí se dice del pacto del sacerdocio vale para el pacto de gracia hecho con todos los creyentes como sacerdotes espirituales. Es un pacto de vida y paz; asegura toda dicha a todos los creyentes en este mundo y en el venidero. Honra para los siervos de Dios es ser empleados como sus mensajeros. Los labios del sacerdote no deben retener conocimiento de su pueblo, sino guardarlo para ellos. Todo el pueblo está preocupado por saber la voluntad del Señor. No sólo debemos consultar la palabra escrita, sino desear instrucción y consejo de los mensajeros de Dios, en los asuntos de nuestra alma. Los ministros deben emplearse a fondo para la conversión de los pecadores, y hasta entre los llamados israelitas, hay muchos que deben ser convertidos de la iniquidad. Los ministros y sólo los que predican la sana doctrina y llevan vidas santas conforme a la Escritura, probablemente, hagan volverse a los hombres del pecado. Muchos se apartaron de este camino y, así, guiaron mal al pueblo. Honran a Dios los que caminan con Dios en paz y justicia, y convierten a los demás del pecado; Él los honrará; en cambio, los que le desprecian serán ligeramente estimados.</p>
<br/>
<p class="text-justify">Vv. 10-17.Las costumbres corrompidas son fruto de principios corruptos; y el que es falso con su Dios no será veraz con sus congéneres mortales. Despreciando el pacto del matrimonio que Dios instituyó, los judíos despedían a la esposa que tenían de su nación, probablemente para dar lugar a esposas extranjeras. Ellas les amargaron la vida, pero a la vista de los demás pretendían ser tiernas con ellos. Considere a ella como esposa tuya; la tuya propia; la relación más cercana que uno tiene en el mundo. La esposa tiene que ser mirada, no como sierva, sino como compañera del marido. Hay un voto de Dios entre ellos, que no debe tomarse a la ligera. El marido y la esposa debieran continuar hasta el final de sus vidas en santo amor y paz. ¿No hizo Dios una, una Eva para un Adán? Pero Dios podría haber hecho otra Eva. ¿De dónde hizo Dios sólo una mujer para un hombre? Fue para que los hijos pudieran ser hechos una semilla que le sirviera a Él. Los maridos y las esposas deben vivir en el temor de Dios, para que su simiente sea una simiente buena. El Dios de Israel dijo que Él odiaba eliminar. Aquellos que serán resguardados del pecado deben tener cuidado de sus espíritus pues ahí empieza todo pecado. Los hombres hallarán que su mala conducta en sus familias brota del egoísmo que no toma en cuenta el bienestar y la dicha de los demás, cuando se opone a sus propias pasiones y fantasías. Cansador para Dios es oír que la gente justifica sus malas costumbres. Los que piensan que Dios puede ser amigo del pecado, lo insultan y se engañan. Los burladores dijeron: ¿Dónde está el Dios del juicio? Pero el día del Señor llegará.</p>
<br/>




</div>
