<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 2</h2>
<p class="text-justify">Vv. 1-12.Era la desgracia de este hombre que tuvieran que transportarlo de esa manera, y que muestra el estado de sufrimiento de la vida humana; fue una muestra de bondad de los que así lo llevaban y enseña la compasión que debiera haber en el hombre hacia sus congéneres que tienen dificultadeds. La fe verdadera y la fe firme pueden obrar de diversas maneras, pero será aceptada y aprobada por Jesucristo. El pecado es la causa de todos nuestros dolores y enfermedades. La manera de eliminar el efecto es eliminar la causa. El perdón de pecado golpea la raíz de todas las enfermedades. Cristo probó su poder para perdonar pecado mostrando su poder para curar al hombre enfermo de parálisis. La curación de las enfermedades era figura del perdón del pecado, porque el pecado es la enfermedad del alma; cuando es perdonado, es sanada. Cuando vemos lo que Cristo hace al sanar almas debemos reconocer que nunca vimos algo igual.
La mayoría de los hombres se piensan íntegros; no sienten necesidad de un médico, por tanto desprecian o rechazan a Cristo y su evangelio. Pero el pecador humilde y convicto, que desespera de toda ayuda, excepto del Salvador, mostrará su fe recurriendo a Él sin demora.</p>
<br/>
<p class="text-justify">Vv. 13-17.Mateo no era una buena persona, al contrario, porque siendo judío nunca debiera haber sido publicano, esto es, cobrador de impuestos para los romanos. Sin embargo, Cristo llamó a este publicano para que lo siguiera. Con Dios, a través de Cristo, hay misericordia para perdonar los pecados más grandes, y gracia para cambiar a los pecadores más grandes y hacerlos santos. Un publicano fiel que tratara con equidad era cosa rara. Debido a que los judíos tenían un odio particular por un oficio que demostraba que ellos estaban sometidos a los romanos, dieron un mal nombre a los cobradores de impuestos. Pero nuestro bendito Señor no vaciló en conversar con los tales cuando se manifestó en semejanza de carne de pecado. No es novedad que lo que está bien hecho y bien diseñado, sea calumniado y convertido en reproche para los hombres mejores y más sabios.
Cristo no se retractaría aunque se ofendieran los fariseos. Si el mundo hubiera sido justo no hubiera habido ocasión para su venida ni para predicar el arrepentimiento o comprar el perdón. No debemos seguir en compañía con los impíos por amor a su conversación vana; pero tenemos que mostrar amor a sus almas, recordando que nuestro buen Médico tenía en sí el poder de sanar, y que no corría peligro de contagiarse la enfermedad, pero no es así como nosotros. Al tratar de hacer bien al prójimo, tengamos cuidado con no dañarnos a nosotros mismos.</p>
<br/>
<p class="text-justify">Vv. 18-22.Los profesantes estrictos son buenos para hallar falta en todo lo que no concuerda plenamente con sus puntos de vista. Cristo no escapó de las calumnias; nosotros debemos estar dispuestos a soportarlas y poner cuidado para no merecerlas; debemos atender cada parte de nuestro deber en su orden y momento apropiado.</p>
<br/>
<p class="text-justify">Vv. 23-28.El día de reposo es una institución divina sagrada; privilegio y beneficio, no es tarea ni esclavitud. Dios nunca lo concibió para que fuera una carga para nosotros; por tanto, no debemos hacer que sea así. El día de reposo fue instituido para el bien de la humanidad, por cuanto vive en sociedad teniendo muchas necesidades y problemas, y se prepara para un estado de dicha o desdicha. El hombre no fue hecho para el día de reposo como si guardarlo pudiera ser un servicio a Dios, ni se le mandó que guardara sus formas externas para su perjuicio real. Toda obediencia al respecto debe interpretarse por la regla de la misericordia.</p>
<br/>




</div>
