<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 15</h2>
<p class="text-justify">Vv. 1-14. Ellos ataron a Cristo. Bueno es para nosotros recordar frecuentemente las ataduras del Señor Jesús, como que estamos atados con el que fue atado por nosotros. Al entregar al Rey, en efecto, ellos entregaron el reino de Dios, que por tanto, les fue quitado como por propio consentimiento de ellos, y fue dado a otra nación.
Cristo dio una respuesta directa a Pilato, pero no quiso responder a los testigos porque se sabía que las cosas que alegaron eran falsas, hasta el mismo Pilato estaba convencido que era así. Pilato pensó que podía apelar desde los sacerdotes al pueblo, y que ellos liberarían a Jesús de las manos de los sacerdotes, pero ellos fueron más y más presionados por los sacerdotes, y gritaron: ¡Crucifícalo! ¡Crucíficalo! Juzguemos a las personas y cosas por sus méritos y la norma de la palabra de Dios, y no por el saber corriente. El pensamiento de que nunca nadie fue tratado tan vergonzosamente, como la única Persona que es perfectamente excelente, santa y sabia que haya aparecido en la tierra, lleva a la mente seria a formarse una firme opinión de la maldad del hombre y la enemistad contra Dios. Aborrezcamos más y más las disposiciones malas que marcaron la conducta de esos perseguidores.</p>
<br/>
<p class="text-justify">Vv. 15-21.Cristo encontró a la muerte en su aspecto más terrorífico. Fue la muerte de los malhechores más viles. Así, se reúnen la cruz y la vergüenza. Dios había sido deshonrado por el pecado del hombre, Cristo dio satisfacción sometiéndose a la mayor desgracia con que la naturaleza humana podía ser cargada. Era una muerte maldita; así fue marcada por la ley judía, Deuteronomio xxi, 23. Los soldados romanos se burlaron de nuestro Señor Jesús como Rey; como los siervos se habían burlado de Él como Profeta y Salvador en el patio del sumo sacerdote. ¿Será un manto púrpura o escarlata una cuestión de orgullo para un cristiano, si fue cuestión de reproche y vergüenza para Cristo? Él llevó la corona de espinas que nosotros merecíamos, para que nosotros pudiéramos llevar la corona de gloria que Él merece. Nosotros fuimos por el pecado condenados a vergüenza y desprecio eternos. Él fue llevado con los hacedores de iniquidad, aunque Él no pecó. Los sufrimientos del manso y santo Redentor son siempre una fuente de instrucción para el creyente, de la cual no puede agotarse en sus mejores horas. ¿Sufrió Jesús así y yo, vil pecador, me afanaré o me pondré descontento? ¿Consentiré a la ira o emitiré reproches y amenazas debido a los problemas e injurias?</p>
<br/>
<p class="text-justify">Vv. 22-32.El lugar donde fue crucificado nuestro Señor Jesús, era llamado el lugar de la Calavera; era el lugar corriente para las ejecuciones, porque Él fue en todo aspecto contado entre los transgresores. Cada vez que miremos a Cristo crucificado, debemos recordar el escrito puesto sobre su cabeza: Él es un Rey y nosotros debemos rendirnos para ser sus súbditos, sin duda, como israelitas.
Crucificaron a dos ladrones con Él, y Él en el medio; con eso pretendían deshonrarlo mucho, pero estaba profetizado que sería contado con los transgresores, porque Él fue hecho pecado por nosotros.
Aun los que pasaban por ahí lo insultaban. Le decían que se bajara de la cruz, y creerían, pero no creyeron aunque les dio la señal más convincente cuando se levantó de la tumba. ¡Con qué fervor buscará salvación el hombre que cree firmemente la verdad, como es dada a conocer por los sufrimientos de Cristo! ¡Con cuánta gratitud recibirá la esperanza naciente del perdón y la vida eterna, adquiridas por los sufrimientos y la muerte del Hijo de Dios! ¡Y con qué piadosa tristeza se dolerá por los pecados que crucificaron al Señor de gloria!</p>
<br/>
<p class="text-justify">Vv. 33-41.Hubo una densa oscuridad sobre la tierra, desde el mediodía hasta las tres de la tarde. Los judíos estaban haciendo lo más que podían para apagar al Sol de Justicia. Las tinieblas significaban la nube bajo la cual estaba el alma humana de Cristo cuando la estaba presentando como ofrenda por el pecado. Él no se quejó de que sus discípulos lo abandonaran, sino de que su Padre lo desamparara. Especialmente en esto fue Él hecho pecado por nosotros. Cuando Pablo iba a ser ofrecido como sacrificio en el servicio de los santos, se gozaba y se regocijaba, Filipenses ii, 17; pero es otra cosa ser ofrecido como sacrificio por el pecado de los pecadores.
En el mismo instante en que Jesús murió, fue rasgado de arriba abajo el velo del templo. Esto expresó terror a los judíos incrédulos, y fue señal de la destrucción de su iglesia y nación. Expresa consuelo para todos los cristianos creyentes, porque significaba abrir un camino nuevo y vivo al Lugar Santísimo por la sangre de Jesús.
La confianza con que Cristo había tratado francamente a Dios como su Padre, encomendando su alma en sus manos, parece haber afectado mucho al centurión. Los puntos de vista correctos sobre Cristo crucificado reconcilian al creyente con el pensamiento de la muerte; anhela contemplar, amar, y alabar, como se debe, a ese Salvador que fue herido y traspasado para salvarlo de la ira venidera.</p>
<br/>
<p class="text-justify">Vv. 42-47.Aquí asistimos al entierro de nuestro Señor Jesús. ¡Oh, que nosotros podamos, por gracia, ser plantandos en su semejanza! José de Arimatea fue uno que esperaba el reino de Dios. Los que esperan por una cuota de sus privilegios deben confesar la causa de Cristo cuando parece estar aplastada. A este hombre levantó Dios para su servicio. Hubo una providencia especial, que Pilato fuera tan estricto en su investigación para que no hubiera pretensión de decir que Jesús estuviera vivo.
Pilato dio a José permiso para bajar el cuerpo, y hacer lo que le pareciera bien con él. Algunas de las mujeres vieron donde fue puesto Jesús, para poder ir después del día de reposo a ungir el cuerpo muerto porque no tuvieron tiempo de hacerlo antes. Se fijaron especialmente en el sepulcro de Cristo porque Él iba a levantarse de nuevo. Él no abandonará a los que confían en Él, y lo invocan. La muerte, privada de su aguijón, pronto terminará las penas del creyente, como terminó las del Salvador.</p>
<br/>




</div>
