<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 16</h2>
<p class="text-justify">Vv. 1-8.Nicodemo trajo una gran cantidad de especias, pero estas buenas mujeres no creyeron que fueran suficientes. El respeto que otros muestran a Cristo no nos debe impedir que mostremos nuestro respeto. Los que son llevados por el celo santo a buscar con diligencia a Cristo, encontrarán que los tropiezos del camino se desaparecen con rapidez. Cuando nos exponemos a problemas y gastos por amor a Cristo, somos aceptos aunque nuestros esfuerzos no tengan éxito. La vista del ángel podía haberlas animado, con justicia, pero ellas se asustaron. Así, pues, muchas veces lo que debiera ser nuestro consuelo, produce terror debido a nuestro propio error. -Él fue crucificado, pero está glorificado. Ha resucitado, no está aquí. No está muerto, y vive de nuevo; más adelante, le veréis, pero aquí podéis ver el lugar donde fue puesto. Así, se enviará el consuelo oportuno a los que lloran al Señor Jesús. Pedro es nombrado en particular: Decid a Pedro; esto lo recibirá muy bien, porque está triste por el pecado. Ver a Cristo es algo muy bien recibido por un verdadero arrepentido, y el penitente verdadero es muy bien recibido cuando quiere ver a Cristo. Los hombres corrieron a toda prisa hacia donde estaban los discípulos; pero los temores inquietantes suelen impedirnos hacer el servicio que podríamos hacer a Cristo y a las almas de los hombres, si la fe y el gozo de la fe fueran firmes.</p>
<br/>
<p class="text-justify">Vv. 9-13.Mejores noticias no pudieron ser llevadas a los discípulos que lloraban, que contarles de la resurrección de Cristo. Nosotros debiéramos estudiar para consolar a los discípulos dolientes diciéndoles lo que hemos visto de Cristo. Fue una sabia providencia que las pruebas de la resurrección de Cristo fueran dadas gradualmente, y recibidas con cautela, para que la seguridad con que los apóstoles predicaron esta doctrina después, fuera más satisfactoria. Sin embargo, ¡cuán lentos somos para admitir los consuelos que la palabra de Dios tiene! Entonces, mientras Cristo consuela a su pueblo, ve que, a menudo, es necesario reprenderlos y corregirlos por la dureza de corazón que desconfía de su promesa como asimismo que no obedece sus santos preceptos.</p>
<br/>
<p class="text-justify">Vv. 14-18.Las pruebas de la verdad del evangelio son tan completas que los que no las aceptan, pueden ser justamente reprendidos por su incredulidad.
Nuestro bendito Señor renueva la elección de los once como apóstoles suyos y les encarga la misión de ir a todo el mundo y predicar el evangelio a toda criatura. Sólo el que es verdadero cristiano será salvo por medio de Cristo. Simón el mago profesó creer, y fue bautizado, pero se declaró que estaba en los lazos de la iniquidad: léase su historia en Hechos viii, Vv. 13-15. Sin duda esta es una declaración solemne de la fe verdadera que recibe a Cristo en todos sus caracteres y oficios, y para todos los propósitos de la salvación, y produce su buen efecto en el corazón y la vida; no el simple asentimiento, que es fe muerta y no da provecho.
La comisión de los ministros de Cristo se extiende a toda criatura de todo el mundo, y las declaraciones del evangelio contienen no sólo verdades, exhortaciones y preceptos, sino también advertencias temibles. Osérvese con qué poder fueron dotados los apóstoles, para confirmar la doctrina que iban a predicar. Estos fueron milagros para confirmar la verdad del evangelio, y medios para difundirlo en las naciones que no lo habían oído.</p>
<br/>
<p class="text-justify">Vv. 19, 20.Después que el Señor habló, subió al cielo. Sentarse es una postura de reposo; había terminado su obra; es postura de gobierno: tomó posesión de su reino. Se sentó a la diestra de Dios, lo que denota su soberana dignidad y poder universal. Lo que Dios haga con nosotros, nos dé o nos acepte, es por su Hijo. Ahora Él está glorificado con la gloria que tuvo antes que el mundo fuese.
Los apóstoles fueron y predicaron en todas partes, lejos y cerca. Aunque la doctrina que predicaron era espiritual y celestial, directamente contraria al espíritu y temperamento del mundo; aunque se encontraron con mucha oposición, y fueron absolutamente desprovistos de todos los apoyos y ventajas del mundo, aun así, en unos pocos años, su voz llegó hasta lo último de la tierra. Los ministros de Cristo no necesitan ahora obrar milagros para probar su mensaje; está demostrado que las Escrituras son de origen divino y esto hace que no tengan excusa los que las rechazan o desprecian. Los efectos del evangelio, cuando se predica fielmente y se cree verdaderamente, y cambia los temperamentos y el carácter de la humanidad, son una prueba constante, una prueba milagrosa, de que el evangelio es poder de Dios para salvación a todo aquel que cree.</p>
<br/>




</div>
