<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 4</h2>
<p class="text-justify">Vv. 1-20.Esta parábola contenía instrucciones tan importantes que todos los capaces de oír estaban obligados a atender. Hay muchas cosas que debemos saber; y si no entendemos las verdades claras del evangelio, ¿cómo aprendemos las más difíciles? Nos servirá valorar los privilegios que disfrutamos como discípulos de Cristo, si meditamos seriamente en el estado deplorable de todos los que no tienen tales privilegios. En el gran campo de la Iglesia, se dispensa a todos la palabra de Dios. De los muchos que oyen la palabra del evangelio unos pocos la reciben como para dar fruto. Muchos que son muy afectados por la palabra momentáneamente no reciben un beneficio perdurable. La palabra no deja impresiones permanentes en la mente de los hombres porque su corazones no están debidamente dispuestos para recibirla. El diablo está muy ocupado con los escuchas negligentes, como las aves del aire lo están con la semilla que está sobre el suelo. Muchos siguen una profesión falsa y estéril, y se van al infierno. Las impresiones que no son profundas, no durarán. A muchos no les importa la obra de corazón sin la cual la religión es nada. La abundancia del mundo impide que otros sean beneficiados por la palabra de Dios. Los que tienen poco del mundo, pueden ser destruidos aun por darle gusto al cuerpo. Dios espera y requiere fruto de quienes disfrutan el evangelio, un temperamento mental y las gracias cristianas ejercidos diariamente, los deberes cristianos debidamente desempeñados. Miremos al Señor para que por su gracia regeneradora, nuestros corazones puedan llegar a ser buena tierra, y que la buena semilla de la palabra produzca en nuestra vida esas buenas palabras y obras que vienen por medio de Jesucristo para alabanza y gloria de Dios Padre.</p>
<br/>
<p class="text-justify">Vv. 21-34.Estas declaraciones estaban concebidas para atraer la atención de los discípulos a la palabra de Cristo. Por este tipo de instrucción, fueron capacitados para instruir a otros; como las velas se encienden, no para ser cubiertas, sino para ser puestas en un candelabro para que den luz a la habitación.
Esta parábola de la buena semilla, muestra la manera en que el reino de Dios avanza en el mundo. Que nada sino la palabra de Cristo tenga el lugar que debe tener en el alma, y se demostrará en la buena conversación. Crece paulatinamente: primero el brote; luego la hoja; después de eso, el trigo maduro en la espiga. Cuando ha brotado seguirá creciendo. La obra de gracia en el alma es, primero, sólo el día de las cosas pequeñas; sin embargo, ya tiene productos poderosos, mientras crece; ¡pero lo que habrá cuando esté perfeccionada en el cielo!</p>
<br/>
<p class="text-justify">Vv. 35-41.Cristo estaba dormido durante la tormenta para probar la fe de sus discípulos, e instarlos a orar. La fe de ellos se mostró débil y sus oraciones poderosas. Cuando nuestro corazón malvado es como el mar tempestuoso que no tiene reposo, cuando nuestras pasiones son ingobernables, pensemos que oímos la ley de Cristo diciendo: Calla, enmudece. Cuando afuera hay pleitos, y adentro temores, y los espíritus están inquietos, si Él dice, “paz, ten calma”, hay gran calma de inmediato. -¿Por qué estáis así amedrentados? Aunque haya causa para temer, de todos modos no la hay para un terror como éste. Pueden sospechar de su fe los que piensan que a Jesús no le importó mucho que su gente pereciera. ¡Cuán imperfectos son los mejores santos! La fe y el temor cumplen turnos mientras estemos en este mundo, pero, dentro de poco, el temor será vencido y la fe se perderá en la vista.</p>
<br/>




</div>
