<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 1</h2>
<p class="text-justify">Vv. 1-8.Isaías y Malaquías hablaron sobre el comienzo del evangelio de Jesucristo en el ministerio de Juan. De lo que dicen estos profetas podemos observar que Cristo, en un evangelio, viene a nosotros trayendo consigo un tesoro de gracia y un cetro de gobierno. Tal es la corrupción del mundo que hay gran oposición a su avance. Cuando Dios envió a su Hijo al mundo, y cuando lo manda al corazón, se encargó, y se encarga, de prepararle camino.
Juan se cree indigno del oficio más vil ante Cristo. Los santos más eminentes siempre han sido los más humildes. Sienten, más que los otros, su necesidad de la sangre expiatoria de Cristo y del Espíritu santificador. La gran promesa que hace Cristo en su evangelio a los arrepentidos y cuyos pecados han sido perdonados, es que serán bautizados con el Espíritu Santo; purificados por su gracia, y renovados por su consuelo. Usamos las ordenanzas, la palabra y los sacramentos en su mayor parte sin provecho ni consuelo, porque no tenemos la luz divina dentro de nosotros; y no la tenemos porque no la pedimos; porque dice su palabra que no puede fallar, que nuestro Padre celestial dará esta luz, su Espíritu Santo, a los que se lo pidan.</p>
<br/>
<p class="text-justify">Vv. 9-13.El bautismo de Cristo fue su primera aparición pública después de haber vivido mucho tiempo ignorado. ¡Cuánto valor oculto hay que no es conocido en este mundo! Pero, tarde o temprano, se conocerá, como lo fue Cristo. Tomó sobre sí la semejanza de la carne de pecado, y de este modo, por nosotros, se santificó a sí mismo para que también nosotros fuésemos santificados y bautizados con Él, Juan xvii, 19. Véase con cuán honra lo reconoció Dios, cuando se sometió al bautismo de Juan. Vio al Espíritu que descendía sobre Él como paloma. Podemos ver que se nos abre el cielo cuando vemos al Espíritu que baja y obra en nosotros. La buena obra de Dios en nosotros es prueba cierta de su buena voluntad hacia nosotros, y de sus preparativos para nosotros.
Marcos comenta de la tentación de Cristo que estaba en el desierto y que estaba con las bestias salvajes. Era un ejemplo del cuidado que su Padre tenía de Él, lo cual le animaba más en cuanto a la provisión que su Padre le daría. Las protecciones especiales son primicias de provisiones oportunas. La serpiente tentó al primer Adán en el huerto, al Segundo Adán en el desierto; sin duda que con diferente resultado, y desde entonces, sigue tentando a los hijos de ambos en todo lugar y condición. La compañía y la conversación tienen sus tentaciones; y estar a solas, aun en un desierto, también tiene las suyas. Ningún lugar ni estado exime, ninguna ocupación, ningún trabajo lícito, comer o beber, y hasta ayunar y orar; la mayoría de los asaltos suelen ocurrir en estos deberes, pero en ellos está la victoria más dulce.
El ministerio de los ángeles buenos es cosa de gran consuelo en contraste con los designios malos de los ángeles malos; pero nos consuela mucho más que nuestros corazones sean la morada de Dios Espíritu Santo.</p>
<br/>
<p class="text-justify">Vv. 14-22.Jesús empezó a predicar en Galilea, después que Juan fue encarcelado. Si alguien es desechado, otros serán levantados para ejecutar la misma obra. Obsérvese las grandes verdades que predicó Cristo. Por el arrepentimiento damos gloria a nuestro Creador a quien hemos ofendido; por la fe damos gloria a nuestro Redentor, que vino a salvarnos de nuestros pecados. Cristo ha unido ambas (la fe y el arrepentimiento) y que ningún hombre piense en separarlas.
Cristo da honra a los que son diligentes en sus cosas y amables unos con otros aunque sean poca cosa en este mundo. La laboriosidad y la unidad son buenas y agradables, y el Señor Jesús les manda una bendición. A los que Cristo llama deben dejar todo para seguirlo, y por su gracia hace que ellos quieran hacerlo así. No que tengamos que salir del mundo, sino que debemos soltar el mundo; abandonar todo lo que sea contrario a nuestro deber con Cristo, y no se pueda conservar sin dañar nuestras almas. Jesús guardó estrictamente el día de reposo aplicándose a ello y abundando en la obra del día de reposo para la cual fue designado el día de reposo. Hay mucho en la doctrina de Cristo que es asombroso; y mientras más la oímos, más causa vemos para admirarla.</p>
<br/>
<p class="text-justify">Vv. 23-28.El diablo es un espíritu inmundo porque perdió toda la pureza de su naturaleza, debido a que actúa en oposición directa al Espíritu Santo de Dios, y por sus sugerencias que contaminan los espíritus de los hombres. En nuestras asambleas hay muchos que calladamente atienden a maestros puramente formales, pero si el Señor llega con ministros fieles y la santa doctrina, y por Su Espíritu queda convicción, ellos están preparados para decir, como este hombre: ¡Qué tienes con nosotros, Jesús nazareno! Ningún trastorno capacita al hombre para saber que Jesús es el Santo de Dios. No quiere tener nada que ver con Jesús, porque no espera ser salvado por Él y teme ser destruido por Él. Véase el lenguaje que hablan los que dicen al Todopoderoso: Apártate de nosotros. Este espíritu inmundo odia y teme a Cristo porque sabe que Él es Santo, porque la mente carnal es enemistad contra Dios, especialmente contra su santidad.
Cuando Cristo, por su gracia, libra almas de las manos de Satanás, no es sin tumulto en el alma; porque ese enemigo maligno alborotará (inquietará) a los que no puede destruir. Esto hace que todos los que lo vieron piensen: ¿Qué es esta nueva doctrina? Ahora se hace una obra tan grande, pero los hombres la trataron con desprecio y descuido. Si no fuera así, la conversión de un hombre notoriamente malo a una vida sobria, justa y santa, por la predicación del Salvador crucificado, haría que muchos se pregunten: ¿Qué doctrina es esta?</p>
<br/>
<p class="text-justify">Vv. 29-39.Dondequiera que Cristo llega, viene a hacer el bien. Cura para que podamos ministrarlo a Él y al prójimo que es suyo y por amor a Él. Quienes no pueden ir a las ordenanzas públicas por estar enfermos o por otros impedimentos verdaderos, pueden esperar la gracia de la presencia del Salvador; Él calmará sus tristezas, y abatirá sus dolores. Obsérvese cuán numerosos eran los pacientes. Cuando otros andan bien con Cristo debiera instarnos a ir en pos de Él.
Cristo se fue a un lugar desierto. Aunque no corría peligro de distraerse o de tentación a la vanagloria, de todos modos se retiraba. Quienes desempeñan en público la mayor parte de su actividad, y de la mejor clase, a veces deben, no obstante, estar a solas con Dios.</p>
<br/>
<p class="text-justify">Vv. 40-45.Aquí tenemos que Cristo limpia a un leproso. Nos enseña a recurrir al Salvador con gran humildad y con sumisión total a su voluntad, diciendo: “Señor, si quieres”, sin dudar del ánimo pronto de Cristo para socorrer al angustiado. Véase también qué esperar de Cristo: que conforme a nuestra fe será hecho. El pobre leproso dijo: Si quieres. Cristo dispensa prestamente favores a los que prontamente se encomiendan a su voluntad. Cristo no hace nada que haga parecer como que busca la alabanza de la gente. Pero ahora no hay razón para que dudemos en difundir las alabanzas de Cristo.</p>
<br/>




</div>
