<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 10</h2>
<p class="text-justify">Vv. 1-12.Donde estuviera Jesús le seguían multitudes y Él les enseñaba. Predicar era costumbre constante de Jesús. Aquí señala que la razón por la cual la ley de Moisés permitió el divorcio, era de tal naturaleza que ellos no debían usar ese permiso; era solamente por la dureza de sus corazones. Dios mismo unió a marido y mujer; los preparó para que fueran de consuelo y ayuda mutuo. Lo que Dios unió no debe ser desatado a la ligera. Los que están por desechar a sus esposas piensen qué sería de ellos si Dios los tratara de esa manera.</p>
<br/>
<p class="text-justify">Vv. 13-16.Algunos padres o niñeras trajeron niños pequeños a Cristo para que Él los tocara como símbolo de su bendición sobre ellos. No parece que necesitaran sanidad corporal ni que fueran capaces de ser enseñados; pero los encargados de cuidarlos, creían que la bendición de Cristo haría bien a sus almas; por tanto, los llevaron a Él. Jesús mandó que los dejaran venir a Él y que nada debía decirse o hacerse para impedirlo. Los niños deben ser guiados al Salvador tan pronto como sean capaces de entender sus palabras. Además, debemos recibir el reino de Dios como niños pequeños; debemos ser afectuosos con Cristo y su gracia, como los niñitos con sus padres, niñeras y maestros.</p>
<br/>
<p class="text-justify">Vv. 17-22.Este joven rico mostró gran honestidad. Preguntó qué debía hacer ahora para ser feliz para siempre. La mayoría pide bienes para tenerlos en este mundo; cualquier bien, Salmo iv, 6; éste pide el bien que hay que hacer en este mundo para disfrutar del bien mayor en el otro. Cristo estimula esta pregunta asistiendo su fe y guiando su práctica.
Sin embargo, aquí hay una separación penosa entre Jesús y este joven. Pregunta a Cristo qué debe hacer además de lo que ya hizo para obtener la vida eterna; y Cristo le dice si tiene, como parece sin duda, esa fe firme en la vida eterna, y si le da elevado valor, ¿está dispuesto a soportar una cruz presente con la expectativa de una corona futura? El joven lamentó no poder ser un seguidor de Cristo en condiciones más fáciles; que no pudiera obtener la vida eterna y retener también sus posesiones mundanales. Se fue triste. Véase Mateo vi, 24: No podéis servir a Dios y Mamón.</p>
<br/>
<p class="text-justify">Vv. 23-31.Cristo aprovecha esta ocasión para hablar a sus discípulos sobre la dificultad de la salvación de quienes tienen abundancia en este mundo. Los que así buscan ansiosamente la riqueza del mundo, nunca valorarán en justicia a Cristo y su gracia. Además habla de la grandeza de la salvación de los que tienen poco de este mundo y lo dejan por Cristo. La prueba más grande de la constancia de un hombre bueno se produce cuando el amor a Jesús le pide que renuncie al amor a los amigos y a los familiares. Aunque vencedores por Cristo, aun deben esperar sufrir por Él hasta que lleguen al cielo. Aprendamos a contentarnos en una situación mala y a estar alertas contra el amor a las riquezas en una situación buena. Oremos para ser capaces de dejarlo todo si fuere necesario por el servicio de Cristo, y para usar en su servicio todo lo que se nos permita retener.</p>
<br/>
<p class="text-justify">Vv. 32-45.Cristo sigue adelante con su empresa para la salvación de la humanidad, cosa que fue, es y será el asombro de todos sus discípulos. La honra mundanal tiene un brillo, con el cual pueden haberse deslumbrado muchas veces los ojos de los discípulos mismos de Cristo. Cuidémonos de tener sabiduría y gracia para saber sufrir con Él; y que podamos confiar en que Él proveerá los grados de nuestra gloria.
Cristo les muestra que generalmente se abusa del poder en el mundo. Si Jesús nos concediera todos los deseos, pronto se haría evidente que deseamos fama o poder, y que no queremos beber su copa ni pasar su bautismo; con frecuencia sería una ruina que respondiera nuestras oraciones. Pero nos ama y dará a su pueblo sólo lo que es bueno para ellos.</p>
<br/>
<p class="text-justify">Vv. 46-52.Bartimeo, que había oído de Jesús y sus milagros, y sabido que iba a pasar por ahí, esperaba recuperar la vista. Al ir a Cristo a pedir ayuda y salud, debemos mirarlo como el Mesías prometido. Los llamados de gracia que Cristo nos hace para que vayamos a Él, animan nuestra esperanza de que si vamos a Él tendremos aquello por lo cual fuimos a Él. Quienes vayan a Jesús deben desechar el ropaje de su propia suficiencia, deben librarse de todo peso, y del pecado que, como ropajes largos, los asedian más fácilmente, Hebreos xii, 1. -Él ruega que sus ojos sean abiertos. Muy deseable es ser capaz de ganar nuestro pan; y donde Dios ha dado a los hombres sus extremidades y sentidos, es vergonzoso que, por necedad y pereza, se hagan efectivamente ciegos y cojos. Sus ojos fueron abiertos. Tu fe te ha hecho salvo: la fe en Cristo como el Hijo de David, y en su compasión y poder; no tus palabras repetidas, sino tu fe; Cristo pone a trabajar tu fe.
Los pecadores sean llamados a imitar al ciego Bartimeo. Jesús pasa por donde se predica el evangelio o circulan las palabras escritas de la verdad, y esta es la oportunidad. No basta con ir a Cristo por salud espiritual, sino que, cuando estemos sanados, debemos continuar siguiéndole, para que podamos honrarle y recibir instrucción de Él. Los que tienen vista espiritual ven en Cristo esa belleza atractiva que los hará correr tras Él.</p>
<br/>




</div>
