<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 14</h2>
<p class="text-justify">Vv. 1-11.¿Derramó Cristo Su alma hasta morir por nosotros, y pensaremos que haya algo demasiado precioso para Él? ¿Le damos el ungüento precioso de nuestros mejores afectos? Amémosle con todo el corazón aunque es común que el celo y el afecto sean malentendidos y culpados; y recordemos que la caridad para con el pobre no será excusa de ningún acto particular de piedad para con el Señor Jesús. Cristo elogió la piadosa atención de esta mujer para que lo sepan los creyentes de todas las épocas. A quienes honran a Cristo, Él los honrará. La codicia era la lujuria principal de Judas y eso le traicionó para que pecara traicionando a su Maestro; el diablo adaptó su tentación a eso y, de ese modo, lo venció. Véase cuántas tretas engañosas tienen muchos en sus esfuerzos pecaminosos; pero lo que parece progresar en sus planes, al final resultará ser maldición.</p>
<br/>
<p class="text-justify">Vv. 12-21.Nada podría ser menos resultado de la previsión humana que los sucesos aquí relatados. Pero nuestro Señor sabe todas las cosas sobre nosotros antes que acontezcan. Si lo recibimos, habitará en nuestros corazones.
El Hijo del Hombre va, como está escrito de Él, como cordero al matadero; pero ¡ay de aquel hombre por quien es entregado! Si Dios permite los pecados de los hombres, y se glorifica en ellos, no los obliga a pecar; ni es excusa para su culpa, ni aminorará el castigo.</p>
<br/>
<p class="text-justify">Vv. 22-31.La cena del Señor es alimento para el alma , por tanto, basta con muy poco en comparación con lo que es para el cuerpo en tanto sirva de señal. Fue instituida por el ejemplo y la práctica de nuestro Maestro para que siguiera vigente hasta su segunda venida. Fue instituida con bendición y acción de gracias para ser un memorial de la muerte de Cristo. Se menciona frecuentemente su preciosa sangre como el precio de nuestra redención. ¡Cuán consolador es esto para los pobres pecadores arrepentidos, que la sangre de Cristo sea derramada por muchos! Si por muchos, ¿por qué no por mí? Fue señal del traspaso de los beneficios adquiridos para nosotros por su muerte. Aplicaos la doctrina de Cristo crucificado a vosotros mismos; que sea carne y bebida para vuestras almas, fortaleciendo y refrescando vuestra vida espiritual. Iba a ser una primicia y un sabor anticipado de la dicha del cielo, y por ello, nos quita el gusto por los placeres y deleites de los sentidos. Todo el que ha saboreado las delicias espirituales, directamente desea las eternas.
Aunque el gran Pastor pasó por sus sufrimientos sin dar un paso en falso, sus seguidores han sido, no obstante, esparcidos a menudos por la pequeña medida de sufrimientos asignados a ellos. ¡Qué dados somos a pensar bien de nosotros mismos y a confiar en nuestros corazones! Fue malo que Pedro le contestara así a su Señor, sin temor ni temblor. Señor, dame gracia para evitar que te niegue.</p>
<br/>
<p class="text-justify">Vv. 32-42.Los sufrimientos de Cristo empezaron con los más dolorosos, los de su alma. Empezó a entristecerse y a angustiarse; palabras no empleadas en San Mateo, pero muy llenas de sentido. Los terrores de Dios lo combatieron, y Él le permitió contemplarlos. Nunca hubo dolor como su dolor hasta ahora. Él fue hecho maldición por nosotros; las maldiciones de la ley fueron echadas sobre Él como nuestra prenda. Ahora Él saboreó la muerte en toda su amargura. Esto era ese miedo del que habla el apóstol, el miedo natural al dolor y la muerte, ante la cual se sobresalta la naturaleza humana. ¿Podremos alguna vez tener pensamientos favorables o siquiera ligeros sobre el pecado, cuando vemos los penosos sufrimientos que el pecado trajo al Señor Jesús, aunque le fueron reconocidos? ¿Será leve para nuestras almas lo que fue tan pesado para la Suya? ¿Estuvo Cristo en tal agonía por nuestros pecados, y nosotros nunca agonizaremos por ellos? ¡Cómo debiéramos mirar a Aquel que traspasamos, y cómo debiera dolernos! Nos corresponde entristecernos excesivamente por el pecado, porque Él lo estuvo y nunca se rió de eso.
Cristo, como Hombre rogó que si era posible pasaran de Él sus sufrimientos. Como Mediador se sometió a la voluntad de Dios, diciendo: Mas no lo que yo quiero, sino lo que tú; lo acepto.
Véase cómo vuelve la pecaminosa debilidad de los discípulos de Cristo y los vence. ¡Qué lastres tan pesados son nuestros cuerpos para nuestras almas! Pero cuando veamos el problema en la puerta, debemos prepararnos para ello. Ay, hasta los creyentes suelen mirar de manera turbia los sufrimientos del Redentor, y en lugar de estar listos para morir con Cristo, ni siquiera están preparados para velar con Él durante una hora.</p>
<br/>
<p class="text-justify">Vv. 43-52.Debido a que Cristo no se manifestó como un príncipe temporal, sino que predicó el arrepentimiento, la reforma y la vida santa, y dirigió los pensamientos, afectos y propósitos de los hombres a otro mundo, por eso, los dirigentes judíos procuraron destruirlo.
Pedro hirió a uno de la partida. Es más fácil pelear por Cristo que morir por Él. Pero hay una gran diferencia entre los discípulos falibles y los hipócritas. Estos últimos llaman Maestro a Cristo, presurosos y sin pensar, y expresan gran afecto por Él, pero lo entregan a sus enemigos. Así aceleran su propia destrucción.</p>
<br/>
<p class="text-justify">Vv. 53-65.Aquí tenemos la condena de Cristo ante el gran consejo de los judíos. Pedro siguió, pero el lado del fuego del Sumo Sacerdote no era el lugar apropiado, ni sus siervos eran compañía adecuada para Pedro: era una entrada en la tentación.
Se empleó gran diligencia para conseguir testigos falsos contra Jesús aunque el testimonio de ellos no era equivalente a una acusación de delito capital, por mucho que ellos estiraran la ley. Se le preguntó: ¿Eres el Hijo del Bendito? Esto es, el Hijo de Dios. Él se refiere a su segunda venida para probar que es el Hijo de Dios.
Tenemos en estos ultrajes muchas pruebas de la enemistad del hombre hacia Dios, y del amor gratuito e indecible de Dios por el hombre.</p>
<br/>
<p class="text-justify">Vv. 66-72.La negación de Cristo por parte de Pedro empezó por mantenerse alejado de Él. Los que se avergüenzan de la santidad están bien avanzados en el camino de negar a Cristo. Quienes piensan que es peligroso andar en compañía de los discípulos de Cristo, porque de ahí pueden ser llevados a sufrir por Él, encontrarán mucho más peligroso estar en la compañía de sus enemigos, porque ahí serán llevados a pecar contra Él.
Cuando Cristo era admirado y lo seguían, Pedro lo confesó con prontitud; pero no reconoce su relación con Él ahora que está abandonado y despreciado. Pero obsérvese que el arrepentimiento de Pedro fue muy rápido.
El que piensa estar firme, mire que no caiga; y el que ha caído piense en estas cosas, y en sus propias ofensas, y vuelva al Señor con llanto y súplicas, buscando el perdón para ser levantado por el Espíritu Santo.</p>
<br/>




</div>
