<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Marcos 13</h2>
<p class="text-justify">Vv. 1-4.Obsévese en cuán poco valora Cristo la pompa externa, donde no hay verdadera pureza de corazón. Mira con compasión la ruina de almas preciosas, y llora por ellas, pero nosotros no lo hallamos mirando con lástima la ruina de una casa hermosa. Entonces, recordemos cuán necesario es que tengamos una habitación más perdurable en el cielo y estar preparados para ella por la obra del Espíritu Santo, buscada en el uso ferviente de todos los medios de gracia.</p>
<br/>
<p class="text-justify">Vv. 5-13.Nuestro Señor Jesús, al responder la pregunta de los discípulos, no hace tanto para satisfacer su curiosidad como para dirigir sus conciencias. Cuando muchos son engañados, debemos por ello ser despertados para examinarnos a nosotros mismos. Los discípulos de Cristo, si no es su propia falta, pueden disfrutar de santa seguridad y paz mental cuando todo a su alrededor está desordenado. Pero ellos deben cuidar de no ser alejados de Cristo y de su deber hacia Él por los sufrimientos con que se encontrarán por amor a Él. Serán odiados por todos los hombres: ¡problema más que suficiente! Pero la obra a la que fueron llamados debe seguir adelante y prosperar. Aunque ellos sean aplastados y derribados, el evangelio no puede serlo. La salvación prometida es más que liberación del mal, es bendición eterna.</p>
<br/>
<p class="text-justify">Vv. 14-23.Los judíos apresuraron el ritmo de su ruina al rebelarse contra los romanos y perseguir a los cristianos. Aquí tenemos una predicción de la destrucción que les sobrevino unos cuarenta años después de esto; una destrucción y un estrago como no los ha habido en la historia. Las promesas de poder para perseverar y las advertencias contra un alejamiento concuerdan bien unas con otras. Pero mientras más consideremos estas cosas, veremos motivos más abundantes para huir sin demora a refugiarnos en Cristo, y a renunciar a todo objeto terrenal por la salvación de nuestras almas.</p>
<br/>
<p class="text-justify">Vv. 24-27.Los discípulos habían confundido la destrucción de Jerusalén con el fin del mundo. Cristo corrigió este error y demostró que el día de la venida de Cristo y el día del juicio serán después de aquella tribulación. Aquí anuncia la disolución final del marco y trama presentes del mundo. Además, predice la aparición visible del Señor Jesús que viene en las nubes y la reunión de todos los elegidos con Él.</p>
<br/>
<p class="text-justify">Vv. 28-37.Tenemos la aplicación del sermón profético. En cuanto a la destrucción de Jerusalén, esperad que venga dentro de muy poco tiempo. En cuanto al fin del mundo, no preguntéis cuando vendrá, porque el día y la hora no lo sabe ningún hombre. Cristo, como Dios, no podía ignorar nada, por que la sabiduría divina que habitaba en nuestro Señor se comunicaba a su alma humana conforme al beneplácito divino. Nuestro deber respecto de las dos es estar alertas y orar. Nuestro Señor Jesús, cuando ascendió a lo alto, dejó algo para que todos sus siervos hagan. Siempre debemos estar vigilantes esperando su regreso. Esto se aplica a la venida de Cristo a nosotros en nuestra muerte y también al juicio general. No sabemos si nuestro Señor vendrá en los días de la juventud, en la edad mediana o en la vejez, pero, tan pronto como nacemos, empezamos a morir y, por tanto, debemos esperar la muerte. Nuestro gran afán debe ser que, cuando venga el Señor, no nos halle confiados, dándonos el gusto en comodidad y pereza, despreocupados de nuestra obra y del deber. A todos les dice: Velad, para que sean hallados en paz, sin mancha e irreprensibles.</p>
<br/>




</div>
