<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 11</h2>
<p class="text-justify">V. 1.Nuestro divino Redentor nunca se cansó de su obra de amor; y nosotros no debemos agotarnos de hacer el bien, porque a su debido tiempo cosecharemos si no desfallecemos.</p>
<br/>
<p class="text-justify">Vv. 2-6.Algunos piensan que Juan envió a preguntar esto para su satisfacción. Donde hay verdadera fe, puede aún haber una mezcla de duda. La incredulidad remanente en los hombres buenos puede, en la hora de tentación, cuestionar a veces las verdades más importantes. Pero esperamos que la fe de Juan no fallara en este asunto, y que él sólo deseara verla fortalecida y confirmada. Otros piensan que Juan envió a sus discípulos a Cristo para satisfacción de ellos.
Cristo les señala lo que han oído y visto. La condescendencia y la compasión de la gracia de Cristo por los pobres muestran que Él era quien debía traer al mundo las tiernas misericordias de nuestro Dios.
Las cosas que los hombres ven y oyen, comparadas con las Escrituras, dirigen el camino en que se debe hallar la salvación. Cuesta vencer prejuicios, y peligroso es no vencerlos, pero los que creen en Cristo, verán que su fe será hallada mucho más para la alabanza, honra y gloria.</p>
<br/>
<p class="text-justify">V. 7-15.Lo que Cristo dijo acerca de Juan no sólo fue para elogiarlo, sino para provecho del pueblo. Los que oyen la palabra serán llamados a dar cuenta de su provecho. ¿Pensamos que se termina el cuidado cuando se termina el sermón? No, entonces empieza el mayor de los cuidados.
Juan era un hombre abnegado, muerto para todas las pompas del mundo y los placeres de los sentidos. Conviene que la gente, en todas sus apariencias, sea coherente con su carácter y situación.
Juan era hombre grande y bueno, pero no perfecto; por tanto, no alcanzó la estatura de los santos glorificados. El menor en el cielo sabe más, ama más, y hace más alabando a Dios y recibe más de Él que el más grande de este mundo. Pero por el reino de los cielo aquí se debe entender más bien al reino de la gracia, la dispensación del evangelio en su poder y pureza. ¡Cuánta razón tenemos para estar agradecidos que nuestra suerte esté echada en los días del reino de los cielos, bajo tales ventajas de luz y amor! -Hay multitudes que fueron traídas por el ministerio de Juan y llegaron a ser discípulos suyos. Y hubo quienes lucharon por un lugar en este reino, que nadie pensaría que tenían derecho ni título para eso, y parecieron ser intrusos. Nos muestra cuánto fervor y celo se requiere de todos. Hay que negar el yo; hay que cambiar la inclinación, la disposición y el temperamento de la mente. Los que tengan un interés en la salvación grandiosa, lo tendrán a cualquier costo, y no pensarán que es difícil ni la dejarán ir sin una bendición. Las cosas de Dios son de preocupación grande y común. Dios no requiere más de nosotros que el uso justo de las facultades que nos ha dado. La gente es ignorante porque no quiere aprender.</p>
<br/>
<p class="text-justify">Vv. 16-24.Cristo reflexiona en los escribas y fariseos que tenían un orgulloso concepto de sí. Compara la conducta de ellos con el juego de los niños que, enojándose sin razón, rebaten todos los intentos de sus compañeros por complacerlos, o para que se unan a los juegos para los cuales acostumbraban reunirse.
Las objeciones capciosas de los hombres mundanos son a menudo muy burlonas y demuestran gran malicia. Algo tienen que criticar de todos por excelente y santo que sea. Cristo, que era inmaculado, y apartado de los pecadores, aquí se presenta junto con ellos y contaminado por ellos. La inocencia más inmaculada no siempre será defensa contra el reproche.
Cristo sabía que los corazones de los judíos eran más enconados y endurecidos contra sus milagros y doctrinas que los de Tiro y Sidón; por tanto, su condenación será mayor. El Señor ejerce su omnipotencia, pero no castiga más de lo que merecen y nunca retiene el conocimiento de la verdad de aquellos que lo anhelan.</p>
<br/>
<p class="text-justify">Vv. 25-30.Corresponde a los hijos ser agradecidos. Cuando vamos a Dios como Padre, debemos recordar que Él es el Señor de cielo y tierra, lo cual nos obliga a ir a Él con reverencia en cuanto es Señor soberano de todo; aunque con confianza como a Quien es capaz de defendernos del mal y proporcionarnos todo bien.
Nuestro bendito Señor agregó una declaración notable: que el Padre había puesto en Sus manos todo poder, autoridad y juicio. Estamos endeudados con Cristo por toda la revelación que tenemos de la voluntad y el amor de Dios Padre, aun desde que Adán pecó.
Nuestro Salvador ha invitado a todos los que trabajan fuerte y están muy cargados que vayan a Él. En algunos sentidos, todos los hombres están así. Los hombres mundanos se recargan con preocupaciones estériles por la riqueza y los honores; el alegre y sensual se esfuerza en pos de los placeres; el esclavo de Satanás y sus propias lujurias es el siervo más esclavizado de la tierra. Los que trabajan duro por establecer su propia justicia, también trabajan en vano. El pecador convicto está muy cargado de culpa y terror; y el creyente tentado y afligido tiene trabajos duros y cargas. Cristo los invita a todos a que vayan a Él en pos de reposo para sus almas. Él solo da esta invitación: los hombres van a Él cuando, sintiendo su culpa y miseria, y creyendo su amor y poder para socorrer, lo buscan con oración ferviente. Así, pues, es deber e interés de los pecadores trabajados y cargados, ir a Jesucristo. Este es el llamado del evangelio: quienquiera que quiera, venga. Todos los que así van recibirán reposo como regalo de Cristo, y obtendrán paz y consuelo en su corazón. Pero al ir a Él deben tomar su yugo y someterse a su autoridad. Deben aprender de Él todas las cosas acerca de su consuelo y obediencia. Él acepta al siervo dispuesto, por imperfectos que sean sus servicios. Aquí podemos hallar reposo para nuestras almas, y sólo aquí.
Ni tenemos que temer su yugo. Sus mandamientos son santos, justos y buenos. Requiere negarse a sí mismo y trae dificultades, pero esto es abundatemente recompensado, ya en este mundo, por la paz y el gozo interior. Es un yugo forrado con amor. Tan poderosos son los socorros que nos da, tan adecuadas las exhortaciones, y tan fuertes las consolaciones que se encuentran en el camino del deber, que podemos decir verdaderamente, que es un yugo grato. El camino del deber es el camino del reposo. Las verdades que enseña Cristo son tales que podemos aventurar por ellas nuestra alma.
Tal es la misericordia del Redentor, y ¿por qué debe el pecador laborioso y cargado buscar reposo en alguna otra parte? Vamos diariamente a Él en busca de la liberación de la ira y de la culpa, del pecado y de Satanás, de todas nuestras preocupaciones, temores y dolores. Pero la obediencia forzada, lejos de ser fácil y liviana, es carga pesada. En vano nos acercamos a Jesús con nuestros labios mientras el corazón esté lejos de Él. Entonces, venid a Jesús para hallar reposo para vuestras almas.</p>
<br/>




</div>
