<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 2</h2>
<p class="text-justify">Vv. 1-8.Los que viven completamente alejados de los medios de gracia suelen usar la máxima diligencia y aprenden a conocer lo máximo de Cristo y de su salvación. Pero ningún arte curioso ni el puro aprendizaje humano pueden llevar a los hombres a Él. Debemos aprender de Cristo atendiendo a la palabra de Dios, como luz que brilla en un lugar oscuro, y buscando la enseñanza del Espíritu Santo. Aquellos en cuyo corazón se levanta la estrella de la mañana, para darles el necesario conocimiento de Cristo, hacen de su adoración su actividad preferente.
Aunque Herodes era muy viejo, y nunca había mostrado afecto por su familia, y era improbable que viviera hasta que el recién nacido llegara a la edad adulta, empezó a turbarse con el temor de un rival. No comprendió la naturaleza espiritual del reino del Mesías. Cuidémonos de la fe muerta. El hombre puede estar persuadido de muchas verdades y aun puede odiarlas, porque interfieren con su ambición o licencia pecaminosa. Tal creencia le incomodará, y se decidirá más a oponerse a la verdad y la causa de Dios; y puede ser suficientemente necio para esperar tener éxito en eso.</p>
<br/>
<p class="text-justify">Vv. 9-12.Cuánto gozo sintieron estos sabios al ver la estrella, nadie lo sabe tan bien como quienes, después de una larga y triste noche de tentación y abandono, bajo el poder de un espíritu de esclavitud, al fin reciben el Espíritu de adopción, dando testimonio a sus espíritus que son hijos de Dios. Podemos pensar qué desilusión fue para ellos cuando encontraron que una choza era su palacio, y su propia y pobre madre era la única servidumbre que tenía. Sin embargo, estos magos no se creyeron impedidos, porque habiendo hallado al Rey que buscaban, le ofrecieron sus presentes. Quien busca humilde a Cristo no tropezará si lo halla a Él y a sus discípulos en chozas oscuras, después de haberlos buscado en vano en los palacios y ciudades populosas. -¿Hay un alma ocupada en buscar a Cristo? ¿Querrá adorarlo y decir, ¡sí!, yo soy una criatura pobre y necia y nada tengo que ofrecer? ¡Nada! ¿No tienes un corazón, aunque indigno de Él, oscuro, duro y necio? Dáselo tal como es, y prepárate para que Él lo use y disponga como le plazca; Él lo tomará, y lo hará mejor, y nunca te arrepentirás de habérselo dado. Él lo modelará a su semejanza, y Él mismo se te dará y será tuyo para siempre.
Los presentes de los magos eran oro, incienso, y mirra. La providencia los mandó como socorro oportuno para José y María en su actual condición de pobreza. Así, nuestro Padre celestial, que sabe lo que necesitan sus hijos, usa a algunos como mayordomos para suplir las necesidades de los demás y proveerles aun desde los confines de la tierra.</p>
<br/>
<p class="text-justify">Vv. 13-15.Egipto había sido una casa de esclavitud para Israel, y particularmente cruel para los infantes de Israel; pero va a ser un lugar de refugio para el santo niño Jesús. Cuando a Dios agrada, puede hacer que el peor de los lugares sirva al mejor de los propósitos. Esta fue una prueba de la fe de José y María. Pero la fe de ellos, siendo probada, fue hallada firme. Si nosotros y nuestros infantes estamos en problemas en cualquier tiempo, recordemos los apremios en que estuvo Cristo cuando era un infante.</p>
<br/>
<p class="text-justify">Vv. 16-18.Herodes mató todos los niños varones, no sólo de Belén, sino de todas las aldeas de esa ciudad. La ira desenfrenada, armada con un poder ilícito, a menudo lleva a los hombres a crueldades absurdas. No fue cosa injusta que Dios permitiera esto; cada vida es entregada a su justicia tan pronto como empieza. Las enfermedades y las muertes de los pequeños son prueba del pecado original. Pero el asesinato de estos niños fue su martirio. ¡Qué temprano empezó la persecución contra Cristo y su reinado! -Herodes creía que había obstruido las profecías del Antiguo Testamento, y los esfuerzos de los magos para hallar a Cristo; pero el consejo del Señor permanecerá por astutas y crueles que sean las artimañas del corazón de los hombres.</p>
<br/>
<p class="text-justify">Vv. 19-23.Egipto puede servir por un tiempo como estadía o refugio, pero no para quedarse a vivir. Cristo fue enviado a las ovejas perdidas de la casa de Israel, y a ellas debe retornar. Si miramos al mundo como a nuestro Egipto, el lugar de nuestra esclavitud y exilio, y sólo al cielo como nuestro Canaán, nuestro hogar, nuestro reposo, deberemos levantarnos rápido y partir de aquí cuando seamos llamados, como José salió de Egipto.
La familia debe establecerse en Galilea. Nazaret era lugar tenido en pobre estima, y Cristo fue crucificado con esta acusación, Jesús Nazareno. Donde quiera nos asigne la providencia los límites de nuestra habitación, debemos esperar compartir el reproche de Cristo; aunque podemos gloriarnos en ser llamados por su nombre, seguros de que si sufrimos con Él también seremos glorificados con Él.</p>
<br/>




</div>
