<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 6</h2>
<p class="text-justify">Vv. 1-4.En seguida, nuestro Señor advirtió contra la hipocresía y la simulación exterior en los deberes religiosos. Lo que hay que hacer, debemos hacerlo a partir de un principio interior de ser aprobados por Dios, no la búsqueda del elogio de los hombres. En estos versículos se nos advierte contra la hipocresía de dar limosna. Atención a esto. Es pecado sutil; y la vanagloria se infiltra en lo que hacemos, antes de darnos cuenta. Pero el deber no es menos necesario ni menos excelente porque los hipócritas abusan de él para servir a su orgullo. La condena que Cristo dicta parece primero una promesa, pero es su recompensa; no es la recompensa que promete Dios a los que hacen el bien, sino la recompensa que los hipócritas se prometen a sí mismos, y pobre recompensa es; ellos lo hicieron para ser vistos por los hombres, y son vistos por los hombres. Cuando menos notamos nuestras buenas obras, Dios las nota más. Él te recompensará; no como amo que da a su siervo lo que se gana, y nada más, sino como Padre que da abundantemente a su hijo lo que le sirve.</p>
<br/>
<p class="text-justify">Vv. 5-8.Se da por sentado que todos los que son discípulos de Cristo oran. Puede que sea más rápido hallar un hombre vivo que no respire que a un cristiano vivo que no ore. Si no hay oración, entonces no hay gracia. Los escribas y los fariseos eran culpables de dos grandes faltas en la oración: la vanagloria y la vana repetición. -“Verdaderamente ellos tienen su recompensa”; si en algo tan grande entre nosotros y Dios, cuando estamos orando, podemos tener en cuenta una cosa tan pobre como el halago de los hombres, justo es que eso sea toda nuestra recompensa. Pero no hay un musitar secreto y repetido en busca de Dios que Él no vea. Se le llama recompensa, pero es de gracia, no por deuda; ¿qué mérito puede haber en mendigar? Si no da a su pueblo lo que piden, se debe a que sabe que no lo necesitan y que no es para su bien. Tanto dista Dios de ser convencido por el largo o las palabras de nuestras oraciones, que las intercesiones más fuertes son las que se emiten con gemidos indecibles. Estudiemos bien lo que muestra la actitud mental en que debemos ofrecer nuestras oraciones, y aprendamos diariamente de Cristo cómo orar.</p>
<br/>
<p class="text-justify">Vv. 9-15.Cristo vio que era necesario mostrar a sus discípulos cuál debe ser corrientemente el tema y el método de su oración. No se trata que estemos atados sólo a usar la misma oración siempre, pero, indudablemente, es muy bueno orar según un modelo. Dice mucho en pocas palabras; se usa en forma aceptable no más de lo que se usa con entendimiento y sin vanas repeticiones.
Seis son las peticiones: las primeras tres se relacionan más expresamente a Dios y su honra; las otras tres, a nuestras preocupaciones temporales y espirituales. Esta oración nos enseña a buscar primero el reino de Dios y su justicia, y todas las demás cosas serán añadidas.
Después de las cosas de la gloria, del reino y de la voluntad de Dios, oramos por el sustento y el consuelo necesario en la vida presente. Aquí cada palabra contiene una lección. Pedimos pan ; eso nos enseña sobriedad y templanza: y sólo pedimos pan, no lo que no necesitamos. Pedimos por nuestro pan; eso nos enseña honestidad y trabajo; no tenemos que pedir el pan de los demás ni el pan del engaño, Proverbios xx, 17. Ni el pan del ocio, Proverbios xxxi, 27, sino el pan honestamente obtenido. Pedimos por nuestro pan diario , lo que nos enseña a depender constantemente de la providencia divina. Rogamos a Dios que nos los dé ; no que lo venda ni lo preste, sino que lo dé. El más grande de los hombres debe dirigirse a la misericordia de Dios para su pan diario. Oramos, dánoslo . Esto nos enseña compasión por el pobre. También que debemos orar con nuestra familia. Oramos que Dios nos lo dé este día , lo que nos enseña a renovar los deseos de nuestras almas en cuanto a Dios, como son renovadas las necesidades de nuestros cuerpos. Al llegar el día debemos orar a nuestro Padre celestial y reconocer que podríamos pasar muy bien el día sin comida, pero no sin oración.
Se nos enseña a odiar y aborrecer el pecado mientras esperamos misericordia, a desconfiar de nosotros, a confiar en la providencia y la gracia de Dios para impedirnos pecar, a estar preparados para resistir al tentador, y no volvernos tentadores de los demás.
Aquí hay una promesa: Si perdonas tu Padre celestial también te perdonará. Debemos perdonar porque esperamos ser perdonados. Los que desean hallar misericordia de Dios deben mostrar misericordia a sus hermanos. Cristo vino al mundo como el gran Pacificador no sólo para reconciliarnos con Dios sino los unos con los otros.</p>
<br/>
<p class="text-justify">Vv. 16-18.El ayuno religioso es un deber requerido a los discípulos de Cristo pero no es tanto un deber en sí mismo, sino como medio para disponernos para otros deberes. Ayunar es humillar el alma, Salmo xxxv, 13; esta es la faz interna del deber; por tanto, que sea tu principal interés, y en cuanto a la externa, no permitas que se vea codicia. Dios ve en lo secreto, y te recompensará en público.</p>
<br/>
<p class="text-justify">Vv. 19-24.La mentalidad mundana es síntoma fatal y corriente de la hipocresía, porque por ningún pecado puede Satanás tener un soporte más seguro y más firme en el alma que bajo el manto de una profesión de fe. Algo tendrá el alma que mirar como lo mejor aquello en lo cual se complace y confía por encima de todas las demás cosas. Cristo aconseja que hagamos como nuestras mejores cosas a los goces y las glorias del otro mundo, las cosas que no se ven, que son eternas y que pongamos nuestra felicidad en ellas. Hay tesoros en el cielo. Sabiduría nuestra es poner toda diligencia para asegurar nuestro derecho a la vida eterna por medio de Jesucristo, y mirar todas las cosas de aquí abajo como indignas de ser comparadas con aquellas y a estar contentos con nada menos que ellas. Es felicidad superior y más allá de los cambios y azares del tiempo, es herencia incorruptible.
El hombre mundano se equivoca en su primer principio; por tanto, todos sus razonamientos y acciones que de ahí surgen deben ser malos. Esto se aplica por igual a la falsa religión; lo que es considerado luz es la oscuridad más densa. Este es un ejemplo espantoso, pero corriente; por tanto, debemos examinar cuidadosamente nuestros principios directrices a la luz de la palabra de Dios, pidiendo con oración ferviente la enseñanza de su Espíritu.
Un hombre puede servir un poco a dos amos, pero puede consagrarse al servicio de no más que uno. Dios requiere todo el corazón y no lo compartirá con el mundo. Cuando dos amos se oponen entre sí, ningún hombre puede servir a ambos. Él se aferra y ama al mundo, y debe despreciar a Dios; el que ama a Dios debe dejar la amistad del mundo.</p>
<br/>
<p class="text-justify">Vv. 25-34.Escasamente haya otro pecado contra el cual advierta más nuestro Señor Jesús a sus discípulos que las preocupaciones inquietantes, distractoras y desconfiadas por las cosas de esta vida. A menudo esto entrampa al pobre tanto como el amor a la riqueza al rico. Pero hay una despreocupación por las cosas temporales que es deber, aunque no debemos llevar a un extremo estas preocupaciones lícitas.
No os afanéis por vuestra vida. Ni por la extensión de ella, sino referidla a Dios para que la alargue o acorte según le plazca; nuestros tiempos están en su mano y están en buena mano. Ni por las comodidades de esta vida; dejad que Dios la amargue o endulce según le plazca. Dios ha prometido la comida y el vestido, por tanto podemos esperarlos.
No penséis en el mañana, en el tiempo venidero. No os afanéis por el futuro, cómo viviréis el año que viene, o cuando estéis viejos, o qué dejaréis detrás de vosotros. Como no debemos jactarnos del mañana, así tampoco debemos preocuparnos por el mañana o sus acontecimientos. Dios nos ha dado vida y nos ha dado el cuerpo. ¿Y qué no puede hacer por nosotros el que hizo eso? Si nos preocupamos de nuestras almas y de la eternidad, que son más que el cuerpo y esta vida, podemos dejarle en manos de Dios que nos provea comida y vestido, que son lo menos.
Mejorad esto como exhortación a confiar en Dios. Debemos reconciliarnos con nuestro patrimonio en el mundo como lo hacemos con nuestra estatura. No podemos alterar las disposiciones de la providencia, por tanto debemos someternos y resignarnos a ellas. El cuidado considerado por nuestras almas es la mejor cura de la consideración cuidada por el mundo. Buscad primero el reino de Dios y haced de la religión vuestra ocupación: no digáis que este es el modo de hambrearte; no es la manera de estar bien provisto, aun en este mundo.
La conclusión de todo el asunto es que es la voluntad y el mandamiento del Señor Jesús, que por las oraciones diarias podamos obtener fuerza para sostenernos bajo nuestros problemas cotidianos, y armarnos contra las tentaciones que los acompañan y no dejar que ninguna de esas cosas nos conmuevan.
Bienaventurados los que toman al Señor como su Dios, y dan plena prueba de ellos confiándose totalmente a su sabia disposición. Que tu Espíritu nos dé convicción de pecado en la necesidad de esta disposición y quite lo mundano de nuestros corazones.</p>
<br/>




</div>
