<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 7</h2>
<p class="text-justify">Vv. 1-6.Debemos juzgarnos a nosotros mismos, y juzgar nuestros propios actos, pero sin hacer de nuestra palabra una ley para nadie. No debemos juzgar duramente a nuestros hermanos sin tener base. No debemos hacer lo peor de la gente. Aquí hay una reprensión justa para todos los que pelean con sus hermanos por faltas pequeñas, mientras ellos se permiten las grandes. Algunos pecados son como motas, mientras otros son como vigas; algunos son como un mosquito, y otros son como un camello. No es que haya pecado pequeño; si es como mota o una astilla, está en el ojo; si es un mosquito está en la garganta; ambos son dolorosos y peligrosos, y no podemos estar bien ni cómodos hasta que salgan. Lo que la caridad nos enseña a llamar no más que paja en el ojo ajeno, el arrepentimiento y la santa tristeza nos enseñará a llamarlo viga en el nuestro. Extraño es que un hombre pueda estar en un estado pecaminoso y miserable, y no darse cuenta de eso, como un hombre que tiene una viga en su ojo y no la toma en cuenta; pero el dios de este mundo les ciega el entendimiento.
Aquí hay una buena regla para los que juzgan: primero refórmate a ti mismo.</p>
<br/>
<p class="text-justify">Vv. 7-11.La oración es el medio designado para conseguir lo que necesitamos. Orad; orad a menudo; haced de la oración vuestra ocupación, y sed serios y fervientes en ello. Pedid, como un mendigo pide limosna. Pedid como el viajero pregunta por el camino. Buscad como se busca una cosa de valor que perdimos; o como el mercader que busca perlas buenas. Llamad como llama a la puerta el que desea entrar en casa. El pecado cerró y echó llave a la puerta contra nosotros; por la oracióñ llamamos.
Sea lo que sea por lo que oréis, conforme a la promesa, os será dado si Dios ve que es bueno para vosotros, y ¿qué más querrías tener? Esto está hecho para aplicarlo a todos los que oran bien; todo el que pide, recibe, sea judío o gentil, joven o viejo, rico o pobre, alto o bajo, amo o sirviente, docto o indocto, todos por igual son bienvenidos al trono de la gracia, si van por fe.
Se explica comparándolo con los padres terrenales y su aptitud para dar a sus hijos lo que piden. Los padres suelen ser neciamente afectuosos, pero Dios es omnisciente; Él sabe lo que necesitamos, lo que deseamos, y lo que es bueno para nosotros. Nunca supongamos que nuestro Padre celestial nos pediría que oremos y, luego, se negaría oír o darnos lo que nos perjudica.</p>
<br/>
<p class="text-justify">Vv. 12-14.Cristo vino a enseñarnos, no sólo lo que tenemos que saber y creer, sino lo que tenemos que hacer; no sólo para con Dios, sino para con los hombres; no sólo para con los que son de nuestro partido y denominación, sino para con los hombres en general, con todos aquellos que nos relacionemos. Debemos hacer a nuestro prójimo lo que nosotros mismos reconocemos que es bueno y razonable. En nuestros tratos con los hombres debemos ponernos en el mismo caso y en las circunstancias que aquellos con quienes nos relacionamos, y actuar en conformidad con ello.
No hay sino dos caminos: el correcto y el errado, el bueno y el malo; el camino al cielo y el camino al infierno; todos vamos caminando por uno u otro: no hay un lugar intermedio en el más allá; no hay un camino neutro. Todos los hijos de los hombres somos santos o pecadores, buenos o malos.
Fijaos en que el camino del pecado y de los pecadores que la puerta es ancha y está abierta. Podéis entrar por esta puerta con todas las lujurias que la rodean; no frena apetitos ni pasiones. Es un camino ancho; hay muchas sendas en este; hay opciones de caminos pecaminosos. Hay multitudes en este camino. Pero, ¿qué provecho hay en estar dispuesto a irse al infierno con los demás, porque ellos no irán al cielo con nosotros? El camino a la vida eterna es angosto. No estamos en el cielo tan pronto como pasamos por la puerta angosta. Hay que negar el yo, mantener el cuerpo bajo control, y mortificar las corrupciones. Hay que resistir las tentaciones diarias; hay que cumplir los deberes. Debemos velar en todas las cosas y andar con cuidado; y tenemos que pasar por mucha tribulación. No obstante, este camino nos invita a todos; lleva a la vida; al consuelo presente en el favor de Dios, que es la vida del alma; a la bendición eterna, cuya esperanza al final de nuestro camino debe facilitarnos todas las dificultades del camino. Esta simple declaración de Cristo ha sido descartada por muchos que se han dado el trabajo de hacerla desparecer con explicaciones pero, en todas la épocas el discípulo verdadero de Cristo ha sido mirado como una personalidad singular, que no está de moda; y todos los que se pusieron del lado de la gran mayoría, se han ido por el camino ancho a la destrucción. Si servimos a Dios, debemos ser firmes en nuestra religión. -¿Podemos oír a menudo sobre la puerta estrecha y el camino angosto y que son pocos los que los hallan, sin dolernos por nosotros mismos o sin considerar si entramos al camino angosto y cuál es el avance que estamos haciendo ahí?</p>
<br/>
<p class="text-justify">Vv. 15-20.Nada impide tanto a los hombres pasar por la puerta estrecha y llegar a ser verdaderos seguidores de Cristo, como las doctrinas carnales, apaciguadoras y halagadoras de quienes se oponen a la verdad. Estos pueden conocerse por el arrastre y los efectos de sus doctrinas. Una parte de sus temperamentos y conductas resulta contraria a la mente de Cristo. Las opiniones que llevan a pecar no vienen de Dios.</p>
<br/>
<p class="text-justify">Vv. 21-29.Aquí Cristo muestra que no bastará reconocerlos como nuestro Amo sólo de palabra y lengua. Es necesario para nuestra dicha que creamos en Cristo, que nos arrepintamos de pecado, que vivamos una vida santa, que nos amemos unos a otros. Esta es su voluntad, nuestra santificación.
Pongamos cuidado de no apoyarnos en los privilegios y obras externas, no sea que nos engañemos y perezcamos eternamente con una mentira a nuestra derecha, como lo hacen multitudes. Que cada uno que invoca el nombre de Cristo se aleje de todo pecado. Hay otros cuya religión descansa en el puro oír, sin ir más allá; sus cabezas están llenas de nociones vacías. Estas dos clases de oidores están representados por los dos constructores. Esta parábola nos enseña a oír y hacer los dichos del Señor Jesús: algunos pueden parecer duros para carne y sangre, pero deben hacerse. Cristo está puesto como cimiento y toda otra cosa fuera de Cristo es arena. Algunos construyen sus esperanzas en la prosperidad mundanal; otros, en una profesión externa de religión. Sobre estas se aventuran, pero esas son todo arena, demasiado débiles para soportar una trama como nuestras esperanzas del cielo.
Hay una tormenta que viene y probará la obra de todo hombre. Cuando Dios quita el alma, ¿dónde está la esperanza del hipócrita? La casa se derrumbó en la tormenta, cuando más la necesitaba el constructor, y esperaba que le fuera un refugio. Se cayó cuando era demasiado tarde para edificar otra. El Señor nos haga constructores sabios para la eternidad. Entonces, nada nos separará del amor de Cristo Jesús.
Las multitudes se quedaban atónitas ante la sabiduría y el poder de la doctrina de Cristo. Este sermón, tan a menudo leído, siempre es nuevo. Cada palabra prueba que su Autor es divino. Seamos cada vez más decididos y fervientes, y hagamos de una u otra de estas bienaventuranzas y gracias cristianas, el tema principal de nuestros pensamientos, por semanas seguidas. No descansemos en deseos generales y confusos al respecto, por los cuales podemos captar todo, pero sin retener nada.</p>
<br/>




</div>
