<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 4</h2>
<p class="text-justify">Vv. 1-11.Con referencia a la tentación de Cristo obsérvese que fue tentado inmediatamente después de ser declarado Hijo de Dios y Salvador del mundo; los grandes privilegios y las señales especiales del favor divino no aseguran a nadie que no va a ser tentado. Pero si el Espíritu Santo da testimonio que hemos sido adoptados como hijos de Dios, eso contestará todas las sugerencias del espíritu malo.
Cristo fue llevado al combate. Si hacemos gala de nuestra propia fuerza, y desafiamos al diablo a tentarnos, provocamos a que Dios nos deje librados a nosotros mismos. Otros son tentados, cuando son desviados por su propia concupiscencia, y son seducidos, Santiago i, 14; pero nuestro Señor Jesús no tenía naturaleza corrupta, por tanto Él fue tentado sólo por el diablo. Se manifiesta en la tentación de Cristo que nuestro enemigo es sutil, mal intencionado y muy atrevido, pero se le puede resistir. Consuelo para nosotros es que Cristo sufrió siendo tentado, porque, así, se manifiesta que nuestras tentaciones, mientras no cedamos a ellas, no son pecado y sólo son aflicciones. En todas sus tentaciones Satanás atacaba para que Cristo pecara contra Dios.
1. Lo tentó a desesperarse de la bondad de su Padre, y a desconfiar del cuidado de su Padre. Una de las tretas de Satanás es sacar ventaja de nuestra condición externa; y los que son puestos en apreturas tienen que redoblar su guardia. Cristo respondió todas las tentaciones de Satanás con un “Está escrito”para darnos el ejemplo al apelar a lo que está escrito en la Biblia. Nosotros debemos adoptar este método cada vez que seamos tentados a pecar. Aprendamos a no seguir rumbos equivocados a nuestra provisión, cuando nuestras necesidades son siempre tan apremiantes: el Señor proveerá en una u otra forma.
2. Satanás tentó a Cristo a que presumiera del poder y protección de su Padre en materia de seguridad. No hay extremos más peligrosos que la desesperación y la presunción, especialmente en lo referido a los asuntos de nuestra alma. Satanás no objeta lugares sagrados como escenario de sus asaltos. No bajemos la guardia en ningún lugar. La ciudad santa es el lugar donde, con la mayor ventaja, tienta a los hombres al orgullo y la presunción. Todos los altos son lugares resbalosos; el avance en el mundo hace al hombre un blanco para que Satanás le dispare sus dardos de fuego. ¿Satanás está tan bien versado en las Escrituras que es capaz de citarlas fácilmente? Sí, lo está. Es posible que un hombre tenga su cabeza llena de nociones de las Escrituras, y su boca llena de expresiones de las Escrituras mientras su corazón está lleno de enconada enemistad con Dios y contra toda bondad. Satanás citó mal las palabras. Si nos salimos de nuestro camino, fuera del camino de nuestro deber, abandonamos la promesa y nos ponemos fuera de la protección de Dios. Este pasaje, Deuteronomio viii, 3, hecho contra el tentador, por tanto él omitió una parte. Esta promesa es firme y resiste bien. ¿Pero seguiremos en pecado para que la gracia abunde? No.
3. Satanás tentó a Cristo a la idolatría con el ofrecimiento de los reinos del mundo y la gloria de ellos. La gloria del mundo es la tentación más encantadora para quien no piensa y no se da cuenta; esto es lo que más fácilmente vence a los hombres. Cristo fue tentado a adorar a Satanás. Rechazó con aborrecimiento la propuesta. “¡Vete de aquí Satanás!”Algunas tentaciones son abiertamente malas; y no son para ser simplemente resistidas, sino para ser rechazadas de inmediato. Bueno es ser rápido y firme para resistir la tentación. Si resistimos al diablo, éste huirá de nosotros. Pero el alma que delibera está casi vencida. Encontramos sólo unos pocos que pueden rechazar resueltamente tales carnadas, como las que ofrece Satanás aunque, ¿de qué le aprovecha a un hombre si gana a todo el mundo y pierde su alma? -Cristo fue socorrido después de la tentación para estimularlo a seguir en su esfuerzo, y para estimularnos a confiar en Él, porque supo, por experiencia, lo que es sufrir siendo tentado, de modo que sabía lo que es ser socorrido en la tentación; por tanto, podemos esperar no sólo que sienta por su pueblo tentado, sino que venga con el oportuno socorro.</p>
<br/>
<p class="text-justify">Vv. 12-17.Justo es que Dios quite el evangelio y los medios de gracia de quienes los desprecian y los arrojan de sí. Cristo no se quedará mucho tiempo donde no sea bienvenido. Los que están sin Cristo están en las tinieblas. Están instalados en esa condición, una postura contenta; la eligen antes que la luz; son voluntariamente ignorantes. Cuando viene el evangelio, viene la luz; cuando llega a cualquier parte, cuando llega a un alma, ahí se hace de día. La luz revela y dirige; así lo hace el evangelio.
La doctrina del arrepentimiento es buena doctrina del evangelio. No sólo el austero Juan el Bautista, sino el bondadoso Jesús predicó el arrepentimiento. Aún existe la misma razón para hacerlo así.
No se reconoció por completo que el reino de los cielos había llegado hasta la venida del Espíritu Santo después de la ascensión de Cristo.</p>
<br/>
<p class="text-justify">Vv. 18-22.Cuando Cristo empezó a predicar empezó a reunir discípulos que debían ser oyentes, y luego predicadores, de su doctrina, que debían ser testigos de sus milagros, y luego testificar acerca de ellos. No fue a la corte de Herodes, ni fue a Jerusalén a los sumos sacerdotes ni a los ancianos, sino al mar de Galilea, a los pescadores. El mismo poder que llamó a Pedro y a Andrés podría haber traído a Anás y a Caifás, porque nada es imposible con Dios. Pero Cristo elige lo necio del mundo para confundir a lo sabio.
La diligencia es un llamado honesto a complacer a Cristo, y no es un obstáculo para la vida santa. La gente ociosa está más abierta a las tentaciones de Satanás que a los llamados de Dios. Es cosa feliz y esperanzadora ver hijos que cuidan a sus padres y cumplen su deber. Cuando Cristo venga es bueno ser hallado haciendo así. ¿Estoy en Cristo? Es una pregunta muy necesaria que nos hagamos, y luego de esa, ¿estoy en mi llamado? -Habían seguido antes a Cristo como discípulos corrientes, Juan i, 37; ahora deben dejar su oficio. Los que siguen bien a Cristo deben, a su mandato, dejar todas las cosas para seguirle a Él, deben estar dispuestos a separarse de ellas. Esta instancia del poder del Señor Jesús nos exhorta a depender de su gracia. Él habla y está hecho.</p>
<br/>
<p class="text-justify">Vv. 23-25.Donde iba Cristo confirmaba su misión divina por medio de milagros, que fueron emblema del poder sanador de su doctrina y del poder del Espíritu que lo acompañaban. Ahora no encontramos en nuestros cuerpos el milagroso poder sanador del Salvador, pero si somos curados por la medicina, la alabanza es igualmente suya. Aquí se usan tres palabras generales. Él sanó toda enfermedad o dolencia; ninguna fue demasiado mala, ninguna demasiado terrible, para que Cristo no la sanara con una palabra. Se nombran tres enfermedades: la parálisis que es la suprema debilidad del cuerpo; la locura que es la enfermedad más grande de la mente; y la posesión demoníaca que es la desgracia y calamidad más grandes de todas; pero Cristo sanó todo y, así, al curar las enfermedades del cuerpo demostró que su gran misión al mundo era curar los males espirituales. El pecado es enfermedad, dolencia y tormento del alma: Cristo vino a quitar el pecado y, así, curar el alma.</p>
<br/>




</div>
