<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 8</h2>
<p class="text-justify">V. 1.Este versículo se refiere al final del sermón anterior. Aquellos a quienes Cristo se ha dado a conocer, desean saber más de Él.</p>
<br/>
<p class="text-justify">Vv. 2-4. En estos versículos tenemos el relato de la limpieza de un leproso hecha por Cristo; el leproso se acercó a Él y lo adoró como a Uno investido de poder divino. Esta purificación no sólo nos guía a acudir a Cristo, que tiene poder sobre las enfermedades físicas, para la sanidad de ellas; también nos enseña la manera de apelar a Él. Cuando no podemos estar seguros de la voluntad de Dios, podemos estar seguros de su sabiduría y misericordia. Por grande que sea la culpa, en la sangre de Cristo hay aquello que la expía; ninguna corrupción es tan fuerte que no haya en su gracia lo que puede someterla. Para ser purificados debemos encomendarnos a su piedad; no podemos demandarlo como deuda; debemos pedirlo humildemente como un favor.
Quienes por fe apelan a Cristo por misericordia y gracia, pueden estar seguros de que Él les está dando libremente la misericordia y la gracia que ellos así procuran. Benditas sean las aflicciones que nos llevan a conocer a Cristo, y nos hacen buscar su ayuda y su salvación.
Quienes son limpios de su lepra espiritual, vayan a los ministros de Cristo y expongan su caso, para ser aconsejados, consolados y para que oren por ellos.</p>
<br/>
<p class="text-justify">Vv. 5-13.Este centurión era pagano, un soldado romano. Aunque era soldado, no obstante, era un buen hombre. Ninguna vocación ni posición del hombre será excusa para la incredulidad y el pecado. Véase cómo expone el caso de su siervo. Debemos interesarnos por las almas de nuestros hijos y siervos, espiritualmente enfermos, que no sienten los males espirituales, y no conocen lo que es espiritualmente bueno; debemos llevarlos a Cristo por fe y por la oración.
Obsérvese su humillación. Las almas humildes se hacen más humildes por la gracia de Cristo en el trato con ellos. Obsérvese su gran fe. Mientras menos nos fiemos de nosotros mismos, más fuerte será nuestra confianza en Cristo. Aquí el centurión le reconoce mando con poder divino y pleno sobre todas las criaturas y poderes de la naturaleza, como un amo sobre sus siervos. Este tipo de siervos debemos ser todos para Dios; debemos ir y venir, conforme a los mandatos de su palabra y las disposiciones de su providencia.
Pero cuando el Hijo del Hombre viene, encuentra poca fe, por tanto, halla poco fruto. Una profesión externa hace que se nos llame hijos del reino, pero si descansamos en eso, y nada más podemos mostrar, seremos desechados.
El siervo obtuvo la sanidad de su enfermedad y el amo obtuvo la aprobación de su fe. Lo que se le dijo a él, se dice a todos: Cree y recibirás; sólo cree. Véase el poder de Cristo y el poder de la fe. La curación de nuestras almas es, de inmediato, el efecto y la prueba de nuestro interés en la sangre de Cristo.</p>
<br/>
<p class="text-justify">Vv. 14-17.Pedro tenía una esposa aunque era apóstol de Cristo, lo que demuestra que aprobaba el estado del matrimonio, siendo bondadoso con la madre de la esposa de Pedro. La iglesia de Roma, que prohíbe que sus ministros se casen, contradice a este apóstol, sobre el cual tanto se apoyan. Tenía a su suegra consigo en su familia, lo que es ejemplo de ser bueno con nuestros padres. En la sanidad espiritual, la Escritura dice la palabra, el Espíritu da el toque, toca el corazón, toca la mano. Aquellos que se recuperan de una fiebre suelen estar débiles por un tiempo; pero para mostrar que esta curación estaba por sobre el poder de la naturaleza, la mujer estuvo tan bien que de inmediato se dedicó a los quehaceres de la casa.
Los milagros que hizo Jesús fueron publicados ampliamente, de modo que muchos se agolparon viniendo a Él, y sanó a todos los que estaban enfermos, aunque el paciente estuviera muy débil y el caso fuera de lo peor. Muchas son las enfermedades y las calamidades del cuerpo a las que estamos propensos; y hay más en esas palabras del evangelio que dicen que Jesucristo llevó nuestras enfermedades y nuestros dolores, para sostenernos y consolarnos cuando estamos sometidos a ellos, que en todos los escritos de los filósofos. No nos quejemos por el trabajo, el problema o el gasto al hacer el bien al prójimo.</p>
<br/>
<p class="text-justify">Vv. 18-22.Uno de los escribas se apresuró a prometer; se dice cercano seguidor de Cristo. Parece muy resuelto. Muchas decisiones religiosas son producidas por una súbita convicción de pecado, y asumidas sin una debida reflexión; estas llegan a nada. Cuando este escriba ofreció seguir a Cristo, se podría pensar que Jesús debió sentirse animado; un escriba podía dar más crédito y servicio que doce pescadores; pero Cristo vio su corazón, y respondió a sus pensamientos, y, enseña a todos cómo ir a Cristo. Su resolución parece surgir de un principio mundano y codicioso; pero Cristo no tenía dónde reclinar su cabeza, y si él lo seguía, no debía esperar que le fuera mejor. Tenemos razón para pensar que este escriba se alejó.
Otro era demasiado lento. La demora en hacer es, por un lado, tan mala como la prisa para resolver por el otro. Pidió permiso para ocuparse de enterrar a su padre, y luego se pondría al servicio de Cristo. Esto parecía razonable aunque no era justo. No tenía celo verdadero por la obra. Enterrar al muerto, especialmente a un padre muerto, es una buena obra, pero no es tu obra en este momento. Si Cristo requiere nuestro servicio, debe cederse aun el afecto por los parientes más cercanos y queridos, y por las cosas que no son nuestro deber. A la mente sin disposición nunca le faltan las excusas. Jesús le dijo: Sígueme, y, sin duda, salió poder con esta palabra para él como para los otros; siguió a Cristo y se aferró de Él. El escriba dijo, yo te seguiré; a este otro hombre Cristo le dijo: Sígueme; comparándolos, se ve que somos llevados a Cristo por la fuerza de su llamado personal, Romanos ix, 16.</p>
<br/>
<p class="text-justify">Vv. 23-27.Consuelo para quienes se hacen a la mar en barcos, y suelen peligrar allí, es reflexionar que tienen un Salvador en quien confiar y al cual orar, que sabe qué es estar en el agua y estar en tormentas. Quienes están pasando por el océano de este mundo con Cristo, deben esperar tormentas.
Su naturaleza humana, semejante a nosotros en todo, pero sin pecado, estaba fatigada y se durmió en ese momento para probar la fe de sus discípulos. Ellos fueron a su Maestro en su temor. Así es en el alma; cuando las lujurias y las tentaciones se levantan y rugen, y Dios está, al parecer, dormido a lo que ocurre, esto nos lleva al borde de la desesperación. Entonces, se clama por una palabra de su boca: Señor Jesús, no te quedes callado o estoy acabado. Muchos que tienen fe verdadera son débiles en ella. Los discípulos de Cristo eran dados a inquietarse con temores en un día tempestuoso; se atormentaban a sí mismos con que las cosas estaban mal para ellos, y con pensamientos desalentadores de que vendrá algo peor. Las grandes tormentas de la duda y temor en el alma, bajo el poder del espíritu de esclavitud, suelen terminar en una calma maravillosa, creada y dirigida por el Espíritu de adopción.
Ellos quedaron estupefactos. Nunca habían visto que una tormenta fuera de inmediato calmada a la perfección. El que puede hacer esto, puede hacer cualquier cosa, lo que estimula la confianza y el consuelo en Él, en el día más tempestuoso de adentro o de afuera, Isaías xxvi, 4.</p>
<br/>
<p class="text-justify">Vv. 28-34.Los demonios nada tienen que ver con Cristo como Salvador; ellos no tienen ni esperan ningún beneficio de Él. ¡Oh, la profundidad de este misterio del amor divino: que el hombre caído tenga tanto que ver con Cristo, cuando los ángeles caídos nada tienen que ver con Él! Hebreos ii, 16. Seguramente que aquí sufrieron un tormento, al ser forzados a reconocer la excelencia que hay en Cristo, y aún así, no tener parte con Él. Los demonios no desean tener nada que ver con Cristo como Rey . Véase qué lenguaje hablan quienes no tendrán nada que ver con el evangelio de Cristo. Pero no es verdad que los demonios no tengan nada que ver con Cristo como Juez , porque tienen que ver, y lo saben; así es para con todos los hijos de los hombres.
Satanás y sus instrumentos no pueden ir más allá de lo que el Señor permita; ellos deben dejar la posesión cuando Él manda. No pueden romper el cerco de protección en torno a su pueblo; ni siquiera pueden entrar en un cerdo sin su permiso.
Recibieron el permiso. A menudo Dios permite, por objetivos santos y sabios, los esfuerzos de la ira de Satanás. Así, pues, el diablo apresura a la gente a pecar; los apura a lo que han resuelto en contra, de lo cual saben que será vergüenza y pena para ellos: miserable es la condición de los que son llevados cautivos por él a su voluntad.
Hay muchos que prefieren sus cerdos al Salvador y, así, no alcanzan a Cristo y la salvación por Él. Ellos desean que Cristo se vaya de sus corazones, y no soportan que Su Palabra tenga lugar en ellos, porque Él y su palabra destruirían sus concupiscencias brutales, eso que se entrega a los cerdos como alimento. Justo es que Cristo abandone a los que están cansados de Él; y después diga: Apartaos, malditos, a quienes ahora le dicen al Todopoderoso: Véte de nosotros.</p>
<br/>




</div>
