<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 20</h2>
<p class="text-justify">Vv. 1-16.El objeto directo de esta parábola parece ser demostrar que, aunque los judíos fueron llamados primero a la viña, en el largo plazo el evangelio será predicado a los gentiles que deben ser recibidos con los privilegios y ventajas en igualdad con los judíos. La parábola puede aplicarse también en forma más general y muestra, que: -1. Dios no es deudor de ningún hombre.
2. Muchos que empiezan al final, y prometen poco en la religión, a veces, por la bendición de Dios, llegan a mucho conocimiento, gracia y utilidad.
3. La recompensa será dada a los santos, pero no conforme al tiempo de su conversión. Describe el estado de la iglesia visible y explica la declaración de que los últimos serán los primeros, y los primeros, últimos, en sus diversas referencias.
Mientras no seamos contratados en el servicio de Dios estamos todo el día de ociosos: un estado pecaminoso, aunque para Satanás sea un estado de esclavitud, puede llamarse estado de ociosidad. El mercado es el mundo y de él fuimos llamados por el evangelio. Venid, salid de ese mercado. El trabajo para Dios no admite bagatelas. El hombre puede irse ocioso al infierno, pero quien vaya al cielo debe ser diligente.
El centavo romano era siete centavos, medio penique del dinero inglés, pagaba entonces suficiente para el sostén diario. Esto no prueba que la recompensa de nuestra obediencia a Dios sea de obras o de deuda; cuando hemos hecho todo, somos siervos inútiles; significa que hay una recompensa puesta ante nosotros, pero que nadie, por esta suposición, postergue el arrepentimiento hasta su vejez. Algunos fueron enviados a la viña en la hora undécima, pero nadie los había contratado antes. Los gentiles entraron a la hora undécima; el evangelio no había sido predicado antes a ellos. Quienes han tenido la oferta del evangelio en la hora tercera o sexta, y la han rechazado, no tendrán que decir en la hora undécima, como éstos: Nadie nos contrató.
Por tanto, no para desanimar a nadie sino para despertar a todos, es que se recuerda que ahora es el tiempo aceptable.
Las riquezas de la gracia divina son objetadas en voz alta por los fariseos orgullosos y por los cristianos nominales. Hay en nosotros una gran inclinación a pensar que tenemos demasiado poco, y los demás mucho de las señales del favor de Dios; y que hacemos demasiado y los demás muy poco en la obra de Dios. Pero si Dios da gracia a otros, es bondad para ellos, y no injusticia para nosotros. Las criaturas mundanas carnales están de acuerdo con Dios en cuanto a su riqueza en este mundo, y optan por su porción en esta vida. Los creyentes obedientes están de acuerdo con Dios en cuanto a su riqueza en el otro mundo, y deben recordar que estuvieron de acuerdo. ¿No acordaste tú tomar el cielo como porción tuya, como tu todo, y buscas tu felicidad en la criatura? Dios no castiga más de lo merecido, y premia cada servicio hecho por Él y para Él; por tanto, no hace mal a ninguno al mostrar gracia extraordinaria a otros.
Véase aquí la naturaleza de la envidia. Es una avaricia descontenta por el bien de los demás y que desea su mal. Es un pecado que no tiene placer, provecho ni honor. Dejemos irse todo reclamo orgulloso y procuremos la salvación como dádiva gratuita. No envidiemos ni murmuremos; regocijémonos y alabemos a Dios por su misericordia hacia los demás y con nosotros.</p>
<br/>
<p class="text-justify">Vv. 17-19.Aquí Cristo es más detallado que antes para predecir sus sufrimientos. Aquí, como antes, agrega la mención de su resurrección y su gloria, a la de su muerte y sus sufrimientos, para dar ánimo a sus discípulos, y consolarlos. Una manera de ver a nuestro Redentor una vez crucificado y ahora glorificado con fe, es buena para humillar la disposición orgullosa que se justifica a sí misma. Cuando consideramos la necesidad de la humillación y sufrimientos del Hijo de Dios, para la salvación de los pecadores perecederos, ciertamente debemos darnos cuenta de la liberalidad y de las riquezas de la gracia divina en nuestra salvación.</p>
<br/>
<p class="text-justify">Vv. 20-28.Los hijos de Zebedeo usaron mal lo que Cristo decía para consolar a los discípulos. Algunos no pueden tener consuelo; los transforman para un mal propósito. El orgullo es el pecado que más fácilmente nos acosa; es una ambición pecaminosa de superar a los demás en pompa y grandeza. Para abatir la vanidad y la ambición de su pedido, Cristo los guía a pensar en sus sufrimientos. Copa amarga es la que debe beberse; copa de temblor, pero no la copa del impío. No es sino una copa, pero seca y amarga quizá, pero pronto se vacía; es una copa en la mano del Padre, Juan xviii, 11. El bautismo es una ordenanza por la cual somos unidos al Señor en pacto y comunión; y así es el sufrimiento por Cristo, Ezequiel xx, 37; Isaías xlviii, 10. El bautismo es señal externa y visible de una gracia espiritual interior; así es el padecimiento por Cristo, que a nosotros es concedido, Filipenses i, 29. Pero no sabían qué era la copa de Cristo, ni qué era su bautismo. Comúnmente los más confiados son los que están menos familiarizados con la cruz. Nada hace más mal entre los hermanos que el deseo de grandeza. Nunca encontramos disputando a los discípulos de Cristo sin que algo de esto se halle en el fondo de la cuestión. El hombre que con más diligencia labora, y con más paciencia sufre, buscando hacer el bien a sus hermanos, y fomentar la salvación de las almas, más evoca a Cristo, y recibirá más honra de Él para toda la eternidad.
Nuestro Señor habla de su muerte en los términos aplicados a los sacrificios de antaño. Es un sacrificio por los pecados de los hombres, y es aquel sacrificio verdadero y esencial, que los de la ley representaban débil e imperfectamente. Era un rescate de muchos, suficiente para todos, obrando sobre muchos; y, si por muchos, entonces la pobre alma temblorosa puede decir, ¿por qué no por mí?</p>
<br/>
<p class="text-justify">Vv. 29-34.Bueno es que los sometidos a la misma prueba o enfermedad del cuerpo o de la mente, se unan para orar a Dios por alivio, para que puedan estimularse y exhortarse unos a otros. Hay suficiente misericordia en Cristo para todos los que piden. Ellos oraban con fervor. Clamaban como hombres apremiados. Los deseos fríos mendigan negaciones. Fueron humildes para orar, poniéndose a merced de la misericordia del mediador y refiriéndose alegremente a ella. Muestran fe al orar por el título que dieron a Cristo. Seguro que fue por el Espíritu Santo que trataron de Señor a Jesús. Perseveraron en oración. Cuando iban en busca de la misericordia no había tiempo para la timidez o la vacilación: clamaban con fervor.
Cristo los animó. Nos sensibilizamos rápidamente ante las necesidades y las cargas del cuerpo, y nos podemos relacionar con ellas con prontitud. ¡Oh, que nos quejásemos con tanto sentimiento de nuestras dolencias espirituales, especialmente de nuestra ceguera espiritual! Muchos están espiritualmente ciegos, pero dicen que ven. Jesús curó a estos ciegos y cuando hubieron recibido la vista, lo siguieron. Nadie sigue ciegamente a Cristo. Primero, por gracia Él abre los ojos de los hombres, y así atrae hacia Él sus corazones. Estos milagros son nuestro llamamiento a Jesús; podemos oírlo y hacerlo nuestra oración diaria para crecer en gracia y en el conocimiento del Señor y Salvador Jesucristo.</p>
<br/>




</div>
