<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 24</h2>
<p class="text-justify">Vv. 1-3.Cristo predice la total ruina y la destrucción futura del templo. Una crédula visión en fe de la desaparición de toda gloria mundanal, nos servirá para que evitemos admirarla y sobrevalorarla. El cuerpo más bello será pronto comida para los gusanos, y el edificio más magnífico, un montón de escombros. ¿No ve estas cosas? Nos hará bien que las miremos como viendo a través de ellas y viendo el fin de ellas.
Nuestro Señor, habiéndose ido con sus discípulos al Monte de los Olivos, puso ante ellos el orden de los tiempos en cuanto a los judíos, hasta la destrucción de Jerusalén, y en cuanto a los hombres en general hasta el fin del mundo.</p>
<br/>
<p class="text-justify">Vv. 4-28.Los discípulos preguntaron acerca de los tiempos, ¿Cuándo serán estas cosas? Cristo no les contestó eso, pero ellos también habían preguntado: ¿Cuál será la señal? Esta pregunta la contestó plenamente. La profecía trata primero los acontecimientos próximos, la destrucción de Jerusalén, el fin de la iglesia y del estado judíos, el llamado a los gentiles, y el establecimiento del reino de Cristo en el mundo; pero también mira al juicio general; y al cercano, apunta más en detalle a este último. Lo que dijo aquí Cristo a sus discípulos, tendía más a fomentar la cautela que a satisfacer su curiosidad; más a prepararlos para los acontecimientos que sucederían que a darles una idea clara de los hechos. Este es el buen entendimiento de los tiempos que todos debemos codiciar, para de eso inferir lo que Israel debe hacer.
Nuestro Salvador advierte a sus discípulos que estén en guardia contra los falsos maestros. Anuncia guerras y grandes conmociones entre las naciones. Desde el tiempo en que los judíos rechazaron a Cristo y Él dejó su casa desolada, la espada nunca se ha apartado de ellos. Véase lo que pasa por rechazar el evangelio. A los que no oigan a los mensajeros de la paz, se les hará oír a los mensajeros de la guerra. Pero donde esté puesto el corazón, confiando en Dios, se mantiene en paz y no se asusta. Contrario a la mente de Cristo es que su pueblo tenga corazones perturbados aun en tiempos turbulentos.
Cuando miramos adelante a la eternidad de la miseria que está ante los obstinados que rechazan a Cristo y su evangelio, podemos decir en verdad: Los juicios terrenales más grandes sólo son principio de dolores. Consuela que algunos perseveren hasta el fin.
Nuestro Señor predice la predicación del evangelio en todo el mundo. El fin del mundo sólo vendrá cuando el evangelio haya hecho su obra.
Cristo anuncia la ruina que sobrevendrá al pueblo judío; y lo que dice aquí, servirá a sus discípulos para su conducta y para consuelo. Si Dios abre una puerta de escape, debemos escapar, de lo contrario no confiamos en Dios, sino lo tentamos. En tiempos de trastorno público corresponde a los discípulos de Cristo estar orando mucho: eso nunca es inoportuno, pero se vuelve especialmente oportuno cuando estamos angustiados por todos lados. Aunque debemos aceptar lo que Dios envíe, aún podemos orar contra los sufrimientos; y algo que prueba mucho al hombre bueno es ser sacado por una obra de necesidad del servicio y adoración solemnes de Dios en el día de reposo. Pero he aquí una palabra de consuelo, que por amor a los elegidos esos días serán acortados en relación a lo que concibieron sus enemigos, que los hubieran cortados a todos, si Dios, que usó a esos enemigos para servir sus propósitos, no hubiera puesto límite a la ira de ellos.
Cristo anuncia la rápida difusión del evangelio en el mundo. Es visto simplemente como el rayo. Cristo predicó abiertamente su evangelio. Los romanos eran como águila y la insignia de sus ejércitos era el águila. Cuando un pueblo, por su pecado, se hace como asquerosos esqueletos, nada puede esperarse, sino que Dios envíe enemigos para destruirlo. Esto es muy aplicable al día del juicio, la venida de nuestro Señor Jesucristo en ese día, 2 Tesalonicenses ii, 1, 2. Pongamos diligencia para hacer segura nuestra elección y vocación; entonces podremos saber que ningún enemigo ni engañador prevalecerá contra nosotros.</p>
<br/>
<p class="text-justify">Vv. 29-41.Cristo predice su segunda venida. Es habitual que los profetas hablen de cosas cercanas y a la mano para expresar la grandeza y certidumbre de ellas. En cuanto a la segunda venida de Cristo, se anuncia que habrá un gran cambio para hacer nuevas todas las cosas. Entonces verán al Hijo del hombre que viene en la nubes. En su primera venida fue puesto como señal que sería contradicha, pero en su segunda venida, una señal que debe ser admirada.
Tarde o temprano, todos los pecadores se lamentarán, pero los pecadores arrepentidos miran a Cristo y se duelen de manera santa; y los que siembran con lágrimas cosecharán con gozo dentro de poco. Los pecadores impenitentes verán a Aquel que traspasaron y, aunque ahora ríen, entonces lamentarán y llorarán con horror y desesperación interminable.
Los elegidos de Dios están dispersos en todas partes; los hay en todas partes y en todas las naciones, pero cuando llegue ese gran día de reunión no habrá uno solo de ellos que falte. La distancia del lugar no dejará a nadie fuera del cielo. Nuestro Señor declara que los judíos nunca cesarán de ser un pueblo distinto hasta que se cumplan todas las cosas que había predicho. Su profecía llega al día del juicio final; por tanto, aquí, versículo 34, anuncia que Judá nunca dejará de existir como pueblo distinto, mientras dure este mundo.
Los hombres del mundo complotan y planean de generación en generación, pero no planean con referencia al hecho más seguro de la segunda venida de Cristo, que se acerca sobrecogedor, el cual terminará con toda estratagema humana, y echará a un lado por siempre todo lo que Dios prohíbe. Ese será un día tan sorpresivo como el diluvio para el mundo antiguo.
Aplíquese esto, primero, a los juicios temporales, particularmente el que entonces llegaba apresuradamente a la nación y pueblo de los judíos. Segundo, al juicio eterno. Aquí Cristo muestra el estado del mundo antiguo cuando llegó el diluvio; y ellos no creían. Si nosotros supiéramos correctamente que todas las cosas terrenales deben pasar dentro de poco, no pondríamos nuestros ojos y nuestro corazón en ellas tanto como lo hacemos. ¡Qué palabras pueden describir con más fuerza lo súbito de la llegada de nuestro Salvador! Los hombres estarán en sus respectivas ocupaciones y, repentinamente se manifestará el Señor de gloria. Las mujeres estarán en sus tareas domésticas, pero en ese momento toda otra obra será dejada de lado, y todo corazón se volverá adentro y dirá, ¡es el Señor! ¿Estoy preparado para encontrarlo? ¿Puedo estar ante Él? Y de hecho ¿qué es el día del juicio para todo el mundo, si no el día de la muerte de cada uno?</p>
<br/>
<p class="text-justify">Vv. 42-51.Velar por la venida de Cristo es mantener el temperamento mental en que deseamos que nos halle nuestro Señor. Sabemos que tenemos poco tiempo para vivir, no podemos saber si tenemos largo tiempo para vivir; mucho menos sabemos el tiempo fijado para el juicio.
La venida de nuestro Señor será feliz para los que estén preparados, pero será muy espantosa para quienes no lo estén. Si un hombre, que profesa ser siervo de Cristo, es incrédulo, codicioso, ambicioso o amante del placer, será cortado. Quienes escogen por porción el mundo en esta vida, tendrán el infierno como porción en la otra. Que nuestro Señor, cuando venga, nos sentencie bienaventurados y nos presente ante el Padre, lavados en su sangre, purificados por su Espíritu, y aptos para ser partícipes de la suerte de los santos en luz.</p>
<br/>




</div>
