<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 9</h2>
<p class="text-justify">Vv. 1-8.La fe de los amigos del paralítico al llevarlo a Cristo era una fe firme; ellos creían firmemente que Jesucristo podía y querría sanarlo. Una fe fuerte no considera los obstáculos al ir en busca de Cristo. Era una fe humilde; ellos lo llevaron a esperar en Cristo. Era una fe activa. El pecado puede ser perdonado, pero no ser eliminada la enfermedad; la enfermedad puede ser quitada, pero no perdonado el pecado: pero si tenemos el consuelo de la paz con Dios, con el consuelo de la recuperación de la enfermedad, esto hace que, sin duda, la sanidad sea una misericordia. Esto no es exhortación para pecar. Si tú llevas tus pecados a Jesucristo, como tu enfermedad y tu desgracia para ser curados de esto, y librados de aquello, es bueno; pero ir con ellos, como tus amores y deleites, pensando aún en retenerlos y recibirlo a Él, es un tremendo error, un engaño miserable. La gran intención del bendito Jesús en la redención que obró, es separar nuestros corazones del pecado.
Nuestro Señor Jesús tiene perfecto conocimiento de todo lo que decimos dentro de nosotros mismos. Hay mucho mal en los pensamientos pecaminosos, que es muy ofensivo para el Señor Jesús. A Cristo le interesa mostrar que su gran misión al mundo era salvar a su pueblo de sus pecados. Dejó el debate con los escribas y pronunció las palabras de salud al enfermo. No sólo no tuvo más necesidad de que lo llevaran en su lecho, sino que tuvo fuerzas para llevarlo él. Dios debe ser glorificado en todo el poder que se da para hacer el bien.</p>
<br/>
<p class="text-justify">Vv. 9.Mateo fue en su llamado, como los demás a los que Cristo llamó. Como Satanás viene con sus tentaciones al ocioso, así viene Cristo con sus llamados a los que están ocupados. Todos tenemos natural aversión a ti, oh Dios; llámanos a seguirte; atráenos por tu poderosa palabra y correremos en pos de ti. Habla por la palabra del Espíritu a nuestros corazones, el mundo no puede retenernos, Satanás no puede detener nuestro camino, nos levantaremos y te seguiremos. Cristo como autor, y su palabra como el medio, obra un cambio salvador en el alma. Ni el cargo de Mateo ni sus ganancias, pudieron detenerlo cuando Cristo lo llamó. Él lo dejó todo, y aunque después, ocasionalmente, a los discípulos que eran pescadores los hallamos pescando otra vez, nunca más encontramos a Mateo en sus ganancias pecaminosas.</p>
<br/>
<p class="text-justify">Vv. 10-13.Algún tiempo después de su llamado, Mateo procuró llevar a sus antiguos socios a que oyeran a Cristo. Sabía por experiencia lo que podía hacer la gracia de Cristo y no se desesperó al respecto. Los que son eficazmente llevados a Cristo no pueden sino desear que los demás también sean llevados a Él.
Aquellos que suponen que sus almas están sin enfermedad no acogerán al Médico espiritual. Este era el caso de los fariseos; ellos despreciaron a Cristo porque se creían íntegros; pero los pobres publicanos y pecadores sentían que les faltaba instrucción y enmienda. Fácil es, y también corriente, poner las peores interpretaciones sobre las mejores palabras y acciones. Puede sospecharse con justicia que los que no tienen la gracia de Dios, no se complacen con que otros la consigan. Aquí se llama misericordia que Cristo converse con los pecadores, porque fomentar la conversión de las almas es el mayor acto de misericordia.
El llamado del evangelio es un llamado al arrepentimiento; un llamado para que cambiemos nuestro modo de pensar y cambiemos nuestros caminos. Si los hijos de los hombres no fueran pecadores no hubiera sido necesario que Cristo viniera a ellos. Examinemos si hemos investigado nuestra enfermedad y si hemos aprendido a seguir las órdenes de nuestro gran Médico.</p>
<br/>
<p class="text-justify">Vv. 14-17.En esta época Juan estaba preso; sus circunstancias, su carácter, y la naturaleza del mensaje que fue enviado a dar, guió a los que estaban peculiarmente afectos a él, a realizar ayunos frecuentes. Cristo los refirió al testimonio que Juan da de Él, Juan iii, 29. Aunque no cabe duda de que Jesús y sus discípulos vivieron en forma frugal y económica, sería impropio que sus discípulos ayunaran mientras tenían el consuelo de su presencia. Cuando está con ellos, todo está bien. La presencia del sol hace el día, y su ausencia produce la noche.
Nuestro Señor les recuerda luego las reglas comunes de la prudencia. No se acostumbraba tomar un pedazo de tela de lana cruda, que nunca había sido preparada, para coserla a un traje viejo, porque no se uniría bien con el ropaje viejo y suave, sino que lo desgarraría aún más, y la rasgadura sería peor. Ni tampoco los hombres echaban vino nuevo en odres viejos, que iban a podrirse y se reventarían por la fermentación del vino; al poner el vino nuevo en odres nuevos y fuertes, ambos serían preservados. Se requiere gran prudencia y cautela para que los nuevos convertidos no reciban ideas sombrías y prohibitorias del servicio de nuestro Señor; antes bien serán estimulados en los deberes a medida que sean capaces de soportarlos.</p>
<br/>
<p class="text-justify">Vv. 18-26.La muerte de nuestros familiares debe llevarnos a Cristo que es nuestra vida. Gran honor para los reyes más grandes es esperar en el Señor; y los que reciban misericordia de Cristo deben honrarle. La variedad de métodos que Cristo usó para hacer sus milagros quizá se debió a las diferentes disposiciones mentales y temperamentos con que venían los que a Él acudían; todo esto lo conocía perfectamente Aquel que escudriña los corazones.
Una pobre mujer apeló a Cristo y recibió de Él misericordia, al pasar por el camino. Si sólo tocásemos, como si así fuera, el borde de la túnica de Cristo por fe viva, serán sanados nuestros peores males; no hay otra cura verdadera ni tenemos que temer que sepa cosas que son dolor y carga para nosotros, y que no las contaríamos a ningún amigo terrenal.
Cuando Cristo entró a la casa del hombre principal dijo: Apartaos. A veces, cuando prevalece el dolor del mundo, es difícil que entren Cristo y sus consolaciones. La hija del principal estaba realmente muerta, pero no para Cristo. La muerte del justo, de manera especial, debe ser considerada sólo un dormir.
Las palabras y las obras de Cristo pueden no ser entendidas al comienzo, aunque por eso no deben ser despreciadas. La gente fue fortalecida. Los escarnecedores que se ríen de lo que no entienden no son testigos apropiados de las maravillosas obras de Cristo. Las almas muertas no son resucitadas a la vida espiritual, a menos que Cristo las tome de la mano: está hecho en el día de su poder. Si este solo caso en que Cristo resucitó a un muerto reciente, aumentó tanto su fama, ¡qué será su gloria cuando todos los que están en los sepulcros oigan su voz y salgan; los que hicieron bien a resurrección de la vida, y los que hicieron mal, a resurrección de condenación!</p>
<br/>
<p class="text-justify">Vv. 27-31.En esa época los judíos esperaban que apareciera el Mesías; estos ciegos supieron y proclamaron en las calles de Capernaum que había venido, y que era Jesús. Los que, por la providencia de Dios, han perdido la vista física, por gracia de Dios, pueden tener plenamente iluminados los ojos de su entendimiento. Sean las que sean nuestras necesidades y cargas, no necesitamos más provisión y apoyo que participar en la misericordia de nuestro Señor Jesús. En Cristo hay suficiente para todos.
Ellos lo siguieron gritando en voz alta. Iba a probar su fe, y nos enseñaría a orar siempre y no desmayar, aunque la respuesta no llegue de inmediato. Ellos siguieron a Cristo y lo siguieron clamando, pero la gran pregunta es: ¿Crees tú? La naturaleza puede hacernos fervorosos, pero es sólo la gracia la que puede obrar la fe.
Cristo tocó sus ojos. Él da vista a las almas ciegas por el poder de su gracia que va unida a su palabra, e imparte la cura sobre la fe de ellos. Los que apelan a Jesucristo serán tratados, no conforme a sus fantasías ni a su profesión, sino conforme a su fe.
A veces Cristo ocultaba sus milagros porque no quería dar pie al engaño que prevalecía entre los judíos de que su Mesías sería un príncipe temporal, y así, dar ocasión a que el pueblo intentara tumultos y sediciones.</p>
<br/>
<p class="text-justify">Vv. 32-34.De ambos, mejor es un demonio mudo que uno que blasfeme. Las curas de Cristo van a la raíz, y eliminan el efecto quitando la causa; abren los labios rompiendo el poder de Satanás en el alma.
Nada puede convencer a quienes están bajo el poder del orgullo. Creerán cualquier cosa, por falsa o absurda que sea, antes que las Sagradas Escrituras; así, muestran la enemistad de sus corazones contra el santo Dios.</p>
<br/>
<p class="text-justify">Vv. 35-38.Jesús visitó no sólo las ciudades grandes y ricas, sino las aldeas pobres y oscuras, y allí predicó, y sanó. Las almas de los más viles del mundo son tan preciosas para Cristo, y deben serlo para nosotros, como las almas de los que más figuren. Había sacerdotes, levitas, y escribas en toda la tierra; pero eran pastores de ídolos, Zacarías xi, 17; por tanto, Cristo tuvo compasión del pueblo como ovejas desamparadas y dispersas, como hombres que perecen por falta de conocimiento. A la fecha hay multitudes enormes que son como ovejas sin pastor, y debemos tener compasión y hacer todo lo que podamos para ayudarles. Las multitudes deseosas de instrucción espiritual formaban una cosecha abundante que necesitaba muchos obreros activos; pero pocos merecían ese carácter. Cristo es el Señor de la mies. Oremos que muchos sean levantados y enviados a trabajar para llevar almas a Cristo. Es señal de que Dios está por conceder alguna misericordia especial a un pueblo cuando los invita a orar por ello. Las misiones encomendadas a los obreros como respuesta a la oración, son las que más probablemente tengan éxito.</p>
<br/>




</div>
