<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 26</h2>
<p class="text-justify">Vv. 1-5.Nuestro Señor habló frecuentemente de Sus sufrimientos como distantes; ahora habla de ellos como inmediatos. Al mismo tiempo, el concilio judío consultaba cómo podían matarlo en forma secreta. Pero agradó a Dios derrotar la intención de ellos. Jesús, el verdadero cordero pascual, iba a ser sacrificado por nosotros en ese mismo momento, y su muerte y resurrección serían públicas.</p>
<br/>
<p class="text-justify">Vv. 6-13.El ungüento derramado sobre la cabeza de Cristo era una señal del mayor respeto. Donde hay amor verdadero por Jesucristo en el corazón, nada se considerará como demasiado bueno para dárselo a Él. Mientras más se ponga reparos a los siervos de Cristo y a sus servicios, más manifiesta Él su aceptación. Este acto de fe y amor fue tan notable que sería registrado como monumento a la fe y amor de María para todas las eras futuras, y en todos los lugares donde se predicara el evangelio. Esta profecía se cumple.</p>
<br/>
<p class="text-justify">Vv. 14-16.No hay sino doce apóstoles llamados, y uno de ellos era como un diablo; con toda seguridad nunca debemos esperar que ninguna sociedad sea absolutamente pura a este lado del cielo. Mientras más grandiosa sea la profesión de la religión que hagan los hombres, más grande será la oportunidad que tengan de hacer el mal si sus corazones no están bien con Dios. Obsérvese que el propio discípulo de Cristo, que conocía tan bien su doctrina y estilo de vida, fue falso con Él, y no lo pudo acusar de ningún delito, aunque hubiera servido para justificar su traición. ¿Qué quería Judas? ¿No era bien recibido donde quiera fuera su Maestro? ¿No le iba como le iba a Cristo? No es la falta de sino el amor al dinero lo que es la raíz de todo mal. Después que hizo esa malvada transacción, Judas tuvo tiempo para arrepentirse y revocarla; pero cuando la conciencia se ha endurecido con actos menores de deshonestidad, los hombres hacen sin dudar lo que es más vergonzoso.</p>
<br/>
<p class="text-justify">Vv. 17-25.Obsérvese que el lugar para comer la pascua fue señalado por Cristo a los discípulos. Él conoce a la gente que, escondida, favorece su causa y visita por gracia a todos los que están dispuestos a recibirlo. Los discípulos hicieron como indicó Jesús. Los que desean tener la presencia de Cristo en la pascua del evangelio, deben hacer lo que Él dice.
Corresponde que los discípulos de Cristo sean siempre celosos de sí mismos, especialmente en los tiempos de prueba. No sabemos con cuánta fuerza podemos ser tentados, ni cuánto puede Dios dejarnos librados a nosotros mismos; por tanto, tenemos razón para no ser altivos, sino para temer. El examen que escudriña el corazón y la oración ferviente son especialmente apropiadas antes de la cena del Señor, para que, puesto que Cristo, nuestra pascua, es ahora sacrificado por nosotros, podemos guardar esta fiesta, y renovar nuestro arrepentimiento, nuestra fe en su sangre y rendirnos a su servicio.</p>
<br/>
<p class="text-justify">Vv. 26-30.La ordenanza de la cena del Señor es para nosotros la cena de la pascua, por la cual conmemoramos una liberación mucho mayor que la de Israel desde Egipto. “Tomad, comed”; acepta a Cristo como te es ofrecido; recibe la expiación, apruébala, sométete a su gracia y mando. La carne que sólo se mira, por muy bien presentada que esté el plato, no alimenta; debe comerse: así debe pasar con la doctrina de Cristo. “Esto es mi cuerpo”esto es, que significa y representa espiritualmente su cuerpo. Participamos del sol no teniendo al sol puesto en nuestras manos, sino sus rayos lanzados para abajo sobre nosotros; así, participamos de Cristo al participar de su gracia y de los frutos benditos del partimiento de su cuerpo. La sangre de Cristo está significada y representada por el vino. Él dio gracias, para enseñarnos a mirar a Dios en cada aspecto de la ordenanza. Esta copa la dio a los discípulos con el mandamiento de: “Bebed de ella todos”. El perdón de pecado es la gran bendición que se confiere en la cena del Señor a todos los creyentes verdaderos; es el fundamento de todas las demás bendiciones. -Él aprovecha la comunión para asegurarles la feliz reunión de nuevo al final: “Hasta aquel día en que lo beba de nuevo con vosotros”, lo que puede entenderse como las delicias y las glorias del estado futuro, del cual participarán los santos con el Señor Jesús. Ese será el reino de su Padre; el vino del consuelo será siempre nuevo allí. Mientras miramos las señales externas del cuerpo de Cristo partido y su sangre derramada por la remisión de nuestros pecados, recordemos que la fiesta le costó tanto que tuvo que dar, literalmente, su carne como comida y su sangre como nuestra bebida.</p>
<br/>
<p class="text-justify">Vv. 31-35.La confianza impropia en sí mismo, como la de Pedro, es el primer paso hacia una caída. Todos somos proclives a ser demasiado confiados, pero caen más pronto y más mal los que más confiados están en sí mismos. Los que se piensan más seguros son los que están menos a salvo. Satanás está activo para descarriar a los tales; ellos son los que están menos en guardia: Dios los deja a sí mismos para humillarlos.</p>
<br/>
<p class="text-justify">Vv. 36-46.El que hizo expiación por los pecados de la humanidad, se sometió en el huerto del sufrimiento a la voluntad de Dios, contra la cual se había rebelado el hombre en un huerto de placeres. Cristo llevó consigo, a esa parte del huerto donde sufrió su agonía, sólo a los que habían presenciado su gloria en su transfiguración. Están mejor preparados para sufrir con Cristo los que, por fe, han contemplado su gloria. Las palabras usadas denotan el rechazo, asombro, angustia y horror mental más completos; el estado de uno rodeado de penas, abrumado con miserias, y casi consumido por el terror y el desánimo.
Ahora comenzó a entristecerse y nunca dejó de estar así hasta que dijo: Consumado es. Él oró que, si era posible, la copa pasara de Él. Pero también mostró su perfecta voluntad de llevar la carga de sus sufrimientos; estaba dispuesto a someterse a todo por nuestra redención y salvación. Conforme a este ejemplo de Cristo, debemos beber de la copa más amarga que Dios ponga en nuestras manos; aunque nuestra naturaleza se oponga, debe someterse. Debemos cuidar más de hacer que nuestras tribulaciones sean santificadas, y nuestros corazones se satisfagan sometidos a ellas, que lograr que los problemas sean eliminados.
Bueno es para nosotros que nuestra salvación esté en la mano de Uno que no se adormece ni se duerme. Todos somos tentados, pero debemos tener gran temor de meternos en tentación. Para estar a salvo de esto debemos velar y orar y mirar continuamente al Señor, para que nos sostenga y estemos a salvo.
Indudablemente nuestro Señor tenía una visión completa y clara de los sufrimientos que aún tenía que soportar y, aun así, habló con la mayor calma hasta este momento. Cristo es el garante que decidió ser responsable de rendir las cuentas por nuestros pecados. En consecuencia, fue hecho pecado por nosotros, y sufrió por nuestros pecados, el Justo por el injusto; y la Escritura atribuye sus sufrimientos más intensos a la mano de Dios. Él tenía pleno conocimiento del infinito mal del pecado y de la inmensa magnitud de la culpa por la cual iba a hacer expiación; con visiones horrorosas de la justicia y santidad divina, y del castigo merecido por los pecados de los hombres, tales que ninguna lengua puede expresar ni mente concebir. Al mismo tiempo, Cristo sufrió siendo tentado; probablemente Satanás sugirió horribles pensamientos todos tendientes a sacar una conclusión sombría y espantosa: estos deben de haber sido los más difíciles de soportar por su perfecta santidad. ¿Y la carga del pecado imputado pesó tanto en el alma de Aquel, de quien se dijo: Sustenta todas las cosas con la palabra de su poder? ¡En qué miseria entonces deben hundirse aquellos cuyos pecados pesan sobre sus propias cabezas! ¿Cómo escaparán los que descuidan una salvación tan grande?</p>
<br/>
<p class="text-justify">Vv. 47-56.No hay enemigos que sean tan aborrecibles como los discípulos profesos que traicionan a Cristo con un beso.
Dios no necesita nuestros servicios, mucho menos nuestros pecados, para realizar sus propósitos. Aunque Cristo fue crucificado por debilidad, fue debilidad voluntaria; se sometió a la muerte. Si no hubiera estado dispuestos a sufrir, ellos no lo hubiesen vencido.
Fue un gran pecado de quienes dejaron todo para seguir a Jesús dejarlo ahora por lo que no sabían. ¡Qué necedad huir de Él, al cual conocían y reconocían como el Manantial de la vida, por miedo a la muerte!</p>
<br/>
<p class="text-justify">Vv. 57-68.Jesús fue llevado apresuradamente a Jerusalén. Luce mal, y presagia lo peor, que los dispuestos a ser discípulos de Cristo no estén dispuestos a ser conocidos como tales. Aquí empieza la negación de Pedro: porque seguir a Cristo desde lejos es empezar a retirarse de Él. Nos concierne más prepararnos para el fin, cualquiera sea, que preguntar curiosos cuál será el fin. El hecho es de Dios, pero el deber es nuestro.
Ahora fueron cumplidas las Escrituras que dicen: Se han levantado contra mí testigos falsos. Cristo fue acusado, para que nosotros no fuéramos condenados; y, si en cualquier momento nosotros sufrimos así, recordemos que no podemos tener la expectativa de que nos vaya mejor que a nuestro Maestro. Cuando Cristo fue hecho pecado por nosotros, se quedó callado y dejó que su sangre hablara. Hasta entonces rara vez había confesado Jesús, expresamente, ser el Cristo, el Hijo de Dios; el tenor de su doctrina lo dice y sus milagros lo probaban, pero, por ahora omitiría hacer una confesión directa. Hubiera parecido que renunciaba a sus sufrimientos. Así confesó Él, como ejemplo y estímulo para que sus seguidores, lo confiesen ante los hombres, cualquiera sea el peligro que corran. El desdén, la burla cruel y el aborrecimiento son la porción segura del discípulo, como lo fueron del Maestro, de parte de los que deseaban golpear y reírse con burla del Señor de la gloria. En el capítulo cincuenta de Isaías se predicen exactamente estas cosas. Confesemos el nombre de Cristo y soportemos el reproche, y Él nos confesará delante del trono de su Padre.</p>
<br/>
<p class="text-justify">Vv. 69-75.El pecado de Pedro es relatado con veracidad, porque las Escrituras tratan con fidelidad. Las malas compañías llevan a pecar: quienes se meten innecesariamente en eso pueden hacerse la expectativa de ser tentados y atrapados, como Pedro. Apenas pueden desprenderse de esas compañías sin culpa o dolor, o ambas. Gran falta es tener vergüenza de Cristo y negar que lo conocemos cuando somos llamados a reconocerlo y, en efecto, eso es negarlo. El pecado de Pedro fue con agravantes; pero él cayo en pecado por sorpresa, no en forma intencional, como Judas. La conciencia debiera ser para nosotros como el canto del gallo para hacernos recordar los pecados que habíamos olvidado.
Pedro fue así dejado caer para abatir su confianza en sí mismo y volverlo más modesto, humilde, compasivo y útil para los demás. El hecho ha enseñado, desde entonces, muchas cosas a los creyentes y si los infieles, los fariseos y los hipócritas tropiezan en esto o abusan de ello, es a su propio riesgo. Apenas sabemos cómo actuar en situaciones muy difíciles, si fuésemos dejados a nosotros mismos. Por tanto, que el que se cree firme, tenga cuidado que no caiga; desconfiemos todos de nuestros corazones y confiemos totalmente en el Señor.
Pedro lloró amargamente. La pena por el pecado no debe ser ligera sino grande y profunda. Pedro, que lloró tan amargamente por negar a Cristo, nunca lo volvió a negar, sino que lo confesó a menudo frente al peligro. El arrepentimiento verdadero de cualquier pecado se demostrará por la gracia y el deber contrario; esa es señal de nuestro pesar no sólo amargo, sino sincero.</p>
<br/>




</div>
