<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 3</h2>
<p class="text-justify">Vv. 1-6.Después de Malaquías no hubo profeta hasta Juan el Bautista. Apareció primero en el desierto de Judea. No era un desierto deshabitado, sino parte del país, no densamente poblado ni muy aislado. Ningún lugar es tan remoto como para excluirnos de las visitas de la gracia divina.
Predicaba la doctrina del arrepentimiento: “Arrepentíos”. La palabra aquí usada implica un cambio total de modo de pensar: un cambio de juicio, de la disposición, y de los afectos, una inclinación diferente y mejor del alma. Consideren sus caminos, cambien sus sus pensamientos: han pensado mal; piensen de nuevo y piensen bien. Los penitentes verdaderos tienen pensamientos de Dios y de Cristo, del pecado y de la santidad, de este mundo y del otro, diferentes de los que que tuvieron. El cambio del pensamiento produce un cambio de camino. Este es el arrepentimiento del evangelio, el cual se produce al ver a Cristo, al captar su amor, y de la esperanza de perdón por medio de Él. Es un gran estímulo para que nosotros nos arrepintamos; arrepentíos, porque vuestros pecados serán perdonados si os arrepentís. Volveos a Dios por el camino del deber, y Él, por medio de Cristo, se volverá a vosotros por el camino de la misericordia. Ahora es tan necesario que nos arrepintamos y nos humillemos para preparar el camino del Señor, como lo era entonces. Hay mucho que hacer para abrir camino para Cristo en un alma, y nada más necesario que el descubrimiento del pecado, y la convicción de que no podemos ser salvados por nuestra propia justicia. El camino del pecado y de Satanás es un camino retorcido, pero para preparar un camino para Cristo es necesario enderezar las sendas, Hebreos xii, 13.
Quienes tienen por actividad llamar a los demás a lamentar el pecado y a mortificarlo, deben llevar una vida seria, una vida de abnegación y desprecio del mundo. Dando a los demás este ejemplo, Juan preparó el camino para Cristo.
Muchos fueron al bautismo de Juan, pero pocos mantuvieron la profesión que hicieron. Puede que haya muchos oyentes interesados, pero pocos creyentes verdaderos. La curiosidad y el amor de la novedad y variedad pueden llevar a muchos a oír una buena predicación, siendo afectados momentaneamente, a muchos que nunca se someten a su autoridad. Los que recibieron la doctrina de Juan, testificaron su arrepentimiento confesando sus pecados. Están listos para recibir a Jesucristo como su justicia sólo los que son llevados con tristeza y vergüenza a reconocer su culpa. Los beneficios del reino de los cielos, ahora ya muy cerca, les fueron sellados por el bautismo. Juan los purificó con agua, en señal de que Dios los limpiaría de todas sus iniquidades, dando a entender con esto que, por naturaleza y costumbre, todos estaban contaminados y no podían ser recibidos en el pueblo de Dios a menos que fueran lavados de sus pecados en el manantial que Cristo iba a abrir, Zacarías xiii, 1.</p>
<br/>
<p class="text-justify">Vv. 7-12.Dar aplicación para las almas de los oyentes es la vida de la predicación; así fue la de Juan. Los fariseos ponían el énfasis principal en observancias externas, descuidando los asuntos de más peso de la ley moral, y el significado espiritual de sus ceremonias legales. Otros eran hipócritas detestables que hacían con sus pretensiones de santidad un manto de la iniquidad. Los saduceos estaban en el extremo opuesto, negando la existencia de los espíritus y el estado futuro. Ellos eran los infieles burladores de esa época y ese país.
Hay una gran ira venidera. Gran interés de cada uno es huir de la ira. Dios, que no se deleita en nuestra ruina, nos ha advertido; advierte por la palabra escrita, por los ministros, por la conciencia. No son dignos del nombre de penitentes, ni de sus privilegios, los que dicen que lamentan sus pecados, pero siguen en ellos. Conviene a los penitentes ser humildes y bajos a sus propios ojos, agradecer la mínima misericordia, ser pacientes en las grandes aflicciones, estar alerta contra toda apariencia de mal, abundar en todo deber, y ser caritativos al juzgar al prójimo.
Aquí hay una palabra de cautela, no confiar en los privilegios externos. Hay muchos cuyos corazones carnales son dados a seguir lo que ellos mismos dicen dentro de sí y dejan de lado el poder de la palabra de Dios que convence de pecado y su autoridad. Hay multitudes que no llegan al cielo por descansar en los honores y las simples ventajas de ser miembros de una iglesia externa.
He aquí una palabra de terror para el negligente y confiado. Nuestros corazones corruptos no pueden dar buen fruto a menos que el Espíritu regenerador de Cristo implante la buena palabra de Dios en ellos. Sin embargo, todo árbol, con muchos dones y honores, por verde que parezca en su profesión y desempeño externo, si no da buen fruto, frutos dignos de arrepentimiento, es cortado y echado al fuego de la ira de Dios, el lugar más apto para los árboles estériles; ¿para qué otra cosa sirven? Si no dan fruto, son buenos como combustible.
Juan muestra el propósito y la intención de la aparición de Cristo, la cual ellos ahora esperaban con prontitud. No hay formas externas que puedan limpiarnos. Ninguna ordenanza, sea quien sea el que la administre, o no importa la modalidad, puede suplir la necesidad del bautismo del Espíritu Santo y de fuego. Sólo el poder purificador y limpiador del Espíritu Santo puede producir la pureza de corazón, y los santos afectos que acompañan a la salvación. Cristo es quien bautiza con el Espíritu Santo. Esto hizo con los extraordinarios dones del Espíritu enviados a los apóstoles, Hechos ii, 4. Esto hace con las gracias y consolaciones del Espíritu, dados a quienes le piden, Lucas xi, 13; Juan vii, 38, 39; ver Hechos xi, 16.
Obsérvese aquí, la iglesia externa en la era de Cristo, Isaías xxi, 10. Los creyentes verdaderos son el trigo, sustanciosos, útiles y valiosos; los hipócritas son paja, livianos y vacíos, inútiles, sin valor, llevados por cualquier viento; están mezclados, bueno y malo, en la misma comunión externa. Viene el día en que serán separados la paja y el trigo. El juicio final será el día que haga la diferencia, cuando los santos y los pecadores sean apartados para siempre. En el cielo los santos son reunidos, y no más esparcidos; están a salvo y ya no más expuestos; separados del prójimo corrompido por fuera y con afectos corruptos por dentro, y no hay paja entre ellos. El infierno es el fuego inextinguible que ciertamente será la porción y el castigo de los hipócritas e incrédulos. Aquí la vida y la muerte, el bien y el mal, son puestos ante nosotros: según somos ahora en el campo, seremos entonces en la era.</p>
<br/>
<p class="text-justify">Vv. 13-17.Las condescendencias de la gracia de Cristo son tan asombrosas que aun los creyentes más firmes apenas pueden creerlas al principio; tan profundas y misteriosas que aun quienes conocen bien su mente, están prontos a ofrecer objeciones contra la voluntad de Cristo. Quienes tienen mucho del Espíritu de Dios, mientras están aquí ven que necesitan pedir más de Cristo. No niega que Juan tenía necesidad de ser bautizado por Él, pero declara que debe ser bautizado por Juan. Cristo está ahora en estado de humillación. Nuestro Señor Jesús consideró conveniente, para cumplir toda justicia, apropiarse de cada institución divina, y mostrar su disposición para cumplir con todos los preceptos justos de Dios.
En Cristo y por medio de Él, los cielos están abiertos para los hijos de los hombres. Este descenso del Espíritu sobre Cristo demuestra que estaba dotado sin medida con sus poderes sagradas. El fruto del Espíritu Santo es amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza.
En el bautismo de Cristo hubo una manifestación de las tres Personas de la Santa Trinidad. El Padre confirmando al Hijo como Mediador; el Hijo que solemnemente se encarga de la obra; el Espíritu Santo que desciende sobre Él para ser comunicado al pueblo por su intermedio. En Él son aceptables nuestros sacrificios espirituales, porque Él es el altar que santifica todo don, 1 Pedro ii, 5. Fuera de Cristo Dios es fuego consumidor; en Cristo, un Padre reconciliado. Este es el resumen del evangelio, el cual debemos abrazar jubilosamente por fe.</p>
<br/>




</div>
