<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 28</h2>
<p class="text-justify">Vv. 1-8.Cristo se levantó al tercer día después de su muerte; ese era el tiempo del cual había hablado frecuentemente. El primer día de la primera semana Dios mandó que de las tinieblas brillara la luz. En este día el que es la Luz del mundo, salió resplandeciendo desde las tinieblas de la tumba; y este día es, desde entonces, mencionado a menudo en el Nuevo Testamento como el día en que los cristianos celebraron religiosamente asambleas solemnes para honrar a Cristo.
Nuestro Señor Jesús podría haber quitado la piedra por su poder, pero optó por hacerlo por medio de un ángel.
La resurrección de Cristo es el gozo de sus amigos y el terror y la confusión de sus enemigos. El ángel exhorta a las mujeres contra sus temores. Los pecadores de Sion teman. No temáis porque su resurrección será vuestro consuelo. Nuestra comunión con Él debe ser espiritual, por fe en su palabra. Cuando estemos listos para hacer de este mundo nuestro hogar, y a decir, es bueno estar aquí, recordemos entonces que nuestro Señor Jesús no está aquí, Ha resucitado; por tanto, que nuestros corazones se eleven, y busquen las cosas de arriba.
Ha resucitado, como dijo. Nunca pensemos que es raro lo que la palabra de Cristo nos ha dicho que esperemos; sean los sufrimientos de este tiempo presente o la gloria que va a ser revelada. Puede tener buen efecto en nosotros mirar por fe el lugar donde yace el Señor.
Id pronto. Fue bueno estar ahí, pero los siervos de Dios tienen asignada otra obra. La utilidad pública tiene prioridad sobre el placer de la comunión secreta con Dios. Decid a los discípulos que ellos pueden ser consolados en sus tristezas.
Cristo sabe donde habitan sus discípulos y los visitará. Él se manifestará, por gracia, aun a aquellos que están lejos de la abundancia de los medios de gracia.
El temor y el gozo unidos aceleraron su paso. Los discípulos de Cristo deben ser estimulados a darse a conocer mutuamente sus experiencias de comunión con su Señor, y deben contar a los demás lo que Dios ha hecho por sus almas.</p>
<br/>
<p class="text-justify">Vv. 9, 10.Las visitas de la gracia de Dios suelen hallarnos en el camino del deber; y más será dado a los que usan lo que tienen para provecho del prójimo. Esta entrevista con Cristo era inesperada, pero Cristo estaba cerca de ellos y aún está cerca de nosotros en la palabra. El saludo habla de la buena voluntad de Cristo para con el hombre, aun desde que entró a su estado de exaltación. Es la voluntad de Cristo que su pueblo sea un pueblo alegre y jubiloso, y su resurrección da abundante material para el gozo.
No temáis. Cristo resucitó de entre los muertos para acallar los temores de su pueblo y hay suficiente en ello para acallarlos. Los discípulos lo habían abandonado, vergonzosamente en sus sufrimientos, pero para mostrar que puede perdonar, y para enseñarnos a hacerlo así, los llama hermanos. A pesar de su majestad y pureza, y de nuestra bajeza e indignidad, Él aun condesciende a llamar sus hermanos a los creyentes.</p>
<br/>
<p class="text-justify">Vv. 11-15.¡Qué maldad es la que los hombres no cometerán por amor al dinero! Aquí se dio mucho dinero a los soldados por decir a sabiendas una mentira, pero muchos refunfuñan porque es poco el dinero por decir lo que saben que es la verdad. Nunca dejemos morir una buena causa cuando vemos a los malos tan generosamente sostenidos. Los sacerdotes se dedicaron a protegerse de la espada de Pilato, pero no protegieron a los soldados de la espada de la justicia de Dios, que pende sobre las cabezas de quienes aman y hacen una mentira. Prometen más de lo que pueden hacer los que tratan de sacar inerme a un hombre que comete pecado voluntario.
Pero esta falsedad se refuta a sí misma. Si todos los soldados hubieran estado dormidos, no hubieran podido saber lo que pasó. Si alguno hubiera estado despierto, hubiera despertado a los otros e impedido el robo; si hubieran estado dormidos, por cierto que nunca se hubieran atrevido a confesarlo; porque los gobernantes judíos hubieran sido los primeros en pedir su castigo. De nuevo, si hubiera habido algo de verdad en el informe, los dirigentes hubieran juzgado con severidad a los apóstoles por eso. El todo muestra que la historia era falsa por completo. No debemos culpar de tales cosas a la debilidad del entendimiento, sino a la maldad del corazón. Dios los dejó delatar su propio curso.
El gran argumento para probar que Cristo es el Hijo de Dios es su resurrección; y nadie podía dar pruebas más convincentes de la verdad que aquella de los soldados; pero ellos aceptaron el soborno para impedir que otros creyeran. La evidencia más clara no afectará a los hombres, sin la obra del Espíritu Santo.</p>
<br/>
<p class="text-justify">Vv. 16-20.Este evangelista pasa por alto otras apariciones de Cristo registradas por Lucas y Juan, y se apresura a relatar la más solemne; una establecida desde antes de su muerte, y después de su resurrección. Todos los que miran al Señor Jesús con los ojos de la fe, lo adorarán. Pero la fe del sincero puede ser muy débil e inestable. Pero Cristo dio pruebas tan convincentes de su resurrección, para hacer que su fe triunfara sobre las dudas. Ahora encarga solemnemente a los apóstoles y a sus ministros que vayan a todas las naciones. La salvación que iban a predicar es salvación común; quien la quiera, que venga y tome el beneficio; todos son bienvenidos a Cristo Jesús.
El cristianismo es la religión de un pecador que pide salvación de la merecida ira y del pecado; recurre a la misericordia del Padre por medio de la expiación hecha por el Hijo encarnado y por la santificación del Espíritu Santo, y se entrega a ser adorador y siervo de Dios, como Padre, Hijo y Espíritu Santo, tres Personas, pero un solo Dios, en todas sus ordenanzas y mandamientos.
El bautismo es una señal externa del lavamiento interno o santificación del Espíritu, que sella y demuestra la justificación del creyente. Examinémonos si realmente poseemos la gracia espiritual interna de la muerte al pecado y el nuevo nacimiento a la justicia, por los cuales los que eran hijos de ira llegan a ser los hijos de Dios.
Los creyentes tendrán siempre la presencia constante de su Señor; todos los días, cada día. No hay día, ni hora del día en que nuestro Señor Jesús no esté presente en sus iglesias y con sus ministros; si lo hubiera, en ese día, en esa hora, ellos serían deshechos. El Dios de Israel, el Salvador, es a veces un Dios que se esconde, pero nunca es un Dios lejano. A esas preciosas palabras se añade el Amén. Aun así, Señor Jesús, sé con nosotros y con todo tu pueblo; haz que tu rostro brille sobre nosotros, que tu camino sea conocido en la tierra, tu salud salvadora entre todas las naciones.</p>
<br/>




</div>
