<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 13</h2>
<p class="text-justify">Vv. 1-23.Jesús se embarcó en una barca para ser menos presionado y para que la gente escuchara mejor. Con esto nos enseña en las circunstancias externas de la adoración a no desear lo que es majestuoso, sino hacer lo mejor de las facilidades que Dios nos asigna en su providencia. Cristo enseñaba con parábolas. Por medio de ellas simplificaba y hacía más fáciles las cosas de Dios para los dispuestos a ser enseñados, y más difíciles y oscuras para los dispuestos a ser ignorantes.
La parábola del sembrador es clara. La semilla sembrada es la palabra de Dios. El sembrador es nuestro Señor Jesucristo, por sí o por sus ministros. Predicar a una multitud es sembrar el grano; no sabemos dónde brotará. Una clase de terreno, aunque nos demos mucho trabajo, no da fruto adecuado mientras la buena tierra da fruto con abundancia. Así ocurre en los corazones de los hombres, cuyos diferentes caracteres están aquí descritos como cuatro clases de terreno.
Los oyentes negligentes y frívolos son presas fáciles para Satanás que, como el gran homicida de las almas, es el gran ladrón de sermones, y con seguridad estará presto para robarnos la palabra si no tenemos el cuidado de obedecerla.
Los hipócritas, como el terreno pedregoso, suelen tener el comienzo de los cristianos verdaderos en su muestra de profesión de fe. Muchos de los que se alegran de oír un buen sermón, son los que no se benefician. Se les habla de la salvación gratuita, de los privilegios de los creyentes, y la felicidad del cielo; y, sin cambio de corazón, sin convicción permanente de su propia depravación, de su necesidad del Salvador o de la excelencia de la santidad, pronto profesan una seguridad sin fundamentos. Pero cuando una prueba pesada los amenaza o pueden tener una ventaja pecaminosa, se rinden u ocultan su profesión o se vuelven a un sistema más fácil.
Los afanes del mundo son apropiadamente comparados con las espinas, porque vinieron con el pecado y son fruto de la maldición; son buenos en su lugar para llenar un vacío, pero debe estar bien armado el hombre que tenga mucho que ver con ellos; enredan, afligen, arañan y su fin es ser quemados, Hebreos vi, 8. Los afanes del mundo son grandes obstáculos para tener provecho de la palabra de Dios. Lo engañoso de las riquezas obra el mal; no se puede decir que nos engañamos a menos que depositemos nuestra confianza en ellas, entonces ahogamos la buena semilla.
Lo que distinguió al buen terreno fue la fructificación. Por esto se distinguen los cristianos verdaderos de los hipócritas. Cristo no dice que la buena tierra no tenga piedras y espinas, sino que nada puede impedir que dé fruto. Todos no son iguales; debemos apuntar más alto para dar más fruto. El sentido del oído no puede ser mejor usado que para oír la palabra de Dios; y mirémonos a nosotros para que sepamos que clase de oyente es.</p>
<br/>
<p class="text-justify">Vv. 24-30. 36-43.Esta parábola representa el estado presente y el futuro de la Iglesia del evangelio; el cuidado de Cristo por ella, la enemistad del diablo contra ella; la mezcla de buenos y malos que tiene en este mundo, y la separación entre ellos en el otro mundo. Tan proclive a pecar es el hombre caído que si el enemigo siembra, puede seguir su camino, y la cizaña brotará y hará daño; mientras cuando se siembra buena semilla, debe cuidarse, regarse y protegerse. Los siervos se quejan a su amo: Señor ¿no sembraste buena semilla en tu campo? Sin duda que sí; lo que sea que esté mal en la iglesia tengamos la seguridad que no es de Cristo. Aunque los transgresores groseros, y otros que se oponen abiertamente al evangelio, debieran ser separados de la sociedad de los fieles, sin embargo, no hay, destreza humana que pueda efectuar una separación precisa. Los que se oponen no deben ser sacados sino instruidos, y con mansedumbre. Y aunque los buenos y los malos estén juntos en este mundo, sin embargo, en el día grande del juicio serán separados; entonces serán claramente conocidos el justo y el impío; a veces aquí cuesta mucho distinguir entre ellos. No hagamos iniquidad si conocemos el temor del Señor.
En la muerte los creyentes brillarán por sí mismos; en el día grande, brillarán ante todo el mundo. Brillarán por reflejo, con luz prestada de la Fuente de luz. La santificación de ellos será perfeccionada y su justificación, publicada. Que seamos hallados en ese feliz número.
Vv. 31-35. El alcance de la parábola de la semilla de mostaza es mostrar que los comienzos del evangelio es pequeño pero su final será grande; de este modo será ejecutada la obra de gracia en el corazón, el reino de Dios dentro de nosotros. En el alma donde verdaderamente está la gracia, crecerá en realidad, aunque, quizá al comienzo, no sea discernida, pero al final tendrá gran fuerza y utilidad.
La predicación del evangelio obra como levadura en el corazón de los que lo reciben. La levadura obra ciertamente, así lo hace la palabra, pero gradualmente. Obra silenciosamente y sin ser vista, pero sin fallar. Así fue en el mundo . Los apóstoles, predicando el evangelio, escondieron un puñado de levadura en la gran masa de la humanidad. Fue hecho poderoso por el Espíritu de Jehová de los ejércitos, que obra y nada puede impedirlo. En el corazón es así. Cuando el evangelio llega al alma, obra un cambio radical; se expande a todos los poderes y facultades del alma, y altera la propiedad aun de los miembros del cuerpo, Romanos vi, 13. De estas parábolas se nos enseña esperar un progreso gradual; por tanto, preguntemos, ¿estamos creciendo en gracia y en los santos principios y costumbres?</p>
<br/>
<p class="text-justify">Vv. 44-52.He aquí cuatro parábolas: -1. La del tesoro escondido en el campo. Muchos toman a la ligera el evangelio porque miran sólo la superficie del campo. Pero todos los que escudriñan las Escrituras, para hallar en ellas a Cristo y la vida eterna, Juan v, 39, descubrirán tal tesoro que a este campo lo hace indeciblemente valioso; se aprpopian de él a cualquier costo. Aunque nada pueda darse como precio por la salvación, sin embargo, mucho debe darse por amor a ella.
2. Todos los hijos de los hombres están ocupados; uno será rico, otro será honorable, aun otro será docto; pero la mayoría está engañada y toman las falsificaciones por perlas legítimas. Jesucristo es la Perla de gran precio; teniéndolo a Él tenemos suficiente para hacernos dichosos aquí y para siempre. El hombre puede comprar oro muy caro, pero no esta Perla de gran precio. Cuando el pecador convicto ve a Cristo como el Salvador de gracia, todo lo demás pierde valor para sus pensamientos.
3. El mundo es un mar ancho, y en su estado natural, los hombres son como los peces. Predicar el evangelio es echar una red en este mar para pescar algo para gloria de Quien tiene la soberanía sobre este mar. Los hipócritas y los cristianos verdaderos serán separados: desgraciada es la condición de quienes, entonces, serán echados fuera.
4. El fiel y diestro ministro del evangelio es un escriba bien versado en las cosas del evangelio y capaz de enseñarlas. Cristo lo compara con un buen dueño de casa, que trae los frutos de la cosecha del año anterior y lo recogido este año, abundante y variado, para tratar a sus amigos. Todas las experiencias antiguas y las observaciones nuevas tienen su utilidad. Nuestro lugar está a los pies de Cristo, y debemos aprender diariamente de nuevo las viejas lecciones y, también, las nuevas.</p>
<br/>
<p class="text-justify">Vv. 53-58.Cristo repite su ofrecimiento a los que lo han rechazado. Ellos le reprochan: ¿No es éste el hijo del carpintero? Sí, es cierto que tenía la fama de serlo; y no es desgracia ser el hijo de un comerciante honesto; debieron respetarle más porque era uno de ellos mismos, pero, por eso lo despreciaron.
No hizo muchas obras poderosas ahí debido a la incredulidad de ellos. La incredulidad es el gran estorbo para los favores de Cristo. Mantengámonos fieles a Él como el Salvador que hizo nuestra paz con Dios.</p>
<br/>




</div>
