<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Miqueas 7</h2>
<p class="text-justify">Vv. 1-7.El profeta se queja de vivir en un pueblo que se madura veloz hacia su ruina, en la cual sufrirán muchas personas buenas. Los hombres no tenían consuelo, ni satisfacción en sus propias familias ni en sus parientes más cercanos. El desprecio y la violación de los deberes domésticos son un síntoma triste de la corrupción universal. Los que no cumplen sus deberes con sus padres probablemente nunca lleguen a nada bueno.
El profeta no vio seguridad ni consuelo, sino en mirar a Jehová y esperar en Dios su salvación. Cuando estamos sometidos a pruebas debemos mirar continuamente a nuestro Redentor divino para tener fuerza y gracia para confiar en Él y ser ejemplo para los que nos rodean.</p>
<br/>
<p class="text-justify">Vv. 8-13.Los penitentes verdaderos por el pecado, verán mucha razón para ser pacientes en la aflicción. Cuando nos quejamos al Señor de lo malo que son los tiempos, debemos quejarnos contra nosotros mismos por lo malo de nuestros corazones. Debemos depender de Dios para que obre liberación para nosotros en el momento debido. No debemos tan sólo mirar a Él sino buscarlo a Él. En la mayor de nuestras angustias no veremos razón para perder la esperanza de la salvación si miramos al Señor por fe como Dios de nuestra salvación.
Aunque los enemigos triunfen e insulten, serán silenciados y avergonzados. Aunque haga mucho que los muros de Sion estén en ruinas, llegará el día en que serán reparados. Israel acudirá de lejanas partes, sin volverse por el desaliento. Aunque parezca que nuestros enemigos nos derrotan, y se regocijan sobre nosotros, no debemos desesperarnos. Aunque derribados, no estamos destruidos; podemos poner la esperanza en la misericordia de Dios, sumisos a su corrección. Ningún estorbo puede evitar los favores que el Señor tiene para su Iglesia.</p>
<br/>
<p class="text-justify">Vv. 14-20.Cuando está por librar a su pueblo, Dios despierta a sus amigos para que oren por ellos. Aplíquese espiritualmente la oración del profeta a Cristo, que cuida de su Iglesia como el Gran Pastor de las ovejas, y va delante de ellas, mientras están en este mundo como en un bosque, en este mundo, pero no de este mundo.
Como respuesta a esta oración, Dios promete que hará por ellos, lo que será repetir los milagros de épocas anteriores. Como el pecado de ellos los llevó a la esclavitud, así el perdón de su pecado de parte de Dios los sacó de ella. Todos los que hallan la misericordia que perdona, no pueden sino maravillarse por su misericordia; tenemos razón para estar asombrados si sabemos qué es esto.
Cuando quita la culpa del pecado, para que no pueda condenarnos, el Señor rompe el poder del pecado para que no tenga dominio de nosotros. Si somos dejados solos, nuestros pecados serán demasiado duros para nosotros, pero la gracia de Dios será suficiente para someterlos de modo que no nos gobiernen, y entonces no nos destruirán. Cuando Dios perdona el pecado, se cuida de que nunca sean recordados contra el pecador. Él arroja sus pecados al mar; no cerca de la playa donde pueden reaparecer, sino en lo profundo del mar, para que nunca salgan a flote otra vez. Todos sus pecados serán arrojados allí, porque cuando perdona el pecado, Dios lo olvida por completo. Él perfeccionará lo que nos concierne y con esta buena obra hará por nosotros todo lo que nuestro caso requiera y que Él ha prometido.
Estos compromisos se relacionan con Cristo y el éxito del evangelio en los últimos tiempos, la futura restauración de Israel, y el dominio final de la verdadera religión en toda la tierra. El Señor cumplirá su verdad y misericordia, ni una tilde ni una coma suyas caerán al suelo; fiel es el que ha prometido, que también lo hará. Recordemos que el Señor ha dado la seguridad de su pacto para poderoso consuelo de todos los que huyen a refugiarse, para que se aferren a la esperanza puesta delante de ellos en Cristo Jesús.</p>
<br/>




</div>
