<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Nehemías 13</h2>
<p class="text-justify">Vv. 10-14.El carácter sagrado que no impide que los hombres den un mal ejemplo, no debe disculpar a nadie de la culpa y el castigo que merece. Los levitas habían sido maltratados; sus porciones no les habían sido entregadas. Tuvieron que salir a ganarse la vida por sí mismos y para sus familias porque su profesión no los mantenía. El mantenimiento insuficiente empobrece el ministerio. La obra se descuida porque los obreros están descuidados.
Nehemías culpó a los gobernantes. Los ministros y el pueblo que abandonan la religión y sus servicios, y los magistrados que no hacen lo posible para mantenerlos en ella, tienen mucho de qué dar cuenta. No tardó en traer de regreso a los levitas a sus puestos y se ocupó de que se les diera el justo pago. En toda ocasión Nehemías miró a Dios y se encomendó a Él con todos sus asuntos. Le agradaba pensar que había sido útil para revivir y sostener la religión en su patria. Aquí se refiere a Dios, no con orgullo, sino con una súplica humilde acerca de su intención honesta en todo lo que había hecho. Ora: “Acuérdate de mí”; no, “recompénsame”; “no borres mis buenas obras”; y no “publícalas o hazlas registrar”. Pero fue recompensado y sus buenas obras quedaron escritas. Dios hace más de lo que somos capaces de pedir.</p>
<br/>
<p class="text-justify">Vv. 15-22.La santa observancia del día del Señor forma un objeto importante para la atención de quienes fomentan la verdadera piedad. La religión nunca prospera cuando se pisotean los días de reposo. No es de maravillarse que hubiera una decadencia general de la fe, y una corrupción de las costumbres de los judíos, cuando abandonaron el santuario y profanaron el día de reposo. Los que profanan el día de reposo poco consideran cuánto mal hacen. Debemos responder por los pecados que otros cometen llevados por nuestro ejemplo. Nehemías los culpa a ellos como cosa mala, porque procede del desprecio a Dios y a nuestras propias almas. Él muestra que quebrantar el día de reposo fue uno de los pecados por los cuales Dios trajo juicios contra ellos; y que si no recibían la advertencia, sino que volvían a los mismos pecados, tenían que esperar más juicios. El valor, el celo y la prudencia de Nehemías en este asunto quedan registrados para que nosotros hagamos lo mismo; y tenemos razón para pensar que la cura que él trajo fue duradera. Él se sintió y se confesó pecador, que nada podía pedir de Dios en justicia, cuando así clama a Él pidiendo misericordia.</p>
<br/>
<p class="text-justify">Vv. 23-31.Si cada padre es impío y de naturaleza corrupta, inclinará a los hijos a seguir su ejemplo; esto es una razón fuerte por la cual los cristianos no deben unirse en yugo desigual. Debe darse sumo cuidado a la educación de los hijos en cuanto al cuidado de la lengua para que no aprendan el lenguaje de Asdod, ni la conversación impura o impía ni la comunicación corrompida.
Nehemías mostró lo malo de estos matrimonios. A algunos, más obstinados que el resto, los azotó, esto es, mandó que fueran azotados por los oficiales conforme a la ley, Deuteronomio xxv, 2, 3.
Aquí están las oraciones de Nehemías en esta ocasión. Él suplica: “Acuérdate de ellos, Dios mío”. Señor, convéncelos de pecado y conviértelos; pon en sus mentes lo que deben ser y hacer. Los mejores servicios para el público han sido olvidados por aquellos para quienes se hicieron, por tanto, Nehemías se encomienda a Dios para que lo recompense. Esto bien puede ser el resumen de nuestras peticiones; no necesitamos más que esto para hacernos felices: Acuérdate de mí, Dios mío, para bien. Podemos esperar humildemente que el Señor se acuerde de nosotros y de nuestros servicios aunque, después de vidas de inagotable actividad y utilidad, aun veremos causa para aborrecernos y arrepentirnos con polvo y cenizas y clamar con Nehemías: ¡Sálvame Dios mío conforme a la grandeza de tu misericordia!</p>
<br/>




</div>
