<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Oseas 14</h2>
<p class="text-justify">Vv. 1-3.Se exhorta a Israel que desde sus pecados e ídolos se vuelva a Jehová, por fe en su misericordia y gracia a través del Redentor prometido y atendiendo con diligencia a su adoración y servicio. Quita la iniquidad; sácala como carga bajo la cual estás listo para sucumbir, o como piedra de tropiezo en que caemos a menudo. Quítala toda por un perdón libre y completo, porque no podemos sacarla por nosotros mismos. Recibe de gracia nuestra oración. Ellos no dicen qué bien procuran, pero lo refieren a Dios. No es bien del que muestra el mundo, sino del que da Dios.
Ellos tenían que considerar sus pecados, sus necesidades y el remedio; y no tenían que llevar sacrificios, sino palabras que declararan los deseos de sus corazones, y con ellas hablar al Señor. El total conforma una descripción clara de la naturaleza y la tendencia de la conversión a Dios del pecador por medio de Jesucristo. Al acercarnos a Dios por la oración de fe, debemos rogarle primero que nos enseñe qué pedir. Debemos ser fervientes con Él rogándole que quite toda iniquidad.</p>
<br/>
<p class="text-justify">Vv. 4-8.Israel busca el rostro de Dios y no lo buscará en vano. Su ira está alejada de ellos. A quien Dios ama, ama libremente; no porque ellos lo merezcan sino por su propio buen placer.
Dios será para ellos todo lo que necesitan. Las gracias del Espíritu son el maná oculto, oculto en el rocío; la gracia así otorgada gratuitamente a ellos no será en vano. Crecerán hacia arriba y serán más florecientes; crecerán como el lirio que, cuando llega a su altura, es una flor hermosa, Mateo vi, 28, 29. Crecerán hacia abajo y serán más firmes. Con la flor del lirio estará la raíz fuerte del cedro del Líbano. El crecimiento espiritual consiste mayormente en el crecimiento de la raíz, que está fuera de la vista. También se extenderán como la vid, cuyas ramas se desparraman ampliamente. Cuando los creyentes abundan en buenas obras, sus ramas se ensanchan. Serán aceptables para Dios y para el hombre. La santidad es la belleza del alma. La Iglesia se compara con la vid y el olivo, que dan fruto útil.
Las promesas de Dios corresponden sólo a los que obedecen sus ordenanzas; no a los que sólo huyen a esta sombra para ampararse de un fulgor caliente, sino a todos los que habitan bajo ella. Cuando un hombre es llevado a Dios, le va mejor a todos los que viven bajo su sombra.
Los frutos santificadores aparecerán en su vida. Así, los creyentes crecen en la experiencia y fertilidad del evangelio.
Efraín dirá: Dios pondrá en su corazón decir: ¡Qué más tengo que ver con los ídolos! Las promesas de Dios son nuestra seguridad y nuestra fuerza para mortificar el pecado más que nuestras promesas a Dios. Véase el poder de la gracia divina. Dios obrará tal cambio en él que odiará los ídolos tanto como antes los amó. Véase el beneficio de las aflicciones santificadas. Efraín se resintió por las consecuencias de su idolatría, y este es su fruto, la remoción de su pecado, Isaías xxvii, 9. Véase la naturaleza del arrepentimiento; es una firme resolución fija de no tener más nada que ver con el pecado. El Señor sale con misericordia al encuentro de los penitentes, como el padre del hijo pródigo salió al encuentro de su hijo que regresaba. Dios será delicia y defensa para todos los convertidos verdaderos; se sentarán a su sombra con delicia. Y como raíz de un árbol: de mí será hallado tu fruto De Él recibimos la gracia y el poder que nos capacita para cumplir nuestro deber.</p>
<br/>
<p class="text-justify">V. 9.¿Quién se beneficia de las verdades entregadas por el profeta? Los que se ponen a entender y conocer estas cosas. Los caminos de la providencia de Dios para nosotros son rectos; todo está bien hecho. Cristo es Piedra Angular para algunos; para otros, Piedra de tropiezo y Roca de escándalo. Lo que fuera ordenado para vida por el abuso se convierte en la muerte para ellos. El mismo sol ablanda la cera y endurece el barro. Pero ciertamente tienen las caídas más peligrosas y fatales los transgresores que caen en los caminos de Dios, que se desmenuzan en la Roca de los siglos, y que sacan veneno del bálsamo de Galaad. Que los pecadores de Sion teman esto. Aprendamos a andar en los caminos rectos de Dios como sus siervos justos, y ninguno de nosotros sea desobediente e incrédulo, y tropiece en la palabra.</p>
<br/>




</div>
