<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Oseas 2</h2>
<p class="text-justify">Vv. 1-5.Este capítulo continúa el discurso figurado a Israel, con referencia a la esposa e hijos de Oseas. Reconozcamos y amemos como hermanos a todos los que el Señor parezca poner entre sus hijos, y animémosles en que han recibido misericordia. Todo cristiano debe protestar contra el mal y los abusos por su ejemplo y conducta, aun entre aquellos a quienes pertenece y debe respeto. Los pecadores impenitentes serán despojados pronto de las ventajas que no aprovecharon y que consumieron en sus lujurias.</p>
<br/>
<p class="text-justify">Vv. 6-13.Dios advierte lo que hará con este traicionero pueblo idólatra.
Ellos no se volvieron, por tanto les sobrevino todo esto, y quedó escrito para nuestra amonestación. Si se superan dificultades menores, Dios las levantará mayores. Los más resueltos en las empresas pecadoras corrientemente son los más trabados en ellas. El camino y deber de Dios suele estar bordeado con espinas, pero tenemos razón para pensar que es camino pecaminoso el que está bordeado y cubierto de espinas. Las cruces y los obstáculos de un camino malo son grandes bendiciones y así deben considerarse; son las vallas de Dios para impedirnos transgredir, para dificultarnos el camino del pecado y sacarnos de ahí. Tenemos razón para bendecir a Dios por la gracia que reprime y por las providencias que frenan; y hasta por el dolor, la enfermedad o la calamidad aguda, si nos impide pecar.
Las desilusiones que encontramos al buscar satisfacción en la criatura, deben llevarnos al Creador, si es que no hacen más. Cuando los hombres olvidan o no toman en cuenta que sus consuelos vienen de Dios, Él suele quitarlos por misericordia, para llevarlos a pensar en su necedad y peligro. El pecado y la alegría nunca pueden durar mucho, pero si los hombres no sacan el pecado de su alegría, Dios les quitará la alegría de sus pecados. Si los hombres destruyen la palabra y las ordenanzas de Dios, es justo que Él destruya sus vides e higueras.
Esta será la ruina de su alegría. Quitar las festividades solemnes y los días de reposo no sirve de nada, porque ellos se separarán prestamente de ellos y no lo considerarán como pérdida, pero Dios les quitará sus placeres sensuales. Los días de alegría pecaminosa deben ser castigados con días de lloro.</p>
<br/>
<p class="text-justify">Vv. 14-23.Después de estos juicios el Señor tratará con más benevolencia a Israel. Por la promesa del reposo en Cristo somos invitados a uncirnos su yugo; la obra de conversión puede prosperar por consolaciones y por convicción de pecado. Pero habitualmente el Señor nos lleva a perder las esperanzas en el goce terrenal y la confianza en nosotros mismos, de modo que teniendo todas las puertas cerradas, podamos llamar a la puerta de la Misericordia.
Desde esa época Israel sería más afectuoso con el Señor, dejando de llamarlo Baali, o “Mi amo y señor”que alude a la autoridad más que al amor, y diciéndole Ishi, una manera cariñosa de tratarlo. Esto puede predecir la restauración del cautiverio de Babilonia y también aplicarse a la conversión a Cristo de los judíos en los días de los apóstoles, y a la conversión general futura de esa nación; los creyentes son facultados para esperar infinitamente más ternura y bondad de su santo Dios que lo que puede esperar una esposa amada del mejor marido.
Cuando el pueblo fuera separado de los ídolos para amar al Señor, ninguna criatura les haría más daño. Esto pueden entenderse de las bendiciones y privilegios del Israel espiritual, de cada creyente verdadero, y de su participación en la justicia de Cristo; también, de la conversión a Cristo de los judíos.
He aquí un argumento para que nosotros andemos de modo tal que Dios no sea deshonrado por nosotros: Tú eres mi pueblo. Si la familia de un hombre anda desordenadamente, es una deshonra para el amor. Si Dios nos llama hijos, podemos decir, Tú eres nuestro Dios. Alma incrédula, deja de lado los pensamientos deprimentes; no respondas así a la amorosa bondad de Dios. ¿Dijo Dios, eres mi pueblo? Di: Señor, Tú eres mi Dios.</p>
<br/>




</div>
