<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 5</h2>
<p class="text-justify">Vv. 1-5.Un cambio bendito ocurre en el estado del pecador cuando llega a ser un creyente verdadero, haya sido lo que fuera. Siendo justificado por la fe tiene paz con Dios. El Dios santo y justo no puede estar en paz con un pecador mientras esté bajo la culpa del pecado. La justificación elimina la culpa y, así, abre el camino para la paz. Esta es por medio de nuestro Señor Jesucristo; por medio de Él como gran Pacificador, el Mediador entre Dios y el hombre.
El feliz estado de los santos es el estado de gracia. Somos llevados a esta gracia. Eso enseña que no nacemos en este estado. No podríamos llegar a ese estado por nosotros mismos, sino que somos llevados a él como ofensores perdonados. Allí estamos firmes, postura que denota perseverancia; estamos firmes y seguros, sostenidos por el poder de Dios; estamos ahí como hombres que mantienen su terreno, sin ser derribados por el poder del enemigo. Y los que tienen la esperanza de la gloria de Dios en el mundo venidero, tienen suficiente para regocijarse en el de ahora.
La tribulación produce paciencia, no en sí misma ni de por sí, pero la poderosa gracia de Dios obra en la tribulación y con ella. Los que sufren con paciencia tienen la mayoría de las consolaciones divinas que abundan cuando abundan las aflicciones. Obra una experiencia necesaria para nosotros.
Esta esperanza no desilusiona, porque está sellada con el Espíritu Santo como Espíritu de amor. Derramar el amor de Dios en los corazones de todos los santos es obra de gracia del Espíritu bendito. El recto sentido del amor de Dios por nosotros no nos avergonzará en nuestra esperanza ni por nuestros sufrimientos por Él.</p>
<br/>
<p class="text-justify">Vv. 6-11.Cristo murió por los pecadores; no sólo por los que eran inútiles sino por los que eran culpables y aborrecibles; por ésos cuya destrucción eterna sería para la gloria de la justicia de Dios. Cristo murió por salvarnos, no en nuestros pecados, sino de nuestros pecados y, aún éramos pecadores cuando Él murió por nosotros. Sí, la mente carnal no sólo es enemiga de Dios, sino la enemistad misma, capítulo viii, 7; Colosenses i, 21. Pero Dios determinó librar del pecado y obrar un cambio grande. Mientras continúe el estado pecaminoso, Dios aborrece al pecador y el pecador aborrece a Dios, Zacarías xi, 8. Es un misterio que Cristo muriera por los tales; no se conoce otro ejemplo de amor, para que bien pueda dedicar la eternidad en adorar y maravillarse de Él.
Además, ¿qué idea tenía el apóstol cuando supone el caso de uno que muere por un justo? Y eso que sólo lo puso como algo que podría ser. ¿No era que al pasar este sufrimiento, la persona que se quería beneficiar, pudiese ser librada? Pero ¿de qué son librados los creyentes en Cristo por su muerte? No de la muerte corporal, porque todos deben soportarla. El mal, del cual podía efectuarse la liberación sólo de esta manera asombrosa, debe haber sido mucho más terrible que la muerte natural. No hay mal al que pueda aplicarse el argumento, salvo el que el apóstol asevera concretamente, el pecado y la ira , el castigo del pecado determinado por la justicia infalible de Dios.
Y si, por la gracia divina, así fueron llevados a arrepentirse y a creer en Cristo, y así eran justificados por el precio de su sangre derramada y por fe en esa expiación, mucho más por medio del que murió por ellos y resucitó, serán librados de caer en el poder del pecado y de Satanás, o de alejarse definitivamente de él. El Señor viviente de todos concretará el propósito de su amor al morir salvando hasta el último de todos los creyentes verdaderos.
Teniendo tal señal de salvación en el amor de Dios por medio de Cristo, el apóstol declara que los creyentes no sólo se regocijan en la esperanza del cielo, y hasta en sus tribulaciones por amor de Cristo, sino que también se glorían en Dios como el Amigo seguro y Porción absolutamente suficiente de ellos, por medio de Cristo únicamente.</p>
<br/>
<p class="text-justify">Vv. 12-14.La intención de lo que sigue es clara. Es la exaltación de nuestro punto de vista acerca de las bendiciones que Cristo nos ha procurado, comparándolas con el mal que siguió a la caída de nuestro primer padre; y mostrando que estas bendiciones no sólo se extienden para eliminar estos males, sino mucho más allá. Adán peca, su naturaleza se vuelve culpable y corrupta y así pasa a sus hijos. Así todos pecamos en él. La muerte es por el pecado, porque la muerte es la paga del pecado. Entonces entró toda esa miseria que es la suerte debida al pecado: la muerte temporal, espiritual, y eterna. Si Adán no hubiera pecado no hubiera muerto, pero la sentencia de muerte fue dictada como sobre un criminal; pasó a todos los hombres como una enfermedad infecciosa de la que nadie escapa. Como prueba de nuestra unión con Adán, y de nuestra parte en aquella primera transgresión, observa que el pecado prevaleció en el mundo por mucho tiempo antes que se diera la ley de Moisés. La muerte reinó ese largo tiempo, no sólo sobre los adultos que pecaban voluntariamente, sino también sobre multitud de infantes, cosa que muestra que ellos habían caído bajo la condena en Adán, y que el pecado de Adán se extendió a toda su posteridad. Era una figura o tipo del que iba a venir como Garantía del nuevo pacto para todos los que estén emparentados con Él.</p>
<br/>
<p class="text-justify">Vv. 15-19.Por medio de la ofensa de un solo hombre, toda la humanidad queda expuesta a la condena eterna. Pero la gracia y la misericordia de Dios y el don libre de la justicia y salvación son por medio de Jesucristo como hombre: sin embargo, el Señor del cielo ha llevado a la multitud de creyentes a un estado más seguro y enaltecido que aquel desde el cual cayeron en Adán. Este don libre no los volvió a poner en estado de prueba; los fijó en un estado de justificación, como hubiera sido puesto Adán si hubiera resistido. Hay una semejanza asombrosa pese a las diferencias. Como por el pecado de uno prevalecieron el pecado y la muerte para condenación de todos los hombres, así por la justicia de uno prevaleció la gracia para justificación de todos los relacionados con Cristo por la fe. Por medio de la gracia de Dios ha abundado para muchos el don de gracia por medio de Cristo; sin embargo, las multitudes optan por seguir bajo el dominio del pecado y la muerte en vez de pedir las bendiciones del reino de la gracia. Pero Cristo no echará afuera a nadie que esté dispuesto a ir a Él.</p>
<br/>
<p class="text-justify">Vv. 20, 21.Por Cristo y su justicia tenemos más privilegios, y más grandes que los que perdimos por la ofensa de Adán. La ley moral mostraba que eran pecaminosos muchos pensamientos, temperamentos, palabras y acciones, de modo que así se multiplicaban las transgresiones. No fue que se hiciera abundar más el pecado, sino dejando al descubierto su pecaminosidad, como al dejar que entre una luz más clara a una habitación, deja al descubierto el polvo y la suciedad que había ahí desde antes, pero que no se veían. El pecado de Adán, y el efecto de la corrupción en nosotros, son la abundancia de aquella ofensa que se volvió evidente al entrar la ley. Los terrores de la ley endulzan más aun los consuelos del evangelio. Así, pues, Dios Espíritu Santo nos entregó, por medio del bendito apóstol, una verdad más importante, llena de consuelo, apta para nuestra necesidad de pecadores. Por más cosas que alguien pueda tener por encima de otro, cada hombre es un pecador contra Dios, está condenado por la ley y necesita perdón. No puede hacerse de una mezcla de pecado y santidad esa justicia que es para justificar. No puede haber derecho a la recompensa eterna sin la justicia pura e inmaculada: esperémosla ni más ni menos que de la justicia de Cristo.</p>
<br/>




</div>
