<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 8</h2>
<p class="text-justify">Vv. 1-9.Los creyentes pueden ser castigados por el Señor, pero no serán condenados con el mundo. Por su unión con Cristo por medio de la fe, están seguros. ¿Cuál es el principio de su andar: la carne o el Espíritu, la naturaleza vieja o la nueva, la corrupción o la gracia? ¿Para cuál de estos hacemos provisión, por cuál somos gobernados? La voluntad sin renovar es incapaz de obedecer por completo ningún mandamiento. La ley, además de los deberes externos, requiere obediencia interna. Dios muestra su aborrecimiento del pecado por los sufrimientos de su Hijo en la carne, para que la persona del creyente fuera perdonada y justificada. Así, se satisfizo la justicia divina y se abrió el camino de la salvación para el pecador. El Espíritu escribe la ley del amor en el corazón, y aunque la justicia de la ley no sea cumplida por nosotros, de todos modos, bendito sea Dios, se cumple en nosotros; en todos los creyentes hay quienes responden a la intención de la ley.
El favor de Dios, el bienestar del alma, los intereses de la eternidad, son las cosas del Espíritu que importan a quienes son según el Espíritu. ¿Por cuál camino se mueven con más deleite nuestros pensamientos? ¿Por cuál camino van nuestros planes e ingenios? ¿Somos más sabios para el mundo o para nuestras almas? Los que viven en el placer están muertos, 1 Timoteo v, 6. El alma santificada es un alma viva, y esa vida es paz. La mente carnal no es sólo enemiga de Dios, sino la enemistad misma. El hombre carnal puede, por el poder de la gracia divina, ser sometido a la ley de Dios, pero la mente carnal, nunca; esta debe ser quebrantada y expulsada.
Podemos conocer nuestro estado y carácter verdadero cuando nos preguntamos si tenemos o no el Espíritu de Dios y de Cristo, versículo 9. Vosotros no estáis en la carne, sino en el Espíritu. Tener el Espíritu de Cristo significa haber cambiado el designio en cierto grado al sentir que había en Cristo Jesús, y eso tiene que notarse en una vida y una conversación que corresponda a sus preceptos y a su ejemplo.</p>
<br/>
<p class="text-justify">Vv. 10-17.Si el Espíritu está en nosotros, Cristo está en nosotros. Él habita en el corazón por fe. La gracia en el alma es su nueva naturaleza; el alma está viva para Dios y ha comenzado su santa felicidad que durará para siempre. La justicia imputada de Cristo asegura al alma, la mejor parte, de la muerte. De esto vemos cuán grande es nuestro deber de andar, no en busca de la carne, sino en pos del Espíritu. Si alguien vive habitualmente conforme a las lujurias corruptas, ciertamente perecerá en sus pecados, profese lo que profese. ¿Y puede una vida mundana presente, digna por un momento, ser comparada con el premio noble de nuestro supremo llamamiento? Entonces, por el Espíritu esforcémonos más y más en mortificar la carne.
La regeneración por el Espíritu Santo trae al alma una vida nueva y divina, aunque su estado sea débil. Los hijos de Dios tienen al Espíritu para que obre en ellos la disposición de hijos; no tienen el espíritu de servidumbre, bajo el cual estaba la Iglesia del Antiguo Testamento, por la oscuridad de esa dispensación. El Espíritu de adopción no estaba, entonces, plenamente derramado. Y, se refiere al espíritu de servidumbre, al cual estaban sujetos muchos santos en su conversión.
Muchos se jactan de tener paz en sí mismos, a quienes Dios no les ha dado paz; pero los santificados, tienen el Espíritu de Dios que da testimonio a sus espíritus que les da paz a su alma.
Aunque ahora podemos parecer perdedores por Cristo, al final no seremos, no podemos ser, perdedores para Él.</p>
<br/>
<p class="text-justify">Vv. 18-25.Los sufrimientos de los santos golpean, pero no más hondo que las cosas del tiempo, sólo duran el tiempo actual, son aflicciones leves y sólo pasajeras. ¡Cuán diferentes son la sentencia de la palabra y el sentimiento del mundo respecto de los sufrimientos de este tiempo presente! Indudablemente toda la creación espera con anhelosa expectativa el período en que se manifiesten los hijos de Dios en la gloria preparada para ellos. Hay impureza, deformidad y enfermedad que sobrevinieron a la criatura por la caída del hombre. Hay enemistad de una criatura contra otra. Son utilizadas, más bien se abusa de ellas, por el hombre como instrumentos de pecado. Sin embargo, este estado deplorable de la creación está “con esperanza”. Dios lo librará de estar así mantenida en esclavitud por la depravación del hombre. Las miserias de la raza humana, por medio de la maldad propia de cada uno y de unos con otros, declaran que el mundo no siempre continúa como está.
Que nosotros hayamos recibido las primicias del Espíritu, vivifica nuestros deseos, anima nuestras esperanzas y eleva nuestra expectativa. El pecado fue y es la causa culpable de todo el sufrimiento que existe en la creación de Dios. El pecado trajo los ayes de la tierra; enciende las llamas del infierno. En cuanto al hombre, ninguna lágrima ha sido derramada, ningún lamento se ha emitido, ninguna punzada se ha sentido, en cuerpo o mente, que no haya procedido del pecado. Esto no es todo: hay que considerar que el pecado afecta la gloria de Dios. ¡Con cuánta temeridad, temible, mira el grueso de la humanidad a esto! -Los creyentes han sido llevados a un estado de seguridad, pero su consuelo consiste más bien en esperanza que en deleite. No pueden ser sacados de esta esperanza por la expectativa vana de hallar satisfacción en las cosas del tiempo y de los sentidos. Necesitamos paciencia, nuestro camino es áspero y largo, pero el que ha de venir, vendrá aunque parezca que tarda.</p>
<br/>
<p class="text-justify">Vv. 26, 27.Aunque las dolencias de los cristianos son muchas y grandes, de modo que serían vencidos si fueran dejados a sí mismos, el Espíritu Santo los sostiene. El Espíritu, como Espíritu iluminador, nos enseña por qué cosa orar; como Espíritu santificador obra y estimula las gracias para orar; como Espíritu consolador, acalla nuestros temores y nos ayuda a superar todas las desilusiones. El Espíritu Santo es la fuente de todos los deseos que tengamos de Dios, los cuales son, a menudo, más de lo que pueden expresar las palabras. El Espíritu que escudriña los corazones puede captar la mente y la voluntad del espíritu, la mente renovada, y abogar por su causa. El Espíritu intercede ante Dios y el enemigo no vence.</p>
<br/>
<p class="text-justify">Vv. 28-31.Lo bueno para los santos es lo que hace buena su alma. Toda providencia tiende al bien espiritual de los que aman a Dios: apartándolos del pecado, acercándolos a Dios, quitándolos del mundo y equipándolos para el cielo. Cuando los santos actúan fuera de su carácter, serán corregidos para volverlos a donde deben estar. Aquí está el orden de las causas de nuestra salvación, una cadena de oro que no puede ser rota.
1. “Porque a los que antes conoció, también los predestinó para que fuesen hechos conformes a la imagen de su Hijo”. Todo eso que Dios concibió como la finalidad de la gloria y felicidad, lo decretó como el camino de la gracia y la santidad. Toda la raza humana merecía la destrucción, pero por razones imperfectamente conocidas para nosotros, Dios determinó recuperar a algunos por la regeneración y el poder de su gracia. El predestinó, o decretó antes, que ellos fueran conformados a la imagen de su Hijo. En esta vida ellos son renovados en parte y andan en sus huellas.
2. “Y a los que predestinó, a éstos también llamó”. Es un llamamiento eficaz, desde el yo y desde la tierra a Dios y a Cristo y al cielo, como nuestro fin; desde el pecado y la vanidad a la gracia y la santidad como nuestro camino. Este es el llamado del evangelio. El amor de Dios, que reina en los corazones de quienes, una vez fueron Sus enemigos, prueba que ellos fueron llamados conforme a su propósito.
3. “Y a los que llamó, a éstos también justificó”. Nadie es así justificado, sino los llamados eficazmente. Los que resisten el evangelio, permanecen sujetos a la culpa y la ira.
4. “Y a los que justificó, a éstos también glorificó”. Siendo roto el poder de la corrupción en el llamamiento eficaz, y eliminada la culpa del pecado en la justificación, nada puede interponerse entre esa alma y la gloria. Esto estimula nuestra fe y esperanza, porque como Dios, su camino, su obra, es perfecta.
El apóstol habla como alguien asombrado y absorto de admiración, maravillándose por la altura y la profundidad, y el largo y la anchura del amor de Cristo que sobrepasa todo conocimiento. Mientras más sabemos de otras cosas, menos nos maravillamos, pero mientras más profundamente somos guiados en los misterios del evangelio, más afectados somos por ellos. Mientras Dios esté por nosotros, y nosotros seamos mantenidos en su amor, podemos desafiar con santa osadía a todas las potestades de las tinieblas.</p>
<br/>
<p class="text-justify">Vv. 32-39.Todas las cosas del cielo y la tierra, cualesquiera sean, no son tan grandes como para exhibir el libre amor de Dios como la dádiva de su coigual Hijo, como expiación por el pecado del hombre en la cruz; y todo lo demás sigue a la unión con Él y el interés en Él. “Todas las cosas”, todo eso que pueda ser causa o medio de cualquier bien real para el cristiano fiel. El que ha preparado una corona y un reino para nosotros, nos dará lo que necesitamos en el camino para alcanzarla.
Los hombres pueden justificarse a sí mismos aunque las acusaciones contra ellos estén plenamente vigentes; pero si Dios justifica, eso responde a todo. Así somos asegurados por Cristo. Él pagó nuestra deuda por el mérito de su muerte. Sí, más que eso, Él ha resucitado. Esta es la prueba convincente de que la justicia divina fue satisfecha. De manera que tenemos un Amigo a la diestra de Dios; toda potestad le ha sido dada a Él, que está allí, e intercede. ¡Creyente!; ¡dice tu alma dentro de ti, ¡oh, que Él fuera mío! Y ¡oh, que yo fuera de Él! ¡que yo pudiese complacerle y vivir para Él! Entonces, no juegues tu espíritu ni confundas tus pensamientos en dudas estériles e interminables, sino como estás convencido de impiedad, cree en aquel que justifica al impío. Estás condenado, pero Cristo ha muerto y resucitado. Huye a Él en esa calidad.
Habiendo Dios manifestado su amor al dar a su propio Hijo por nosotros, ¿podemos pensar que haya algo que pueda apartar o eliminar ese amor? Los problemas no causan ni muestran ninguna disminución de su amor. No importa de qué sean separados los creyentes, queda suficiente. Nadie puede quitar a Cristo del creyente; nadie puede quitar al creyente de Cristo, y eso basta. Todos los otros riesgos nada significan. ¡Sí, pobres pecadores! Aunque abunden con posesiones de este mundo, ¡qué cosas tan vanas son! Puedes decir de cualquiera de ellas, ¿quién nos separará? Puede que hasta te saquen las habitaciones preciosas, las amistades y la fortuna. Puede que vivas hasta para ver y esperar tu partida. Al final, debes separarte, porque debes morir. Entonces, adiós a todo lo que este mundo considera de supremo valor. ¿Qué te ha quedado, pobre alma, que no tienes a Cristo, sino aquello de lo cual te separaras gustoso, sin poder hacerlo: ¡la culpa condenadora de todos tus pecados!? Pero el alma que está en Cristo, cuando le quitan las demás cosas, se aferra a Cristo y estas separaciones no le pesan. Sí, cuando llega la muerte, eso rompe todas las demás uniones, hasta la del alma con el cuerpo, lleva el alma del creyente a la unión más íntima con su amado Señor Jesús, y al gozo pleno de Él para siempre.</p>
<br/>




</div>
