<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 12</h2>
<p class="text-justify">Vv. 1, 2.Habiendo terminado el apóstol la parte de su carta en que argumenta y prueba diversas doctrinas que son aplicadas prácticamente, aquí plantea deberes importantes a partir de los principios del evangelio. Él ruega a los romanos, como hermanos en Cristo, que por las misericordias de Dios presenten sus cuerpos en sacrificio vivo a Él. Este es un poderoso llamado. Recibimos diariamente del Señor los frutos de su misericordia. Presentémonos; todo lo que somos, todo lo que tenemos, todo lo que hacemos, porque después de todo, ¿qué tanto es en comparación con las grandes riquezas que recibimos? Es aceptable a Dios: un culto racional, por el cual somos capaces y estamos preparados para dar razón, y lo entendemos. La conversión y la santificación son la renovación de la mente; cambio, no de la sustancia, sino de las cualidades del alma. El progreso en la santificación, morir más y más al pecado, y vivir más y más para la justicia, es llevar a cabo esta obra renovadora, hasta que es perfeccionada en la gloria. El gran enemigo de esta renovación es conformarse a este mundo. Cuidaos de formaros planes para la felicidad, como si estuviera en las cosas de este mundo, que pronto pasan. No caigáis en las costumbres de los que andan en las lujurias de la carne, y se preocupan de las cosas terrenales. La obra del Espíritu Santo empieza, primero, en el entendimiento y se efectúa en la voluntad, los afectos y la conversación, hasta que hay un cambio de todo el hombre a la semejanza de Dios, en el conocimiento, la justicia y la santidad de la verdad. Así, pues, ser piadoso es presentarnos a Dios.</p>
<br/>
<p class="text-justify">Vv. 3-8.El orgullo es un pecado que está en nosotros por naturaleza; necesitamos que se nos advierta y que seamos armados en su contra. Todos los santos constituyen un cuerpo en Cristo que es la Cabeza del cuerpo, y el centro común de su unidad. En el cuerpo espiritual hay algunos que son aptos para una clase de obra y don llamados a ella; otros, para otra clase de obra. Tenemos que hacer todo el bien que podamos, unos a otros, y para provecho del cuerpo. Si pensáramos debidamente en los poderes que tenemos, y cuán lejos estamos de aprovecharlos apropiadamente, eso nos humillaría. Pero, como no debemos estar orgullosos de nuestros talentos, debemos cuidarnos, no sea que so pretexto de la humildad y la abnegación, seamos perezosos en entregarnos para beneficio de los demás. No debemos decir, no soy nada, así que me quedaré quieto y no haré nada; sino no soy nada por mí mismo y, por tanto, me daré hasta lo sumo en el poder de la gracia de Cristo. Sean cuales fueren nuestros dones o situaciones, tratemos de ocuparnos humilde, diligente, alegre y con sencillez, sin buscar nuestro propio mérito o provecho, sino el bien de muchos en este mundo y el venidero.</p>
<br/>
<p class="text-justify">Vv. 9-16.El amor mutuo que los cristianos se profesan debe ser sincero, libre de engaño, y de adulaciones mezquinas y mentirosas. En dependencia de la gracia divina, ellos deben detestar y tenerle pavor a todo mal, y deben amar y deleitarse en todo lo que sea bueno y útil. No sólo debemos hacer lo bueno; tenemos que aferrarnos al bien. Todo nuestro deber mutuo está resumido en esta palabra: amor. Esto significa el amor de los padres por sus hijos, que es más tierno y natural que cualquier otro; es espontáneo y sin ataduras. Amar con celo a Dios y al hombre por el evangelio dará diligencia al cristiano sabio en todos sus negocios mundanos para alcanzar una destreza superior.
Dios debe ser servido con el espíritu, bajo las influencias del Espíritu Santo. Él es honrado con nuestra esperanza y confianza en Él, especialmente cuando nos regocijamos en esa esperanza. Se le sirve no sólo haciendo su obra, sino sentándonos tranquilos y en silencio cuando nos llama a sufrir. La paciencia por amor a Dios es la piedad verdadera. Los que se regocijan en la esperanza probablemente sean pacientes cuando están atribulados. No debemos ser fríos ni cansarnos en el deber de la oración.
No sólo debe haber benignidad para los amigos y los hermanos; los cristianos no deben albergar ira contra los enemigos. Solo es amor falso el que se queda en las palabras bonitas cuando nuestros hermanos necesitan provisiones reales y nosotros podemos proveerles. Hay que estar preparados para recibir a los que hacen el bien: según haya ocasión, debemos dar la bienvenida a los forasteros.
Bendecid, y no maldigáis. Presupone la buena voluntad completa no bendecirlos cuando oramos para maldecirlos en otros momentos, sino bendecirlos siempre sin maldecirlos en absoluto. El amor cristiano verdadero nos hará participar en las penas y alegrías de unos y otros. Trabaja lo más que pueda para concordar en las mismas verdades espirituales; y cuando no lo logres, concuerda en afecto. Mira con santo desprecio la pompa y dignidad mundanas. No te preocupes por ellas, no te enamores de ellas. Confórmate con el lugar en que Dios te ha puesto en su providencia, cualquiera sea. Nada es más bajo que nosotros sino el pecado. Nunca encontraremos en nuestros corazones la condescendencia para con el prójimo mientras alberguemos vanidad personal; por tanto, esta debe ser mortificada.</p>
<br/>
<p class="text-justify">Vv. 17-21.Desde que los hombres se hicieron enemigos de Dios, han estado muy dispuestos a ser enemigos entre sí. Los que abrazan la religión deben esperar encontrarse con enemigos en un mundo cuyas sonrisas rara vez concuerdan con las de Cristo. No paguéis a nadie mal por mal. Esa es una recompensa brutal, apta sólo para los animales que no tienen consciencia de ningún ser superior, o de ninguna existencia después de esta. Y no sólo hagáis, sino estudiad y cuidaos para hacer lo que es amistoso y encomiable, y que hace que la religión resulte recomendable a todos aquellos con los que converséis.
Estudia las cosas que traen la paz; si es posible, sin ofender a Dios ni herir la conciencia. No os venguéis vosotros mismos. Esta es una lección difícil para la naturaleza corrupta; por tanto, se da el remedio para eso. Dejad lugar a la ira. Cuando la pasión del hombre está en su auge, y el torrente es fuerte, déjelo pasar no sea que sea enfurecido más aún contra nosotros. La línea de nuestro deber está claramente marcada y si nuestros enemigos no son derretidos por la benignidad perseverante, no tenemos que buscar la venganza; ellos serán consumidos por la fiera ira de ese Dios al que pertenece la venganza.
El último versículo sugiere lo que es fácilmente entendido por el mundo: que en toda discordia y contienda son vencidos los que se vengan, y son vencedores los que perdonan. No te dejes aplastar por el mal. Aprende a derrotar las malas intenciones en tu contra, ya sea para cambiarlas o para preservar tu paz. El que tiene esta regla en su espíritu, es mejor que el poderoso. Se puede preguntar a los hijos de Dios si para ellos no es más dulce, que todo bien terrenal, que Dios los capacite por su Espíritu de manera que sea éste su sentir y su actuar.</p>
<br/>




</div>
