<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 1</h2>
<p class="text-justify">Vv. 1-7.La doctrina sobre la cual escribe el apóstol Pablo establece el cumplimiento de las promesas hechas por medio de los profetas. Habla del Hijo de Dios, Jesús el Salvador, el Mesías prometido, que vino de David en cuanto a su naturaleza humana, pero que fue declarado Hijo de Dios por el poder divino que lo resucitó de entre los muertos. La confesión cristiana no consiste en el conocimiento conceptual o el sólo asentimiento intelectual, y mucho menos, discusiones perversas, sino en la obediencia. Sólo los llamados eficazmente por Jesucristo son los llevados a la obediencia de la fe.
Aquí se expone: -1. El privilegio de los cristianos amados por Dios y miembros de ese cuerpo que es amado.
2. El deber de los cristianos: ser santos, de aquí en adelante son llamados, llamados a ser santos. El apóstol saluda a éstos deseándoles gracia que santifique sus almas y paz que consuele sus corazones, las que brotan de la misericordia libre de Dios, el Padre reconciliado de todos los creyentes, que viene a ellos a través del Señor Jesucristo.</p>
<br/>
<p class="text-justify">Vv. 8-15.Debemos demostrar amor por nuestros amigos no sólo orando por ellos, sino alabando a Dios por ellos. Como en nuestros propósitos, y en nuestros deseos debemos acordarnos de decir, Si el Señor quiere, Santiago iv, 15. Nuestras jornadas son o no prosperadas conforme a la voluntad de Dios. Debemos impartir prontamente a otros lo que Dios nos ha entregado, regocijándonos al impartir gozo a los demás, especialmente complaciéndonos en tener comunión con los que creen las mismas cosas que nosotros. Si somos redimidos por la sangre, y convertidos por la gracia del Señor Jesús, somos completamente suyos y, por amor a Él, estamos endeudados con todos los hombres para hacer todo el bien que podamos. Tales servicios son nuestro deber.</p>
<br/>
<p class="text-justify">Vv. 16, 17.El apóstol expresa en estos versículos el propósito de toda la epístola, en la cual plantea una acusación de pecaminosidad contra toda carne; declara que el único método de liberación de la condena es la fe en la misericordia de Dios por medio de Jesucristo y, luego, edifica sobre ello la pureza del corazón, la obediencia agradecida, y los deseos fervientes de crecer en todos esas gracias y temperamentos cristianos que nada, sino la fe viva en Cristo, puede producir.
Dios es un Dios justo y santo, y nosotros somos pecadores culpables. Es necesario que tengamos una justicia para comparecer ante Él; tal justicia existe, fue traída por el Mesías, y dada a conocer en el evangelio: el método de aceptación por gracia a pesar de la culpa de nuestros pecados. Es la justicia de Cristo, que es Dios, la que proviene de una satisfacción de valor infinito. La fe es todo en todo, en el comienzo y en la continuación de la vida cristiana. No es de la fe a las obras como si la fe nos pusiera en un estado justificado y, luego, las obras nos mantuvieran allí, pero siempre es de fe en fe: es la fe que sigue adelante ganándole la victoria a la incredulidad.</p>
<br/>
<p class="text-justify">Vv. 18-25.El apóstol empieza a mostrar que toda la humanidad necesita la salvación del evangelio, porque nadie puede obtener el favor de Dios o escapar de su ira por medio de sus propias obras. Porque ningún hombre puede alegar que ha cumplido todas sus obligaciones para con Dios y su prójimo, ni tampoco puede decir verazmente que ha actuado plenamente sobre la base de la luz que se le ha otorgado. La pecaminosidad del hombre es entendida como iniquidad contra las leyes de la primera tabla, e injusticia contra las de la segunda. La causa de esa pecaminosidad es detener con injusticia la verdad. Todos hacen más o menos lo que saben que es malo y omiten lo que saben que es bueno, de modo que nadie se puede permitir alegar ignorancia. El poder invisible de nuestro Creador y la Deidad están tan claramente manifestados en las obras que ha hecho de modo que hasta los idólatras y los gentiles malos se quedan sin excusa. Siguieron neciamente la idolatría y las criaturas racionales cambiaron la adoración del Creador glorioso por animales, reptiles e imágenes sin sentido. Se apartaron de Dios hasta perder todo vestigio de la verdadera religión, si no lo hubiera impedido la revelación del evangelio. Porque los hechos son innegables, cualesquiera sean los pretextos planteados en cuanto a la suficiencia de la razón humana para descubrir la verdad divina y la obligación moral o para gobernar bien la conducta. Estos muestran simplemente que los hombres deshonraron a Dios con las idolatrías y supersticiones más absurdas y que se degradaron a sí mismos con los afectos más viles y las obras más abominables.</p>
<br/>
<p class="text-justify">Vv. 26-32.La verdad de nuestro Señor se muestra en la depravación horrenda del pagano: “que la luz vino al mundo, y los hombres amaron más las tinieblas que la luz, porque sus obras eran malas. Porque todo aquel que hace lo malo, aborrece la luz”. La verdad no era del gusto de ellos. Todos sabemos cuán pronto se confabula el hombre contra la prueba más evidente para razonar evitándose creer lo que le disgusta. El hombre no puede ser llevado a una esclavitud más grande que la de ser entregado a sus propias lujurias. Como a los gentiles no les gustó tener a Dios en su conocimiento, cometieron delitos totalmente contrarios a la razón y a su propio bienestar. La naturaleza del hombre, sea pagano o cristiano, aún es la misma; y las acusaciones del apóstol se aplican más o menos al estado y al carácter de los hombres de todas las épocas, hasta que sean llevados a someterse por completo a la fe de Cristo, y sean renovados por el poder divino. Nunca hubo todavía un hombre que no tuviera razón para lamentarse de sus fuertes corrupciones y de su secreto disgusto por la voluntad de Dios. Por tanto, este capítulo es un llamado a examinarse a uno mismo, cuya finalidad debe ser la profunda convicción de pecado y de la necesidad de ser liberado del estado de condenación.</p>
<br/>




</div>
