<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 2</h2>
<p class="text-justify">Vv. 1-16.Los judíos se creían pueblo santo, merecedores de sus privilegios por derecho propio, aunque eran ingratos, rebeldes e injustos, pero se les debe recordar a todos los que así actúan, en toda nación, época y clase, que el juicio de Dios será conforme al verdadero carácter de ellos. El caso es tan claro, que podemos apelar a los pensamientos propios del pecador. En todo pecado voluntario hay desprecio de la bondad de Dios. Aunque las ramificaciones de la desobediencia del hombre son muy variadas, todas brotan de la misma raíz. Sin embargo, en el arrepentimiento verdadero debe haber odio por la pecaminosidad anterior dado el cambio obrado en el estado de la mente que la dispone a elegir lo bueno y rechazar lo malo. También muestra un sentido de infelicidad interior. Tal es el gran cambio producido en el arrepentimiento, es la conversión, y es necesario para todo ser humano. La ruina de los pecadores es que caminan tras un corazón duro e impenitente. Sus obras pecaminosas se expresan con las fuertes palabras “atesoras para ti mismo ira”.
Nótese la exigencia total de la ley en la descripción del hombre justo. Exige que los motivos sean puros, y rechaza todas las acciones motivadas por la ambición o por fines terrenales. En la descripción del injusto, se presenta el espíritu contencioso como el principio de todo mal. La voluntad humana está enemistada con Dios. Hasta los gentiles, que no tenían la ley escrita, tenían por dentro lo que les dirigía en cuanto a lo que debían hacer por la luz de la naturaleza. La conciencia es un testigo que, tarde o temprano, dará testimonio. Al obedecer o desobedecer estas leyes naturales y sus dictados, las conciencias de ellos los exoneran o los condenan. Nada causa más terror a los pecadores, y más consuelo a los santos, que Cristo sea el Juez. Los servicios secretos serán recompensados, los pecados secretos serán castigados entonces y sacados a la luz.</p>
<br/>
<p class="text-justify">Vv. 17-24.El apóstol dirige su discurso a los judíos y muestra de cuáles pecados eran culpables a pesar de sus confesiones y vanas pretensiones. La raíz y la suma de toda religión es gloriarse en Dios creyendo, humilde y agradecidamente. Pero la jactancia orgullosa que se vanagloria en Dios, y en la profesión externa de su nombre, es la raíz y la suma de toda hipocresía. El orgullo espiritual es la más peligrosa de todas las clases de orgullo. Un gran mal de los pecados de los profesante es el deshonor contra Dios y la religión, porque no viven conforme a lo que profesan. Muchos que descansan en una forma muerta de piedad, son los que desprecian a su prójimo más ignorante, aunque ellos mismos confían en una forma de conocimiento igualmente desprovista de vida y poder, mientras algunos que se glorían en el evangelio, llevan vidas impías que deshonran a Dios y hacen que su nombre sea blasfemado.</p>
<br/>
<p class="text-justify">Vv. 25-29.No pueden aprovechar las formas, las ordenanzas o las nociones sin la gracia regeneradora, que siempre lleva a buscar un interés en la justicia de Dios por la fe. Porque no es más cristiano ahora, de lo que era el judío de antaño, aquel que sólo lo es en lo exterior: tampoco es bautismo el exterior, en la carne. El cristiano verdadero es aquel que por dentro es un creyente verdadero con fe obediente. El bautismo verdadero es el del corazón, por el lavado de la regeneración y la renovación del Espíritu Santo que trae un marco espiritual a la mente y una voluntad de seguir la verdad en sus caminos santos. Oremos que seamos hechos cristianos de verdad, no por fuera, sino por dentro; en el corazón y el espíritu, no en la letra; bautizados no tan sólo con agua sino con el Espíritu Santo; y que nuestra alabanza sea no de los hombres, sino de Dios.</p>
<br/>




</div>
