<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Romanos 16</h2>
<p class="text-justify">Vv. 1-17.Pablo encomienda a Febe a los cristianos de Roma. Corresponde a los cristianos ayudarse unos a otros en sus asuntos, especialmente a los forasteros; no sabemos qué ayuda podremos necesitar nosotros mismos. Pablo pide ayuda para una que ha sido útil para muchos; el que riega también será regado.
Aunque el cuidado de todas las iglesias estaba con él a diario, podía recordar a muchas personas y enviar saludos a cada una, con sus caracteres particulares y expresar interés por ellos.
Para que nadie se sienta herido, como si Pablo se hubiera olvidado de ellos, manda sus recuerdos al resto, como hermanos y santos, aunque no los nombra. Agrega, al final, un saludo general para todos ellos en el nombre de las iglesias de Cristo.</p>
<br/>
<p class="text-justify">Vv. 17-20.¡Cuán fervientes, cuán afectuosas son estas exhortaciones! Lo que se parta de la sana doctrina de las Escrituras es algo que abre la puerta a la división y a las ofensas. Si se abandona la verdad, no durarán mucho la paz y la unidad. Muchos que llaman Maestro, Señor, a Cristo, distan mucho de servirle, porque sirven sus intereses mundanos, sensuales y carnales. Corrompen la cabeza engañando al corazón; pervierten los juicios porque se enredan en los afectos. Tenemos gran necesidad de cuidar nuestros corazones con toda diligencia. La política corriente de los seductores es imponerse sobre los que están ablandados por sus convicciones. El temperamento dócil es bueno cuando está bien guiado, de lo contrario puede ser llevado a descarriarse. Sed tan sabios como para no ser engañados, pero tan sencillos como para no engañar.
La bendición de Dios que espera el apóstol es la victoria sobre Satanás. Esto incluye todos los designios y estratagemas de Satanás contra las almas, para contaminarlas, perturbarlas y destruirlas; todos sus intentos son para obstaculizarnos la paz del cielo aquí, y la posesión del cielo en el más allá. Cuando parezca que Satanás prevalece, y que estamos listos para darlo todo por perdido, entonces intervendrá el Dios de paz por nosotros. Por tanto, resistid con fe y paciencia un poco más. Si la gracia de Cristo está con nosotros, ¿quién puede vencernos?</p>
<br/>
<p class="text-justify">Vv. 21-24.El apóstol agrega recuerdos afectuosos de personas que están con él, conocidos por los cristianos de Roma. Gran consuelo es ver la santidad y el servicio de nuestros parientes. No son llamados muchos nobles, ni muchos poderosos, pero algunos los son. Es lícito que los creyentes desempeñen oficios civiles y sería deseable que todos los oficios de los países cristianos, y de la Iglesia, fueran encargados a cristianos prudentes y firmes.</p>
<br/>
<p class="text-justify">Vv. 25-27.Lo que confirma las almas es la clara predicación de Jesucristo. Nuestra redención y salvación hecha por el Señor Jesucristo, incuestionablemente es el gran misterio de la piedad. Sin embargo, bendito sea Dios, que tanto de este misterio sea claro como para llevarnos al cielo, si no rechazamos voluntariamente una salvación tan grande. La vida y la inmortalidad son sacadas a la luz por el evangelio, y el Sol de Justicia se levanta sobre el mundo. Las Escrituras de los profetas, lo que dejaron por escrito, no sólo es claro en sí, sino que por ellas se da a conocer este misterio a todas las naciones. Cristo es salvación para todas las naciones. El evangelio es revelado, no para conversarlo ni para debatirlo, sino para someterse a él. La obediencia de fe es la obediencia dada a la palabra de la fe, y que viene por la gracia de la fe.
Toda la gloria que el hombre caído dé a Dios, para ser aceptado por Él, debe ser por medio del Señor Jesús, porque en Él solo pueden ser agradables para Dios nuestras personas y nuestras obras. Debemos mencionar esta justicia, como suya solamente, de Aquel que es el Mediador de todas nuestras oraciones, porque Él es y será, por la eternidad, el Mediador de todas nuestras alabanzas. Recordando que somos llamados a la obediencia de fe, y que todo grado de sabiduría es del único sabio Dios, debemos rendir a Él, por palabra y obra, la gloria por medio de Jesucristo; para que, así esté la gracia de nuestro Señor Jesucristo con nosotros para siempre.</p>
<br/>




</div>
