<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Rut 1</h2>
<p class="text-justify">Vv. 1-5.No se puede culpar a Elimelec de falta de cuidado para proveer a su familia, pero no puede justificarse que se fuera a Moab. Ese cambio terminó en el desastre de su familia. Es necio pensar en escapar de la cruz que se pone en nuestro camino para que la tomemos. Cambiar de lugar no es arreglar las cosas. Quienes llevan a la gente joven a malas compañías y los desvían del camino de las ordenanzas públicas, aunque piensen que lo hacen por buenas razones, y armados contra la tentación, no saben cuál será el final. No parece que las mujeres con quienes se casaron los hijos de Elimelec fueran prosélitas de la religión judía.
Las pruebas o los placeres terrenales son de breve duración. La muerte se lleva continuamente a los de toda edad y situación, y estropea todas nuestras consolaciones externas: nunca preferiremos en exceso las ventajas que durarán eternamente.</p>
<br/>
<p class="text-justify">Vv. 6-14.Después de la muerte de sus dos hijos, Noemí empezó a pensar en regresar. Cuando llega la muerte a una familia debe reformar lo que esté mal. La tierra se nos hace amarga para que amemos el cielo. Noemí parece haber sido persona de fe y piadosa. Se despide de sus nueras con oración. Muy apropiado para los amigos, cuando se separan, separarse con oración. Ella las despidió afectuosamente. Si los familiares deben separarse, que lo hagan con amor. -¿Hizo bien Noemí en desanimar a sus nueras a que fueran con ella, cuando podría haberlas salvados de la idolatría de Moab y llevarlas a la fe y adoración del Dios de Israel? Noemí deseaba indudablemente hacer eso, pero si iban con ella, no las forzaría a ir por cuenta de ella. Los que hacen profesión de fe sólo para agradar a sus amigos o para acompañarlos, serán convertidos de poco valor. Si la seguían, sería por una elección propia después de sentarse a calcular el costo, como corresponde a quienes hacen una profesión religiosa. Muchos desean ‘descansar en la casa de un marido’o en algún establecimiento mundano, o satisfacción terrenal, que el reposo al cual Cristo invita a nuestra alma; por tanto, cuando son probados se alejan de Cristo, aunque quizá con cierta tristeza.</p>
<br/>
<p class="text-justify">Vv. 15-18.Véase la resolución de Rut y su gran afecto por Noemí. Orfa se resistía a separarse de ella, pero no la amaba tanto como para dejar Moab. De esta manera, muchos aprecian a Cristo y le tienen afecto, pero quedan destitudos de su salvación porque no quieren abandonar otras cosas por Él. Lo aman, pero lo dejan, porque no lo aman tanto como aman las otras cosas. Rut es un ejemplo de la gracia de Dios que inclina al alma a elegir la mejor parte. Noemí no podía desear otra cosa que la declaración solemne que hizo Rut. Véase el poder de la resolución; silencia a la tentación. Quienes recorren los caminos religiosos sin una mente firme, son como una puerta entreabierta, que invita al ladrón; pero la resolución cierra y echa cerrojo la puerta, resiste al diablo y le obliga a huir.</p>
<br/>
<p class="text-justify">Vv. 19-22.Noemí y Rut llegaron a Belén. Las aflicciones producen grandes y asombrosos cambios en poco tiempo. Que Dios, por Su gracia, quiera prepararnos para todos esos cambios especialmente ¡para el gran cambio! -Noemí significa “placentera”o “amigable”’Mara, “amarga”o “amargura”. Ahora era una mujer de espíritu amargado. Ella había vuelto a casa vacía, pobre, viuda y sin hijos. Pero hay una plenitud para los creyentes de la cual nunca pueden quedar vacíos; la buena parte que no será quitada de quienes la tienen. La copa de la aflicción es una copa ‘amarga’, pero ella reconoce que la aflicción viene de Dios. Conviene mucho que nuestro corazón sea humillado bajo providencias humillantes. No es la aflicción misma, sino la aflicción bien llevada lo que nos hace bien.</p>
<br/>




</div>
