<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Rut 2</h2>
<p class="text-justify">Vv. 1-3.Obsérvese la humildad de Rut. Cuando la providencia la empobreció, ella se sometió de buena gana a su suerte. Los espíritus soberbios prefieren morir de hambre antes que doblegarse; no así Rut. Es más, es su propia proposición. Ella habla humildemente de su permiso para ir a espigar. Podemos no exigir bondad, como si nos fuera debida, pero podemos pedir, y tomarla como favor, aunque se trate de algo pequeño.
Rut también fue un ejemplo de diligencia. No le gustaba comer el pan de balde. Este es un ejemplo para la juventud. La diligencia promete bien tanto para este mundo como para el otro. No debemos avergonzarnos de un empleo honesto. Ningún trabajo es indigno. El pecado es una cosa baja para nosotros, pero no debemos pensar lo mismo de algo a lo cual nos llama la providencia.
Ella fue un ejemplo de consideración por su suegra y de confianza en la providencia. Dios ordena sabiamente lo que a nosotros nos parecen hechos pequeños; y los que se ven totalmente inciertos, también son dirigidos a servir su gloria y el bien de su pueblo.</p>
<br/>
<p class="text-justify">Vv. 4-16.El lenguaje piadoso y bondadoso entre Booz y sus segadores muestra que había personas piadosas en Israel. Un lenguaje como éste rara vez se oye en nuestros campos; con demasiada frecuencia, por el contrario, es inmoral y corrupto. Un extranjero se formaría una opinión muy diferente de nuestra tierra en comparación con la que Rut se formó de Israel a partir de la conversación y conducta de Booz y sus segadores. Pero la verdadera religión enseña al hombre a comportarse rectamente en todos los estados y condiciones; forma amos amables y siervos fieles y produce armonía en la familia. La religión verdadera produce amor y bondad mutuas entre personas de diferentes rangos. Tuvo estos efectos sobre Booz y sus hombres. Cuando él iba a ellos, oraba por ellos. Ellos no lo maldecían en cuanto él se ponía fuera del alcance de oírlos, como algunos siervos de mala naturaleza que odian el ojo de su amo, sino que retribuyen su cortesía. Lo más probable es que las cosas salgan bien donde hay una buena voluntad como esta entre amos y siervos. Ellos se expresaban su bondad unos a otros y oraban los unos por los otros.
Booz preguntó por la extranjera que vio y ordenó que se la tratara bien. Los amos deben cuidar no sólo de no dañarse a sí mismos; tampoco deben permitir que sus siervos y los que están a su mando hagan el mal. Rut se reconoció humildemente indigna de tales favores, considerando había nacido y sido criada como pagana. Nos conviene a todos pensar humildemente de nosotros mismos, estimando mejor a los demás que a nosotros mismos.
En la bondad de Booz con Rut notemos la bondad del Señor Jesucristo con los pobres pecadores.</p>
<br/>
<p class="text-justify">Vv. 17-23.Estimula la diligencia que en todo trabajo, aun el de espigar, haya ganancia. Rut se contentó con lo que ganaba por su laboriosidad y se cuidó de retener el trabajo. Cuidémonos de no perder lo que hemos obtenido, que hemos ganado para bien de nuestra alma, 2 Juan 8.
Los padres deben examinar a sus hijos como hizo Noemí, no para asustarlos o desanimarlos, no para que odien el hogar o tentarlos a mentir, sino para elogiarlos si han hecho bien, y reprenderlos con suavidad y aconsejarlos si han hecho de otro modo. Una buena pregunta para plantearnos cada noche es, ¿dónde he espigado hoy? ¿Qué mejorías he hecho en el conocimiento y la gracia? ¿Qué he hecho que me dé buen crédito? Cuando el Señor nos da abundancia, no seamos encontrados en otro campo, ni procurando nuestra felicidad y satisfacción en la criatura. Perdemos favores divinos si los desdeñamos.
Rut observó debidamente las instrucciones de su suegra. Cuando terminó la cosecha, hizo compañía a su anciana suegra en casa. Dina salió a ver a las hijas de la tierra; su vanidad terminó en desgracia, Génesis xxxiv. Rut se quedó en casa y ayudó a mantener a su suegra y no salió a otra diligencia que no fuera obtener provisiones para ellas; su humildad y laboriosidad terminaron en su progreso.</p>
<br/>




</div>
