<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Salmos 2</h2>
<p class="text-justify">Vv. 1-6.Aquí se nos dice quiénes aparecerán como adversarios de Cristo. Como este mundo es el reino de Satanás, los inconversos de todo rango, partido y carácter, son incitados por él a oponerse a la causa de Dios, aunque los príncipes de la tierra han sido generalmente los más activos. Las verdades y los preceptos del cristianismo están en contra de los proyectos mundanos ambiciosos y contra las lujurias. Se nos dice a qué apuntan ellos en esta oposición. Ellos romperán las ligaduras de la conciencia y echarán las cuerdas de los mandamientos de Dios; no los recibirán sino que los arrojarán tan lejos como puedan. Esos enemigos no pueden mostrar una buena causa para oponerse a un gobierno justo y santo que, si fuera recibido por todos, traería el cielo a la tierra. No pueden esperar el éxito al oponerse a un reino tan poderoso. El Señor Jesús tiene toda potestad en cielo y tierra y es la Cabeza de la iglesia por sobre todas las cosas, a pesar de los incansables esfuerzos de sus enemigos. El trono de Cristo está establecido en su iglesia, esto es, en el corazón de los creyentes.</p>
<br/>
<p class="text-justify">Vv. 7-9.El reino del Mesías se fundamenta en un decreto eterno de Dios Padre. A este se refiere a menudo nuestro Señor Jesús, por cuanto se gobernaba por él. Dios le había dicho, Tú eres mi Hijo, y conviene a cada uno de nosotros decirle: Tú eres mi Señor, mi Soberano. Al pedir a los paganos como herencia, el Hijo desea la felicidad de ellos en Él; así que ruega por ellos, vive siempre para hacerlo, y es poderoso para salvar hasta lo sumo, y tendrá multitudes de súbditos leales, voluntarios, entre ellos. Los cristianos son la heredad del Señor Jesús; son para Él un nombre y una alabanza. Dios Padre se los da a Cristo cuando, por Su Espíritu y gracia, obra en ellos para llevarlos al Señor Jesús.</p>
<br/>
<p class="text-justify">Vv. 10-12.En cualquier cosa en que nos regocijemos en este mundo, debe ser siempre con temblor, debido a la incertidumbre de todas las cosas. Acoger bien a Jesucristo y someterse a Él, es nuestra sabiduría e interés. Que Él os sea muy querido y precioso; amadle por sobre todas las cosas, amadle con sinceridad, amadle mucho, como lo amaba la mujer, a la cual mucho se le perdonó, y como señal de esto, besó sus pies, Lucas vii, 38. Y con un beso de lealtad uníos a este yugo y someteos para ser gobernados por sus leyes, dispuestos por su providencia y enteramente consagrados a su causa.
La incredulidad es un pecado contra el único remedio. Para vosotros será completa la destrucción; no sea que perezcáis en el camino de vuestros pecados y desde el camino de vuestras vanas esperanzas; para que vuestro camino no perezca, no sea que perdáis el camino a la felicidad. Cristo es el camino; obedeced, no sea que seáis cortados de Él como vuestro camino a Dios. Pensaban que estaban en el camino, pero rechazando a Cristo, perecieron. Bienaventurados en el día de ira los que confiando en Cristo, le han hecho su Refugio.</p>
<br/>




</div>
