<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Salmos 50</h2>
<p class="text-justify">Vv. 1-6.Este es un salmo de instrucción. Habla de la venida de Cristo y del día del juicio en que Dios llamará a los hombres a rendir cuentas; el Espíritu Santo es el Espíritu de juicio. Corresponde a todos los hijos de los hombres conocer la manera justa de adorar al Señor en espíritu y en verdad. Nuestro gran Dios vendrá en el gran día y hará oír su juicio a quienes no escucharon su ley. Dichosos los que entran en el pacto de gracia por fe en el sacrificio expiatorio del Redentor, y muestran la sinceridad de su amor por sus frutos de justicia.
Cuando Dios rechace los servicios de los que descansan en logros externos, aceptará por gracia a quienes lo buscan con rectitud. Sólo podemos ser aceptados por Dios por un sacrificio, por Cristo, el gran sacrificio, de quien derivan su validez los sacrificios de la ley.
Verdaderos y justos son sus juicios; hasta las conciencias de los pecadores serán forzadas a reconocer la justicia de Dios.</p>
<br/>
<p class="text-justify">Vv. 7-15.Obedecer es mejor que los sacrificios, y amar a Dios y a nuestro prójimo es mejor que todos los holocaustos. Aquí se nos advierte que no debemos descansar en tales obras. Cuidémonos de descansar en ellas en ninguna forma. Dios pide el corazón, ¿cómo podrían complacerlo las invenciones humanas, cuando se desprecia el arrepentimiento, la fe y la santidad? -En el día de tribulación, debemos acudir al Señor en oración ferviente. Nuestros problemas deben llevarnos a Él, y no alejarnos de Él, aunque veamos que vienen de la mano de Dios. Debemos reconocerle en todos nuestros caminos, confiar en su sabiduría, poder y bondad, y remitirnos completamente a Él y, así, darle gloria. De esta manera debemos mantener la comunión con Dios; reunirnos con Él mediante la oración cuando estamos en pruebas, y con alabanzas cuando somos liberados. El que suplica con fe no sólo tendrá la respuesta por gracia para su pedido y, tendrá motivos para alabar a Dios, también tendrá gracia para alabarle.</p>
<br/>
<p class="text-justify">Vv. 16-23.La hipocresía es iniquidad que Dios juzgará. Es muy común que los que declaran los estatutos del Señor a los demás, vivan en desobediencia. Este engaño surge de abusar de la paciencia de Dios y de errar voluntariamente en cuanto a su carácter y a la intención de su evangelio.
Los pecados de los pecadores les serán plenamente probados en el gran día del juicio. Viene el día en que Dios pondrá en orden sus pecados, los pecados de la infancia y de la juventud, de la edad madura y de la vejez, para vergüenza y terror eternos de ellos. Los que hasta ahora olvidan a Dios, que están entregados a la maldad o de alguna manera desprecian la salvación, consideren su urgente peligro. La paciencia del Señor es muy grande. Es por demás maravillosa, porque los pecadores hacen tan mal uso de ella; pero si no se vuelven, hará que vean su error cuando sea demasiado tarde. Quienes olvidan a Dios, se olvidan a sí mismos; y nunca estarán bien consigo mismos hasta que recapaciten.
El fin principal del hombre es glorificar a Dios: quien ofrezca alabanza, le glorifica, y sus sacrificios espirituales serán aceptados. Debemos alabar a Dios, sacrificar alabanza, ponerla en las manos del sacerdote, nuestro Señor Jesús, que también es el altar: debemos ser fervientes de espíritu, alabando al Señor. Aceptemos agradecidos la misericordia de Dios y dedíquemonos a glorificarle por palabra y obra.</p>
<br/>




</div>
