<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Salmos 69</h2>
<p class="text-justify">Vv. 1-12.Debemos pensar frecuentemente en la persona del Sufriente del cual se habla aquí y preguntar por qué y qué sufrió, para que meditando en ello seamos más humillados por el pecado, y más convencidos de nuestro peligro para que sintamos más gratitud y amor, que nos lleve a vivir para gloria de Aquel que murió por nuestra salvación. De aquí que aprendemos que cuando estamos afligidos tenemos que encomendar el cuidado de nuestra alma a Dios, para que no seamos amargados por el descontento, ni nos hundamos en la desesperación.
David fue odiado malamente, pero las palabras se aplican con más propiedad a Cristo. En un mundo donde tanto reina la injusticia, no debemos asombrarnos si nos encontramos con la maldad de nuestros enemigos. Cuidémonos de nunca hacer mal; entonces, si recibimos mal, podemos tolerarlo mejor. Por la satisfacción que hizo Cristo con su sangre, ante Dios, por nuestro pecado, restauró aquello que nos quitó, pagó nuestra deuda, sufrió por nuestras ofensas. Aunque podamos alegar que no somos culpables, respecto de las acusaciones injustas de los hombres, sin embargo, ante Dios debemos reconocernos merecedores de todo lo que nos acarrea. Todos nuestros pecados surgen de nuestra necedad. Todos son hechos ante los ojos de Dios.
David se queja de la hostilidad de los amigos y parientes. Esto se cumplió en Cristo, cuyos hermanos no creyeron en Él, y fue abandonado por sus discípulos.
Cristo hizo satisfacción por nosotros, no sólo despojándose de los honores debidos a Dios, sino sometiéndose a las deshonras más grandes que se puedan hacer a un hombre. No tenemos que desanimarnos si nuestro celo por las verdades, preceptos y por la adoración de Dios provoca a algunos, y hace que otros se burlen de nuestra tristeza santa y de que estemos muertos para el mundo.</p>
<br/>
<p class="text-justify">Vv. 13-21.No importa cuán profundas sean las aguas de aflicción o de tentación en que nos hundamos, no importa cuántos sean los diluvios de problemas o de hombres impíos que parecen dispuestos a abatirnos, perseveremos en oración ante nuestro Señor para que nos salve. Las señales del favor de Dios para con nosotros son suficientes para impedir que nuestro espíritu zozobre en los problemas externos más profundos. Si pensamos bien de Dios, y continuamos haciéndolo ante las penurias más grandes, no tenemos que temer, más bien Él nos hará bien. Y si en cualquier momento somos llamados a sufrir reproche y vergüenza por Cristo, esto puede ser nuestro consuelo: Él lo sabe. Mal le sienta a quien conoce el valor de un buen nombre, ser oprimido por un malo, pero cuando pensamos qué favor es ser tenidos por dignos de sufrir vergüenza por el nombre de Jesús, veremos que no hay razón por la cual eso deba quebrantarnos el corazón.
Aquí se anuncian los sufrimientos de Cristo en detalle, lo que prueba que la Escritura es la palabra de Dios; como se cumplieron exactamente estas profecías en Jesucristo, eso prueba que Él es el verdadero Mesías. El vinagre y la hiel que le dieron eran una débil figura de la amarga copa que bebió para que nosotros recibamos la copa de la salvación. No podemos esperar poco de los hombres, todos son consoladores molestos; tampoco podemos esperar demasiado del Dios de todo consuelo y bondad.</p>
<br/>
<p class="text-justify">Vv. 22-29.Estas son profecías de la destrucción de los perseguidores de Cristo. Los versículos 22 y 23 se aplican a los juicios de Dios contra los judíos incrédulos, Romanos xi, 9, 10. Cuando el sustento de la vida y el placer de los sentidos, por la corrupción de nuestra naturaleza, se constituyen en alimento y combustible para el pecado, entonces, nuestra mesa es una trampa.
El pecado de ellos no fue que no vieran, sino que cerraron sus ojos a la luz, amando más las tinieblas; el castigo de ellos no es que no verán, sino que serán entregados a las concupiscencias de sus propios corazones que los encallecieron.
Los que rechazan la gran salvación de Dios que se les ofrece, pueden temer justamente que su indignación sea derramada sobre ellos. Si los hombres pecan, el Señor lo tomará en cuenta. Pero quienes se han multiplicado en el pecar pueden aún hallar misericordia por medio de la justicia del Mediador. Dios no excluye a nadie de esa justicia; el evangelio no excluye a nadie que no se excluya a sí mismo por incredulidad. Pero los que son orgullosos y soberbios y no acuden a la justicia de Dios, tendrán su correspondiente condena: ellos mismos la deciden. Que no esperen ningún provecho de ello quienes no se alegran de estar en deuda con ella.
Es mejor estar pobre y triste con la bendición del Señor, que rico y de buen humor con la maldición del Señor. Esto puede aplicarse a Cristo cuando estuvo en la tierra; el varón de dolores que no tenía dónde reclinar su cabeza, pero Dios lo enalteció. Invoquemos al Señor y su salvación nos elevará, aunque estemos pobres y tristes, culpables y corruptos.</p>
<br/>
<p class="text-justify">Vv. 30-36.El salmo que empezó con quejas por su pesar, el salmista lo concluye con santo gozo y alabanza. Gran consuelo para nosotros es que las alabanzas humildes y agradecidas agraden más a Dios que los sacrificios más caros y pomposos. El humilde mirará a Él y se alegrará; quienes lo buscan por medio de Cristo vivirán y serán consolados.
Dios hará grandes cosas por la iglesia del evangelio, en lo cual regocíjense todos los que desean el bien. Una simiente le servirá en la tierra, y sus siervos heredarán el reino celestial. Los que aman su nombre habitarán por siempre ante Él. El que no escatimó ni a su propio Hijo sino que lo entregó por todos nosotros, ¿cómo no nos dará con Él todas las cosas libremente? Levántate tú, Gran Restaurador de los lugares antiguos para habitar en ellos, y aparta la impiedad de tu pueblo.</p>
<br/>




</div>
