<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Salmos 37</h2>
<p class="text-justify">Vv. 1-6.Cuando miramos alrededor vemos el mundo lleno de malhechores que florecen y viven con comodidad. Así se ha visto de antaño, por lo cual no debemos maravillarnos. Por esto somos tentados a angustiarnos, a pensar que es la única gente feliz, y tendemos a hacer como ellos; sin embargo, se nos advierte en contra. La prosperidad exterior se desvanece. Si miramos adelante, con el ojo de la fe, no veremos razón para envidiar al impío. Su lloro y lamento serán eternos.
La vida religiosa es confianza proveniente de la fe en el Señor y el cuidado diligente de servirle conforme a su voluntad. No es confiar en Dios, sino tentarlo, no tomar conciencia de nuestro deber para con Él. La vida del hombre no consiste en su abundancia, sino en tener el alimento suficiente para ti. Esto es más de lo que merecemos y basta para el que va al cielo.
Deleitarse en Dios es tanto un privilegio como un deber. Él no ha prometido complacer los apetitos del cuerpo y los humores de la fantasía, sino los deseos del alma renovada y santificada. ¿Cuál es el deseo del corazón de un hombre bueno? Es conocer y amar y servir a Dios.
Encomienda a Jehová tu camino; entrega tu camino al Señor, se puede leer. Echa tu carga sobre el Señor, la carga de tu preocupación. Debemos descargarnos nosotros mismos, no afligirnos ni quedarnos perplejos con pensamientos sobre cosas futuras, sino referirlos a Dios. Presenta en oración tu caso y todas tus preocupaciones ante el Señor y confía en Él. Debemos cumplir nuestro deber y, luego, dejarlo a Dios. La promesa es muy dulce: Él hará que ocurra lo que le encomendaste, sea lo que sea.</p>
<br/>
<p class="text-justify">Vv. 7-20.Satisfagámonos con que Dios hará que todo obre para nuestro bien. No nos agitemos por lo que vemos en este mundo. Un espíritu afanoso, descontento está expuesto a muchas tentaciones. Porque en todos los aspectos, lo poco que se asigna al justo, es más consolador y provechoso que todas las riquezas mal obtenidas y engañosas de los impíos. Viene de una mano de amor especial. Dios provee abundantemente y bien, no sólo para sus siervos que trabajan, sino para sus siervos que esperan. Tienen lo que es mejor que la riqueza, paz mental, paz con Dios, y entonces, paz en Dios; esa paz que el mundo no puede dar y el mundo no puede tener . Dios conoce los días del creyente. Nada de la obra de un día quedará sin recompensa. Su tiempo en la tierra se cuenta por días, que pronto terminará la cuenta; pero la felicidad celestial será para siempre.
Esto será un verdadero sustento para los creyentes en las épocas malas. Quienes descansan sobre la Roca de los siglos, no tienen razón para envidiar al malo su apoyo en cañas cascadas.</p>
<br/>
<p class="text-justify">Vv. 21-33.El Señor nuestro Dios requiere que actuemos con justicia y demos a todos lo debido. Gran pecado es que los que pueden, nieguen el pago de deudas justas; gran miseria es no poder pagarlas. El que es verdaderamente misericordioso siempre será misericordioso. Debemos abandonar nuestros pecados; aprender a hacer el bien y aferrarnos a eso. Esta es la verdadera religión.
La bendición de Dios es el manantial, la dulzura, y la seguridad de todos nuestros placeres terrenales. Y si estamos seguros de esto, no estamos seguros de que no nos faltará bien alguno en este mundo. Por su gracia y por el Espíritu Santo, Él dirige los pensamientos, los afectos y los designios de los hombres buenos. Por su providencia Él pasa por encima de los hechos como para hacer sencillo el camino de ellos. No siempre les muestra un tramo extenso de su camino, sino que los guía paso a paso, como se guían los niños. Dios los guardará de ser destruidos por sus caídas, sea en pecado o en problemas, aunque la caída en pecado será sumamente dolorosa.
Pocos, si es que hay alguien, han conocido a un creyente coherente, o a sus hijos, reducido a una desesperada y miserable necesidad. Dios no abandona en la aflicción a sus santos; y sólo el justo habitará por siempre en el cielo; esa será su morada eterna. Un hombre bueno puede caer en las manos de un mensajero de Satanás y ser dolorosamente afectado, pero Dios no lo dejará en las manos de su enemigo.</p>
<br/>
<p class="text-justify">Vv. 34-40.El deber es nuestro y debemos ocuparnos de él; pero los acontecimientos son de Dios, debemos dejar en sus manos disposición de ellos. -¡Qué cuadro impactante es el de los versículos 35, 36, acerca de más de uno de los prósperos enemigos de Dios! Pero Dios destruye notablemente los proyectos de los impíos prósperos, especialmente de los perseguidores.
Nadie es perfecto en sí mismo, pero los creyentes lo son en Cristo Jesús. Si todos los días de los santos continúan siendo tenebrosos y nublados, su día de morir puede resultar consolador y ponerse brillante su sol. O si deben ponerse bajo una nube, de todos modos su estado futuro será de paz perdurable. La salvación del justo será obra del Señor. Él los ayudará a cumplir sus deberes, a llevar sus cargas; les ayudará a soportar bien sus problemas, y lograr el bien a través de ellos, y en el tiempo debido, los librará de sus problemas. Entonces que los pecadores se alejen del mal y hagan el bien; que se arrepientan, abandonen el pecado, y confíen en la misericordia de Dios por medio de Jesucristo. Tomen ellos su yugo sobre sí y aprendan de Él, para que puedan habitar por siempre en el cielo. Notemos las escenas finales de diferentes personajes, y siempre dependamos de la misericordia de Dios.</p>
<br/>




</div>
