<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Santiago 4</h2>
<p class="text-justify">Vv. 1-10.Puesto que todas las guerras y peleas vienen de las corrupciones de nuestros propios corazones, bueno es mortificar las concupiscencias que luchan en los miembros. Las concupiscencias mundanas y carnales son males que no permiten el contento ni la satisfacción. Los deseos y los afectos pecaminosos impiden la oración y la obra de nuestros deseos para con Dios. Pongámonos en guardia para no abusar o usar mal por la disposición del corazón, las misericordias recibidas cuando se conceden las oraciones.
Cuando los hombres piden prosperidad a Dios, suelen pedir con malas miras e intenciones. Si así buscamos las cosas de este mundo, es justo que Dios las niegue. Los deseos incrédulos y fríos oran negaciones; podemos tener toda la seguridad de que nuestras oraciones volverán vacías cuando responde al lenguaje de las concupiscencias más que al lenguaje de las virtudes.
He aquí una clara advertencia a evitar todas las amistades criminales con este mundo. La orientación del mundo es enemistad contra Dios. Un enemigo puede ser reconciliado, pero nunca la ‘enemistad’. El hombre puede tener una porción grande de cosas de esta vida y ser, no obstante, mantenido en el amor de Dios, pero el que pone su corazón en el mundo, al que se conformará en vez de soltar su amistad, es un enemigo para Dios. Así, pues, cualquiera que resuelva en todos los hechos estar en buenos términos con el mundo, debe ser enemigo de Dios. Entonces, los judíos o los profesantes relajados del cristianismo, ¿piensan que la Escritura habla en vano contra esta orientación al mundo? O ¿el Espíritu Santo que habita en todos los cristianos o en la nueva naturaleza que Él crea, producen esa clase de fruto? -La corrupción natural se muestra envidiando. El espíritu del mundo nos enseña a acumular, a apilar para nosotros conforme a nuestras propias fantasías; Dios Espíritu Santo nos enseña a estar dispuestos a hacer el bien a todos los que nos rodean, según podamos. La gracia de Dios corregirá y curará nuestro espíritu natural; y donde Él da gracia, da otro espíritu que no es el del mundo.
El orgulloso resiste a Dios; en su entendimiento resisten las verdades de Dios; en su voluntad resisten las leyes de Dios; en sus pasiones resisten la providencia de Dios; por tanto, no es raro que Dios resista al soberbio. ¡Qué desgraciado el estado de los que hacen de Dios su enemigo! Dios dará más gracia al humilde porque ellos ven su necesidad de ella, oran por ella, son agradecidos de ella, y ellos la tendrán.
Someteos a Dios, versículo 7. Somete tu entendimiento a la verdad de Dios; somete tu voluntad a la voluntad de su precepto, la voluntad de su providencia. Someteos vosotros mismos a Dios, porque Él está dispuesto a hacerles el bien. Si nos rendimos a las tentaciones, el diablo nos seguirá continuamente, pero si nos ponemos toda la armadura de Dios, y le resistimos, nos dejará. Entonces, sométanse a Dios los pecadores y busquen su gracia y favor resistiendo al diablo. Todo pecado debe lamentarse; aquí con tristeza santa; en el más allá , con miseria eterna. El Señor no le negará el consuelo al que lamenta verdaderamente el pecado, y exaltará al que se humille ante Él.</p>
<br/>
<p class="text-justify">Vv. 11-17.Nuestros labios deben estar gobernados por la ley de la bondad, la verdad y la justicia. Los cristianos son hermanos. Quebrantar los mandamientos de Dios es hablar mal de ellos y juzgarlos, como si nos pusieran una restricción demasiado grande. Tenemos la ley de Dios, que es regla para todo; no presumamos de poner nuestras propias nociones y opiniones como regla a los que nos rodean, y tengamos cuidado de no ser condenados por el Señor. -“Anda ahora”es un llamado a todo aquel que considera que su conducta es mala. ¡Qué dados son los hombres mundanos y astutos para dejar fuera de sus planes a Dios! ¡Qué vano es buscar algo bueno sin la bendición ni la dirección de Dios! La fragilidad, la brevedad y la incertidumbre de la vida deben frenar la confianza vana y presuntuosa de todos los proyectos para el futuro. Podemos establecer la hora y el minuto de la salida y la puesta del sol para mañana, pero no podemos fijar la hora cierta en que se disipará la niebla. Tan corta, tan irreal y dada a marchitarse es la vida humana, y toda la prosperidad y el placer que la acompañan; pero la bendición o el ay para siempre serán conforme a nuestra conducta en este momento pasajero.
Siempre tenemos que depender de la voluntad de Dios. Nuestros tiempos no están en nuestras manos sino a disposición de Dios. Nuestra cabeza puede estar llena de preocupaciones y pensamientos por nosotros mismos, o por nuestras familias o amistades, pero la providencia a menudo confunde nuestros planes. Todo lo que pensemos y todo lo que hagamos debe depender con sumisión de Dios. Necio y dañino es jactarse de cosas mundanas y proyectos futuros; producirá gran desengaño y resultará destructivo al final.
Los pecados de omisión y los de comisión serán llevados a juicio. Será condenado tanto aquel que no hace el bien que sabe debe hacer y el que hace el mal que sabe que no debe hacer. ¡Oh, qué fuésemos tan cuidadosos para no omitir la oración y no descuidar la meditación y el examen de nuestras conciencias puesto que no hemos de cometer crasos vicios externos contra la luz!</p>
<br/>




</div>
