<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Santiago 1</h2>
<p class="text-justify">Vv. 1-11.El cristianismo enseña a los hombres a estar gozosos en las tribulaciones; tales ejercicios vienen del amor de Dios; y las pruebas del camino del deber darán lustre a nuestras virtudes ahora y a nuestra corona al final. En los tiempos de prueba preocupémonos que la paciencia actúe en nosotros, y no la pasión; lo que se diga o haga, sea la paciencia la que lo diga y haga. Todo lo necesario para nuestra carrera y guerra cristiana será otorgada cuando la obra de la paciencia esté completa. No debemos orar pidiendo que la aflicción sea eliminada, tanto como pidiendo sabiduría para usarla correctamente. ¿Y quién no quiere sabiduría para que lo guíe en las pruebas, regulando su propio espíritu y administrando sus asuntos? He aquí algo como respuesta a cada giro desalentador de la mente, cuando vamos a Dios experimentando nuestra propia debilidad y necedad. Después de todo, si alguien dice, esto puede pasarle a algunos, pero me temo que yo no triunfaré, la promesa es: a todo aquel que pida, le será dado.
Una mente que se ocupe en considerar, de manera única y dominante, su interés espiritual eterno, y que se mantiene firme en sus propósitos para Dios, crecerá sabia por las aflicciones, continuará ferviente en sus devociones y se levantará por sobre las pruebas y las oposiciones. Cuando nuestra fe y espíritu se levantan y caen con las causas secundarias, nuestras palabras y acciones serán inestables. Esto no siempre expone a los hombres al desprecio del mundo, pero esos caminos no pueden agradar a Dios. Ninguna situación de la vida es tal que impida regocijarse en Dios. Los de baja condición pueden regocijarse si son exaltados a ser ricos en fe y herederos del reino de Dios; y los ricos pueden regocijarse con las providencias humillantes que los llevan a una disposición mental humilde y modesta.
La riqueza mundana es cosa que se agota. Entonces, que el que es rico se regocije en la gracia de Dios que lo hace y mantiene humilde; y en las pruebas y ejercicios que le enseñan a buscar la dicha en Dios y de Él, no en los placeres perecederos.</p>
<br/>
<p class="text-justify">Vv. 12-18.No todo hombre que sufre es el bendecido; pero sí el que con paciencia y constancia va por el camino del deber, a través de todas las dificultades. Las aflicciones no nos pueden hacer miserables si no son por nuestra propia falta. El cristiano probado será un cristiano coronado. La corona de la vida se promete a todos los que tienen el amor de Dios reinando en sus corazones. Toda alma que ama verdaderamente a Dios tendrá sus pruebas de este mundo plenamente recompensadas en ese mundo de lo alto, donde el amor es perfeccionado.
Los mandamientos de Dios, y los tratos de su providencia, prueban los corazones de los hombres, y muestran la disposición que prevalece en ellos. Pero nada pecaminoso del corazón y la conducta puede ser atribuido a Dios. Él no es el autor de la escoria, aunque su prueba de fuego la deja al descubierto. Los que culpan del pecado a su constitución o a su situación en el mundo, o pretenden que no lo pueden evitar, dejan mal a Dios como si Él fuese el autor del pecado. Las aflicciones, como enviados de Dios, están concebidas para sacar a relucir nuestras virtudes, pero no nuestras corrupciones. El origen del mal y de las tentaciones está en nuestros propios corazones.
Detén los comienzos del pecado o todos los males que sigan serán totalmente cargados a tu cuenta. Dios no se complace en la muerte de los hombres, como que no tiene mano en el pecado de ellos, pero el pecado y la miseria, se deben a ellos mismos. Así como el sol es el mismo en la naturaleza e influye, aunque a menudo se interpongan la tierra y las nubes, haciendo lo que a nosotros nos parece variable, así Dios es inmutable y nuestros cambios y sombras no son cambios ni alteraciones en Él. Lo que el sol es en la naturaleza es Dios en gracia, providencia y gloria, e infinitamente más. Como toda buena dádiva es de Dios, así, en particular, es que hayamos nacido de nuevo, y todas sus consecuencias santas y felices vienen de Él. Un cristiano verdadero llega a ser una persona tan diferente de la que era antes de las influencias renovadoras de la gracia divina, que es como si fuera formado de nuevo. Debemos dedicar todas nuestras facultades al servicio de Dios, para que podamos ser una especie de primicias de sus criaturas.</p>
<br/>
<p class="text-justify">Vv. 19-21.En lugar de culpar a Dios cuando estamos sometidos a pruebas, abramos nuestros oídos y corazones para aprender lo que nos enseña por ellas. Si los hombres desean gobernar sus lenguas, deben gobernar sus pasiones. Lo peor que podemos aportar a cualquier disputa es la ira.
He aquí una exhortación a separar y echar como ropa sucia todas las prácticas pecaminosas. Esto debe alcanzar a los pecados del pensamiento y del afecto, y a los pecados del hablar y del hacer; a toda cosa corrupta y pecaminosa. Debemos rendirnos a la palabra de Dios con mentes humildes y dóciles a la enseñanza. Debemos estar dispuestos a oír de nuestros defectos, y a tomarlos no sólo con paciencia, sino con gratitud. El objetivo de la palabra de Dios es hacernos sabios para salvación y los que se proponen cualquier finalidad mala o baja al prestarle atención, deshonran el evangelio y desilusionan sus propias almas.</p>
<br/>
<p class="text-justify">Vv. 22-25.Si oyéramos un sermón cada día de la semana y un ángel del cielo fuera el predicador, no nos llevaría nunca al cielo si nos apoyáramos solamente en el oír. Los que son solo oidores se engañan a sí mismos; y el engaño de sí mismo será hallado, al final, como el peor engaño. Si nos halagamos a nosotros mismos es nuestra propia falta. La verdad no halaga a nadie, tal como está en Jesús. La palabra de verdad debe ser cuidadosamente escuchada con atención, y expondrá ante nosotros la corrupción de nuestra naturaleza, los desórdenes de nuestros corazones y de nuestra vida; nos dirá claramente lo que somos. Nuestros pecados son las manchas que la ley deja al descubierto; la sangre de Cristo es el lavamiento que enseña el evangelio, pero oímos en vano la palabra de Dios y en vano miramos el espejo del evangelio si nos vamos y olvidamos nuestras manchas en lugar de sacarlas lavándolas, y olvidamos nuestro remedio en lugar de recurrir a este. Eso pasa con los que no oyen la palabra como debieran. Al oír la palabra miramos dentro de ella en busca de consejo y guía, y cuando la estudiamos, se vuelve nuestra vida espiritual. Los que se mantienen en la ley y la palabra de Dios son y serán bendecidos en todos sus caminos. Su recompensa de gracia en el más allá estará relacionada con su paz y consuelo presente.
Cada parte de la revelación divina tiene su uso, llevando al pecador a Cristo para salvación, y guiándole y exhortándole a andar en libertad por el Espíritu de adopción, conforme a los santos mandamientos de Dios. Nótese la distinción: el hombre no es bendecido por sus obras, sino en su obra. No es hablar sino andar lo que nos llevará al cielo. Cristo se volverá más precioso para el alma del creyente, que por Su gracia, se volverá más idónea para la herencia de los santos en luz.</p>
<br/>
<p class="text-justify">Vv. 26, 27.Cuando los hombres se esfuerzan por parecer más religiosos de lo que realmente son, es una señal de que su religión es vana. No frenar la lengua, la prontitud para hablar de las faltas del prójimo, o para disminuir su sabiduría y piedad, son señales de religión vana. El hombre que tiene una lengua calumniadora, no puede tener un corazón verdaderamente humilde y bondadoso.
Las religiones falsas pueden conocerse por sus impurezas y falta de caridad. La religión verdadera nos enseña a hacer cada cosa como estando en la presencia de Dios. Una vida inmaculada debe ir unida al amor y la caridad no fingidas. Nuestra religión verdadera es igual a la medida en que estas cosas tengan lugar en nuestro corazón y conducta. Recordemos que nada sirve en Cristo Jesús salvo la fe que obra por amor, que purifica el corazón, que somete las lujurias carnales y que obedece los mandamientos de Dios.</p>
<br/>




</div>
