<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Santiago 5</h2>
<p class="text-justify">Vv. 1-6.Los trastornos públicos son los más penosos para los que viven en el placer y son seguros y sensuales aunque todos los rangos sufran profundamente en tales momentos. Todos los tesoros idolatrados perecerán pronto salvo que sean levantados en juicio contra sus poseedores. Cuidaos de defraudar y oprimir; y evitad hasta las apariencias de mal. Dios no nos prohíbe usar el placer lícito, pero vivir en el placer, especialmente en el placer pecaminoso, es un pecado que provoca. ¿No daña a la gente el no equiparse para preocuparse por los intereses de sus almas, pero darse el gusto en los apetitos carnales? -El justo puede ser condenado y muerto, pero cuando el tal sufre por parte de opresores, Dios lo nota. Por sobre todos sus otros delitos, los judíos habían condenado y crucificado al Justo que vino a ellos, a Jesucristo el Justo.</p>
<br/>
<p class="text-justify">Vv. 7-11.Piénsese en el que espera una cosecha de maíz, ¿y no esperarás una corona de gloria? Si fueras llamado a esperar un poco más que el campesino, ¿no es que hay algo más valioso que esperar? En todo sentido se viene aproximando la venida del Señor y todas las pérdidas, privaciones y sufrimientos de su pueblo serán recompensados. Los hombres cuentan como largo el tiempo porque lo miden según sus propias vidas, pero todo el tiempo es como nada para Dios; es como un instante. Unos cuantos años parecen siglos a las criaturas de corta vida; pero la Escritura que mide todas las cosas por la existencia de Dios, reconoce que miles de años son como algunos días.
Dios hizo cosas en el caso de Job para mostrar claramente que Él es muy compasivo y de tierna misericordia. Esto no se ve durante sus problemas, pero se vio en el resultado, y ahora los creyentes encuentran un final feliz en sus pruebas. Sirvamos a nuestro Dios y soportemos nuestras pruebas como quienes creen que el final coronará todo. Nuestra dicha eterna está segura si confiamos en Él: todo lo demás es pura vanidad que pronto será terminada para siempre.</p>
<br/>
<p class="text-justify">Vv. 12-18.Se condena el pecado de jurar; pero ¡cuántos toman a la ligera el jurar profano corriente! Tales juramentos arrojan desprecio expreso contra el nombre y la autoridad de Dios. Este pecado no produce ganancia, placer ni fama, pero muestra una enemistad contra Dios que no es necesaria ni tiene provecho. Muestra que el hombre es enemigo de Dios, por más que pretenda llamarse con su nombre, o participar a veces en los actos de adoración. Pero el Señor no considerará inocentes a quienes toman su nombre en vano.
En el día de la aflicción nada es más oportuno que la oración. Entonces el espíritu está más humillado y el corazón, quebrantado y blando. Es necesario ejercer fe y esperanza en las aflicciones; y la oración es el medio establecido para obtener e incrementar esas gracias.
Fíjese que la salvación del enfermo no se atribuye a la unción con aceite, sino a la oración. En un momento de enfermedad no es la oración fría y formal la que es efectiva, sino la oración de fe. La gran cosa que debemos rogar de Dios para nosotros y los demás en el tiempo de enfermedad es el perdón de pecado. Que nada se haga para estimular a nadie a tardar, con la equivocada noción de que una confesión, una oración, la absolución y la exhortación de parte de un ministro, o el sacramento, arreglarán todo en el último momento, cuando se han descuidado los deberes de la vida piadosa. La confesión mutua de nuestras faltas ayudará mucho a la paz y al amor fraternal. Mucho sirve cuando una persona justa, un creyente verdadero, justificado en Cristo, y por su gracia, que anda delante de Dios en santa obediencia, presenta una oración ferviente eficaz, puesta en su corazón por el poder del Espíritu Santo, la que produce afectos santos y expectativas de fe, y así guía con fervor a pedir las promesas de Dios en su trono de misericordia.
El caso de Elías demuestra el poder de la oración. No debemos mirar al mérito del hombre cuando oramos, sino a la gracia de Dios. No basta decir una oración sino debemos pedir en la oración. Los pensamientos deben quedar fijos, los deseos deben ser firmes y ardientes, y las gracias deben ejercerse. Este caso del poder de la oración da ánimos a todo cristiano para orar eficazmente. Dios nunca dice a nadie de la simiente de Jacob: “Buscad en vano mi rostro”. Donde pueda parecer que no es un gran milagro de Dios al contestar nuestras oraciones, aún hay mucha gracia.</p>
<br/>
<p class="text-justify">Vv. 19, 20.No es característica del hombre piadoso o sabio jactarse de estar libre de error o negarse a reconocer un error. Hay un error doctrinal en el fondo de todo error práctico. Habitualmente nadie es malo si no se basa en un principio malo.
La conversión es hacer volver al pecador del error de su camino y no solo de una parte a otra o de una noción a otra, ni de un modo de pensar a otro. No hay forma de ocultar eficaz y definitivamente el pecado, sino abandonarlo. Muchos pecados son impedidos por un convertido; también puede hacer así en otros sobre quienes puede tener influencia. La salvación de un alma es de importancia infinitamente mayor que preservar la vida de multitudes o fomentar el bienestar de todo un pueblo. Tengamos presente estas cosas en nuestras diversas etapas, sin eludir el dolor al servicio de Dios, y el tiempo probará que nuestro trabajo en el Señor no es en vano. Él ha estado multiplicando el perdón por seis mil años y todavía su libre gracia no está cansada ni se ha agotado. Ciertamente la misericordia divina es un océano que siempre está lleno y siempre fluye. Que el Señor nos dé una parte de esta abundante misericordia por medio de la sangre de Cristo y de la santificación del Espíritu.</p>
<br/>




</div>
