<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Santiago 2</h2>
<p class="text-justify">Vv. 1-13.Los que profesan fe en Cristo como el Señor de la gloria no deben hacer acepción de personas por las solas circunstancias y apariencias externas, de una manera que no concuerdan con su profesión de ser discípulos del humilde Jesús. Aquí Santiago no anima a la rudeza ni al desorden; debe darse el respeto civil, pero nunca de tal modo que influya en los procedimientos de los cristianos para disponer de los oficios de la Iglesia de Cristo o para pasar las censuras de la iglesia o en alguna cuestión de la religión. El cuestionarnos es algo que sirve mucho en cada parte de la vida santa. Hagámoslo con más frecuencia y aprovechemos toda ocasión para discurrir con nuestras almas.
Como los lugares de adoración no pueden edificarse ni mantenerse sin gastos, puede resultar apropiado que los que contribuyen, sean acomodados de manera concordante, pero si todos fueran personas de mayor orientación espiritual, los pobres serían tratados con más atención de lo que suele ocurrir en las congregaciones.
El estado humilde es más favorable para la paz interior y el crecimiento en la santidad. Dios daría riquezas y honra de este mundo a todos los creyentes si les hicieran bien, considerando que Él los ha escogido para que sean ricos en fe y los ha hecho herederos de su reino, que prometió conceder a todos los que le aman. Considérese cuán a menudo las riquezas conducen al vicio y a la maldad, y qué grandes reproches se hacen a Dios y a la religión por parte de hombres ricos, poderosos y grandes en el mundo; eso hará que este pecado parezca muy grave y necio.
La Escritura da como ley amar al prójimo como a uno mismo. Esta ley es una ley real que viene del Rey de reyes; y si los cristianos actúan injustamente son convictos de transgresión por la ley.
Pensar que nuestras buenas obras expiarán nuestras malas obras, es algo que claramente nos lleva a buscar otra expiación. Conforme al pacto de obras, transgredir cualquier mandamiento pone al hombre bajo condenación, de la cual ninguna obediencia lo puede librar, sea pasada, presente o futura.
Esto nos muestra la dicha de los que están en Cristo. Podemos servirle sin miedo esclavizante. Pero Dios considera que es su gloria y dicha perdonar y bendecir a los que pudieran ser condenados con justicia en su tribunal; y su gracia enseña que los que participan de su misericordia, deben imitarla en su conducta.</p>
<br/>
<p class="text-justify">Vv. 14-26.Se equivocan los que toman la sola creencia de nociones del evangelio por el todo de la religión evangélica, como hacen muchos ahora. Sin duda que la sola fe verdadera, por la cual los hombres participan en la justicia, expiación y gracia de Cristo, salva sus almas; pero produce frutos santos y se demuestra verdadera por sus efectos en las obras de ellos, mientras el solo asentimiento a cualquier forma de doctrina o creencia histórica de hechos, difiere totalmente de la fe salvadora. La sola profesión de fe puede obtener la buena opinión de la gente piadosa, y en algunos casos, puede procurar cosas mundanas buenas, pero ¿de qué aprovecha a alguien si ganare todo el mundo y perdiere su alma? ¿Puede esa fe salvarle? Todas las cosas deben ser contadas como provechosas o perjudiciales para nosotros, según tiendan a promover o a estorbar la salvación de nuestras almas. Este lugar de la Escritura muestra evidentemente que una opinión o asentimiento al evangelio, sin obras, no es fe. No hay manera de mostrar que creemos realmente en Cristo, sino siendo diligentes en buenas obras por motivo del evangelio y para propósitos del evangelio. Los hombres pueden jactarse los unos a los otros y enorgullecerse falsamente de lo que no tienen en realidad.
No se trata sólo de conformarse a la fe sino de acceder a ella; no sólo de asentir la verdad de la palabra, sino del acceder a recibir a Cristo. Creer verdaderamente no es sólo un acto del entendimiento, sino una obra de todo el corazón.
Por dos ejemplos se demuestra que la fe que justifica no puede ser sin obras: Abraham y Rahab. Abraham creyó a Dios y le fue contado por justicia. La fe que produce tales obras le llevó a favores peculiares. Entonces vemos, versículo 24, cómo es justificado el hombre por las obras, no por la sola opinión o declaración, o por creer sin obedecer, sino teniendo la fe que produce buenas obras. Tener que negar su propia razón, afectos e intereses es una acción apta para probar a un creyente.
Nótese aquí, el maravilloso poder de la fe para cambiar a los pecadores. La conducta de Rahab probó que la fe de ella era viva y tenía poder; demostró que ella creía con su corazón y no solo por asentimiento intelectual.
Entonces, pongamos atención que las buenas obras sin fe son obras muertas, carentes de raíz y principio. Todo lo que hacemos por fe es realmente bueno, porque se hace en obediencia a Dios y para su aceptación: cuando no hay fruto es como si la raíz estuviera muerta. La fe es la raíz, las buenas obras son los frutos y debemos ocuparnos de tener ambas. Esta es la gracia de Dios por la cual resistimos y a la cual debemos defender. No hay estado intermedio. Cada uno debe vivir como amigo de Dios o como enemigo de Dios. Vivir para Dios, que es consecuencia de la fe, que justifica y salvará, nos obliga a no hacer nada en su contra sino a hacer todo por Él y para Él.</p>
<br/>




</div>
