<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Sofonías 3</h2>
<p class="text-justify">Vv. 1-7.El santo Dios odia más el pecado en los que están más cerca de él. Un estado pecador es y será un estado lamentable. Sin embargo, ellos tenían los emblemas de la presencia de Dios, y todas las ventajas de conocer su voluntad, con las razones más fuertes para hacerla; aún así persistieron en desobedecer. Sí, los hombres suelen ser más activos para hacer el mal que los creyentes para hacer el bien.</p>
<br/>
<p class="text-justify">Vv. 8-13.Se predice la predicación del evangelio, cuando se ejecute la venganza sobre la nación judía. Las doctrinas purificadoras del evangelio o el lenguaje puro de la gracia del Señor enseñarán a los hombres a usar el lenguaje de la humildad, el arrepentimiento y la fe. Buenas son la pureza y la piedad en la conversación corriente. Parece aludir al estado puro y feliz de la Iglesia en los postreros tiempos. El Señor terminará la jactancia y dejará a los hombres sin nada en qué gloriarse salvo el Señor Jesús, hecho por Dios sabiduría, justicia, santificación y redención para ellos. La humillación por el pecado y las obligaciones hacia el Redentor, harán rectos y sinceros a los creyentes verdaderos, cualquiera sea el caso de los simples profesantes.</p>
<br/>
<p class="text-justify">Vv. 14-20.Después de las promesas de quitar el pecado, siguen las promesas de quitar las tribulaciones. Cuando la causa es eliminada, cesa el efecto. Lo que hace santo a un pueblo, lo hará feliz. Las preciosas promesas hechas al pueblo purificado iban a tener su cumplimiento pleno en el evangelio. Estos versículos se relacionan principalmente con la conversión y restauración futura de Israel, y a los tiempos gloriosos que van a seguir. Muestran la paz, el consuelo y la prosperidad abundante de la Iglesia en los tiempos felices por venir. Él salvará; Él será Jesús; responderá al Nombre, porque Él salvará a su pueblo de sus pecados.
Antes de la época gloriosa anunciada, los creyentes tendrán aflicción y serán objeto de reproche. Pero el Señor salvará al creyente más débil, y hará que los cristianos verdaderos sean tratados con honores ahí donde fueron tratados con desprecio. Un acto de misericordia y gracia servirá, al mismo tiempo para reunir a Israel de su diáspora y llevarlos a su propia tierra. Entonces, el Israel de Dios será hecho nombre y alabanza para la eternidad. Los solos hechos pueden responder plenamente al lenguaje de esta profecía.
Muchas son las aflicciones del justo, pero pueden regocijarse en el amor de Dios. Seguramente nuestros corazones honrarán al Señor y se regocijarán en Él cuando oigamos tales palabras de condescendencia y gracia. Nuestra prueba y pena ahora es tener prohibidas sus ordenanzas, pero a su debido tiempo seremos reunidos en su templo de lo alto. La gloria y la dicha del creyente serán perfectas, inmutables y eternas, cuando sea liberado de las penas terrenales y llevado a la bendición celestial.</p>
<br/>




</div>
