<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Tito 1</h2>
<p class="text-justify">Vv. 1-4.Son siervos de Dios todos los que no son siervos del pecado y de Satanás. Toda la verdad del evangelio es conforme a la piedad, y enseña el temor de Dios. La intención del evangelio es producir esperanza y fe; sacar la mente y el corazón del mundo y elevarlos al cielo y a las cosas de lo alto. ¡Cuán excelente es, entonces, el evangelio que desde los primeros tiempos fue el tema de la promesa divina y cuánta gratitud le debemos por nuestros privilegios! La fe viene por el oír, y el oír por la palabra de Dios; y quien sea así llamado, debe predicar la palabra.
La gracia es el favor gratuito de Dios y la aceptación de Él; y la misericordia, los frutos de ese favor, son el perdón de pecados, y la libertad de todas las miserias, tanto aquí como en el más allá. La paz es el efecto y fruto de la misericordia: la paz con Dios por medio de Cristo que es nuestra Paz, y paz con las criaturas y con nosotros mismos. La gracia es la fuente de todas las bendiciones. La misericordia, la paz, y todo lo bueno surgen de ella.</p>
<br/>
<p class="text-justify">Vv. 5-9.El carácter y las cualidades de los pastores, aquí llamados ancianos y obispos, concuerdan con lo que el apóstol escribió a Timoteo. Puesto que los obispos y sobreveedores del rebaño, deben ser ejemplo para ellos, y mayordomos de Dios para cuidar los asuntos de su casa, hay mucha razón para que sean irreprensibles. Se indica claramente lo que no deben ser y lo que tienen que ser como siervos de Cristo y ministros eficientes de la letra y la práctica del evangelio. Aquí se describe el espíritu y la costumbre que corresponde a los tales, que deben ser ejemplo de buenas obras.</p>
<br/>
<p class="text-justify">Vv. 10-16.Se describe a los falsos maestros. Los ministros fieles deben oponerse a ellos en el momento oportuno para que la necedad de ellos se haga manifiesta, para que no sigan adelante. Tenían una baja finalidad en lo que hacían; sirviendo un interés mundano so pretexto de la religión: porque el amor al dinero es raíz de todo el mal. Los tales deben ser resistidos y avergonzados, por la sana doctrina de las Escrituras. Las acciones vergonzosas, el reproche de los paganos, deben estar lejos de los cristianos; la falsedad y la mentira, la astucia envidiosa y la crueldad, las costumbres brutales y sensuales, la ociosidad y la pereza, son pecados condenados hasta por la luz de la naturaleza. Pero la mansedumbre cristiana dista tanto del disimulo cobarde del pecado y del error como de la ira y la impaciencia. Aunque haya diferencias nacionales de carácter, sin embargo, el corazón del hombre de toda época y lugar es engañoso y perverso. Pero las reprensiones más agudas deben apuntar al bien del reprendido; la fe sana es muy deseable y necesaria. Nada es puro para los que son corrompidos e incrédulos; ellos abusan y hacen pecado de las cosas buenas y lícitas. Muchos profesan conocer a Dios, pero en sus vidas lo niegan y rechazan. Nótese el miserable estado de los hipócritas, como los que tienen una forma de piedad, pero están sin su poder; de todos modos, no estemos tan dispuestos a acusar de esto a los demás, como cuidadosos de que no se aplique a nosotros.</p>
<br/>




</div>
