<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Tito 3</h2>
<p class="text-justify">Vv. 1-7.Los privilegios espirituales no vacían ni debilitan, antes bien confirman los deberes civiles. Sólo las buenas palabras y las buenas intenciones no bastan sin las buenas obras. No deben ser belicosos, sino mostrar mansedumbre en todas las ocasiones, no sólo con las amistades sino a todos los hombres, pero con sabiduría, Santiago ii, 13. Aprendamos de este texto cuán malo es que un cristiano tenga malos modales con el peor, el más débil y el más abyecto.
Los siervos del pecado tienen muchos amos, sus lujurias los apresuran a ir por diferentes caminos; el orgullo manda una cosa, la codicia, otra. Así son odiosos, y merecen ser odiados. Desgracia de los pecadores es que se odien unos a otros, y deber y dicha de los santos es amarse los unos a los otros. Somos librados de nuestro estado miserable sólo por la misericordia y la libre gracia de Dios, el mérito y los sufrimientos de Cristo, y la obra de su Espíritu.
Dios Padre es Dios nuestro Salvador. Él es la fuente de la cual fluye el Espíritu Santo para enseñar, regenerar y salvar a sus criaturas caídas; y esta bendición llega a la humanidad por medio de Cristo. El brote y el surgimiento de ellos son la bondad y el amor de Dios al hombre. El amor y la gracia tienen gran poder, por medio del Espíritu, para cambiar y volver el corazón a Dios. Las obras deben estar en el salvado, pero no son la causa de su salvación. Obra un nuevo principio de gracia y santidad, que cambia, gobierna y hace nueva criatura al hombre. La mayoría pretende que al final tendrá el cielo, aunque ahora no les importa la santidad: ellos quieren el final sin el comienzo. He aquí el signo y sello externo de ello en el bautismo, llamado el lavamiento de la regeneración. La obra es interior y espiritual; es significada y sellada exteriormente en esta ordenanza. No se reste importancia al signo y sello exterior; pero no descanséis en el lavamiento exterior, pero busca la respuesta de una buena conciencia, sin la cual el lavado externo no sirve de nada. El que obra en el interior es el Espíritu de Dios; es la renovación del Espíritu Santo. Por Él mortificamos el pecado, cumplimos el deber, andamos en los caminos de Dios; toda la obra de la vida divina en nosotros, los frutos de la justicia afuera, son por este Espíritu bendito y santo. El Espíritu y sus dones y gracias salvadoras vienen por medio de Cristo, como Salvador, cuya empresa y obra es llevar a los hombres a la gracia y la gloria. La justificación, en el sentido del evangelio, es el perdón gratuito del pecador; aceptarlo como justo por la justicia de Cristo recibida por fe. Dios es bueno con el pecador cuando lo justifica según el evangelio, pero es justo consigo mismo y con su ley. Como el perdón es por medio de la justicia perfecta, y Cristo satisface la justicia, esta no puede ser merecida por el pecador mismo. La vida eterna se presenta ante nosotros en la promesa; el Espíritu produce la fe en nosotros y la esperanza de esa vida; la fe y la esperanza la acercan y llenan de gozo por la expectativa de ella.</p>
<br/>
<p class="text-justify">Vv. 8-11.Cuando se ha declarado la gracia de Dios para con la humanidad, se insta la necesidad de las buenas obras. Los que creen en Dios deben cuidar de mantener las buenas obras, buscando oportunidades para hacerlas, influidos por el amor y la gratitud. Hay que evitar las cuestiones necias y vanas, las distinciones sutiles y las preguntas vanas; tampoco debe la gente desear lo novedoso, sino amar la sana doctrina que tiende mayormente a edificar. Aunque ahora pensemos que algunos pecados son leves y pequeños, si el Señor despierta la conciencia, sentiremos que aun el menor pesa mucho en nuestras almas.</p>
<br/>
<p class="text-justify">Vv. 12-15.El cristianismo no es una profesión infructuosa, y quienes lo profesan deben estar llenos de los frutos de justicia que son por Jesucristo, para la gloria y alabanza de Dios. Deben hacer el bien y mantenerse lejos del mal. Que los ‘nuestros’tengan labores y ocupaciones honestas para proveer para sí mismos y para sus familias. El cristianismo obliga a todos a buscar algún trabajo y vocación honesta, y en ellos, permanecer con Dios.
El apóstol termina con expresiones de consideración amable y una oración ferviente. La gracia sea con todos vosotros; el amor y el favor de Dios, con sus frutos y efectos, para los casos de necesidad; y abunden en ellos en sus almas cada vez más. Este es el deseo y la oración del apóstol que muestra su afecto por ellos, y su deseo de bien para ellos, y quiere que sea el medio de obtener y traigan sobre sí, lo pedido. La gracia es la cosa principal que se debe desear y rogar orando, con respecto a nosotros o al prójimo; es “todo bien”.</p>
<br/>




</div>
