<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Tito 2</h2>
<p class="text-justify">Vv. 1-8.Los antiguos discípulos de Cristo deben comportarse en todo de manera armoniosa con la doctrina cristiana. Los ancianos deben ser sobrios; que no piensen que el deterioro de la naturaleza justifica cualquier exceso, pero busquen consuelo en la comunión más íntima con Dios, no en concesiones indebidas. La fe obra por amor y debe verse en el amor, el de Dios por sí mismo y el de los hombres por amor a Dios. Las personas mayores tienden a ser irritables y temerosas; por tanto, se necesita cuidarlas. Aunque no hay un texto bíblico expreso para cada palabra o mirada, hay, no obstante, reglas generales conforme a las cuales debe ordenarse todo. Las mujeres jóvenes deben ser sobrias y discretas, porque muchas se exponen a tentaciones fatales por lo que al principio pudo ser sólo falta de discreción. Se agrega la razón: para que no sea blasfemada la Palabra de Dios. Fallar en los deberes es un gran reproche al cristianismo.
Los jóvenes son dados a ser ansiosos y precipitados, por tanto, se les debe llamar con seriedad a que sean sobrios: hay gente joven que se arruina más por el orgullo que por cualquier otro pecado.
Todo esfuerzo del hombre piadoso debe ser para callar las bocas de los adversarios. Que tu propia conciencia responda a tu rectitud. ¡Qué gloria es para el cristiano cuando la boca que se abre en su contra, no puede hallar nada malo para hablar de él!</p>
<br/>
<p class="text-justify">Vv. 9, 10.Los siervos deben conocer y cumplir su deber para con sus amos terrenales, con referencia al amo celestial. Al servir a un amo terrenal conforme a la voluntad de Cristo, Él es servido; los tales serán recompensados por Él. No darse al lenguaje insolente y provocativo, pero aceptar en silencio una reprensión o un reproche, sin formular respuestas soberbias ni atrevidas. Cuando uno tiene conciencia de una falta, excusarse o justificarla simplemente la aumenta al doble. Nunca uséis por cuenta propia lo que pertenece al amo, ni desperdiciéis los bienes que os hayan confiado. Demuestra toda esa buena fidelidad para utilizar los bienes del amo, y fomentar su progreso. Si no habéis sido fieles en lo que es de otro hombre, ¿quién os dará lo que es propio? Lucas xvi, 12. La religión verdadera es un honor para los que la profesan y ellos deben adornarla en todas las cosas.</p>
<br/>
<p class="text-justify">Vv. 11-15.La doctrina de la gracia y la salvación por el evangelio es para todos los rangos y estados del hombre. Nos enseña a dejar el pecado; a no tener más relación con éste. La conversación terrenal y sensual no conviene a la vocación celestial. Enseña a tomar conciencia de lo que es bueno. Debemos mirar a Dios en Cristo como objeto de nuestra esperanza y adoración. La conversación del evangelio debe ser una conversación buena. Nótese aquí nuestro deber en pocas palabras: negar la impiedad y las lujurias mundanas, vivir sobria, recta y piadosamente, a pesar de todas las trampas, tentaciones, ejemplos malos, usos malos y vestigios del pecado en el corazón del creyente, con todos sus obstáculos. Nos enseña a buscar las glorias del otro mundo. En la manifestación gloriosa de Cristo, se completará la bendita esperanza de los cristianos.
Llevarnos a la santidad y a la felicidad era la finalidad de la muerte de Cristo. Jesucristo, el gran Dios y Salvador nuestro, que salva no sólo como Dios, y mucho menos como Hombre solo, sino como Dios-Hombre, dos naturalezas en una sola persona. Él nos amó, y se dio por nosotros; ¡y qué menos podemos hacer sino amarle y darnos a Él! La redención del pecado y la santificación de la naturaleza van aunadas y forman un pueblo peculiar para Dios, libre de culpa y condenación, y purificado por el Espíritu Santo.
Toda la Escritura es provechosa. Aquí está lo que proveerá para todas las partes del deber y el correcto desempeño de ellos. Indaguemos si toda nuestra dependencia está puesta en esa gracia que salva al perdido, perdona al culpable, y santifica al inmundo. Mientras más alejados estemos de jactarnos de buenas obras imaginarias, o de confiar en ellas, para gloriarnos en Cristo solo, más celosos seremos para abundar en toda verdadera obra buena.</p>
<br/>




</div>
