<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Zacarías 1</h2>
<p class="text-justify">Vv. 1-6.La omnipotencia de Dios y su dominio soberano debieran comprometer y animar a los pecadores a arrepentirse y volverse a Él. Muy deseable es tener a Jehová de los ejércitos como amigo nuestro, y muy temible es tenerlo como nuestro enemigo. Revisad lo pasado y observad el mensaje que Dios envió por sus siervos, los profetas, a sus padres. Volveos ahora de sus malos caminos y de sus malas obras. Convenceosque dejar sus pecados es la única forma de impedir la ruina que vendrá. -¿Qué llegaron a ser nuestros padres y los profetas que les predicaron? Todos muertos e idos. Ahí estuvieron, en las ciudades y países donde vivimos, pasando y volviendo a pasar por las mismas calles, habitando en las mismas casas, negociando en las mismas tiendas y mercados, adorando a Dios en los mismos lugares, pero ¿dónde están? Cuando murieron no fue el fin de ellos; están en la eternidad, en el mundo de los espíritus, el mundo inmutable hacia el que marchamos apresuradamente. ¿Dónde están? Los que vivieron y murieron en pecado están en los tormentos. Los que vivieron y murieron en Cristo están en el cielo; y si nosotros vivimos y morimos como ellos, dentro de poco tiempo estaremos con ellos eternamente. Si no les importó sus almas, ¿es razón para que su posteridad deba destruir también las suyas? -Los profetas se fueron. Cristo es el Profeta que vive por siempre, pero todos los demás profetas tienen un punto final puesto a su oficio. ¡Oh, que esta consideración tuviera el debido peso; que los ministros moribundos traten con gente moribunda sobre sus almas que nunca mueren, y sobre una eternidad sobrecogedora, al filo de la cual se encuentran! Nosotros y nuestros profetas viviremos para siempre en otro mundo: prepararse para ese mundo debiera ser nuestra mayor preocupación en éste.
Los predicadores murieron y los oyentes murieron, pero la palabra de Dios no muere; ni una jota ni una tilde de ella caerán en tierra porque Él es justo.</p>
<br/>
<p class="text-justify">Vv. 7-17.El profeta vio un bosquecillo oscuro y sombrío oculto por colinas. Esto representaba la baja y triste condición de la iglesia judía. Un hombre, como un guerrero, montado en un caballo alazán, en medio de los mirtos en la hondonada. Aunque la iglesia estaba en baja condición, Cristo estaba presente en medio, listo para manifestarse para alivio de su pueblo. Detrás de Él había ángeles listos para ser utilizados en su servicio; algunos en actos de juicio; otros, de misericordia; otros, en sucesos varios. Si deseamos saber algo de los misterios del reino de los cielos, debemos acudir, no a los ángeles, porque ellos mismos son aprendices, sino a Cristo mismo. Él está preparado para enseñar a los que humildemente desean aprender las cosas de Dios.
Las naciones cercanas a Judea disfrutaban paz en aquella época, pero el estado de los judíos era inestable, lo que dio lugar a la súplica que siguió, pero sólo debe esperarse misericordia por medio de Cristo. La intercesión por su Iglesia prevalece. Jehová le contestó al ángel, el ángel del pacto, con promesas de misericordia y liberación. Todas las palabras buenas y las palabras consoladoras del evangelio las recibimos de Jesucristo, como Él las ha recibido del Padre, en respuesta a la oración de su sangre; y sus ministros tienen que predicarlas a todo el mundo. La tierra se quedó callada y estaba en reposo. No es raro que los enemigos de Cristo estén en reposo en el pecado mientras su pueblo está soportando corrección, acosado por la tentación, inquietos por temores de la ira o gimiendo bajo la opresión y la persecución. Aquí hay anuncios que se refieren al avivamiento de los judíos después del cautiverio, pero esos sucesos fueron sombra de lo que ocurrirá en la Iglesia después de terminada la opresión de la Babilonia del Nuevo Testamento.</p>
<br/>
<p class="text-justify">Vv. 18-21.Los enemigos de la Iglesia amenazan con cortar el nombre de Israel. Son cuernos, emblemas de poder, fuerza y violencia. El profeta los vio tan formidables que empezó a desesperar de la seguridad de todo hombre bueno, y del éxito de toda buena obra, pero el Señor les mostró cuatro carpinteros facultados para cortar los cuernos. Con el ojo de los sentidos vemos el poder de los enemigos de la Iglesia; en cualquier manera que miremos, el mundo nos muestra eso, pero es sólo con el ojo de la fe que la vemos segura. El Señor nos muestra eso. Cuando Dios tiene obra que hacer, levantará a alguien para que la haga, y a otros para que la defiendan y protejan a los ocupados en hacerla. ¡Qué razón hay para mirar con amor y alabanza al Espíritu santo y eterno, que tiene el mismo cuidado por los intereses presentes y eternos de los creyentes, llevando a la Iglesia a conocer por la santa palabra las cosas maravillosas de la salvación!</p>
<br/>




</div>
