<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Zacarías 2</h2>
<p class="text-justify">Vv. 1-5.El Hijo de David, el mismo hombre Cristo Jesús, a quien el profeta ve con un cordel de medir en su mano, es el Maestro constructor de su Iglesia. Dios se fija en la expansión de su Iglesia y cuidará de que haya espacio cualquiera sea el número de invitados llevados al banquete de boda. Esta visión significa bien para Jerusalén. Los muros de una ciudad, al tiempo que la defienden encierran a sus habitantes, pero Jerusalén será extendida tan libremente como si no tuviera muros en absoluto, pero estará tan segura como si tuviera los muros más fuertes.
En la Iglesia de Dios aún hay lugar para otras multitudes, más de lo que puede contar el hombre. No se rechazará a nadie que confíe en Cristo; y Él nunca echa del cielo a un verdadero miembro de la Iglesia de la tierra. Dios será muro de fuego alrededor de ellos, por el cual no se puede entrar ni se puede minar ni puede ser asaltado sin riesgo para los que atacan. Esta visión iba a ser plenamente cumplida en la Iglesia del evangelio, que se extiende para recibir a los gentiles en ella; y que tiene al Hijo de Dios como su Príncipe y Protector; en especial en los tiempos gloriosos aún por venir.</p>
<br/>
<p class="text-justify">Vv. 6-9.Si Dios edifica a Jerusalén para el pueblo y su consuelo, ellos deben habitarla para Él y para su gloria. Las promesas y los privilegios con que es bendecido el pueblo de Dios, debe comprometernos a unirnos a ellos, cualquiera sea el costo para nosotros. Cuando Sion es extendida para dar cabida a todo el Israel de Dios, la gran locura es que alguno de ellos se quede en Babilonia. El cautiverio de un estado pecador no tiene que continuar de ninguna manera, aunque un hombre se sienta cómodo en las cosas del mundo. Escapa por tu vida, no mires atrás. Cristo ha proclamado liberación a los cautivos, la cual ha hecho Él mismo y concierne a cada uno resolver que el pecado no tenga dominio sobre sí. Los que se encuentren entre los hijos de Dios, deben salvarse de este mundo, ver Hechos ii, 40.
Lo que Cristo hará por su Iglesia será prueba evidente del cuidado y afecto de Dios. El que te toca, toca la pupila de su ojo. Esta es una fuerte expresión del amor de Dios por su Iglesia. Él toma lo que se hace contra ella como un ataque contra la parte más sensible del ojo, al que el roce mínimo irrita. Cristo es enviado para ser el protector de su Iglesia.</p>
<br/>
<p class="text-justify">Vv. 10-13.He aquí una predicción de la venida de Cristo en naturaleza humana. Muchas naciones renunciarán a la idolatría ese día, y Dios reconocerá como su pueblo a los que se le unan con propósito de corazón. Se predicen tiempos gloriosos como profecía de la venida y del reino de nuestro Señor. Dios está por hacer algo inesperado y muy sorprendente, y a alegar la causa de su pueblo que ha parecido abandonado por mucho tiempo. Sometéos silenciosamente a su santa voluntad, y esperad con paciencia el acontecer; seguro de que Dios completará su obra. Viene a juzgar antes que pase mucho tiempo, para completar la salvación de su pueblo y castigar a los habitantes de la tierra por sus pecados.</p>
<br/>




</div>
