<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">3.1 Disfrazado como una astuta serpiente, Satanás vino a tentar a Eva. Alguna vez, Satanás fue un ser angelical que se rebeló contra Dios y fue echado del cielo. Satanás es un ser creado y por lo tanto tiene limitaciones. Aun cuando Satanás está tratando de tentar a todos para alejarlos de Dios, no tendrá la victoria final. En Gen 3:14-15 Dios promete que Satanás será aplastado por uno de la simiente de la mujer, el Mesías.
3.1-6 ¿Por qué Satanás nos tienta? La tentación es una invitación de Satanás para entregarnos a su estilo de vida y renunciar al estilo de vida de Dios. Satanás tentó a Eva y logró que pecara. Desde entonces se mantiene ocupado tratando de conseguir que la gente peque. Incluso tentó a Jesús (Mat 4:11), ¡pero Jesús no pecó!
¿De qué manera podría haber resistido Eva la tentación? Siguiendo los mismos principios que nosotros podemos seguir. Primero, debemos darnos cuenta de que ser tentados no es un pecado. No hemos pecado hasta que nos rendimos ante la tentación. Por lo tanto, para resistir la tentación, debemos: (1) orar pidiendo fuerzas para resistirla, (2) huir (algunas veces literalmente), y (3) decir no cuando nos enfrentemos a algo que nos consta que no es correcto. Jam 1:12 habla de las bendiciones y recompensas para aquellos que no se rinden ante la tentación.
3.1-6 La serpiente (Satanás) tentó a Eva haciéndola dudar de la bondad de Dios. El sugirió que Dios era estricto, mísero y egoísta ya que no quería que Eva tuviese como El conocimiento del bien y del mal. Satanás hizo que Eva se olvidara de todo lo que Dios le había dado y que centrara su atención en la única cosa que no podía tener. También, nosotros nos metemos en problemas cuando insistimos en prestar atención a las pocas cosas que no tenemos en lugar de mirar lo mucho que Dios nos ha dado. La próxima vez que sienta lástima de sí por lo que no tiene, considere todo lo que sí tiene y agradezca a Dios. Luego sus dudas no lo harán caer en pecado.
3.5 Adán y Eva obtuvieron lo que querían: un conocimiento íntimo tanto del bien como del mal. Pero lo obtuvieron a través del camino equivocado y el resultado fue desastroso. A veces tenemos la ilusión que libertad es hacer lo que a uno le place. Dios dice que la verdadera libertad proviene de la obediencia y de saber lo que no debemos hacer. Las restricciones que El nos dio son para nuestro propio beneficio, ayudándonos a evitar el mal. Tenemos la libertad de caminar de frente a un automóvil que viene hacia nosotros a alta velocidad, pero no es necesario que seamos atropellados para darnos cuenta de que si lo hacemos sería algo realmente tonto. No escuche las tentaciones de Satanás. No es necesario que haga lo malo para obtener mayor experiencia y aprender más acerca de la vida.
3.5 Satanás utilizó un motivo sincero para tentar a Eva: &quot;¡Llegarás a ser como Dios!&quot; No estaba mal que Eva quisiese ser como Dios. Parecerse más a Dios es la meta suprema de la humanidad. Es lo que se supone que debemos hacer. Pero Satanás engañó a Eva en lo que respecta al modo apropiado de lograr este objetivo. Le dijo que ella podría parecerse más a Dios al desafiar su autoridad, tomando su lugar y decidiendo por sí misma lo que era mejor para su vida. En efecto, le dijo que se convirtiese en su propio dios.
Pero llegar a ser como Dios no es lo mismo que tratar de ser Dios. Más bien, es reflejar sus características y reconocer su autoridad sobre su vida. Al igual que Eva, a menudo tenemos una meta muy valiosa pero tratamos de alcanzarla de un modo equivocado. Nos comportamos como un candidato político que le paga al encargado del recuento de votos para ganar las elecciones. Cuando hace esto, servir al pueblo deja de ser su meta principal.
La exaltación del yo conduce a la rebelión contra Dios. Tan pronto como comenzamos a sacar a Dios de nuestros planes, nos estamos colocando nosotros mismos por encima de El. Esto es exactamente lo que Satanás quiere que hagamos.
ADAN
Es difícil imaginarnos cómo se sentiría Adán siendo la primera y única persona en la tierra. Una cosa es que nosotros nos sintamos solos; para Adán, que nunca había conocido a otro ser humano, era otra cosa. El se perdió de muchas cosas que nos hicieron como somos ahora: no tuvo niñez, ni padres, ni familia, ni amigos. Tuvo que aprender a ser humano por su cuenta. Afortunadamente, Dios no permitió que luchara demasiado tiempo antes de presentarle una ayuda y compañera idónea: Eva. Formaron una unidad completa, inocente y abierta, sin una pizca de vergüenza en nada.
Una de las primeras conversaciones de Adán con su agradabilísima y bella compañera debieron haber sido las reglas del huerto. Antes de que Dios creara a Eva, ya le había dado a Adán completa libertad en el huerto, junto con la responsabilidad de vigilarlo y cuidarlo. Sin embargo, un árbol estaba fuera de los límites: el árbol del conocimiento del bien y del mal. Adán debió haber hablado con Eva sobre todo esto. Ella sabía, cuando Satanás se le acercó, que el fruto de ese árbol no se debía comer. Sin embargo, decidió comer el fruto prohibido. Más tarde se lo ofreció a Adán. En ese momento, el destino de la creación estuvo en peligro. Tristemente, Adán no se detuvo a considerar las consecuencias. Siguió adelante y lo comió.
En ese momento de pequeña rebelión algo grande, hermoso y puro se resquebrajó: la perfecta creación de Dios. El hombre se vio separado de Dios por querer actuar por su cuenta. Sea que se lance un guijarro o una piedra grande hacia una ventana de vidrio, el efecto es el mismo. Nunca podrán volver a reunirse los miles de fragmentos.
Sin embargo, en el caso del pecado del hombre, Dios ya había puesto en marcha un plan para vencer los efectos de la rebelión. La Biblia entera es la historia de cómo se desarrolla ese plan, con la visita de Dios a la tierra a través de su Hijo Jesús como parte esencial. La vida sin pecado de Jesús y su muerte hicieron posible que Dios ofreciera el perdón a todos los que lo quisieran. Nuestras acciones de rebelión, ya sean pequeñas o grandes, demuestran que somos descendientes de Adán. Unicamente el pedir el perdón de Jesucristo nos hace hijos de Dios.
Puntos fuertes y logros :
-- Fue el primer zoólogo: le dio nombre a los animales
-- Fue el primer diseñador de jardines, a cargo de vigilar y cuidar de él
-- Es el padre de la raza humana
-- Fue la primera persona hecha a la imagen de Dios y primer humano que tuvo una relación íntima y personal con El
Debilidades y errores :
-- Evadió la responsabilidad y culpó a otros; prefirió esconderse a enfrentarse; se excusó en lugar de confesar la verdad
-- Su más grande error: hacerse cómplice de Eva para traer el pecado al mundo
Lecciones de su vida :
-- Como descendientes de Adán, todos reflejamos hasta cierto grado la imagen de Dios
-- Dios quiere que las personas, aunque tienen libertad de hacer el mal, opten por amarlo a El.
-- No debemos culpar a los demás de nuestras propias faltas
-- No podemos escondernos de Dios
Datos generales :
-- Dónde: Huerto de Edén
-- Ocupación: Guardián, jardinero y granjero
-- Familiares: Esposa: Eva. Hijos: Caín, Abel, Set y muchos otros hijos más. El único hombre que nunca tuvo padre ni madre terrenales
Versículos clave :
&quot;La mujer que me diste por compañera me dio del árbol, y yo comí&quot; (Gen 3:12).
&quot;Porque así como en Adán todos mueren, también en Cristo todos serán vivificados&quot; (1Co 15:22).
La historia de Adán se relata en Génesis 1.26-5.5. También se le menciona en 1Ch 1:1; Luk 3:38; Rom 5:14; 1Co 15:22, 1Co 15:45; 1Ti 2:13-14.
3.6 Satanás trató de que Eva pensara que el pecado era bueno, placentero y deseable. El conocimiento tanto del bien como del mal le parecía inofensivo a ella. Por lo general, la gente decide hacer cosas malas porque se ha convencido de que esas cosas son buenas, al menos para ellos mismos. Nuestros pecados no siempre nos parecen horribles, y los pecados que dan placer son los que nos cuesta más trabajo evitar. Así que prepárese para las atractivas tentaciones que puedan surgir a su paso. Aun cuando no siempre podamos prevenir la tentación, siempre hay una salida (1Co 10:13). Recurra a la Palabra de Dios y a su pueblo para permanecer firme ante la tentación.
3.6, 7 Observe con atención lo que hizo Eva: miró, tomó, comió y dio. A menudo la batalla está perdida al primer vistazo. La tentación comienza simplemente al mirar algo que queremos. ¿Está usted luchando con la tentación porque no ha aprendido que mirar es el primer paso hacia el pecado? Saldremos victoriosos de la tentación más a menudo si seguimos el consejo de Pablo de huir de aquellas cosas que nos producen malos pensamientos (2Ti 2:22).
3.6, 7 Una de las realidades del pecado es que su efecto se extiende. Después de que Eva pecase, involucró a Adán en su mala acción. Cuando hacemos algo malo, a menudo nuestro primer alivio de la culpa viene cuando involucramos a alguien más. Como desperdicio tóxico derramado en un río, el pecado se extiende rápidamente. Reconozca y confiese su pecado a Dios antes de que sea tentado y contamine a los que están a su alrededor.
3.7, 8 Después de pecar, Adán y Eva se sintieron culpables y avergonzados por su desnudez. Sus sentimientos de culpabilidad los hicieron huir de Dios y trataron de esconderse. Una conciencia culpable es una señal de advertencia que Dios ha colocado dentro de usted que se enciende cuando ha hecho lo malo. Lo peor que puede hacer es eliminar los sentimientos de culpabilidad sin eliminar la causa. Es como utilizar un analgésico sin detectar la enfermedad. Alégrese de que esos sentimientos estén ahí, lo hacen estar consciente de su pecado para que así pueda pedir el perdón de Dios y corregir sus malas acciones.
3.8 Resulta graciosa la imagen de dos humanos cubiertos con hojas de higuera tratando de esconderse del Dios que todo lo ve y todo lo sabe. ¿Cómo pudieron ser tan tontos de pensar que podían esconderse? Sin embargo, nosotros hacemos lo mismo cuando tratamos de ocultarle cosas a Dios. Cuéntele todo lo que hace y piensa y no trate de esconderse, es imposible. La sinceridad fortalecerá su relación con Dios.
3.8, 9 Este versículo muestra el deseo de Dios de tener amistad con nosotros. También muestra por qué tenemos miedo de tener una relación con El. Adán y Eva se escondieron cuando escucharon que se acercaba. Dios quería estar con ellos, pero por causa de su pecado, Adán y Eva tenían miedo de mostrarse ante El. El pecado había roto su comunión con Dios, así como ha roto nuestra comunión con Dios. Pero por medio de Jesucristo, el Hijo de Dios, se ha abierto el camino para que renovemos nuestra amistad con El. Dios desea estar con nosotros. El nos ofrece de lleno su amor incondicional. Nuestra respuesta natural es el temor, ya que sabemos que no podemos vivir bajo sus normas. Pero el reconocer que El nos ama, a pesar de nuestras faltas, nos puede ayudar a quitar ese temor.
3.11-13 Adán y Eva no hicieron caso a la advertencia de Dios en 2.16, 17. Ellos no entendieron las razones de este mandamiento, así que decidieron actuar de la forma que les parecía más apropiada. Todos los mandamientos de Dios son obviamente para nuestro propio beneficio, pero puede que no siempre entendamos las razones. El pueblo que confía en Dios le obedecerá porque Dios lo pide, sea que entienda o no el porqué de sus mandamientos.
3.11-13 Cuando Dios le preguntó a Adán sobre su pecado, Adán culpó a Eva. Luego Eva culpó a la serpiente. Cuán fácil es disculpar nuestros pecados culpando a otra persona o a las circunstancias. Pero Dios sabe la verdad. Y El nos hace responsables a cada uno de nosotros por lo que hacemos (véase 3.14-19). Admita su pecado y pida disculpas a Dios. No trate de escapar de su pecado culpando a otro.
3.14ss Adán y Eva eligieron su curso de acción (desobediencia) y luego Dios eligió el suyo. Como Dios santo sólo podía responder de una manera coherente con su naturaleza moral perfecta. No podía permitir pasar por alto el pecado, debía castigarlo. Si las consecuencias del pecado de Adán y Eva le parecen extremas, recuerde que el pecado que cometieron puso en acción la tendencia del mundo a la desobediencia a Dios. Este es el motivo por el cual todavía pecamos hoy: Todo ser humano que jamás haya nacido, con la excepción de Jesús, posee la herencia de la naturaleza pecaminosa de Adán y Eva (Rom 5:12-21). El castigo de Adán y Eva refleja con qué seriedad Dios ve el pecado de cualquier clase.
3.14-19 Adán y Eva aprendieron por medio de una experiencia dolorosa que, ya que Dios es justo y odia el pecado, debe castigar a los pecadores. El resto del libro de Génesis relata historias dolorosas de vidas arruinadas por la caída. La desobediencia es pecado y rompe nuestra relación con Dios. Afortunadamente, cuando desobedecemos, la voluntad de Dios es perdonarnos y restaurar nuestra relación con El.
3.15 Satanás es nuestro enemigo, él hará todo lo posible para hacer que sigamos su camino de maldad y muerte. La frase &quot;Tú le herirás en el calcañar&quot; se refiere a los intentos constantes de Satanás de derrotar a Cristo durante su vida en la tierra. &quot;Esta te herirá en la cabeza&quot;, anuncia la derrota de Satanás cuando Cristo se levantó de la muerte. Un golpe al talón no es mortal, pero uno asestado en la cabeza sí. Ya Dios estaba revelando su plan para derrotar a Satanás y ofrecer salvación al mundo por medio de su Hijo Jesucristo.
3.17-19 La desobediencia de Adán y Eva, y la caída de la gracia de Dios afectó a toda la creación, incluyendo al medio ambiente. Años atrás la gente no se preocupaba de la contaminación de los ríos con desperdicios químicos y basura. Esto parecía tan insignificante, tan trivial. Ahora sabemos que sólo dos o tres partes por millón de ciertas sustancias químicas pueden dañar la salud humana. El pecado en nuestras vidas es extrañamente similar a los desperdicios tóxicos. Hasta las cantidades más pequeñas son letales.
3.22-24 La vida en el huerto del Edén era como vivir en el cielo. Todo era perfecto, y si Adán y Eva hubieran obedecido a Dios, podrían haber vivido allí por siempre. Pero después de desobedecer, Adán y Eva ya no merecían vivir en el paraíso, así que Dios les dijo que se fueran. Si hubieran continuado viviendo en el huerto y comiendo del árbol de la vida, habrían vivido para siempre. Pero la vida eterna en un estado de pecado significaría tratar de esconderse eternamente de Dios. Como Adán y Eva, todos nosotros hemos pecado y estamos separados de Dios. Sin embargo, nosotros no tenemos que permanecer separados. Dios está preparando una nueva tierra como paraíso eterno para todo su pueblo (véase Apocalipsis 22).
3.24 Los querubines eran poderosos ángeles del Señor.
3.24 Así es como Adán y Eva rompieron su relación con Dios: (1) llegaron a estar convencidos de que su camino era mejor que el de Dios; (2) se cohibieron y se escondieron; (3) trataron de disculparse y defenderse. Para construir una relación con Dios debemos revertir esos pasos: (1) abandonar las disculpas y la autodefensa; (2) dejar de escondernos de Dios; (3) convencernos de que el camino de Dios es mejor que el nuestro.
PLAN DE SATANAS
Duda: Nos hace cuestionar la Palabra de Dios y su bondad
Desaliento: Nos hace dirigir la mirada hacia nuestros problemas y no hacia Dios
Confusión: Hace que las cosas malas nos parezcan atractivas para que las deseemos más que las cosas buenas
Derrota: Nos hace sentirnos fracasados
Demora: Nos hace posponer las cosas para que nunca las hagamos</p>
<br/>




</div>
