<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">1.1 La simple afirmación de que Dios creó los cielos y la tierra es uno de los conceptos más desafiantes que enfrenta la mente moderna. La grandiosa galaxia en la que vivimos gira a la increíble velocidad de 784.000 km por hora. Pero incluso a esta velocidad vertiginosa, nuestra galaxia igualmente necesita 200 millones de años para hacer una rotación. Y existen más de 1000 millones de galaxias como la nuestra.
Algunos científicos dicen que el número de estrellas que hay en la creación es igual a todos los granos de todas las arenas de todas las playas del mundo. Aun así este complejo mar de estrellas giratorias funciona con un orden y una eficiencia sorprendentes. Decir que el universo &quot;sólo apareció&quot; o &quot;evolucionó&quot; requiere mucha más fe que creer que Dios está detrás de todas estas estadísticas asombrosas. Ciertamente Dios ha creado un universo maravilloso.
Dios no necesitaba crear el universo; El decidió crearlo. ¿Por qué? Dios es amor y el amor se expresa mejor hacia algo o hacia alguien, así que Dios creó al mundo y a la gente como una expresión de su amor. Debemos evitar reducir la creación de Dios a términos meramente científicos. Recuerde que Dios creó el universo porque ama a cada uno de nosotros.
1.1ss La historia de la creación nos enseña mucho acerca de Dios y de nosotros mismos. Primero, aprendemos acerca de Dios: (1) El es creativo; (2) como Creador es diferente a su creación; (3) El es eterno y controla al mundo. También aprendemos de nosotros mismos: (1) ya que Dios decidió crearnos, somos valiosos ante sus ojos; (2) somos más importantes que los animales. (Véase 1.28 para mayor información sobre nuestro rol en el orden creado.)
1.1ss ¿Exactamente cómo creó Dios al mundo? Este sigue siendo un asunto de gran debate. Algunos dicen que hubo una repentina explosión y el universo apareció. Otros dicen que Dios inició el proceso y que el universo evolucionó a lo largo de miles de millones de años. Casi cualquier religión antigua cuenta con su propia historia para explicar cómo llegó a ser el mundo. Y casi todos los científicos tienen una opinión sobre el origen del universo. Pero sólo la Biblia muestra un Dios supremo que creó la tierra por su gran amor y que dio a toda la gente un lugar especial en él. Nunca sabremos todas las respuestas de cómo Dios creó al mundo. Pero la Biblia nos dice que Dios sí lo creó. Este hecho por sí solo da a la gente valor y dignidad.
1.2 La afirmación de que &quot;la tierra estaba desordenada y vacía&quot;, proporciona el entorno para la narración de la creación que aparece a continuación. Durante el segundo y tercer días de la creación, Dios dio forma al universo; durante los tres días siguientes, Dios llenó la tierra con seres vivientes. &quot;Las tinieblas[...] sobre la faz del abismo&quot;, se disiparon el primer día cuando Dios creó la luz.
1.2 La imagen del Espíritu de Dios que se movía sobre la faz de las aguas es similar a un pájaro que protege a sus polluelos (véanse Deu 32:11-12; Isa 31:5). El Espíritu de Dios estaba activamente involucrado en la creación del mundo (véanse Job 33:4; Psa 104:30). Su cuidado y protección siguen estando activos.
1.3-2.7 ¿Cuánto tiempo le tomó a Dios crear el mundo? Hay dos puntos de vista respecto de los días de la creación: (1) cada día fue un período literal de veinticuatro horas; (2) cada día representa un período indefinido (hasta millones de años).
La Biblia no aclara cuál teoría es la correcta. Pero la pregunta real no es cuánto tiempo le tomó a Dios, sino cómo lo hizo. Dios creó al mundo de una manera ordenada (no creó las plantas antes que la luz); y creó al hombre y a la mujer como seres singulares capaces de comunicarse con El. Ninguna otra parte de la creación puede reclamar ese maravilloso privilegio. El punto importante no es cuánto tiempo le tomó a Dios crear el mundo, ya sean unos pocos días o unos pocos miles de millones de años, sino que lo creó tal cual quiso hacerlo.
1.6 La &quot;expansión en medio de las aguas&quot; era una separación entre el mar y el vaho del cielo.
1.25 Dios vio que su obra era buena. En ocasiones, la gente se siente culpable por pasar un rato agradable o por sentirse bien por un logro. Esto no debe ser así. Así como Dios estaba complacido con su obra, podemos estar complacidos con las nuestras. Sin embargo, no podemos estar complacidos con nuestra obra si Dios no lo está también. ¿Qué está haciendo usted que haga feliz tanto a Dios como a usted mismo?
1.26 ¿Por qué Dios empleó la forma plural cuando dijo &quot;Hagamos al hombre a nuestra imagen&quot;? Una perspectiva dice que está haciendo referencia a la Trinidad -Dios, el Padre; Jesucristo, su Hijo; y el Espíritu Santo- todos los cuales son Dios. Otra perspectiva afirma que el plural se utiliza para denotar majestuosidad. Tradicionalmente los reyes utilizan la forma plural al hablar de ellos mismos. De Job 33:4 y Psa 104:30 sabemos que el Espíritu de Dios estaba presente en la creación. De Col 1:16 sabemos que Cristo, el Hijo de Dios, estaba trabajando en la creación.
1.26 ¿Cómo es que somos hechos a semejanza de Dios? Obviamente, Dios no nos creó exactamente como El, porque Dios no tiene cuerpo físico. En cambio, somos reflejo de la gloria de Dios. Algunos piensan que nuestro raciocinio, creatividad, poder de comunicación o autodeterminación es la imagen de Dios. Más bien, es todo nuestro ser el que refleja la imagen de Dios. Nunca llegaremos a ser totalmente iguales a Dios, porque El es nuestro Creador supremo. Pero sí tenemos la capacidad de reflejar su carácter en nuestro amor, paciencia, perdón, bondad y fidelidad.
El saber que fuimos creados a semejanza de Dios y por lo tanto poseemos muchas de sus características, nos proporciona una base sólida para nuestra autoestima. Nuestro valor no se basa en posesiones, logros, atractivo físico o reconocimiento público. En cambio se fundamenta en el hecho de haber sido creados a semejanza de Dios. Debido a que somos semejantes a Dios podemos tener sentimientos positivos acerca de nosotros mismos. El criticarnos o degradarnos equivale a criticar lo que Dios ha hecho. Saber que usted es una persona que tiene valor le da la libertad de amar a Dios, de conocerlo personalmente y de hacer una contribución valiosa a aquellos que lo rodean.
1.27 Dios hizo tanto al hombre como a la mujer a su imagen. Ninguno de los dos fue hecho más a la imagen de Dios que el otro. Desde el principio vemos que la Biblia coloca tanto a uno como al otro en el pináculo de la creación de Dios. Ninguno de los sexos es exaltado ni despreciado.
1.28 Señorear significa ejercer absoluta autoridad y control sobre algo. Dios es quien en última instancia gobierna la tierra y ejerce su autoridad con cuidado amoroso. Cuando Dios delegó parte de su autoridad a la especie humana, esperaba que nos hiciésemos responsables del medio y de las otras criaturas que comparten nuestro planeta. No debemos ser descuidados ni derrochadores al llevar a cabo la tarea encomendada. Dios fue cuidadoso al crear la tierra. No debemos ser negligentes al atender de ella.
1.31 Dios observó que lo que había hecho era muy bueno. Usted es parte de la creación de Dios y El está complacido por la manera en que lo creó. Si en ocasiones siente que carece de valor o que vale poco, recuerde que Dios lo creó por una buena razón. Usted es valioso para él.
DIAS DE LA CREACION
Primer día: Luz (así que hubo luz y oscuridad)
Segundo día: Cielo y agua (se separaron las aguas)
Tercer día: Mar y tierra (se juntaron las aguas); vegetación
Cuarto día: Sol, luna y estrellas (para regir sobre el día y la noche, para dar origen a las estaciones, señalar los días y los años)
Quinto día: Peces y aves (para llenar las aguas y el cielo)
Sexto día: Animales (para llenar la tierra). Hombre y mujer (para cuidar la tierra y tener comunión con Dios)
Séptimo día: Dios descansó y declaró que todo lo que había hecho era muy bueno
PRINCIPIOS
La Biblia no aborda el tema de la evolución. Más bien su cosmovisión da por sentado que Dios lo creó. El punto de vista bíblico de la creación no está en conflicto con la ciencia, pero sí está en conflicto con cualquier cosmovisión que principie sin un creador.
Igualmente los cristianos comprometidos y sinceros han tenido que luchar con este tema del origen de las cosas y han llegado a conclusiones diversas. Por supuesto, esto es de esperarse ya que la evidencia es muy antigua y, debido a los estragos de las generaciones, muy fragmentada. Los estudiosos de la Biblia y de la ciencia deben evitar polarizaciones y pensamientos extremistas. Los primeros deben tener cuidado de no hacer que la Biblia diga cosas que no dice, así como los segundos no deben forzar a la ciencia a decir cosas que tampoco dice.
El aspecto más importante de esta discusión continua no es el proceso de la creación, sino el origen de la creación. El mundo no es un producto de la casualidad ni de la probabilidad; Dios lo creó.
La Biblia no sólo nos dice que Dios creó el mundo; más importante aún, nos dice quién es ese Dios. Nos revela la personalidad de Dios, su carácter y su plan para la creación. Además nos revela el deseo más profundo de Dios: relacionarse y tener comunión con la gente por medio de su visita histórica a este planeta en la persona de Su Hijo Jesucristo. Podemos conocer de una forma muy personal a este Dios que creó el universo.
Los cielos y la tierra están aquí. Nosotros estamos aquí. Dios creó todo lo que vemos y experimentamos. El libro de Génesis comienza, &quot;En el principio creó Dios los cielos y la tierra&quot;.
Aquí comenzamos la más emocionante y plena de todas las aventuras.</p>
<br/>




</div>
