<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">La caída. La prístina inocencia del Edén fue abruptamente arruinada por la entrada del pecado. Los errores de Adán y Eva son típicos de todos los pecados, pero siendo ellos los padres de la humanidad sus hechos tuvieron graves consecuencias. La tentación fue comunicada por una serpiente, que en Lev. 11:31 se describe como una criatura inmunda y, por lo tanto, un símbolo apro piado para el mal. La serpiente comienza sobreenfatizando lo estricto de la ley (Dios había puesto sólo un árbol en prohibición) y poniendo en duda la buena voluntad de Dios para con los seres humanos (algo que la narrativa del cap. 2 había puesto más allá de toda duda). Eva refuta sus insinuaciones, si bien en términos inexactos (ni lo toquéis no fue parte de la prohibición original 2:17). Luego la serpiente desafió la sentencia de Dios cuando dice ciertamente no moriréis y a cambio promete sofisticado avance (vuestros ojos serán abiertos) y también progreso espiritual (y seréis como Dios).
Atraída por la perspectiva de placer instantáneo (vio que el árbol era bueno para comer) y de una supuesta madurez, súbitamente sucumbió y persuadió a su marido para que también comiese. Al hacer esto él prefirió la sugerencia de la serpiente que el mandato de Dios. (A través de la Escritura, la esencia del pecado es poner el juicio humano por encima del mandamiento de Dios.) En forma inmediata tanto la culpabilidad como la vergüenza hicieron presa de ellos. Lo único que vieron con sus ojos abiertos fue su propia desnudez, la que pretendieron esconder el uno del otro y de Dios.</p>
<br/>
<p class="text-justify">Juicio y sentencia. El hombre, la mujer y la serpiente fueron interrogados y sentenciados por el inquisidor divino. Las preguntas de Dios estaban diseñadas con el propósito de sacar una confesión, no información; él sabía perfectamente lo que ellos habían hecho.
Los efectos a largo plazo del pecado comenzaron a aparecer. La serpiente fue condenada a arrastrarse sobre su vientre y tener una constante guerra con la humanidad, la descendencia de la mujer (15). La descendencia de ella herirá en la cabeza a la serpiente, y ésta saldrá peor en la gran batalla. Si bien esto fue el juicio sobre la serpiente, se transformó a la vez en una promesa para el hombre. Esto ha sido visto tradicionalmente por los judíos y los cristianos como el primer anuncio de un salvador para la humanidad, y 3:15 siempre ha sido llamado el protoevangelio o el “primer evangelio”. Las alusiones a esto en el NT incluyen Rom. 16:20; Heb. 2:14; Apoc. 12. En Gén. la promesa a Abraham que “en tu descendencia serán benditas todas las naciones de la tierra” (22:18) comienza a hacer más específica la tenue promesa del 3:15. También es notable que este primer juicio sobre el pecado esté matizado con esperanza, algo que es recurrente a través de las Escrituras (cf. 6:5-8), así como la misericordia de Dios excede a su ira (cf. Exo. 20:5, 6).
La sentencia sobre Eva arruinó su vocación de madre. Ser la madre jubilosa de muchos hijos era la esperanza de cada mujer del AT (30:1; Sal. 113:9), pero el dolor al dar a luz se transformó en un recordatorio constante del pecado de la primera madre. Además, el matrimonio, en vez de ser una relación de cuidado mutuo, a menudo tuvo la tensión como su característica. Tu deseo puede ser o el deseo sexual o el deseo de independencia, pero a la larga prevalecerá el señorío de su marido. Y él se enseñoreará de ti puede indicar el ejercicio de dominio duro, o simplemente puede ser una reafirmación de la cadena de autoridad (Dios-hombre-mujer) establecida en la creación, pero revertida en la caída (6). Esta última pareciera ser la interpretación más apropiada, especialmente si se tiene en cuenta la forma en que es introducida la sentencia a Adán porque obedeciste la voz de tu mujer (17). Entonces Dios decretó que el hombre sufriría frustración en su trabajo (hortelanos y agricultores enfrentan una continua batalla con las malezas en la producción de sus tierras). Con trabajo duro viviría, pero finalmente moriría. Esto era un indicio de que él sería expulsado del Edén y privado de acceso al árbol de la vida.</p>
<br/>
<p class="text-justify">El juicio. La expulsión del huerto probó la falsedad de la promesa de la serpiente en el sentido de que no morirían (4). Porque si bien Adán y Eva siguieron viviendo fuera del huerto, esto era una simple sombra de la vida plena que vivieron dentro del huerto, en donde disfrutaron de una íntima relación con Dios. A estas alturas es evidente el costo total del pecado. No es sólo una conciencia inquieta (7, 8), disputas con la amada esposa (12), dolor (16) o el afán por las cosas diarias (17-19), sino que además es separación de la presen cia de Dios y finalmente la muerte física (Rom. 6:23). Los querubines más tarde adornarían el arca, el tabernáculo y el templo (Exo. 25:18-22; 26:31; 1 Rey. 6:23-28), eran seres alados con dos ros tros, uno de hombre y el otro de león (Eze. 41:18).</p>
<br/>
<p class="text-justify">La caída. La prístina inocencia del Edén fue abruptamente arruinada por la entrada del pecado. Los errores de Adán y Eva son típicos de todos los pecados, pero siendo ellos los padres de la humanidad sus hechos tuvieron graves consecuencias. La tentación fue comunicada por una serpiente, que en Lev. 11:31 se describe como una criatura inmunda y, por lo tanto, un símbolo apro piado para el mal. La serpiente comienza sobreenfatizando lo estricto de la ley (Dios había puesto sólo un árbol en prohibición) y poniendo en duda la buena voluntad de Dios para con los seres humanos (algo que la narrativa del cap. 2 había puesto más allá de toda duda). Eva refuta sus insinuaciones, si bien en términos inexactos (ni lo toquéis no fue parte de la prohibición original 2:17). Luego la serpiente desafió la sentencia de Dios cuando dice ciertamente no moriréis y a cambio promete sofisticado avance (vuestros ojos serán abiertos) y también progreso espiritual (y seréis como Dios).
Atraída por la perspectiva de placer instantáneo (vio que el árbol era bueno para comer) y de una supuesta madurez, súbitamente sucumbió y persuadió a su marido para que también comiese. Al hacer esto él prefirió la sugerencia de la serpiente que el mandato de Dios. (A través de la Escritura, la esencia del pecado es poner el juicio humano por encima del mandamiento de Dios.) En forma inmediata tanto la culpabilidad como la vergüenza hicieron presa de ellos. Lo único que vieron con sus ojos abiertos fue su propia desnudez, la que pretendieron esconder el uno del otro y de Dios.</p>
<br/>
<p class="text-justify">Juicio y sentencia. El hombre, la mujer y la serpiente fueron interrogados y sentenciados por el inquisidor divino. Las preguntas de Dios estaban diseñadas con el propósito de sacar una confesión, no información; él sabía perfectamente lo que ellos habían hecho.
Los efectos a largo plazo del pecado comenzaron a aparecer. La serpiente fue condenada a arrastrarse sobre su vientre y tener una constante guerra con la humanidad, la descendencia de la mujer (15). La descendencia de ella herirá en la cabeza a la serpiente, y ésta saldrá peor en la gran batalla. Si bien esto fue el juicio sobre la serpiente, se transformó a la vez en una promesa para el hombre. Esto ha sido visto tradicionalmente por los judíos y los cristianos como el primer anuncio de un salvador para la humanidad, y 3:15 siempre ha sido llamado el protoevangelio o el “primer evangelio”. Las alusiones a esto en el NT incluyen Rom. 16:20; Heb. 2:14; Apoc. 12. En Gén. la promesa a Abraham que “en tu descendencia serán benditas todas las naciones de la tierra” (22:18) comienza a hacer más específica la tenue promesa del 3:15. También es notable que este primer juicio sobre el pecado esté matizado con esperanza, algo que es recurrente a través de las Escrituras (cf. 6:5-8), así como la misericordia de Dios excede a su ira (cf. Exo. 20:5, 6).
La sentencia sobre Eva arruinó su vocación de madre. Ser la madre jubilosa de muchos hijos era la esperanza de cada mujer del AT (30:1; Sal. 113:9), pero el dolor al dar a luz se transformó en un recordatorio constante del pecado de la primera madre. Además, el matrimonio, en vez de ser una relación de cuidado mutuo, a menudo tuvo la tensión como su característica. Tu deseo puede ser o el deseo sexual o el deseo de independencia, pero a la larga prevalecerá el señorío de su marido. Y él se enseñoreará de ti puede indicar el ejercicio de dominio duro, o simplemente puede ser una reafirmación de la cadena de autoridad (Dios-hombre-mujer) establecida en la creación, pero revertida en la caída (6). Esta última pareciera ser la interpretación más apropiada, especialmente si se tiene en cuenta la forma en que es introducida la sentencia a Adán porque obedeciste la voz de tu mujer (17). Entonces Dios decretó que el hombre sufriría frustración en su trabajo (hortelanos y agricultores enfrentan una continua batalla con las malezas en la producción de sus tierras). Con trabajo duro viviría, pero finalmente moriría. Esto era un indicio de que él sería expulsado del Edén y privado de acceso al árbol de la vida.</p>
<br/>
<p class="text-justify">El juicio. La expulsión del huerto probó la falsedad de la promesa de la serpiente en el sentido de que no morirían (4). Porque si bien Adán y Eva siguieron viviendo fuera del huerto, esto era una simple sombra de la vida plena que vivieron dentro del huerto, en donde disfrutaron de una íntima relación con Dios. A estas alturas es evidente el costo total del pecado. No es sólo una conciencia inquieta (7, 8), disputas con la amada esposa (12), dolor (16) o el afán por las cosas diarias (17-19), sino que además es separación de la presen cia de Dios y finalmente la muerte física (Rom. 6:23). Los querubines más tarde adornarían el arca, el tabernáculo y el templo (Exo. 25:18-22; 26:31; 1 Rey. 6:23-28), eran seres alados con dos ros tros, uno de hombre y el otro de león (Eze. 41:18).</p>
<br/>
<p class="text-justify">La caída. La prístina inocencia del Edén fue abruptamente arruinada por la entrada del pecado. Los errores de Adán y Eva son típicos de todos los pecados, pero siendo ellos los padres de la humanidad sus hechos tuvieron graves consecuencias. La tentación fue comunicada por una serpiente, que en Lev. 11:31 se describe como una criatura inmunda y, por lo tanto, un símbolo apro piado para el mal. La serpiente comienza sobreenfatizando lo estricto de la ley (Dios había puesto sólo un árbol en prohibición) y poniendo en duda la buena voluntad de Dios para con los seres humanos (algo que la narrativa del cap. 2 había puesto más allá de toda duda). Eva refuta sus insinuaciones, si bien en términos inexactos (ni lo toquéis no fue parte de la prohibición original 2:17). Luego la serpiente desafió la sentencia de Dios cuando dice ciertamente no moriréis y a cambio promete sofisticado avance (vuestros ojos serán abiertos) y también progreso espiritual (y seréis como Dios).
Atraída por la perspectiva de placer instantáneo (vio que el árbol era bueno para comer) y de una supuesta madurez, súbitamente sucumbió y persuadió a su marido para que también comiese. Al hacer esto él prefirió la sugerencia de la serpiente que el mandato de Dios. (A través de la Escritura, la esencia del pecado es poner el juicio humano por encima del mandamiento de Dios.) En forma inmediata tanto la culpabilidad como la vergüenza hicieron presa de ellos. Lo único que vieron con sus ojos abiertos fue su propia desnudez, la que pretendieron esconder el uno del otro y de Dios.</p>
<br/>
<p class="text-justify">Juicio y sentencia. El hombre, la mujer y la serpiente fueron interrogados y sentenciados por el inquisidor divino. Las preguntas de Dios estaban diseñadas con el propósito de sacar una confesión, no información; él sabía perfectamente lo que ellos habían hecho.
Los efectos a largo plazo del pecado comenzaron a aparecer. La serpiente fue condenada a arrastrarse sobre su vientre y tener una constante guerra con la humanidad, la descendencia de la mujer (15). La descendencia de ella herirá en la cabeza a la serpiente, y ésta saldrá peor en la gran batalla. Si bien esto fue el juicio sobre la serpiente, se transformó a la vez en una promesa para el hombre. Esto ha sido visto tradicionalmente por los judíos y los cristianos como el primer anuncio de un salvador para la humanidad, y 3:15 siempre ha sido llamado el protoevangelio o el “primer evangelio”. Las alusiones a esto en el NT incluyen Rom. 16:20; Heb. 2:14; Apoc. 12. En Gén. la promesa a Abraham que “en tu descendencia serán benditas todas las naciones de la tierra” (22:18) comienza a hacer más específica la tenue promesa del 3:15. También es notable que este primer juicio sobre el pecado esté matizado con esperanza, algo que es recurrente a través de las Escrituras (cf. 6:5-8), así como la misericordia de Dios excede a su ira (cf. Exo. 20:5, 6).
La sentencia sobre Eva arruinó su vocación de madre. Ser la madre jubilosa de muchos hijos era la esperanza de cada mujer del AT (30:1; Sal. 113:9), pero el dolor al dar a luz se transformó en un recordatorio constante del pecado de la primera madre. Además, el matrimonio, en vez de ser una relación de cuidado mutuo, a menudo tuvo la tensión como su característica. Tu deseo puede ser o el deseo sexual o el deseo de independencia, pero a la larga prevalecerá el señorío de su marido. Y él se enseñoreará de ti puede indicar el ejercicio de dominio duro, o simplemente puede ser una reafirmación de la cadena de autoridad (Dios-hombre-mujer) establecida en la creación, pero revertida en la caída (6). Esta última pareciera ser la interpretación más apropiada, especialmente si se tiene en cuenta la forma en que es introducida la sentencia a Adán porque obedeciste la voz de tu mujer (17). Entonces Dios decretó que el hombre sufriría frustración en su trabajo (hortelanos y agricultores enfrentan una continua batalla con las malezas en la producción de sus tierras). Con trabajo duro viviría, pero finalmente moriría. Esto era un indicio de que él sería expulsado del Edén y privado de acceso al árbol de la vida.</p>
<br/>
<p class="text-justify">El juicio. La expulsión del huerto probó la falsedad de la promesa de la serpiente en el sentido de que no morirían (4). Porque si bien Adán y Eva siguieron viviendo fuera del huerto, esto era una simple sombra de la vida plena que vivieron dentro del huerto, en donde disfrutaron de una íntima relación con Dios. A estas alturas es evidente el costo total del pecado. No es sólo una conciencia inquieta (7, 8), disputas con la amada esposa (12), dolor (16) o el afán por las cosas diarias (17-19), sino que además es separación de la presen cia de Dios y finalmente la muerte física (Rom. 6:23). Los querubines más tarde adornarían el arca, el tabernáculo y el templo (Exo. 25:18-22; 26:31; 1 Rey. 6:23-28), eran seres alados con dos ros tros, uno de hombre y el otro de león (Eze. 41:18).</p>
<br/>




</div>
