<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 2</h2>
<p class="text-justify">El santo día séptimo
Un cambio dramático en la marcha y en el estilo sobresale como lo distintivo del sábado. El séptimo día no es llamado aquí sábado, pero así es referido, desde que en él reposó puede ser parafraseado como “en el sabático”. Por otro lado, la importancia del séptimo día es destacada por el hecho de que Dios lo bendice y lo hace santo. El sábado gene ralmente es declarado “santo”, pero sólo en Neh. 8:9, 11 es considerado como entre las demás festividades del pueblo y es llamado “santo”. Aquí se nos dice que Dios reposó en el séptimo día, y el es critor claramente sugiere que toda la humanidad, que ha sido hecha a la imagen de Dios, siga el ejemplo de su Creador. En verdad, el contexto sugiere que un día a la semana para descansar es tan necesario como la sexualidad (1:27, 28) o la comida (1:29) para la sobrevivencia humana. Este es un énfasis que parece haber sido olvidado en el día de hoy, aun entre los cristianos.
Nota. Génesis 1 y la ciencia. Gén. y la ciencia moderna están respondiendo a muchas preguntas. Gén. explica quién es Dios y cómo se relaciona con la creación. La ciencia clarifica que las leyes dadas por Dios explican los fenómenos naturales; y a partir de estas leyes los científicos pueden trabajar hacia el pasado con el propósito de trazar el curso del desarrollo del universo. La ciencia nos ha ce conscientes del poder infinito y de la sabiduría del Creador, pero no explica el propósito de Dios al crear el universo, o su carácter. Gén. no está interesado en tratar los asuntos que levantan los científicos del siglo XX sino más bien está relacionado con las ideas contemporáneas del antiguo Oriente de hace 3.000 años. En contra de la visión politeísta del mundo que sostenía que había muchos dioses y diosas de variada sabiduría y poder, Gén. declara que hay un solo Dios de absoluto poder y santidad. Rechazando esos puntos de vista antiguos que postulaban que la humanidad fue simplemente creada como consecuencia de un pensamiento tardío que los dioses más tarde lamentaron, Gén. afirma que el hombre fue la meta de la creación y que su bienestar es la preocupación suprema de Dios. Estos principios son reafirmados con reiteración a través de toda la Escritura, pero están des tacados con ejemplar claridad en Gén. 1 y son clave en lo que el autor estaba tratando de decir. Los lectores modernos debieran centrarse en estas intenciones originales de Gén. y no traer al texto temas científicos que son ajenos a su propósito.</p>
<br/>
<p class="text-justify">La creación del primer hombre. El escritor mira hacia atrás al momento previo en que fue creada la humanidad en el día sexto (1:26-28) y describe un desierto típico del Medio Oriente, el cual requiere de esfuerzos humanos para regarlo y hacerlo germinar. Fue del polvo de esa área que Dios, el gran Alfarero, moldeó al primer hombre y sopló en él aliento de vida. A través de esta imagen Gén. establece que la gente es por naturaleza más que materia; también tienen composición espiritual, dada por Dios.</p>
<br/>
<p class="text-justify">El huerto de Dios para la humanidad. La preocupación de Dios por la necesidad humana, ya mencionada en 1:29, es nuevamente destacada aquí. Un hermoso huerto lleno de árboles frutales, ríos, oro y piedras preciosas es preparado para morada del hombre en el área llamada Edén (eso es, “hermoso”). Arboles, agua, oro y piedras preciosas y querubines también adornarían más tarde el tabernáculo (Exo. 25:27) y el templo (1 Rey. 7; Eze. 41-47), y estos símbolos sugieren que lo más importante en el huerto era la presencia de Dios. El acostumbraba a pasearse allí en lo fresco del día teniendo conversaciones íntimas con Adán y Eva (3:8). El árbol de la vida da vida eterna y el árbol del conocimiento del bien y del mal da sabiduría. De este último le fue prohibido al hombre su consumo porque la sabiduría adquirida a través del comer conduce a la independencia del hombre con respecto a Dios, mientras que la verdadera sabiduría comienza con “el temor del Señor” (Prov. 1:7).
Nota. 10-14. Dos de los ríos del Edén son bien conocidos: el Tigris y el Eufrates corren a través del Iraq moderno para desembocar en el golfo Pérsico. El Guijón y el Pisón son imposibles de identificar, por ende el intento de ubicar el Edén está condenado al fracaso. La mitología mesopotámica ubica una isla paradisíaca en el inicio del golfo Pérsico y, por lo tanto, la explicación más probable es que el Edén estuviera allí. Esto sería así si consideramos la historia lit., porque en 3:23, 24 se deja muy claro que los hombres no pueden regresar al Edén.</p>
<br/>
<p class="text-justify">La creación de la mujer. A pesar del ambiente idílico algo no estaba bien. Dios dijo: No es bueno que el hombre esté solo (18), y después de reiterar su observación en el sentido de que todo lo que él había creado era bueno (p. ej. 1:10, 31) este comentario es una sorpresa y sirve para destacar el siguiente acto creador.
En primer lugar, los animales fueron creados como compañeros del hombre. Estaban sujetos a la autoridad humana (según el v. 20, el hombre les puso nombres), pero la intención de Dios excluía la explotación de ellos (cf. 1:24-31). Desafortunadamente, los animales no fueron la compañía perfecta para el hombre. Sólo la creación de la mujer fue totalmente satisfactoria para él.
El encantador relato de Dios creando a Eva de una costilla de Adán y luego presentándosela como en una escena de bodas resume en una manera hermosa muchas de las claves bíblicas acerca del matrimonio. Aquí como en 1:27, 28 tenemos la norma de Dios para la relación que debe existir entre los sexos. Mientras que en 1:28 se enfatiza la importancia de la procreación, 2:20-24 explora la naturaleza del compañerismo dentro del matrimonio. Pri mero, el marido y la mujer se complementan el uno al otro. Ayuda idónea sería mejor traducido como “ayudante que armoniza con él”, eso es, supliendo lo que le falta. Ella es “su costilla perdida”. Matthew Henry comentó sobre la elección que Dios hizo de una costilla para crear a Eva: “No la hizo de su cabeza para que estuviera encima de él, tampoco la hizo de sus pies para que fuese pisoteada, la hizo de su costado para que fuese igual a él, de debajo de su brazo para que fuese protegida, y cerca de su corazón para que fuese amada.” Es posible que esto sea demasiada lectura para una sola costilla, pero expresa muy bien el ideal bíblico para el matrimonio.
Segundo, la unión entre el hombre y la mujer debe ser permanente: el hombre se unirá (lit. “pegado”) a su mujer, y serán una sola carne. Jesús (Mat. 19:5) y Pablo (Ef. 5:31) citan este pasaje al referirse al tema del divorcio.
Tercero, el hombre debe dar prioridad a su esposa por sobre todas las cosas, aun de sus padres. El dejará a su padre y a su madre, no por ir a vivir a otro lugar sino poniendo este importante deber de cuidar por ellos (Exo. 20:12) en segundo lugar en relación con su deber con su cónyuge (cf. Ef. 5:25-29).
Cuarto, la mujer está bajo la autoridad de su marido: el la llama Mujer (23) y más tarde Eva (3:20), en la misma forma como anteriormente él le puso nombre a los animales (19). Este concepto del hombre como cabeza de la mujer se da por sentado en el resto de la Biblia (p. ej. 1 Cor. 11:3; 1 Ped. 3:1-6).
Finalmente, se debe destacar que Dios creó una sola Eva para Adán, no muchas Evas como tampoco otro Adán. Esto indica la desaprobación de Dios de la poligamia (cf. Lev. 18:18; Deut. 17:17) y de la práctica de la homosexualidad (Lev. 18:22; Rom. 1:26, 27).</p>
<br/>
<p class="text-justify">El santo día séptimo
Un cambio dramático en la marcha y en el estilo sobresale como lo distintivo del sábado. El séptimo día no es llamado aquí sábado, pero así es referido, desde que en él reposó puede ser parafraseado como “en el sabático”. Por otro lado, la importancia del séptimo día es destacada por el hecho de que Dios lo bendice y lo hace santo. El sábado gene ralmente es declarado “santo”, pero sólo en Neh. 8:9, 11 es considerado como entre las demás festividades del pueblo y es llamado “santo”. Aquí se nos dice que Dios reposó en el séptimo día, y el es critor claramente sugiere que toda la humanidad, que ha sido hecha a la imagen de Dios, siga el ejemplo de su Creador. En verdad, el contexto sugiere que un día a la semana para descansar es tan necesario como la sexualidad (1:27, 28) o la comida (1:29) para la sobrevivencia humana. Este es un énfasis que parece haber sido olvidado en el día de hoy, aun entre los cristianos.
Nota. Génesis 1 y la ciencia. Gén. y la ciencia moderna están respondiendo a muchas preguntas. Gén. explica quién es Dios y cómo se relaciona con la creación. La ciencia clarifica que las leyes dadas por Dios explican los fenómenos naturales; y a partir de estas leyes los científicos pueden trabajar hacia el pasado con el propósito de trazar el curso del desarrollo del universo. La ciencia nos ha ce conscientes del poder infinito y de la sabiduría del Creador, pero no explica el propósito de Dios al crear el universo, o su carácter. Gén. no está interesado en tratar los asuntos que levantan los científicos del siglo XX sino más bien está relacionado con las ideas contemporáneas del antiguo Oriente de hace 3.000 años. En contra de la visión politeísta del mundo que sostenía que había muchos dioses y diosas de variada sabiduría y poder, Gén. declara que hay un solo Dios de absoluto poder y santidad. Rechazando esos puntos de vista antiguos que postulaban que la humanidad fue simplemente creada como consecuencia de un pensamiento tardío que los dioses más tarde lamentaron, Gén. afirma que el hombre fue la meta de la creación y que su bienestar es la preocupación suprema de Dios. Estos principios son reafirmados con reiteración a través de toda la Escritura, pero están des tacados con ejemplar claridad en Gén. 1 y son clave en lo que el autor estaba tratando de decir. Los lectores modernos debieran centrarse en estas intenciones originales de Gén. y no traer al texto temas científicos que son ajenos a su propósito.</p>
<br/>
<p class="text-justify">La creación del primer hombre. El escritor mira hacia atrás al momento previo en que fue creada la humanidad en el día sexto (1:26-28) y describe un desierto típico del Medio Oriente, el cual requiere de esfuerzos humanos para regarlo y hacerlo germinar. Fue del polvo de esa área que Dios, el gran Alfarero, moldeó al primer hombre y sopló en él aliento de vida. A través de esta imagen Gén. establece que la gente es por naturaleza más que materia; también tienen composición espiritual, dada por Dios.</p>
<br/>
<p class="text-justify">El huerto de Dios para la humanidad. La preocupación de Dios por la necesidad humana, ya mencionada en 1:29, es nuevamente destacada aquí. Un hermoso huerto lleno de árboles frutales, ríos, oro y piedras preciosas es preparado para morada del hombre en el área llamada Edén (eso es, “hermoso”). Arboles, agua, oro y piedras preciosas y querubines también adornarían más tarde el tabernáculo (Exo. 25:27) y el templo (1 Rey. 7; Eze. 41-47), y estos símbolos sugieren que lo más importante en el huerto era la presencia de Dios. El acostumbraba a pasearse allí en lo fresco del día teniendo conversaciones íntimas con Adán y Eva (3:8). El árbol de la vida da vida eterna y el árbol del conocimiento del bien y del mal da sabiduría. De este último le fue prohibido al hombre su consumo porque la sabiduría adquirida a través del comer conduce a la independencia del hombre con respecto a Dios, mientras que la verdadera sabiduría comienza con “el temor del Señor” (Prov. 1:7).
Nota. 10-14. Dos de los ríos del Edén son bien conocidos: el Tigris y el Eufrates corren a través del Iraq moderno para desembocar en el golfo Pérsico. El Guijón y el Pisón son imposibles de identificar, por ende el intento de ubicar el Edén está condenado al fracaso. La mitología mesopotámica ubica una isla paradisíaca en el inicio del golfo Pérsico y, por lo tanto, la explicación más probable es que el Edén estuviera allí. Esto sería así si consideramos la historia lit., porque en 3:23, 24 se deja muy claro que los hombres no pueden regresar al Edén.</p>
<br/>
<p class="text-justify">La creación de la mujer. A pesar del ambiente idílico algo no estaba bien. Dios dijo: No es bueno que el hombre esté solo (18), y después de reiterar su observación en el sentido de que todo lo que él había creado era bueno (p. ej. 1:10, 31) este comentario es una sorpresa y sirve para destacar el siguiente acto creador.
En primer lugar, los animales fueron creados como compañeros del hombre. Estaban sujetos a la autoridad humana (según el v. 20, el hombre les puso nombres), pero la intención de Dios excluía la explotación de ellos (cf. 1:24-31). Desafortunadamente, los animales no fueron la compañía perfecta para el hombre. Sólo la creación de la mujer fue totalmente satisfactoria para él.
El encantador relato de Dios creando a Eva de una costilla de Adán y luego presentándosela como en una escena de bodas resume en una manera hermosa muchas de las claves bíblicas acerca del matrimonio. Aquí como en 1:27, 28 tenemos la norma de Dios para la relación que debe existir entre los sexos. Mientras que en 1:28 se enfatiza la importancia de la procreación, 2:20-24 explora la naturaleza del compañerismo dentro del matrimonio. Pri mero, el marido y la mujer se complementan el uno al otro. Ayuda idónea sería mejor traducido como “ayudante que armoniza con él”, eso es, supliendo lo que le falta. Ella es “su costilla perdida”. Matthew Henry comentó sobre la elección que Dios hizo de una costilla para crear a Eva: “No la hizo de su cabeza para que estuviera encima de él, tampoco la hizo de sus pies para que fuese pisoteada, la hizo de su costado para que fuese igual a él, de debajo de su brazo para que fuese protegida, y cerca de su corazón para que fuese amada.” Es posible que esto sea demasiada lectura para una sola costilla, pero expresa muy bien el ideal bíblico para el matrimonio.
Segundo, la unión entre el hombre y la mujer debe ser permanente: el hombre se unirá (lit. “pegado”) a su mujer, y serán una sola carne. Jesús (Mat. 19:5) y Pablo (Ef. 5:31) citan este pasaje al referirse al tema del divorcio.
Tercero, el hombre debe dar prioridad a su esposa por sobre todas las cosas, aun de sus padres. El dejará a su padre y a su madre, no por ir a vivir a otro lugar sino poniendo este importante deber de cuidar por ellos (Exo. 20:12) en segundo lugar en relación con su deber con su cónyuge (cf. Ef. 5:25-29).
Cuarto, la mujer está bajo la autoridad de su marido: el la llama Mujer (23) y más tarde Eva (3:20), en la misma forma como anteriormente él le puso nombre a los animales (19). Este concepto del hombre como cabeza de la mujer se da por sentado en el resto de la Biblia (p. ej. 1 Cor. 11:3; 1 Ped. 3:1-6).
Finalmente, se debe destacar que Dios creó una sola Eva para Adán, no muchas Evas como tampoco otro Adán. Esto indica la desaprobación de Dios de la poligamia (cf. Lev. 18:18; Deut. 17:17) y de la práctica de la homosexualidad (Lev. 18:22; Rom. 1:26, 27).</p>
<br/>
<p class="text-justify">El santo día séptimo
Un cambio dramático en la marcha y en el estilo sobresale como lo distintivo del sábado. El séptimo día no es llamado aquí sábado, pero así es referido, desde que en él reposó puede ser parafraseado como “en el sabático”. Por otro lado, la importancia del séptimo día es destacada por el hecho de que Dios lo bendice y lo hace santo. El sábado gene ralmente es declarado “santo”, pero sólo en Neh. 8:9, 11 es considerado como entre las demás festividades del pueblo y es llamado “santo”. Aquí se nos dice que Dios reposó en el séptimo día, y el es critor claramente sugiere que toda la humanidad, que ha sido hecha a la imagen de Dios, siga el ejemplo de su Creador. En verdad, el contexto sugiere que un día a la semana para descansar es tan necesario como la sexualidad (1:27, 28) o la comida (1:29) para la sobrevivencia humana. Este es un énfasis que parece haber sido olvidado en el día de hoy, aun entre los cristianos.
Nota. Génesis 1 y la ciencia. Gén. y la ciencia moderna están respondiendo a muchas preguntas. Gén. explica quién es Dios y cómo se relaciona con la creación. La ciencia clarifica que las leyes dadas por Dios explican los fenómenos naturales; y a partir de estas leyes los científicos pueden trabajar hacia el pasado con el propósito de trazar el curso del desarrollo del universo. La ciencia nos ha ce conscientes del poder infinito y de la sabiduría del Creador, pero no explica el propósito de Dios al crear el universo, o su carácter. Gén. no está interesado en tratar los asuntos que levantan los científicos del siglo XX sino más bien está relacionado con las ideas contemporáneas del antiguo Oriente de hace 3.000 años. En contra de la visión politeísta del mundo que sostenía que había muchos dioses y diosas de variada sabiduría y poder, Gén. declara que hay un solo Dios de absoluto poder y santidad. Rechazando esos puntos de vista antiguos que postulaban que la humanidad fue simplemente creada como consecuencia de un pensamiento tardío que los dioses más tarde lamentaron, Gén. afirma que el hombre fue la meta de la creación y que su bienestar es la preocupación suprema de Dios. Estos principios son reafirmados con reiteración a través de toda la Escritura, pero están des tacados con ejemplar claridad en Gén. 1 y son clave en lo que el autor estaba tratando de decir. Los lectores modernos debieran centrarse en estas intenciones originales de Gén. y no traer al texto temas científicos que son ajenos a su propósito.</p>
<br/>
<p class="text-justify">La creación del primer hombre. El escritor mira hacia atrás al momento previo en que fue creada la humanidad en el día sexto (1:26-28) y describe un desierto típico del Medio Oriente, el cual requiere de esfuerzos humanos para regarlo y hacerlo germinar. Fue del polvo de esa área que Dios, el gran Alfarero, moldeó al primer hombre y sopló en él aliento de vida. A través de esta imagen Gén. establece que la gente es por naturaleza más que materia; también tienen composición espiritual, dada por Dios.</p>
<br/>
<p class="text-justify">El huerto de Dios para la humanidad. La preocupación de Dios por la necesidad humana, ya mencionada en 1:29, es nuevamente destacada aquí. Un hermoso huerto lleno de árboles frutales, ríos, oro y piedras preciosas es preparado para morada del hombre en el área llamada Edén (eso es, “hermoso”). Arboles, agua, oro y piedras preciosas y querubines también adornarían más tarde el tabernáculo (Exo. 25:27) y el templo (1 Rey. 7; Eze. 41-47), y estos símbolos sugieren que lo más importante en el huerto era la presencia de Dios. El acostumbraba a pasearse allí en lo fresco del día teniendo conversaciones íntimas con Adán y Eva (3:8). El árbol de la vida da vida eterna y el árbol del conocimiento del bien y del mal da sabiduría. De este último le fue prohibido al hombre su consumo porque la sabiduría adquirida a través del comer conduce a la independencia del hombre con respecto a Dios, mientras que la verdadera sabiduría comienza con “el temor del Señor” (Prov. 1:7).
Nota. 10-14. Dos de los ríos del Edén son bien conocidos: el Tigris y el Eufrates corren a través del Iraq moderno para desembocar en el golfo Pérsico. El Guijón y el Pisón son imposibles de identificar, por ende el intento de ubicar el Edén está condenado al fracaso. La mitología mesopotámica ubica una isla paradisíaca en el inicio del golfo Pérsico y, por lo tanto, la explicación más probable es que el Edén estuviera allí. Esto sería así si consideramos la historia lit., porque en 3:23, 24 se deja muy claro que los hombres no pueden regresar al Edén.</p>
<br/>
<p class="text-justify">La creación de la mujer. A pesar del ambiente idílico algo no estaba bien. Dios dijo: No es bueno que el hombre esté solo (18), y después de reiterar su observación en el sentido de que todo lo que él había creado era bueno (p. ej. 1:10, 31) este comentario es una sorpresa y sirve para destacar el siguiente acto creador.
En primer lugar, los animales fueron creados como compañeros del hombre. Estaban sujetos a la autoridad humana (según el v. 20, el hombre les puso nombres), pero la intención de Dios excluía la explotación de ellos (cf. 1:24-31). Desafortunadamente, los animales no fueron la compañía perfecta para el hombre. Sólo la creación de la mujer fue totalmente satisfactoria para él.
El encantador relato de Dios creando a Eva de una costilla de Adán y luego presentándosela como en una escena de bodas resume en una manera hermosa muchas de las claves bíblicas acerca del matrimonio. Aquí como en 1:27, 28 tenemos la norma de Dios para la relación que debe existir entre los sexos. Mientras que en 1:28 se enfatiza la importancia de la procreación, 2:20-24 explora la naturaleza del compañerismo dentro del matrimonio. Pri mero, el marido y la mujer se complementan el uno al otro. Ayuda idónea sería mejor traducido como “ayudante que armoniza con él”, eso es, supliendo lo que le falta. Ella es “su costilla perdida”. Matthew Henry comentó sobre la elección que Dios hizo de una costilla para crear a Eva: “No la hizo de su cabeza para que estuviera encima de él, tampoco la hizo de sus pies para que fuese pisoteada, la hizo de su costado para que fuese igual a él, de debajo de su brazo para que fuese protegida, y cerca de su corazón para que fuese amada.” Es posible que esto sea demasiada lectura para una sola costilla, pero expresa muy bien el ideal bíblico para el matrimonio.
Segundo, la unión entre el hombre y la mujer debe ser permanente: el hombre se unirá (lit. “pegado”) a su mujer, y serán una sola carne. Jesús (Mat. 19:5) y Pablo (Ef. 5:31) citan este pasaje al referirse al tema del divorcio.
Tercero, el hombre debe dar prioridad a su esposa por sobre todas las cosas, aun de sus padres. El dejará a su padre y a su madre, no por ir a vivir a otro lugar sino poniendo este importante deber de cuidar por ellos (Exo. 20:12) en segundo lugar en relación con su deber con su cónyuge (cf. Ef. 5:25-29).
Cuarto, la mujer está bajo la autoridad de su marido: el la llama Mujer (23) y más tarde Eva (3:20), en la misma forma como anteriormente él le puso nombre a los animales (19). Este concepto del hombre como cabeza de la mujer se da por sentado en el resto de la Biblia (p. ej. 1 Cor. 11:3; 1 Ped. 3:1-6).
Finalmente, se debe destacar que Dios creó una sola Eva para Adán, no muchas Evas como tampoco otro Adán. Esto indica la desaprobación de Dios de la poligamia (cf. Lev. 18:18; Deut. 17:17) y de la práctica de la homosexualidad (Lev. 18:22; Rom. 1:26, 27).</p>
<br/>




</div>
