<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">El principio de la creación
La RVA acepta el entendimiento tradicional de estos versículos, en el sentido de que describen que el primer acto creador, cuando Dios creó toda la materia (los cielos y la tierra) de la nada. Y la tierra inmediatamente después de la creación estaba sin orden y vacía, eso es, improductiva e inhabitada. De esta manera la narrativa procede a relacionar cómo en seis días Dios organizó este caos en un mundo bien ordenado como lo vemos hoy.
Algunas traducciones y comentaristas modernos entienden el v. 1 en forma diferente. Algunos lo consideran simplemente como definiendo la situación cuando Dios comenzó a crear: “En el principio cuando Dios creó … la tierra estaba sin forma … ” Otros simplemente consideran el v. 1 como un título resumen del capítulo 1. Pero ninguno de estos puntos de vista es como el que ha adoptado la RVA. “Crear” es algo que sólo Dios puede hacer (este verbo es usado sólo en relación con Dios en el AT). El demuestra su poder para crear cosas inesperadas y maravillosas (Núm. 16:30), p. ej. grandes criaturas (21), hombres y mujeres (27) y montañas (Amós 4:13).
El v. 2 describe el mundo en tinieblas y desolación, cubierto por aguas y con el misterioso Espíritu (o viento) de Dios moviéndose sobre el océano. La propuesta de un poder existente en la deidad es desarrollada más adelante en Prov. 8:22-31 y en Juan 1:1-3, en donde se habla de la “sabiduría” y “el Verbo” asistiendo en la creación.</p>
<br/>
<p class="text-justify">La creación de la luz. El oscuro mundo fue iluminado cuando Dios dijo: Sea la luz. Más precisamente, el día fue distinguido de la noche al crearse la luz. La luz es una forma de energía y puede ser producida en diferentes maneras, no sólo por el sol y las estrellas (los cuales no habían sido creados sino hasta el día cuarto). Cosmólogos contemporáneos dicen que el universo comenzó con un gran estallido ardiente, el cual debió producir una luz muy brillante. El orden comienza a aparecer y a reemplazar el oscuro caos. El refrán Dios vio que (esto) era bueno (cf. vv. 10, 12, 18, 21, 25, 31) afirma la bondad intrínseca de la creación y de su Creador.
Nota. Es posible que el orden de tarde-mañana en la frase Y fue la tarde y la mañana del primer día (cf. vv. 8, 13, 19, 23, 31) refleje el concepto hebreo del día comenzando con el atardecer y terminando con el amanecer siguiente. Lo que más importa en Gén. es que Dios trabajó durante seis “días” y descansó. Al ser estos los días de la actividad de Dios y no de la actividad humana, no es probable que deban ser considerados como días de 24 horas. Además, la palabra hebrea para “día” cubre una variedad de períodos, que van desde las horas de luz en el día (Gén. 29:7), a un día de 24 horas (Gén. 7:4), o a un período indefinido (Gén. 35:3). Que ellos fueron diferentes de los días ordinarios se muestra por el hecho de la no existencia del sol hasta el día cuarto. Otra insinuación de que la creación no tomó seis días literales es la mención de la creación de los cielos y la tierra, eso es, el universo desorganizado (1) antes que los seis días fuesen contados. Finalmente, se debe notar que 1:1-2:3, diferente a todas las otras secciones de Gén., no está encabezada por el título: “Estos son los orígenes”, que es lo que une la protohistoria (2:4-11:26) con la historia patriarcal (11:27-50:26). Todas estas diferencias indican que 1:1-2:3 sirve como una obertura para el resto del libro y que no debe ser tomada lit. como aquello que continúa. No obstante, que Dios trabajó seis días y que descansó el día séptimo (sea cual fuere el largo de sus días por medidas humanas) es un modelo para ser seguido por la humanidad.</p>
<br/>
<p class="text-justify">La separación de las aguas. Dios mostró su poder nuevamente al ponerle límites a las aguas que hasta ese momento cubrían el globo (cf. Job 38:8-11). Algunas fueron confinadas a los mares, el resto a los cielos. Las aguas de arriba fueron conservadas allí por la “bóveda” o el “firmamento” (BJ). Desde la tierra, el cielo (firmamento) parece ser una especie de cúpula que previene que las aguas caigan en forma descontrolada sobre la tierra (cf. 7:11).</p>
<br/>
<p class="text-justify">La creación de la tierra y las plantas. Aun más importante para la humanidad fue la provisión, en el tercer día, de tierra seca, en la cual ella podía vivir, y plantas para sustentar la vida (cf. 1:29-30). La variedad de plantas (11, 12) da testimonio del poder organizador de Dios, y estas distinciones no debieran ser entremezcladas (ver las normativas en contra de ciertas mezclas en Lev. 19:19; Deut. 22:9-11).</p>
<br/>
<p class="text-justify">La creación de las lumbreras celestiales. Una prueba aun más poderosa del poder creativo de Dios, y siempre pertinente para la existencia humana, son el sol, la luna y las estrellas. Contemporáneos paganos del Gén. reconocieron en estos cuerpos celestes dioses por derecho propio. Para evitar el levantamiento de cualquier sospecha en relación con el sol y la luna en el sentido de que no son otra cosa que creación de Dios, Gén. las llama simplemente lumbreras. Fueron establecidas para regular los ritmos esenciales de la vida humana sean estos la definición del día y la noche, sean estos las estaciones del año.</p>
<br/>
<p class="text-justify">La creación de los pájaros y los peces. El paralelo en la obra creadora de Dios entre los primeros tres días y los segundos tres días llega a ser más claro. En el primer día, fue creada la luz, en el día cuarto, las lumbreras celestiales; en el día segundo, el cielo y los océanos, en el día quinto, las aves y los peces. Una vez más, Gén. está enfatizando la preocupación de Dios por el orden. “Los grandes animales acuáticos” fueron reconocidos como divinos en alguno de los mitos antiguos; Gén. insiste en que ellos fueron solamente criaturas de Dios. Además, Dios quiso que tanto las aguas como el aire estuvieran llenos de criaturas, y su decreto y bendición garantizó la fertilidad de estos. Ningún rito mágico o de fertilidad fueron necesarios para asegurarla.</p>
<br/>
<p class="text-justify">La creación de los animales y la humanidad
El relato de la creación alcanza su clímax en el día sexto. Nótese cuánto más completa es la descripción del trabajo de Dios de este día que en cual quiera de los días anteriores y los paralelos con las palabras del día tercero (la tierra).
Aquí Gén. define el propósito de la humanidad y su lugar en el plan de Dios. Dios dice que el hombre ha de ser creado a nuestra imagen, conforme a nuestra semejanza. Esto significa que la humanidad, tanto el varón como la mujer, es representante de Dios en la tierra. Los reyes del antiguo Oriente fueron a menudo vistos como portadores de la imagen de sus dioses, pero Gén. afirma que cada ser humano está hecho a la imagen de Dios. El NT afirma que Cristo es “la imagen del Dios invisible” (Col. 1:15), “el resplandor de su gloria y la expresión exacta de su naturaleza” (Heb. 1:3). Semejante entendimiento de la imagen divina estaba más allá del alcance del autor humano de Gén., pero él alude a otra dimensión de ésta al comentar Hagamos al hombre a nuestra imagen (26). Aquí Dios se presenta como hablando con los ángeles, la única alusión hecha a otros seres sobrenaturales en este capítulo. Esta observación implica que el hombre es como Dios y los ángeles. (Tradicionalmente, los cristianos han visto el nosotros y el nuestro como aludiendo a las otras personas de la Trinidad. Aunque esta es una legítima y más amplia interpretación, no es el significado primario de las palabras usadas aquí.)
En segundo lugar, dado que los seres humanos son creados a la imagen de Dios ellos son sus representantes en la tierra y deben tener dominio … sobre la tierra (26). El Sal. 8:4-8 ofrece un maravilloso comentario poético sobre el tema. Dominio implica señorío pero no explotación. El hombre, como representante de Dios, debe dominar a los que le están subordinados, como Dios lo hace, para el propio beneficio de ellos. Mientras se legitimiza el uso humano de los recursos naturales, Dios no da licencia para nuestro abuso de su creación.
En tercer lugar, Dios deliberadamente creó la humanidad en dos sexos y dijo: sed fecundos y multiplicaos. En relación con esto él bendijo la actividad sexual e indicó su importancia en su plan. Otras historias antiguas, surgiendo de la Mesopotamia urbana (cuya preocupación estaba en la explosión demográfica) cuentan de los dioses dando pasos para frenar la fertilidad humana a través del envío de plagas, hambre, inundaciones y abortos. El Dios del Gén. exhorta reiteradas veces a la primera pareja el ser fructíferos (1:28; 8:17; 9:1, 7) y le prometió a los patriarcas que llegarían a ser padres de una innumerable cantidad de hijos. Por lo tanto, la sexualidad es vista como una parte importante de la creación misma de Dios (31).
En cuarto lugar, Dios proveyó comida para la humanidad en la forma de planta que da semilla y todo árbol cuyo fruto lleva semilla (29). No fue sino hasta después del diluvio que el comer carne fue sancionado (9:1-3). Sin embargo, Gén. no está interesado en mostrar si los primeros habitantes fueron vegetarianos o no, sino más bien en el hecho que Dios les proveyó comida. En la mitología mesopotámica los dioses crearon al hombre para proveerse a sí mismos de comida; Gén. afirma precisamente lo contrario, que Dios alimenta a la humanidad (cf. Sal. 65; 50:7-15).</p>
<br/>
<p class="text-justify">El principio de la creación
La RVA acepta el entendimiento tradicional de estos versículos, en el sentido de que describen que el primer acto creador, cuando Dios creó toda la materia (los cielos y la tierra) de la nada. Y la tierra inmediatamente después de la creación estaba sin orden y vacía, eso es, improductiva e inhabitada. De esta manera la narrativa procede a relacionar cómo en seis días Dios organizó este caos en un mundo bien ordenado como lo vemos hoy.
Algunas traducciones y comentaristas modernos entienden el v. 1 en forma diferente. Algunos lo consideran simplemente como definiendo la situación cuando Dios comenzó a crear: “En el principio cuando Dios creó … la tierra estaba sin forma … ” Otros simplemente consideran el v. 1 como un título resumen del capítulo 1. Pero ninguno de estos puntos de vista es como el que ha adoptado la RVA. “Crear” es algo que sólo Dios puede hacer (este verbo es usado sólo en relación con Dios en el AT). El demuestra su poder para crear cosas inesperadas y maravillosas (Núm. 16:30), p. ej. grandes criaturas (21), hombres y mujeres (27) y montañas (Amós 4:13).
El v. 2 describe el mundo en tinieblas y desolación, cubierto por aguas y con el misterioso Espíritu (o viento) de Dios moviéndose sobre el océano. La propuesta de un poder existente en la deidad es desarrollada más adelante en Prov. 8:22-31 y en Juan 1:1-3, en donde se habla de la “sabiduría” y “el Verbo” asistiendo en la creación.</p>
<br/>
<p class="text-justify">La creación de la luz. El oscuro mundo fue iluminado cuando Dios dijo: Sea la luz. Más precisamente, el día fue distinguido de la noche al crearse la luz. La luz es una forma de energía y puede ser producida en diferentes maneras, no sólo por el sol y las estrellas (los cuales no habían sido creados sino hasta el día cuarto). Cosmólogos contemporáneos dicen que el universo comenzó con un gran estallido ardiente, el cual debió producir una luz muy brillante. El orden comienza a aparecer y a reemplazar el oscuro caos. El refrán Dios vio que (esto) era bueno (cf. vv. 10, 12, 18, 21, 25, 31) afirma la bondad intrínseca de la creación y de su Creador.
Nota. Es posible que el orden de tarde-mañana en la frase Y fue la tarde y la mañana del primer día (cf. vv. 8, 13, 19, 23, 31) refleje el concepto hebreo del día comenzando con el atardecer y terminando con el amanecer siguiente. Lo que más importa en Gén. es que Dios trabajó durante seis “días” y descansó. Al ser estos los días de la actividad de Dios y no de la actividad humana, no es probable que deban ser considerados como días de 24 horas. Además, la palabra hebrea para “día” cubre una variedad de períodos, que van desde las horas de luz en el día (Gén. 29:7), a un día de 24 horas (Gén. 7:4), o a un período indefinido (Gén. 35:3). Que ellos fueron diferentes de los días ordinarios se muestra por el hecho de la no existencia del sol hasta el día cuarto. Otra insinuación de que la creación no tomó seis días literales es la mención de la creación de los cielos y la tierra, eso es, el universo desorganizado (1) antes que los seis días fuesen contados. Finalmente, se debe notar que 1:1-2:3, diferente a todas las otras secciones de Gén., no está encabezada por el título: “Estos son los orígenes”, que es lo que une la protohistoria (2:4-11:26) con la historia patriarcal (11:27-50:26). Todas estas diferencias indican que 1:1-2:3 sirve como una obertura para el resto del libro y que no debe ser tomada lit. como aquello que continúa. No obstante, que Dios trabajó seis días y que descansó el día séptimo (sea cual fuere el largo de sus días por medidas humanas) es un modelo para ser seguido por la humanidad.</p>
<br/>
<p class="text-justify">La separación de las aguas. Dios mostró su poder nuevamente al ponerle límites a las aguas que hasta ese momento cubrían el globo (cf. Job 38:8-11). Algunas fueron confinadas a los mares, el resto a los cielos. Las aguas de arriba fueron conservadas allí por la “bóveda” o el “firmamento” (BJ). Desde la tierra, el cielo (firmamento) parece ser una especie de cúpula que previene que las aguas caigan en forma descontrolada sobre la tierra (cf. 7:11).</p>
<br/>
<p class="text-justify">La creación de la tierra y las plantas. Aun más importante para la humanidad fue la provisión, en el tercer día, de tierra seca, en la cual ella podía vivir, y plantas para sustentar la vida (cf. 1:29-30). La variedad de plantas (11, 12) da testimonio del poder organizador de Dios, y estas distinciones no debieran ser entremezcladas (ver las normativas en contra de ciertas mezclas en Lev. 19:19; Deut. 22:9-11).</p>
<br/>
<p class="text-justify">La creación de las lumbreras celestiales. Una prueba aun más poderosa del poder creativo de Dios, y siempre pertinente para la existencia humana, son el sol, la luna y las estrellas. Contemporáneos paganos del Gén. reconocieron en estos cuerpos celestes dioses por derecho propio. Para evitar el levantamiento de cualquier sospecha en relación con el sol y la luna en el sentido de que no son otra cosa que creación de Dios, Gén. las llama simplemente lumbreras. Fueron establecidas para regular los ritmos esenciales de la vida humana sean estos la definición del día y la noche, sean estos las estaciones del año.</p>
<br/>
<p class="text-justify">La creación de los pájaros y los peces. El paralelo en la obra creadora de Dios entre los primeros tres días y los segundos tres días llega a ser más claro. En el primer día, fue creada la luz, en el día cuarto, las lumbreras celestiales; en el día segundo, el cielo y los océanos, en el día quinto, las aves y los peces. Una vez más, Gén. está enfatizando la preocupación de Dios por el orden. “Los grandes animales acuáticos” fueron reconocidos como divinos en alguno de los mitos antiguos; Gén. insiste en que ellos fueron solamente criaturas de Dios. Además, Dios quiso que tanto las aguas como el aire estuvieran llenos de criaturas, y su decreto y bendición garantizó la fertilidad de estos. Ningún rito mágico o de fertilidad fueron necesarios para asegurarla.</p>
<br/>
<p class="text-justify">La creación de los animales y la humanidad
El relato de la creación alcanza su clímax en el día sexto. Nótese cuánto más completa es la descripción del trabajo de Dios de este día que en cual quiera de los días anteriores y los paralelos con las palabras del día tercero (la tierra).
Aquí Gén. define el propósito de la humanidad y su lugar en el plan de Dios. Dios dice que el hombre ha de ser creado a nuestra imagen, conforme a nuestra semejanza. Esto significa que la humanidad, tanto el varón como la mujer, es representante de Dios en la tierra. Los reyes del antiguo Oriente fueron a menudo vistos como portadores de la imagen de sus dioses, pero Gén. afirma que cada ser humano está hecho a la imagen de Dios. El NT afirma que Cristo es “la imagen del Dios invisible” (Col. 1:15), “el resplandor de su gloria y la expresión exacta de su naturaleza” (Heb. 1:3). Semejante entendimiento de la imagen divina estaba más allá del alcance del autor humano de Gén., pero él alude a otra dimensión de ésta al comentar Hagamos al hombre a nuestra imagen (26). Aquí Dios se presenta como hablando con los ángeles, la única alusión hecha a otros seres sobrenaturales en este capítulo. Esta observación implica que el hombre es como Dios y los ángeles. (Tradicionalmente, los cristianos han visto el nosotros y el nuestro como aludiendo a las otras personas de la Trinidad. Aunque esta es una legítima y más amplia interpretación, no es el significado primario de las palabras usadas aquí.)
En segundo lugar, dado que los seres humanos son creados a la imagen de Dios ellos son sus representantes en la tierra y deben tener dominio … sobre la tierra (26). El Sal. 8:4-8 ofrece un maravilloso comentario poético sobre el tema. Dominio implica señorío pero no explotación. El hombre, como representante de Dios, debe dominar a los que le están subordinados, como Dios lo hace, para el propio beneficio de ellos. Mientras se legitimiza el uso humano de los recursos naturales, Dios no da licencia para nuestro abuso de su creación.
En tercer lugar, Dios deliberadamente creó la humanidad en dos sexos y dijo: sed fecundos y multiplicaos. En relación con esto él bendijo la actividad sexual e indicó su importancia en su plan. Otras historias antiguas, surgiendo de la Mesopotamia urbana (cuya preocupación estaba en la explosión demográfica) cuentan de los dioses dando pasos para frenar la fertilidad humana a través del envío de plagas, hambre, inundaciones y abortos. El Dios del Gén. exhorta reiteradas veces a la primera pareja el ser fructíferos (1:28; 8:17; 9:1, 7) y le prometió a los patriarcas que llegarían a ser padres de una innumerable cantidad de hijos. Por lo tanto, la sexualidad es vista como una parte importante de la creación misma de Dios (31).
En cuarto lugar, Dios proveyó comida para la humanidad en la forma de planta que da semilla y todo árbol cuyo fruto lleva semilla (29). No fue sino hasta después del diluvio que el comer carne fue sancionado (9:1-3). Sin embargo, Gén. no está interesado en mostrar si los primeros habitantes fueron vegetarianos o no, sino más bien en el hecho que Dios les proveyó comida. En la mitología mesopotámica los dioses crearon al hombre para proveerse a sí mismos de comida; Gén. afirma precisamente lo contrario, que Dios alimenta a la humanidad (cf. Sal. 65; 50:7-15).</p>
<br/>
<p class="text-justify">El principio de la creación
La RVA acepta el entendimiento tradicional de estos versículos, en el sentido de que describen que el primer acto creador, cuando Dios creó toda la materia (los cielos y la tierra) de la nada. Y la tierra inmediatamente después de la creación estaba sin orden y vacía, eso es, improductiva e inhabitada. De esta manera la narrativa procede a relacionar cómo en seis días Dios organizó este caos en un mundo bien ordenado como lo vemos hoy.
Algunas traducciones y comentaristas modernos entienden el v. 1 en forma diferente. Algunos lo consideran simplemente como definiendo la situación cuando Dios comenzó a crear: “En el principio cuando Dios creó … la tierra estaba sin forma … ” Otros simplemente consideran el v. 1 como un título resumen del capítulo 1. Pero ninguno de estos puntos de vista es como el que ha adoptado la RVA. “Crear” es algo que sólo Dios puede hacer (este verbo es usado sólo en relación con Dios en el AT). El demuestra su poder para crear cosas inesperadas y maravillosas (Núm. 16:30), p. ej. grandes criaturas (21), hombres y mujeres (27) y montañas (Amós 4:13).
El v. 2 describe el mundo en tinieblas y desolación, cubierto por aguas y con el misterioso Espíritu (o viento) de Dios moviéndose sobre el océano. La propuesta de un poder existente en la deidad es desarrollada más adelante en Prov. 8:22-31 y en Juan 1:1-3, en donde se habla de la “sabiduría” y “el Verbo” asistiendo en la creación.</p>
<br/>
<p class="text-justify">La creación de la luz. El oscuro mundo fue iluminado cuando Dios dijo: Sea la luz. Más precisamente, el día fue distinguido de la noche al crearse la luz. La luz es una forma de energía y puede ser producida en diferentes maneras, no sólo por el sol y las estrellas (los cuales no habían sido creados sino hasta el día cuarto). Cosmólogos contemporáneos dicen que el universo comenzó con un gran estallido ardiente, el cual debió producir una luz muy brillante. El orden comienza a aparecer y a reemplazar el oscuro caos. El refrán Dios vio que (esto) era bueno (cf. vv. 10, 12, 18, 21, 25, 31) afirma la bondad intrínseca de la creación y de su Creador.
Nota. Es posible que el orden de tarde-mañana en la frase Y fue la tarde y la mañana del primer día (cf. vv. 8, 13, 19, 23, 31) refleje el concepto hebreo del día comenzando con el atardecer y terminando con el amanecer siguiente. Lo que más importa en Gén. es que Dios trabajó durante seis “días” y descansó. Al ser estos los días de la actividad de Dios y no de la actividad humana, no es probable que deban ser considerados como días de 24 horas. Además, la palabra hebrea para “día” cubre una variedad de períodos, que van desde las horas de luz en el día (Gén. 29:7), a un día de 24 horas (Gén. 7:4), o a un período indefinido (Gén. 35:3). Que ellos fueron diferentes de los días ordinarios se muestra por el hecho de la no existencia del sol hasta el día cuarto. Otra insinuación de que la creación no tomó seis días literales es la mención de la creación de los cielos y la tierra, eso es, el universo desorganizado (1) antes que los seis días fuesen contados. Finalmente, se debe notar que 1:1-2:3, diferente a todas las otras secciones de Gén., no está encabezada por el título: “Estos son los orígenes”, que es lo que une la protohistoria (2:4-11:26) con la historia patriarcal (11:27-50:26). Todas estas diferencias indican que 1:1-2:3 sirve como una obertura para el resto del libro y que no debe ser tomada lit. como aquello que continúa. No obstante, que Dios trabajó seis días y que descansó el día séptimo (sea cual fuere el largo de sus días por medidas humanas) es un modelo para ser seguido por la humanidad.</p>
<br/>
<p class="text-justify">La separación de las aguas. Dios mostró su poder nuevamente al ponerle límites a las aguas que hasta ese momento cubrían el globo (cf. Job 38:8-11). Algunas fueron confinadas a los mares, el resto a los cielos. Las aguas de arriba fueron conservadas allí por la “bóveda” o el “firmamento” (BJ). Desde la tierra, el cielo (firmamento) parece ser una especie de cúpula que previene que las aguas caigan en forma descontrolada sobre la tierra (cf. 7:11).</p>
<br/>
<p class="text-justify">La creación de la tierra y las plantas. Aun más importante para la humanidad fue la provisión, en el tercer día, de tierra seca, en la cual ella podía vivir, y plantas para sustentar la vida (cf. 1:29-30). La variedad de plantas (11, 12) da testimonio del poder organizador de Dios, y estas distinciones no debieran ser entremezcladas (ver las normativas en contra de ciertas mezclas en Lev. 19:19; Deut. 22:9-11).</p>
<br/>
<p class="text-justify">La creación de las lumbreras celestiales. Una prueba aun más poderosa del poder creativo de Dios, y siempre pertinente para la existencia humana, son el sol, la luna y las estrellas. Contemporáneos paganos del Gén. reconocieron en estos cuerpos celestes dioses por derecho propio. Para evitar el levantamiento de cualquier sospecha en relación con el sol y la luna en el sentido de que no son otra cosa que creación de Dios, Gén. las llama simplemente lumbreras. Fueron establecidas para regular los ritmos esenciales de la vida humana sean estos la definición del día y la noche, sean estos las estaciones del año.</p>
<br/>
<p class="text-justify">La creación de los pájaros y los peces. El paralelo en la obra creadora de Dios entre los primeros tres días y los segundos tres días llega a ser más claro. En el primer día, fue creada la luz, en el día cuarto, las lumbreras celestiales; en el día segundo, el cielo y los océanos, en el día quinto, las aves y los peces. Una vez más, Gén. está enfatizando la preocupación de Dios por el orden. “Los grandes animales acuáticos” fueron reconocidos como divinos en alguno de los mitos antiguos; Gén. insiste en que ellos fueron solamente criaturas de Dios. Además, Dios quiso que tanto las aguas como el aire estuvieran llenos de criaturas, y su decreto y bendición garantizó la fertilidad de estos. Ningún rito mágico o de fertilidad fueron necesarios para asegurarla.</p>
<br/>
<p class="text-justify">La creación de los animales y la humanidad
El relato de la creación alcanza su clímax en el día sexto. Nótese cuánto más completa es la descripción del trabajo de Dios de este día que en cual quiera de los días anteriores y los paralelos con las palabras del día tercero (la tierra).
Aquí Gén. define el propósito de la humanidad y su lugar en el plan de Dios. Dios dice que el hombre ha de ser creado a nuestra imagen, conforme a nuestra semejanza. Esto significa que la humanidad, tanto el varón como la mujer, es representante de Dios en la tierra. Los reyes del antiguo Oriente fueron a menudo vistos como portadores de la imagen de sus dioses, pero Gén. afirma que cada ser humano está hecho a la imagen de Dios. El NT afirma que Cristo es “la imagen del Dios invisible” (Col. 1:15), “el resplandor de su gloria y la expresión exacta de su naturaleza” (Heb. 1:3). Semejante entendimiento de la imagen divina estaba más allá del alcance del autor humano de Gén., pero él alude a otra dimensión de ésta al comentar Hagamos al hombre a nuestra imagen (26). Aquí Dios se presenta como hablando con los ángeles, la única alusión hecha a otros seres sobrenaturales en este capítulo. Esta observación implica que el hombre es como Dios y los ángeles. (Tradicionalmente, los cristianos han visto el nosotros y el nuestro como aludiendo a las otras personas de la Trinidad. Aunque esta es una legítima y más amplia interpretación, no es el significado primario de las palabras usadas aquí.)
En segundo lugar, dado que los seres humanos son creados a la imagen de Dios ellos son sus representantes en la tierra y deben tener dominio … sobre la tierra (26). El Sal. 8:4-8 ofrece un maravilloso comentario poético sobre el tema. Dominio implica señorío pero no explotación. El hombre, como representante de Dios, debe dominar a los que le están subordinados, como Dios lo hace, para el propio beneficio de ellos. Mientras se legitimiza el uso humano de los recursos naturales, Dios no da licencia para nuestro abuso de su creación.
En tercer lugar, Dios deliberadamente creó la humanidad en dos sexos y dijo: sed fecundos y multiplicaos. En relación con esto él bendijo la actividad sexual e indicó su importancia en su plan. Otras historias antiguas, surgiendo de la Mesopotamia urbana (cuya preocupación estaba en la explosión demográfica) cuentan de los dioses dando pasos para frenar la fertilidad humana a través del envío de plagas, hambre, inundaciones y abortos. El Dios del Gén. exhorta reiteradas veces a la primera pareja el ser fructíferos (1:28; 8:17; 9:1, 7) y le prometió a los patriarcas que llegarían a ser padres de una innumerable cantidad de hijos. Por lo tanto, la sexualidad es vista como una parte importante de la creación misma de Dios (31).
En cuarto lugar, Dios proveyó comida para la humanidad en la forma de planta que da semilla y todo árbol cuyo fruto lleva semilla (29). No fue sino hasta después del diluvio que el comer carne fue sancionado (9:1-3). Sin embargo, Gén. no está interesado en mostrar si los primeros habitantes fueron vegetarianos o no, sino más bien en el hecho que Dios les proveyó comida. En la mitología mesopotámica los dioses crearon al hombre para proveerse a sí mismos de comida; Gén. afirma precisamente lo contrario, que Dios alimenta a la humanidad (cf. Sal. 65; 50:7-15).</p>
<br/>




</div>
