<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 49</h2>
<p class="text-justify">[134] Así nos reuniremos todos los hijos de Yisra&apos;el en los últimos días para oír la Palabra de YAHWEH de la boca de Yahshúa.
[135] No solamente vemos a Efrayim recibiendo el derecho de la primogenitura por sobre su hermano mayor Menasheh, sino que Yisra&apos;el también lo remueve de Reuven puesto que Reuven contaminó la cama de su padre y era sexualmente impuro referente a la privacidad e intimidad del lecho matrimonial de Yisra&apos;el. Así que en realidad Efray im es colocado adelante de Reuven, Yosef y Menasheh para recibir la bendición de primogenitura de Yisra&apos;el. 1Ki 5:1-2; Jer 31:9 lo confirman.
[136] Violó a Tamar y se arrepintió, pero querían venir a Yisra&apos;el y todos se circuncidaron ( cap. 34), siendo que Yisra&apos;el siempre fue y es una mezcla de gentes y pueblos, tengamos cuidado con los que quieren destruir con sus doctrinas demoníacas.
[137] Hasta que venga al que le pertenece la obediencia, éste es Yahshúa.
[138] Cuando Yisra&apos;el dio la primogenitura a Efrayim, él se la dio con una reservación mayor en donde a Yahudáh le es dada preeminencia o poder para mandar y gobernar realmente sobre la Casa de Yisra&apos;el. El v 9 declara que la preeminencia causaría que todo Yisra&apos;el rindiera homenaje al León de Yahudáh, a quién el v 10 se refiere con el título Mesiánico de Shiloh. Shiloh significa el &quot;enviado&quot; o el Rey Mesías ungido de la línea real de Yahudáh quien sería manifiesto en lo natural a través de la tribu de Yahudáh. Heb 7:14 aclara que Yahshúa era Shiloh y es evidente que El brotó de Yahudáh. ¡Ya&apos;akov trajo división entre los hijos de Yisra&apos;el puesto que un hijo tenía la primogenitura pero el otro hijo, Yahudáh, tenía el derecho a reinar! Los hijos de Yisra&apos;el se someterían a la semilla de Yahudáh, no a la de Efrayim, sin embargo, la semilla de Efrayim llegaría a ser la plenitud de los Gentiles. Yahudáh reinaría sobre la Casa de Yisra&apos;el, pero Efrayim traería la zera prometida que llenaría el mundo con la promesa a los patriarcas de mult iplicidad física. Yisra&apos;el sabía lo que estaba haciendo puesto que él estaba ministrando a través del Ruaj HaKodesh . El partió la autoridad y bendición entre los dos hermanos que continuarían guerreando sobre la plenitud de la bendición que últimamente sería decidida en una batalla real sobre el título de ¿Quién es Yisra&apos;el? De acuerdo con el verso 10 será el León de Yahudáh (Mesías Yahshúa), quien reuniría la semilla de Efrayim de regreso a la Casa de Yisra&apos;el.
[139] Aquí dice que Dan juzgará, por siete años el Antimesías juzgará con mano dura y se cree que vendrá de la tribu de Dan.
[140] Esta víbora ataca a los &quot;del camino,&quot; los primeros conversos Israelita Mesiánicos le llamaban &quot;los del Camino.&quot; Yahshúa en los últimos días está montado en un caballo blanco (Rev 19:11), entonces nos dice que el Antimesías de la tribu de Dan será ese que muerde al caballo, entonces Ya&apos;akov clamará por la salvación de Yahshúa. La tribu de Dan no está incluida en los 144,000 de los últimos días (Rev 7:4), pero esto no significa que Dan no tenga Salvación, sino que no es escogido para este trabajo. Podemos ver en Eze 48:2 a Dan se le da su porción de tierra después que el tercer Templo esté edificado por Mesías Yahshúa. Como nadie sabe de qué tribu es, ni dónde precisamente están las tribus, Roma también tiene Israelitas de sangre, y de ahí vendrá todo esto. Ya en un tiempo hubo un papa Judío, (&quot;La Historia Verídica de un papa Judío&quot;).
[141] La tierra está llena de la semilla de Yosef, hermanos y hermanas permanezcan agarrados al Mesías y a la Toráh, no pierdan estas maravillosas bendiciones y la Salvación eterna.</p>
<br/>




</div>
