<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 28</h2>
<p class="text-justify">Resurrección gloriosa de Jesucristo. Los ángeles la anuncian a las mujeres que venían a visitar el sepulcro. Aparece el Señor a estas, y les manda que den la nueva a los discípulos. Los mismos guardas dan testimonio de la resurrección del Señor, y los sacerdotes los sobornan para que digan lo contrario. El Señor se muestra a sus discípulos en Galilea, y los envía por todo el mundo a predicar el Evangelio.
1 a. El Evangelista cuenta aquí el día natural de veinte y cuatro horas, desde que el sol sale, hasta que otra vez vuelve a salir, como lo contaban los romanos. Los hebreos lo hacían desde puesto el sol, hasta que otro día se volvía a poner. Y así lo que esto quiere decir es, que se acababa el último día de la semana, y comenzaba el primero de la otra. Jesucristo resucitó la mañana del domingo, como lo cree la Iglesia. San Jerónimo, San Gregorio Niseno, San Agustín y Santo Tomás se han aplicado particularmente a hacer ver, que vespere sabbati se debe explicar pasada la semana, o la noche del mismo sábado; y las otras palabras: quae lucescit in prima sabbati señalan la declinación de esta misma noche, que era el principio y como el rayar de la aurora del siguiente día; esto es, del domingo primer día de la semana siguiente.
2 b. El cual probablemente no se extendería mucho más allá del sitio del jardín, en donde estaba enterrado el cuerpo de Jesucristo. El adverbio idóu, ecce, aunque significa en el mismo tiempo, o de improviso, aquí se debe tomar como partícula afirmativa, y el pretérito como plusquam perfecto, como lo usan los hebreos, porque todo esto que aquí se refiere, no aconteció luego que llegaron las mujeres, sino que había ya sucedido durante la noche; y aunque no se sabe la hora, fue al amanecer o por la mañana, cuando resucitó el Señor, como lo dice expresamente San Marcos (16,9), y se infiere cotejado con Mc 16,2; Lc 24; Jn 20.
c. El Griego: apó tés thúras, de la entrada, o de la puerta.
3 d. El Griego: leukón, blancos.
5 e. San Lucas y San Juan hablan de dos ángeles, que unos quieren que fuesen diferentes de este; y otros, que hablando de uno solo San Mateo y San Marcos, entienden el que de los dos habló a las mujeres. Pero parece más probable lo primero, porque este se nos representa sentado sobre la piedra que cubría la entrada del sepulcro, y los otros dos dentro de él, uno sentado a la cabecera, y otro a los pies del lugar donde había sido puesto el cuerpo del Señor (Jn 20,12; véase Mc 16,5).
f. Estas palabras son enfáticas: No temáis vosotras; como si dijera: Teman y queden aterrados los que pretenden oscurecer la gloria de la resurrección de mi Señor; mas vosotras no tenéis por qué asustaros, ni por qué temer. Sé, que ansiosas de manifestarle vuestro amor, venís aquí buscando al que ha sido crucificado, para ungir su cuerpo, y embalsamarlo. San Jerónimo.
6 g. El Griego: ékeito, en donde yacía.
7 h. El Griego: apó tón nekrón, de entre los muertos.
i. Obligándolos así a salir cuanto antes de Jerusalén, y pasar a Galilea para que estuviesen más distantes de todos aquellos que les pudiesen hacer algún daño. San Juan Crisóstomo, Santo Tomás.
8 j. MS. Ayna.
k. El Griego: hós dé eporéuonto apangéilai tois mathetáis autóu, y cuando iban a dar la nueva a sus discípulos. Todo esto no se lee en la Vulgata. Estas mujeres salieron del sepulcro, esto es, de la gruta en que estaba el sepulcro de Jesucristo, y a donde habían entrado por orden del ángel. Este disipó las tinieblas de aquel lugar oscuro, con la luz y resplandor que arrojaba de sí mismo, como observa San Jerónimo. El temor que tuvieron, nacía de la vista del ángel, y del peligro en que se creían estar, porque dudaban de la verdad de las cosas que se les decían. Mas este temor iba mezclado de una extraordinaria alegría por la novedad de la resurrección milagrosa del Salvador, que les parecía increíble. Esto mismo experimentamos muchas veces, cuando deseamos con ansia una cosa, pues apenas la creemos, aun cuando la estamos viendo y tocando.
10 l. ¡Qué palabra tan llena de consuelo y de aliento para aquellos que con tanta cobardía volvieron las espaldas al Señor al tiempo de su muerte!
12 m. El Griego: argúria hikaná, bastante dinero.
13 n. ¿Cómo pueden estos dar testimonio de lo que pasó, si estaban durmiendo? Los dormidos fuisteis vosotros, dice admirablemente San Agustín, enderezando su discurso a los príncipes de los sacerdotes y a los ancianos; porque recurriendo a un artificio tan poco verosímil, descubristeis vosotros mismos la impostura.
17 o. No de su resurrección, sino de si era verdaderamente su Señor, el que entonces se les aparecía.
18 p. Por su muerte, y por haber resucitado triunfando de la muerte, le fue dada por su Padre toda potestad en el cielo para estar sentado a su derecha, y para ser reconocido rey de todos los ángeles; y en la tierra para fundar su Iglesia, componiéndola de todas las naciones, reuniendo en un solo cuerpo todos sus miembros, y reinando soberanamente sobre todas las criaturas.
19 q. Estas palabras, dice San Agustín, De Bapt. lib. VI, cap. XXV, n. 47, son evangélicas, y sin ellas no se puede conferir el Bautismo.
20 r. Después de la instrucción en las cosas de la fe, manda el Señor a sus Apóstoles que enseñen a todos las reglas de las costumbres; porque la vida de un hombre, que esta bautizado, debe formarse sobre las reglas que Jesucristo ordenó a sus discípulos en su Evangelio, y no sobre alguna solamente, sino sobre todas. Porque el que quebranta uno de los preceptos, se hace reo, como si los hubiera quebrantado todos (Stgo 2,10). Y así no basta tener la fe, ni haber recibido el Bautismo, sino que es necesario observar exactamente todo lo que el Hijo de Dios nos ha ordenado por la boca de los Apóstoles, que fueron los ministros de su palabra y los intérpretes de su voluntad. San Jerónimo.
s. El Griego, amén. Sobre la firmeza e inmovilidad de esta palabra descansa la Iglesia, y está asegurada, que ni las potestades del infierno, ni todas las de la tierra podrán prevalecer jamás contra la verdad de su creencia.</p>
<br/>




</div>
