<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 2</h2>
<p class="text-justify">Los Magos vienen de Oriente a Belén: adoran al Señor, y le ofrecen sus presentes. Crueldad de Herodes en hacer matar a todos los niños menores de dos años en Belén y en toda su comarca. Huida de Cristo a Egipto: su vuelta a la tierra de Israel.
1 a. Esto es, de la tribu de Judá, porque había otra ciudad del mismo nombre, que pertenecía a la tribu de Zabulón (Jos 19,15).
b. Estos Magos, de que habla aquí el Evangelista, eran, según el sentimiento de San Jerónimo, hombres sabios y filósofos, aplicados al conocimiento de las cosas naturales, in Dan 2. Entre los persas eran llamados Magos, y tenidos en el mayor respeto los ministros de la religión, que atendían al culto de la divinidad, y se aplicaban al conocimiento de ella. Por el Oriente entienden algunos la Persia, y otros la Arabia; y esto parece más conforme a lo que dice David en el Sal 71,10: Que los reyes de los Árabes, y de Sabá ofrecerían presentes. De aquí han creído algunos intérpretes, que fueron reyes; o por lo menos de los principales y más nobles del país. A estos Magos escogió Dios entre otros muchos, para llenarlos de luz, y hacerles conocer el misterio de nuestra redención.
2 c. El Griego: ho tejthéis, aquel que nació, el nacido. Aquí el artículo ho es enfático.
d. Algunos explican este lugar de esta manera: Estando en el Oriente, vimos su estrella, suponiendo que se dejó ver sobre Jerusalén; pero esta exposición parece contraria a lo que se dice en el v. 9. Todo lo que se nos refiere aquí acerca de estos Magos, es extraordinario y milagroso. Este fenómeno que apareció a los Magos, no era una estrella propiamente, sino un fuego encendido extraordinariamente por el poder divino, bajo la figura de una grande y resplandeciente estrella, destinada para alumbrar a los Magos, y servirles de guía, y que aparecía y desaparecía, según la voluntad del soberano Artífice que la había formado. Los Magos, por divina revelación, supieron lo que esta nueva estrella les anunciaba.
3 e. Una nueva, que le aseguraba el nacimiento de un nuevo rey de los judíos, no podía menos de turbarle, temiendo que le despojaría de un reino que él había usurpado.
4 f. Las cabezas de las veinte y cuatro familias sacerdotales, que servían en el templo por su turno (1Cro 24,17).
g. Los doctores de la ley; porque estos eran los depositarios de los libros santos, y los intérpretes de las Escrituras divinas; y por esto los llama, para que le expliquen lo que decían las profecías sobre el nacimiento del Cristo o del Mesías.
5 h. En Miqueas se llama Belén Efratá.
7 i. Les apareció; esto es, se les comenzó a aparecer, o la vieron la primera vez.
8 j. Lo que pretendía Herodes, era saber dónde se hallaba el rey recién nacido, no para pasar a adorarle, como decía, sino para hacerle morir cruelmente, como se vio por lo que hizo después, cuando se vio burlado por los Magos. Pero contra el consejo de Dios nada pueden todos los hombres y reyes juntos.
9 k. Sirviéndoles de guía en el camino hasta Jerusalén.
11 l. El Griego: kái elthóntes eis tén oikían, éidon tó paidíon (y llegando a la casa, vieron al niño). Esta casa, según San Jerónimo y otros, era un establo. En este rinconcito de la tierra nació el Creador de los cielos. En él fue envuelto en pobres pañales, visitado de los pastores, mostrado por la estrella, y adorado por los Magos, y reconocido por Dios.
m. Esto es, los cofres en donde llevaban sus tesoros y alhajas. Los Padres advierten, que le ofrecieron oro como a rey, incienso como a Dios, y mirra como a hombre.
12 n. El Griego: jrematisthéntes. Esta palabra, de que usa el texto Griego, explica que fueron avisados por un ángel.
13 o. El Griego: egerthéis (despertando), y lo mismo repite poco más abajo.
p. Pero ¿el Libertador del mundo debía temer la cólera y el furor de Herodes, y salvarse de sus manos por medio de la huida? ¿No parece cosa poco decorosa e indigna del Señor universal de todas las cosas, atender a la seguridad de su Hijo por unos medios que tienen todo el aire de temor y de flaqueza? Pero esta misma pregunta se puede hacer acerca de todos los abatimientos que tuvo el Señor desde el punto mismo en que desde el seno del Padre descendió a encarnarse en el seno de María. Véase San Juan Chrysóstomo, Homil. VIII in Matth. Viniendo al mundo, quiso mostrar de luego a luego, que él era el que venía a ser desechado y despreciado entre los hombres, el varón de dolores, que sabe lo que es flaqueza (Is 53,3).
15 q. El texto de Os 11,1, habla del pueblo de Israel, a quien Dios sacó de Egipto bajo la conducta de Moisés; pero aquello figuraba a Cristo, que es cabeza de la Iglesia, en quien se cumple principalmente la profecía.
16 r. Después que la Virgen y San José habían huido a Egipto.
s. MS. De dos annos aiuso.
18 t. Ramá estaba en los confines de la tribu de Benjamín, y cerca de Belén. San Jerónimo siente, que Ramá no se debe tomar aquí por nombre propio, y que así el verdadero sentido de estas palabras es este: Un grande ruido se dejó oír bien lejos, y se levantó hasta el cielo. Mas es de notar, que el sepulcro de Raquel estaba cerca de este lugar (Gén 35,19).
u. El Griego: thrénos, kái klauthmós, kái odurmós polús (Lloro, y lamentación, y gemido grande) (Jer 31,15). Lo que el profeta había dicho antes del tiempo del cautiverio de Babilonia, lo aplicó también el Evangelista al tiempo de la mortandad de los Inocentes. Jeremías, para dar una idea del dolor que causaría el cautiverio de las diez tribus, introduce a Raquel, como saliendo de su sepulcro, para llorar a la vista de tan triste espectáculo. Las lágrimas de los vivos no bastaban para llorar esta desgracia tan terrible; y así era necesario juntar las de los muertos, y sobre todo de Raquel, cuyo sepulcro estaba sobre el camino por donde debían pasar los cautivos. Los gemidos y gritos penetrantes de estos la hicieron, por decirlo así, salir del sepulcro, y derramar lágrimas, temiendo que no volverían más a ver su patria. Esta bella imagen la aplica el Evangelista a la crueldad de Herodes con los Inocentes.
20 v. Los que buscaban la vida, o querían matar; el plural por el singular; esto es, Herodes que buscaba. Puede también esto entenderse de los cortesanos de Herodes, que por lisonjearle, aprobarían su bárbara resolución. Cosa muy común en los palacios.
22 w. MS. E por amostramiento del ángel en suennos.
23 x. Nazareno quiere decir santo, separado y consagrado al Señor. Los judíos le llamaban así por desprecio, por haberse criado en Nazaret, ciudad para ellos despreciable. Pero en el sentido en que hablaron de él los profetas, fue por su singular consagración, porque la palabra hebrea Nazar significa ser puro, consagrado, como lo es el Santo de los santos. Las profecías a que alude el texto pueden ser la del Gén 49,26, y la del Dt 33,16, en las que se da el nombre de Nazareno a José hijo de Jacob, que fue la figura más expresa de Jesucristo. San Jerónimo dice, que aquí se hace alusión a Is 11,1, et flos de radice ejus ascendet, y en este caso se escribe Netsar por Tsade, y no Nazar por Zain.</p>
<br/>




</div>
