<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 3</h2>
<p class="text-justify">San Juan Bautista, precursor de Jesucristo, predica penitencia en el desierto, conforme a lo que habían vaticinado los profetas. Reprende a los fariseosfariseos y saduceos. Bautiza a Cristo, sobre el cual desciende el Espíritu Santo; y se oye del cielo la voz del Padre.
1 a. Veinte años pasaron desde que volvió Jesús de Egipto a Nazaret, hasta la predicación de San Juan; de la que se habla en este capítulo. Así que estas palabras en aquellos días, no quieren decir que esto sucedió luego que volvieron de Egipto, sino en general, en aquel tiempo que vivieron en Nazaret.
b. Se le dio este sobrenombre, en atención al ministerio que ejercía. Este era dar un Bautismo de preparación y penitencia a los que querían disponerse para recibir el de Jesucristo. Este Bautismo que recibían, no quitaba por sí mismo los pecados, sino sólo en cuanto miraba al verdadero Bautismo del Mesías, que era el que los había de purificar perfectamente.
3 c. Porque de Juan es de quien dijo el profeta Isaías: Se ha oído la voz: o Esta es la voz (Is 40,3). La letra del texto de Isaías mira a la libertad de los judíos del cautiverio de Babilonia. Y aquella figuraba la que el Salvador había de dar al hombre.
4 d. Un vestido áspero tejido de pelos de camello, apretado y ajustado con un ceñidor de cuero.
e. MS. E su vianda era de lagosta, e demiel salvagina. Por el traje y vianda se muestra que hacía una vida austera y penitente. Para que no parezca extraño que el Bautista se pudiese alimentar con langostas, véanse las notas sobre Lev 11,22.
6 f. MS. E baptizábalos. En otros muchos lugares más frecuentemente se lee batear.
7 g. Los fariseos y los saduceos eran dos sectas célebres entre los judíos. Los primeros afectaban mayor regularidad en su vida, y se habían adquirido un grande concepto entre el pueblo; por manera, que eran mirados como los maestros de la piedad, aunque estuviesen llenos de soberbia y de hipocresía. Los saduceos negaban la resurrección de los muertos, y tenían otros muchos sentimientos contrarios a los de los judíos; y así muchos de ellos venían al Bautismo de Juan llenos de orgullo, y por una especie de política y curiosidad. Dios descubrió al santo Precursor el fondo de sus corazones; y por esto los llama linaje o raza de víboras; esto es, hombres llenos de veneno y de malicia, y dignos hijos de sus padres: hijos del diablo que en muchos lugares es llamado vibora, porque su veneno es el más nocivo de todos (Jn 8,44).
9 h. No os lisonjeéis diciendo: A Abraham tenemos, etc.
i. Este lugar se puede entender literalmente, porque para Dios no hay cosa imposible. San Jerónimo in Matth. y otros intérpretes. Puede también entenderse en sentido metafórico, como lo explican otros Padres, significando que Dios podía hacer hijos dignos de Abraham a los que tenían corazones tan duros como las piedras: esto es, a los mismos gentiles; lo que en efecto declaraba su conversión a la fe de Jesucristo. Abrahae está en dativo, como se reconoce en el texto Griego, tó.
10 j. Texto Griego: ekkóptetai, etc., bálletai; es cortado, etc., es arrojado. Como si dijera: El que viene en pos de mí va a destruir con sus obras toda vuestra falsa gloria, y toda esa vana confianza que tenéis en la nobleza de vuestro origen. Él os cortará, como árboles infructuosos, para arrojaros al fuego eterno, si no procuráis llevar buenos frutos por medio de la penitencia, y si no os hacéis hijos dignos de Abraham, no según la carne, sino según la fe. Porque la dignidad de nuestro origen consiste en imitar los ejemplos de virtud que nos dejaron nuestros padres; y la gloria de nuestros antepasados no llega hasta nosotros, sino cuando va acompañada de su fe y de sus virtudes. S. Hilar. in Matth. Canon. II.
11 k. El Griego: erjómenos, el que viene.
l. Otros trasladan: Cuyo calzado no soy yo digno de servirle, o de llevar.
m. En Espíritu Santo; que como fuego alumbrará, encenderá y purificará vuestros corazones.
12 n. Su bieldo en su mano, para separar el trigo de la paja. El trigo, que son los buenos frutos y obras, de los que son sus fieles servidores, lo recogerá para ponerlo en sus eternos graneros; pero la paja de vuestra vanidad y ligereza servirá de alimento al fuego eterno del infierno. El templo destruido, la república arruinada, la nación esparcida por toda la tierra, son un monumento eterno de la venganza de Dios contra los que quitaron la vida a su Hijo.
MS. El aventadero.
13 o. Después de haber exhortado San Juan a los judíos a hacer penitencia, preparándolos para recibir el Mesías, este Señor, que hasta entonces había estado oculto, viviendo una vida común con la Virgen su madre, y con San José en Nazaret, ciudad de Galilea, pasó al lugar donde bautizaba San Juan; esto es, a la ribera del Jordán. Treinta años de una vida oculta de un Dios hecho hombre, y el silencio del Verbo y de la voz del Padre eterno en todo este tiempo, confunden de una manera asombrosa la vana precipitación de aquellos hombres inquietos que se presentan en público sin especial vocación de Dios, para hacer brillar a los ojos de los pueblos sus talentos, sirviendo más bien para su propia confusión delante de Dios, que para la salud y aprovechamiento de los prójimos.
14 p. San Juan lleno de espanto, viendo venir a su Bautismo, y acercarse a ser bautizado con los pecadores, a aquel mismo de quien acababa de dar un testimonio tan auténtico, se resistía a bautizar al Señor; pero se humilló y obedeció, luego que le oyó decir que era necesario cumplir todas las órdenes del Padre eterno. Estas pedían que el Señor se anonadase, por decirlo así, bajo la forma de hombre, para reparar el ultraje que el hombre había hecho a Dios, elevándole su orgullo más allá de lo que era.
15 q. Le dejó hacer lo que quería; esto es, no se resistió más a bautizar al Señor. La Vulgata antigua: Entonces le bautizó.
16 r. No solamente el Señor, sino también San Juan y todos los judíos que le acompañaban vieron la figura de una paloma, bajo la cual el Espíritu Santo descendió del cielo, y descansó sobre la cabeza de Jesucristo. El Espíritu Santo apareció en esta forma; porque, como dice San Juan Crisóstomo, siendo la paloma dulce y pura, quiso aquel divino Espíritu, que lo es de dulzura, de pureza y de paz, elegir esta figura, que representaba en alguna manera lo que él es, y lo que deben ser aquellos en quienes desciende por el Bautismo. El misterio de la Trinidad, como observa San Jerónimo, se descubre en el bautismo de Jesucristo. El Hijo que es el mismo bautizado; el Espíritu Santo, que desciende sobre él en figura de paloma, y la voz del Padre, que da un ilustre testimonio de la persona de su Hijo.
17 s. MS. Con que a mi plogo.</p>
<br/>




</div>
