<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 27</h2>
<p class="text-justify">Arrepentimiento y desesperación de Judas. El Señor es presentado a Pilato. El pueblo pide la libertad de Barrabás, y la muerte de Jesucristo. Pilato le condena contra el testimonio de su propia conciencia; y el pueblo toma sobre sí, y sobre toda su posteridad, la culpa de aquella sentencia. Después de haber sido azotado el Señor, y sentenciado a muerte, le toman los soldados, y le escarnecen en diversas maneras; le crucifican entre dos ladrones, y reparten sus ropas, y aun en la cruz le llenan de oprobios. En su muerte se oscurece el sol, resucitan los muertos, etc. José de Arimatea le baja de la cruz, y le da honrosa sepultura.
2 a. MS. Á Pilato el merino. Poncio Pilato no era propiamente sino un procurador de Judea. Así llamaban los romanos a los que estaban encargados de recoger las rentas del imperio. Dio. Cassius, I. LIII; Tácito, Annal. I. XV. Los que eran enviados a provincias grandes gobernadas por un presidente, solamente tenían la superintendencia de las rentas; pero cuando las provincias eran pequeñas, ejercían también la autoridad de gobernadores, y de esta clase era Pilato. Los romanos habían quitado a los judíos la potestad de condenar a algún reo a pena capital; y por esta razón, aunque Caifás declaró a Jesucristo reo de muerte, no dio contra él la sentencia, sino que lo remitió al gobernador de la provincia.
3 b. Judas, viendo que el furor de los judíos, después de haberle declarado reo de muerte, no descansaría hasta verle crucificado, abrió los ojos para conocer y condenar su delito. Mas este arrepentimiento fue estéril e inútil, y así añadiendo otro nuevo y mayor pecado de desesperación, se ahorcó. No consta si la infeliz muerte de este miserable fue antes o después de la muerte de Jesucristo. Es opinión común, que el desdichado discípulo ató el lazo con que se ahorcó de un árbol; y aun el poeta Juveneo determina en particular la higuera: ficus de vertice. San León. Suele el demonio, después de haber cegado a muchos para que se precipiten en la mayores abominaciones y delitos, abrirles por último los ojos, para que considerando la atrocidad de sus maldades, y oprimidos de su peso, caigan en desesperación, y por esta en el infierno.
6 c. Corbona, o como llama San Marcos (7,3), Corban, es palabra hebrea, que significa ofrenda hecha a Dios o a su templo, del verbo karab o kerib, presentar, ofrecer: y así quiere decir tesoro sagrado. San Jerónimo. Los príncipes de los sacerdotes, hipócritas como siempre, después de haberse tragado un camello, hicieron escrúpulo de pasar un mosquito; y así fundados en algunas tradiciones de sus antiguos, no quisieron poner de nuevo en el tesoro común aquel dinero, que había sido precio de la sangre de Jesucristo; sino que teniéndolo por profano, le aplicaron a beneficio de los pobres y peregrinos.
7 d. Que pertenecía a un ollero, o en donde hacía sus ollas y vasijas de tierra.
e. MS. Para cimiterio. De los que no pertenecían al pueblo de Dios, de los cuales los judíos querían estar separados, aun después de la muerte.
8 f. La voz haceldama es siríaca, del hebreo dan, o más bien del caldeo dama, sangre. Fue tan señalado este campo, que desde aquel tiempo no fue conocido por otro nombre, permitiéndolo así Dios, para que fuese una prueba y un monumento eterno de la injusticia de los judíos.
9 g. Parte de esta profecía se halla en Jeremías (32,7-9) y parte en Zacarías (11,12-13). La compra del campo está en Jeremías, y el precio de las treinta monedas se lee en Zacarías; y San Mateo añade las últimas palabras del aprecio de los hijos de Israel. David Kimchi en el prefacio a Jeremías dice, que Jeremías antiguamente ocupaba el primer lugar en el Libro de los profetas; y de aquí la mención que de él hace San Mateo (16,14), más bien que de los otros profetas, parece ser, porque era el primero, cuyo nombre se leía en dicho libro. Y lo mismo debe entenderse aquí, esto es, que cita el Libro de los profetas, nombrando a Jeremías. A este modo dijo también el Salvador (Lc 24,44): Se ha de cumplir todo lo que hay escrito acerca de mí en la ley, en los profetas, y en los salmos; esto es, en los libros de los Escritores sagrados, en los cuales tenía el primer lugar el de los salmos. San Agustín.
h. Puede también trasladarse: Que pusieron en precio los hijos de Israel. El texto Griego: apó huión israél, en donde se puede suplir hoi óntes, los israelitas, los sumos sacerdotes, etc., dando por la vida de un verdadero israelita el mismo precio que se daba según la ley (Éx 21, 32) por el rescate de la de un esclavo.
15 i. De la Pascua. Costumbre introducida por los judíos en memoria de haber sido librados por Dios de la esclavitud de Egipto, y que conservaron, según se ve en este lugar, los romanos señores de la provincia.
17 j. Causa verdaderamente asombro, que acostumbrando pedir los judíos en esta fiesta solemne de Pascua la libertad y absolución de un reo, fuese Pilato el que pidió por el Justo de los justos, y no pudo conseguir su libertad. San Juan Crisóstomo. Pilato, que conocía la inocencia del Señor, y que deseaba sacarle de las manos de los judíos, escogió expresamente a Barrabás para ponerle en comparación del Salvador, no dudando que el pueblo, a quien Jesús había colmado de beneficios, le preferiría a un ladrón, asesino y sedicioso. Mas se engañó; porque el pueblo instigado por los príncipes de los sacerdotes, y por sus ancianos o magistrados, pidió la libertad del facineroso, y condenó a ser crucificado al que era la misma inocencia. ¡Oh cuántas veces hacemos, los cristianos, el mismo cambio que hicieron los judíos!
19 k. El autor de la carta ad Philip. n. 4, atribuida a San Ignacio obispo de Antioquía, y algunos otros autores han creído que fue el demonio el que envió este sueño a la mujer de Pilato, con el fin de estorbar, cuanto le era posible, la muerte de Jesucristo. Porque comenzando a reconocer la divinidad del Señor, y a penetrar los misterios de su muerte, conocía muy bien los grandes efectos que produciría a favor de los hombres. Pero todos los otros Padres han creído que fue un sueño enviado por Dios, para justificar en el concepto del presidente a aquel que los judíos querían que él mismo condenase.
24 l. MS. Qne nol tenia pro ninguno.
m. Mandaba Dios en Dt 21,6, que cuando se encontrase el cuerpo de un hombre muerto, sin haberse descubierto el matador, se lavasen todos las manos en testimonio de su inocencia. Pilato, o conformándose con esta práctica de los judíos, o porque esta costumbre fuese también común a las otras naciones, creyó que con esta ceremonia exterior de lavarse las manos, podía condenar sin ningún remordimiento al que reconocía y publicaba inocente, solamente por satisfacer a los judíos. Mas no es el agua la que purifica el corazón; y el delito que se contrae por un consentimiento injusto del alma, no se limpia con una exterior ablución del cuerpo. San León.
25 n. ¡Terrible imprecación! Su funesto efecto ha sido, es, y será siempre bien visible. El estado a que fue reducida la nación de los judíos, llegando a ser el oprobio de todos los pueblos, ha sido el cumplimiento de esta maldición que pronunciaron contra sí; y este mismo cumplimiento debería abrirles al presente los ojos, para que viesen una luz que podía disipar las tinieblas de muerte en que voluntaria y pertinazmente se hallan sepultados. ¡Nuestro Juvenco expresa al vivo esta horrible imprecación!
Hoc magis inclamant: Nos, nos cruor iste sequatur,
Et genus in nostrum scelus hoc et culpa redundet.
26 o. Los romanos acostumbraban hacer azotar a los que condenaban a ser crucificados, antes de ponerlos en la cruz. San Jerónimo. Pero por el Evangelio de San Juan (cap. 19), se ve que Pilato había hecho azotar a Jesús con el designio de suavizar el corazón de sus enemigos, creyendo que movidos de compasión, y satisfecho su furor, desistirían de pedir su muerte. Pero fue encender más la sed que tenían de verle crucificado. Y así, como perros rabiosos gritaban cada vez más, hasta que vieron cumplidos sus deseos. San Mateo no sigue aquí el orden preciso del tiempo en la narración de todas estas circunstancias. San Agustín.
27 p. El pretorio era la sala en que el gobernador daba audiencia, y oía en justicia.
q. La cohorte; esto es, los soldados romanos que la componían, y eran de seiscientos veinte y cinco, cuando estaba completa.
28 r. Chlamys, en latín paludamentum, significa propiamente un manto que usaban los reyes, y también los generales del ejército.
29 s. La corona en su origen fue símbolo del sol. Los reyes se la apropiaron después. Con esto parece que quisieron significar, que ellos eran para sus pueblos lo que el sol para el universo. Asimismo tomaron el cetro, emblema de la autoridad real, a ejemplo de los pastores, cuyo nombre igualmente se aplicaron: Homer. Iliad. lib. II, pues estos usan del cayado, para conducir y defender a sus ganados.
t. Como los judíos le habían acusado de que había querido usurpar el reino, los soldados le llenaron de ultrajes, tratándole como a rey de burlas, y con el mayor desprecio.
32 u. San Juan dice expresamente (19,17) que Jesús salió cargado con la cruz. Debe entenderse de la casa del gobernador, y que la llevó por toda la ciudad hasta salir de ella. Pero allí agobiado de su peso, y sin aliento por la mucha sangre que había derramado, le faltaron las fuerzas para continuar llevándola hasta el lugar mismo del suplicio.
Sus enemigos, viéndole en aquel estado, temiendo que se les moriría antes de llegar, y que no tendrían la satisfacción de verle crucificado, obligaron a cargar con la cruz de Jesucristo a un hombre que encontraron al salir de la ciudad. Era este natural u oriundo de la provincia de Cirene en África, y se llamaba Simón. San Agustín cree, que Simón llevó sólo la cruz desde este sitio, como el Señor la había traído hasta allí desde la casa de Pilato. Otros creen, que solamente ayudó a Jesús a llevarla. El verbo latino angario viene del griego angaréuein, que es alquilar u obligar por fuerza a alguno para algún trabajo o servicio del público.
33 v. Gólgota: se llamaba así este monte vecino a Jerusalén, o por su figura redonda a manera de cabeza, por la cual, aun en nuestros escritos y autores antiguos se llamaba cabezos las cimas de los montes, y los collados pequeños y redondos, y se deriva de una palabra siria o caldea, que los hebreos, corrompiéndola, pronunciaban gulgolelh, y significa cabeza, o según San Jerónimo, por las muchas calaveras o cráneos que allí había de los que eran ajusticiados, siendo aquel monte el lugar destinado para ello. Muchos Padres, como son Orígenes, San Atanasio, San Ambrosio, San Basilio, San Epifanio, San Juan Crisóstomo y otros, apoyados en una antigua tradición, sienten, que se llamó así por haberse encontrado en él la calavera de Adán, que fue enterrado allí por particular disposición del Señor, y que el segundo Adán eligió, para sufrir la muerte y rescatar a todo el género humano, el lugar mismo en donde reposaba el primero, que había sido el principio de la muerte de todos los hombres. Y aunque San Jerónimo desecha esta tradición, nos debe bastar la autoridad de tantos y tan graves Padres, para no dejar de referirla.
34 w. San Marcos dice vinum myrrathum, vino con mirra. Era costumbre dar a los que iban a sufrir el último suplicio, para confortarlos (a manera de lo que se practica hoy día entre nosotros), vino generoso, que tal vez esto significa figuradamente el adjetivo myrrathum, o mezclado efectivamente con mirra, como usaban por regalo los antiguos. Y para guardar aquellos crueles verdugos esta costumbre con Jesucristo, pero con desprecio y nuevo tormento, en vez de mirra lo mezclaron con hiel, como dice San Mateo; lo que San Marcos llama myrrathum, porque se dio en lugar de mirra. Véase Baronio. El Griego le llama vinagre, como que con la hiel se corrompió, e hizo tan desabrido o mas que él.
35 x. Los soldados dividieron en cuatro partes las ropas exteriores del Señor, y las sortearon entre sí; y del mismo modo sortearon la túnica, que era sin costura tejida toda de arriba abajo. Circunstancia, que con particularidad había profetizado el rey David (Sal 20,19), diciendo: Diviserunt sibi, etc. Partiéronse, etc.
38 y. La conversión de uno de ellos fue el primer fruto de la preciosísima sangre del Salvador.
41 z. El Griego: kái farisáion, y fariseos.
42 a. El Griego: kái pistéusomen, y le creeremos.
43 b. El Griego: pépoithen, es pretérito perfecto: y por tanto lo es también sin duda el latino confidit, confió, o ha confiado.
c. Puesto que se gloriaba de ser el Hijo de Dios.
44 d. San Mateo usa aquí de una expresión figurada, poniendo el plural por el singular. Pues San Lucas dice expresamente, que fue uno solo el que le empezó a zaherir; y en otro lugar escribe, que los soldados le presentaron vinagre, habiendo sido uno solo, como consta de los otros evangelistas. San Juan Crisóstomo con algunos otros Padres creyó, que al principio lo cargaron de injurias los dos ladrones; mas que el uno le adoró después como a Dios, mientras que el otro le blasfemaba; y que esto lo permitió así el Señor para dar una muestra más brillante de la eficacia de su gracia. La primera opinión, que es de San Agustín, es la que se sigue comúnmente.
45 e. Estas tinieblas no fueron efecto de algún eclipse natural; porque este sucede en el novilunio o conjunción del sol y de la luna, y entonces era el plenilunio u oposición. Fuera de esto, el eclipse natural, aunque sea total o central, no se extiende a toda la tierra, sino a una parte de ella; y estas tinieblas nos dice el Evangelio que ocuparon toda la tierra por espacio de tres horas, que fue el tiempo que estuvo el Señor en la cruz, hasta que expiró. Este solo milagro, siendo tan grande por sí mismo, y habiendo sucedido en el tiempo en que se vio, debía bastar para convertir a todos los judíos. San Juan Crisóstomo.
46 f. Palabras tomadas del Salmo 21,1, y pronunciadas parte en hebreo, parte en siríaco. Este clamor, según San Juan Crisóstomo, manifiesta el poder supremo y absoluto que tenía el Señor de dejar su vida, o de volverla a tomar, cuando quisiera; porque no parece natural, que un hombre acabado con tanto padecer, y después de haber derramado tanta sangre, pudiese clamar con tan grande esfuerzo algunos momentos antes de expirar. Se debe tener presente lo que dejamos advertido en la nota a 26,30, para no extrañar esta que parece queja del abandono, en que le había dejado su Padre eterno; pero que manifestaba el estado espantoso a que le había reducido la malicia de los hombres, el horror que Dios mostraba al pecado cometido contra su divina Majestad, y que solamente un hombre Dios podía expiar por el mérito infinito de su muerte, y últimamente su amor inefable a los mismos hombres, puesto que abandonó de esta suerte a su propio Hijo para salvarnos por su muerte. San León.
47 g. Es probable, y San Jerónimo lo dice expresamente, que estos fueron los soldados romanos, los cuales no entendiendo la lengua hebrea, ni lo que significaban las palabras Eli, Eli, se persuadieron que llamaba en su socorro al profeta Elías.
50 h. El verbo emitto. y lo mismo el original Griego, afíemi significa acción voluntaria, para que se vea siempre cumplida la profecía de Isaías (53,7).
51 i. Orígenes y San Jerónimo creyeron, que este fue el velo exterior que cubría aquella parte del templo, a donde sólo entraban los sacerdotes; pero otros Padres entienden esto del velo interior, que cubría inmediatamente el santuario. Fuese cualquiera de los dos, se representaba por esto, que por la muerte del Salvador se rasgaba el velo de la antigua alianza, se nos descubrían todos los misterios, cumplidas ya todas las figuras; y que quedaba abierto el camino para entrar en el santuario de la Divinidad por el conocimiento de las más grandes verdades, y por la posesión del mismo Dios. San Juan Crisóstomo, Santo Tomás.
j. Movióse la tierra, o hubo terremoto y temblor de tierra.
53 k. Aunque parece por la manera con que habla el Evangelista, que los sepulcros se abrieron en el momento mismo en que expiró el Salvador; esto no obstante, parece cierto que los muertos no resucitaron sino después de la resurrección del Señor, pues se nota que no fueron vistos de muchos hasta este tiempo. Estos muertos, habiendo salido de los sepulcros que estaban fuera de la ciudad, vinieron a Jerusalén, y permitió Dios que fuesen vistos de muchas personas, para que este milagro teniendo muchos testigos entre los mismos judíos, sirviese de prueba para la resurrección de Jesucristo. Algunos creen, que no resucitaron sino por algún tiempo, y que murieron de nuevo. Y San Agustín parece haber encontrado grandes dificultades en admitir la opinión contraria; pero San Hilario, San Epifanio, Santo Tomás y otros autores antiguos y modernos no pueden inclinarse a creer que Jesucristo haya resucitado a estos santos para hacerlos volver al sepulcro; y han considerado su resurrección como el principio de su vida inmortal y bienaventurada.
55 l. El Griego: theoróusai, mirando.
m. MS. É que pensauan dél.
57 n. Esto es, pasada ya la hora en que el Señor expiró. Jesucristo murió a la hora de nona, o tres horas después de mediodía, cuando comenzaban las primeras vísperas, que duraban hasta ponerse el sol, en que daban principio las segundas, que continuaban hasta la noche. Esta distinción se observa en Mt 14,15, en donde se habla de las primeras; y después en el v. 25, que se debe entender de las segundas. Arimatea era un pueblo que distaba de Jerusalén cinco o seis leguas a la parte del Norte.
59 o. Los judíos lavaban los cadáveres, y cuando eran de personas ricas y de cualidad, los embalsamaban, no quitándoles las entrañas, como hacían los egipcios, y se practicó después en Occidente; sino empapándolas de un licor espeso de mirra, aloes, y otras drogas aromáticas: después los vendaban desde la cabeza hasta los pies con vendas anchas de lienzo, empapadas también del mismo licor. Y envolviéndolos después con una sábana nueva y muy blanca, los recostaban de esta suerte en el sepulcro sobre pequeños lechos. La cabeza y el rostro los cubrían con un lienzo, que llamaban sudario. Y así parece que fue enterrado el Señor. Véase Calmet. Disert. sobre los funerales y sepultura de los hebreos.
60 p. Esto lo dispuso así el Señor, para que los judíos no pudiesen calumniar ni decir, que era otro el que había resucitado. Al mismo tiempo debe reflexionar el cristiano con la mayor atención, cuánta es la pureza de corazón que se requiere para llegar a recibir en su pecho el adorable cuerpo del Señor, que no quiso ser depositado después de muerto en lugar en donde hubiese habitado la corrupción.
62 q. Este día de la Parasceve, o preparación era, según San Lucas (23,54), el que precedía al sábado; esto es, el viernes en que murió Jesucristo. Se llamaba día de preparación, porque en él se preparaba todo lo que era necesario para el mismo sábado; por cuanto este era día de descanso y del Señor, y no se podía trabajar en él. Y así fue la mañana del mismo sábado cuando acudieron a Pilato los príncipes de los sacerdotes y los fariseos.
63 r. El Griego: egéiromai, resucitó.
64 s. El Griego: nuktós, de noche.
t. Llaman error, engaño, la opinión que se tenía de que Jesús fuese el Cristo, o Hijo de Dios. Y así dicen, que este segundo engaño sería peor que el primero: puesto que por este medio se haría más creíble aquella opinión, y tomaría nuevo y mayor cuerpo.
65 u. Tenían los judíos una compañía de soldados para la guarda del templo: y Dios permitió, según la reflexión de San Juan Crisóstomo, que Pilato no quisiese que fuesen sus soldados los que guardasen el sepulcro; porque en este caso los judíos hubieran dicho, que se había concertado con los discípulos del Salvador, y que les habían entregado su cuerpo. Ellos mismos tomaron sobre sí este cuidado, y no omitieron medio alguno para evitar este robo, que temían de los discípulos. Mas ellos mismos se taparon la boca, para que no pudiesen culpar a ninguno, y se pusieron en la necesidad inevitable de reconocer en lo sucesivo, que aquel a quien habían tratado de impostor, había verdaderamente resucitado, como lo había dicho.</p>
<br/>




</div>
