<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 1</h2>
<p class="text-justify">Genealogía de Jesucristo, según la carne. El ángel revela a José el modo con que había concebido la Virgen. Nacimiento del Señor.
1 a. Esto es, descendiente de David y de Abraham, según la carne, como se ve por el árbol genealógico que aquí se pone.
3 b. De Tamar su nuera, y por tanto de un incesto; porque como Cristo vino a redimir pecadores, no rehusó nacer de pecadores. Por esta misma razón quiso que se nombrasen también Bersabé adúltera, y Rahab y Ruth, que fueron extranjeras y de humilde condición.
6 c. Mujer.
8 d. Joram no fue padre inmediato de Ozías, sino tercer abuelo; porque Joram engendró a Ocozías; Ocozías a Joás; Joás a Amasías; y Amasías a Ozías (1Cro 3,12). El profeta Elías había anunciado a Achab rey de Israel el exterminio de toda su descendencia. Y el Evangelista, al parecer, quiso ejecutar esta sentencia por una especie de muerte civil, a lo menos hasta la cuarta generación, en la genealogía de Jesucristo, porque Joram estuvo casado con Atalía hija de Achab, de la cual tuvo a Ocozías padre de Joás, que lo fue de Amasías, y este de Ozías, que también se llamó Azarías (2Cro 3).
11 e. A Jeconías: se debe entender no inmediatamente, sino por medio de Joaquim padre de Jeconías (1Cro 3,15-16). Este Joaquim no mereció tener lugar en la sepultura de los reyes de Judá (Jer 22,8). Y por esta razón San Mateo creyó, que tampoco debía ponerse en la genealogía de Jesucristo. Y sus hermanos: quiere decir, y a su hermano Sedecías (1Cro 3,16); o si tuvo otros, no los nombra la Escritura hebrea. En el tiempo, o hacia el tiempo de la transmigración, porque Josías ya había muerto, cuando sucedió ésta; la cual comenzó en el reinado de Joaquim su hijo, y se continuó en el de Jeconías (2Re 24,15 y 2Cro 36,1-2). En algunos manuscritos se lee: iosías dé egénnese tón iakéim: iakéim dé egénnese tón iekosían (Josías engendró a Jacim: Jacim engendró a Jeconías), etc., con la cual adición se completan las veinte y ocho generaciones que cuenta San Mateo desde David hasta Jesucristo; pues sin ella quedan defectuosas: a no ser que contemos en esta genealogía a María santísima, honra, que por haber concebido a Jesucristo sin comercio de varón, le hacen muchos, no obstante que las mujeres no tenían lugar en las genealogías.
f. MS. En el traspassamiento de Babilonia. En la cautividad.
12 g. Verificada ya la transmigración, y durante ella.
16 h. José era esposo y verdadero marido de María, non concubitu, sed affectu; non commixtione corporum, sed copulatione, quod est carius, animorum (no por cohabitación, sino en el afecto; no por conjunción de los cuerpos, sino por la unión de sus almas, lo cual es más íntimo), dice San Agustín, Contra Fausto, lib. XXIII, cap. VIII, y ésta es la sentencia más seguida de los Padres. Mandaba Dios a los israelitas, que no emparentasen sino con personas de la misma tribu y familia (Núm 36,6-8). Y por esto el árbol genealógico de San José, que pone aquí el Evangelista, es el mismo que el de María; por lo que siendo verdadera Madre de Jesucristo, se prueba evidentemente que este Señor era verdadero descendiente de David. Demás de esto, Jesucristo había sido prometido, como hijo de la mujer, y como hijo de David; esto es, como hombre y como rey. Para que se viese el cumplimiento de esta doble promesa, San Lucas, en su genealogía, hace subir hasta Adán su línea materna, de la cual nació hombre; y San Mateo en este lugar, para mostrar que era de la familia real de David, la trae desde este rey hasta José, que era tenido por su padre.
i. Cristo, nombre griego, que corresponde al hebreo Mesías, y quiere decir el Ungido. David en el Sal 64,9, dice, que fue ungido con óleo más abundante y grueso que todos los otros; de manera que sólo él es reconocido por el nombre de Cristo, cuando no se añade otro. Siendo Dios, se hizo hombre para ser ungido; y era de tal suerte hombre, que al mismo tiempo era Dios. Fue ungido como rey, como profeta y como sacerdote, quedando en su Encarnación sumo Pontífice de la ley nueva (Sal 99,4).
18 j. Esto es, prometida, según la loable antiquísima costumbre de interponer un cierto espacio de tiempo entre la promesa o esponsales, y la celebración o consumación del matrimonio (Gén 19,14; Dt 20,7; 22,23).
k. El Evangelista nos refiere lo que sucedió en verdad; esto es, que María concibió en su seno virginal, antes que José la conociese. Mas de aquí no se ha de inferir que la conociese después; porque la Iglesia tuvo siempre por herejes a los que afirman esto. San Jerónimo.
l. Esto es, por virtud y operación milagrosa y sobrenatural del Espíritu Santo. La concepción del Verbo, aunque común a todas tres divinas Personas, se atribuye especialmente al Espíritu Santo; porque así como se atribuye al Padre el poder, y al Hijo la sabiduría, del mismo modo se atribuyen al Espíritu Santo las obras de caridad y de santidad; y entre éstas la principal y la mayor fue la Encarnación del Verbo Eterno.
19 m. La palabra latina vir, como la griega anér, es común al prometido, o que tiene dados esponsales, y al casado, como la voz esposo entre nosotros.
n. Se hallaba perplejo, sin saber qué partido tomar. Por una parte, su rectitud, viendo la preñez de la Virgen, le inclinaba a no vivir en su compañía; por otra, la estimación y concepto en que la tenía, no le permitían exponerla al rigor de la ley; y así se determinó a dejarla secretamente.
o. El Griego: paradeigmatísai, significa: Hacer un ejemplar, o un escarmiento; acusándola en juicio como adúltera, o repudiándola públicamente, como mandaba Dios en el Dt 24,1.
20 p. Llevándola por la primera vez a su casa, o continuando en vivir con ella, según los diversos pareceres de los intérpretes.
q. Lo que ha concebido en su purísimo vientre.
21 r. Salvador, o salud. Este es el nombre que propiamente convenía al Hijo de Dios en su Encarnación; porque venía a merecer, y dar a su pueblo la salud eterna.
22 s. Para mostrar la conformidad del cumplimiento con la predicción. La predicción no fue ocasión del cumplimiento, sino que el profeta anunció lo que había de suceder, y estaba ya eternamente decretado. Es una de las más insignes profecías del Antiguo Testamento.
23 t. La Virgen. En el original encierra particular énfasis el artículo he parthénos, la Virgen, como si dijera: aquella Virgen o doncella, señalada y privilegiada, que Dios escogió ab aeterno, para que concibiese y pariese al Redentor del género humano.
25 u. Véase lo que dejamos dicho en la nota (v. 18, 6). Es frase de Escritura decir &quot;hasta que&quot;, por &quot;jamás&quot; (Is 22,14). Este pecado no os será perdonado hasta la muerte; esto es, jamás.
v. De llamar el Evangelio hijo primogénito a Jesucristo, no se infiere que María tuviese después otros, sino que no los tuvo antes. La ley ordenaba a los judíos ofrecer a Dios sus primogénitos. Para esto, luego que nacía el primero, se llamaba primogénito, naciesen o no después otros. De manera, que en tón protótokon, el artículo tón denota relación a aquel, de quien antes había hablado el ángel, y no distinción, como si después de Jesucristo hubiera tenido otros hijos.</p>
<br/>




</div>
