<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">2. LA PRIMERA PAREJA DESOBEDECE A DIOS, 3:1-24
Este es uno de los capítulos más importantes de la revelación bíblica. Declara que las relaciones distorsionadas del hombre con Dios, con sus semejantes, con el universo y consigo mismo tienen su origen en la desobediencia de la primera pareja y en la imitación a ella que cada ser humano realiza. Establece al mismo tiempo la fidelidad de Dios a su propósito de comunión con el hombre, manifestando el inicio de su obra redentora. Se debe considerar este capítulo en su complementación revelatoria en Rom 5:12-21; Efesios 5:21-6:9 y en contraste con la perfecta obediencia de Jesucristo (Phi 2:1-11).
(1) La pareja cede a la tentación de la serpiente,Phi 3:1-13. La serpiente, instrumento externo de tentación, ofrece a la mujer un destino mejor del que Dios había establecido para la pareja. Apela a la satisfacción de las necesidades más básicas del ser humano: sustento, desarrollo ilimitado de sus capacidades y deseo de controlar el destino de sus vidas sin depender de un ser superior (Dios).
La mujer no cede inicialmente a la tentación, sino después de un proceso de evaluación externa e interna que finalmente la lleva a concluir que el árbol es bueno, atractivo y codiciable. La Biblia repetidamente advierte al hombre del peligro de este proceso mental y emocional hacia el pecado (Mat 5:27-28; Jam 1:14-15; 1Jo 2:16). La mujer come del árbol dando también a su marido quien aparentemente estaba con ella todo el tiempo. El hombre también escoge desobedecer a Dios admitiendo luego su decisión libre y su acción individual (v. 12). El apóstol Pablo responsabiliza a la desobediencia de Adán la entrada del pecado y la muerte en la raza humana (Rom 5:12-21; 1Co 15:21-22), admitiendo que la desobediencia de Eva también tiene su consecuencia específica en la mujer (2Ti 2:11-15).
Adán Pero para Adán... (2Ti 2:20). Esta es la primera vez en todo el relato que en la traducción RVA y en la Biblia de las Américas aparece el término &quot;Adán&quot; usado como nombre propio.
La nota de pie de RVA llama la atención a que puede traducirse: &quot;pero para el hombre&quot;. RVR-60 usa Adán H120 por primera vez en 2:19. La Biblia de Jerusalén lo hace hasta 4:25 como también la versión Dios Habla Hoy.
El nombre &quot;Adán&quot; es una palabra que significa: de la tierra o tomado de la tierra roja. De acuerdo con la genealogía de Luk 3:38 resulta ser el &quot;hijo de Dios&quot;. El hecho sencillo es que el ser humano no es tan individual e independiente de toda la raza. Lo que una persona es y hace afecta a toda la sociedad en mayor o menor grado.
Eva
Le haré ayuda idónea (Luk 2:18). Esta es una expresión frecuentemente mal interpretada y mal aplicada. La palabra &quot;ayuda&quot; viene de la voz hebrea ezer H5828 que describe la fuerza, energía o impulso que viene de alguien superior al que recibe la ayuda. En este caso, es Dios quien ayuda al hombre por medio de su mujer. La mujer no es el ayudante del hombre como un peón lo es a su capataz. No es una ayuda subordinada, sino superior, pues es la ayuda que Dios da.
La palabra &quot;idónea&quot; es la traducción del vocablo kenegdo H5048, que significa &quot;adecuada para...&quot; o &quot;que cumple a cabalidad&quot;. La mujer no es igual al hombre, es diferente, es la contraparte, fue hecha de tal manera para cumplir el propósito y el plan del Señor.
El mensaje es claro: el hombre y la mujer no están completos el uno sin el otro. Se necesitan mutuamente.
El conocimiento que adquieren el hombre y la mujer los hacen sentir con vergüenza uno del otro, contrario a la relación mutua anterior (Luk 2:25) y con temor ante la presencia de Dios. A las preguntas de Dios, el hombre y la mujer intentan eludir su responsabilidad aunque admiten su acción desobediente.
(2) La desobediencia trae sus consecuencias,Luk 3:14-24. Dios se dirige primero a la serpiente. La maldición que recibe es la de una vida precaria y por engañar a la mujer, una hostilidad permanente entre la serpiente y la humanidad. Aquí se rompe la armonía entre el hombre y los animales. Por la identificación posterior de la serpiente con Satanás (Apoc. 12:9; 20:3), la afirmación de que será aplastada se convierte en una promesa de salvación. Esta promesa se cumple en Jesucristo, nacido de mujer (Gal 4:4) e hijo de Adán (Luk 3:38), quien en la culminación del plan redentor de Dios vence totalmente a la serpiente (Apoc. 20:10).
La consecuencia en la mujer está directamente relacionada con su papel de madre y de esposa. El desarrollo y realización de la maternidad será con dolor y sufrimiento. Como mujer tendrá deseo hacia un marido quien ejercerá control sobre ella.
Aquí se rompe la igualdad y mutualidad intentada por Dios en la creación de la pareja. Las relaciones de pareja no son ya ideales. Esta relación distorsionada se traslada luego a todas las otras esferas de relaciones sociales.
La triple T Y fueron abiertos los ojos de ambos, y se dieron cuenta de que estaban desnudos. Entonces cosieron hojas de higuera, y se hicieron ceñidores (3:7). La triple &quot;T&quot; de aquel evento se repite en nuestra propia experiencia:
* Tentación, es la invitación a desobedecer al Señor.
* Transgresión, es la violación de la orden del Señor.
* Tragedia, es el resultado de la desobediencia.
Tentación, transgresión y tragedia pintan el cuadro triste de la tentación y la caída en el pecado. El acto fue sencillo, pero la desobediencia fue de graves consecuencias. Toda la humanidad, descendencia de Adán, fue afectada por la muerte. Más tarde Pablo escribe que &quot;en Adán todos morimos&quot;.
Dios declara al hombre tres consecuencias permanentes: Primera, la tierra, medio de su vida y del desarrollo de su vocación, es maldita. Aquí se pierde la armonía tierrahombre del jardín. Segunda, la tierra en su hostilidad causa dificultades y penas al hombre en el cumplimiento de su papel como el proveedor de sustento. Aquí se rompe la armonía y satisfacción que el trabajo debería acarrear al hombre. Se debe aclarar que el trabajo en sí mismo no es maldición, sino que se convierte en una fuente de penas y fracasos al proveer el sustento. Tercera, la vida del hombre tiene un límite definitivo ahora. El hombre deberá volver a la tierra en la experiencia de la muerte. Aquí se reconoce que la vida en la tierra, además de presentar dificultades en todas las áreas, tiene definitivamente su límite. La muerte en este sentido no es la alternativa de la vida, sino
la limitación de la vida terrenal. El apóstol Pablo expresa esta realidad cuando afirma que la paga del pecado es muerte (Rom 6:23a). Aquí también se descubre la mentira de la serpiente a la mujer: No moriréis (v. 4). Dios, el Dios de la vida, provee más adelante un Salvador que anula las consecuencias del pecado en el hombre, la sociedad y la naturaleza (Rom 6:23b; Act 3:10-21).
Verdad práctica Seréis como Dios, conociendo el bien y el mal (Act 3:4). La media verdad es mucho más dañina que la mentira. El tentador dijo a la mujer que al comer de la fruta prohibida tendrían la capacidad de conocer el bien y el mal. Una media verdad era que sus ojos serían abiertos y que efectivamente iban a experimentar la diferencia entre el bien y el mal. La otra media verdad era que, al tener esa experiencia, habrían desobedecido la palabra de Dios y por lo tanto no podrían volver a su estado de inocencia. Satanás atrae con &quot;carnadas&quot; que parecen la verdad, pero que resultan ser un una trampa mortal.
Dios muestra su gran misericordia a través de tres acciones concretas. Primera, permite la continuación de la raza humana. Adán reconoce esto al llamar a su mujer Eva y declarar que ella sería la madre de todos los vivientes (v. 20). Segunda, Dios viste al hombre y a la mujer, restaurando así parcialmente la relación hombremujer destruida por la desobediencia. Tercera, Dios saca a Adán y Eva del jardín preparado especialmente para el desarrollo de la vida. El hombre no quiso vivir con responsabilidad y respetar las limitaciones que Dios le había puesto. Por su nueva condición de búsqueda de autonomía e independencia de Dios es expulsado del jardín. Más que un castigo, este acto de Dios está lleno de misericordia. El jardín con el árbol de la vida se convierte en un lugar muy peligroso para el hombre. Dios entonces se asegura que el hombre no tenga acceso a algo que le pudiera perjudicar aún más. Tanto el jardín como el árbol de vida quedan como promesas de concesión a los creyentes en Cristo Jesús (Apoc. 2:7; 22:1-5).
Promesa y profecía Esta te herirá en la cabeza, y tu le herirás en el talón (3:15). Aquí encontramos una promesa y una profecía. De la simiente de la mujer nacería alguien que tendría la capacidad de vengar el engaño hecho a la mujer. Los llamados Padres de la iglesia vieron en este versículo el protoevangelio y la promesa de Jehová de proveer a Jesucristo para restaurar la comunión rota con él.
Castigo Con dolor comerás de ella todos los días de tu vida (3:17). La Biblia no nos dice cuánto tiempo Adán vivió en el estado de inocencia y pureza, pero perdió todas las bendiciones cuando escuchó la voz del tentador. Fue arrojado de su posición como administrador del jardín en Edén y condenado a vivir como labrador de la tierra de la cual fue tomado. De aquí en adelante, tendría que ganar su sustento con el sudor de su frente y saborear la frustración de cultivar la tierra con tanto esfuerzo y ver brotar espinos y cardos (3:17-23).</p>
<br/>
<p class="text-justify">2. LA PRIMERA PAREJA DESOBEDECE A DIOS, 3:1-24
Este es uno de los capítulos más importantes de la revelación bíblica. Declara que las relaciones distorsionadas del hombre con Dios, con sus semejantes, con el universo y consigo mismo tienen su origen en la desobediencia de la primera pareja y en la imitación a ella que cada ser humano realiza. Establece al mismo tiempo la fidelidad de Dios a su propósito de comunión con el hombre, manifestando el inicio de su obra redentora. Se debe considerar este capítulo en su complementación revelatoria en Rom 5:12-21; Efesios 5:21-6:9 y en contraste con la perfecta obediencia de Jesucristo (Phi 2:1-11).
(1) La pareja cede a la tentación de la serpiente,Phi 3:1-13. La serpiente, instrumento externo de tentación, ofrece a la mujer un destino mejor del que Dios había establecido para la pareja. Apela a la satisfacción de las necesidades más básicas del ser humano: sustento, desarrollo ilimitado de sus capacidades y deseo de controlar el destino de sus vidas sin depender de un ser superior (Dios).
La mujer no cede inicialmente a la tentación, sino después de un proceso de evaluación externa e interna que finalmente la lleva a concluir que el árbol es bueno, atractivo y codiciable. La Biblia repetidamente advierte al hombre del peligro de este proceso mental y emocional hacia el pecado (Mat 5:27-28; Jam 1:14-15; 1Jo 2:16). La mujer come del árbol dando también a su marido quien aparentemente estaba con ella todo el tiempo. El hombre también escoge desobedecer a Dios admitiendo luego su decisión libre y su acción individual (v. 12). El apóstol Pablo responsabiliza a la desobediencia de Adán la entrada del pecado y la muerte en la raza humana (Rom 5:12-21; 1Co 15:21-22), admitiendo que la desobediencia de Eva también tiene su consecuencia específica en la mujer (2Ti 2:11-15).
Adán Pero para Adán... (2Ti 2:20). Esta es la primera vez en todo el relato que en la traducción RVA y en la Biblia de las Américas aparece el término &quot;Adán&quot; usado como nombre propio.
La nota de pie de RVA llama la atención a que puede traducirse: &quot;pero para el hombre&quot;. RVR-60 usa Adán H120 por primera vez en 2:19. La Biblia de Jerusalén lo hace hasta 4:25 como también la versión Dios Habla Hoy.
El nombre &quot;Adán&quot; es una palabra que significa: de la tierra o tomado de la tierra roja. De acuerdo con la genealogía de Luk 3:38 resulta ser el &quot;hijo de Dios&quot;. El hecho sencillo es que el ser humano no es tan individual e independiente de toda la raza. Lo que una persona es y hace afecta a toda la sociedad en mayor o menor grado.
Eva
Le haré ayuda idónea (Luk 2:18). Esta es una expresión frecuentemente mal interpretada y mal aplicada. La palabra &quot;ayuda&quot; viene de la voz hebrea ezer H5828 que describe la fuerza, energía o impulso que viene de alguien superior al que recibe la ayuda. En este caso, es Dios quien ayuda al hombre por medio de su mujer. La mujer no es el ayudante del hombre como un peón lo es a su capataz. No es una ayuda subordinada, sino superior, pues es la ayuda que Dios da.
La palabra &quot;idónea&quot; es la traducción del vocablo kenegdo H5048, que significa &quot;adecuada para...&quot; o &quot;que cumple a cabalidad&quot;. La mujer no es igual al hombre, es diferente, es la contraparte, fue hecha de tal manera para cumplir el propósito y el plan del Señor.
El mensaje es claro: el hombre y la mujer no están completos el uno sin el otro. Se necesitan mutuamente.
El conocimiento que adquieren el hombre y la mujer los hacen sentir con vergüenza uno del otro, contrario a la relación mutua anterior (Luk 2:25) y con temor ante la presencia de Dios. A las preguntas de Dios, el hombre y la mujer intentan eludir su responsabilidad aunque admiten su acción desobediente.
(2) La desobediencia trae sus consecuencias,Luk 3:14-24. Dios se dirige primero a la serpiente. La maldición que recibe es la de una vida precaria y por engañar a la mujer, una hostilidad permanente entre la serpiente y la humanidad. Aquí se rompe la armonía entre el hombre y los animales. Por la identificación posterior de la serpiente con Satanás (Apoc. 12:9; 20:3), la afirmación de que será aplastada se convierte en una promesa de salvación. Esta promesa se cumple en Jesucristo, nacido de mujer (Gal 4:4) e hijo de Adán (Luk 3:38), quien en la culminación del plan redentor de Dios vence totalmente a la serpiente (Apoc. 20:10).
La consecuencia en la mujer está directamente relacionada con su papel de madre y de esposa. El desarrollo y realización de la maternidad será con dolor y sufrimiento. Como mujer tendrá deseo hacia un marido quien ejercerá control sobre ella.
Aquí se rompe la igualdad y mutualidad intentada por Dios en la creación de la pareja. Las relaciones de pareja no son ya ideales. Esta relación distorsionada se traslada luego a todas las otras esferas de relaciones sociales.
La triple T Y fueron abiertos los ojos de ambos, y se dieron cuenta de que estaban desnudos. Entonces cosieron hojas de higuera, y se hicieron ceñidores (3:7). La triple &quot;T&quot; de aquel evento se repite en nuestra propia experiencia:
* Tentación, es la invitación a desobedecer al Señor.
* Transgresión, es la violación de la orden del Señor.
* Tragedia, es el resultado de la desobediencia.
Tentación, transgresión y tragedia pintan el cuadro triste de la tentación y la caída en el pecado. El acto fue sencillo, pero la desobediencia fue de graves consecuencias. Toda la humanidad, descendencia de Adán, fue afectada por la muerte. Más tarde Pablo escribe que &quot;en Adán todos morimos&quot;.
Dios declara al hombre tres consecuencias permanentes: Primera, la tierra, medio de su vida y del desarrollo de su vocación, es maldita. Aquí se pierde la armonía tierrahombre del jardín. Segunda, la tierra en su hostilidad causa dificultades y penas al hombre en el cumplimiento de su papel como el proveedor de sustento. Aquí se rompe la armonía y satisfacción que el trabajo debería acarrear al hombre. Se debe aclarar que el trabajo en sí mismo no es maldición, sino que se convierte en una fuente de penas y fracasos al proveer el sustento. Tercera, la vida del hombre tiene un límite definitivo ahora. El hombre deberá volver a la tierra en la experiencia de la muerte. Aquí se reconoce que la vida en la tierra, además de presentar dificultades en todas las áreas, tiene definitivamente su límite. La muerte en este sentido no es la alternativa de la vida, sino
la limitación de la vida terrenal. El apóstol Pablo expresa esta realidad cuando afirma que la paga del pecado es muerte (Rom 6:23a). Aquí también se descubre la mentira de la serpiente a la mujer: No moriréis (v. 4). Dios, el Dios de la vida, provee más adelante un Salvador que anula las consecuencias del pecado en el hombre, la sociedad y la naturaleza (Rom 6:23b; Act 3:10-21).
Verdad práctica Seréis como Dios, conociendo el bien y el mal (Act 3:4). La media verdad es mucho más dañina que la mentira. El tentador dijo a la mujer que al comer de la fruta prohibida tendrían la capacidad de conocer el bien y el mal. Una media verdad era que sus ojos serían abiertos y que efectivamente iban a experimentar la diferencia entre el bien y el mal. La otra media verdad era que, al tener esa experiencia, habrían desobedecido la palabra de Dios y por lo tanto no podrían volver a su estado de inocencia. Satanás atrae con &quot;carnadas&quot; que parecen la verdad, pero que resultan ser un una trampa mortal.
Dios muestra su gran misericordia a través de tres acciones concretas. Primera, permite la continuación de la raza humana. Adán reconoce esto al llamar a su mujer Eva y declarar que ella sería la madre de todos los vivientes (v. 20). Segunda, Dios viste al hombre y a la mujer, restaurando así parcialmente la relación hombremujer destruida por la desobediencia. Tercera, Dios saca a Adán y Eva del jardín preparado especialmente para el desarrollo de la vida. El hombre no quiso vivir con responsabilidad y respetar las limitaciones que Dios le había puesto. Por su nueva condición de búsqueda de autonomía e independencia de Dios es expulsado del jardín. Más que un castigo, este acto de Dios está lleno de misericordia. El jardín con el árbol de la vida se convierte en un lugar muy peligroso para el hombre. Dios entonces se asegura que el hombre no tenga acceso a algo que le pudiera perjudicar aún más. Tanto el jardín como el árbol de vida quedan como promesas de concesión a los creyentes en Cristo Jesús (Apoc. 2:7; 22:1-5).
Promesa y profecía Esta te herirá en la cabeza, y tu le herirás en el talón (3:15). Aquí encontramos una promesa y una profecía. De la simiente de la mujer nacería alguien que tendría la capacidad de vengar el engaño hecho a la mujer. Los llamados Padres de la iglesia vieron en este versículo el protoevangelio y la promesa de Jehová de proveer a Jesucristo para restaurar la comunión rota con él.
Castigo Con dolor comerás de ella todos los días de tu vida (3:17). La Biblia no nos dice cuánto tiempo Adán vivió en el estado de inocencia y pureza, pero perdió todas las bendiciones cuando escuchó la voz del tentador. Fue arrojado de su posición como administrador del jardín en Edén y condenado a vivir como labrador de la tierra de la cual fue tomado. De aquí en adelante, tendría que ganar su sustento con el sudor de su frente y saborear la frustración de cultivar la tierra con tanto esfuerzo y ver brotar espinos y cardos (3:17-23).</p>
<br/>




</div>
