<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 49</h2>
<p class="text-justify">(3) Jacob bendice a sus hijos, 49:1-28. La bendición patriarcal a la generación siguiente era muy importante. Por ello Jacob, antes de morir, reúne a sus doce hijos y los bendice. La bendición consiste en pronunciamientos con referencia a eventos del pasado, situaciones del presente y visión del futuro como historia desde la perspectiva de Dios y sus promesas. Tiene un significado peculiar porque las obligaciones y privilegios del pacto son transmitidos así a la siguiente generación. Se pueden notar varias características en la bendición de Jacob. Primera, su propósito es dar a cada hijo como originador de tribu, la dirección y orientación necesaria para el futuro desde la perspectiva del propósito de Dios. En este sentido, la bendición es una profecía y su cumplimiento es certero e inalterable. Segunda, se hacen referencias a experiencias y eventos pasados en la vida de algunos de los patriarcas, porque dichos eventos han de afectar la historia de la tribu originada por ellos. Aquí se nota la importancia que tienen las decisiones y acciones de personas con una importante responsabilidad histórica. Tercera, se vislumbra el papel político y religioso que ha de tocar a cada tribu y aún la asignación territorial que han de recibir. Esta visión siempre está orientada desde la perspectiva del propósito divino. Cuarta, la bendición es a cada uno y a todos los hijos y no solamente al primogénito como en los patriarcas anteriores. Este hecho se debe a que estos doce hijos de Jacob, son los antepasados que dan origen a las doce tribus de Israel. Manasés y Efraín ya quedaron incluidos en la bendición anterior suplantando ambos a su padre José. En el desarrollo de la nación de Israel, hubo doce tribus con asignación territorial y una (Leví) sin asignación territorial. Los dos hijos de José, Manasés y Efraín completan las doce tribus territoriales, pero cuando se habla de las doce tribus, se los unen y ambos representan a José.
Semillero homilético El Dios de nuestros padres
48:15, 16
Introducción : La naturaleza del Dios que adora una persona tendrá gran peso sobre esa persona, sus valores, su comportamiento y su visión mundial. Jacob había tenido muchas experiencias con Dios durante sus largos años. En su vejez piensa en estas grandes bendiciones. La bendición de Jacob contiene los temas principales de todo el libro de Génesis. Veamos:
I. Dios es identificado como el Dios en cuya presencia anduvieron mis padres. Se presenta a un Dios que se relaciona y comunica con su pueblo; además se subraya que aquellos patriarcas fueron lo que fueron por causa de su dedicación a &quot;andar delante de Dios&quot;. Por supuesto, Dios es el eslabón que une a cada uno de los patriarcas de los que surgirá el pueblo del pacto.
II. Tenemos un sumario de fe, una declaración de la teología básica que conecta e identifica la verdadera fe a través de muchas generaciones. Dios es descrito como el Dios que me pastorea y el ángel que me redime de todo mal. Aunque muy pocas veces en la Biblia se identifica a Dios como un ángel, pues él es quien envía a los ángeles, sin embargo debemos recordar que hasta ahora Jacob era el único de los patriarcas que había sido visitado por un ángel (22:11). Dios es quien nos salva, cuida y guarda de todo mal.
III. El acto de bendecir a los dos hijos de José levanta el tema de la tierra prometida a Abraham. Ellos también serán llamados por el &quot;nombre&quot; de Jacob y el nombre de Isaac y Abraham. Tal como Dios lo había prometido a Abraham: Yo haré de ti una gran nación... engrandeceré tu nombre (12:2).
Conclusión : Jacob pudo reflexionar sobre su vida y las muchas experiencias con Dios, y reconocer que Dios lo había acompañado, de acuerdo con la declaración en Gen 28:20. ¿Podemos hacer lo mismo?
Se pueden notar algunos hechos resaltantes en relación a algunos de los hijos en estos pronunciamientos. Rubén, por su comportamiento vil y usurpador, pierde el derecho a la primogenitura. Judá, como tribu, recibe una atención especial. Se resalta su prominencia política en el sentido de que tendrá permanentemente un gobernador propio y será líder a las demás tribus de las que ha de recibir alabanzas. El cumplimiento histórico del sueño de José se proyecta para la tribu de Judá. Los demás pueblos también estarán en sujeción a Judá. El v. 10 se considera un pasaje mesiánico que se refiere al reinado universal del Mesías. La bendición a José indica que él es considerado como primogénito y responsable de la continuación del pacto. Primero se desea la fecundidad y prosperidad de esta tribu. Luego se lo conecta íntimamente con el Dios de la tradición patriarcal descripto con diferentes nombres. Y finalmente, se pronuncian bendiciones sobre esta tribu en todos los aspectos de su vida.
Aclaración: ¿Fueron setenta? En Gen 46:8-27 el relato dice claramente que el total de los miembros de la familia de Jacob que entraron en Egipto fueron setenta. Sin embargo, dentro de este pasaje se alcanza esta cifra de dos maneras diferentes. Primero hay una lista general de la familia de Jacob con el subtotal de treinta y tres (v. 15), dieciséis (v. 18), catorce (v. 22) y siete (v. 25), lo cual suma setenta. En esta lista se incluye a Jacob mismo (observe la inclusión de Jacob y sus hijos a los nombres de los hijos de Israel que entraron a Egipto, v. 8. En nuestra RVA se diluye la adición por medio de colocar los dos puntos y no el punto y seguido o punto y coma que la lectura del hebreo sugiere); también se incluye a José (v. 19) y a sus dos hijos nacidos en Egipto (v. 20), pero no se mencionan a Er y a Onán (v. 12) quienes murieron en Canaan antes del viaje a Egipto. El subtotal en la lista también incluye a Dina (v. 15). La dificultad en la lista radica en la adición: El total de las personas de sus hijos y de sus hijas, la cual parece excluir a Jacob, pero el v. 8 ya trató el problema.
Por otra parte, el subtotal dado en los vv. 26 y 27: Todas las personas fueron sesenta y seis. Esto es lógico, pues excluye a las esposas de los hijos de Jacob que no eran sus descendientes directos. Cuando se añade a Dina, Sera, Efraín y Manasés, el total es setenta.
El número setenta es consistente con Exo 1:5 y Deu 10:22, en donde claramente se dice que fueron setenta los hijos de Israel que fueron a Egipto.
Es interesante que en la Septuaginta se añaden cinco nombres más en el v. 20. Los nombres se tomaron de Num 26:29-36. Consecuentemente esa versión dice en Exo 1:5 que fueron setenta y cinco quienes fueron a Egipto. Sin duda fue esta tradición la que citó Esteban en Act 7:14 (recordemos que la Septuaginta fue la Biblia de los hebreos del tiempo de Jesús). Una nota que ayuda es que tanto en la Septuaginta como en los textos de Qumran no se dice los descendientes de Jacob, sino &quot;el número de los hijos de Dios&quot;.
El uso del número &quot;setenta&quot; no es caprichoso, pues encontramos en Génesis 10 que el número de las naciones fue setenta. Lo que encontramos en este relato es la demostración del tema de Deu 32:8 que fue Dios quien estableció los límites y la estructura del pueblo hebreo en medio de todas las naciones de la tierra. Con una nación tan pequeña entre un número tan grande de otras naciones Dios cumplirá su propósito y llevará a cabo sus planes.
Rubén : Inestable como el agua Rubén el hijo primogénito de Jacob (Deu 49:3-4), recibe una bendición limitada y casi hasta un castigo por haber cometido el pecado de incesto. Aunque la tribu adquiere un mediano tamaño nunca llega a tener verdadera importancia. Para los días de Moisés apenas cuenta con unos pocos hombres competentes para la guerra.
Estos hechos nos demuestran que la falta de fidelidad a los principios de la palabra del Señor producen un carácter inestable como el agua. Es decir que siempre tiende a buscar el nivel más bajo y no retiene sus estados (líquido, gaseoso, sólido) por ella misma, sino depende de las circunstancia que la rodean.
Debilidad transformada en fuerza
Simeón y Levi se caracterizaron por un carácter violento y la historia del ataque alevoso contra los hombres de Siquem lo confirma (Deu 34:1-31). Muchos años más tarde, sin embargo, cuando Dios pide que los que estén de su parte den un paso al frente, los levitas lo hicieron y se mantuvieron firmes en la defensa de la causa del Señor (Exo 32:25-29). Como resultado, Dios los escogió para que fueran los sacerdotes de Israel. Dios puede transformar las debilidades de nuestro carácter en fuerza, eso fue lo que hizo con los descendientes de Levi. Cualquiera que sea la debilidad de nuestro carácter llevémosla con confianza delante del Señor y pidamos que lo cambie y lo use de modo que sea para honra de su nombre.</p>
<br/>
<p class="text-justify">(3) Jacob bendice a sus hijos, 49:1-28. La bendición patriarcal a la generación siguiente era muy importante. Por ello Jacob, antes de morir, reúne a sus doce hijos y los bendice. La bendición consiste en pronunciamientos con referencia a eventos del pasado, situaciones del presente y visión del futuro como historia desde la perspectiva de Dios y sus promesas. Tiene un significado peculiar porque las obligaciones y privilegios del pacto son transmitidos así a la siguiente generación. Se pueden notar varias características en la bendición de Jacob. Primera, su propósito es dar a cada hijo como originador de tribu, la dirección y orientación necesaria para el futuro desde la perspectiva del propósito de Dios. En este sentido, la bendición es una profecía y su cumplimiento es certero e inalterable. Segunda, se hacen referencias a experiencias y eventos pasados en la vida de algunos de los patriarcas, porque dichos eventos han de afectar la historia de la tribu originada por ellos. Aquí se nota la importancia que tienen las decisiones y acciones de personas con una importante responsabilidad histórica. Tercera, se vislumbra el papel político y religioso que ha de tocar a cada tribu y aún la asignación territorial que han de recibir. Esta visión siempre está orientada desde la perspectiva del propósito divino. Cuarta, la bendición es a cada uno y a todos los hijos y no solamente al primogénito como en los patriarcas anteriores. Este hecho se debe a que estos doce hijos de Jacob, son los antepasados que dan origen a las doce tribus de Israel. Manasés y Efraín ya quedaron incluidos en la bendición anterior suplantando ambos a su padre José. En el desarrollo de la nación de Israel, hubo doce tribus con asignación territorial y una (Leví) sin asignación territorial. Los dos hijos de José, Manasés y Efraín completan las doce tribus territoriales, pero cuando se habla de las doce tribus, se los unen y ambos representan a José.
Semillero homilético El Dios de nuestros padres
48:15, 16
Introducción : La naturaleza del Dios que adora una persona tendrá gran peso sobre esa persona, sus valores, su comportamiento y su visión mundial. Jacob había tenido muchas experiencias con Dios durante sus largos años. En su vejez piensa en estas grandes bendiciones. La bendición de Jacob contiene los temas principales de todo el libro de Génesis. Veamos:
I. Dios es identificado como el Dios en cuya presencia anduvieron mis padres. Se presenta a un Dios que se relaciona y comunica con su pueblo; además se subraya que aquellos patriarcas fueron lo que fueron por causa de su dedicación a &quot;andar delante de Dios&quot;. Por supuesto, Dios es el eslabón que une a cada uno de los patriarcas de los que surgirá el pueblo del pacto.
II. Tenemos un sumario de fe, una declaración de la teología básica que conecta e identifica la verdadera fe a través de muchas generaciones. Dios es descrito como el Dios que me pastorea y el ángel que me redime de todo mal. Aunque muy pocas veces en la Biblia se identifica a Dios como un ángel, pues él es quien envía a los ángeles, sin embargo debemos recordar que hasta ahora Jacob era el único de los patriarcas que había sido visitado por un ángel (22:11). Dios es quien nos salva, cuida y guarda de todo mal.
III. El acto de bendecir a los dos hijos de José levanta el tema de la tierra prometida a Abraham. Ellos también serán llamados por el &quot;nombre&quot; de Jacob y el nombre de Isaac y Abraham. Tal como Dios lo había prometido a Abraham: Yo haré de ti una gran nación... engrandeceré tu nombre (12:2).
Conclusión : Jacob pudo reflexionar sobre su vida y las muchas experiencias con Dios, y reconocer que Dios lo había acompañado, de acuerdo con la declaración en Gen 28:20. ¿Podemos hacer lo mismo?
Se pueden notar algunos hechos resaltantes en relación a algunos de los hijos en estos pronunciamientos. Rubén, por su comportamiento vil y usurpador, pierde el derecho a la primogenitura. Judá, como tribu, recibe una atención especial. Se resalta su prominencia política en el sentido de que tendrá permanentemente un gobernador propio y será líder a las demás tribus de las que ha de recibir alabanzas. El cumplimiento histórico del sueño de José se proyecta para la tribu de Judá. Los demás pueblos también estarán en sujeción a Judá. El v. 10 se considera un pasaje mesiánico que se refiere al reinado universal del Mesías. La bendición a José indica que él es considerado como primogénito y responsable de la continuación del pacto. Primero se desea la fecundidad y prosperidad de esta tribu. Luego se lo conecta íntimamente con el Dios de la tradición patriarcal descripto con diferentes nombres. Y finalmente, se pronuncian bendiciones sobre esta tribu en todos los aspectos de su vida.
Aclaración: ¿Fueron setenta? En Gen 46:8-27 el relato dice claramente que el total de los miembros de la familia de Jacob que entraron en Egipto fueron setenta. Sin embargo, dentro de este pasaje se alcanza esta cifra de dos maneras diferentes. Primero hay una lista general de la familia de Jacob con el subtotal de treinta y tres (v. 15), dieciséis (v. 18), catorce (v. 22) y siete (v. 25), lo cual suma setenta. En esta lista se incluye a Jacob mismo (observe la inclusión de Jacob y sus hijos a los nombres de los hijos de Israel que entraron a Egipto, v. 8. En nuestra RVA se diluye la adición por medio de colocar los dos puntos y no el punto y seguido o punto y coma que la lectura del hebreo sugiere); también se incluye a José (v. 19) y a sus dos hijos nacidos en Egipto (v. 20), pero no se mencionan a Er y a Onán (v. 12) quienes murieron en Canaan antes del viaje a Egipto. El subtotal en la lista también incluye a Dina (v. 15). La dificultad en la lista radica en la adición: El total de las personas de sus hijos y de sus hijas, la cual parece excluir a Jacob, pero el v. 8 ya trató el problema.
Por otra parte, el subtotal dado en los vv. 26 y 27: Todas las personas fueron sesenta y seis. Esto es lógico, pues excluye a las esposas de los hijos de Jacob que no eran sus descendientes directos. Cuando se añade a Dina, Sera, Efraín y Manasés, el total es setenta.
El número setenta es consistente con Exo 1:5 y Deu 10:22, en donde claramente se dice que fueron setenta los hijos de Israel que fueron a Egipto.
Es interesante que en la Septuaginta se añaden cinco nombres más en el v. 20. Los nombres se tomaron de Num 26:29-36. Consecuentemente esa versión dice en Exo 1:5 que fueron setenta y cinco quienes fueron a Egipto. Sin duda fue esta tradición la que citó Esteban en Act 7:14 (recordemos que la Septuaginta fue la Biblia de los hebreos del tiempo de Jesús). Una nota que ayuda es que tanto en la Septuaginta como en los textos de Qumran no se dice los descendientes de Jacob, sino &quot;el número de los hijos de Dios&quot;.
El uso del número &quot;setenta&quot; no es caprichoso, pues encontramos en Génesis 10 que el número de las naciones fue setenta. Lo que encontramos en este relato es la demostración del tema de Deu 32:8 que fue Dios quien estableció los límites y la estructura del pueblo hebreo en medio de todas las naciones de la tierra. Con una nación tan pequeña entre un número tan grande de otras naciones Dios cumplirá su propósito y llevará a cabo sus planes.
Rubén : Inestable como el agua Rubén el hijo primogénito de Jacob (Deu 49:3-4), recibe una bendición limitada y casi hasta un castigo por haber cometido el pecado de incesto. Aunque la tribu adquiere un mediano tamaño nunca llega a tener verdadera importancia. Para los días de Moisés apenas cuenta con unos pocos hombres competentes para la guerra.
Estos hechos nos demuestran que la falta de fidelidad a los principios de la palabra del Señor producen un carácter inestable como el agua. Es decir que siempre tiende a buscar el nivel más bajo y no retiene sus estados (líquido, gaseoso, sólido) por ella misma, sino depende de las circunstancia que la rodean.
Debilidad transformada en fuerza
Simeón y Levi se caracterizaron por un carácter violento y la historia del ataque alevoso contra los hombres de Siquem lo confirma (Deu 34:1-31). Muchos años más tarde, sin embargo, cuando Dios pide que los que estén de su parte den un paso al frente, los levitas lo hicieron y se mantuvieron firmes en la defensa de la causa del Señor (Exo 32:25-29). Como resultado, Dios los escogió para que fueran los sacerdotes de Israel. Dios puede transformar las debilidades de nuestro carácter en fuerza, eso fue lo que hizo con los descendientes de Levi. Cualquiera que sea la debilidad de nuestro carácter llevémosla con confianza delante del Señor y pidamos que lo cambie y lo use de modo que sea para honra de su nombre.</p>
<br/>




</div>
