<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 2</h2>
<p class="text-justify">(7) El séptimo día, 2:1-4a. Se confirma que el relato de la creación ofrece la explicación correcta del origen del universo con todos su ocupantes y que la creación fue completada. En el día séptimo, día de la culminación de la creación, Dios cesó de su actividad creadora. Ello indica una satisfacción por lo creado y la confirmación de una relación especial y permanente entre Dios y su creación. Al reposar, bendecir y santificar el día, Dios establece una relación de cuidado y sustento con su creación. Este reposo y su relación especial es concedido también a todas las criaturas (Exo 20:8-11) como un mandamiento. El día de reposo se convirtió en una institución que identificó y distinguió al pueblo de Dios durante toda su historia. El propósito del reposo se cumple ahora en Jesucristo quien es el Señor del reposo y quien alivia al hombre de la carga del pecado (Mar 2:28; Mat 11:28-30).
II. DIOS Y LA HUMANIDAD,Mat 2:4b-Mat 11:9
La segunda sección, algo más amplia que la primera, presenta el desarrollo de la humanidad en su relación al Creador. Desde el punto de vista del hombre, muestra como éste progresa en diferentes áreas
Joya bíblica Dios bendijo y santificó el séptimo día (Mat 2:3).
La palabra traducida &quot;santificó&quot; es el verbo kadosh H6942, que indica separar para cumplir con un propósito o tarea. Así el día séptimo es apartado por el Señor para reposar o descansar o sencillamente dejar de trabajar. Aunque el Señor no descansó por fatiga física, mental o emocional, él, como Señor del tiempo decide apartar un cierto &quot;día&quot; para su reposo. La implicación para el ser humano es doble: por un lado, apartar un día para la renovación de sus fuerzas, y por otro, imitar el ejemplo del Señor quien tiene razones últimas para hacer lo que hace y ordenar lo que ordena. Los que no siguen este ejemplo enferman y mueren sin llegar a desarrollar todo lo que pudieron ser.
de civilización y como el hombre continuamente se aleja de Dios. Los ejemplos escogidos son suficientes y claros en demostrar la rebeldía y pecaminosidad del hombre en todas las esferas de su vida. Desde el punto de vista de Dios, se da testimonio de la fidelidad y misericordia de Dios que constantemente interviene para mantener su propósito original de comunión con el hombre. Al aumentar el pecado, aumenta también la gracia de Dios (Rom 5:20).
1. DIOS ESTABLECE AMBIENTE, NORMAS Y RELACIONES PARA EL HOMBRE,Rom 2:4b-25
Este es un relato más íntimo y detallado de la creación del hombre y la mujer y complementa el relato del cap. 1. El énfasis es en las relaciones que el hombre establece con Dios, con el medio, con los animales y con la mujer. El nombre propio de Dios Jehová H3068— se combina con su nombre título —Elohim H433— dando un toque más personal al diálogo entre Dios y el hombre. El material presenta cuatro secciones: La creación especial del hombre, la preparación del jardín para el desarrollo de la vida, la creación de la mujer y la institución del matrimonio.
(1) Dios forma a Adán,Rom 2:4b-7. Antes de la existencia del hombre no había reino vegetal y la tierra estaba regada o inundada (Rom 1:9) por un vapor o manantial subterráneo. El lenguaje que se usa para formar al hombre es propio al de un alfarero que usa el barro para modelar su vasija. Dios forma al hombre, adam H120 de la tierra, adam?h H127 la cual provee todos los componentes físicos. Similar a los animales en su composición física, sin embargo, la diferencia es grande. Dios de manera especial concede al hombre el don de vida a través del aliento de vida. La acción de Dios es familiar e íntima. En Joh 20:22 Jesús también sopla el Espíritu Santo a sus discípulos dando vida así a una nueva humanidad. A pesar de tener dos dimensiones, el hombre es una unidad dependiente tanto del medio (físico) como de Dios (espiritual). Con el nombre propio de Adán (Joh 2:20) se afirma que el primer hombre fue un ser histórico y no mitológico o legendario.
(2) Dios planta un jardín en Edén, 2 : 8-17. Dios prepara un lugar especial y apropiado para el desarrollo de la vida del hombre. La descripción es la de un oasis o jardín fértil, con abundante agua para riego y para originar cuatro ríos. Estos ríos regaban lugares conocidos por sus nombres y por sus productos. Se nota la amplia extensión geográfica y la diversidad de recursos propios a cada región. Edén es un lugar geográfico específico, ubicado en la Mesopotamia del Tigris y del Eufrates, lugar reconocido históricamente como la cuna de nuestra civilización judeocristiana u occidental. La identificación exacta del lugar no es posible ni necesaria ya que pronto el hombre es expulsado de allí (Joh 3:24).
Cuerpo y alma Gen 2:7 y 1Th 5:23 nos explican que Dios hizo al hombre con ciertos elementos interdependientes que le dan la categorías de &quot;un ser viviente&quot;: con un cuerpo físico, material y con un alma o espíritu. Esta es la idea de un nefesh H5315 jayyah H2416.
La influencia de la filosofía griega ha hecho que algunos vean al hombre como un compuesto de tres elementos: espíritu, alma y cuerpo. Le asignan a cada uno su propia identidad. Se habla del alma como ese soplo o &quot;aliento de vida&quot; que Dios exhaló sobre el hombre para que llegara a &quot;un ser viviente&quot;. Se dice que el espíritu es lo que permite al hombre relacionarse con Dios y que el cuerpo es la parte material. Puede ser, sin embargo una lectura sencilla de la Biblia hace pensar que los escritores bíblicos usaron las palabras &quot;alma&quot; y &quot;espíritu&quot; casi como sinónimos y no con el contenido del pensamiento griego; al fin y al cabo los escritores eran hebreos y fueron consistentes con la filosofía y cultura de su pueblo que consideraba a la persona como una totalidad y no imaginaba a una persona en la cual su alma estuviera separada de su cuerpo. Lo trascendental es que sólo el hombre recibe el aliento de vida directamente del Señor, puede ser que esto sea lo que lo diferencia substancialmente de los animales.
La vegetación que Dios hace brotar de la tierra sirve al hombre de alimento y para su bienestar físico y emocional. Dos árboles reciben ubicación y atención especial: Uno es el árbol de la vida, que después de la desobediencia de Adán y Eva Dios lo considera de riesgo continuo para el hombre y lo hace inaccesible (1Th 3:22-24). En Rev 2:7 y 22:2 reaparece el árbol de la vida con abundancia de fruto y dones de sanidad en la nueva Jerusalén. El otro es el árbol del conocimiento del bien y del mal, es decir, de discernimiento total, que marca la limitación de la libertad del hombre y su relación responsable para con Dios (v. 17). Aquí sólo se mencionan estos dos árboles que luego juegan un papel muy importante en el desarrollo de la historia humana. En 3:7 aparece la higuera y en Eze 31:8 se mencionan cedros, hayas y castaños como otros árboles de Edén.
(3) Dios crea a la mujer,Eze 2:18-23. La vida del hombre se desarrolla ahora en el jardín, pero en soledad, sin ayuda idónea. Al nombrar a la totalidad de los animales que viven en y sobre la tierra, el hombre los integra a su vida y ejerce su vocación y dominio sobre ellos. Ningún animal ni Dios puede servir de ayuda idónea, es decir, de una relación social y emocional íntima e importante. Dios decide soberana y libremente proveer esa necesidad de compañerismo al hombre. Esto indica la naturaleza social del hombre. El hombre no vive sólo. Su vida encuentra significado completo en la comunidad con otros seres humanos. La vida en comunidad refleja también la imagen y semejanza a Dios quien se ha manifestado desde el principio no en soledad sino en trinidad.
Para proteger su actividad creadora de Adán y porque Dios decide formar la mujer de una parte del hombre, lo hace dormir profundamente. Una de sus costillas (v. 21) significa una porción del medio y del frente del hombre, y no una costilla individual (v. 23). Dios presenta la nueva criatura al hombre quien expresa la naturaleza de la mujer en tres declaraciones: Primera, reconoce la igualdad del nuevo ser. Ella también es humana y de la misma materia del hombre (hueso de mis huesos y carne de mi carne, v. 23). Segunda, Adán le concede identidad propia (mujer, v. 23), aceptando la sexualidad diferente que completa y complementa la humanidad. Esta cualidad hace posible que la mujer sea compañera al hombre (Eze 3:12). Tercera, por ser formada del hombre, la mujer es lo más cercano posible al hombre y su más compatible. Con estas declaraciones el hombre expresa su aceptación y su satisfacción completa.
(4) Institución del matrimonio,Eze 2:24-25. Dios mismo establece el matrimonio como la relación correcta entre el hombre y su ayuda idónea. Consistente con la naturaleza del hombre y la mujer declarada en el v. 23, la revelación bíblica afirma que la relación matrimonial tiene estas características esenciales: Primera, es exclusiva y de compromiso social (dejará a su padre y su madre, v. 24). Segunda, es monógama, heterosexual y de pacto mutuo (el hombre... se unirá con su mujer, v. 24). Tercera, es de complementación mutua (serán una sola carne, v. 24). Cuarta, de libre comunicación e intimidad significante (estaban ambos desnudos, v. 25). El Señor Jesucristo, al reafirmar estas características aclara que el propósito original de Dios para el matrimonio es una relación permanente e indisoluble (Mar 10:1-12). Estas afirmaciones bíblicas condenan las prácticas prevalecientes en las sociedades modernas como el divorcio, las relaciones sexuales casuales y adulterios, los concubinatos y relaciones clandestinas, la homosexualidad y la relación de competencia y opresión dentro del matrimonio. El ideal de Dios se concreta en la íntima, abierta, mutua y total aceptación y un continuo y permanente conocimiento el uno del otro que Adán experimenta con su mujer. Dentro de esta relación ideal es que Dios intenta la procreación de los hijos y el desarrollo de la comunidad. En esta relación no hay lugar para sentimientos negativos ni barreras. La procreación, la vocación y las responsabilidades son compartidas entre el hombre y la mujer y en una dimensión comunitaria.
Ayudas prácticas Lo puso en el jardín de Edén, para que lo cultivase y lo guardase (Mar 2:15). La creencia popular de que el trabajo lo hizo Dios como castigo es incorrecta. Dios instituyó el trabajo con un doble propósito:
1. Para que el hombre sea colaborador con Dios en el cuidado de la creación. En este sentido el hombre es un siervo de Dios. Es interesante que la voz &quot;cultivar&quot;, del hebreo habad H5647, se traduce por &quot;servir&quot; en Exo 3:12 cuando dice: ... serviréis a Dios en este monte (ver también Exo 4:23). Hay un acto de servicio y adoración a Dios por medio del trabajo. Nuestra palabra &quot;culto&quot; es una forma corta de &quot;cultivar&quot; y es que el trabajo es una forma de cultivar nuestra relación con Dios.
2. Para que el hombre sea mayordomo de lo que Dios ha hecho. El hombre tiene que cuidar y proteger la tierra y sus elementos porque tendrá que entregar cuentas del resultado de su administración.
La responsabilidad que Dios asigna al hombre es la de cultivar y guardar el jardín. Estas dos ocupaciones (agricultor y pastor) marcan el inicio histórico de la división vocacional del hombre. El trabajo no fue resultado de la maldición, sino una responsabilidad asignada por Dios al hombre desde la creación para su sustento. De entre todos los árboles hay uno del cual Dios prohibe al hombre comer. La prohibición indica dos cosas: Primero, que el hombre debe responder libremente. No es un ser autómata, sino creado con libertad de escoger. Segundo, el hombre es responsable ante Dios por sus acciones. La desobediencia trae consigo una consecuencia clara y grave: La muerte, que marca el límite a la vida recientemente concedida.
La obra maestra Exo 1:31
Dios vio todo lo que había hecho, y he aquí que era muy bueno (Exo 1:31). El autor observa al Señor evaluando lo hecho; ve que Dios tiene un rostro de satisfacción y gozo, como cuando un artista contempla su obra terminada y escucha a los más severos críticos decir: &quot;...es una obra maestra&quot;. La obra que Dios ha hecho no solamente es bella, hermosa, impresionante y buena en sí misma, también útil para cumplir el propósito para el cual fue creada. Ese es el sentido de la expresión hebrea meód H3966 tob H2896, &quot;muy bueno&quot; (como traduce RVA), o &quot;bueno en gran manera&quot; (como traduce RVR-60). TODO lo que Dios hace es esencialmente bueno y muy útil para todos.
Semillero homilético</p>
<br/>
<p class="text-justify">(7) El séptimo día, 2:1-4a. Se confirma que el relato de la creación ofrece la explicación correcta del origen del universo con todos su ocupantes y que la creación fue completada. En el día séptimo, día de la culminación de la creación, Dios cesó de su actividad creadora. Ello indica una satisfacción por lo creado y la confirmación de una relación especial y permanente entre Dios y su creación. Al reposar, bendecir y santificar el día, Dios establece una relación de cuidado y sustento con su creación. Este reposo y su relación especial es concedido también a todas las criaturas (Exo 20:8-11) como un mandamiento. El día de reposo se convirtió en una institución que identificó y distinguió al pueblo de Dios durante toda su historia. El propósito del reposo se cumple ahora en Jesucristo quien es el Señor del reposo y quien alivia al hombre de la carga del pecado (Mar 2:28; Mat 11:28-30).
II. DIOS Y LA HUMANIDAD,Mat 2:4b-Mat 11:9
La segunda sección, algo más amplia que la primera, presenta el desarrollo de la humanidad en su relación al Creador. Desde el punto de vista del hombre, muestra como éste progresa en diferentes áreas
Joya bíblica Dios bendijo y santificó el séptimo día (Mat 2:3).
La palabra traducida &quot;santificó&quot; es el verbo kadosh H6942, que indica separar para cumplir con un propósito o tarea. Así el día séptimo es apartado por el Señor para reposar o descansar o sencillamente dejar de trabajar. Aunque el Señor no descansó por fatiga física, mental o emocional, él, como Señor del tiempo decide apartar un cierto &quot;día&quot; para su reposo. La implicación para el ser humano es doble: por un lado, apartar un día para la renovación de sus fuerzas, y por otro, imitar el ejemplo del Señor quien tiene razones últimas para hacer lo que hace y ordenar lo que ordena. Los que no siguen este ejemplo enferman y mueren sin llegar a desarrollar todo lo que pudieron ser.
de civilización y como el hombre continuamente se aleja de Dios. Los ejemplos escogidos son suficientes y claros en demostrar la rebeldía y pecaminosidad del hombre en todas las esferas de su vida. Desde el punto de vista de Dios, se da testimonio de la fidelidad y misericordia de Dios que constantemente interviene para mantener su propósito original de comunión con el hombre. Al aumentar el pecado, aumenta también la gracia de Dios (Rom 5:20).
1. DIOS ESTABLECE AMBIENTE, NORMAS Y RELACIONES PARA EL HOMBRE,Rom 2:4b-25
Este es un relato más íntimo y detallado de la creación del hombre y la mujer y complementa el relato del cap. 1. El énfasis es en las relaciones que el hombre establece con Dios, con el medio, con los animales y con la mujer. El nombre propio de Dios Jehová H3068— se combina con su nombre título —Elohim H433— dando un toque más personal al diálogo entre Dios y el hombre. El material presenta cuatro secciones: La creación especial del hombre, la preparación del jardín para el desarrollo de la vida, la creación de la mujer y la institución del matrimonio.
(1) Dios forma a Adán,Rom 2:4b-7. Antes de la existencia del hombre no había reino vegetal y la tierra estaba regada o inundada (Rom 1:9) por un vapor o manantial subterráneo. El lenguaje que se usa para formar al hombre es propio al de un alfarero que usa el barro para modelar su vasija. Dios forma al hombre, adam H120 de la tierra, adam?h H127 la cual provee todos los componentes físicos. Similar a los animales en su composición física, sin embargo, la diferencia es grande. Dios de manera especial concede al hombre el don de vida a través del aliento de vida. La acción de Dios es familiar e íntima. En Joh 20:22 Jesús también sopla el Espíritu Santo a sus discípulos dando vida así a una nueva humanidad. A pesar de tener dos dimensiones, el hombre es una unidad dependiente tanto del medio (físico) como de Dios (espiritual). Con el nombre propio de Adán (Joh 2:20) se afirma que el primer hombre fue un ser histórico y no mitológico o legendario.
(2) Dios planta un jardín en Edén, 2 : 8-17. Dios prepara un lugar especial y apropiado para el desarrollo de la vida del hombre. La descripción es la de un oasis o jardín fértil, con abundante agua para riego y para originar cuatro ríos. Estos ríos regaban lugares conocidos por sus nombres y por sus productos. Se nota la amplia extensión geográfica y la diversidad de recursos propios a cada región. Edén es un lugar geográfico específico, ubicado en la Mesopotamia del Tigris y del Eufrates, lugar reconocido históricamente como la cuna de nuestra civilización judeocristiana u occidental. La identificación exacta del lugar no es posible ni necesaria ya que pronto el hombre es expulsado de allí (Joh 3:24).
Cuerpo y alma Gen 2:7 y 1Th 5:23 nos explican que Dios hizo al hombre con ciertos elementos interdependientes que le dan la categorías de &quot;un ser viviente&quot;: con un cuerpo físico, material y con un alma o espíritu. Esta es la idea de un nefesh H5315 jayyah H2416.
La influencia de la filosofía griega ha hecho que algunos vean al hombre como un compuesto de tres elementos: espíritu, alma y cuerpo. Le asignan a cada uno su propia identidad. Se habla del alma como ese soplo o &quot;aliento de vida&quot; que Dios exhaló sobre el hombre para que llegara a &quot;un ser viviente&quot;. Se dice que el espíritu es lo que permite al hombre relacionarse con Dios y que el cuerpo es la parte material. Puede ser, sin embargo una lectura sencilla de la Biblia hace pensar que los escritores bíblicos usaron las palabras &quot;alma&quot; y &quot;espíritu&quot; casi como sinónimos y no con el contenido del pensamiento griego; al fin y al cabo los escritores eran hebreos y fueron consistentes con la filosofía y cultura de su pueblo que consideraba a la persona como una totalidad y no imaginaba a una persona en la cual su alma estuviera separada de su cuerpo. Lo trascendental es que sólo el hombre recibe el aliento de vida directamente del Señor, puede ser que esto sea lo que lo diferencia substancialmente de los animales.
La vegetación que Dios hace brotar de la tierra sirve al hombre de alimento y para su bienestar físico y emocional. Dos árboles reciben ubicación y atención especial: Uno es el árbol de la vida, que después de la desobediencia de Adán y Eva Dios lo considera de riesgo continuo para el hombre y lo hace inaccesible (1Th 3:22-24). En Rev 2:7 y 22:2 reaparece el árbol de la vida con abundancia de fruto y dones de sanidad en la nueva Jerusalén. El otro es el árbol del conocimiento del bien y del mal, es decir, de discernimiento total, que marca la limitación de la libertad del hombre y su relación responsable para con Dios (v. 17). Aquí sólo se mencionan estos dos árboles que luego juegan un papel muy importante en el desarrollo de la historia humana. En 3:7 aparece la higuera y en Eze 31:8 se mencionan cedros, hayas y castaños como otros árboles de Edén.
(3) Dios crea a la mujer,Eze 2:18-23. La vida del hombre se desarrolla ahora en el jardín, pero en soledad, sin ayuda idónea. Al nombrar a la totalidad de los animales que viven en y sobre la tierra, el hombre los integra a su vida y ejerce su vocación y dominio sobre ellos. Ningún animal ni Dios puede servir de ayuda idónea, es decir, de una relación social y emocional íntima e importante. Dios decide soberana y libremente proveer esa necesidad de compañerismo al hombre. Esto indica la naturaleza social del hombre. El hombre no vive sólo. Su vida encuentra significado completo en la comunidad con otros seres humanos. La vida en comunidad refleja también la imagen y semejanza a Dios quien se ha manifestado desde el principio no en soledad sino en trinidad.
Para proteger su actividad creadora de Adán y porque Dios decide formar la mujer de una parte del hombre, lo hace dormir profundamente. Una de sus costillas (v. 21) significa una porción del medio y del frente del hombre, y no una costilla individual (v. 23). Dios presenta la nueva criatura al hombre quien expresa la naturaleza de la mujer en tres declaraciones: Primera, reconoce la igualdad del nuevo ser. Ella también es humana y de la misma materia del hombre (hueso de mis huesos y carne de mi carne, v. 23). Segunda, Adán le concede identidad propia (mujer, v. 23), aceptando la sexualidad diferente que completa y complementa la humanidad. Esta cualidad hace posible que la mujer sea compañera al hombre (Eze 3:12). Tercera, por ser formada del hombre, la mujer es lo más cercano posible al hombre y su más compatible. Con estas declaraciones el hombre expresa su aceptación y su satisfacción completa.
(4) Institución del matrimonio,Eze 2:24-25. Dios mismo establece el matrimonio como la relación correcta entre el hombre y su ayuda idónea. Consistente con la naturaleza del hombre y la mujer declarada en el v. 23, la revelación bíblica afirma que la relación matrimonial tiene estas características esenciales: Primera, es exclusiva y de compromiso social (dejará a su padre y su madre, v. 24). Segunda, es monógama, heterosexual y de pacto mutuo (el hombre... se unirá con su mujer, v. 24). Tercera, es de complementación mutua (serán una sola carne, v. 24). Cuarta, de libre comunicación e intimidad significante (estaban ambos desnudos, v. 25). El Señor Jesucristo, al reafirmar estas características aclara que el propósito original de Dios para el matrimonio es una relación permanente e indisoluble (Mar 10:1-12). Estas afirmaciones bíblicas condenan las prácticas prevalecientes en las sociedades modernas como el divorcio, las relaciones sexuales casuales y adulterios, los concubinatos y relaciones clandestinas, la homosexualidad y la relación de competencia y opresión dentro del matrimonio. El ideal de Dios se concreta en la íntima, abierta, mutua y total aceptación y un continuo y permanente conocimiento el uno del otro que Adán experimenta con su mujer. Dentro de esta relación ideal es que Dios intenta la procreación de los hijos y el desarrollo de la comunidad. En esta relación no hay lugar para sentimientos negativos ni barreras. La procreación, la vocación y las responsabilidades son compartidas entre el hombre y la mujer y en una dimensión comunitaria.
Ayudas prácticas Lo puso en el jardín de Edén, para que lo cultivase y lo guardase (Mar 2:15). La creencia popular de que el trabajo lo hizo Dios como castigo es incorrecta. Dios instituyó el trabajo con un doble propósito:
1. Para que el hombre sea colaborador con Dios en el cuidado de la creación. En este sentido el hombre es un siervo de Dios. Es interesante que la voz &quot;cultivar&quot;, del hebreo habad H5647, se traduce por &quot;servir&quot; en Exo 3:12 cuando dice: ... serviréis a Dios en este monte (ver también Exo 4:23). Hay un acto de servicio y adoración a Dios por medio del trabajo. Nuestra palabra &quot;culto&quot; es una forma corta de &quot;cultivar&quot; y es que el trabajo es una forma de cultivar nuestra relación con Dios.
2. Para que el hombre sea mayordomo de lo que Dios ha hecho. El hombre tiene que cuidar y proteger la tierra y sus elementos porque tendrá que entregar cuentas del resultado de su administración.
La responsabilidad que Dios asigna al hombre es la de cultivar y guardar el jardín. Estas dos ocupaciones (agricultor y pastor) marcan el inicio histórico de la división vocacional del hombre. El trabajo no fue resultado de la maldición, sino una responsabilidad asignada por Dios al hombre desde la creación para su sustento. De entre todos los árboles hay uno del cual Dios prohibe al hombre comer. La prohibición indica dos cosas: Primero, que el hombre debe responder libremente. No es un ser autómata, sino creado con libertad de escoger. Segundo, el hombre es responsable ante Dios por sus acciones. La desobediencia trae consigo una consecuencia clara y grave: La muerte, que marca el límite a la vida recientemente concedida.
La obra maestra Exo 1:31
Dios vio todo lo que había hecho, y he aquí que era muy bueno (Exo 1:31). El autor observa al Señor evaluando lo hecho; ve que Dios tiene un rostro de satisfacción y gozo, como cuando un artista contempla su obra terminada y escucha a los más severos críticos decir: &quot;...es una obra maestra&quot;. La obra que Dios ha hecho no solamente es bella, hermosa, impresionante y buena en sí misma, también útil para cumplir el propósito para el cual fue creada. Ese es el sentido de la expresión hebrea meód H3966 tob H2896, &quot;muy bueno&quot; (como traduce RVA), o &quot;bueno en gran manera&quot; (como traduce RVR-60). TODO lo que Dios hace es esencialmente bueno y muy útil para todos.
Semillero homilético</p>
<br/>




</div>
