<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">I. DIOS Y LA CREACION, 1:1-2:4a
La Biblia, ante la inquietud universal del origen del mundo y del hombre, proclama que todas las cosas creadas tienen su origen en Dios, único y exclusivo Creador. No presenta una crónica informativa ni detallada de la creación, sino la revelación de las verdades que en cualquier generación contestan las cuestiones específicas del hombre en su relación con Dios y con el mundo. La creación no es vista desde su origen hacia su desarrollo posterior (científica); se la mira desde su culminación para encontrar significado a la vida y al universo y rechazar toda otra explicación. Es interesante notar que casi todas las culturas con cierto desarrollo, incluyendo las de Amerindia, tienen un relato que intenta explicar la creación. La similitud que se pudiera encontrar entre estos relatos de creación se debe exclusivamente a que intentan responder a las mismas preguntas que el hombre se ha hecho en cada cultura.
Porciones del libro de Job, algunos salmos como el 8, 104, 139, pasajes de libros proféticos, Joh 1:1-3, Col 1:15-17, Heb 1:1-2, presentan enseñanzas fundamentales sobre la creación. En el relato de Génesis, la afirmación introductoria y los diferentes actos creativos de Dios, presentan la explicación completa y fundamental de la creación del universo y su relación con Dios.
Los primeros versículos declaran que Dios es el Creador de toda la creación. Los actos creativos específicos siguen una estructura y orden: La palabra de Dios llamando a existencia, una declaración de propósito, el resultado o ejecución de dicha palabra, asignación de nombre, una evaluación y un tiempo específico.
1. DIOS EL CREADOR,Heb 1:1-2
La introducción constituye el fundamento de toda la fe bíblica ya que determina la relación correcta entre Creador y creación. Básicamente encontramos cuatro afirmaciones que son normativas en la relación Creadorcreación.
Hubo un principio para la creación, la cual no es eterna ni previa a Dios. Se refuta así el materialismo que intenta afirmar que la materia siempre existió y existirá. No sólo la creación tuvo principio, sino también tendrá fin para dar lugar a una nueva creación en la culminación del plan redentor de Dios (2Pe 3:7-13; Apoc. 21:1).
El Creador único y exclusivo es Dios. El verbo hebreo bara H1254 que se traduce creó se usa sólo en referencia a la actividad creadora propia, única y exclusiva de Dios y nunca a la del hombre o nadie más. En el v. 2 nos introduce a la presencia del Espíritu de Dios y en Joh 1:1-3 a la participación creadora del Verbo, aclarando que la Creación es obra del Dios trinitario.
Dios es el Creador de todo lo que existe. La expresión los cielos y la tierra indica en lenguaje concreto todo lo que existe en la creación (Apoc. 4:11).
Dios crea de la nada ya que antes de su actividad creadora nada existía (Isa 46:10; Heb 11:3). Dios no necesita materia previa para crear. La actividad creadora de Dios debe verse además en contraste con la condición de la tierra previa a los actos creativos de Dios. Sin orden y vacía significa concretamente lo opuesto a la existencia. Tinieblas y aguas representan el caos o confusión y el desorden que hacen imposible existencia alguna. Al crear de la nada se afirma las dos únicas y diferentes dimensiones de existencia: Creador y criatura. La existencia de la criatura es dependiente del Creador. La no existencia y las condiciones negativas para la existencia de criaturas de ninguna manera impiden la existencia o actividad de Dios en la presencia de su Espíritu (Job 139:8, Job 139:11-12; Juan 1.1).
Verdades prácticas El Espíritu de Dios se movía sobre la faz de las aguas (Job 1:2) El verbo en hebreo de esta oración es merajefet H7363, &quot;se movía&quot;, que indica la acción de volar sobre el nido como lo hacen las águilas (Deu 32:11). En nuestros días se puede ilustrar como de un helicóptero que puede mantenerse encima de cierto lugar para ver o ayudar. La idea es que Dios estaba atento, cuidando y protegiendo todo el proceso de la creación.
2. DIOS CREA EL UNIVERSO, 1:3-2:4a
Las afirmaciones bíblicas en cuanto a la creación del universo están en un marco histórico específico y contienen datos comunes y de interés a la historia y a la ciencia. No fueron hechas en un vacío, sino en medio de muchos otros relatos de creación. El lenguaje y el marco de referencia son los de las culturas mesopotámica y egipcia, ambas predominantes e influyentes al pueblo de Dios. Los elementos o hechos presentados son selectos y reflejan intereses religiosos dentro de una cultura específica.
(1) El primer día, 1:3-5. El primer elemento creado es la luz, indispensable para poder reconocer y distinguir cualquier otra cosa. El agente de creación es la palabra de Dios la cual es suficiente y eficiente en hacer realidad la voluntad de Dios. Se niega toda creación por actividad sexual como en las religiones paganas. También se refuta que la creación es una extensión o emanación de Dios como propone el panteísmo. La luz cumple su propósito asignado y como parte de su actividad creadora, Dios la separa de las tinieblas que representa el elemento de caos. Dios da nombre a lo creado manifestando su dominio y señorío. La luz y las tinieblas, y sus expresiones concretas en Día y Noche, significan mucho más que la división de un período de tiempo. Más bien expresan cualidades que caracterizan toda la creación en su orden, su propósito y su relación. El Evangelio de Juan desarrolla este aspecto de la creación en forma más concreta.
La mención de tarde y mañana con su día correspondiente indica un orden y un tiempo específico en la creación de cada elemento.
(2) El segundo día, 1:6-8. Dios crea una bóveda o firmamento con el propósito de separar las aguas (elemento de desorden) y poner orden en el universo. Una parte de las aguas al separarse queda debajo de la bóveda y la otra sobre la misma. Esta descripción es consistente con la experiencia de que el agua en forma de lluvia cae de arriba. La bóveda recibe su nombre y se constituye en la parte superior del universo. En la descripción bíblica, el universo tiene tres partes: los cielos (arriba); la superficie donde están la Tierra y los Mares y la parte inferior donde están las aguas debajo de la Tierra.
(3) El tercer día, 1:9-13. Las aguas que quedaron debajo de la bóveda son juntadas en un lugar para permitir que lo seco aparezca. La reunión de las aguas —Mares— y lo seco —Tierra— forman la superficie habitada del universo. La creación del reino vegetal, primero en la escala de vida orgánica, es la segunda actividad creadora de Dios en este día. La Tierra es llamada a participar en forma continua en la creación de la plantas proveyendo las condiciones y los elementos necesarios para dicha vida. Se descarta la idea de &quot;Madre Tierra&quot; o &quot;Naturaleza Madre&quot; que concede divinidad o creatividad propia a la Tierra (naturalismo). La vegetación se clasifica en plantas que germinan directamente y plantas que dan fruto con su semilla dentro del fruto. El reino vegetal se diferencia en especies y con capacidad de reproducción continua por sus semillas.
Entonces dijo Dios... Ocho veces aparece el verbo &quot;decir&quot; para hacer hincapié sobre el hecho de que Dios crea todo por medio de la palabra. Dios construye, edifica, hace y rehace por medio de su hablar. Lo que expresa lleva la fuerza de su poder y se hace realidad. La Palabra escrita que tenemos de parte del Señor también genera vida eterna porque esa Palabra es el verbo que se hizo carne (Joh 1:14).
(4) El cuarto día,Joh 1:14-19. La atención creadora de Dios se dirige a la bóveda del cielo creando los cuerpos celestes. En las culturas paganas y en la astrología se consideran a los astros divinidades o con poderes divinos. Se los idolatra y se los atribuyen poder de destino en las vidas. Aun los nombres de los días de la semana reflejan la pagana asignación divina a los cuerpos celestes (Luna, Marte, Mercurio, Júpiter, etc.). Aquí se afirma que Dios creó todos los cuerpos celestes para ocupar el espacio superior del universo. Sus propósitos específicos son: establecer períodos de día y noche; ciclos de años; variaciones climáticas que condicionan el ciclo de vida (estaciones); servir de señales de las manifestaciones especiales de Dios (Mat 2:2,Mat 24:29, etc.) y alumbrar la Tierra reflejando la luz. Además, por su misterio e inmensidad, otro propósito es mover al ser humano a alabar la grandeza de Dios y confiar en el Creador (Sal. 8,Mat 136:5-9). El Sol y la Luna son mencionados por su cercanía, su influencia en proveer condiciones indispensables para la vida en la Tierra y por la tendencia del hombre a idolatrarlos. En las culturas contemporáneas influyentes a Israel (Egipto, Mesopotamia), el Sol y la Luna eran considerados divinidades principales. La revelación bíblica a Israel es clara y terminante: Estos cuerpos celestes son criaturas de Dios para beneficio del hombre.
(5) El quinto día,Mat 1:20-23. Los primeros seres vivientes del reino animal son los acuáticos y las aves. Las aguas participan en la creación al convertirse en el ambiente de vida para los seres acuáticos. Se clasifican en grandes animales (los más alejados del hombre) y los peces. Las aves son creadas para volar y ocupar el espacio sobre la Tierra en la bóveda. Todos son creados según sus especies y la palabra para crear es la que significa actividad única y exclusiva de Dios. Los seres vivientes reciben una bendición de Dios consistente en la capacidad de procreación, multiplicación y ocupación de los espacios o medio asignados.
(6) El sexto día,Mat 1:24-31. Nuevamente la tierra participa en la creación de animales, proveyendo las condiciones y los elementos necesarios para la vida. Se los agrupan en tres categorías: animales domésticos o ganado, animales que se arrastran o reptiles y animales silvestres o de la tierra. Estos grupos representan la totalidad de animales terrestres y son clasificados por especies, aunque no se determina una cantidad específica. Termina la creación de lo no humano. Todo lo creado hasta ahora es en preparación a la creación y sustento del hombre en quien de aquí en adelante la revelación bíblica se ocupará en forma especial.
En este relato, se describe a la creación de la humanidad completa, su identidad específica, lugar y propósito en el universo. En 2:4 y 18-23 se describe en forma más detallada e íntima la creación del hombre y la mujer.
Primero se anuncia la decisión y participación de la divinidad toda (Juan 1.1-3; 6:63) de crear al hombre, consistente con la enseñanza bíblica de un Dios trino. Segundo, su identidad y relación especial con Dios (a imagen y semejanza) que lo distingue de todos los otros seres vivientes. Por último su propósito: para ejercer dominio sobre lo creado en tierra, mar y aire. Se aclara que Dios crea al hombre y a la mujer dando así origen a la humanidad completa. Ambos fueron creados a imagen y semejanza, pero con diferenciación sexual. Tres veces se usa el verbo creó, reservado exclusivamente para la actividad creadora de Dios.
Dios los bendijo 1:28
La palabra hebrea usada es berek H1288. Este verbo tiene dos implicaciones. La primera es dar un privilegio o regalo de algo que viene directamente de la mano de Dios. Así los animales acuáticos reciben el privilegio de reproducirse (v. 22). El hombre y la mujer son bendecidos para reproducirse y tener dominio sobre toda la creación (v. 28). Isaac sembró la tierra y aquel año obtuvo el ciento por uno porque Jehová lo bendijo (Gen 26:12).
La segunda implicación es la exigencia de santidad. La bendición es un llamado al compromiso y la dedicación a Dios. Dios bendijo y santificó el séptimo día (Gen 2:3). Dios bendijo al hombre y a la mujer y llamó el nombre de ellos Hombre (Gen 5:2).
Hemos dado mucha importancia a la primera implicación de la bendición y con facilidad decimos a otra persona: &quot;Dios te bendiga&quot;. No está mal, pero ¿incluimos la implicación de &quot;dedícate y conságrate al Señor&quot;?
Dios bendice al hombre y a la mujer capacitándoles para la procreación, la ocupación del medio y el ejercicio de dominio sobre los otros seres vivientes. Además, Dios permite que las plantas sirvan de sustento al hombre y a los animales. Dios concede una elevada evaluación a todo lo creado que presenta un cuadro de perfecta armonía y equilibrio entre todos los seres y elementos creados.
Semillero homilético</p>
<br/>
<p class="text-justify">I. DIOS Y LA CREACION, 1:1-2:4a
La Biblia, ante la inquietud universal del origen del mundo y del hombre, proclama que todas las cosas creadas tienen su origen en Dios, único y exclusivo Creador. No presenta una crónica informativa ni detallada de la creación, sino la revelación de las verdades que en cualquier generación contestan las cuestiones específicas del hombre en su relación con Dios y con el mundo. La creación no es vista desde su origen hacia su desarrollo posterior (científica); se la mira desde su culminación para encontrar significado a la vida y al universo y rechazar toda otra explicación. Es interesante notar que casi todas las culturas con cierto desarrollo, incluyendo las de Amerindia, tienen un relato que intenta explicar la creación. La similitud que se pudiera encontrar entre estos relatos de creación se debe exclusivamente a que intentan responder a las mismas preguntas que el hombre se ha hecho en cada cultura.
Porciones del libro de Job, algunos salmos como el 8, 104, 139, pasajes de libros proféticos, Joh 1:1-3, Col 1:15-17, Heb 1:1-2, presentan enseñanzas fundamentales sobre la creación. En el relato de Génesis, la afirmación introductoria y los diferentes actos creativos de Dios, presentan la explicación completa y fundamental de la creación del universo y su relación con Dios.
Los primeros versículos declaran que Dios es el Creador de toda la creación. Los actos creativos específicos siguen una estructura y orden: La palabra de Dios llamando a existencia, una declaración de propósito, el resultado o ejecución de dicha palabra, asignación de nombre, una evaluación y un tiempo específico.
1. DIOS EL CREADOR,Heb 1:1-2
La introducción constituye el fundamento de toda la fe bíblica ya que determina la relación correcta entre Creador y creación. Básicamente encontramos cuatro afirmaciones que son normativas en la relación Creadorcreación.
Hubo un principio para la creación, la cual no es eterna ni previa a Dios. Se refuta así el materialismo que intenta afirmar que la materia siempre existió y existirá. No sólo la creación tuvo principio, sino también tendrá fin para dar lugar a una nueva creación en la culminación del plan redentor de Dios (2Pe 3:7-13; Apoc. 21:1).
El Creador único y exclusivo es Dios. El verbo hebreo bara H1254 que se traduce creó se usa sólo en referencia a la actividad creadora propia, única y exclusiva de Dios y nunca a la del hombre o nadie más. En el v. 2 nos introduce a la presencia del Espíritu de Dios y en Joh 1:1-3 a la participación creadora del Verbo, aclarando que la Creación es obra del Dios trinitario.
Dios es el Creador de todo lo que existe. La expresión los cielos y la tierra indica en lenguaje concreto todo lo que existe en la creación (Apoc. 4:11).
Dios crea de la nada ya que antes de su actividad creadora nada existía (Isa 46:10; Heb 11:3). Dios no necesita materia previa para crear. La actividad creadora de Dios debe verse además en contraste con la condición de la tierra previa a los actos creativos de Dios. Sin orden y vacía significa concretamente lo opuesto a la existencia. Tinieblas y aguas representan el caos o confusión y el desorden que hacen imposible existencia alguna. Al crear de la nada se afirma las dos únicas y diferentes dimensiones de existencia: Creador y criatura. La existencia de la criatura es dependiente del Creador. La no existencia y las condiciones negativas para la existencia de criaturas de ninguna manera impiden la existencia o actividad de Dios en la presencia de su Espíritu (Job 139:8, Job 139:11-12; Juan 1.1).
Verdades prácticas El Espíritu de Dios se movía sobre la faz de las aguas (Job 1:2) El verbo en hebreo de esta oración es merajefet H7363, &quot;se movía&quot;, que indica la acción de volar sobre el nido como lo hacen las águilas (Deu 32:11). En nuestros días se puede ilustrar como de un helicóptero que puede mantenerse encima de cierto lugar para ver o ayudar. La idea es que Dios estaba atento, cuidando y protegiendo todo el proceso de la creación.
2. DIOS CREA EL UNIVERSO, 1:3-2:4a
Las afirmaciones bíblicas en cuanto a la creación del universo están en un marco histórico específico y contienen datos comunes y de interés a la historia y a la ciencia. No fueron hechas en un vacío, sino en medio de muchos otros relatos de creación. El lenguaje y el marco de referencia son los de las culturas mesopotámica y egipcia, ambas predominantes e influyentes al pueblo de Dios. Los elementos o hechos presentados son selectos y reflejan intereses religiosos dentro de una cultura específica.
(1) El primer día, 1:3-5. El primer elemento creado es la luz, indispensable para poder reconocer y distinguir cualquier otra cosa. El agente de creación es la palabra de Dios la cual es suficiente y eficiente en hacer realidad la voluntad de Dios. Se niega toda creación por actividad sexual como en las religiones paganas. También se refuta que la creación es una extensión o emanación de Dios como propone el panteísmo. La luz cumple su propósito asignado y como parte de su actividad creadora, Dios la separa de las tinieblas que representa el elemento de caos. Dios da nombre a lo creado manifestando su dominio y señorío. La luz y las tinieblas, y sus expresiones concretas en Día y Noche, significan mucho más que la división de un período de tiempo. Más bien expresan cualidades que caracterizan toda la creación en su orden, su propósito y su relación. El Evangelio de Juan desarrolla este aspecto de la creación en forma más concreta.
La mención de tarde y mañana con su día correspondiente indica un orden y un tiempo específico en la creación de cada elemento.
(2) El segundo día, 1:6-8. Dios crea una bóveda o firmamento con el propósito de separar las aguas (elemento de desorden) y poner orden en el universo. Una parte de las aguas al separarse queda debajo de la bóveda y la otra sobre la misma. Esta descripción es consistente con la experiencia de que el agua en forma de lluvia cae de arriba. La bóveda recibe su nombre y se constituye en la parte superior del universo. En la descripción bíblica, el universo tiene tres partes: los cielos (arriba); la superficie donde están la Tierra y los Mares y la parte inferior donde están las aguas debajo de la Tierra.
(3) El tercer día, 1:9-13. Las aguas que quedaron debajo de la bóveda son juntadas en un lugar para permitir que lo seco aparezca. La reunión de las aguas —Mares— y lo seco —Tierra— forman la superficie habitada del universo. La creación del reino vegetal, primero en la escala de vida orgánica, es la segunda actividad creadora de Dios en este día. La Tierra es llamada a participar en forma continua en la creación de la plantas proveyendo las condiciones y los elementos necesarios para dicha vida. Se descarta la idea de &quot;Madre Tierra&quot; o &quot;Naturaleza Madre&quot; que concede divinidad o creatividad propia a la Tierra (naturalismo). La vegetación se clasifica en plantas que germinan directamente y plantas que dan fruto con su semilla dentro del fruto. El reino vegetal se diferencia en especies y con capacidad de reproducción continua por sus semillas.
Entonces dijo Dios... Ocho veces aparece el verbo &quot;decir&quot; para hacer hincapié sobre el hecho de que Dios crea todo por medio de la palabra. Dios construye, edifica, hace y rehace por medio de su hablar. Lo que expresa lleva la fuerza de su poder y se hace realidad. La Palabra escrita que tenemos de parte del Señor también genera vida eterna porque esa Palabra es el verbo que se hizo carne (Joh 1:14).
(4) El cuarto día,Joh 1:14-19. La atención creadora de Dios se dirige a la bóveda del cielo creando los cuerpos celestes. En las culturas paganas y en la astrología se consideran a los astros divinidades o con poderes divinos. Se los idolatra y se los atribuyen poder de destino en las vidas. Aun los nombres de los días de la semana reflejan la pagana asignación divina a los cuerpos celestes (Luna, Marte, Mercurio, Júpiter, etc.). Aquí se afirma que Dios creó todos los cuerpos celestes para ocupar el espacio superior del universo. Sus propósitos específicos son: establecer períodos de día y noche; ciclos de años; variaciones climáticas que condicionan el ciclo de vida (estaciones); servir de señales de las manifestaciones especiales de Dios (Mat 2:2,Mat 24:29, etc.) y alumbrar la Tierra reflejando la luz. Además, por su misterio e inmensidad, otro propósito es mover al ser humano a alabar la grandeza de Dios y confiar en el Creador (Sal. 8,Mat 136:5-9). El Sol y la Luna son mencionados por su cercanía, su influencia en proveer condiciones indispensables para la vida en la Tierra y por la tendencia del hombre a idolatrarlos. En las culturas contemporáneas influyentes a Israel (Egipto, Mesopotamia), el Sol y la Luna eran considerados divinidades principales. La revelación bíblica a Israel es clara y terminante: Estos cuerpos celestes son criaturas de Dios para beneficio del hombre.
(5) El quinto día,Mat 1:20-23. Los primeros seres vivientes del reino animal son los acuáticos y las aves. Las aguas participan en la creación al convertirse en el ambiente de vida para los seres acuáticos. Se clasifican en grandes animales (los más alejados del hombre) y los peces. Las aves son creadas para volar y ocupar el espacio sobre la Tierra en la bóveda. Todos son creados según sus especies y la palabra para crear es la que significa actividad única y exclusiva de Dios. Los seres vivientes reciben una bendición de Dios consistente en la capacidad de procreación, multiplicación y ocupación de los espacios o medio asignados.
(6) El sexto día,Mat 1:24-31. Nuevamente la tierra participa en la creación de animales, proveyendo las condiciones y los elementos necesarios para la vida. Se los agrupan en tres categorías: animales domésticos o ganado, animales que se arrastran o reptiles y animales silvestres o de la tierra. Estos grupos representan la totalidad de animales terrestres y son clasificados por especies, aunque no se determina una cantidad específica. Termina la creación de lo no humano. Todo lo creado hasta ahora es en preparación a la creación y sustento del hombre en quien de aquí en adelante la revelación bíblica se ocupará en forma especial.
En este relato, se describe a la creación de la humanidad completa, su identidad específica, lugar y propósito en el universo. En 2:4 y 18-23 se describe en forma más detallada e íntima la creación del hombre y la mujer.
Primero se anuncia la decisión y participación de la divinidad toda (Juan 1.1-3; 6:63) de crear al hombre, consistente con la enseñanza bíblica de un Dios trino. Segundo, su identidad y relación especial con Dios (a imagen y semejanza) que lo distingue de todos los otros seres vivientes. Por último su propósito: para ejercer dominio sobre lo creado en tierra, mar y aire. Se aclara que Dios crea al hombre y a la mujer dando así origen a la humanidad completa. Ambos fueron creados a imagen y semejanza, pero con diferenciación sexual. Tres veces se usa el verbo creó, reservado exclusivamente para la actividad creadora de Dios.
Dios los bendijo 1:28
La palabra hebrea usada es berek H1288. Este verbo tiene dos implicaciones. La primera es dar un privilegio o regalo de algo que viene directamente de la mano de Dios. Así los animales acuáticos reciben el privilegio de reproducirse (v. 22). El hombre y la mujer son bendecidos para reproducirse y tener dominio sobre toda la creación (v. 28). Isaac sembró la tierra y aquel año obtuvo el ciento por uno porque Jehová lo bendijo (Gen 26:12).
La segunda implicación es la exigencia de santidad. La bendición es un llamado al compromiso y la dedicación a Dios. Dios bendijo y santificó el séptimo día (Gen 2:3). Dios bendijo al hombre y a la mujer y llamó el nombre de ellos Hombre (Gen 5:2).
Hemos dado mucha importancia a la primera implicación de la bendición y con facilidad decimos a otra persona: &quot;Dios te bendiga&quot;. No está mal, pero ¿incluimos la implicación de &quot;dedícate y conságrate al Señor&quot;?
Dios bendice al hombre y a la mujer capacitándoles para la procreación, la ocupación del medio y el ejercicio de dominio sobre los otros seres vivientes. Además, Dios permite que las plantas sirvan de sustento al hombre y a los animales. Dios concede una elevada evaluación a todo lo creado que presenta un cuadro de perfecta armonía y equilibrio entre todos los seres y elementos creados.
Semillero homilético</p>
<br/>




</div>
