<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 49</h2>
<p class="text-justify">CAPITULO 49
Vers. 1-33. LA BENDICION PATRIARCAL.
1. llamó Jacob a sus hijos-En este capítulo, se llama la atención a los dichos no tanto del santo moribundo como del profeta inspirado. Bajo la influencia inmediata del Espíritu Santo él pronunció su bendición profética, y pintó la condición de sus respectivos descendientes en los últimos días, o tiempos futuros.
3-4. RUBEN. por su crimen perdió los derechos y honores de la primogenitura. Su posteridad nunca fué notable; de su tribu no provino ningún juez, profeta ni gobernante.
5-7. SIMEON y LEVI estuvieron asociados en maldad, y la misma predicción sería por igual aplicable a sus dos tribus. Leví tenía ciudades designadas para ellos (Josué 21) en todas las tribus. Por causa de su celo contra la idolatría, ellos fueron honorablemente “divididos en Jacob”; mientras que la tribu de Simeón, que era culpable de la idolatría más grosera y de los vicios con ella asociados, fué ignominiosamente “esparcida”.
8-12. JUDA. Una preeminencia suprema se destina a esta tribu (Num 10:14; Jdg 1:2). Además del honor de dar nombre a la Tierra Prometida, David y uno mayor que David, el Mesías, nacieron de ella. Principal entre las tribus, creció de un “cachorro de león”, o sea, un poder pequeño, hasta llegar a ser “león viejo”, tranquilo y quieto, sin embargo todavía formidable. hasta que venga Shiloh-Shiloh, esta palabra obscura se interpreta de varias maneras, para significar “el enviado” (Joh 17:3), “la simiente” (Isa 11:1), el “pacífico o próspero” (Eph 2:14), o sea, el Mesías (Isa 11:10; Rom 15:12); y cuando viniera él, “la tribu de Judá no se jactaría más de un rey independiente ni de un juez suyo propio”. (Calvino). Hace diez y ocho siglos que los judíos están sin gobernador y sin juez, puesto que vino Shiloh, y “a él se congregaron los pueblos”.
13. ZABULON había de tener su lote cerca de la costa de mar, junto a Sidón, y de ocuparse, como aquel estado, en las tareas marítimas y el comercio.
14, 15. ISSACHAR. Un asno fuerte agachado entre dos cargas o sea, había de ser activa esta tribu, paciente, dada a los trabajos agrícolas. Se estableció en la baja Galilea, una “tierra deleitosa”, asentándose entre los cananeos, donde, por amor al “descanso”, “bajó su hombro para llevar, y sirvió en tributo”.
16-18. DAN-aunque era hijo de una esposa secundaria, había de ser “como una de las tribus de Israel”. Dan, “juez”, serpiente … cerasta-Serpiente, cerasta, denota sutileza y estratagema; tal fué preeminentemente el carácter de Samsón el más ilustre de sus jueces.
19. GAD.-Esta tribu sería atacada a menudo y asolada por los pueblos hostiles sobre sus fronteras (Jdg 10:8; Jer 49:1). Pero generalmente ellos saldrían victoriosos al fin de sus guerras.
20. ASER “Bienaventurada”. Su porción era la costa de mar entre Tiro y Carmelo, distrito fértil en la producción del mejor trigo y aceite d toda Palestina.
21. NEPHTALI-La mejor traducción que conocemos es ésta: “Nephtalí es una cierva vagante en libertad; emite hermosos ramos”, o “majestuosas astas” (Taylor’s Scripture Illustrations); parece que el significado de la profecía es que la tribu de Neftalí sería ubicada en territorio tan fértil y tranquilo, que, alimentándose en los pastos más ricos, se extendería como la cierva extiende sus astas.
22. JOSE.-ramo fructífero, etc.-señala el crecimiento extraordinario de aquella tribu (comp. Num 1:33-36; Jos 17:17; Deu 33:17). El patriarca describe estas dos tribus como atacadas por la envidia, la venganza, la tentación, la ingratitud, sin embargo, todavía, por la gracia de Dios, triunfantes sobre toda oposición, de modo que vinieron a ser el sustentador de Israel; y entonces sigue derramando bendiciones de toda suerte sobre la cabeza de este hijo favorito. La historia de las tribus de Efraím y Manasés, demuestra cuán ampliamente estas bendiciones fueron realizadas.
27-33. BENJAMIN devorará como lobo. Esta tribu en su historia temprana gastó sus energías en guerras pequeñas o ignominiosas, especialmente en contiendas violentas e injustas (Jdg 19:20.), en las que se envolvía con las otras tribus, cuando, a pesar de haber obtenido dos victorias, fué casi exterminada.
28. Todos éstos fueron las doce tribus de Israel-o antepasados. Las palabras proféticas de Jacob evidentemente no se referían tanto a los hijos mismos como a las tribus de Israel.
29. Mandóles luego-El mandato ya había sido dado, y solemnemente aceptado (cap. 47:31). Pero al mencionar ahora sus deseos, y repetir todas las circunstancias relacionadas con la compra de Macpela, quiso declarar con su último aliento, ante toda su familia, que él moría en la misma fe de Abraham.
33. como acabó Jacob de dar órdenes a sus hijos-Es probable que fuera sobrenaturalmente fortalecido el patriarca para este último oficio importante, y que cuando cesó la inspiración divina, cediendo sus fuerzas agotadas, exhaló el espíritu, y fué reunido con sus padres.</p>
<br/>




</div>
