<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 2</h2>
<p class="text-justify">CAPITULO 2
Vers. 1. EL RELATO DE LA CREACION EN SEIS DIAS, CONTINUADO. El curso del relato fué inoportunamente interrumpido por la división del capítulo.
1. los cielos-el firmamento, o atmósfera, su ornamento-Palabra que en las Escrituras se refiere generalmente sólo a los cielos, pero aquí a la tierra también, significando todo lo que ellos contienen. (Más correctamente traducida, la palabra quiere decir “hueste, ejército”, como las estrellas innumerables se asemejan a un gran ejército.-Nota del Trad.) fueron acabados-la obra consumada. Desde entonces ningún cambio permanente se ha hecho en el curso del mundo; ninguna especie de animales ha sido formada; ninguna ley de la naturaleza ha sido abrogada ni ninguna añadida. Habrían podido ser “acabados” en un momento tan bien como en seis días, pero la obra de la creación fué gradual para la instrucción del hombre, como también, tal vez, para la de otras criaturas (Job 38:7).
2-7. EL PRIMER SABADO.
2. y reposó el día séptimo-no para reposar de agotamiento por el trabajo (véase Isa 40:28), mas cesó de trabajar, dando un ejemplo, que equivale a un mandato, para que nosotros también suspendamos toda clase de trabajos.
3. bendijo Dios al día séptimo, y santificólo.-haciéndole una distinción peculiar sobre los otros seis días, que muestra que fué dedicado a fines sagrados. La institución del sábado es tan vieja como la creación, dando origen a la división semanal del tiempo, la que prevaleció en las épocas más remotas. Es una ley sabia y benéfica, pues proporciona aquel intervalo regular de descanso que requiere la naturaleza física del hombre y de los animales empleados en su servicio, y la inobservancia del mismo trae en ambos casos una decadencia prematura. Además, si el descanso fué necesario en el estado de la inocencia primitiva, ¡cuánto más ahora, cuando el hombre se inclina a olvidar a Dios y sus demandas! (Nuestra palabra “sábado” viene del hebreo “sabath”, que quiere decir “descanso”.-N. del Trad.).
4. Estos son los orígenes de los cielos y de la tierra.-la historia o relato de su producción. ¿De dónde consiguió Moisés este relato tan diferente de las ficciones pueriles y absurdas de los paganos? No de una fuente humana, porque el hombre no existía para poder contemplarlo; no de la luz de la naturaleza y la razón, porque aunque ellas proclaman el poder y la divinidad por las cosas que fueron hechas, no pueden decir cómo fueron hechas. Nadie más que el Creador mismo podría dar esta información, y por lo tanto “por fe entendemos haber sido compuestos los siglos por la palabra de Dios” (Heb 11:3).
6. vapor.-véase cap. 1:12.
7. Aquí el escritor sagrado nos proporciona algunos datos más acerca de la primera pareja. formó-Había formado al hombre del polvo de la tierra. La ciencia ha probado que la sustancia de su carne, tendones y huesos, consiste en los mismos elementos del suelo que forman la corteza de la tierra y la piedra caliza que está en el interior de la tierra. Pero de aquel material tan ruin ¡qué admirable estructura se ha formado en el cuerpo humano! (Psa 139:14). soplo de vida-literalmente, en hebreo, “vidas”-no sólo la vida animal sino la espiritual también. Si es admirable el cuerpo, ¡cuánto más el alma con todas sus variadas facultades! alentó en su nariz soplo de vida-ne que el Creador literalmente ejecutara ese acto, pero siendo la respiración el medio y la señal de vida, se usa esta frase para mostrar que la vida del hombre se originó de una manera diferente de la de su cuerpo, pues fué implantada directamente por Dios (Ecclesiastés 12:7), y por lo tanto también en la nueva creación del alma, Cristo sopló sobre sus discípulos (Joh 20:22).
8-17. EL HUERTO DE EDEN.
8. Edén.-fué probablemente una región muy extensa en Mesopotamia, según se cree, distinguida por su hermosura natural y la riqueza y variedad de sus productos. De ahí su nombre que significa delicia. Dios plantó un huerto “al oriente”-un parque extenso, un paraíso, en el cual fué puesto el hombre para ser enseñado en la piedad y utilidad, bajo el cuidado paternal de su Hacedor.
9. el árbol de vida-así llamado por su carácter simbólico como señal y sello de la vida inmortal. Su posición prominente “en medio del huerto”, donde sería objeto de observación e interés diarios, estaba admirablemente adaptada para hacerles recordar constantemente a Dios y el porvenir eterno. árbol de ciencia del bien y del mal-así llamado porque tenía por objeto poner a prueba la obediencia por medio de la cual nuestros primeros padres habían de manifestar si eran buenos o malos, obedientes a Dios o rebeldes a sus mandamientos.
15. le puso en el huerto de Edén, para que lo labrara-no sólo para darle un empleo agradable, sino para ponerle a prueba, y como el título del huerto, el huerto de Jehová (cap. 13:10; Eze 28:13) lo indica, era en efecto un templo en el cual él adoraba a Dios, y se ocupaba diariamente en ofrecer los sacrificios de agradecimiento y alabanza.
17. no comerás de él … morirás-no se da ninguna razón para la prohibición, pero la muerte sería el castigo de la desobediencia. Un mandato positivo como éste, no sólo era la prueba más sencilla y más fácil, sino la única a la cual podría exponerse su fidelidad.
18-25. LA CREACION DE LA MUJER, Y LA INSTITUCION DEL MATRIMONIO.
18. No es bueno que el hombre esté solo-En medio de la abundancia y los deleites, el hombre era consciente de sentimientos que no podía satisfacer. Para hacerlo sensible a sus necesidades,
19. Dios trájolas a Adam-no todos los animales existentes, sino los principales que estaban en las cercanías, y los que habían de serle útiles. todo lo que Adam llamó a los animales vivientes, ese es su nombre-Sus poderes de percepción e inteligencia estaban sobrenaturalmente aumentados para que conociera el carácter, los hábitos y usos de cada especie que le era traída.
20. mas para Adam no halló ayuda idónea para él-El propósito de esta escena singular era el de mostrarle que ninguna de las criaturas vivientes que él veía, era de condición igual a él, y que mientras cada especie tenía su compañero de la misma naturaleza, forma y hábitos, sólo él no tenía compañera. Además, al darles nombres, él fué inducido a ejercer sus facultades de habla, y así prepararse para el trato social con su compañera, criatura todavía a ser formada.
21. sueño-probablemente un éxtasis o rapto como los de los profetas, cuando tenían visiones o revelaciones del Señor, porque probablemente toda la escena fué visible a los ojos mentales de Adam, y de ahí su exclamación maravillosa. tomó una de sus costillas-“Ella no fué de una parte de su cabeza para sobresalir a él, ni de sus pies para ser pisoteada, sino de su costado para ser igual a él, y de cerca de su corazón para serle querida.”
24. una sola carne-la pareja humana se diferenciaba de todas las demás parejas, en que, por la formación peculiar de Eva, eran uno. A este pasaje apela nuestro Señor para probar que el matrimonio es institución divina (Mat 19:4-5; Eph 5:28). Así, pues, Adam aparece como criatura formada a la imagen de Dios, mostrando su conocimiento al dar nombres a los animales, su justicia por su aprobación de la relación conyugal, y su santidad por sus principios y sentimientos, hallando la satisfacción de ellos en el servicio y la felicidad con Dios.</p>
<br/>




</div>
