<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">CAPITULO 1
Vers. 1, 2. LA CREACION DEL CIELO Y LA TIERRA.
1. En el principio-un período de antigüedad lejano y desconocido, escondido en las profundidades de las edades eternas; y así se usa la frase en Pro 8:22-23, también Referencia marginal. Dios-el nombre del Ser Supremo, que significa en Hebreo, “Fuerte”, “Poderoso”. Es expresivo de poder omnipotente; y por su uso aquí en la forma plural, se enseña obscuramente en el mismo principio de la Biblia, una doctrina claramente revelada en otras partes de la misma; es decir, que aunque Dios es uno, hay una pluralidad de personas en la deidad-Padre, Hijo y Espíritu, que estaban ocupados en la obra creadora (Pro 8:27; Joh 1:3, Joh 1:10; Eph 3:9; Heb 1:2; Job 26:13). crió-no formó de materiales preexistentes, mas hizo de la nada. los cielos y la tierra-el universo. Este primer versículo es una introducción general al tomo inspirado, que declara la grande e importante verdad de que todas las cosas tuvieron su principio: que nada por toda la ancha extensión de la Naturaleza existía desde la eternidad, ni se originó por la suerte ni por la pericia de algún agente inferior; sino que todo el universo fué producido por el poder creador de Dios (Act 17:24; Rom 11:36). Después de este prefacio, el relato se limita a la tierra.
2. la tierra estaba desordenada y vacía-o en “confusión y vaciedad”, como se traducen las palabras en Isa 34:11. (En la versión inglesa, quiere decir el autor. Nota del Trad.). Habiendo sido convulsionado este globo terráqueo, en algún período desconocido, era una extensión desolada, obscura y anegada, hasta que, de entre este estado caótico, surgió la actual estructura del mundo. el Espíritu de Dios se movía-literalmente, continuaba cubriéndola, como hace el ave empollando los huevos. La agencia inmediata del Espíritu, obrando sobre los elementos muertos y discordantes, los combinaba, arreglaba y preparaba adaptándolos para ser la escena de una creación nueva. El relato de esta nueva creación correctamente empieza al final de este segundo versículo; y los detalles del proceso se describen de la manera natural como lo habría hecho un espectador, que veía los cambios que sucesivamente se efectuaban.
3-5. EL PRIMER DIA.
3. dijo Dios-Esta frase, que se menciona tan repetidamente en el relato, quiere decir “resolvió, decretó, estableció”; y la voluntad determinante de Dios fué seguida en cada caso por un resultado inmediato. Sea que el sol fuera creado al mismo tiempo que la tierra, o mucho antes, la densa acumulación de neblinas y vapores que envolvía el caos, había cubierto nuestra esfera con una obscuridad absoluta. Pero por el mandato de Dios, la luz se hizo visible; las grandes nubes lóbregas fueron disipadas, rotas o enrarecidas, de modo que la luz se difundió sobre la expansión de aguas. El efecto se describe en el nombre DIA, que en hebreo significa calor; mientras que el nombre NOCHE significa ARROLLAR. pues la noche envuelve todas las cosas en un manto obscuro.
4. apartó Dios la luz de las tinieblas-se refiere a la alternación o sucesión de la una a la otra, producida por la rotación diaria de la tierra sobre su eje.
5. un día-o día primero. Día natural, como lo determina claramente la mención de sus dos partes. Moisés calcula, según la usanza oriental, de puesta de sol a puesta de sol, y por lo tanto no dice “día y noche” como nosotros, sino “la tarde y la mañana.”
6-8. EL DIA SEGUNDO.
6. expansión-firmamento-cosa extendida a fuerza de golpear, como un plato de metal; nombre dado a la atmósfera por su apariencia al observador de ser una bóveda de cielo, que sostenía el peso de las nubes acuosas. Por la creación de una atmósfera, las partes más livianas de las aguas que cubrían la superficie de la tierra, fueron absorbidas para arriba y suspendidas en los cielos visibles, mientras la masa grande y más pesada quedaba abajo. El aire entonces estaba “en medio de las aguas”, es decir, las separaba; y como éste era el uso aparente del aire, es el único mencionado, aunque la atmósfera sirve para otros usos, como medio de vida y luz.
9-13. EL TERCER DIA.
9. Júntense las aguas que están debajo de los cielos en un lugar-El mundo había de ser una esfera terráquea, y esto se efectuó por una convulsión volcánica en su superficie, solevantando algunas partes, y hundiendo otras, y la formación de grandes huecos en los cuales las aguas se lanzaron impetuosamente, como se describe tan gráficamente. (Psa 104:6-9). (Hitchcock.) Así una buena parte de la tierra quedó como “la seca”, y así también fueron formados los océanos, mares, lagos y ríos que, teniendo todos sus propios lechos o canales, están unidos con el mar (Job 38:10; Ecclesiastés 1:7).
11. Produzca la tierra-El suelo desnudo se cubrió de vegetación, y es de notarse que los árboles, las plantas y las hierbas-tres divisiones del reino vegetal, aquí mencionadas-no fueron llamados a la existencia de la misma manera que la luz y el aire; se les hizo crecer, y crecieron, así como todavía crecen de entre la tierra-pero no por el lento proceso de la vegetación, sino por poder divino, sin lluvia, ni rocío ni proceso alguno de trabajo-brotando y floreciendo en un solo día.
14-19. EL CUARTO DIA.
14. Sean lumbreras en la expansión-Estando completamente purificada la atmósfera, por primera vez el sol, la luna y las estrellas fueron revelados en toda su gloria en el cielo límpido; se les describe como “en la expansión”, o firmamento, como aparecen a nuestros ojos, aunque sabemos que están a una distancia enorme de la tierra.
16. las dos grandes lumbreras-Como el día se calculaba empezando a la puesta del sol, la luna sería vista primero en el horizonte, parecería “una grande lumbrera”, comparada con las pequeñas estrellas centellantes; aunque el pálido resplandor de ella sería eclipsado por la deslumbrante brillantez del sol. Cuando su brillante orbe se levantara en la mañana y gradualmente llegara a su gloria meridiana, aparecería “la grande lumbrera” que iba a señorear en el día. Estas dos lumbreras, se dice fueron “hechas” en el cuarto día-no creadas, pues aquí se usa una palabra diferente, sino constituídas, destinadas al importante y necesario oficio de servir como lumbreras al mundo, y de regular por sus movimientos y su influencia el progreso y las divisiones del tiempo.
20-23. EL QUINTO DIA. Las señales de la vida animal aparecen en las aguas y en el aire.
20. de ánima viviente-todos animales ovíparos, entre las criaturas de aletas y las de plumas-notables por su rápida y aun prodigiosa multiplicación. aves-todo animal que vuela. La palabra traducida “ballenas”, incluye también los cocodrilos, tiburones, etc., de modo que desde los innumerables cardumes de pececitos hasta los grandes monstruos del mar, desde el diminuto insecto hasta el rey de los pájaros, a las aguas y al aire repentinamente se les hizo abundar en criaturas formadas para vivir y prosperar en sus respectivos elementos.
24-31. EL SEXTO DIA. En este día hubo más progreso por la creación de animales terrestres, todas las diferentes especies de los cuales están incluídas en tres clases-es decir, el ganado, herbívoros, capaces de trabajo y domesticación.
24. animales de la tierra-animales silvestres, cuya naturaleza voraz fué entonces refrenada, y todas las diferentes formas de serpientes-toda clase de reptiles hasta los insignificantes gusanos.
26. Llegando ahora a la ultima etapa en el progreso de la creación, dijo Dios: Hagamos al hombre-palabras que muestran la peculiar importancia de la obra que estaba por hacerse, la formación de una criatura, que había de ser el representante de Dios, investida de autoridad y dominio como visible cabeza y monarca del mundo a nuestra imagen, conforme a nuestra semejanza-Esta es una distinción peculiar, cuyo valor aparece en el hecho de que las palabras se repiten dos veces. Y ¿en qué consistía esta imagen de Dios?-no en la forma recta o vertical o en las facciones del hombre, no en su inteligencia, porque a este respecto el diablo y los ángeles son muy superiores; no en su inmortalidad, porque no tiene, como Dios, una eternidad pasada como una futura, sino en las disposiciones morales de su alma, comúnmente llamadas justicia original (Ecclesiastés 7:29). Como la nueva criatura no es sino una restauración de esta imagen, la historia de la una arroja luz sobre la otra; y se nos informa que es renovada según la imagen de Dios en conocimiento, justicia y verdadera santidad (Eph 4:24; Col 3:10).
28. Fructificad, etc.-la raza humana en todos los países y en todas las edades ha sido la descendencia de la primera pareja. De todas las variedades halladas entre los hombres, algunos negros, otros de color cobrizo como también blancos, las investigaciones de la ciencia moderna llevan a la conclusión, todas completamente acordes con la historia sagrada, de que todos son de una especie y de una familia (Act 17:26). ¡Qué poder en la palabra de Dios! “El dijo, y fué hecho; él mandó, y existió.” “¡Cuán muchas son tus obras, oh Jehová! Hiciste todas ellas con sabiduría”. Admiramos aquella sabiduría, no sólo en el progreso regulado de la creación sino en su perfecta adaptación al fin. Se representa a Dios como haciendo una pausa a cada etapa para contemplar su obra. No es maravilla que la contemplara con complacencia. Cada objeto estaba en su lugar correcto, cada proceso vegetal progresaba según su estación, todo animal estaba en su estructura e instinto ajustado a su modo de vida, y a su uso en la economía del mundo. Vió todas las cosas que había hecho, respondiendo al plan que su eterna sabiduría había concebido; y, v. 31. “HE AQUI QUE ERA BUENO EN GRAN MANERA”.</p>
<br/>




</div>
