<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 3</h2>
<p class="text-justify">CAPITULO 3
Vers. 1-5. LA TENTACION.
1. serpiente-La caída del hombre fué efectuada por las seducciones de una serpiente. Que haya sido una serpiente verdadera, es evidente por el estilo claro y natural de la historia, y por las muchas alusiones hechas a ella en el Nuevo Testamento. Pero la serpiente material fué el instrumento o la herramienta de un agente superior, Satanás o el Diablo, a quien los escritores sagrados aplican por este incidente el nombre infamante de “la serpiente”, “el viejo dragón”. Aunque Moisés no hace mención de este espíritu malévolo-dándonos sólo la historia del mundo visible-sin embargo, en los descubrimientos más completos del evangelio, se insinúa claramente que Satanás fué el autor del complot (Joh 8:44; 2Co 11:3; 1Jo 3:8; 1Ti 2:14; Rev 20:2). astuta, más que todos-Es proverbial la sabiduría de las serpientes. (Mat 10:16). Pero estos reptiles eran en el principio, muy superiores en hermosura y sagacidad de lo que son en su estado actual. la cual dijo-No habiendo en el corazón puro de la primera pareja ningún principio de mal sobre el cual obrar, una incitación para pecar no podría venir sino de afuera, como en el caso análogo de Jesucristo (Mat 4:3); y como el tentador no pudo asumir la forma humana, habiendo en el mundo sólo dos seres humanos, Adam y Eva, la agencia de una criatura inferior tenía que ser empleada. El Dragón-serpiente (Bochart) parecía el más apto para el vil propósito; y al Diablo le fué permitido por Dios, quien permitió la prueba, sacar sonidos articulados y claros de la boca del animal. a la mujer-el objeto del ataque, debido al conocimiento que tenía de la fragilidad de ella, por haber estado sólo un corto tiempo en el mundo, y por su limitada experiencia de las tribus animales, y sobre todo estando ella sola, no protegida por la presencia y los consejos de su esposo. Aunque sin pecado y santa era ella agente libre, propensa a ser tentada y seducida. ¿Conque Dios os ha dicho-¿Es verdad que él os ha limitado en el uso de las frutas de este lugar delicioso? Esto no parece cosa de un ser tan bueno y bondadoso. Seguramente hay algún error. Insinuó una duda en cuanto a la opinión de ella acerca de la voluntad divina, y apareció como “ángel de luz” (2Co 11:14), ofreciendo conducirla a la verdadera interpretación. Es evidente por el hecho de que ella le consideraba como enviado especialmente con aquel mensaje que, en vez de asustarse de que el reptil hablara, lo recibió como mensajero celestial.
2. la mujer respondió … Del fruto de los árboles del huerto comemos-En su contestación, Eva ensalzó la grande extensión de la libertad que ellos gozaban en andar libremente entre todos los árboles-exceptuando uno solo-respecto a los cuales ella declaró que no había ninguna prohibición de pena. Pero motivo hay para creer que ella ya había recibido una impresión dañosa, porque usando las palabras “para que no muráis” en vez de “seguramente moriréis”, ella habló como si pensara que el árbol hubiese sido prohibido porque su fruto fuera venenoso. Viendo esto el tentador, se hizo más atrevido en sus afirmaciones.
4. No moriréis-él procedió, no sólo a asegurarle una perfecta impunidad, sino a prometer grandes beneficios al participar de él.
5. serán abiertos vuestros ojos-Sus palabras significaban más de lo que percibió al oído. En un sentido sus ojos fueron abiertos; porque adquirieron una experiencia horrible del “bien y del mal”, de la felicidad de una condición santa, y de la miseria de una condición pecaminosa. Pero él ocultó a Eva este resultado, quien, entusiasmada por un generoso deseo de conocimiento, pensó sólo en elevarse al rango y a los privilegios de su visitante celestial.
6-9. LA CAIDA.
6. Y vió la mujer que el árbol era bueno para comer-Su imaginación y sus sentidos fueron completamente vencidos; y la caída de Eva fué pronto seguida por la de Adam. La historia de todas las tentaciones, y de todo pecado, es la misma: el objeto exterior de atracción, la conmoción interior de la mente, el aumento y triunfo del deseo apasionado; terminando en la degradación, esclavitud y ruina del alma (Jam 1:15; 1Jo 2:16).
8. oyeron la voz de Jehová Dios que se paseaba en el huerto-El Ser divino apareció de la misma manera que antes, emitiendo las bien conocidas palabras de bondad, caminando en alguna forma visible-no corriendo con ímpetu, como alguno impelido por la influencia de sentimiento de ira. ¡Cuán hermosamente expresivas son estas palabras referentes a la manera familiar y condescendiente en que antes tenía comunión con la primera pareja! al aire del día-en la tardecita fresca, escondióse el hombre y su mujer de la persencia de Jehová Dios-Vergüenza, remordimiento, temor, una sensación de culpa, sentimientos a los cuales ellos hasta ahora habían sido extraños, trastornaron sus mentes, y los llevaron a esceparse de Aquel cuya llegada antes recibían con gozo. ¡Qué torpeza pensar en escaparse de su presencia! (Psa 139:1-12).
10-13. EL EXAMEN.
10. tuve miedo, porque estaba desnudo-aparentemente una confesión, lenguaje de pesar; pero evasivo, sin señales de verdadera humildad y penitencia; cada uno trata de echar la culpa sobre el otro.
12. La mujer que me diste-El culpa a Dios. (Calvino.) Como la mujer le había sido dada por compañera y ayuda, él había comido del árbol por amor a ella; y viendo que estaba arruinada, él resolvió no sobrevivirle. (M’Knight.)
13. me engañó-la engatuzó con mentiras lisonjeras. Este pecado de la primera pareja fué atroz y agravante; no fué simplemente acto de comer una manzana, sino amor de sí mismos, deshonra a Dios, ingratitud a un bienhechor, desobediencia al mejor de los maestros, preferencia de la criatura sobre el Creador.
14-24. LA SENTENCIA.
14. Y Jehová Dios dijo a la serpiente-El juez pronuncia un juicio sobre la serpiente material, que es maldecida sobre todas las criaturas; de un modelo de gracia y elegancia en la forma, ha venido a ser el tipo de todo lo odioso, lo repugnante y lo vil (Leclerc, Rosenmuller.); o la maldición ha convertido su condición natural en castigo; ahora es señalada con infamia y evitada con horror. Luego sobre la Serpiente espiritual, el seductor. Ya caído, él había de ser degradado todavía más, y totalmente destruído su poder, por la simiente de los que él había engañado.
15. tu simiente-no sólo los espíritus malvados, sino también hombres perversos. simiente de la mujer-el Mesías y su Iglesia. (Calvino, Hengstenberg). enemistad pondré entre ti y la mujer-Sólos se puede decir que Dios obra así dejando “a la serpiente y a su simiente a la influencia de su propia corrupción; y aquellas medidas, seguidas para la salvación de los hombres, llenan a Satanás y a sus ángeles de envidia y furor.” tú le herirás en el calcañar-La serpiente hiere el calcañar que la aplasta; y así a Satanás se le permitirá afligir la humanidad de Cristo, y traer sufrimiento y persecución sobre su pueblo. ésta te herirá en la cabeza-el veneno de la serpiente está en la cabeza; y una herida en esa parte es fatal. Así, fatal será el golpe que Satanás recibirá de Cristo; pero es probable que él no entendiera en el principio la naturaleza y la magnitud de la condena.
16. A la mujer dijo: Multiplicaré en gran manera tus dolores-Ella fué condenada como esposa y madre, a sufrir dolor del cuerpo y angustia de la mente. De compañera y ayuda del hombre y partícipe de su cariño, su condición de aquí en adelante sería la de humilde sujeción.
17-19. al hombre dijo-obligado a ganar la vida labrando la tierra; pero lo que antes de la caída hacía con facilidad y placer, no había de conseguirse después sin esfuerzos penosos y perseverantes.
19. hasta que vuelvas a la tierra-El hombre se conviritió en mortal; aunque no murió en el momento que comió la furta prohibida, su cuerpo experimentó un cambio, y aquel cambio lo llevaría a la disolución. Habiendo sido disuelta la unión entre su alma y Dios, quedaba expuesto a todas las miserias de esta vida, y a los sufrimientos del infierno para siempre. ¡Qué lúgubre capítulo es éste, en la historia del hombre! Nos da el único relato verdadero del origen de todos los males físicos y morales que hay en este mundo, mientras que apoya el carácter moral de Dios; demuestra que el hombre, hecho justo, cayó por no poder resistir una leve tentación; y haciéndose culpable y miserable, sumió a toda su posteridad en el mismo abismo. (Rom 5:12). ¡Cuán asombrosa la gracia que en aquel momento dió la promesa de un Salvador; y confirió sobre aquella que tenía la ignominia de introducir el pecado, el honor futuro de introducir al Redentor! (1Ti 2:15).
20. llamó al hombre el nombre de su mujer, Eva-probablemente con referencia a que ella sería la madre del Salvador prometido, como también de toda la humanidad.
21. Dios hizo … túnicas de pieles-Los enseñó a hacérselas. Esto abarca la institución del sacrificio de animales, que seguramente era por orden divina, y la instrucción en el único modo de culto acepto para criaturas pecaminosas, por fe en un Redentor. (Heb 9:22).
22. dijo Jehová Dios: He aquí el hombre es como uno de Nos-no dicho con ironía, como generalmente se supone, sino con profunda compasión. Las palabras deberían traducirse: “He aquí, ¡lo que ha llegado a ser el hombre que era como uno de Nos!” formado al principio a nuestra imagen conociendo el bien y el mal-¡cuán triste su condición ahora! ahora, pues, porque no alargue su mano, y tome también del árbol de la vida-siendo el árbol una garantía de vida inmortal con la cual había de premiarse la obediencia, el hombre, en la caída, perdió todo derecho al árbol; y por lo tanto, para que no comiera de él, o se hiciera la ilusión de que comiendo de él, recobraría lo que había perdido, el Señor lo desterró del huerto.
24. puso … querubines-El pasaje debería traducirse: “Y él habitó entre los querubines al este del huerto de Edén, y un fuego terrible (o shechinah) desarrollándose para guardar el camino del árbol de la vida”. Este era el modo de culto establecido ahora, para mostrar la ira de Dios por el pecado, y enseñar la mediación del Salvador prometido, así como el camino de la vida, y también de acceso a Dios. Estas eran las misma figuras que más tarde estaban en el tabernáculo y en el templo; y ahora, como entonces, Dios dijo: “Hablaré contigo … de entre los dos querubines” (Exo 25:22).</p>
<br/>




</div>
