<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 3</h2>
<p class="text-justify">SURGIMIENTO DE JUAN EL BAUTISTA
Mateo 3:1-6
Por aquel tiempo apareció en escena Juan el Bautista, predicando en el desierto de Judasa:
-¡Arrepentíos, que el Reino del Cielo está cerca!
Fue de este hombre del que hablaba el profeta Isaías cuando dijo: &quot; La voz de uno de clama en el desierto: &quot;¡Preparad el camino por donde ha de venir el Señor, y enderezad las sendas por donde ha de viajar!&quot;»
El mismo Juan llevaba una ropa hecha de pelo de camello, con un cinturón de cuero en la cintura; y su comida consistía en langostas y miel silvestre. Entonces la gente de Jerusalén y Judasa y todos los distritos de alrededor del Jordán salía a su encuentro, y él los bautizaba en el río Jordán mientras ellos confesaban sus pecados.
El surgimiento de Juan fue como el repentino resonar de la. voz de Dios. En aquel tiempo los judíos habían aceptado tristemente el hecho de que la voz profética ya no se dejaba oír. Decían que hacía cuatrocientos años que no había profetas. Como ellos mismos decían, «no se escuchaba la voz, y no había nadie que respondiera.» Pero en Juan volvió a resonar la voz. Ahora debemos preguntarnos cuáles eran las características de Juan y de su mensaje.
(i) Denunciaba intrépidamente el mal cuando y dondequiera que lo encontraba. Si era el mismo rey Herodes el que pecaba contrayendo un matrimonio malvado e ilegal, Juan le reprendía. Si los escribas y los fariseos, los líderes del judaísmo ortodoxo, los jerarcas de la iglesia de aquellos tiempos, estaban inmersos en un formalismo ritualista, Juan no dudaba en declararlo. Si la gente corriente vivía volviéndole las espaldas a Dios, Juan se lo decía.
Siempre que Juan veía el mal -en el estado, en la iglesia, en la sociedad-, lo denunciaba. Era como una luz que iluminaba los lugares tenebrosos; era como el viento de Dios que barría todo el país. Se decía de un famoso periodista que era grande, pero que nunca cumplió plenamente la obra que hubiera podido llevar a cabo, que &quot;no se indignaba lo suficiente.» Hay siempre un lugar en el mensaje cristiano para la advertencia y para la denuncia. «La verdad -decía Diógenes- es como la luz para los ojos irritados.» &quot;El que no ofende nunca a nadie -decía- nunca le hace ningún bien a nadie.»
Puede que haya habido tiempos en los que la Iglesia ha tenido demasiado cuidado de no ofender; pero hay situaciones en las que ya ha pasado la hora de la cortés suavidad, y ha llegado la de la reprensión terminante.
(ii) Convocaba urgentemente a la gente a la justicia. El mensaje de Juan no era una mera denuncia negativa; era una positiva presentación de las exigencias morales de Dios. No sólo denunciaba el mal que se hacía; también emplazaba al bien que se debía hacer. No sólo condenaba a los hombres por cómo eran; también los desafiaba a ser como podían ser. Era como una voz que convocaba a cosas más elevadas. No sólo reprendía el mal, sino también presentaba el bien.
Puede que haya habido tiempos en los que la Iglesia estaba demasiado ocupada en decirle a la gente lo que no tenía que hacer, y demasiado poco en presentarle la cima del ideal cristiano.
(iii) Juan venía de Dios. Procedía del desierto. Llegó hasta los hombres después de años de solitaria preparación con Dios. Como decía Alexander Maclaren, «fue como si Juan saltara a la palestra plenamente desarrollado y armado.» Y traía, no algunas opiniones personales suyas, sino un mensaje de Dios. Antes de hablar a los hombres había estado largo tiempo en comunión con Dios.
El predicador, el maestro de voz profética, deben siempre venir a presentarse ante los hombres de la presencia de Dios.
(iv) Juan señalaba más allá de sí mismo. Era no solamente una luz que iluminaba el mal, una voz que reprendía el pecado; era también un indicador hacia Dios. No era a sí mismo al que quería que miraran, sino quería prepararlos para que reconocieran al Que había de venir.
Los judíos creían que Elías volvería antes de que llegara el Mesías, y que sería el heraldo del Rey en Su venida. «Yo os envío al profeta Elías antes que llegue el día grande y terrible del Señor» (Mal 4:5 ). Juan llevaba una ropa de pelo de camello, sujeta con un cinturón de cuero a la cintura. Esa era la descripción de cómo había ido vestido Elías (2Re 1:8 ).
Mateo le conecta con una profecía de Isaías (40:3). En los tiempos antiguos en Oriente, las carreteras eran muy malas. Había un proverbio oriental que decía: «Hay tres situaciones miserables: la enfermedad, el hambre y el viajar.» Antes de ponerse en camino para un largo viaje, se aconsejaba: «Pagar las deudas, proveer para la familia, hacer regalos de despedida, devolver todos los depósitos y hacer acopio de dinero y de buen humor para el viaje; y, por último, decir adiós a todos.» Las carreteras ordinarias no eran más que senderos. No estaban en absoluto pavimentadas, porque el suelo de Palestina es duro, y soporta el tráfico de mulas, borricos, bueyes y carretas. Un viaje por esas carreteras era toda una aventura, y, por supuesto, algo que no se hacía nada más que cuando no se tenía más remedio.
Había algunas carreteras pavimentadas y construidas artificialmente. Josefo, por ejemplo, nos refiere que Salomón cubrió las calzadas que iban a Jerusalén de basalto negro para facilitarles el viaje a los peregrinos y «para hacer alarde del buen estado de la economía de su gobierno.» Todas las carreteras trazadas y pavimentadas las construían los reyes y para el uso de los reyes. De ahí que se las llamara «calzadas reales.» Se mantenían en buen estado de conservación sólo si el rey las necesitaba para sus viajes. Antes de que llegara el rey a una zona, se pregonaba un mensaje para que la gente tuviera la carretera real en orden para la visita del rey.
Juan estaba preparándole el camino al Rey. El predicador y el maestro de voz profética no llaman la atención a sí mismos, sino a Dios. Lo que se proponen no es que la gente se fije en su propia inteligencia, sino en la majestad de Dios. El verdadero predicador se hace invisible en su mensaje.
La gente reconocía a Juan como profeta, aun cuando hacía muchos años que no se escuchaba la voz profética, porque era una luz que alumbraba las cosas malas, una voz que convocaba a la justicia, un indicador que señalaba hacia Dios; y porque tenía en sí esa autoridad incontestable que irradian los que vienen de la presencia de Dios a presentarse ante los hombres.</p>
<br/>
<p class="text-justify">EL MENSAJE DE JUAN - LA AMENAZA
Mateo 3:7-12
Cuando vio Juan que muchos de los que acudían a su bautismo eran de los fariseos y de los saduceos, les dijo:
-¡Raza de víboras! ¿Quién os puso en la mente el huir de la ira venidera? Producid frutos que acrediten vuestro arrepentimiento. No creáis que os podéis decir: «Tenemos a Abraham por padre.» Porque os digo que Dios puede suscitarle hijos a Abraham hasta de estas piedras. Ya está dispuesta el hacha a la raíz de los árboles, y todo el que no dé buen fruto está a punto de que lo corten y echen al fuego. Yo os bautizo con agua para que os arrepintáis; pero el Que viene detrás de mí es más fuerte que yo y yo no sirvo ni para llevarle las sandalias: Él es el Que os bautizará con el Espíritu Santo y con fuego. Ya tiene el soplillo en la mano para limpiar afondo Su era; y luego recogerá el grano en Su granero, y quemará la paja con un fuego que nadie podrá extinguir.
En el mensaje de Juan había amenaza y había promesa. Todo su mensaje estaba lleno de ilustraciones vívidas.
Juan llama a los fariseos y a los saduceos raza de víboras, y les pregunta que quién les ha aconsejado huir de la ira venidera. Puede que haya aquí una de dos imágenes.
Juan conocía el desierto. Había en algunos sitios yerbajos secos y espinos achaparrados por la falta de humedad. Algunas veces se producía un fuego, que se extendía rápidamente por la hierba seca y los arbustos resecos como la yesca. Y adelantándose al fuego se veían escabullirse a toda prisa las serpientes y los alacranes y todos los animalejos que tenían su hábitat en la poca maleza disponible. El río de fuego los echaba de sus guaridas, y corrían como locos huyendo de la quema.
Pero puede que haya aquí otra imagen. Hay muchos animalillos en un campo de trigo: ratones de campo, ratas, conejos, pájaros. Pero cuando llegan los segadores, los echan de sus nidos y guaridas y, como el campo queda al descubierto, tienen que huir para salvar la vida.
Es en estas escenas en las que está pensando Juan. Si los fariseos y los saduceos venían buscando de veras el bautismo, eran como esas alimañas escabulléndose del fuego que se les echaba encima o de la hoz del segador que estaba poniendo fin a su precaria seguridad.
Juan les advierte que no les va a servir de nada alegar que Abraham es su padre. Para los judíos ortodoxos esa era una afirmación alucinante. Para los judíos, Abraham era único. Tan único era en su bondad y en el favor de Dios que sus méritos bastaron, no sólo para él mismo, sino también para todos sus descendientes. Había allegado tal tesoro de méritos que no podían agotarlo todas las pretensiones y necesidades de todos sus descendientes. Así es que los judíos creían que simplemente por ser judíos, sin ningún mérito propio, estaban a salvo en la vida por venir. Decían: «Todos los israelitas tienen segura su porción en el mundo venidero.» Hablaban de «los méritos liberadores de los padres.» Decían que Abraham se sentaba a las puertas de la gehena para darle la vuelta a cualquier israelita que resultara haber sido destinado a sus terrores. Decían que eran los méritos de Abraham lo que permitía que los barcos navegaran a salvo por los mares; lo que hacía que la lluvia descendiera sobre la tierra; lo que hizo que Moisés pudiera acceder al Cielo para recibir la Torá; lo que hizo que David fuera oído. Los méritos de Abraham eran suficientes hasta para los malvados. &quot;Si tus hijos -decían de Abraham- no fueran más que cuerpos muertos, sin venas y sin huesos, ¡tus méritos les serían suficientes!»
Era ese espíritu lo que Juan estaba reprendiendo. Puede que los judíos lo llevaran al último extremo, pero siempre hay que advertir que no se puede vivir del capital espiritual del pasado. Una edad degenerada no puede esperar obtener la salvación gracias a un pasado heroico; y un mal hijo no puede alegar a su favor los méritos de sus piadosos padres.
Así que Juan, otra vez, vuelve a la metáfora de la cosecha. Al final de la estación, el guarda de las viñas y de las higueras y de los olivos pasaría revista a sus árboles; y quitaría de en medio los que no habían dado fruto. No harían más que esquilmar el terreno. La inutilidad siempre invita al desastre. La persona que es inútil para Dios y para sus semejantes corre un grave peligro y está bajo condenación.
EL MENSAJE DE JUAN - LA PROMESA
Mateo 3:7-12 (continuación)
Pero inmediatamente después de la amenaza de Juan venía la promesa -que también contenía una amenaza. Como ya hemos dicho, Juan señalaba más allá de sí mismo a Uno Que había de venir. De momento, Juan disfrutaba de una gran reputación, y blandía una influencia muy poderosa. Sin embargo dijo que no merecía ni llevarle las sandalias al Que había de venir y llevar las sandalias era una labor de esclavo. La actitud total de Juan era de auto-obliteración, no de autoexaltación. Él reconocía que su importancia consistía en que era un indicador que señalaba al Que había de venir.
Dijo que el Que había de venir los bautizaría con el Espíritu Santo y con fuego.
A lo largo de toda su historia, los judíos había estado esperando el tiempo en que había de venir el Espíritu. Ezequiel oyó decir a Dios: «Os daré un corazón nuevo y pondré un espíritu nuevo dentro de vosotros... Pondré dentro de vosotros Mi Espíritu, y haré que andéis en Mis estatutos y que guardéis Mis preceptos y los pongáis por obra» (Eze 36:26 s). «Pondré Mi Espíritu en vosotros y viviréis» (Eze 37:14 ). &quot;No esconderé más de ellos Mi rostro; porque habré derramado sobre ellos de Mi Espíritu sobre la casa de Israel, dice el Señor Dios» (Eze 39:29 ). «Porque Yo derramaré aguas sobre el sequedal, ríos sobre la tierra seca. Mi Espíritu derramaré sobre tu descendencia, y Mi bendición sobre tus renuevos» (Isa 44:3 ). «Después de esto derramaré Mi Espíritu sobre todo ser humano» (Joe 2:28 ).
Entonces, ¿qué es el don y la obra del Espíritu de Dios? Al tratar de contestar esta pregunta debemos recordar que tenemos que hacerlo en términos Hebreos. Juan era judío, y hablaba a los judíos. Pensaba y hablaba, no en los términos de la doctrina cristiana del Espíritu Santo, sino en los de la doctrina judía del Espíritu.
(i) La palabra hebrea para espíritu es rúaj, y rúaj, como pneuma en griego, quiere decir no sólo espíritu, sino también aliento. El aliento es la vida; y por tanto, la promesa del Espíritu es la promesa de la vida. El Espíritu de Dios alienta la vida de Dios en las personas. Cuando el Espíritu de Dios entra en nosotros, nuestra vida cansada, desvaída y derrotada desaparece, y una oleada de nueva vida entra en nosotros y nos hace nuevas criaturas.
(ii) Esta palabra rúaj no sólo quiere decir aliento, sino también viento. Es la palabra que designa el viento de la tempestad, el poderoso turbión que una vez oyó Elías. Viento quiere decir poder. La tempestad de viento se lleva los navíos por delante y desarraiga los árboles. El viento tiene un poder irresistible. El Espíritu de Dios es el Espíritu de poder. Cuando el Espíritu de Dios entra en un hombre, su debilidad se reviste del poder de Dios. Es capaz de hacer lo irrealizable, y de arrostrar lo imposible, y de soportar lo insoportable. Se desvanece la frustración, y llega la victoria.
(iii) El Espíritu de Dios se conecta con la obra de la creación. Fue el Espíritu de Dios Quien, moviéndose sobre las aguas, volvió el caos un cosmos, cambió el desorden en orden, e hizo el mundo de las nieblas increadas. El Espíritu de Dios puede re-crearnos a nosotros. Cuando el Espíritu de Dios penetra en una persona, el desorden de la naturaleza humana se convierte en el orden de Dios; nuestras vidas embarulladas, desordenadas, descontroladas, las introduce el Espíritu en la armonía de Dios.
(iv) Los judíos atribuían al Espíritu algunas funciones especiales. El Espíritu traía la verdad de Dios a las personas. Todo nuevo descubrimiento en cualquier reino del pensamiento es un don del Espíritu. El Espíritu penetra en la mente, y convierte las suposiciones humanas en certeza divina, y cambia la ignorancia humana en conocimiento divino.
(v) El Espíritu capacita alas personas a reconocer la verdad de Dios cuando la ven. Cuando el Espíritu entra en nuestro corazón, nos abre los ojos. Quita los prejuicios que antes nos tenían ciegos. Elimina la propia voluntad que nos tenía en la oscuridad. El Espíritu capacita a la persona para ver.
Tales son los dones del Espíritu como los vio Juan, y tales los que traería el Que había de venir.
EL MENSAJE DE JUAN:
PROMESA Y AMENAZA
Mateo 3:7-12 (continuación)
Hay una palabra y una imagen en el mensaje de Juan que combinan la promesa y la amenaza.
Juan dice que el Bautismo del Que había de venir sería de fuego. En esto del Bautismo de fuego hay tres ideas.
(i) Está la idea de la iluminación. El destello de una llamarada lanza una luz en medio de la noche e ilumina los rincones oscuros. La llama del faro guía al marino al puerto y al viajero a su destino. En el fuego hay luz y guía. Jesús es la luz del faro que guía a la humanidad a la verdad y la dirige a su hogar en Dios.
(ii) Está la idea del calor. Un hombre eminente fue descrito como uno que encendía la chimenea en las habitaciones frías. Cuando llega Jesús a la vida de una persona, enciende su corazón con el calor del amor hacia Dios y hacia sus semejantes. El Cristianismo es la religión del corazón ardiente.
(iii) Está la idea de la purificación. En este sentido, la purificación conlleva destrucción, porque la llama purificadora destruye todo lo falso y deja lo auténtico. La llama templa y fortalece y purifica el metal. Cuando Cristo llega a la vida de una persona, la purga de toda la escoria del mal. Algunas veces tiene que suceder mediante experiencias dolorosas; pero, si creemos que en todas las experiencias de la vida Dios coopera con todas las cosas para nuestro bien, saldremos de ellas con un carácter limpio y purificado de forma que, puros de corazón, podamos ver a Dios.
Así pues, la palabra fuego contiene la iluminación, el calor y la purificación que trae consigo la venida de Jesucristo a nuestro corazón.
Pero hay también una imagen que contiene una promesa y una amenaza: la imagen de la era de la trilla. El bieldo era un palo largo que acababa en un transversal con cuatro puntas de madera que se usaba, como hasta hace muy poco en España, para aventar el cereal después de la trilla, lanzándolo al aire de manera que el grano fuera cayendo en un montón mientras que la brisa se llevaba más lejos la paja. Después, el grano se recogía y almacenaba, y la paja se usaba como yesca para encender, cualquier fuego, como el del horno.
La venida de Cristo implica por necesidad separación. Las personas pueden, o aceptarle, o rechazarle. Cuando se encuentran frente a frente con Él, se enfrentan con una elección que no se puede evitar ni posponer indefinidamente. Están por o contra El. Y es precisamente esa elección lo que determina el destino. La separación se hace por la reacción ante Jesucristo.
En el Cristianismo no hay manera de evitar la decisión eterna. En el verde prado de Bedford, Juan Bunyan oyó la voz que le levantó de repente y le dejó mirando a la eternidad: «¿Dejarás tus pecados e irás al Cielo, o seguirás con tus pecados e irás al infierno?» En último análisis esa es la elección de la que nadie se puede evadir.
EL MENSAJE DE JUAN: LA DEMANDA
Mateo 3:7-12 (continuación)
En la predicación de Juan había una demanda básica: «¡Arrepentíos!» (Mat 3:2 ). Esa fue también la demanda básica del mismo Jesús, Que inició Su ministerio proclamando: &quot;¡Arrepentíos y creed la Buena Noticia!» (Mar 1:15 ). Haremos bien en tratar de entender lo que quiere decir esta demanda básica del Rey y de Su heraldo.
Hay que advertir que tanto Jesús como Juan usan la palabra arrepentíos sin explicar su significado. La usan con la seguridad de que los oyentes la conocen y entienden.
Veamos cuál era la doctrina judía acerca del arrepentimiento.
Para los judíos, el arrepentimiento era algo esencial en toda fe religiosa y en toda relación con Dios. G. F. Moore escribe: &quot;El arrepentimiento es la sola, pero inexorable, condición para recibir el perdón de Dios y ser restaurados a Su favor, y el perdón y el favor divinos nunca se le niegan al que está genuinamente arrepentido.» Y también escribe: «Que Dios remite plena y gratuitamente los pecados del penitente es una doctrina cardinal del judaísmo.» Los rabinos decían: «Grande es el arrepentimiento, porque trae sanidad al mundo. Grande es el arrepentimiento, porque alcanza al trono de la gloria.» C. G. Montefiori escribió: &quot;El arrepentimiento es el gran nexo mediatorial entre Dios y el hombre.»
La Ley fue creada dos mil años después de la Creación; pero los rabinos enseñaban que el arrepentimiento era una de las seis cosas que fueron creadas antes que la Ley; las seis eran: el arrepentimiento, el paraíso, el infierno, el glorioso trono de Dios, el templo celestial y el nombre del Mesías. «Uno -puede disparar una flecha a unos pocos estadios, pero el arrepentimiento alcanza hasta el trono de Dios.»
Hay un famoso pasaje rabínico que coloca el arrepentimiento por delante de todo lo demás: &quot;¿Quién es como Dios un maestro de pecadores que los conduce al arrepentimiento?» Recorriendo las distintas partes del Antiguo Testamento, le preguntaron primero a la Sabiduría: &quot;¿Cuál será el castigo de los pecadores?&quot; La Sabiduría contestó: &quot;El mal persigue a los pecadores&quot; (Pro 13:21 ). Entonces le preguntaron a la Profecía; y esta contestó: &quot;El alma que peque esa morirá&quot; (Eze 18:4 ). Después le preguntaron a la Ley, que contestó: &quot;Que ofrezca un sacrificio! (Lev 1:4 ). Por último Le preguntaron directamente a Dios, y Él contestó: &quot;Que se arrepienta, y obtendrá la expiación. Hijos Míos, ¿qué es lo que Yo os pido? Buscadme y viviréis (Amo 5:4 ). &quot;» Así es que, para los judíos, la única puerta de acceso a Dios es la del arrepentimiento.
La palabra hebrea que se usa corrientemente para el arrepentimiento es teshúbá, que es el nombre de la raíz shúb que quiere decir volver. Arrepentirse es volverle la espalda al pecado y volverse hacia Dios..
G. F. Moore escribe: «El sentido primario transparente del arrepentimiento en el judaísmo es siempre un cambio de actitud del hombre hacia Dios; y, en la conducta de la vida, una reforma religiosa y moral del pueblo y del individuo.» C. G. Montefiore escribe: «Para los rabinos, la esencia del arrepentimiento radicaba en un total cambio de mentalidad tal que conducía a un cambio de vida y de conducta.» El cordobés Maimónides, la mayor autoridad judía de la Edad Media, define así el arrepentimiento: «¿Qué es el arrepentimiento? Es que el pecador abandona su pecado y lo arroja de sus pensamientos y decide totalmente en su mente no cometerlo otra vez. Como está escrito: «Deje el impío su camino, y el hombre inicuo sus pensamientos» (Isa 55:7 ). &quot;
G. F. Moore señala muy interesante y certeramente que, con la única excepción de las dos palabras entre paréntesis, la definición del arrepentimiento de la Confesión de Westminster sería totalmente aceptable para un judío: «El arrepentimiento para vida es una gracia salvadora por la cual el pecador, movido por un sincero sentimiento de pecado, y aprehensión de la misericordia de Dios (en Cristo), se vuelve de veras, con dolor y aborrecimiento de su pecado, se vuelve de él a Dios, con pleno propósito y esfuerzo de nueva obediencia.» Una y otra vez la Biblia habla de este volver la espalda al pecado, y este volverse hacia Dios. Ezequiel lo expresa diciendo: «Vivo Yo, dice el Señor Dios, que no quiero la muerte del impío, sino que se vuelva el impío de su camino y que viva. ¡Volveos, volveos de vuestros malos caminos! ¿Por qué habéis de morir, casa de Israel?» (Eze 33:11 ). Jeremías lo expresa de la siguiente manera: «Conviérteme, y seré convertido, porque Tú eres el Señor mi Dios» (Jer 31:18 ). Y Oseas dice: &quot;¡Vuelve, Israel, al Señor tu Dios...! Llevad con vosotros palabras de súplica, volved al Señor» (Ose 14:1 s).
En todo esto se ve claramente que, en el judaísmo, el arrepentimiento incluye una demanda ética. Es un volverse del mal hacia Dios, con un cambio correspondiente de conducta. Juan estaba claramente enmarcado en la tradición de su pueblo cuando demandaba que sus oyentes produjeran frutos dignos del arrepentimiento. Hay una hermosa oración sinagoga que dice: «Haznos volver, oh Padre, a Tu Ley; acércanos, oh Rey, a Tu servicio; devuélvenos a Tu presencia en perfecto arrepentimiento. Bendito seas Tú, oh Señor, que Te deleitas en el arrepentimiento.» Pero ese arrepentimiento había de mostrarse en un verdadero cambio de vida.
Un rabino, comentando Jon 3:10 , escribió: «Hermanos, no se dice de los ninivitas que Dios vio su cilicio y su ayuno, sino que Dios vio sus obras, que se volvieron de su mal camino.&quot; Los rabinos decían: «No seáis como los necios, que, cuando pecan, ofrecen un sacrificio pero no se arrepienten. Si uno dice: &quot;Pecaré y me arrepentiré, pecaré y me arrepentiré,&quot; no se le permite arrepentirse.» Hay una lista de cinco pecados imperdonables que incluye: «Los que pecan para arrepentirse, y los que se arrepienten mucho pero siempre vuelven a pecar.&quot; Decían: &quot; Si uno tiene una cosa inmunda en las manos, aunque se las lave en todos los mares del mundo nunca será limpio; pero si arroja la cosa inmunda, le bastará con un poco de agua.&quot; Los maestros judíos hablaban de lo que llamaban «las nueve normas del arrepentimiento,» las nueve cosas necesarias para que un arrepentimiento lo sea de verdad. Las encontraron en la serie de mandamientos de Isa 1:16 : &quot; Lavaos y limpiaos; quitad la iniquidad de vuestras obras de delante de Mis ojos, dejad de hacer lo malo, aprended a hacer el bien, buscad el derecho, socorred al agraviado, haced justicia al huérfano, amparad a la viuda.» Ben Sirá escribe en el Eclesiástico: &quot; No digáis: Pequé, y ¿qué fatiga me ha venido? Porque el Señor es paciente; no te dejará. Del perdón del pecado no te asegures del todo, para añadir pecados a pecados. Y no digas: Grande es Su misericordia; Él me perdonará la multitud de mis pecados. Porque así la ira como la misericordia vendrá de Él apresuradamente; y Su enojo descansará sobre los pecadores. No tardes de volverte al Señor, ni lo dilates de día en día» (Eclesiástico 5:4-8, B.O.). Y en otro lugar: &quot; El que se lava por haber tocado un muerto, y otra vez lo toca, ¿de qué le sirve su lavatorio? Así el hombre que ayuna por sus pecados, y va otra vez a cometer los mismos, ¿quién oirá sus oraciones? ¿O de qué le sirvió su afligirse? (Eclesiástico 34:29-30, B.O.; otras biblias, 34:25-26).
Los judíos mantenían que el verdadero arrepentimiento se manifiesta, no en un mero dolor sentimental, sino en un verdadero cambio de vida -y los cristianos, lo mismo. Los judíos mantenían que el verdadero arrepentimiento produce frutos que demuestran su autenticidad -y también los cristianos.
Pero los judíos tenían todavía más cosas que decir acerca del arrepentimiento, y debemos pasar a considerarlas.
EL MENSAJE DE JUAN: LA DEMANDA
Mateo 3:7-12 (conclusión)
Hay una nota casi aterradora en la demanda ética de la idea judía del arrepentimiento, pero hay también en ella otras cosas consoladoras.
El arrepentimiento siempre es posible. &quot; El arrepentimiento es como el mar decían-: uno se puede bañar en él a cualquier hora.» Puede que haya veces cuando hasta las puertas de la oración están cerradas; pero las puertas del arrepentimiento no se cierran nunca.
El arrepentimiento es totalmente esencial. Hay una historia de una especie de discusión que Abraham tuvo con Dios. Abraham le dijo a Dios: &quot; Tú no puedes agarrar los dos cabos del cordón al mismo tiempo. Si quieres estricta justicia, el mundo no puede subsistir. Si quieres conservar el mundo, la estricta justicia no puede permanecer.» El mundo no puede continuar existiendo sin la misericordia de Dios y la puerta del arrepentimiento. Si no hubiera más que la justicia de Dios, sería el fin de todas las personas y de todas las cosas. Tan esencial es el arrepentimiento que, para hacerlo posible, Dios cancela Sus propias demandas: «Amado es el arrepentimiento ante Dios, porque por causa de él Dios cancela Sus propias palabras.&quot; La amenaza de la destrucción del pecador queda cancelada al aceptar Dios el arrepentimiento del pecador por sus pecados.
El arrepentimiento dura toda la vida. Mientras hay vida, hay posibilidad de arrepentirse. «Dios extiende Su mano bajo las alas de Su carroza celestial para rescatar al arrepentido del poder de la justicia.&quot; Rabí Simeón ben Yojai dijo: &quot; Si un hombre hubiera sido completamente justo todos los días de su vida, y se rebelara al final, destruye todo lo anterior, porque dicho está: &quot; La justicia del justo no lo librará el día que se rebele» (Eze 33:12 ); y si un hombre ha sido un completo malvado todos los días de su vida, y se arrepiente al foral, Dios le recibe; porque dicho está: «Y la impiedad del impío no le será estorbo el día que se vuelva de su impiedad» (Eze 33:12 ). &quot; Muchos dicen- pueden introducirse en el mundo para venir sólo después de años y años; mientras que otros lo ganan en una hora.&quot; Muchos buscan y hallan la misericordia, como decía Cervantes, «puesto ya el pie en el estribo&quot; o, como dice un poeta inglés, &quot; entre el estribo y el suelo,&quot; es decir, en el acto de desmontar.
Tal es la misericordia de Dios que recibirá aun el arrepentimiento tácito. Rabí Eleazar decía: &quot; La costumbre del mundo es que, cuando un hombre ha insultado a su prójimo en público, y pasado el tiempo quiere reconciliarse con él, el otro le dice: &quot;Tú me insultaste públicamente, ¿y ahora quieres que nos reconciliemos en privado los dos solos? ¡Vete a traer a todos los que estaban presentes cuando me insultaste, y me reconciliaré contigo!&quot; Pero Dios no es así. Una persona puede plantarse en el mercado, y blasfemar, mientras el Santo dice: &quot;Arrepiéntete entre nosotros dos, y Yo te recibiré.&quot;» La misericordia de Dios está abierta a la persona que está tan avergonzada de sí misma que no puede mostrarle su vergüenza nada más que a Dios.
Hay mudos que dicen: &quot; Yo perdono, pero no olvido.» Dios no se olvidó de nada, porque es Dios; pero Su misericordia es tal que no solo perdona, sino, aunque parezca increíble, también olvida el pecado del penitente: &quot; ¿Qué Dios hay como Tú, que perdone la maldad y olvide el pecado del remanente de Su heredad?» (Miq 7:18 ). &quot; Yo, Yo soy Quien borro tus rebeliones por amor de Mí mismo, y no Me acordaré de tus pecados» (Isa 43:25 ). «Porque perdonaré la maldad de ellos, y no me acordaré más de su pecado&quot; (Jer 31:34 ).
Pero lo más maravilloso es que Dios sale hasta la mitad del camino, y más aún, para encontrar al penitente: «Volveos lo más que podáis, y Yo os saldré al encuentro hasta ese punto del camino.&quot; Los rabinos, desde su cima más alta, vislumbraron al Padre que, en Su amor, salió corriendo para darle la bienvenida a Su hijo pródigo.
Sin embargo, hasta recordando toda Su misericordia, queda en pie el caso de que, en el verdadero arrepentimiento, es necesario hacer reparación hasta donde se pueda. Los rabinos decían: &quot; Hay que reparar la injuria, y hay que buscar y recibir el perdón. El verdadero penitente es el que tiene la misma oportunidad de cometer el mismo pecado otra vez, en las mismas circunstancias, y no lo comete.&quot; Los rabinos subrayaban una y otra vez la importancia de las relaciones humanas, y de rectificarlas cuando es necesario.
Hay un curioso pasaje rabínico. &quot; El que es bueno con el Cielo y no con sus semejantes, es un mal tsaddiq. (Un tsaddiq es un hombre íntegro). El que es malvado contra el Cielo y contra sus semejantes es un pecador de lo peor. El que es malvado contra el Cielo, pero no contra sus semejantes no es un pecador de lo peor.»
Precisamente porque la reparación es tan necesaria es por lo que el que enseña a otros a pecar es el peor de los pecadores; porque no puede hacer reparación, ya que no puede decir nunca hasta dónde ha llegado su pecado y a cuántos ha llegado a influenciar.
La reparación no es lo único necesario en un verdadero arrepentimiento; también lo es la confesión. Una y otra vez nos encontramos esa demanda en la Biblia. &quot; El hombre o la mujer que cometa cualquiera de los pecados con que los hombres son infieles contra el Señor... confesará su pecado que cometió&quot; (Num 5:6 s). «El que oculta sus pecados no prosperará; pero el que los confiesa y se aparta de ellos alcanzará misericordia&quot; (Pro 28:13 ). &quot; Mi pecado Te declaré, y no encubrí mi iniquidad. Dije: &quot;Confesaré mis rebeliones al Señor&quot; y Tú perdonaste la maldad de mi pecado» (Salmo 32: S). Es la persona que dice que es inocente, y que se niega a admitir que ha pecado, la que es condenada (Jer 2:35 ). Maimónides propone la fórmula que se puede usar para confesar el pecado: &quot; Oh Dios, he pecado, he obrado iniquidad, he transgredido delante de Ti, y he hecho esto y esto. Estoy apenado y avergonzado de mi obra, y no la haré nunca más.» El verdadero arrepentimiento necesita la humildad de admitir y confesar el pecado.
No hay ningún caso desesperado para el arrepentimiento, ni ninguna persona a la que le resulte imposible arrepentirse. Los rabinos decían: «Que nadie diga: «Como he pecado, no tengo remedio.&quot; Que confíe en Dios y se arrepienta, y Dios le recibirá.» El ejemplo clásico de una aparentemente imposible reforma fue el caso de Manasés: dio culto a los baales, introdujo dioses extraños en Jerusalén, y hasta sacrificó niños a Moloc en el valle de Hinnom. Luego fue llevado cautivo a Asiria donde, encadenado, se humilló al Dios de sus padres, oró y fue atendido y volvió a Jerusalén. «Entonces reconoció Manasés que el Señor es Dios&quot; (2Cr 33:13 ). Algunas veces requiere la amenaza de Dios y Su disciplina el hacerlo, pero nadie está fuera del poder de Dios para recuperarle.
Hay una última creencia judía en relación con el arrepentimiento, y es la que debe de haber estado en la mente de Juan. Algunos, a lo menos, de los maestros judíos enseñaban que si Israel se pudiera arrepentir perfectamente aunque solo fuera por un día, vendría el Mesías. Era solo la dureza de corazón de la gente lo que retrasaba la venida del Redentor de Dios al mundo.
El arrepentimiento era el centro mismo de la fe judía, como lo es también de la fe cristiana; porque el arrepentimiento es cambiar de sentido en la vida volviéndonos del pecado hacia Dios, y hacia la vida que Dios quiere que vivamos.</p>
<br/>
<p class="text-justify">JESÚS Y SU BAUTISMO
Mateo 3:13-17
Entonces Jesús vino desde Galilea al Jordán, a Juan, para que Le bautizara. Pero Juan intentó impedírselo.
-Soy yo -Le dijo- el que necesita ser bautizado por Ti, ¿y Tú vienes a mí?
Déjalo por ahora -le contestó Jesús-, porque esta es la manera en que nos corresponde cumplir toda justicia.
Entonces dejó que Jesús fuera bautizado.
Inmediatamente después de ser bautizado, salía Jesús del agua, y en ese mismo momento se abrieron los cielos a Juan, y vio al Espíritu de Dios descender como una paloma y posarse sobre Jesús. Y, fijaos, llegó una voz desde el Cielo que decía:
-Este es Mi Hijo, el Amado, en Quien encuentro plena satisfacción.
Cuando vino Jesús a Juan para que Le bautizara, Juan se quedó perplejo y no quería bautizarle. Juan estaba convencido de que era él mismo el que necesitaba lo que Jesús tuviera para él, y no Jesús el Que necesitara nada de Juan.
Desde que se empezó a pensar en el relato evangélico, el bautismo de Jesús ha resultado difícil de entender. El bautismo de Juan era una llamada al arrepentimiento, con el fin de obtener el perdón de los pecados; pero, si Jesús era el Que creemos que era, no tenía necesidad de arrepentirse, ni necesitaba por tanto que Dios Le perdonara. El bautismo de Juan era para los pecadores que reconocieran su pecado, y por tanto no parecía aplicable a Jesús en absoluto.
Un escritor del principio de la Iglesia sugirió que Jesús vino a bautizarse solamente para complacer a Su Madre y a Sus hermanos, y que fue la insistencia de ellos lo que casi Le obligó a someterse a aquello. El Evangelio según los Hebreos, que fue uno de los evangelios que no fueron incluidos en el Nuevo Testamento, tiene un pasaje sobre esto: &quot; He aquí que la Madre del Señor y Sus hermanos Le dijeron: &quot;Juan el Bautista está bautizando para la remisión de los pecados; vayamos a ser bautizados por él.&quot; Pero Él les dijo: &quot;¿Qué pecado he cometido Yo para tener que ir a que Me bautice? Salvo, tal vez, que esto que acabo de decir sea ignorancia.&quot;»
Desde los primeros tiempos de la Iglesia, los pensadores estaban perplejos con el hecho de que Jesús Se sometiera al bautismo. Pero había razones, y buenas razones, para que lo hiciera.
(i) Jesús había estado esperando treinta años en Nazaret, cumpliendo fielmente los deberes normales del hogar y del taller de carpintería. Todo ese tiempo sabía que había un mundo que Le estaba esperando. Todo ese tiempo fue haciéndose más y más consciente de Su expectativa. El éxito de cualquier empresa viene determinado por la sabiduría con que se elige el momento de embarcarse en ella. Jesús tiene que haber estado esperando que llegara Su momento, que sonara Su hora. Y cuando surgió Juan, Jesús reconoció que Su hora había llegado.
(ii) ¿Por qué había de ser así? Había una razón muy sencilla y vital. Es un hecho que nunca en toda la historia antes de este hecha había tenido que bautizarse ningún judío. Los judíos conocían y usaban el bautismo, pero solamente para los prosélitos que llegaban al judaísmo de otra o de ninguna religión. Era natural que fueran bautizados los prosélitos, que estaban manchados por el pecado y contaminados; pero ningún judío había concebido jamás que él, un miembro del pueblo elegido, un hijo de Abraham, seguro de la salvación de Dios, pudiera nunca necesitar ser bautizado. El bautismo era para los pecadores, y ningún judío se consideraba pecador y excluido de Dios. Entonces, por primera vez en toda su historia nacional, los judíos reconocían su propio pecado y su perentoria necesidad de Dios. Nunca antes había habido un movimiento así de arrepentimiento y búsqueda de Dios.
Ese era el mismísimo momento que Jesús había estado esperando. El pueblo era consciente de su pecado y de su necesidad de Dios como nunca antes. Esta era Su oportunidad; y en Su bautismo Se identificó con todas las personas que había venido a salvar, en el momento del nuevo despertar de su conciencia y de su búsqueda de Dios.
La voz que oyó Jesús en Su bautismo es de suprema importancia. «Este es Mi Hijo amado -dijo-, en Quien encuentro plena satisfacción.» La frase está formada por dos citas: «Este es Mi Hijo amado» es una cita del Sal 2:7 . Todos los judíos creían que ese Salmo era una descripción del Mesías, el poderoso Rey Que había de venir de Dios. &quot; En Quien Mi alma tiene contentamiento» se encuentra en Isa 42:1 , que es una descripción del Siervo Doliente, una descripción que culmina en Isaías 53.
Así es que, en Su bautismo, Jesús recibió dos confirmaciones: la seguridad de que Él era sin duda el Escogido de Dios, y la seguridad de que el camino que tenía delante conducía a la Cruz. En ese momento supo Jesús sin la menor duda que Su trono había de ser la Cruz. En ese momento supo que estaba destinado a ser conquistador, pero que Su conquista habría de lograrse con la sola arma del poder del amor doliente. En ese momento se Le pusieron delante tanto Su misión como la única manera en que habría de cumplirla.
EL TIEMPO DE LA PRUEBA
Mateo desarrolla la vida de Jesús paso a paso. Empieza mostrándonos como nació Jesús en este mundo. Sigue mostrándonos, al menos por implicación, que Jesús tuvo que cumplir fielmente Sus obligaciones para con Su hogar antes de cumplir Su deber para con el mundo, que Jesús tenía que mostrarse fiel en las pequeñas tareas antes de que Dios Le confiara la tarea más importante del mundo y de la Historia.
Ahora pasa a mostrarnos cómo, al surgir en la escena Juan el Bautista, Jesús supo que había sonado Su hora y Le había llegado el momento de asumir Su obra. Juan nos muestra a Jesús identificándose con un pueblo que buscaba a Dios como nunca antes. En ese momento nos muestra a Jesús dándose cuenta de que Él era sin duda el Escogido de Dios, pero que el camino de la victoria había de pasar por la Cruz.
Cuando una persona tiene una visión, su problema inmediato es cómo hacerla realidad; tiene que encontrar la manera de convertir el sueño en un hecho. Ese era el problema con que se enfrentaba Jesús. Había venido a conducir a la humanidad de vuelta a Dios. ¿Cómo habría de hacerlo? ¿Qué método tendría que adoptar: el del conquistador poderoso, o el del amor doliente y sacrificial? Ese era el problema con que se enfrentaba Jesús en Sus tentaciones. Se Le había encomendado una labor. ¿Qué método habría de escoger para cumplir la tarea que Dios Le había encargado llevar a cabo?
###</p>
<br/>




</div>
