<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 1</h2>
<p class="text-justify">EL LINAJE DEL REY
Mateo 1:1-17
Libro de la genealogía de Jesucristo, hijo de David, hijo de Abraham:
Abraham engendró a Isaac, Isaac a Jacob, y Jacob a Judá y a sus hermanos. Judá engendró de Tamar a Fares y a Zara, Fares a Esrom, y Esrom a Aram. Aram engendró a Aminadab, Aminadab a Naasón, y Naasón a Salmón. Salmón engendró de Rahab a Booz, Booz engendró de Rut a Obed, y Obed a Isaí. Isaí engendró al rey David.
El rey David engendró de la que fue mujer de Urías a Salomón. Salomón engendró a Roboam, Roboam a Abías, y Abías a Asa. Asa engendró a Josafat, Josafat a Joram, y Joram a Uzías. Uzías engendró a Jotam, Jotam a Acaz, y Acaz a Ezequías. Ezequías engendró a Manasés, Manasés a Amón, y Amón a Josías. Josías engendró a Jeconías y a sus hermanos en el tiempo de la deportación a Babilonia.
Después de la deportación a Babilonia, Jeconías engendró a Salatiel, y Salatiel a Zorobabel. Zorobabel engendró a Abiud, Abiud a Eliaquim, y Eliaquim a Azor. Azor engendró a Sadoc, Sadoc a Aquim y Aquim a Eliud. Eliud engendró a Eleazar, Eleazar a Matán, Matán a Jacob. Jacob engendró a José, marido de María, de la cual nació Jesús, llamado el Cristo.
De manera que todas las generaciones de Abraham hasta David son catorce; desde David hasta la deportación a Babilonia, catorce; y desde la deportación a Babilonia hasta Cristo, catorce.
Al lector moderno le parecerá que Mateo escogió una manera muy extraña de empezar su evangelio, y le alucinará tener que vadear una larga lista de nombres propios justamente al principio de todo. Pero, para un judío, esto era lo más natural y lo más interesante; y, desde luego, la manera más esencial de empezar la historia de la vida de cualquier persona.
Los judíos tenían un interés tremendo en las genealogías. Mateo llama a esta parte el libro de la generación (biblos guenéseós) de Jesucristo. Esa era una frase corriente entre los judíos; y quería decir la partida del linaje de una persona, con unas pocas frases explicativas donde fueran necesarias. En el Antiguo Testamento nos encontramos frecuentemente con listas de generaciones de personas famosas (Gen 5:1 ; Gen 10:1 ; Gen 11:10 ; Gen 11:27 ). Cuando Josefo, el gran historiador judío, escribió su propia autobiografía, empezó por su propio pedigrí que, nos dice, encontró en los registros públicos.
La razón de este interés en los pedigrís era que los judíos daban la mayor importancia a la pureza de linaje. Si hubiera en alguna persona la más ligera mezcla de sangre extranjera, perdería su derecho de ciudadanía como judía y como miembro del pueblo de Dios. Un sacerdote, por ejemplo, estaba obligado a presentar el certificado ininterrumpido de su pedigrí remontándose hasta Aarón; y, si se casaba, su mujer tenía que presentar su pedigrí por lo menos de las últimas cinco generaciones. Cuando Esdras estaba reorganizando el culto de Dios, después que el pueblo volvió del exilio, y estaba instalando el sacerdocio en su ministerio, los hijos de Habaía, los de Cos y los de Barzilai fueron excluidos del sacerdocio y considerados contaminados porque «buscaron su registro genealógico pero no lo hallaron» (Esd 2:62 ).
Estos registros genealógicos los guardaba el sanedrín. A Herodes el Grande siempre le despreciaron los purasangres judíos porque era medio edomita; y podemos advertir la importancia que el mismo Herodes concedía a estas genealogías por el hecho de que hizo destruir todos los registros oficiales para que nadie pudiera demostrar un pedigrí más puro que el suyo. Este puede que nos parezca un pasaje sin ninguna importancia, pero para un judío contiene un asunto de la máxima importancia: el que la genealogía de Jesús se pudiera trazar hasta Abraham.
Además ha de notarse que esta genealogía está dispuesta con sumo cuidado. Comprende tres grupos de catorce nombres cada uno. Es, de hecho, lo que técnicamente llamaríamos mnemotécnica; es decir, algo que se coloca de manera que se pueda memorizar fácilmente. Debemos recordar siempre que los evangelios se escribieron siglos antes de que existiera tal cosa como libros impresos. Muy pocas personas serían capaces de poseer ejemplares de ellos; así que, si querían poseerlos, los tenían que memorizar. Esta genealogía, por tanto, está organizada de tal manera que sea fácil de memorizar. Su invalidad es demostrar que Jesús fue el Hijo de David, y está dispuesta para que resulte fácil conservarla en la memoria.
LAS TRES ETAPAS
Mateo 1:1-17 (continuación)
Hay algo representativo en la manera como está organizada esta genealogía: hay en ella tres secciones, que corresponden a las tres grandes etapas de la historia de Israel.
La primera sección incluye la historia hasta David. David fue el hombre que fraguó a Israel como nación, e hizo de los judíos un poder en el mundo. La primera sección sigue la historia hasta el surgimiento del más grande rey de Israel.
La segunda sección continúa la historia hasta la cautividad de Babilonia. Es la sección que nos cuenta la vergüenza, y la tragedia, y el desastre de la nación.
La tercera sección continúa la historia hasta Jesucristo. Jesucristo fue la Persona Que liberó a la humanidad de la esclavitud, Que la rescató del desastre, y en Quien la tragedia se transformó en triunfo.
Estas tres secciones representan tres etapas de la historia espiritual de la humanidad.
(i) El hombre fue creado para la grandeza. «Y creó Dios al hombre a Su imagen, a imagen de Dios lo creó» (Gen 1:27 ). Dios dijo «Hagamos al hombre a Nuestra imagen, conforme a Nuestra semejanza» (Gen 1:26 ). Adán -el primer hombre y la raza humana- fue creado a imagen de Dios. El sueño de Dios para el hombre era un sueño de grandeza. El hombre estaba diseñado para la comunión con Dios. Fue creado para nada menos que vivir en intimidad con Dios. Como lo veía el pensador latino Cicerón: &quot;La única diferencia entre el hombre y Dios es en cuanto al tiempo.» Adán nació esencialmente para ser rey.
(ii) El hombre perdió su grandeza. En vez de ser siervo de Dios, se convirtió en esclavo del pecado. Como dijo G. K. ChEsterton: «Entre otras cosas tal vez, lo que es seguro es que el hombre no es lo que se supuso que fuera.» Usó su libre albedrío para desafiar y desobedecer a Dios más bien que para entrar en una relación de amistad y comunión con Él. Culpablemente frustró el designio y el plan de Dios en Su creación.
(iii) El hombre puede recuperar su grandeza. Aun entonces, Dios no abandonó al hombre a su destino frustrado, Dios no permitió que el hombre fuera destruido por su propia necedad. No dejó que la historia acabara en tragedia. A este mundo Dios mandó a Su Hijo Jesucristo para que rescatara al hombre de la ciénaga del pecado en que se había perdido, y le liberara de las cadenas del pecado. en las que él mismo se había aherrojado, para que por medio de Él el hombre pudiera recuperar la comunión con Dios que había perdido.
En su genealogía Mateo nos muestra la realeza original; la tragedia de la libertad perdida; la gloria de la libertad restaurada. Y esa, por la misericordia de Dios, es la historia de la humanidad y de cada persona humana.
REALIZACIÓN DE LOS SUEÑOS HUMANOS
Mateo 1:1-17 (continuación)
Este pasaje hace hincapié en dos cosas especiales acerca de Jesús:
(i) Subraya el hecho de que era el Hijo de David. Era, desde luego y principalmente, para demostrar este hecho para lo que se compuso la genealogía. El Nuevo Testamento lo subraya una y otra vez.
Pedro lo afirmó en el primer sermón cristiano del que tenemos referencia, el del día de Pentecostés (Hec 2:29-36 ). Pablo dice que Jesucristo fue descendiente de David según la carne (Rom 1:3 ). El autor de las epístolas pastorales nos exhorta a recordar que Jesucristo, descendiente de David, resucitó de entre los muertos (2 Timoteo 2:8 ). El autor del Apocalipsis oye decir al Cristo resucitado: «Yo soy la raíz y el linaje de David» (Apocalipsis 22:16).
Repetidamente se Le llama así a Jesús en la historia evangélica. Después de la curación del hombre ciego y mudo, la gente exclamó: &quot;¿Será Éste aquel Hijo de David?» (Mat 12:23 ). La mujer de Tiro y Sidón que le pedía a Jesús que ayudara a su hija le llamó «Hijo de David» (Mat 15:22 ). Los dos ciegos que clamaron a Jesús cuando pasaba Le llamaron «Señor, Hijo de David» (Mat 20:30 s). Fue como Hijo de David como las multitudes Le saludaron y aclamaron cuando entró en Jerusalén por última vez (Mat 21:9; Mat 21:15 ). Aquí hay algo sumamente significativo. Está claro que fue la multitud, la gente corriente, la que llamaba a Jesús Hijo de David. Los judíos eran un pueblo a la expectativa. Nunca olvidaban, y nunca podían olvidar, que eran el pueblo escogido de Dios. Aunque su historia era una larga serie de desastres, aunque entonces eran un pueblo sometido, nunca olvidaron su destino. Y era el sueño de la gente del pueblo que algún día vendría a este mundo un descendiente de David que los conduciría a la gloria que ellos creían que les pertenecía por derecho.
Es decir: Jesús es la respuesta a los sueños humanos. Es verdad que muchas veces no se ve así. Se ve la respuesta a los sueños en el poder, en la riqueza, en la abundancia material, y en la realización de las ambiciones que se. han acariciado. Pero si han de cumplirse los sueños de paz y .amor, de grandeza y satisfacción, solamente podrá ser en Jesucristo.
Jesucristo y la vida que ofrece son la respuesta a los sueños humanos. En la vieja historia de José :hay un texto que sobrepasa la historia misma. Cuando José estaba en la cárcel, el copero y el panadero principales del Faraón estaban presos con él. Tuvieron cada uno un sueño que los dejó turbados y les hizo clamar en confusión: «Hemos tenido sueños, pero no hay nadie que nos los interprete» (Gen 40:8 ). Porque el hombre es hombre, porque es una criatura de la eternidad, el hombre está siempre alucinado por su sueño; y la única manera de que pueda realizarse está en Jesucristo.
(ii) Este pasaje también hace hincapié en que Jesús es el cumplimiento de la profecía. En Él se hace realidad el mensaje de los profetas. En nuestro tiempo tomamos bastante a la ligera la profecía. No tenemos interés la mayor parte de nosotros en buscar los dichos del Antiguo Testamento que se cumplen en el Nuevo. Pero es verdad que la profecía, contiene esta gran verdad eterna: Que en este universo hay un propósito y un diseño, y que Dios quiere y se propone que sucedan ciertas cosas.
J. H. Withers cita un dicho de la obra de Gerald Healy El extranjero negro. La escena tiene lugar en Irlanda, en los terribles días de hambre de mediados del siglo diecinueve. Por falta de nada mejor que hacer, y por carecer de ninguna otra solución, el gobierno había enviado hombres que hicieran carreteras sin ningún sentido y que no conducían a ninguna parte. Michael lo descubre y vuelve a casa un día diciéndole a su padre con angustiada sorpresa: «Están haciendo carreteras que no van a ninguna parte.»
Si creemos en la profecía, eso es lo que no podemos decir nunca. La Historia no puede nunca ser una carretera que no lleva a ninguna parte. Puede que no usemos la profecía de la misma manera que nuestros padres; pero, tras el hecho de la profecía descansa el eterno hecho de que la vida y el mundo no siguen un camino que no lleva a ninguna parte, sino el camino cuya meta es Dios.
NO JUSTOS, SINO PECADORES
Mateo 1:1-17 (conclusión)
Con mucho lo más maravilloso de este pedigrí son los nombres de mujeres que aparecen en él.
No es normal encontrar nombres de mujeres en las genealogías judías. La mujer no tenía derechos legales; se la consideraba, no como una persona, sino como una cosa. No era más que una posesión de su padre o de su marido, quienes podían hacer con ella lo que quisieran. En la fórmula tradicional de oración matutina, el judío le da gracias a Dios por no haberle hecho ni un gentil, ni un esclavo, ni una mujer. La misma existencia de estos nombres en cualquier pedigrí es ya un fenómeno de lo más sorprendente y extraordinario.
Pero cuando nos fijamos en quiénes eran estas mujeres y en lo que hicieron, la cosa se vuelve todavía más alucinante. Rajab -o como se la llama en el Antiguo Testamento, Rahab, era una prostituta de Jericó (Jos 2:1-7 ). Rut no era judía, sino moabita (Rut 1:4 ), ¿y es que no establecía la ley misma que: &quot;No entrará el amonita ni el moabita en la congregación del Señor, ni siquiera en su décima generación; no entrarán nunca en la congregación del Señor?» (Deu 23:3 )? Rut pertenecía a un pueblo ajeno y aborrecido. Tamar fue una seductora y adúltera (Génesis 38). Betsabé, la madre de Salomón era la mujer de Urías a la que David sedujo con una crueldad imperdonable (2 Samuel 11 y 12). Si Mateo hubiera escarbado las páginas del Antiguo Testamento buscando candidatas improbables no podría haber descubierto cuatro antepasadas de Jesucristo más increíbles. Pero sin duda hay algo encantador en esto. Aquí; justamente al principio, Mateo nos da una muestra del Evangelio de Dios en Jesucristo, porque nos muestra las barreras que se vienen abajo.
(i) Desaparece la barrera entre judío y gentil. Rahab, la mujer de Jericó, y Rut, la mujer de Moab, hallan su sitio en el pedigrí de Jesucristo. Ya está aquí la gran verdad de que en Cristo no hay judío ni griego. Aquí, en el mismo principio, encontramos el universalismo del Evangelio y del amor de Dios.
(ii) Desaparece la barrera entre varón y mujer. En ningún pedigrí ordinario se encontraría el nombre de ninguna mujer; pero sí en el de Jesús. El viejo desprecio ha desaparecido; y varones y mujeres se encuentran en el mismo nivel en el amor de Dios y son igualmente importantes en Sus propósitos.
(iii) Desaparece la barrera entre santo y pecador. Dios se las arregla para usar para Su propósito a los que han sido grandes pecadores. «Yo he venido -dijo Jesús-, no para llamar a los justos, sino a los pecadores (Mat 9:13 ).
Aquí, al principio mismo del evangelio, se nos da un adelanto de la amplitud del amor de Dios que lo abarca todo. Dios puede encontrar servidores entre aquellos que los respetables ortodoxos evitarían con horror.</p>
<br/>
<p class="text-justify">LA LLEGADA DEL SALVADOR AL MUNDO
Mateo 1:18-25
El nacimiento de Jesucristo tuvo lugar de la siguiente manera.
María, Su Madre, era la prometida de José; y, antes que llegasen a ser marido y mujer, se supo que ella estaba embarazada por obra del Espíritu Santo.
Aunque José, su marido, era cumplidor de la Ley, no quiso humillarla públicamente; decidió divorciarse de ella en secreto. Y cuando estaba haciendo los preparativos, fijaos: un ángel del Señor se le apareció en sueños, y le dijo:
José, hijo de David: no dudes en tomar por mujer a María; porque lo de su embarazo procede del Espíritu Santo. Dará a luz un Hijo, y tú le pondrás por nombre Jesús, porque Él es el Que salvará a Su pueblo de sus pecados. Todo esto ha sucedido para que se cumpliera lo que dijo el Señor por medio del profeta: «He aquí que la muchacha concebirá y dará a luz un Hijo, y le llamarás de nombre Emanuel, que significa &quot;Dios está con nosotros. &quot;»
Así es que, cuando José se despertó del sueño, hizo lo que le había mandado el ángel del Señor: tomó a María por mujer, y no la conoció hasta después que ella dio a luz a un niño; y él Le puso por nombre Jesús.
Para nuestra manera occidental de pensar, las relaciones que salen en este pasaje son muy extrañas. En primer lugar, se nos dice que María estaba desposada (Reina-Valera, revisiones anteriores a la del 95) con José; luego hemos traducido que él estaba haciendo los preparativos para divorciarse de ella en secreto; y luego se la llama su mujer o esposa. Pero la relación entre ambos representa el procedimiento judío normal, en el que había tres pasos.
(i) Estaba el compromiso. Este se hacía a menudo cuando la pareja no eran más que niños. Lo hacían corrientemente los padres, o por medio de un casamentero profesional. Y se hacía a menudo sin que los que formaban la pareja se hubieran visto nunca. El matrimonio se consideraba que era un paso demasiado serio para dejarlo a los dictados del corazón humano.
(ii) Estaba el desposorio. Este era lo que podríamos llamar la ratificación del compromiso que ya había contraído la pareja. Hasta este momento, el compromiso que se había establecido por medio de los padres o del casamentero, se podía romper si una de las dos partes no quería continuar con él. Pero una vez que se llegaba al desposorio era absolutamente vinculante. Duraba un año. Durante ese año la pareja se consideraban marido y mujer, aunque todavía no tenían esa relación. El desposorio no se podía dar por concluido de ninguna manera más que por el divorcio. En la ley judía nos encontramos frecuentemente lo que nos parece una frase curiosa. Una chica cuyo prometido había muerto durante el año de los desposorios se llamaba «una virgen que es viuda.» En esta etapa se encontraban José y María. Estaban desposados; y si José quería acabar el desposorio no lo podía hacer más que con el divorcio; y ese año de desposorio a María se la conocía legalmente como su esposa.
(iii) La tercera etapa era el matrimonio propiamente dicho, que tenía lugar al final del año de desposorio.
Si tenemos presentes las costumbres matrimoniales normales de los judíos, entonces la relación que se indica en este pasaje está perfectamente clara.
Así que en esta etapa se le dijo a José que María iba a tener un Niño, que había sido concebido por obra del Espíritu Santo, y que él, José, debería ponerle por nombre Jesús. Jesús es la forma griega del nombre hebreo Josué, que quiere decir Jehová es salvación. Hacía mucho tiempo, el salmista había oído decir a Dios: &quot;El redimirá a Israel de todos sus pecados» (Sal 130:8 ). Y a José se le dijo que el Niño que nacería llegaría a ser el Que salvara al pueblo de Dios de sus pecados. Jesús fue, aún más que el Hombre nacido para ser Rey, el Hombre nacido para ser Salvador. Vino a este mundo no por Su propia cuenta, sino por la de los hombres y su salvación.
NACIDO DEL ESPÍRITU SANTO
Mateo 1:18-25 (continuación)
Este pasaje nos dice que Jesús nació por la acción del Espíritu Santo. Nos habla de lo que llamamos el Nacimiento Virginal. De momento lo único que nos concierne es descubrir lo que quiere decir para nosotros.
Si miramos este pasaje con naturalidad y lo leemos como si fuera la primera vez encontramos que lo que subraya no es tanto que Jesús naciera de una mujer virgen como que el nacimiento de Jesús fue la obra del Espíritu Santo. «Se supo que María estaba embarazada del Espíritu Santo.» «Lo que ella ha concebido es del Espíritu Santo.» Es como si estas frases estuvieran subrayadas o impresas en tipo grande. Eso es lo que Mateo quiere decirnos en este pasaje. Entonces, ¿qué quiere decir que en el nacimiento de Jesús el Espíritu Santo de Dios estuvo especialmente operativo? Dejemos las cuestiones dudosas o debatibles, y concentrémonos en esa gran verdad, como Mateo querría que hiciéramos.
En el pensamiento judío el Espíritu Santo tenía ciertas funciones muy definidas. No podemos traer a este pasaje la idea cristiana del Espíritu Santo en toda su plenitud, porque José no sabría nada de eso. Debemos interpretarlo a la luz de la idea judía del Espíritu Santo, porque esa sería la interpretación que José le daría inevitablemente a este pasaje, porque era la única que conocía.
(i) Según la idea judía, el Espíritu Santo era la Persona Que traía a los hombres la verdad de Dios. Era el Espíritu Santo el Que enseñaba a los profetas lo que habían de decir; era el Espíritu Santo el Que enseñaba a los hombres lo que debían hacer; era el Espíritu Santo Quien a lo largo de edades y generaciones traía la verdad de Dios a la humanidad. Así que Jesús es la única Persona que trae la verdad de Dios a la humanidad.
Para decirlo de otra manera: Jesús es la única Persona que nos puede decir cómo es Dios y lo que Dios quiere que seamos. Solamente en Él podemos ver cómo es Dios y cómo debemos ser nosotros. Antes de que Jesús viniera, la humanidad no tenía más que unas ideas vagas e imprecisas, y a menudo erróneas, acerca de Dios; lo único que podía era suponer y andar a tientas; pero Jesús pudo decir: «El que Me ha visto ha visto al Padre» (Jua 14:9 ). En Jesús vemos el amor, la compasión, la misericordia, el corazón buscador, la pureza de Dios, como no los podemos ver en ningún otro lugar del mundo. Con la venida de Jesús, el tiempo de las suposiciones ha terminado, y ha llegado el de las certezas. Antes de que Jesús viniera no sabíamos realmente lo que era la bondad. Solamente en Jesús podemos ver lo que son la verdadera humanidad, la verdadera bondad, la verdadera obediencia a la voluntad de Dios. Jesús vino al mundo a decirnos la verdad acerca de Dios y acerca de nosotros mismos.
(ii) Los judíos creían que el Espíritu Santo no sólo traía la verdad de Dios a los hombres, sino también capacitaba a los hombres para reconocer esa verdad cuando la vieran. Así es que Jesús nos abre los ojos a la verdad. Los hombres son cegados por su propia ignorancia; son descarriados por sus propios prejuicios; tienen la mente y los ojos oscurecidos por su propio pecado y por sus pasiones. Jesús puede abrir nuestros ojos para que podamos ver la verdad.
En una de las novelas de William J. Locke hay una descripción de una mujer que tenía más dinero del que podía contar, y que había pasado la mitad de su vida visitando los museos de pintura del mundo. Estaba cansada y aburrida. Entonces conoció a un francés que tenía muy poco de las cosas de este mundo, pero que tenía un conocimiento amplio y un amor profundo por la belleza. Fue con ella, y en su compañía las cosas aparecieron totalmente diferentes. &quot;Yo nunca supe cómo eran las cosas -le dijo ella- hasta que tú me enseñaste a mirarlas.»
La vida se convierte en algo totalmente diferente cuando Jesús nos enseña a mirar las cosas. Cuando Jesús viene a nuestro corazón, nos abre los ojos para que veamos las cosas tal como son de veras.
CREACIÓN Y RECREACIÓN
Mateo 1:18-25 (conclusión)
(iii) Especialmente, los judíos conectaban al Espíritu de Dios con la obra de la creación. Fue por medio de Su Espíritu como Dios realizo Su obra creadora. En el principio, el Espíritu de Dios se movía sobre las aguas y el caos llegó a ser un mundo (Gen 1:2 ). «Por la palabra del Señor fueron Hechos los cielos -dijo el salmista-; y todo el ejército de ellos por el aliento de Su boca» (Sal 33:6 ). (Tanto en hebreo, rúaj, como en griego, pneuma, la palabra para aliento y espíritu es la misma). «Envías Tu Espíritu, son creados y renuevas la faz de la tierra» (Sal 104:30 ). &quot;El Espíritu de Dios me hizo -decía Job- y el soplo del Omnipotente me dio vida» (Job 33:4 ).
El Espíritu es el Creador del mundo y el Dador de la vida. Así que en Jesús vino al mundo el poder vivificador y creador de Dios. Ese poder, que convirtió en orden el caos primigenio, ha venido a traer orden a nuestra desordenada vida. Ese poder, que alentó vida donde antes no la había, ha venido a alentar vida en nuestra debilidad y frustración. Podríamos decir realmente que no estamos vivos de veras hasta que Jesús entra en nuestras vidas.
(iv) Los judíos conectaban al Espíritu especialmente, no sólo con la obra de la creación, sino también con la obra de la re-creación. Ezequiel traza un cuadro sombrío del valle de los huesos secos. Pasa luego a contar cómo los huesos secos volvieron a la vida; y entonces oye decir a Dios: &quot;Yo hago entrar espíritu en vosotros y viviréis» (Eze 37:1-14 ). Los rabinos tenían un dicho: «Dios dijo a Israel: &quot;En este mundo Mi Espíritu ha puesto sabiduría en vosotros, pero en el futuro Mi Espíritu os hará vivir de nuevo.&quot;» Cuando los hombres están muertos en pecado y en letargo, es el Espíritu de Dios el Que puede despertarlos a una vida nueva.
Así pues, en Jesús vino a este mundo el poder que puede re-crear la vida. Puede traer otra vez a la vida al alma que está muerta en pecado; puede reavivar otra vez los ideales que han muerto; puede hacer fuerte otra vez la voluntad de la bondad que ha perecido. Puede renovar la vida, cuando las personas han perdido todo lo que la vida representa.
Hay mucho más en este capítulo que el hecho escueto de que Jesucristo nació de una madre virgen. La esencia de la historia de Mateo es que, en el nacimiento de Jesús, el Espíritu de Dios estuvo operativo como nunca antes en este mundo. Es el Espíritu el Que trae a la humanidad la verdad de Dios; el Que capacita a las personas a reconocer esa verdad cuando la ven; el Que fue el Agente de Dios en la creación del mundo; el único Que puede re-crear el alma humana que ha perdido la vida que debería tener.
Jesús nos capacita para ver cómo es Dios y cómo debemos ser nosotros; nos abre los ojos de la mente para que podamos ver la verdad de Dios para nosotros; es el poder creador venido entre los hombres; es el poder re-creador que puede liberar las almas humanas de la muerte del pecado.</p>
<br/>




</div>
