<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 2</h2>
<p class="text-justify">EL LUGAR DEI NACIMIENTO DEL REY
Mateo 2:1-2
Cuando nació Jesús en Belén de Judasa en tiempos del rey Herodes, sucedió que llegaron a Jerusalén unos sabios del Oriente. Y preguntaron:
-¿Dónde está el recién nacido Rey de los judíos? Porque hemos visto aparecer Su estrella, y venimos a rendirle homenaje.
Fue en Belén donde nació Jesús. Belén era un pueblecito a unos ocho kilómetros al Sur de Jerusalén. Antiguamente se había llamado Efrat o Efratá. El nombre completo en hebreo es Bedéjem, que quiere decir casa de pan, y Belén estaba situado en una región fértil, lo que justificaba su nombre. Estaba ubicado sobre unas montañas de caliza gris a más de ochocientos metros sobre el nivel del Marcos Tenía una cima a cada lado y un hondón como una silla de montar entre las dos. Así que, por su posición, Belén parecía un pueblo asentado en un anfiteatro de colinas.
Belén tenía una larga historia. Fue allí donde Jacob enterró a Raquel y erigió un pilar en su memoria junto a la tumba (Gen 48:7 ; Gen 35:20 ). Fue allí donde vivió Rut después de casarse con Booz (Rut 1:22 ), y desde Belén Rut podía ver la tierra de Moab, su antigua patria, al otro lado del valle del Jordán. Pero, sobre todo, Belén fue el hogar y la ciudad de David (1Sa 16:1 ; 1Sa 17:12 ; 1Sa 20:6 ); y era del agua del pozo de Belén de lo que David tenía tanta nostalgia cuando era un fugitivo perseguido por las colinas, lo que motivó una preciosa escena de lealtad y de piedad (2Sa 23:14 s).
En tiempos posteriores leemos que Jeroboam fortificó el pueblo de Belén (2Cr 11:6 ). Pero, en la historia de Israel y en las mentes del pueblo, Belén era supremamente la ciudad de David. Era de la dinastía de David de la que Dios haría venir al gran Libertador de Su pueblo. Como dijo el profeta Miqueas: «Pero tú, Belén Efratá, tan pequeña entre las familias de Judá, de ti ha de salir el que será Señor en Israel; Sus orígenes se remontan al inicio de los tiempos, a los días de la eternidad» (Miq 5:2 ).
Era en Belén, la ciudad de David, donde los judíos esperaban que naciera el mayor Hijo del gran David; era de allí de donde esperaban que viniera al mundo el Ungido de Dios. Y así fue.
La imagen del establo y del pesebre como el lugar del nacimiento de Jesús está grabada indeleblemente en nuestras mentes; pero puede que no sea totalmente correcta. Justino Mártir, uno de los más grandes de los primeros padres, que vivió hacia 150 d.C. y que procedía del distrito cercano a Belén, nos dice que Jesús nació en una cueva cerca de la aldea (Justino Mártir, Diálogo con Trifón 78, 304); y puede que la información de Justino fuera correcta. Las casas de Belén están construidas en la ladera de la montaña de- piedra caliza; y era muy corriente en aquel entonces el tener establos en forma de cuevas en la roca vaciada por debajo de las casas mismas; y muy probablemente fue en un tipo de cueva-establo así donde nació Jesús.
Hasta este día se enseña en Belén una cueva así como el lugar del nacimiento de Jesús, sobre la que se ha construido la Iglesia de la Natividad. Hace mucho tiempo que se enseña esta cueva como el lugar del nacimiento de Jesús. Ya era así en los días del emperador romano Adriano; porque éste, en un deliberado intento de profanar el lugar, erigió un altar al dios pagano Adonis sobre él. Cuando el imperio romano se hizo cristiano, a principios del siglo IV, Constantino, el primer emperador cristiano, construyó allí una gran iglesia que es la que todavía puede verse, considerablemente reformada y restaurada posteriormente.
H. V. Morton nos cuenta su visita a la Iglesia de la Natividad de Belén. Llegó a una gran muralla en la que había una puerta tan baja que uno se tenía que encorvar para entrar; y al otro lado de la puerta, y al otro lado de la muralla, estaba la iglesia. Por debajo del altar mayor de la iglesia está la cueva, y cuando el peregrino desciende a ella se encuentra con una pequeña caverna de unos trece metros de largo por cuatro de ancho, alumbrada por lámparas de plata. En el suelo hay una estrella y alrededor de ella una inscripción latina: «Aquí nació Jesucristo de la Virgen María.&quot;
Cuando el Señor de la Gloria vino a esta Tierra nació en una cueva en la que se guardaban los animales. La cueva de la Iglesia de la Natividad de Belén puede que sea la misma, o que no. Eso nunca lo sabremos de seguro. Pero hay algo hermoso en el simbolismo de la iglesia en la que la puerta es tan baja que uno tiene que inclinarse para entrar. Es supremamente apropiado el que todos nos acerquemos al Niño Jesús de rodillas.
EL HOMENAJE DEL ORIENTE
Mateo 2:1-2 (conclusión)
Cuando Jesús nació en Belén vinieron a rendirle homenaje unos sabios de Oriente. El nombre que se les da en el original es mago¡, una palabra que es difícil de traducir. Heródoto (1: 101, 132) tiene cierta información acerca de los Mago¡. Dice que eran en su origen una tribu de Media. Los medos eran parte del imperio de Persia. Trataron de desplazar a los persas sustituyendo su poder por el de los medos. El intento fracasó. Desde entonces, los Mago¡ dejaron de tener ninguna ambición de poder o de prestigio, y se convirtieron en una tribu de sacerdotes. Llegaron a ser en Persia algo parecido a lo que eran los levitas en Israel. Se convirtieron en los maestros e instructores de los reyes persas. En Persia no se podía ofrecer ningún sacrificio a menos que estuviera presente uno de los Mago¡. Llegaron a ser hombres de santidad y sabiduría.
Estos magos eran hombres versados en filosofía, medicina y ciencias naturales. Eran profetas e intérpretes de sueños. En tiempos posteriores la palabra magos adquirió un significado mucho más bajo, y llegó a querer decir poco más que adivino, brujo o charlatán. Tal era Elimas el mago (Hec 13:6-8 ), y Simón, conocido corrientemente como Simón Mago (Hec 8:9; Hec 8:11 ). Pero en su mejor época los Mago¡ eran hombres buenos y santos, que buscaban la verdad.
En aquellos días de la antigüedad, todo el mundo creía en la astrología. Creían que se podía predecir el futuro por las estrellas, y creían que el destino de una persona quedaba decidido por las estrellas bajo las que nacía. No es difícil de comprender cómo surgió esa creencia. Las estrellas siguen cursos invariables; representan el orden del universo. Y entonces, si repentinamente aparecía alguna estrella brillante, si el orden invariable de los cielos se quebrantaba por algún fenómeno especial, parecía como si Dios estuviera interviniendo en Su propio orden, y anunciando algo muy especial.
No sabemos cuál fue la brillante estrella que vieron aquellos antiguos Mago¡. Se han hecho muchas sugerencias. Hacia el año 11 a.C., el cometa Halley estuvo visible cruzando brillantemente los cielos. Hacia el año 7 a.C. hubo una brillante conjunción de Saturno y Júpiter. En los años 5 a 2 A.C. hubo un fenómeno astronómico inusual. En esos años, el primer día del mes egipcio, Mesori, Sirio, la estrella perro, salió helicalmente, es decir, al amanecer, mostrando un brillo extraordinario. Ahora bien, el nombre Mesori quiere decir el nacimiento de un príncipe, y para aquellos antiguos astrólogos tal estrella querría decir indudablemente el nacimiento de algún gran rey. No podemos decir cual fue la estrella que vieron los Mago¡; pero su profesión consistía en observar los cielos, y algún brillo celestial les anunció la entrada de un gran Rey en el mundo.
Puede que nos parezca extraordinario el que aquellos hombres iniciaran un viaje desde Oriente para encontrar a un rey; pero lo extraño es que, precisamente en el tiempo en que nació Jesús, hubo en el mundo un sentimiento extraño de expectación de la venida de un rey. Hasta los historiadores Romanos lo sabían. No mucho tiempo después, Suetonio podía escribir: «se había extendido por todo el Oriente una vieja creencia establecida de que estaba programado para aquel tiempo que vinieran hombres de Judasa a regir el mundo» (Suetonio: Vida de Vespasiano 4: 5). Tácito nos habla de la misma creencia de que «había una firme convicción... de que por este mismo tiempo el Oriente habría de tener mucho poder, y gobernantes que vinieran de Judasa adquirirían un imperio universal» (Tácito: Historias, 5: 13). Los judíos tenían la creencia de que «hacia ese tiempo uno de su país se convertiría en el gobernador de todo el mundo habitado» (Josefo: Guerras de los judíos, 6: 5, 4). En un tiempo ligeramente posterior encontramos a Tirídates, rey de Armenia, visitando a Nerón en Roma acompañado con sus Magui (Suetonio: Vida de Nerón 13:1). Encontramos a los Magui en Atenas sacrificando en memoria de Platón (Séneca: Epístolas, 58: 31). Casi por el mismo tiempo en que nació Jesús encontramos al emperador Augusto aclamado como el Salvador del Mundo; y Virgilio, el poeta latino, escribe en su Cuarta égloga, que se conoce como la Égloga Mesiánica, acerca de los dorados días por venir.
No tenemos ni la más mínima necesidad de pensar que la historia de la llegada de los Mago¡ a la cuna de Cristo sea simplemente una preciosa leyenda. Es exactamente la clase de cosa que podía suceder fácilmente en aquel mundo antiguo. Cuando vino Jesucristo, el mundo estaba en una ansiedad de expectación. La humanidad estaba esperando a Dios, y el deseo de Dios estaba en sus corazones. Habían descubierto que no podían construir la edad de oro sin Dios. Fue a un mundo en expectativa al que vino Jesús; y, cuando vino, los fines de la Tierra se reunieron a Su cuna. Fue la primera señal y símbolo de la conquista universal de Cristo.</p>
<br/>
<p class="text-justify">EL REY ASTUTO
Mateo 2:3-9
Cuando el rey Herodes se enteró de la noticia, se quedó muy preocupado, y lo mismo toda Jerusalén. Así es que convocó a todos los principales sacerdotes y a los escribas del pueblo, y les preguntó dónde había de nacer el Ungido de Dios. Y ellos le dijeron:
-En Belén de Judasa, porque así está escrito en los profetas: «Y tú, Belén, tierra de Judá, no eres ni mucho menos el menor entre los jefes de Judá; porque de ti saldrá un Pastor que apacentará a Mi pueblo Israel.»
Entonces Herodes citó en secreto a los sabios y los interrogó astutamente acerca de cuándo había aparecido la estrella. Luego los envió a Belén, diciéndoles:
-Id vosotros allá; y haced todo lo posible por descubrir lo que sea de ese Niño. Y cuando Le encontréis, hacédmelo saber, para que yo también vaya a adorarle.
Después de esta entrevista con el rey, los sabios siguieron su camino.
Llegó a los oídos de Herodes la noticia de que habían llegado de Oriente unos sabios, y que estaban buscando a un Niño que había nacido para ser el Rey de los judíos. Cualquier rey se habría preocupado de la noticia de que había nacido un niño que iba a ocupar su trono. Pero Herodes se preocupó por partida doble.
Herodes era medio judío y medio edomita. Tenía sangre edomita en las venas. Se había hecho útil a los Romanos en las guerras y en los levantamientos de Palestina, y confiaban en él. Le habían nombrado gobernador en el año 47 a.C.; el 40 a.C. había recibido el título de rey; y su reinado se prolongó hasta el 4 a.C. Había ejercido el poder mucho tiempo. Se le llamaba Herodes el Grande, y en muchos sentidos merecía ese título. Fue el único gobernador de Palestina que consiguió mantener la paz e imponer el orden. Fue un gran constructor; fue el que construyó el templo de Jerusalén. Sabía ser generoso. En los tiempos difíciles reducía los impuestos para hacerle las cosas más fáciles al pueblo; y en el hambre del año 25 a.C. llegó hasta fundir su propia vajilla de oro para comprar trigo para el pueblo hambriento.
Pero había un fallo terrible en el carácter de Herodes. Era suspicaz hasta casi la locura. Siempre había sido suspicaz; y cuanto más viejo se hacía, también se hacía más suspicaz hasta que, en su vejez, era, como dijo alguien, &quot; un viejo asesino.» Si sospechaba que alguien pudiera ser su rival en el poder, eliminaba a esa persona a toda prisa. Asesinó a su esposa Mariamne y a su madre Alejandra. Su hijo mayor, Antípater, y otros dos de sus hijos, Alejandro y Aristóbulo, también fueron asesinados por orden suya. Augusto, el emperador romano, había dicho amargamente que estaba más a salvo un cerdo de Herodes que un hijo de Herodes. (Este dicho resulta todavía más epigramático en griego, porque hus es la palabra para cerdo, y hyiós es la palabra para hijo). Algo de la naturaleza salvaje, amargada y retorcida de Herodes se puede ver en los preparativos que hizo cuando veía cerca la muerte. Cuando tenía setenta años, sabía que se iba a morir. Se retiró a Jericó, la más encantadora de todas sus ciudades. Dio órdenes para que se hiciera una recolección de los ciudadanos más distinguidos de Jerusalén, que los arrestaran con acusaciones amañadas y los metieran en la cárcel. Y dio orden de que en el momento en que él muriera, los mataran a todos. Dijo sarcásticamente que se daba cuenta de que nadie lloraría su muerte, y estaba decidido a que se derramaran lágrimas cuando él muriera.
Está claro lo que un hombre así sentiría cuando le llegó la noticia de que había nacido un Niño que estaba destinado a ser Rey. Herodes se turbó, y toda Jerusalén con él porque Jerusalén sabía muy bien los pasos que daría Herodes para comprobar esa noticia y eliminar a ese chico. Jerusalén conocía a Herodes y temblaba esperando su inevitable reacción.
Herodes convocó a los principales sacerdotes y los escribas. Los escribas eran los expertos en las Escrituras y en la Ley. Los principales sacerdotes formaban un grupo que consistía en dos clases de personas. Por una parte, los ex-sumo-sacerdotes. El sumo-sacerdocio estaba confinado a muy pocas familias. Eran la aristocracia sacerdotal, y los miembros de estas familias selectas se llamaban los principales sacerdotes. Así que Herodes convocó a la aristocracia religiosa y a los principales teólogos de su tiempo, y les preguntó dónde, según las Escrituras, había de nacer el Ungido de Dios. Ellos le citaron el texto de Miq 5:2 . Herodes mandó buscar a los sabios, y los envió por delante para que hicieran una investigación diligente acerca del Niño que había nacido. Dijo que él igualmente quería ir y adorar al Niño; pero su único deseo era matarle.
Tan pronto como nació Jesús vemos a los hombres agrupándose en los tres partidos que aparecerán siempre en relación con Jesucristo. Consideremos sus tres reacciones.
(i) Tenemos la reacción de Herodes, la reacción del odio y la hostilidad. Herodes tenía miedo de que este Niño pudiera interferir en su vida, su posición, su poder, su influencia; y por tanto, su primer instinto fue destruirle.
Todavía hay personas que destruirían de buena gana a Jesucristo, porque ven en El al Que interfiere en sus vidas. Quieren hacer lo que les plazca, y Cristo no les dejará; así que querrían matarle. La persona cuyo único deseo es hacer lo que le venga en gana no necesita para nada a Jesucristo. El cristiano es el que ha dejado de hacer lo que quiere para dedicar su vida a hacer lo que Cristo quiere.
(ii) Tenemos la reacción de los principales sacerdotes y los escribas, la reacción de una indiferencia total. No les importaba lo más mínimo. Estaban tan inmersos en el ritual de su templo y en sus discusiones legales que pasaban completamente de Jesús. No les decía nada.
Todavía hay personas que están tan interesadas en sus propios asuntos que Jesucristo no les dice nada. Todavía se puede hacer la entrañable pregunta del profeta: «¿No os conmueve a cuantos pasáis por el camino?&quot; (Lam 1:12 ).
(iii) Tenemos la reacción de los sabios, la reacción de piadoso servicio, el deseo de poner a los pies de Jesucristo los dones mas nobles que pudieran aportar.
Sin duda, cuando uno se da cuenta del amor de Dios en Jesucristo, también se pierde como ellos en admiración, alabanza y adoración.</p>
<br/>
<p class="text-justify">REGALOS PARA CRISTO
Mateo 2:9-12
Y fijaos: la estrella que habían visto en ascendente los siguió guiando hasta que llegó a encontrarse por encima del lugar donde estaba el Niño.
Cuando volvieron a ver la estrella se pusieron jubilosos de alegría. Y cuando entraron en la casa vieron al Niño con Su madre María, y cayeron de rodillas y Le adoraron. Luego abrieron sus tesoros y Le ofrecieron de regalo oro, incienso y mirra.
Y, comoquiera que recibieran un mensaje de Dios en sueños advirtiéndoles que no volvieran a Herodes, se volvieron a su propia tierra por otro camino.
Así que los sabios encontraron la manera de llegar a Belén. No tenemos que pensar necesariamente que la estrella se moviera como un guía por los cielos. Esto es poesía, y no debemos convertirla en prosa cruda y sin vida. Pero la estrella estaba brillando sobre Belén. Hay una leyenda preciosa que nos dice que la estrella, una vez cumplida su misión de guía, se cayó en el pozo de Belén, y que está todavía allí, y todavía la pueden ver a veces los limpios de corazón.
Leyendas posteriores se han ocupado afanosamente de los sabios. Al principio, la tradición oriental decía que habían sido doce; pero ahora, la tradición de que fueron tres es casi universal. El Nuevo Testamento no dice cuántos fueron, pero la idea de que fueron tres surgió sin duda de los tres regalos que trajeron. Leyendas posteriores los hicieron reyes. Y una leyenda aún más posterior les puso nombres: Gaspar, Melchor y Baltasar. Todavía más tarde se asignó a cada uno una descripción personal, y se especificó el regalo que aportó cada uno a Jesús. Melchor era anciano, de pelo blanco y con una barba larga, y fue él el que trajo el regalo del oro. Gaspar era joven y lampiño y claro de rostro, y fue el que contribuyó el incienso. Baltasar era negro, con una barba nueva, y fue el que trajo el don de la mirra.
Desde tiempos muy primitivos se ha visto lo apropiados que fueron los regalos que trajeron los sabios. Se ha visto en cada uno de ellos algo que armonizaba especialmente con alguna característica de Jesús y de Su obra.
(i) El oro es el regalo para un rey. Séneca nos dice que en Partia había la costumbre de que nadie se pudiera acercar al rey sin un regalo. Y el oro, el rey de los metales, era regalo apropiado para el Rey de los hombres.
Así que Jesús fue «el Hombre nacido para ser Rey.» Pero había de reinar, no por la fuerza, sino por el amor; no desde un trono, sino desde una Cruz.
Haremos bien en recordar que Jesucristo es Rey. No podemos nunca encontrarnos con Él en igualdad de términos. Siempre debemos acercarnos a Él con una sumisión total. Nelson, el gran almirante, siempre trataba a sus enemigos vencidos con la mayor amabilidad y cortesía. Después de una de sus victorias navales, el almirante derrotado fue traído a bordo del buque bandera de Nelson y a su alcázar. Conociendo la reputación de cortesía que tenía Nelson, y pensando aprovecharse de ella, avanzó por el alcázar con la mano extendida, como para saludar a un igual. Nelson mantuvo la mano en el costado. «Primero vuestra espada -dijo-, y luego vuestra mano.» Antes de tratar a Cristo como amigos debemos someternos a Él.
(ii) El incienso es el regalo para un sacerdote. Era en el culto del templo y en sus sacrificios donde se usaba el dulce aroma del incienso. La función de un sacerdote es abrirles a los hombres el camino hacia Dios. La palabra latina para sacerdote es pontifex, que quiere decir el que hace de puente. Esta es la misión y el privilegio del sacerdote: servir de puente entre Dios y los hombres.
Eso es Jesús. Abrió el camino a Dios; nos hizo posible llegar a la misma presencia de Dios.
(iii) La mirra es el regalo para uno que va a morir. La mirra se usaba para embalsamar los cuerpos de los muertos.
Jesús vino al mundo para morir. Holman Hunt tiene un famoso cuadro de Jesús. Nos muestra a Jesús a la puerta del taller de carpintero de Nazaret. Todavía no es más que un muchacho, y ha salido a la puerta para estirar Sus miembros que se Le han quedado agarrotados con el trabajo. Está de pie en el umbral con los brazos extendidos, y detrás de Él, en la pared el sol poniente proyecta su sombra, y es la sombra de una cruz. Al fondo está María, y al ver esa sombra se refleja en sus ojos el temor de la tragedia inminente.
Jesús vino al mundo a vivir por los hombres y a morir por los hombres. Vino a dar por los hombres tanto Su vida como Su muerte.
El oro para un rey, el incienso para un sacerdote, la mirra para uno que había de morir -estos fueron los regalos de los sabios que, aun a los pies de la cuna de Cristo, predecían que había de ser el verdadero Rey, el perfecto Sumo Sacerdote y, por último, el supremo Salvador de los hombres.</p>
<br/>
<p class="text-justify">LA HUIDA A EGIPTO
Mateo 2:13-15
Después de marcharse los sabios, mirad: un ángel del Señor se le apareció a José en sueños, y le dijo:
-Levántate, toma al Niño y a Su Madre y huye con ellos a Egipto y quédate allí hasta que yo te diga; porque Herodes está a punto de ponerse a buscar al Niño para quitarle la vida.
Así es que José se levantó, y tomó al Niño con Su Madre de noche y se marchó a Egipto, y se quedó allí hasta la muerte de Herodes. Todo esto sucedió para que se cumpliera lo que Dios había dicho por medio del profeta: «He llamado a Mi Hijo para que saliera de Egipto.»
El mundo antiguo no ponía en duda que Dios mandara Sus mensajes a los hombres en sueños. Así es que José fue advertido en un sueño para que huyera a Egipto para escapar de las intenciones asesinas de Herodes. La huida a Egipto era totalmente natural. A menudo, a lo largo de los siglos turbulentos que precedieron a la venida de Jesús, cuando algún peligro o alguna tiranía o alguna persecución les hacían la vida insoportable a los judíos, buscaban refugio en Egipto. El resultado fue que en todas las ciudades de Egipto había una colonia de judíos; y en la ciudad de Alejandría había de hecho más de un millón de judíos, y algunos de sus distritos estaban ocupados exclusivamente por ellos. José, en su hora de peligro, hizo lo que muchos judíos habían hecho antes; y cuando José y María llegaron a Egipto, no se encontrarían totalmente entre extranjeros, porque en todos los pueblos y ciudades encontrarían a judíos que se habían refugiado allí.
Es un hecho interesante que en días posteriores los enemigos del Cristianismo y los enemigos de Jesús solían atribuir a Su estancia en Egipto el origen de muchas cosas de las que Le calumniaban. Egipto era proverbialmente la tierra de la brujería y de la magia. El Talmud dice: «Diez medidas de brujería descendieron al mundo; Egipto recibió nueve, y el resto del mundo la otra.» Así que los enemigos de Jesús pretendían que había sido en Egipto donde Jesús había aprendido la magia y la brujería que Le permitieron hacer milagros y engañar a la gente.
Cuando el filósofo pagano Celso dirigió su ataque contra el Cristianismo en el siglo III, ataque que arrostró y derrotó Orígenes, dijo que Jesús se había criado como un hijo ilegítimo, que alquiló sus servicios en Egipto, que adquirió el conocimiento de ciertos poderes milagrosos, y volvió a su propio país para usarlos proclamándose Dios (Orígenes: Contra Celso 1: 38). Un cierto rabino, Eliezer ben Hyrcanus, dijo que Jesús tenía todas las fórmulas mágicas necesarias tatuadas en el cuerpo para no olvidarlas. Tales eran las calumnias que mentes retorcidas conectaban con la huida a Egipto; pero son obviamente absurdas, porque Jesús llegó a Egipto cuando era un bebé y era un chico pequeño cuando volvió.
Dos de las más preciosas leyendas relacionadas con el Nuevo Testamento están conectadas con la huida a Egipto. La primera es acerca del ladrón penitente, al que llama Dimas, y nos cuenta la historia como sigue. Cuando José y María iban con el Niño hacia Egipto, fueron asaltados por unos ladrones. Uno de sus jefes quería matarlos inmediatamente para robar su reducido equipaje. Pero algo acerca del Niño Jesús penetró en el corazón de Dimas, que era uno de aquellos ladrones. Él impidió que se les hiciera ningún daño a Jesús y a Sus padres. Miró a Jesús y Le dijo: «¡Oh, el más bendito de los niños! Si alguna vez llega el momento de tener misericordia de mí, acuérdate de mí y no olvides esta hora.» Y la leyenda dice que Jesús y Dimas se encontraron otra vez en el Calvario, y Dimas encontró en la cruz el perdón y la misericordia para su alma y la seguridad de la Salvación.
Una variante de esta leyenda es aún mejor conocida en España, porque se encuentra en el «Libro de los Tres Reyes de Oriente», una joyita de los orígenes de la literatura española. Cuenta esta variante que, cuando iba huyendo de Belén a Egipto la Sagrada Familia, fue apresada por dos bandoleros; el uno era cruel, y quería matar al Niño Jesús; y el otro, compasivo, que Le salvó la vida e invitó a la Sagrada Familia a pasar la noche en su cueva. La mujer de este «buen ladrón» le cuenta a María que tiene un hijito recién nacido que está leproso. María le baña en la misma agua en la que ha bañado a Jesús, y el niño queda sano y limpio. Pasado el tiempo, en el Calvario, el hijo del ladrón alevoso muere a la izquierda de Jesús, y el del compasivo a la derecha, y este fue el que pasó al santoral de la Iglesia Católica sencillamente como &quot;el buen ladrón», aunque diversas tradiciones le llamaron Dimas, Dismas o Dimsas.
La otra leyenda es una historia de niños, pero muy encantadora. Cuando José y María y Jesús iban de camino a Egipto, cuenta la historia, a la caída de la tarde estaban cansados, y se refugiaron en una cueva. Hacía mucho frío, tanto que el suelo estaba blanco de escarcha. Una arañuela vio al bebé Jesús y quiso hacer algo para que estuviera calentit aquella fría noche. Lo único que sabía hacer era tejer telas de araña; así es que eso fue lo que hizo: urdió su tela a través de la entrada de la cueva para hacer, como si dijéramos, una cortina.
Por el sendero llegaba un destacamento de soldados buscando niños para matarlos en cumplimiento a la sangrienta orden de Herodes. Cuando llegaron a la cueva estuvieron a punto de entrar violentamente; pero su capitán notó la tela de araña, cubierta de escarcha, que cerraba la entrada de la cueva. &quot; Fijaos -dijo- en esa tela de araña. Está intacta y no puede haber nadie en la cueva, porque cualquiera que hubiera entrado la habría roto.»
Así que los soldados pasaron, y dejaron a la Sagrada Familia en paz, gracias a que una arañuela había tejido su red en la entrada de la cueva. Y esa, por así decirlo, es la razón de que hasta este día pongamos hilillos luminosos de plata en nuestros árboles de Navidad, que representan la tela de la araña, blanca de escarcha, que se extendía de un lado a otro de la entrada de la cueva de la huida a Egipto. Es una historia preciosa; y por lo menos contiene una gran verdad: Que no hay don que Jesús reciba que se olvide nunca.
Las últimas palabras de este pasaje nos introducen en una costumbre que es característica de Mateo. El vio en la huida a Egipto el cumplimiento del dicho de Oseas. Lo cita en esta forma: «He llamado a mi hijo para que saliera de Egipto.» Es una cita de Ose 11:1 , que dice: «Cuando Israel era muchacho, yo lo amé, y de Egipto llamé a Mi hijo.»
Está claro que, en su forma original, este dicho de Oseas no tenía nada que ver con Jesús ni con la huida a Egipto. No era más que una simple afirmación de la manera como Dios había librado a la nación de Israel de la esclavitud y de la opresión en tierra de Egipto.
Veremos una y otra vez que esto es típico del uso que hace Mateo del Antiguo Testamento. Esta dispuesto a usar como una profecía acerca de Jesús cualquier texto que pueda encajar verbalmente, aunque originalmente no tuviera nada que ver con el tema en cuestión, ni nunca se supusiera que tuviera nada que ver con ello. Mateo sabía que casi la única manera de convencer a los judíos de que Jesús era el prometido Ungido de Dios era demostrar que en Él se cumplieron las profecías del Antiguo Testamento. Y en su ansiedad por llevarlo a cabo encuentra profecías en el Antiguo Testamento que nunca se pretendió que lo fueran. Cuando leemos un pasaje como este debemos recordar que, aunque nos parece extraño e inconclusivo, llamaría la atención de aquellos para quienes Mateo estaba escribiendo.</p>
<br/>
<p class="text-justify">LA MATANZA DE LOS NIÑOS
Mateo 2:16-18
Cuando Herodes vio que los sabios le habían burlado, mandó matar a todos los niños de Belén y sus aledaños. Mandó matar a todos los niños de dos años para abajo, calculándolo por el tiempo que había investigado de los sabios. Entonces se cumplió lo que se había dicho por medio del profeta Jeremías: «Se oyó una voz en Ramá, llanto y grandes Lamentaciones; era Raquel llorando a sus hijos inconsolablemente, porque no le quedaba ninguno.»
Ya hemos visto que Herodes era un genio en el arte del asesinato. No había hecho más que subir al trono y ya empezó aniquilando el sanedrín, el tribunal supremo de los judíos. Más tarde hizo una matanza improvisada de trescientos oficiales de la corte. Después mató a su mujer Mariamne, a la madre de ésta, Alejandra, a su propio primogénito Antípater, a otros dos hijos suyos, Alejandro y Aristóbulo. Y a la hora de su muerte hizo los preparativos para la matanza de muchos nobles de Jerusalén.
No se podía esperar que Herodes aceptara tranquilamente la noticia de que había nacido un Niño que llegaría a ser Rey. Ya hemos leído cómo inquirió cuidadosamente de los sabios cuándo habían visto la estrella. Aun entonces, estaba deduciendo astutamente la edad del niño para dar los pasos para eliminarle, y en este punto puso sus planes en acción rápida y salvajemente. Dio la orden de que todos los niños de dos años para abajo de Belén y sus aledaños fueran asesinados.
Hay dos cosas que debemos notar. Belén no era un pueblo grande, y el número de los niños no pasaría de los veinte o treinta. No debemos pensar en términos de centenares. Es verdad que esto no hace el crimen de Herodes nada menos terrible, pero debemos hacernos una idea clara.
En segundo lugar, hay algunos críticos que mantienen que esta matanza no puede haber tenido lugar, porque no se menciona en ningún otro lugar fuera de este único pasaje del Nuevo Testamento. El historiador judío Josefo, por ejemplo, no lo menciona. Hay dos cosas que se deben decir. La primera, como acabamos de ver, es que Belén era un lugar relativamente pequeño, y estaba en una zona en la que el asesinato era tan corriente que la matanza de veinte o treinta bebés no causaría gran conmoción, y querría decir muy poco salvo para las afligidas madres de Belén. En segundo lugar, Carr hace notar que Macaulay, en su historia, indica que el famoso autor de diarios Evelyn, que fue de lo más asiduo y voluminoso reportero de acontecimientos contemporáneos, nunca menciona la matanza escocesa de Glencoe. El hecho de que algo no se mencione, ni siquiera allí donde uno esperaría que se mencionara, no es prueba concluyente de que no sucediera. Todo este incidente es tan típico de Herodes que no tenemos por qué dudar que Mateo nos transmitió la verdad.
Aquí tenemos una terrible ilustración acerca de lo que hacen algunos para librarse de Jesucristo. Si una persona está empeñada en seguir los dictados de su propia voluntad, y ve en Cristo a Alguien que es probable que le cierre el camino de su ambición y se oponga a sus métodos, su deseo será eliminar a Cristo; y luego se lanzará a las cosas más terribles, porque si no llega a destrozar los cuerpos de la gente, es seguro que destrozará su corazón.
De nuevo vemos la manera característica que tiene Mateo de usar el Antiguo Testamento. Cita Jer 31:15 : &quot; Así ha dicho el Señor: &quot;Voz fue oída en Ramá, llanto y lloro amargo: Es Raquel que llora a sus hijos, y no quiso ser consolada acerca de sus hijos, porque perecieron.&quot;»
El versículo de Jeremías no tiene ninguna relación con la matanza de los niños que hizo Herodes. La escena de Jeremías es lo siguiente. Jeremías retrataba al pueblo de Israel llevado en cautiverio. En su triste caminar hacia una tierra ajena pasaron Ramá, que era donde estaba enterrada Raquel (1Sa 10:2 ); y Jeremías retrata a Raquel llorando, aun en su tumba, por la suerte que ha sobrevenido al pueblo.
Mateo está haciendo lo que hace a menudo. En su ansiedad, encuentra una profecía donde no la había. Pero, de nuevo, debemos recordar que lo que a nosotros nos parece extraño no se lo parecería a aquellos para los que Mateo estaba escribiendo entonces.</p>
<br/>
<p class="text-justify">LA VUELTA A NAZARET
Mateo 2:19-23
Cuando murió Herodes, fijaos: el ángel del Señor se le apareció en sueños a José en Egipto y le dijo:
-Levántate, toma al Niño y a Su Madre y vete al país de Israel; porque los que intentaban acabar con Su vida ya han muerto.
Así que se levantó y tomó al Niño y a Su Madre y volvió al país de Israel. Y cuando se enteró de que Arquelao había quedado como rey de Judasa después de la muerte de su padre Herodes, tuvo temor de ir allí. Así pues, después de recibir un mensaje del Señor en sueños, se retiró a la región de Galilea, y fue, y se instaló en un pueblo llamado Nazaret. Esto sucedió para que se cumpliera lo que el Señor había dicho por medio de los profetas: «Se le llamará el Nazareno.»
A su debido tiempo Herodes murió, y entonces todo el reino que había regido se dividió. Los Romanos habían confiado en Herodes, y le habían permitido reinar sobre un territorio muy considerable; pero Herodes sabía muy bien que a ninguno de sus hijos se le permitiría detentar un poder semejante. así que hizo dividir su reino en tres, y en su testamento dejó una parte a cada uno de sus tres hijos: Judasa, a Arquelao; Galilea, a Herodes Antipas, y la región lejana al Nordeste y al otro lado del Jordán, a Felipe.
Pero la muerte de Herodes no resolvió el problema. Arquelao fue un mal rey, y no había de durar mucho en el trono. De hecho, había empezado su reinado tratando de ser más Herodes que Herodes, porque inició su gobierno con la matanza deliberada de tres mil de los más influyentes del país. Está claro que, aun cuando Herodes ya había muerto, todavía era inseguro volver a Judasa cuando estaba en el trono el salvaje y despiadado Arquelao. Así es que José fue guiado a ir a Galilea donde reinaba Herodes Antipas, mucho mejor rey.
Fue en Nazaret donde José se afincó, y fue allí también donde se crió Jesús. No se debe pensar que Nazaret fuera un lugarejo insignificante que no tuviera contacto con la vida y con los acontecimientos.
Nazaret estaba situado en una vaguada en medio de las colinas al sur de Galilea. Pero un chico no tenía más que escalar las colinas para tener a la vista medio mundo. Podía mirar hacia el Oeste, y sus ojos se encontrarían con las aguas del Mediterráneo, azul en la distancia; y vería los navíos que salían hacia los fines de la Tierra. Sólo tenía que mirar a la llanura que se deslizaba hacia la costa, y vería, serpeando alrededor del pie de la misma colina en la que se encontraba, la carretera de Damasco a Egipto, el puente terrestre con África. Era una de las rutas de caravanas más importantes del mundo.
Era la carretera por la que, siglos atrás había ido José a Egipto vendido como un esclavo. Era la carretera que había seguido Alejandro Magno con sus legiones trescientos años antes. Era la carretera por la que siglos después había de marchar Napoleón. Era la carretera que había de tomar Allenby en el siglo veinte. Algunas veces se la llamaba el Camino del Sur, y algunas veces la Carretera del Marcos En ella vería Jesús toda clase de viajeros de toda clase de naciones en toda clase de misiones, yendo y viniendo de los términos de la Tierra.
Pero había otra carretera. Se separaba de la costa en Acre o Tolemaida y se dirigía hacia el Este. Era la Carretera del Este. Conducía al extremo y a la frontera orientales del imperio romano. De nuevo la cabalgata de las caravanas con sus sedas y especias pasaría continuamente por allí; y también las legiones romanas en marcha hacia las fronteras.
Está claro que Nazaret no era ningún rincón. Jesús se crió en un pueblo al pie de cuyas colinas pasaban los términos de la Tierra. Desde los días de Su niñez debe de haber visto escenas que le hablaran de un mundo para Dios.
Ya hemos visto que Mateo enlaza todos los acontecimientos del principio de la vida de Jesús con un pasaje del Antiguo Testamento que considera que lo profetiza. Aquí cita Mateo una profecía: &quot; Será llamado Nazareno;» y aquí nos plantea Mateo un problema insoluble, porque no hay tal texto en el Antiguo Testamento. De hecho, ni siquiera se menciona a Nazaret en el Antiguo Testamento. Nadie ha resuelto satisfactoriamente el problema de la parte del Antiguo Testamento que Mateo tenía en mente.
Los antiguos escritores eran muy aficionados a los retruécanos y juegos de palabras. Se ha sugerido que Mateo está jugando con las palabras de Isa 11:1 : «Saldrá una vara del tronco de Isaí; un vástago retoñará de sus raíces.» La palabra para vástago es nétser, la Rama prometida del tronco de Jesé, el Descendiente de David, el prometido Ungido Rey de Dios; y nétser se parece a nótsrí, Nazareno. No se puede asegurar nada. Seguirá siendo un misterio la profecía que Mateo tenía en mente.
Así que ahora ya está montada la escena; Mateo ha traído a Jesús a Nazaret, y en un sentido muy real Nazaret era la puerta del mundo entero.
LOS AÑOS DE ENTREMEDIAS
Antes de pasar al tercer capítulo del evangelio de Mateo hay algo que haremos bien en tener en cuenta. El capítulo segundo del evangelio cierra con Jesús como un chico; el tercer capítulo del evangelio se abre con Jesús como un hombre de treinta años (cp. Luc 3:23 ). Es decir, que entre los dos capítulos hay treinta años de silencio. ¿Por qué tenía que ser así? ¿Qué sucedió en esos años de silencio? Jesús vino al mundo para ser el Salvador del mundo, y pasó treinta años sin salir de los límites de Galilea excepto para ir a Jerusalén para la Pascua. Murió cuando tenía treinta y tres años, y de ellos pasó treinta, de los que no sabemos casi nada, en Nazaret. Para decirlo de otra manera, diez onceavas partes de la vida de Jesús transcurrieron en Nazaret. ¿Qué pasaba entonces?
(i) Jesús fue creciendo y haciéndose un joven, y luego un hombre, en un buen hogar; y no puede haber mejor principio que ese para una vida. J. S. Blackie, el famoso profesor de Edimburgo, dijo una vez en público: «Quiero dar gracias a Dios por la buena casta, por así decirlo, que heredé de mis padres para el negocio de la vida.» George Herbert dijo una vez: «Una buena madre vale como cien maestras.» Así pasaban los años para Jesús, silenciosamente modelándole en el círculo de un buen hogar.
(ii) Jesús estaba cumpliendo los deberes que corresponden al hijo mayor. Parece muy probable que José muriera antes de que toda la familia fuera mayor de edad. Puede que ya fuera mucho mayor que María cuando se casaron. En la historia de la fiesta de bodas de Caná de Galilea no se menciona a José, aunque María sí estaba allí; y es natural suponer que José habría muerto.
Así es que Jesús pasó a ser el artesano del pueblo de Nazaret para mantener a Su Madre y a Sus hermanos menores. Todo un mundo Le estaba esperando y llamando, y, sin embargo, antes de acudir, tuvo que cumplir con Su obligación para con Su familia y hogar. Cuando murió la madre de Sir James Barrie, este pudo escribir: «Puedo mirar atrás, y no puedo descubrir la menor cosa que dejara sin hacer.» Ahí se encuentra la felicidad. Es gracias a los que aceptan los deberes más sencillos con fidelidad y sin refunfuñar como se va edificando el mundo.
Uno de los grandes ejemplos de esto fue el gran médico Sir James Y. Simpson, el descubridor del cloroformo. Venía de un hogar pobre. Un día, su madre le puso en sus rodillas y empezó a zurcirle los calcetines. Cuando terminó, miró su minucioso trabajo, y le dijo: &quot;Mi Jamie, acuérdate cuando tu madre se haya ido de que era una gran zurcidora.» Jamie (el diminutivo de James) era «el chaval listo», &quot;la cajita de sesos», y su familia lo sabía. Tenían sus sueños para él. Su hermano Sandy decía: &quot;Ya me figuraba yo que sería famoso algún día.» Y así, sin envidia y con generosidad, sus hermanos trabajaban en el taller a sus tareas para que el chaval pudiera ir a la universidad y tener una oportunidad. No habría habido un Sir James Simpson si no hubiera sido por gente humilde y generosa dispuesta a hacer cosas sencillas y negarse a sí mismos para que el chico listo tuviera una oportunidad.
Jesús es el gran ejemplo del Que aceptó los sencillos deberes de una familia.
(iii) Jesús estaba aprendiendo lo que es ser un obrero. Estaba aprendiendo lo que costaba ganarse la vida, ahorrar para comida y ropa, y puede que a veces algún extra; tratar con el cliente crítico y difícil de complacer, y con el moroso. Si Jesús había de ayudar a los hombres, tenía que empezar por saber cómo era la vida de la gente. No vino a una vida protegida y almohadillada, sino a la que cualquier hombre tenía que vivir. Tenía que hacerlo para llegar a comprender la vida de la gente normal y corriente.
Hay una historia famosa de María Antonieta, la reina de Francia, en los días cuando se estaba fraguando la Revolución Francesa por todo el país antes de estallar. La gente se moría de hambre; el gentío se amotinaba. La reina preguntó la causa de todo el jaleo, y se le dijo: «No tienen pan.» &quot;¡Pues que coman bollos!» -contestó. La idea de una vida sin abundancia no le entraba en la cabeza.
Jesús trabajó en Nazaret todos esos años de silencio a fin de poder conocer por propia experiencia cómo es nuestra vida; y para, comprendiéndolo, poder ayudarnos.
(iv) Jesús estaba cumpliendo fielmente en el trabajo menos importante antes de que se Le confiara el más importante. El gran hecho es que, si Jesús hubiera fallado en los deberes menores, la tarea impresionante de ser el Salvador del mundo no se Le habría podido confiar a Él. Fue fiel en lo poco para encargarse de lo mucho. No debemos olvidar nunca que en los deberes cotidianos de la vida hacemos o deshacemos un destino, y ganamos o perdemos una corona.
###</p>
<br/>




</div>
