<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 27</h2>
<p class="text-justify">EL HOMBRE QUE CONDENÓ A MUERTE
A JESÚS
Mateo 27:1-2, 11-26
Cuando se hizo de día, todos los principales sacerdotes y los ancianos del pueblo tuvieron una consulta para condenar a muerte a Jesús; así es que Le ataron y Le llevaron para entregársele al gobernador Pilato.
Jesús estaba de. pie ante. el gobernador, y este Le preguntó directamente:
-¿Eres Tú el Rey de los judíos?
-Tú eres el que lo has dicho -le contestó Jesús.
Mientras los principales sacerdotes y los ancianos Le
estaban acusando, Jesús no daba respuesta. Entonces Pilato Le preguntó:
-¿Es que no oyes la evidencia que estos están presentando contra Ti?
Jesús no contestó ni una sola palabra, lo que sorprendió mucho al gobernador.
Por el tiempo de la fiesta de la Pascua, el gobernador tenía costumbre de soltarle al pueblo a un preso, el que ellos quisieran. Por aquel entonces estaba detenido un preso muy conocido que se llamaba Barrabás. Así que, cuando estaban reunidos, les preguntó Pilato:
-¿A quién queréis que os suelte, a Barrabás o a Jesús al que llaman el Cristo?
Porque se daba perfecta cuenta de que le había entregado a Jesús maliciosamente. Mientras Pilato estaba sentado en el sillón del juicio, su mujer le envió un mensaje:
No te dejes enredar en nada que tenga que ver con este Justo -le decía ella-, porque hoy he tenido una experiencia extraordinaria en sueños en relación con Él.
Los principales sacerdotes y los ancianos convencieron al gentío que pidiera la liberación de Barrabás y la condena a muerte de Jesús.
-¿Cuál de los dos -dijo el gobernador- os tengo que soltar?
-¡Barrabás! -gritaron.
Entonces -les dijo Pilato-, ¿qué voy a hacer con Jesús, al que llaman el Cristo?
-¡Que Le crucifiquen! -dijeron todos.
-¿Qué crimen ha cometido? preguntó Pilato. Y la gente siguió gritando cada vez más:
-¡Que Le crucifiquen!
Cuando Pilato vio que no se podía hacer nada, y que había peligro de que se produjera un desorden, tomó agua y se lavó las manos en presencia de la gente.
-Vosotros veréis lo que hacéis.
-¡Que la responsabilidad de Su sangre recaiga sobre nosotros y sobre nuestros hijos! -contestó todo el pueblo.
Entonces Pilato les soltó a Barrabás, e hizo que azotaran a Jesús, y después Le entregó para que Le crucificaran.
Los dos primeros versículos de este pasaje describen lo que debe de haber -sido una reunión muy breve. del sanedrín,. celebrada de -madrugada con: la finalidad de formular una acusación oficial contra Jesús. Eso =era necesario debido al hecho de que, aunque los judíos podían juzgar casos ordinarios, no podían imponer la pena: de muerte. Esa sentencia solo la podía pronunciar el gobernador romano, y solo podían ejecutarla las autoridades romanas. El sanedrín, por tanto, tenía que formular una acusación con la que pudieran dirigirse a Pilato y solicitar la pena de muerte para Jesús.
Mateo no -nos dice cuál fue la acusación;.pero Lucas sí. En el sanedrín, la acusación que se había aceptado contra Jesús era la de blasfemia (Mat 26:65 s). Pero nadie sabía mejor que las autoridades judías que eso no era una acusación válida ante Pilato. Les diría que se marcharan y zanjaran solos sus desavenencias religiosas. Así que, como nos dice Lucas, se presentaron delante de Pilato con una triple acusación, cada una de cuyas partes era una mentira, y una mentira deliberada. Acusaron a Jesús, en primer lugar, de ser un revolucionario; en segundo, de incitar al pueblo a no pagar los impuestos, y en tercero, de presentarse como un rey (Luc 23:2 ). Pergeñaron tres acusaciones políticas, mentiras conscientes, porque sabían que esas eran las únicas que podían obligar a Pilato a actuar.
Así que todo dependía de la actitud de Pilato. ¿Qué clase de hombre era el gobernador romano?
Pilato era oficialmente el procurador de la provincia; y era responsable directamente, no. al senado romano, sino al mismo emperador. Tendría por lo menos treinta y siete años, porque esa era la edad mínima para hacerse cargo del puesto de procurador. Debe de haber sido un hombre de experiencia considerable; porque había toda una escala de cargos, incluyendo los de mando militar, por los que se tenía que ascender para poder llegar a ser gobernador. Pilato tiene que -haber sido un soldado y administrador probado y . cualificado. Llegó a ser procurador de Judasa en él año 26 d:C., y se mantuvo en oficio durante diez años, al final de los cuales fue depuesto.
Cuando Pilato llegó a Judasa, encontró problemas en abundancia, y otros muchos se los buscó él mismo. Su principal dificultad era que no les tenía absolutamente ninguna simpatía a los judíos. Por, el contrario, trataba despectivamente lo que consideraba prejuicios irracionales y fanáticos de sus súbditos, que. eran lo que ellos consideraban sus principios. Los Romanos conocían la intensidad de la religión judía, y el carácter irrompible de la fe judía, y muy sabiamente siempre habían tratado a los judíos con guante, blanco. Pilato propuso arrogantemente usar el guantelete.
Empezó con un problema. El cuartel general romano estaba en Cesarea. Los estandartes Romanos no eran simplemente banderas; eran palos largos con el águila romana o la imagen del emperador en el extremo. Por consideración con el odio judío a las imágenes, todos los anteriores gobernadores habían quitado las águilas y las imágenes de las banderas antes de entrar en Jerusalén para la visita oficial. Pilato se negó a quitarlas. El resultado fue una oposición y una intransigencia tales que Pilato tuvo que acabar por ceder; porque no era posible ni detener ni matar a toda una nación.
Más adelante, Pilato decidió que Jerusalén necesitaba un mejor sistema de conducción de agua una sabia decisión. Para ese fin construyó un nuevo acueducto =pero tomó dinero del tesoro del templo para pagarlo.
Filón, el gran filósofo Judasoalejandrino, hace un estudio psicológico de Pilato. Y Filón, recordemos, no era cristiano, sino que hablaba desde el punto de vista judío. Los judíos, nos dice Filón; habían amenazado con hacer uso de su derecho de delatar a Pilato al emperador por sus fechorías. Esta amenaza «exasperó a Pilato hasta lo sumo, porque se temía que enviaran una embajada al .emperador, que le. hicieran iniciar una investigación con respecto a otros detalles de su gobierno -su corrupción, sus actos de insolencia, su rapiña, su hábito de insultar al pueblo, su crueldad, sus constantes asesinatos de personas sin juicio ni condena y -su inhumanidad interminablemente gratuita y sádica.» La reputación de Pilato con los judíos apestaba; y el que pudieran delatarle le dejaba en una posición totalmente insegura.
Podemos seguir la carrera de Pilato hasta el final. Acabaron por llamarle a Roma para que rindiera cuentas de su brutalidad en un incidente de Samaria. Cierto impostor había citado al pueblo en el monte Gerizín pretendiendo que les mostraría las vasijas sagradas que Moisés había ocultado allí. Desgraciadamente, muchos de los asistentes vinieron armados, y se reunieron en una aldea llamada Tirabata. Pilato se lanzó sobre ellos y los masacró con un salvajismo totalmente innecesario, porque. se trataba de un movimiento inofensivo. Los samaritanos presentaron una queja a Vitelio; el legado de Siria, que era el superior inmediato de Pilato, y Vitelio le ordenó ir a Roma para responder de su conducta.
Cuando Pilato iba de camino a Roma, murió el emperador Tiberio; y parece ser que Pilato no tuvo que presentarse a juicio. Una leyenda dice que acabó cometiendo suicidio; su cuerpo se arrojó al Tíber, pero los espíritus malos revolvían las aguas de tal manera que los Romanos se llevaron el cuerpo de Pilato a Galia y lo tiraron al Ródano. La supuesta tumba de Pilato se enseña todavía en Vienne. Lo mismo sucedió allí, y el cuerpo se llevó por último a un lugar cerca de Lausana, y fue sepultado en un pozo de las montañas. Enfrente de Lucerna hay una colina que se llama el monte de Pilato. Originalmente se llamaba Pileatus, que quiere. decir con la cabeza cubierta de nubes; pero, como se conectó con Pilato, el nombre se cambió por el de Pilatus.
Más tarde, la leyenda cristiana mostró cierta compasión con Pilato, y acabó por echarle toda la culpa de la muerte de Jesús a los judíos. Naturalmente en cierto modo, la leyenda llegó a mantener que la mujer de Pilato, que se dice que era prosélita del judaísmo y que se llamaba Claudia Prócula, se convirtió al Cristianismo. También se llegó a decir que el mismo Pilato también se había hecho cristiano; y hasta el día de hoy la iglesia copta incluye a Pilato y a su mujer en el número de los santo:
Concluimos nuestros estudio de Pilato con un documento muy interesante. Pilato debe de haber enviado a Roma un informe del juicio y ejecución de Jesús; eso sería una parte normal de la administración. Un libro apócrifo llamado Los Hechos de Pilato y Pablo contiene una supuesta copia de ese informe. Ese informe lo citan también Tertuliano y Justino Mártir y Eusebio. El informe que ha llegado hasta nosotros no es probable que sea genuino, pero es interesante leerlo:
Poncio Pilato a Claudio: ¡Saludos!
Sucedió últimamente un asunto en el que yo mismo hice el juicio; porque los judíos, por envidia, se han castigado a sí mismos y a su posteridad con juicios terribles por su propia culpa; porque, aunque sus padres habían prometido que su Dios les enviaría del Cielo a Su Santo, Que debería ser Rey por derecho propio, y prometió que Él Le mandaría a la Tierra en nacimiento virginal; entonces vino cuando yo era gobernador de Judasa, y los judíos Le vieron dar vista a los ciegos, limpiar a los leprosos, sanar a los paralíticos, expulsar a los demonios, resucitar a los muertos, reprender a los vientos, andar sobre las olas del mar a pie enjuto y hacer muchas otras maravillas, y aunque todo el pueblo de los judíos Le llamaba Hijo de Dios, los principales sacerdotes, movidos por envidia contra Él, Le apresaron y me Le presentaron haciendo toda clase de falsas acusaciones una tras otra, diciendo que era hechicero y que hacía muchas cosas en contra de su ley.
Pero yo, creyendo que estas cosas eran ciertas, después de azotarle, Le entregué a su voluntad, y ellos Le crucificaron; y cuando Le enterraron pusieron una guardia al cuidado de la tumba. Pero mientras los soldados vigilaban, Él se levantó de nuevo al tercer día; sin embargo, hasta tal punto se inflamó la malicia de los judíos que les dieron dinero a los soldados diciéndoles: Vosotros decid que Sus discípulos robaron Su cuerpo. Pero ellos, aunque tomaron el dinero, no fueron capaces de guardar silencio acerca de lo que había sucedido, porque ellos también han testificado que Le vieron resucitado, y que recibieron, dinero de los judíos. Y de estas cosas he informado a vuestra alteza por esta causa, no sea que algún otro os mienta, y consideréis que debéis creer los falsos cuentos de los judíos.
Aunque ese informe no es más que una leyenda, Pilato sabía de cierto que Jesús era inocente; pero sus errores pasados pusieron en las manos de los judíos una palanca con la que le obligaron a hacer la voluntad de ellos contra los propios deseos y sentido de la justicia de él.
PILATO PIERDE LA CONTIENDA
Mateo 27:1-2, 11-26 (conclusión)
Todo este pasaje nos da la impresión de que Pilato estaba peleando una batalla perdida. Está claro que Pilato no quería condenar a Jesús. Ciertas verdades surgen de aquí.
(i) A Pilato le impresionó vivamente Jesús. Está claro que no tomó muy en serio que pretendiera ser el Rey de los judíos. Pilato reconocía a un revolucionario a primera vista, y Jesús no lo era. Su silencio digno hizo que Pilato sintiera que no era Jesús el que estaba en tela de juicio, sino él mismo, Pilato. Pilato fue un hombre que sintió el poder de Jesús -y tuvo miedo de someterse a El. Hay todavía personas que tienen miedo de ser tan cristianos como saben que deben serlo.
(ii) Pilato buscó la manera de evadir su responsabilidad. Parece que era costumbre soltar a un preso para la Pascua. En la cárcel había un cierto Barrabás. No era ningún ladronzuelo. Lo más probable es que fuera, o un bandolero, o un revolucionario político.
Se han hecho dos especulaciones interesantes acerca de él. Su nombre Bar-Abbás quiere decir Hijo del Padre. Padre era el título que se asignaba a los más respetados rabinos. Bien puede ser que Barrabás fuera hijo de una antigua familia distinguida, que se había salido del cauce tradicional y embarcado en una carrera de crímenes por todo lo alto. Un hombre así haría del crimen algo romántico, y tendría de su parte a una buena parte del pueblo.
Aún más interesante es la casi seguridad de que Barrabás también se llamara Jesús. Algunas de las más antiguas traducciones del Nuevo Testamento -por ejemplo, las antiguas versiones siríaca y armenia le llaman Jesús Barrabás; y tanto Orígenes como Jerónimo tenían noticia de esa variante y creían que podía ser correcta. Es curioso que por dos veces Pilato especifica que Jesús, al Que llaman el Cristo (versículos 17 y 22), como para distinguirle de algún otro Jesús. Jesús era un nombre corriente. Es el mismo que Josué en hebreo, y el grito frenético de la multitud es probable que fuera: &quot; ¡No Jesús el Cristo, sino Jesús Barrabás!»
Pilato buscaba una salida de emergencia, pero la multitud eligió al criminal violento y rechazó al tierno Jesús. Prefirieron al hombre de violencia al Hombre de Amor.
(iii) Pilato trató de zafarse de la responsabilidad de condenar a Jesús. Se conserva esa extraña y trágica ceremonia de Pilato lavándose las manos. Esa era una costumbre judía. Hay una extraña regla en Deu 21:1-9 . Si se encontraba un cadáver, y no se sabía quién lo había matado, se medía la proximidad del lugar con los pueblos cercanos, y los ancianos del pueblo más próximo tenían que sacrificar una becerra y lavarse las manos con su sangre para quedar libres de culpa. Pilato fue advertido por su sentido de la justicia, y por su conciencia, y por el sueño de su angustiada mujer; pero Pilato no podía resistir a la multitud; y Pilato recurrió al gesto estéril de lavarse las manos. La leyenda dice que hasta el día de hoy hay veces que la sombra de Pilato surge de su tumba y repite la ceremonia de lavarse las manos una vez más.
Hay algo de lo que una persona no puede librarse nunca -y es la responsabilidad. No es nunca posible ni para Pilato ni para ninguna otra persona el decir: &quot;Me lavo las manos de toda responsabilidad.» Porque eso es algo que nadie ni nada puede borrar.
Esta imagen de Pilato inspira en nuestras mentes más bien piedad que condenación; porque aquí tenemos a un hombre tan inmerso en su pasado y tan incapacitado por él que fue incapaz de mantenerse firme en su debida posición. Pilato es una figura de tragedia más que de villanía.</p>
<br/>
<p class="text-justify">EL FINAL DEL TRAIDOR
Mateo 27:3-10
Cuando el traidor de Judas vio que habían condenado a .Jesús, se arrepintió y trajo los, treinta siclos a los principales sacerdotes y los ancianos, y les dijo::
-Yo he pecado traicionando a un Hombre inocente
-¿Qué tenemos nosotros que ver con eso? -le dijeron-. ¡Eso es tu problema!
Judas tiró el dinero en el templo y se marchó; luego fue, y se ahorcó.
Los principales sacerdotes recogieron el dinero, y dijeron:
No podemos echar esto en el tesoro del templó; porque es el precio de una vida.
Después de deliberar, compraron con ese dinero el campo del alfarero para cementerio, de extranjeros. Por eso es por lo que hasta este día se le llama el Campo de la Sangre: Así se cumplió lo que se había dicho por medio del profeta Jeremías cuando dijo: «Y tomaron. los treinta siclos,. el precio de Aquel a cuya vida habían puesto precio los hijos. de Israel, y los dieron por el campo del alfarero, como el Señor me había advertido.-»
Aquí se nos presenta con todo su colorido macabro el último acto de la tragedia de Judas. Comoquiera que interpretemos su mentalidad, una .cosa está clara: que Judas entonces comprendió el horror de lo que había hecho. Mateo nos dice que Judas llevó el dinero y lo tiró en el templo; y es interesante que la palabra que usa no es la palabra más general para todos los edificios del templo (hierón), sino la palabra para el templo propiamente dicho (naos: Se recordará que el templo estaba formado por una serie de atrios cada uno a continuación del precedente. Judas, en su ciega desesperación, entró por el Atrio de los1&quot;Gentiles; pasó por el Atrio de las Mujeres; pasó hasta el final del Atrio, de los Israelitas; no podía entrar más allá: había llegado a la barrera que impedía la entrada en el Atrio de los Sacerdotes, al final del cual se encontraba el templo propiamente dicho. Judas llamó a los sacerdotes para que recogieran el dinero; no acudieron, y él se lo tiró desde lejos, y se marchó, y se ahorcó. Los sacerdotes recogieron el dinero, tan contaminado que no podía echarse al tesoro del templo, y compraron con él un campo para cementerio de los gentiles, para enterrar los cuerpos inmundos de los gentiles que murieran en la ciudad. -
El suicidio de Judas sería la prueba concluyente de que su plan había fracasado. Había pretendido que Jesús Se manifestara como conquistador; pero lo único que había conseguido había sido empujarle hacia la Cruz, y la vida ya no tenía para Judas ningún sentido. Hay dos grandes verdades aquí acerca del pecado.
(i) Lo terrible del pecado es que no podemos atrasar el reloj. No podemos deshacer lo que hemos hecho. Una vez que se ha hecho algo, nada lo puede alterar o hacer volver.
No hace falta ser muy viejo para sentir el anhelo de vivir otra vez alguna hora. El recordar que no se puede traer al presente nada que ya esté en el pasado debería hacernos tener mucho cuidado con nuestras acciones.
(ii) Lo extraño del pecado es que una persona puede llegar a odiar lo que ganó cometiéndolo. El mismo precio que recibió por. pecar puede llegar a asquearle hasta tal punto que su único deseo sea desembarazarse de él. La mayor parte de la gente peca porque cree que, si puede simplemente conseguir la cosa prohibida, le hará feliz. Pero lo que era el deseo del pecado puede convertirse en la cosa de la que uno querría librarse -y a menudo no puede.
Como ya hemos visto, Mateo encuentra profecías de los acontecimientos de la vida de Jesús en los lugares más insospechados. Aquí comete una equivocación. Mateo está citando de memoria; y la cita que hace no es de Jeremías, como dice, sino de Zacarías. Es de un extraño pasaje (Zac 11:10-14 ) en que el profeta nos dice que recibió una recompensa indignó y se la tiró al alfarero. En aquella antigua alegoría, Mateo vio un anuncio simbólico de lo que sucedió con el dinero de Judas.
Si Judas hubiera seguido fiel a Jesús, podría haber acabado su vida como un mártir; pero, como prefirió escoger su propio camino, fue su propia mano la que le causó la muerte. Se perdió la gloria de la corona del martirio para darse cuenta de que la vida le resultaba insoportable a causa de su pecado.
LA ÚLTIMA CENA
Como hemos ido recorriendo los pasajes que cuentan la historia de Judas, ahora tenemos que volver atrás al que nos relata la última Cena.</p>
<br/>
<p class="text-justify">EL HOMBRE QUE CONDENÓ A MUERTE
A JESÚS
Mateo 27:1-2, 11-26
Cuando se hizo de día, todos los principales sacerdotes y los ancianos del pueblo tuvieron una consulta para condenar a muerte a Jesús; así es que Le ataron y Le llevaron para entregársele al gobernador Pilato.
Jesús estaba de. pie ante. el gobernador, y este Le preguntó directamente:
-¿Eres Tú el Rey de los judíos?
-Tú eres el que lo has dicho -le contestó Jesús.
Mientras los principales sacerdotes y los ancianos Le
estaban acusando, Jesús no daba respuesta. Entonces Pilato Le preguntó:
-¿Es que no oyes la evidencia que estos están presentando contra Ti?
Jesús no contestó ni una sola palabra, lo que sorprendió mucho al gobernador.
Por el tiempo de la fiesta de la Pascua, el gobernador tenía costumbre de soltarle al pueblo a un preso, el que ellos quisieran. Por aquel entonces estaba detenido un preso muy conocido que se llamaba Barrabás. Así que, cuando estaban reunidos, les preguntó Pilato:
-¿A quién queréis que os suelte, a Barrabás o a Jesús al que llaman el Cristo?
Porque se daba perfecta cuenta de que le había entregado a Jesús maliciosamente. Mientras Pilato estaba sentado en el sillón del juicio, su mujer le envió un mensaje:
No te dejes enredar en nada que tenga que ver con este Justo -le decía ella-, porque hoy he tenido una experiencia extraordinaria en sueños en relación con Él.
Los principales sacerdotes y los ancianos convencieron al gentío que pidiera la liberación de Barrabás y la condena a muerte de Jesús.
-¿Cuál de los dos -dijo el gobernador- os tengo que soltar?
-¡Barrabás! -gritaron.
Entonces -les dijo Pilato-, ¿qué voy a hacer con Jesús, al que llaman el Cristo?
-¡Que Le crucifiquen! -dijeron todos.
-¿Qué crimen ha cometido? preguntó Pilato. Y la gente siguió gritando cada vez más:
-¡Que Le crucifiquen!
Cuando Pilato vio que no se podía hacer nada, y que había peligro de que se produjera un desorden, tomó agua y se lavó las manos en presencia de la gente.
-Vosotros veréis lo que hacéis.
-¡Que la responsabilidad de Su sangre recaiga sobre nosotros y sobre nuestros hijos! -contestó todo el pueblo.
Entonces Pilato les soltó a Barrabás, e hizo que azotaran a Jesús, y después Le entregó para que Le crucificaran.
Los dos primeros versículos de este pasaje describen lo que debe de haber -sido una reunión muy breve. del sanedrín,. celebrada de -madrugada con: la finalidad de formular una acusación oficial contra Jesús. Eso =era necesario debido al hecho de que, aunque los judíos podían juzgar casos ordinarios, no podían imponer la pena: de muerte. Esa sentencia solo la podía pronunciar el gobernador romano, y solo podían ejecutarla las autoridades romanas. El sanedrín, por tanto, tenía que formular una acusación con la que pudieran dirigirse a Pilato y solicitar la pena de muerte para Jesús.
Mateo no -nos dice cuál fue la acusación;.pero Lucas sí. En el sanedrín, la acusación que se había aceptado contra Jesús era la de blasfemia (Mat 26:65 s). Pero nadie sabía mejor que las autoridades judías que eso no era una acusación válida ante Pilato. Les diría que se marcharan y zanjaran solos sus desavenencias religiosas. Así que, como nos dice Lucas, se presentaron delante de Pilato con una triple acusación, cada una de cuyas partes era una mentira, y una mentira deliberada. Acusaron a Jesús, en primer lugar, de ser un revolucionario; en segundo, de incitar al pueblo a no pagar los impuestos, y en tercero, de presentarse como un rey (Luc 23:2 ). Pergeñaron tres acusaciones políticas, mentiras conscientes, porque sabían que esas eran las únicas que podían obligar a Pilato a actuar.
Así que todo dependía de la actitud de Pilato. ¿Qué clase de hombre era el gobernador romano?
Pilato era oficialmente el procurador de la provincia; y era responsable directamente, no. al senado romano, sino al mismo emperador. Tendría por lo menos treinta y siete años, porque esa era la edad mínima para hacerse cargo del puesto de procurador. Debe de haber sido un hombre de experiencia considerable; porque había toda una escala de cargos, incluyendo los de mando militar, por los que se tenía que ascender para poder llegar a ser gobernador. Pilato tiene que -haber sido un soldado y administrador probado y . cualificado. Llegó a ser procurador de Judasa en él año 26 d:C., y se mantuvo en oficio durante diez años, al final de los cuales fue depuesto.
Cuando Pilato llegó a Judasa, encontró problemas en abundancia, y otros muchos se los buscó él mismo. Su principal dificultad era que no les tenía absolutamente ninguna simpatía a los judíos. Por, el contrario, trataba despectivamente lo que consideraba prejuicios irracionales y fanáticos de sus súbditos, que. eran lo que ellos consideraban sus principios. Los Romanos conocían la intensidad de la religión judía, y el carácter irrompible de la fe judía, y muy sabiamente siempre habían tratado a los judíos con guante, blanco. Pilato propuso arrogantemente usar el guantelete.
Empezó con un problema. El cuartel general romano estaba en Cesarea. Los estandartes Romanos no eran simplemente banderas; eran palos largos con el águila romana o la imagen del emperador en el extremo. Por consideración con el odio judío a las imágenes, todos los anteriores gobernadores habían quitado las águilas y las imágenes de las banderas antes de entrar en Jerusalén para la visita oficial. Pilato se negó a quitarlas. El resultado fue una oposición y una intransigencia tales que Pilato tuvo que acabar por ceder; porque no era posible ni detener ni matar a toda una nación.
Más adelante, Pilato decidió que Jerusalén necesitaba un mejor sistema de conducción de agua una sabia decisión. Para ese fin construyó un nuevo acueducto =pero tomó dinero del tesoro del templo para pagarlo.
Filón, el gran filósofo Judasoalejandrino, hace un estudio psicológico de Pilato. Y Filón, recordemos, no era cristiano, sino que hablaba desde el punto de vista judío. Los judíos, nos dice Filón; habían amenazado con hacer uso de su derecho de delatar a Pilato al emperador por sus fechorías. Esta amenaza «exasperó a Pilato hasta lo sumo, porque se temía que enviaran una embajada al .emperador, que le. hicieran iniciar una investigación con respecto a otros detalles de su gobierno -su corrupción, sus actos de insolencia, su rapiña, su hábito de insultar al pueblo, su crueldad, sus constantes asesinatos de personas sin juicio ni condena y -su inhumanidad interminablemente gratuita y sádica.» La reputación de Pilato con los judíos apestaba; y el que pudieran delatarle le dejaba en una posición totalmente insegura.
Podemos seguir la carrera de Pilato hasta el final. Acabaron por llamarle a Roma para que rindiera cuentas de su brutalidad en un incidente de Samaria. Cierto impostor había citado al pueblo en el monte Gerizín pretendiendo que les mostraría las vasijas sagradas que Moisés había ocultado allí. Desgraciadamente, muchos de los asistentes vinieron armados, y se reunieron en una aldea llamada Tirabata. Pilato se lanzó sobre ellos y los masacró con un salvajismo totalmente innecesario, porque. se trataba de un movimiento inofensivo. Los samaritanos presentaron una queja a Vitelio; el legado de Siria, que era el superior inmediato de Pilato, y Vitelio le ordenó ir a Roma para responder de su conducta.
Cuando Pilato iba de camino a Roma, murió el emperador Tiberio; y parece ser que Pilato no tuvo que presentarse a juicio. Una leyenda dice que acabó cometiendo suicidio; su cuerpo se arrojó al Tíber, pero los espíritus malos revolvían las aguas de tal manera que los Romanos se llevaron el cuerpo de Pilato a Galia y lo tiraron al Ródano. La supuesta tumba de Pilato se enseña todavía en Vienne. Lo mismo sucedió allí, y el cuerpo se llevó por último a un lugar cerca de Lausana, y fue sepultado en un pozo de las montañas. Enfrente de Lucerna hay una colina que se llama el monte de Pilato. Originalmente se llamaba Pileatus, que quiere. decir con la cabeza cubierta de nubes; pero, como se conectó con Pilato, el nombre se cambió por el de Pilatus.
Más tarde, la leyenda cristiana mostró cierta compasión con Pilato, y acabó por echarle toda la culpa de la muerte de Jesús a los judíos. Naturalmente en cierto modo, la leyenda llegó a mantener que la mujer de Pilato, que se dice que era prosélita del judaísmo y que se llamaba Claudia Prócula, se convirtió al Cristianismo. También se llegó a decir que el mismo Pilato también se había hecho cristiano; y hasta el día de hoy la iglesia copta incluye a Pilato y a su mujer en el número de los santo:
Concluimos nuestros estudio de Pilato con un documento muy interesante. Pilato debe de haber enviado a Roma un informe del juicio y ejecución de Jesús; eso sería una parte normal de la administración. Un libro apócrifo llamado Los Hechos de Pilato y Pablo contiene una supuesta copia de ese informe. Ese informe lo citan también Tertuliano y Justino Mártir y Eusebio. El informe que ha llegado hasta nosotros no es probable que sea genuino, pero es interesante leerlo:
Poncio Pilato a Claudio: ¡Saludos!
Sucedió últimamente un asunto en el que yo mismo hice el juicio; porque los judíos, por envidia, se han castigado a sí mismos y a su posteridad con juicios terribles por su propia culpa; porque, aunque sus padres habían prometido que su Dios les enviaría del Cielo a Su Santo, Que debería ser Rey por derecho propio, y prometió que Él Le mandaría a la Tierra en nacimiento virginal; entonces vino cuando yo era gobernador de Judasa, y los judíos Le vieron dar vista a los ciegos, limpiar a los leprosos, sanar a los paralíticos, expulsar a los demonios, resucitar a los muertos, reprender a los vientos, andar sobre las olas del mar a pie enjuto y hacer muchas otras maravillas, y aunque todo el pueblo de los judíos Le llamaba Hijo de Dios, los principales sacerdotes, movidos por envidia contra Él, Le apresaron y me Le presentaron haciendo toda clase de falsas acusaciones una tras otra, diciendo que era hechicero y que hacía muchas cosas en contra de su ley.
Pero yo, creyendo que estas cosas eran ciertas, después de azotarle, Le entregué a su voluntad, y ellos Le crucificaron; y cuando Le enterraron pusieron una guardia al cuidado de la tumba. Pero mientras los soldados vigilaban, Él se levantó de nuevo al tercer día; sin embargo, hasta tal punto se inflamó la malicia de los judíos que les dieron dinero a los soldados diciéndoles: Vosotros decid que Sus discípulos robaron Su cuerpo. Pero ellos, aunque tomaron el dinero, no fueron capaces de guardar silencio acerca de lo que había sucedido, porque ellos también han testificado que Le vieron resucitado, y que recibieron, dinero de los judíos. Y de estas cosas he informado a vuestra alteza por esta causa, no sea que algún otro os mienta, y consideréis que debéis creer los falsos cuentos de los judíos.
Aunque ese informe no es más que una leyenda, Pilato sabía de cierto que Jesús era inocente; pero sus errores pasados pusieron en las manos de los judíos una palanca con la que le obligaron a hacer la voluntad de ellos contra los propios deseos y sentido de la justicia de él.
PILATO PIERDE LA CONTIENDA
Mateo 27:1-2, 11-26 (conclusión)
Todo este pasaje nos da la impresión de que Pilato estaba peleando una batalla perdida. Está claro que Pilato no quería condenar a Jesús. Ciertas verdades surgen de aquí.
(i) A Pilato le impresionó vivamente Jesús. Está claro que no tomó muy en serio que pretendiera ser el Rey de los judíos. Pilato reconocía a un revolucionario a primera vista, y Jesús no lo era. Su silencio digno hizo que Pilato sintiera que no era Jesús el que estaba en tela de juicio, sino él mismo, Pilato. Pilato fue un hombre que sintió el poder de Jesús -y tuvo miedo de someterse a El. Hay todavía personas que tienen miedo de ser tan cristianos como saben que deben serlo.
(ii) Pilato buscó la manera de evadir su responsabilidad. Parece que era costumbre soltar a un preso para la Pascua. En la cárcel había un cierto Barrabás. No era ningún ladronzuelo. Lo más probable es que fuera, o un bandolero, o un revolucionario político.
Se han hecho dos especulaciones interesantes acerca de él. Su nombre Bar-Abbás quiere decir Hijo del Padre. Padre era el título que se asignaba a los más respetados rabinos. Bien puede ser que Barrabás fuera hijo de una antigua familia distinguida, que se había salido del cauce tradicional y embarcado en una carrera de crímenes por todo lo alto. Un hombre así haría del crimen algo romántico, y tendría de su parte a una buena parte del pueblo.
Aún más interesante es la casi seguridad de que Barrabás también se llamara Jesús. Algunas de las más antiguas traducciones del Nuevo Testamento -por ejemplo, las antiguas versiones siríaca y armenia le llaman Jesús Barrabás; y tanto Orígenes como Jerónimo tenían noticia de esa variante y creían que podía ser correcta. Es curioso que por dos veces Pilato especifica que Jesús, al Que llaman el Cristo (versículos 17 y 22), como para distinguirle de algún otro Jesús. Jesús era un nombre corriente. Es el mismo que Josué en hebreo, y el grito frenético de la multitud es probable que fuera: &quot; ¡No Jesús el Cristo, sino Jesús Barrabás!»
Pilato buscaba una salida de emergencia, pero la multitud eligió al criminal violento y rechazó al tierno Jesús. Prefirieron al hombre de violencia al Hombre de Amor.
(iii) Pilato trató de zafarse de la responsabilidad de condenar a Jesús. Se conserva esa extraña y trágica ceremonia de Pilato lavándose las manos. Esa era una costumbre judía. Hay una extraña regla en Deu 21:1-9 . Si se encontraba un cadáver, y no se sabía quién lo había matado, se medía la proximidad del lugar con los pueblos cercanos, y los ancianos del pueblo más próximo tenían que sacrificar una becerra y lavarse las manos con su sangre para quedar libres de culpa. Pilato fue advertido por su sentido de la justicia, y por su conciencia, y por el sueño de su angustiada mujer; pero Pilato no podía resistir a la multitud; y Pilato recurrió al gesto estéril de lavarse las manos. La leyenda dice que hasta el día de hoy hay veces que la sombra de Pilato surge de su tumba y repite la ceremonia de lavarse las manos una vez más.
Hay algo de lo que una persona no puede librarse nunca -y es la responsabilidad. No es nunca posible ni para Pilato ni para ninguna otra persona el decir: &quot;Me lavo las manos de toda responsabilidad.» Porque eso es algo que nadie ni nada puede borrar.
Esta imagen de Pilato inspira en nuestras mentes más bien piedad que condenación; porque aquí tenemos a un hombre tan inmerso en su pasado y tan incapacitado por él que fue incapaz de mantenerse firme en su debida posición. Pilato es una figura de tragedia más que de villanía.</p>
<br/>
<p class="text-justify">LAS BURLAS DE LOS SOLDADOS
Mateo 27:27-31
Entonces los soldados del gobernador llevaron a Jesús a su cuartel, y reunieron allí a todo el destacamento. Le quitaron a Jesús lo que llevaba puesto, y Le pusieron la túnica púrpura de un solado; luego trenzaron una corona de espinos, y Se la pusieron en la cabeza, y Le colocaron una caña en la mano derecha; y doblaban la rodilla delante de Él, y se burlaban de Él diciendo:
-¡Salve, Rey de los judíos! -Y Le escupían, y Le quitaban la caña y Le golpeaban con ella en la cabeza.
Cuando se hubieron divertido con Él, Le quitaron la túnica, y Le pusieron Su propia ropa, y Le condujeron al lugar de la ejecución.
La terrible rutina de la crucifixión había comenzado. La última sección acababa diciéndonos que Pilato mandó que azotaran a Jesús. Eso era una terrible tortura romana. Desnudaban a la víctima; le ataban las manos a la espalda, y le ataban a una columna con la espalda doblada y convenientemente expuesta al látigo. El látigo era una tira larga de cuero en la que se ponían incrustado a trozos huesos agudos y piezas de plomo. Tal tortura solía preceder a la crucifixión, y «reducía el cuerpo desnudo del reo a tiras de carne cruda, y a sangrantes y ardientes verdugones.» Muchos morían en la tortura, y otros perdían la razón, y pocos se mantenían conscientes hasta el fin.
Después de eso entregaron a Jesús a los soldados mientras se preparaban los últimos detalles de la crucifixión y la cruz. Los soldados Le llevaron a su cuartel en la sede del gobernador, y reunieron a todo el destacamento. El destacamento se llama una speira; una speira completa ero seiscientos hombres. No es probable que hubiera tantos en Jerusalén. Estos soldados eran la guardia personal de Pilato, que le habían acompañado desde Cesarea, donde estaba su cuartel general.
Puede que nos horroricemos ante lo que hicieron los soldados; pero, de todos los que intervinieron en la pasión de Jesús, fueron los menos culpables. No estaban fijos en Jerusalén; no tenían ni la menor idea de Quién era Jesús. Por supuesto que no eran judíos, porque los judíos eran los únicos que estaban exentos del servicio militar en el imperio romano; puede que procedieran de los límites del imperio. Hicieron una parodia de la realeza de Jesús; pero, al contrario que los judíos y el mismo Pilato, actuaban en ignorancia.
Puede que para Jesús, de todo lo que sufrió, esto fuera lo más soportable; porque, aunque se burlaron de Su realeza, no había odio en sus ojos. Para ellos no se trataba más que de un iluso galileo que iba a la cruz. No carece de significado el que Filón nos cuente que un gentío judío hizo algo muy parecido con un joven demente: «Tomaron una tira de tela, y se la colocaron en la cabeza como si fuera una diadema... y le dieron como cetro una caña del junco nativo del papiro que se encontraron tirado al borde del camino. Y, como estaba disfrazado de rey... algunos se dirigían a él como para saludarle, y otros como para presentarle alguna demanda.» Así se divertían con un chaval medio idiota; y eso fue lo que los soldados hicieron con Jesús.
Seguidamente se prepararon para conducirle al lugar de la crucifixión. Algunas veces se nos dice que no debemos detenernos morbosamente en el aspecto físico de la crucifixión; pero no podemos hacernos una idea muy clara de lo que Jesús hizo y padeció por nosotros. Klausner, el escritor judío, dice: &quot; La crucifixión es la muerte más terrible y cruel que han diseñado los seres humanos para vengarse de sus semejantes.» Cicerón la llamaba &quot; la tortura más cruel y más horrible.» Tácito la llamaba &quot; una tortura apropiada solo para esclavos.»
La inventaron en Persia; y puede que su razón de ser fuera que la tierra se consideraba consagrada al dios Ormuz, así que el criminal se colocaba fuera del contacto con ella, para que no la contaminara; porque era la propiedad del Dios. De Persia pasó a Cartago en el Norte de África, y fue de los cartagineses de los que la aprendieron los Romanos, aunque estos no la aplicaban más que a los rebeldes, esclavos fugitivos y la clase más baja de criminales. Era una ejecución que no se podía aplicar legalmente a un ciudadano romano.
Klausner pasa a describir la crucifixión. Se ataba a la cruz al criminal, que ya era una masa sangrante después de los azotes. Allí colgaba hasta morir de hambre y sed y exposición a la intemperie, incapaz de defenderse ni siquiera de los tábanos, que acudían a su cuerpo desnudo y a sus heridas sangrantes. No es una escena agradable de contemplar, sino horrible la que Jesucristo sufrió -voluntariamente- por nosotros.</p>
<br/>
<p class="text-justify">LA CRUZ Y LA VERGÜENZA
Mateo 27:32-44
Cuando iban saliendo, se encontraron a un cireneo que se llamaba Simón, y le requisaron para que llevara la Cruz de Jesús. Cuando llegaron al lugar que se llama Gólgota (que quiere decir El lugar de la Calavera), Le ofrecieron vino mezclado con hiel para que lo bebiera; pero, cuando Jesús lo probó, no quiso seguir bebiendo. Cuando ya Le habían crucificado, se repartieron Su ropa echándola a suertes; y, allí sentados, Le observaban. Habían colocado sobre Su cabeza un cartel escrito con la acusación por la que Le ajusticiaban: «Este es Jesús, el Rey de los judíos.&quot; Luego crucificaron a dos malhechores, uno a Su derecha y otro a Su izquierda. Los que pasaban por allí no hacían más que lanzarle insultos. No hacían más que sacudir la cabeza y decir:
-¡El que destruías el templo y lo edificabas en tres días: Sálvate a Ti mismo! ¡Si eres de veras el Hijo de Dios, bájate de la Cruz!
Lo mismo hacían los principales sacerdotes y los escribas y los ancianos burlándose de Él:
-¡Salvó a otros -no hacían más que decir-, y no se puede salvar a Sí mismo! ¡El Rey de Israel! ¡Que baje ahora de la Cruz, y creeremos en Él! ¡Confió en Dios: Que Dios Le libre ahora si Le quiere; porque Él dijo: «Yo soy el Hijo de Dios»!
Hasta los bandidos que estaban crucificados con Él Le lanzaban los mismos oprobios.
La historia de la crucifixión no necesita comentario; todo su poder reside sencillamente en contarla. Lo único que podemos hacer es pintar su trasfondo para que el cuadro aparezca lo más claro posible.
Cuando se había condenado a un criminal, se le conducía al lugar de la crucifixión. Se le colocaba entre cuatro soldados Romanos. Era costumbre que llevara el travesaño de su propia cruz; el madero vertical le estaba esperando en el lugar de la ejecución. El crimen por el que se le ejecutaba estaba escrito en un tablero; lo llevaba el reo colgado al cuello, o lo exponía el oficial que iba al frente de la procesión; más tarde se colocaba sobre la misma cruz. Al criminal se le conducía a la muerte por un camino lo más largo posible para que pudieran verle y escarmentar en él los más posibles.
Jesús ya había pasado los terribles azotes; después, había soportado las burlas de los soldados; antes de todo eso, le habían estado interrogando casi toda la noche; estaba, por tanto, físicamente agotado, y vacilaba bajo el peso de la Cruz. Los soldados Romanos sabían muy bien lo que podían hacer en tales circunstancias. Palestina era una tierra ocupada; todo lo que un oficial tenía que hacer era tocarle el hombro con lo plano de su lanza a un judío para confiscarle para el servicio que fuera, y este tenía que realizar cualquier tarea, por muy humillante y desagradable que fuera. Hacia la ciudad, de una de las aldeas próximas, llegaba entonces, un hombre de la lejana Cirene, en el Norte de África, que se llamaba Simón. Puede que se hubiera pasado años economizando y ahorrando para celebrar una Pascua en Jerusalén -y ahora le correspondía asumir esta terrible indignidad y vergüenza, porque se le obligaba a llevar la Cruz de Jesús. Cuando Marcos nos cuenta este episodio, identifica a Simón como «el padre de Alejandro y de Rufo&quot; (Mar 15:21 ). tal identificación solo puede querer decir que Alejandro y Rufo eran conocidos en la Iglesia. Y puede ser que aquel día terrible, Jesús tomó posesión del corazón de Simón. Que aquello que le había parecido a Simón la mayor vergüenza llegó a ser para él su mayor gloria.
El lugar de la crucifixión fue una colina llamada Gólgota, porque tenía la forma de una calavera. Cuando se llegaba al lugar de la ejecución, al criminal se le colgaba de la cruz. Se le clavaban las manos al travesaño, pero lo corriente era que se le ataran los pies a la cruz. En ese momento, para matar un poco el dolor, se le daba al criminal un vino drogado, preparado por un grupo de mujeres ricas de Jerusalén como obra de misericordia. Un escritor judío escribe: «Cuando se saca a un hombre para matarle, le permiten beber un grano de incienso en una copa de vino para amortiguar sus sentidos... Mujeres ricas de Jerusalén solían aportar estas cosas y ofrecerlas.» La copa drogada se le ofreció a Jesús, pero Él no quiso beberla porque estaba decidido a acatar la muerte en todo su horror y amargura, sin evitar ninguna partícula de dolor.
Ya hemos visto que el criminal se le conducía a la ejecución en moho de cuatro soldados Romanos; a los criminales se los crucificaba desnudos, excepto por un paño en los lomos; y las ropas del criminal eran el gaje al que tenían derecho los soldados encargados de la ejecución. Los judíos llevaban normalmente cinco artículos de ropa: las sandalias, el turbante, el cinto, la túnica interior y la capa exterior. Así es que había cinco artículos para cuatro soldados. Los primeros cuatro artículos tenían aproximadamente el mismo valor; pero la capa exterior tenía más valor que las otras piezas. Fue esa túnica exterior de Jesús la que los soldados se jugaron a los dados, como nos dice Juan (Jua 19:23 s). Cuando los soldados se había repartido la ropa de Jesús, se sentaron, montando la guardia hasta que llegara el final. Así es que había en Gólgota un grupo de tres cruces, en la de en medio el Hijo de Dios, y a cada lado un bandolero. Cierto que estuvo con los pecadores en Su muerte. Los versículos finales describen las burlas que Le lanzaban a Jesús los que pasaban, las autoridades judías y hasta los bandoleros que estaban crucificados con Él. Todas las burlas se centraban en una cosa: La afirmación que Jesús había hecho, y Su obvia indefensión en la Cruz. Precisamente en eso era en lo que más se equivocaron los judíos. Estaban usando la gloria de Cristo como un objeto de burla. &quot;¡Baja de la Cruz -Le decían-, y creeremos en Ti!» Pero como dijo una vez el general Booth: «Es precisamente porque no quiso bajar, por lo que creemos en Él.» Los judíos no veían a Dios nada más que en el poder; pero Jesús nos ha mostrado que Dios está en el amor sacrificial.</p>
<br/>
<p class="text-justify">EL TRIUNFO FINAL
Mateo 27:45-50
Desde las doce del mediodía cubrieron la tierra las tinieblas hasta las tres de la tarde. A eso de las tres de la tarde, Jesús clamó a gran voz:
-El¡, El¡, ¿lama sabajthuni? -(Que quiere decir: &quot; Dios mío, Dios mío, ¿por qué Me has desamparado?»).
Algunos de los que se encontraban allí, oyeron esto y dijeron:
-Este Hombre está llamando a Elías.E inmediatamente uno de ellos fue corriendo, y tomó una esponja, y la empapó de vinagre, y la puso en una caña, y Le dio de beber. Los demás dijeron:-¡Déjale, a ver si viene Elías a salvarle!
Jesús clamó otra vez a gran voz, y entregó el espíritu.
Conforme hemos estado leyendo la historia de la Crucifixión, todo parece haber estado pasando muy deprisa; pero en realidad las horas iban resbalando. Marcos es el más preciso en relación con el tiempo. Nos dice que Jesús fue crucificado a la hora tercera, es decir, las 9 de la mañana (Mar 15:25 ), y que murió a la hora novena, es decir, las 3 de la tarde (Mar 15:34 ). Es decir: Jesús estuvo clavado en la Cruz seis horas. Para Él, la agonía fue misericordiosamente breve, porque se daba el caso de que algunos criminales estuvieran colgando de sus cruces varios días hasta que les llegaba la muerte.
En el versículo 46 tenemos lo que tiene que haber sido la frase más alucinante de toda la historia evangélica: El grito de Jesús: «Dios mío, Dios mío, ¿por qué Me has desamparado?» Este es un dicho ante el que debemos postrarnos en reverencia, aunque también debemos tratar de comprenderlo. Ha habido muchos intentos de penetrar en su misterio; solo podemos considerar tres de ellos.
(i) Es extraña la manera en que el Salmo 22 fluye por toda la narración de la Crucifixión; y esta palabra es de hecho el primer versículo de ese Salmo. Más tarde dice: «Todos los que Me buscan se burlan de. Mí; tuercen la boca y menean la cabeza, diciendo: &quot;Él apeló al Señor, líbrele El; sálvele, si es verdad que Se deleita en Él&quot;» (Sal 22:7 s). Y todavía más adelante leemos: «Se repartieron entre ellos Mis vestidos, y se jugaron mi ropa a los dados» (Sal 22:18 ). El Salmo 22 está entretejido en la misma historia de la Crucifixión.
Se ha sugerido que Jesús estaba de hecho repitiendo ese Salmo para Sí; y aunque empieza con un grito de abatimiento, acaba remontándose en triunfo: «De Ti viene Mi alabanza en la congregación... porque el dominio pertenece al Señor, y El gobierna sobre las naciones» (Sal 22:25-31 ). Así que se sugiere que Jesús estaba repitiendo el Salmo 22 en la Cruz como una descripción de Su situación y como canción de alabanza, sabiendo muy bien que empezaba en las profundidades y acababa en las alturas.
Es una sugerencia atractiva; pero un crucificado no recita poesía ni para sus adentros; aunque sea la poesía de un Salmo; y además, toda la atmósfera es de tragedia despiadada.
(ii) Se sugiere que en ese momento todo el peso del pecado del mundo cayó sobre el corazón y el ser de Jesús; que ese fue el momento en que el Que no conoció pecado fue hecho pecado por nosotros (2Co 5:21 ); y que el castigo que Él sufrió por nosotros implicó la inevitable separación de Dios que produce el pecado. Nadie puede decir que eso no fuera verdad; pero, si lo es, es un misterio que no podemos más que vislumbrar, y ante el que solo podemos adorar.
(iii) Puede ser que haya algo aquí -si podemos decirlo así- más humano. A mí me parece que Jesús no sería Jesús si no hubiera sondeado las simas más profundas de la experiencia humana. En la experiencia humana, en él transcurso de la vida, cuando las más amargas tragedias la invaden, hay momentos cuando nos parece sentir que Dios Se ha olvidado de nosotros; cuando estamos inmersos en una situación que sobrepasa nuestro entendimiento y nos sentimos abandonados hasta de Dios. A mí me parece que eso fue lo que Le sucedió a Jesús aquí. Ya hemos visto que en Getsemaní Jesús sólo sabía que tenía que seguir adelante, porque esa era la voluntad de Dios, y Él tenía que aceptar hasta lo que no podía comprender totalmente. Aquí vemos a Jesús sondeando las más negras profundidades de la situación humana, para que no hubiera ninguna de la que pudiéramos decir que Él no la pasó antes que nosotros.
Los que Le oyeron, no Le comprendieron: Algunos creyeron que estaba llamando a Elías; esos serían judíos. En los escritos del Mar Muerto se encuentran ejemplos que parecen indicar que «Elí, Elí&quot; se podría pronunciar «Elía, Elía.» Tal vez Jesús pronunció el versículo en su dialecto galileo del arameo. Pero también puede ser que entendieran perfectamente que estaba usando palabras de la Sagrada Escritura, y hasta en eso se burlaron de Él.
Uno de los grandes dioses del paganismo era el Sol -Helios. Una invocación al dios Sol habría empezado: «¡Helie!,» y se ha sugerido que los soldados puede que pensaran que Jesús estaba llamando al más grande de sus dioses, que había oscurecido su rostro de espanto ante aquella escena. En cualquier caso, el clamor de Jesús fue un misterio para los espectadores.
Pero aquí hay algo importante. Habría sido terrible el que Jesús hubiera muerto con un grito de angustia en Sus labios; pero no fue así. La narración evangélica prosigue diciéndonos que, cuando Jesús clamó con una gran voz, entregó Su espíritu. Esa gran voz dejó. su impronta en las mentes de los testigos. Está en todos los evangelios (Mat 27:50 ; Mar 15:37 ; Luc 23:46 ). Pero hay un evangelio que llega más allá: Juan nos dice que Jesús murió dando un gran grito: «¡Consumado es!» (Jua 19:30 ). Consumado es son dos palabras en español, pero en griego es solo una: Tetélestai -como sería también en arameo. Y tetélestai es un grito de triunfo; es el grito de Uno Que ha completado Su tarea; es el grito del Que ha vencido en la contienda; es el grito de la Persona Que ha salido de las tinieblas a la gloria de la luz, y Que ha alcanzado la corona. Así es que Jesús murió como vencedor, con un grito de triunfo en los labios.
Aquí tenemos algo de valor incalculable. Jesús pasó por el abismo más insondable, y salió de nuevo a la luz. Nosotros también, si nos aferramos a Dios aun cuando parece que no hay Dios, manteniendo los restos de nuestra -fe desesperada e invenciblemente, no cabe duda que la aurora romperá y saldremos victoriosos. El vencedor es el que se niega a creer que Dios Se ha olvidado de él aun cuando todas las fibras de su ser se sientan abandonadas. Vencedor es aquel que no, deja que se le pierda nunca la fe, aun cuando sienta que ya ha perdido toda su base. Vencedor, es, el que se ha sumido hasta las profundidades, y todavía se aferra a Dios; porque eso es lo que hizo Jesús.</p>
<br/>
<p class="text-justify">LA REVELACIÓN DESLUMBRANTE
Mateo 27:51-56
Y fijaos: El velo del templo se rasgó en dos parte, de arriba abajo, y la tierra se sacudió, y las rocas se quebraran, y las tumbas se abrieron, y resucitaron. dos Y cuerpos, de muchos de los que habían vivido consagrados a Dios, y salieron de las tumbas después de Su Resurrección y vinieron ala. Santa Ciudad y se les aparecieron a muchos.
El centurión y los que estaban observando. a Jesús con él vieron el terremoto y las cosas que habían sucedido, y sintieron un profundísimo temor. No cabe duda -decían-, que este. Hombre era el Hijo de Dios. Muchas mujeres estaban allí observando a distancia.
Eran las mujeres que habían seguido a Jesús desde Galilea, prestándole sus servicios. Entre ellas estaban María de Magdala, y María, la madre de Santiago y de José, y la madre de los hijos de Zebedeo.
Este pasaje se divide naturalmente en tres secciones.
(i) Tenemos .el relato de las cosas sorprendentes que sucedieron cuando murió Jesús. Ya las tomemos literalmente o no, nos enseñan dos grandes verdades.
(a) El velo del templo se rasgó de arriba abajo. Ese era el velo que cubría la entrada del Lugar Santísimo, al otro lado del cual no podía entrar más que el sumo sacerdote el día de la Expiación; era el velo que, ocultaba la presencia del Espíritu de Dios: Aquí hay un profundo simbolismo. Hasta ese momento, Dios había estado oculto y remoto, y nadie sabía cómo era. Pero, en la muerte de Jesús vemos el amor oculto de Dios, y el acceso a la presencia de Dios qué había estado cerrado a toda la humanidad está ahora abierto.. La vida y la muerte de Jesús nos muestran cómo es Dios, y quitan para siempre el velo que Le ocultaba a la humanidad.
(b) Se abrieron las tumbas. La verdad que esto nos revela es que Jesús conquistó la muerte. Al morir y resucitar, Él destruyó el poder de la tumba. A causa de Su vida, Su muerte y Su Resurrección, la tumba ha perdido su poder, el sepulcro ha perdido su terror, la muerte ha perdido su tragedia. Porque estamos seguros de que, como Él vive, nosotros también viviremos:
(ii) Tenemos el relato, de la adoración del centurión. Jesús había dicho: &quot;Yo, cuando sea levantado de la tierra, atraeré a Mí a todas las personas» (Jua 12:32 ). Jesús anunció el poder magnético de la Cruz; y el centurión fue su primer fruto. La Cruz le movió a ver la majestad- de Jesús, como ninguna otra cosa le había movido.
(iii) Tenemos la sencilla mención de las mujeres que vieron el final. Todos los discípulos Le abandonaron y huyeron, pero las, mujeres se mantuvieron. Se ha dicho que, al contrario que los hombres, las mujeres no tenían nada que temer, porque su posición pública era tan poco importante que nadie se fijaría en las discípulas. Pero á más que eso. Estaban allí porque amaban a Jesús; y para ellas, como para tantos otros, el perfecto amor desecha el temor.</p>
<br/>
<p class="text-justify">EL REGALO DE UNA TUMBA
Mateo 27:57-61
Más adelante aquel mismo día vino un hombre rico de Arimatea que se llamaba José, que era un discípulo de Jesús. Se dirigió a Pilato, y le pidió el cuerpo de Jesús. Pilato ordenó que se le diera; así es que José tomó el cuerpo, y lo envolvió en lino limpio, y lo puso en una tumba nueva que había abierto en la roca. Y rodó una piedra muy grande para cerrar la entrada de la tumba, y se marchó. Y María de Magdalena estaba allí, y la otra María, sentadas enfrente de la tumba.
Según la ley judía, ni siquiera el cuerpo de un criminal debía dejarse expuesto toda la noche, sino que tenía que, enterrarse el -mismo día. «Su cuerpo no permanecerá toda la noche sobre el madero, sino que lo enterraréis el mismo día&quot; (Deu 21:22 s). Esto era doblemente obligatorio cuando, tomo en el caso de Jesús, el día siguiente era sábado. Según la ley romana, los parientes de un criminal podían solicitar su cuerpo para enterrarlo; y si no lo solicitaba nadie se dejaba a merced de los perros y de los animales carroñeros..
Ahora bien, ninguno de los parientes de Jesús estaba en posición de reclamar Su cuerpo, porque eran todos galileos, y ninguno tenía una tumba en Jerusalén. Así que el pudiente José de Arimatea intervino. Se dirigió a Pilato y solicitó que le permitiera hacerse cargo del cuerpo de Jesús. Se le concedió, y lo puso en una tumba en la roca en la que no se había enterrado a nadie. José será siempre recordado como el hombre que Le dio una tumba a Jesús.
Han surgido muchas leyendas en torno a la figura de José de Arimatea, algunas de las cuales tienen un interés especial para los ingleses. La más conocida dice que en el año 61 d C., Felipe envió a José, desde la Galia, a predicar el Evangelio en Inglaterra. José fue, llevando consigo el cáliz que se usó en la Última Cena, y que entonces contenía la sangre que Jesús derramó en la Cruz. Ese cáliz llegaría a ser conocido como el Santo Grial, famoso en las historias de los caballeros del rey Arturo. Cuando José y su grupo de misioneros escalaron la colina Weary-all y llegaron al otro lado, se encontraron en Glastonbury; allí José pinchó su bordón en la tierra, -y de él creció el famoso espino de Glastonbury. Es absolutamente cierto que Glastonbury fue mucho tiempo el lugar más sagrado de Inglaterra, y todavía es un centro de peregrinación. La leyenda dice que el espinó original lo taló un puritano, pero que el espino que crece allí hasta el día de hoy brotó de la misma raíz antigua; y hasta el día de hoy se mandan esquejes de él por todo el mundo. Así que la leyenda conecta a José de Arimatea con Glastonbury e Inglaterra.
Pero hay una leyenda menos conocida, recordada en uno de los himnos y poemas más famosos de la literatura inglesa. Es una leyenda todavía muy viva en Somerset. José, dice la leyenda, era mercader de estaño, y vino mucho antes dé que le enviara Felipe en visitas frecuentes a las minas de estaño de Cornwall. El pueblo de Marazion en Cornwall tiene otro nombre: algunas veces se le llama Market Jew, «el judío del mercado», y se dice que fue el centro de una colonia de judíos que eran mercaderes de estaño. La leyenda llega más lejos: José de Arimatea, nos dice, era tío de María la Madre de Jesús. (¿Podría ser que José hiciera uso del derecho que le concedía la ley romana de reclamar el cuerpo de Jesús porque era pariente Suyo?). Y se dice que trajo al niño Jesús consigo en uno de sus viajes a Cornwall. Es una preciosa leyenda que nos gustaría que fuera verdad -sobre todo a los ingleses- porque sería emocionante pensar que los pies del niño Jesús tocaron en tiempos la tierra inglesa.
Se dice muchas veces que José le dio una tumba a Jesús cuando murió, pero no le acercó durante Su vida. José era miembro del sanedrín (Luc 23:50 ); y Lucas nos dice que no había dado su conformidad al plan y a la acción (del tribunal) (Luc 23:51 . Es posible que la reunión del sanedrín que se convocó en la casa de Caifás durante la noche fuera selectiva. No parece probable que todo el sanedrín estuviera allí. Bien puede ser que Caifás citara solamente a los que quería que estuvieran presentes, los que estaba seguro de que le apoyarían, y que José no tuviera oportunidad de estar allí.
No cabe duda de que al final José desplegó el mayor valor. Se manifestó como simpatizante de un criminal crucificado; arrostró el resentimiento posible de Pilato; y también el previsible odio de los judíos. Bien puede ser que José de Arimatea hiciera todo lo que le fue posible hacer.
Todavía queda una incógnita. La mujer que se llama la otra María se identifica como María la madre de José en Mar 15:47 . Ya hemos visto que estas mujeres estuvieron presentes en Gólgota; su amor les hizo seguir a Jesús en la vida y en la muerte.</p>
<br/>
<p class="text-justify">UNA TAREA IMPOSIBLE
Mateo 27:62-66
AL día siguiente, que era el día después de la Preparación, los principales sacerdotes y los fariseos vinieron a una a Pilato.
-Señor -le dijeron-, recordamos que ese impostor decía cuando estaba vivo: «A los tres días, resucitaré.&quot; Da órdenes, por tanto, para que la tumba esté vigilada hasta después de los tres días, no sea que vengan. Sus discípulos, y roben el cuerpo, y digan luego a la gente: «Ha resucitado de entre los muertos.» Si pasara eso, el engaño final sería peor que el primero.
-Contáis con una guardia -dijo Pilato-. Id, y aseguradla lo más posible.
Ellos fueron y aseguraron la tumba poniéndole un sello en la entrada y dejando allí la guardia.
Este pasaje empieza de una manera muy curiosa. Dice que los principales sacerdotes y los fariseos se dirigieron a Pilato al día siguiente, que era el día después de la Preparación. Ahora bien: Jesús fue crucificado el viernes. El sábado era el día de descanso de los judíos. Las horas desde las 3 hasta las 6 de la tarde del viernes se llamaban la víspera o la preparación. Ya hemos visto que, según la manera judía de contar, el nuevo día empezaba a las 6 de la tarde. Por tanto, el sábado empezaba a las 6 de la tarde del viernes, y las últimas horas del viernes eran la preparación. Si esto es exacto, solo puede querer decir una cosa: que los principales sacerdotes y los fariseos se dirigieron de hecho a Pilato con su petición el sábado. Si fue eso lo que hicieron, está claro que quebrantaron la ley del sábado. Si esto es exacto, no hay ningún otro incidente en la historia evangélica que muestre más claramente que este lo desesperadamente ansiosas que estaban las autoridades judías en eliminar a Jesús. A fin de asegurarse de que estaba definitivamente fuera de su camino, estaban dispuestos a quebrantar hasta sus leyes más sagradas.
Aquí hay una ironía macabra. Estos judíos acudieron a Pilato diciéndole que Jesús había dicho que resucitaría a los tres días. No reconocían haber tenido en cuenta la posibilidad de que pudiera ser cierto; pero creían que los discípulos podían ingeniárselas para robar el cuerpo, y decir que había resucitado. Ellos, por tanto, querían tomar medidas para vigilar la tumba. La respuesta de Pilato fue complaciente: «Aseguraos todo lo que podáis.» Es como si Pilato, desde luego inconscientemente, dijera: «Mantened a Cristo en la tumba -si podéis.»
Ellos tomaron todas las medidas que pudieron. La entrada de estas tumbas en la roca se cerraba con una gran piedra redonda, como de molino, que se rodaba por un surco. Ellos la sellaron, y colocaron allí una guardia especial. No se habían dado cuenta de que no había tumba en el mundo que pudiera retener al Cristo Resucitado. Todos los planes humanos no podrían atar al Señor Resucitado. El intentar ponerle ligaduras a Jesucristo es una tarea desesperada.</p>
<br/>




</div>
