<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Mateo 1</h2>
<p class="text-justify">[1] El Nombre Verdadero de El Hijo Único de YHWH, recobrado como inicialmente apareció anterior a Sus días en la tierra, signficando YHWH quien hace la salvación. El uso de Yahoshua a diferencia de Y’shua, o Yahshua como el nombre de Moshiaj, grandemente depende en el contexto histórico. Para las Escrituras de Restauración Edición Del Nombre Verdadero, hemos optado por Yahoshua porque en términos de nuestra investigación, ésta era la forma que el Nombre tenía en términos de previo a la cautividad en Babilonia, al igual que su conexión clara en las Escrituras proféticas, tales como en Zac 6:11-12. Añada a eso el hecho que Yahshua vino en el nombre de Su Padre, que más obviamente contiene la letra hey como en Yahoshua. Sin embargo, en términos de lo que Moshiaj fue realmente llamado en el tiempo de Su primer advenimiento, ambos la Peshitta Aramea y los textos Antiguos Siríacos se refieren a El como yud-shen-vav-ayin en lugar de yud hey vav shen ayin. Hemos optado por el nombre completo incluyendo la letra hey como fue revelado anterior a la corrupción.
[2] La vav antigua pronunciada whh y no ve.
[3] Una Israelita no biológica y una prostituta por añadidura es considerada una Israelita porque ella voluntariamente se unió a Israel y realizó la orden de esconder a los espías. Ella es honrada como una Israelita al ser colocada en el linaje de Moshiaj.
[4] Rut llegó a ser una madre en Israel como una Israelita en el linaje de Moshiaj, sin embargo nunca fue considerada Judía.
[5] Urías fue un Heteo y sin embargo su esposa es considerada una Israelita, como lo fue él, ya que incluso él estaba en el ejército de David.
[6] En realidad aquí Mateo exluye a tres descendientes de Josofat (Ocozías, Joás, y Amasías), porque el hijo de Josofat, Joram, se casó con la hija del maldito Rey Acab (marido de Jezabel de la Casa de Israel) (2Cr 18:1, 2Cr 21:1, 2Cr 21:4-7). Así que mientras que YHWH no maldijo a la Casa entera de Judah, El sí maldijo a la Casa de Acab, y al entrar en matrimonio con la Casa de Acab, Joram trajo líneas sanguineas malditas dentro de la Casa de Judah, o el linaje de Solomón. Como tal, YHWH maldijo a tres generaciones del prole de Joram sin maldecir al linaje entero para siempre como visto en Exo 20:4-5, donde YHWH permite ese tipo de maldición por sólo tres generaciones antes de que sea levantada. Así que mientras ellos sí son contados, o registrados físicamente en otro lugar, ellos no pueden ser considerados ancestros de Moshiaj. Si Mateo hubiese incluído a los tres reyes que faltan tal como la mayoría del los anti-misioneros quieren que haga (Ocozías, Joás, y Amasías), su genealogía sería inválida y la mayoría de los Judíos lo habrían ridiculizado hasta menospreciarlo. Así que los así llamados tres reyes perdidos no están faltando en absoluto. YHWH a través de Mateo intencionalmente los excluye.
[7] YHWH maldijo a Conías en Jer 22:24-30. Esa maldición fue claramente levantada en su nieto Zorobabel, como fue confirmado por YHWH a través de Hageo en el capítulo 2 versos 20-23. En esos versos el sello de la sortija real de favor regio quitado de Conías es devuelto a Zorobabel. Además, la maldición fue para que Conías se quedara sin tener hijos, la cual vemos fue revertida ya que él ciertamente tuvo hijos. Este obstáculo para que Yahshua fuera Moshiaj ya no existe y fue quitado unos 500 años antes de Su nacimiento.
[8] El término Arameo gowra está mal traducido como “esposo” en todos los manuscritos Griegos. Gowra en contexto apropiado es un guardián, o un guardián legal, o tutor legal, como visto en la Torah en Deu 25:5-6 donde a los Israelitas se les ordena establecer un gowra, o un guardián legal. Lo más probable es que este José tomó el lugar del padre fallecido de María y llegó a ser su gowra como Booz lo hizo en Rut 2:20, donde él es llamado el gowra para Rut en el Targum Arameo. (Booz era el gowra de Rut antes de que él llegara a ser su esposo.) Este José (en el verso 16) fue el tutor legal de María. En el verso 19, sin embargo, la palabra Aramea/Hebrea es baalah que solamente puede significar “esposo.” La Peshitta Aramea claramente usa las dos palabras diferentes (gowra y baalah) para mostrar que un José (en el verso 16) era el tutor de María, mientras que el otro José (en el verso 19) era el marido de María. Con esta aclaración, vemos que verdaderamente hay 14 generaciones desde la cautividad Babilónica hasta el nacimiento de Yahshua (de acuerdo con la insistencia audaz de Mateo en el verso 17 que hay tres conjuntos de 14 generaciones), versus sólo 13 si los dos Josés hubiesen sido considerados como el mismo. Si contamos a José el gowra/tutor legal como #12, María como #13 y Yahshua como #14, tenemos un conjunto perfecto de 14. Por lo tanto esta genealogía es claramente la genealogía de María y no de José. Para poder ser el Moshiach, Yahshua tenía que heredar el trono de Solomón - no de Natán como enseña la Cristiandad. Natán nunca se sentó en el trono, y las muchas profecías de David indican que el linaje de el Moshiach sería solamente a través de Solomón y nunca a través de otro de sus hijos. Por lo tanto el relato de Lucas no da la genealogía de María, mientras que el relato de Mateo sí da la genealogía de María, ya que él cuenta a María como la número 13 en el conjunto final de 14, así permitiendo que el verso 17 haga sentido perfecto. Uno puede captar ésto sólo en el texto de la Peshitta Aramea, el cual no es sólamente el texto de primacía del cual todas las traducciones Griegas han venido, sino que también es el único que hace diferencia entre gowra y baalah.
[1] La gematría, o el valor numérico de David en Hebreo es 14. Los tres conjuntos de 14 indican que Yahshua es de la Casa real de David. Como visto en la nota de estudio # 5, cuando se usa la Peshitta Aramea, uno puede ver que habían tres conjuntos perfectos de 14, suprimiendo a los tres reyes malditos junto con el hacer distinción entre José el tutor legal y el José subsecuente, el esposo.
[2] Mateo ahora ha terminado con las genealogías del pasado habiendo establecido su argumento, y ahora cambia al futuro, separando aún más a los dos Josés después de haber hecho una suma neta del pasado en el verso 17.
[3] En ningún momento es este José el baalah, o esposo de María, alguna vez llamado el padre de Yahshua.
[4] Véase la nota de estudio en el verso 16 arriba.
[5] Mar-Yah, o Adon Yah en el Arameo propio.
[6] Israel.
[7] Almah en Hebreo, y parthenos en Griego y betulah en Arameo.
[8] Los “ellos” a quienes se refiere Mateo son los Judíos quienes esperaban al largamente anhelado Moshiaj, como Rashi y otros sabios han afirmado. La palabra “ellos” que menciona Mateo también es un eufemismo para los “profetas de Israel.”
[9] Un título, no un nombre. Los Judíos estaban esperando una visitación sobrenatural, y no a alguien con un nombre como “Immanu-El Glickstein.” Mateo, operando en el nivel remez/indicio de PaRDeS, toma la libertad de decir que a través de este nacimiento virginal, el concepto largamente sostenido de Moshiaj finalmente tomaría lugar - no que vendría un bebé que de hecho se llamará “Immanu-El.” Además, el título Hebreo contiene dos palabras más pequeñas (“Emanu” y “El”). Todos los profetas de Israel creían que Moshiaj era eterno (“El”) y que Moshiaj vendría a Israel (“Emanu,” o “con nosotros” en Israel) - confirmando aún más un concepto y no un nombre propio para Moshiaj.
[10] Un sustantivo propio personal, o nombre no puede ser interpretado, sino que tiene que ser transliterado. Pero el título común Emanu-El sí puede ser y es interpretado aquí.</p>
<br/>




</div>
