<div id="close_comentario"><span>×</span></div><div class="small-12 columns">
<h2 class="text-center">Génesis 1</h2>
<p class="text-justify">Footnotes:
[1] 1.1 Creó : Hebreos bará. En el AT, este verbo tiene por sujeto únicamente a Dios y se refiere siempre a una acción divina que produce un resultado nuevo e imprevisible (Is 48.6-7; Jer 31.22). Se emplea para designar la creación del mundo y de la humanidad (Gn 1.27; 5.1; Dt 4.32; Is 45.12), la formación del pueblo de Israel (Is 43.1,15), la restauración de Jerusalén (Is 65.18), la renovación interior del pecador arrepentido y perdonado (Sal 51.10) y la creación, al final de los tiempos, de un cielo nuevo y una tierra nueva (Is 65.17; 66.22).
[2] 1.1 Los antiguos Hebreos no poseían un término equivalente al gr. cosmos. El universo en su totalidad era designado con la expresión el cielo y la tierra (cf. Gn 14.22; Sal 124.8; Mt 28.18). En el uso de esta expresión se refleja la costumbre semítica de abarcar una totalidad mencionando dos elementos extremos u opuestos (cf. Gn 2.9).
[3] 1.2 Las tinieblas... sobre la faz del abismo : Otra posible traducción: Todo era un mar profundo cubierto de oscuridad. Según una idea muy difundida entre los pueblos del antiguo Oriente, antes de la creación solo había un caos de tinieblas que lo cubrían todo como aguas amenazantes (cf. Sal 104.6-9). Por lo tanto, una de las primeras acciones del Creador consistió en separar las aguas de arriba y las de abajo, poniendo como línea divisoria la expansión o bóveda celeste (v. 7). De acuerdo con los v. 5-9, de este caos primitivo se formaron los mares, tanto los que están sobre la superficie de la tierra como los que están debajo de ella. Véase Sal 18.15 n.; Cf. también Sal 24.2.
[4] 1.2 La palabra hebrea traducida por espíritu puede significar también viento , soplo o aliento. Además, la expresión de Dios se utiliza a veces en el AT como complemento para expresar el superlativo (cf. Gn 10.9, donde gran cazador es lit. cazador de Dios ). Por eso, algunos intérpretes consideran que la parte final de este versículo significa un fuerte viento iba y venía sobre las aguas. Véase Gn 13.10 nota b.
[5] 1.3 Dijo Dios : Esta frase, corroborada por la frase complementaria Y fue así (cf. v. 7,9,11, etc.), pone de relieve el poder creador de la palabra de Dios. La orden divina se cumple en forma inmediata, y el efecto producido coincide con el pensamiento y la voluntad del Creador (cf. Sal 33.6-9; 148.5; Is 48.13; 55.10-11; Heb 11.3).
[6] 1.1-3 Jn 1.1-4.
[7] 1.3 2 Co 4.6.
[8] 1.4 Este relato de la creación insiste en afirmar que la obra realizada por Dios es buena (v. 4,10,12,18,21,25,31). El adjetivo bueno en el AT tiene varios significados, que comprenden desde lo moralmente correcto hasta lo bello, agradable y útil. En este pasaje se afirma que todo lo que existe es bueno , porque procede de Dios y corresponde a su propósito. Esta idea está en abierto contraste con los mitos paganos que hablan de un mundo creado por dioses caprichosos, o de un universo que existe sin propósito alguno o tiene incluso un carácter maligno.
[9] 1.5 Y fue la tarde y la mañana : lit. y anocheció y amaneció ; es decir, se completó un día. Véase. Sal 55.17 n.; 104.19 n.
[10] 1.5 Día : El relato bíblico distribuye las acciones creadoras de Dios en el marco de una semana, con seis días de trabajo y uno de descanso. En esos seis días están repartidas ocho obras: Las cuatro primeras consisten en separar y delimitar las zonas o regiones que configuran el mundo visible; las cuatro restantes están destinadas a poblar esas regiones con seres dotados de movimiento. Véase tabla La Creacíon.
[11] 1.6-8 La palabra hebrea traducida por firmamento designa algo expandido o estirado, como una lámina de metal batido a golpes de martillo. Esta idea estaría relacionada con una de las visiones que antiguamente se tenía del mundo según la cual el universo era una estructura compuesta de tres niveles: el cielo, la tierra y el mundo subterráneo (cf. Ex 20.4).
[12] 1.9 Cf. Job 38.8-11; Sal 104.6-9; Pr 8.27-30; Jer 5.22. Las aguas... debajo de los cielos : Véanse Gn 1.2 nota c ; 1.6-8 n.
[13] 1.11 Produzca la tierra : Dios ha concedido a algunos seres el don de la fecundidad, para que ellos continúen y completen la obra del Creador. Para los antiguos orientales la fecundidad era objeto de culto, porque la consideraban como una fuerza divina que residía en algunos seres (p. e., en la tierra). En el AT, en cambio, la fecundidad es una bendición otorgada por Dios. Véase Gn 1.28 nota u.
[14] 1.14-18 Los astros, que en las religiones del antiguo Oriente eran adorados como dioses, aquí son presentados como seres creados por Dios y no como fuerzas misteriosas que rigen el destino de las personas o como objetos de culto (cf. Dt 4.19). Cf. también Sal 8.3; Jer 31.35.
[15] 1.14 Señales para las estaciones : lit. los tiempos señalados , es decir, las estaciones del año y las fiestas religiosas correspondientes. Cf. Sal 81.3.
[16] 1.21 Los monstruos marinos son mencionados para indicar que también ellos han sido creados por Dios y están bajo su dominio. Aquí radica una de las principales diferencias entre este relato y el más famoso de los mitos babilónicos de la creación, según el cual la creación del mundo estuvo precedida por el nacimiento de varias generaciones de dioses y por la victoria del dios Marduc sobre el monstruo marino que era la personificación del caos originario. Por el contrario, Génesis habla de un único Dios, que existe desde siempre y que por sí mismo crea el universo con el poder de su palabra. Como todo lo que existe ha sido creado por Dios, ya no queda lugar para adorar a los fenómenos de la naturaleza o a cualquier otro ser animado o inanimado.
[17] 1.26 A nuestra imagen : Este plural, pronunciado por el único Dios, ha sido interpretado de diversas maneras. En realidad, parece sugerir la idea de una especial deliberación del Creador en el momento de crear el género humano. De entre todas las obras de Dios, solo la creación del ser humano es precedida por esta referencia a una solemne decisión divina.
[18] 1.26 Cf. Sal 8.4-8.
[19] 1.27 Hombre : Hebreos adam , designa aquí a todo el género humano; en otros pasajes, este mismo término tiene el valor de un nombre propio (Adán). Cf. Gn 4.25.
[20] 1.27 A su imagen, a imagen de Dios lo creó. Los seres humanos no son únicamente una creación especial de Dios (véase Gn 2.7 nota h ), sino que han sido creados a su imagen, es decir, están dotados de características tales que les permiten entrar en una relación personal con Dios y ejercer, como representantes suyos, el gobierno del mundo (v. 28). Cf. Gn 5.1; 9.6; 1 Co 11.7; Stg 3.9.
[21] 1.27 Varón y hembra : El texto señala expresamente que a la condición humana pertenece, por voluntad de Dios, el ser sexuado. Cf. Gn 2.18; Mt 19.4; Mc 10.6.
[22] 1.28 Gn 5.1-2. La bendición divina, en el AT, aparece vinculada con frecuencia al don de la fecundidad. Cf. Gn 17.16,20; 22.17; 26.12,24; 28.3. Véanse también Gn 49.22-26 n.; Sal 128 nota a.
[23] 1.28 Que se mueven : referencia a todos los seres terrestres. Otra posible traducción: que se arrastran.
[24] 1.29 Según algunos mitos muy difundidos en el antiguo Oriente, los dioses crearon a los humanos para que les proporcionaran alimento y realizaran los trabajos serviles que ellos necesitaban para su bienestar. Aquí, en cambio, Dios es el que proporciona todo lo necesario para el bienestar de los seres humanos, ya que el Creador no padece ninguna necesidad. Cf. Sal 50.9-13.
[25] 1.31 Todo... era bueno en gran manera : Este superlativo se refiere, probablemente, no a una obra de Dios en particular, sino al conjunto de la creación. Véase 1.4 n.</p>
<br/>




</div>
